### ISSUE TITLE
Vercel Edge Error: Dynamic require crypto is not supported

### ISSUE THREAD

**Issue by brittianwarner** [sveltejs/kit#10107]
### Describe the bug

I am currently trying to leverage edge functions however, I am getting the following error after a successful build and deploy when trying to access the route that is configured with the edge runtime:

```
Error: Dynamic require of "crypto" is not supported
    at (../../../../.svelte-kit/vercel-tmp/fn-5/edge.js:13:7)
    at (../../../../node_modules/@hapi/iron/lib/index.js:3:15)
    at (../../../../.svelte-kit/vercel-tmp/fn-5/edge.js:13:7)
    at (../../../../.svelte-kit/output/server/chunks/cookie.js:1:61)
    at (../../../../.svelte-kit/vercel-tmp/fn-5/edge.js:13:7)
    at (../../../../.svelte-kit/output/server/chunks/hooks.server.js:1:0)
    at (../../../../.svelte-kit/vercel-tmp/fn-5/edge.js:13:7)
    at (../../../../.svelte-kit/output/server/chunks/internal.js:92:47)
    at (../../../../.svelte-kit/output/server/index.js:45:11981)
    at (../../../../.svelte-kit/vercel-tmp/fn-5/edge.js:14:1)
```

My feeling is it's something with @hapi/iron library which I'm using to decrypt encrypted cookies in my hooks.server.js file. 

In my test I created a simple route:
![image](https://github.com/sveltejs/kit/assets/18333842/d54cf673-d752-447e-beb7-fbd8c471d7eb)

Here is the config in the page.js file:
```
export const config = {
	runtime: 'edge',
	external: ['stream', 'crypto', 'os', 'path', 'fs', 'http', 'https']
};
```

I am including the externals as I was getting errors during the build and from my understanding this is what that property is for (But could be wrong).

### Reproduction

https://github.com/livlabs/edge-issue-repro

The error appears when you go to this page: https://edge-issue-repro.sitepreview.page/sverdle

### Logs

```Shell
[GET] /sverdle/__data.json?x-sveltekit-invalidated=01 reason=EDGE_FUNCTION_INVOCATION_FAILED, status=500, user_error=true
```
```
Error: Dynamic require of "crypto" is not supported
    at (../../../../.svelte-kit/vercel-tmp/fn/edge.js:13:7)
    at (../../../../node_modules/@hapi/iron/lib/index.js:3:15)
    at (../../../../.svelte-kit/vercel-tmp/fn/edge.js:13:7)
    at (../../../../.svelte-kit/output/server/chunks/hooks.server.js:1:17)
    at (../../../../.svelte-kit/vercel-tmp/fn/edge.js:13:7)
    at (../../../../.svelte-kit/output/server/chunks/internal.js:176:9)
    at (../../../../.svelte-kit/output/server/index.js:2689:23)
    at (../../../../.svelte-kit/vercel-tmp/fn/edge.js:14:1)
```
```


### System Info

```Shell
Chrome Version 113.0.5672.134 (Official Build) (64-bit)
```

### Severity

serious, but I can work around it

### Additional Information

My app is up and fully functional without the use of edge functions, however, I would love to be able to leverage edge functions for our app.

**Comment by ghostdevv** [comment]
Iron is trying to use node's crypto module, which vercel [doesn't seem to support](https://vercel.com/docs/concepts/functions/edge-functions/edge-runtime#compatible-node.js-modules). They also mention (as you have run into) you [can't call require](https://vercel.com/docs/concepts/functions/edge-functions/edge-runtime#unsupported-apis).

You may have to polyfill `node:crypto` here or switch to a different library - I am not sure

**Comment by brittianwarner** [comment]
I am going to try using `js-cookie` and `crypto-js` and see if I can get a working version. Let me know if anyone recommends another alternative to `@hapi/iron` for encrypting and decrypting cookies. I'll report back.

**Comment by brittianwarner** [comment]
Replacing `@hapi/iron` seems to have done the trick. Thanks, @ghostdevv! Much easier than I expected.
