### ISSUE TITLE
Impossible to delete cookies on the server

### ISSUE THREAD

**Issue by ramory-l** [sveltejs/kit#10137]
### Describe the bug

Function cookies.delete("accessToken") doesn't work on my server after deploy.
**It's very strange, but locally everything works fine.**

BTW: The same problem was with function **cookies.set()** (**only after deploy, locally works fine even without opts**). But when I add opts:
```
{
	httpOnly: true,
	sameSite: "strict",
	secure: false,
	path: "/",
	maxAge: Number(env.ACCESS_TOKEN_MAX_AGE),
}
```
cookies are set properly.

### Reproduction

logout/+page.server.ts
```
import { postRequest } from "$lib/server/api";
import type { PageServerLoad } from "./$types";
import { redirect } from "@sveltejs/kit";

export const load = (async ({ cookies }) => {
	const accessToken = cookies.get("accessToken");
	const refreshToken = cookies.get("refreshToken");

	cookies.delete("accessToken", { path: "/" });
	cookies.delete("refreshToken", { path: "/" });

	const response = await postRequest(
		"auth/invalidate-refresh-token",
		{ refreshToken },
		{ Authorization: `Bearer ${accessToken}` },
	);

	if (response.status === 204) {
		throw redirect(302, "/sign-in");
	}
}) satisfies PageServerLoad;
```
sign-in/+page.server.ts
```
import { env } from "$env/dynamic/private";
import { postRequest } from "$lib/server/api";
import type { Actions } from "./$types";
import { fail, redirect } from "@sveltejs/kit";

export const actions = {
	default: async ({ cookies, request }) => {
		const data = await request.formData();
		const username = data.get("username");
		const password = data.get("password");

		const response = await postRequest("auth/sign-in", {
			username,
			password,
		});

		if (response.status === 200) {
			const tokens = await response.json();

			cookies.set("accessToken", tokens.accessToken, {
				httpOnly: true,
				sameSite: "strict",
				secure: false,
				path: "/",
				maxAge: Number(env.ACCESS_TOKEN_MAX_AGE),
			});

			cookies.set("refreshToken", tokens.refreshToken, {
				httpOnly: true,
				sameSite: "strict",
				secure: false,
				path: "/",
				maxAge: Number(env.REFRESH_TOKEN_MAX_AGE),
			});

			throw redirect(303, "/profile");
		} else {
			return fail(response.status, {
				message: "Wrong username or password!",
			});
		}
	},
} satisfies Actions;
```

### Logs

```Shell
# Sometimes
Error: Missing +page.svelte component for route /logout
    at Module.render_response (/node_modules/.pnpm/@sveltejs+kit@1.5.0_svelte@3.54.0_vite@4.2.2/node_modules/@sveltejs/kit/src/runtime/server/page/render.js:83:10)
    at Module.render_page (/node_modules/.pnpm/@sveltejs+kit@1.5.0_svelte@3.54.0_vite@4.2.2/node_modules/@sveltejs/kit/src/runtime/server/page/index.js:303:15)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async resolve (/node_modules/.pnpm/@sveltejs+kit@1.5.0_svelte@3.54.0_vite@4.2.2/node_modules/@sveltejs/kit/src/runtime/server/respond.js:363:17)
    at async Module.respond (/node_modules/.pnpm/@sveltejs+kit@1.5.0_svelte@3.54.0_vite@4.2.2/node_modules/@sveltejs/kit/src/runtime/server/respond.js:234:20)
    at async file:///usr/src/app/node_modules/.pnpm/@sveltejs+kit@1.5.0_svelte@3.54.0_vite@4.2.2/node_modules/@sveltejs/kit/src/exports/vite/dev/index.js:495:22
```

### System Info

```Shell
My Dockerfile:
FROM node:19-alpine
LABEL name=svelteapp
RUN npm i -g pnpm
WORKDIR /usr/src/app
COPY package.json pnpm-lock.yaml ./
RUN pnpm i --frozen-lockfile
COPY . .
RUN pnpm run build
EXPOSE 8081
CMD ["pnpm", "run", "dev"]
```

### Severity

blocking all usage of SvelteKit

### Additional Information

Deploying to docker swarm.
docker-compose.yml:
```
version: '3'

services:
  admin_panel:
    environment:
      - ACCESS_TOKEN_MAX_AGE=$ACCESS_TOKEN_MAX_AGE
      - REFRESH_TOKEN_MAX_AGE=$REFRESH_TOKEN_MAX_AGE
    image: myimage // look for Dockerfile in system info
    ports:
      - 8081:8081
```

**Comment by ramory-l** [comment]
That was my mistake. Cookies delete/set only on localhost because of security. https://stackoverflow.com/questions/75045021/cookies-are-not-getting-set-when-running-with-host-option-in-official-svelteki
