### ISSUE TITLE
Error on non-existent pages.

### ISSUE THREAD

**Issue by kadenscott** [sveltejs/kit#1015]
**Describe the bug**
When setting up a fresh unmodified install of SvelteKit using the given install directions on the [documentation page](https://kit.svelte.dev/docs#introduction-getting-started), all non-index pages (pages that don't exist, rather?) result in an error. I am unsure if this is an issue with SvelteKit or Svelte, as I'm not very familiar with this project.

To clarify, I am on SvelteKit `v1.0.0-next.74` as reported from `npm run dev`.
**Logs**
Nothing (no errors) is printed to the console when visiting a page that does not exist.
The following error is displayed on the page when visiting a page that does not exist:
```
TypeError: Cannot read property 'message' of undefined
    at eval (C:\Users\kscott-laptop-window\projects\test\.svelte\dev\components\error.svelte:15:41)
    at Object.$$render (C:\Users\kscott-laptop-window\projects\test\node_modules\svelte\internal\index.js:1369:22)
    at Object.default (/C:\Users\kscott-laptop-window\projects\test\.svelte\dev/generated/root.svelte:57:127)
    at eval (C:\Users\kscott-laptop-window\projects\test\src\routes\$layout.svelte:11:41)
    at Object.$$render (C:\Users\kscott-laptop-window\projects\test\node_modules\svelte\internal\index.js:1369:22)
    at eval (/C:\Users\kscott-laptop-window\projects\test\.svelte\dev/generated/root.svelte:55:122)
    at $$render (C:\Users\kscott-laptop-window\projects\test\node_modules\svelte\internal\index.js:1369:22)
    at Object.render (C:\Users\kscott-laptop-window\projects\test\node_modules\svelte\internal\index.js:1377:26)
    at render_response (file:///C:/Users/kscott-laptop-window/projects/test/node_modules/@sveltejs/kit/dist/ssr.js:377:28)
    at async respond_with_error (file:///C:/Users/kscott-laptop-window/projects/test/node_modules/@sveltejs/kit/dist/ssr.js:2572:10)
```
**To Reproduce**
- Follow the instructions on the [Getting Started documentation page](https://kit.svelte.dev/docs#introduction-getting-started)
  - `mkdir my-app`
  - `cd my-app`
  - `npm init svelte@next`
  - `npm install`
  - `npm run dev`
- After the dev server starts, visit a non-existent page (i.e. `localhost:3000/hello`)

**Expected behavior**
No error should be displayed.

**Severity**
This bug, while not preventing me from developing the pages I want to develop, confuses me whether I need to create a 404 route, or there is something more going on. A more graceful error should be provided at least, imo.

**Comment by kadenscott** [comment]
As #996 appears to cover this issue and provides a fix for this, I will close this.
