### ISSUE TITLE
Build failure with node-ssh or ssh2 npm packages

### ISSUE THREAD

**Issue by figuerom16** [sveltejs/kit#10182]
### Describe the bug

Bug seems to be related to the @sveltejs/adapter-node as node-ssh/ssh2 can build in Vite.  npm run dev works perfectly with my full application without issue.

Including the below line in +page.server.ts or +server.ts causes build failure.
`import { NodeSSH } from 'node-ssh';`

error during build:
RollupError: Unexpected character ''...

### Reproduction

https://gitlab.com/figuerom16/nodesshbug
Minimal reproduction steps.  Simply install and attempt to build it.

Reproduction uses new SvelteKit barebones:
npm i -D @sveltejs/adapter-node node-ssh
svelte.config.js is changed to adapter-node
added one file src/routes/+pages.server.ts with a single line `import { NodeSSH } from 'node-ssh';`

### Logs

```Shell
> nodesshbug@0.0.1 build
> vite build


vite v4.3.9 building SSR bundle for production...
transforming (45) src/routes/+page.server.ts"NodeSSH" is imported from external module "node-ssh" but never used in "src/routes/+page.server.ts".
✓ 50 modules transformed.

vite v4.3.9 building for production...
✓ 40 modules transformed.
.svelte-kit/output/client/_app/version.json                              0.03 kB │ gzip: 0.05 kB
.svelte-kit/output/client/vite-manifest.json                             1.83 kB │ gzip: 0.37 kB
.svelte-kit/output/client/_app/immutable/nodes/0.6ca3df57.js             0.55 kB │ gzip: 0.37 kB
.svelte-kit/output/client/_app/immutable/nodes/2.ad52e74a.js             0.83 kB │ gzip: 0.48 kB
.svelte-kit/output/client/_app/immutable/nodes/1.868e16d9.js             0.98 kB │ gzip: 0.57 kB
.svelte-kit/output/client/_app/immutable/chunks/singletons.26ad1706.js   2.85 kB │ gzip: 1.46 kB
.svelte-kit/output/client/_app/immutable/entry/app.ad8050cf.js           5.50 kB │ gzip: 2.19 kB
.svelte-kit/output/client/_app/immutable/chunks/index.6dba6488.js        7.06 kB │ gzip: 2.86 kB
.svelte-kit/output/client/_app/immutable/entry/start.73378873.js        23.98 kB │ gzip: 9.51 kB
✓ built in 397ms
.svelte-kit/output/server/vite-manifest.json                   1.46 kB
.svelte-kit/output/server/entries/pages/_page.server.ts.js     0.02 kB
.svelte-kit/output/server/internal.js                          0.19 kB
.svelte-kit/output/server/entries/fallbacks/layout.svelte.js   0.24 kB
.svelte-kit/output/server/entries/pages/_page.svelte.js        0.31 kB
.svelte-kit/output/server/entries/fallbacks/error.svelte.js    0.89 kB
.svelte-kit/output/server/chunks/index.js                      3.27 kB
.svelte-kit/output/server/chunks/internal.js                   5.37 kB
.svelte-kit/output/server/index.js                            86.40 kB

Run npm run preview to preview your production build locally.

> Using @sveltejs/adapter-node
error during build:
RollupError: Unexpected character '' (Note that you need plugins to import files that are not JavaScript)
    at error (file:///home/matt/Documents/sveltekit/nodesshbug/node_modules/rollup/dist/es/shared/node-entry.js:2213:30)
    at Module.error (file:///home/matt/Documents/sveltekit/nodesshbug/node_modules/rollup/dist/es/shared/node-entry.js:13537:16)
    at Module.tryParse (file:///home/matt/Documents/sveltekit/nodesshbug/node_modules/rollup/dist/es/shared/node-entry.js:14263:25)
    at Module.setSource (file:///home/matt/Documents/sveltekit/nodesshbug/node_modules/rollup/dist/es/shared/node-entry.js:13864:39)
    at ModuleLoader.addModuleSource (file:///home/matt/Documents/sveltekit/nodesshbug/node_modules/rollup/dist/es/shared/node-entry.js:24011:20)
```

### System Info

```Shell
System:
    OS: Linux 6.2 Pop!_OS 22.04 LTS
    CPU: (12) x64 AMD Ryzen 5 PRO 4650G with Radeon Graphics
    Memory: 18.45 GB / 27.27 GB
    Container: Yes
    Shell: 5.1.16 - /bin/bash
  Binaries:
    Node: 20.3.0 - /usr/bin/node
    npm: 9.6.7 - /usr/bin/npm
  Browsers:
    Firefox: 114.0.1
  npmPackages:
    @sveltejs/adapter-node: ^1.2.4 => 1.2.4 
    @sveltejs/kit: ^1.5.0 => 1.20.4 
    svelte: ^3.54.0 => 3.59.1 
    vite: ^4.3.0 => 4.3.9
```

### Severity

annoyance

**Comment by ghostdevv** [comment]
I'm not sure exactly why rollup is failing when using the node adapter. However a workaround is to install `node-ssh` as a regular dependancy so the node adapter won't try and bundle it with rollup. The disadvantage of this is that wherever you deploy your node server you will need to make sure you have `node-ssh` installed.

**Comment by figuerom16** [comment]
@ghostdevv Changing node-ssh to a regular dependency works perfectly.  It installs fine with npm install && npm run build and the node server works with it this way.  I think this could be the solution in this niche case.

**Comment by ghostdevv** [comment]
Awesome

**Comment by acoreyj** [comment]
@ghostdevv @figuerom16 

What is meant by "regular dependency" in this case. Having this issue with ssh2-sftp-client
