### ISSUE TITLE
Feature request: setting to only show first few lines of SSR stack trace instead of all of them

### ISSUE THREAD

**Issue by henrikvilhelmberglund** [sveltejs/kit#10200]
### Describe the problem

When I get an error using SSR I usually have to make the console window a lot bigger or scroll a lot to see the actual error. I would like a setting that makes the output a bit more minified, only showing the error and maybe the file name (if available).
Here's an example:
```
ReferenceError: rawCode is not defined
    at eval (eval at instantiateModule (file:///C:/Github/Tutorials/node_modules/vite/dist/node/chunks/dep-33545781.js:54349:28), <anonymous>:42:15)
    at Object.$$render (/node_modules/svelte/internal/index.mjs:1999:22)
    at eval (/src/routes/svelte-course/[slug]/+page.svelte:26:127)
    at Object.$$render (/node_modules/svelte/internal/index.mjs:1999:22)
    at Object.default (/.svelte-kit/generated/root.svelte:88:142)
    at eval (/node_modules/@sveltejs/kit/src/runtime/components/layout.svelte:8:41)
    at Object.$$render (/node_modules/svelte/internal/index.mjs:1999:22)
    at Object.default (/.svelte-kit/generated/root.svelte:77:133)
    at eval (/src/routes/+layout.svelte:31:32)
    at Object.$$render (/node_modules/svelte/internal/index.mjs:1999:22)
    at eval (/.svelte-kit/generated/root.svelte:65:129)
    at $$render (/node_modules/svelte/internal/index.mjs:1999:22)
    at Object.render (/node_modules/svelte/internal/index.mjs:2007:26)
    at Module.render_response (/node_modules/@sveltejs/kit/src/runtime/server/page/render.js:185:29)
    at async Module.render_page (/node_modules/@sveltejs/kit/src/runtime/server/page/index.js:295:10)
    at async resolve (/node_modules/@sveltejs/kit/src/runtime/server/respond.js:405:17)
    at async Module.respond (/node_modules/@sveltejs/kit/src/runtime/server/respond.js:274:20)
    at async file:///C:/Github/Tutorials/node_modules/@sveltejs/kit/src/exports/vite/dev/index.js:505:22
```
Maybe this stack trace is because I'm using mdsvex and some spicy stuff like that but I think it's pretty huge. Generally when I get an SSR error I have to first clear the console (or try very hard to grab the scroll handle), if I cleared then refresh, then scroll so I can see the actual error at the top of the stack trace. It can be a bit hard to see the actual stack trace if there are several stack traces in a row too.

In this case the error is very easy to understand `ReferenceError: rawCode is not defined` so I just need to see this to be able to fix it but it's made a bit harder by the stack trace itself being so big.

### Describe the proposed solution

I would like to see a setting that changes the SSR stack trace to be much smaller and only include the error and the closest file that triggered it, something like this:
```
ReferenceError: rawCode is not defined
    at eval (/src/routes/svelte-course/[slug]/+page.svelte:26:127)
```

### Alternatives considered

My current alternative is to disable SSR to see the errors more clearly in the browser, it works but feels a bit silly.

### Importance

would make my life easier

**Comment by Conduitry** [comment]
I don't think we want to be trying to mess with the native Node stack trace for things. There are also a lot of situations where the immediate exception being thrown is not that helpful, and so people would probably need to be editing this setting repeatedly in order to debug both types of errors.

If you don't want to pixel hunt for the scroll bar, can you not (a) make your scroll bad bigger, or (b) just use your mouse wheel?

**Comment by henrikvilhelmberglund** [comment]
That makes sense! Yes I can make it a bit nicer but it won't super nice overall.

Anyway, I did find a workaround, you can put `Error.stackTraceLimit = 0;` in the code and it will only show the error itself, then when you need longer stack traces you can set it back to `Error.stackTraceLimit = Infinity;` or something.
