### ISSUE TITLE
Migration to Svelte 4 fails if a project doesn’t have `dependencies`

### ISSUE THREAD

**Issue by malinowskip** [sveltejs/kit#10220]
### Describe the bug

Migration to Svelte 4 using `svelte-migrate` fails if the project’s `package.json` doesn’t have `dependencies`. The error occurs here (the script attempts to read the package name on `undefined`):

https://github.com/sveltejs/kit/blob/c52bd3d2872a53e61ff2955a19c72e261fd9fe3a/packages/migrate/migrations/svelte-4/migrate.js#L24

### Reproduction

Run `npx svelte-migrate svelte-4` in a project that does not have `dependencies` in its `package.json`.

### Logs

```Shell
file:///Users/pm/.npm/_npx/ca732f115159e57c/node_modules/svelte-migrate/migrations/svelte-4/migrate.js:24
		if (pkg.dependencies[name]) {
		                    ^

TypeError: Cannot read properties of undefined (reading 'svelte')
    at update_pkg (file:///Users/pm/.npm/_npx/ca732f115159e57c/node_modules/svelte-migrate/migrations/svelte-4/migrate.js:24:23)
    at update_pkg_json_content (file:///Users/pm/.npm/_npx/ca732f115159e57c/node_modules/svelte-migrate/migrations/svelte-4/migrate.js:34:2)
    at update_pkg_json (file:///Users/pm/.npm/_npx/ca732f115159e57c/node_modules/svelte-migrate/migrations/svelte-4/migrate.js:7:3)
    at migrate (file:///Users/pm/.npm/_npx/ca732f115159e57c/node_modules/svelte-migrate/migrations/svelte-4/index.js:59:2)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
```

### System Info

```Shell
System:
    OS: macOS 13.4
    CPU: (8) arm64 Apple M1
    Memory: 85.78 MB / 16.00 GB
    Shell: 3.6.1 - /opt/homebrew/bin/fish
  Binaries:
    Node: 20.3.0 - /opt/homebrew/bin/node
    Yarn: 1.22.19 - /opt/homebrew/bin/yarn
    npm: 9.6.7 - /opt/homebrew/bin/npm
  Browsers:
    Chrome: 114.0.5735.133
    Edge: 114.0.1823.37
    Safari: 16.5
  npmPackages:
    @sveltejs/adapter-auto: 1.0.0-next.90 => 1.0.0-next.90
    @sveltejs/adapter-static: 1.0.0-next.49 => 1.0.0-next.49
    @sveltejs/kit: ^1.20.4 => 1.20.4
    svelte: ^3.59.2 => 3.59.2
    vite: ^4.3.9 => 4.3.9
```

### Severity

blocking an upgrade

**Comment by gtm-nayan** [comment]
Released in svelte-migrate@1.2.3, you might want to specify the version number to avoid any caching
