### ISSUE TITLE
export const prerender = true not working

### ISSUE THREAD

**Issue by gigitalz** [sveltejs/kit#10302]
### Describe the bug

I am trying to render a static route with:

export const prerender = true;

inserted inside page.ts.

### Reproduction

-

### Logs

```Shell
node:internal/event_target:1006
  process.nextTick(() => { throw err; });
                           ^
Error: The following routes were marked as prerenderable, but were not prerendered because they were not found while crawling your app:
  - /terms

See https://kit.svelte.dev/docs/page-options#prerender-troubleshooting for info on how to solve this
    at prerender (file:///C:/Backup/Projects/Crypto/tier10k/webapp/node_modules/@sveltejs/kit/src/core/postbuild/prerender.js:475:9)
    at async MessagePort.<anonymous> (file:///C:/Backup/Projects/Crypto/tier10k/webapp/node_modules/@sveltejs/kit/src/utils/fork.js:22:16)
Emitted 'error' event on Worker instance at:
    at [kOnErrorMessage] (node:internal/worker:290:10)
    at [kOnMessage] (node:internal/worker:301:37)
    at MessagePort.<anonymous> (node:internal/worker:202:57)
    at [nodejs.internal.kHybridDispatch] (node:internal/event_target:731:20)
    at exports.emitMessage (node:internal/per_context/messageport:23:28)
```

### System Info

```Shell
System:
    OS: Windows 10 10.0.19045
    CPU: (32) x64 AMD Ryzen 9 5950X 16-Core Processor
    Memory: 35.78 GB / 63.92 GB
  Binaries:
    Node: 18.12.1 - C:\Program Files\nodejs\node.EXE
    npm: 8.19.2 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Edge: Spartan (44.19041.1266.0), Chromium (114.0.1823.67)
  npmPackages:
    @sveltejs/adapter-node: ^1.2.4 => 1.2.4
    @sveltejs/kit: ^1.20.4 => 1.21.0
    svelte: ^4.0.0 => 4.0.1
    vite: ^4.3.6 => 4.3.9
```

### Severity

serious, but I can work around it

**Comment by Conduitry** [comment]
Did you read the documentation linked to in the errors message?

GitHub issues aren't the right place for support questions like this. Please ask on StackOverflow or in our [Discord chat room](https://svelte.dev/chat). And when you do, provide a reproduction, or they won't be able to help you either.
