### ISSUE TITLE
Supabase fails to import

### ISSUE THREAD

**Issue by cjsmocjsmo** [sveltejs/kit#10321]
### Describe the bug

While following the Supabase/Sveltekit tutorial found [here](https://supabase.com/docs/guides/getting-started/quickstarts/sveltekit)
I get the following error:

`"default" is not exported by "src/lib/supabaseClient.js", imported by "src/routes/reviewspage/+page.server.js"`

### Reproduction

.env contains:

`PUBLIC_SUPABASE_ADDR="my-supabase-addr"
PUBLIC_SUPABASE_KEY="my-supabase-key"
`

/lib/supabaseClient.js contains:

`import { createClient } from "@supabase/supabase-js";
import { PUBLIC_SUPABASE_ADDR } from "$env/static/public";
import { PUBLIC_SUPABASE_KEY } from "$env/static/public";

export const supabase = createClient(PUBLIC_SUPABASE_ADDR, PUBLIC_SUPABASE_KEY);`

/src/routes/reviewspage/+page.server.js contains:

`import supabase from '$lib/supabaseClient.js';

export async function load() {
	const { data } = await supabase.from('reviews').select('*');
	console.log(data);
	return { data };
}`

### Logs

```Shell
npm run build

> ats-svelte-google@0.0.1 build
> vite build


vite v4.3.9 building SSR bundle for production...
✓ 327 modules transformed.
✓ built in 14.09s
"default" is not exported by "src/lib/supabaseClient.js", imported by "src/routes/reviewspage/+page.server.js".
file: /media/charliepi/HD/ats/ats-svelte-google/src/routes/reviewspage/+page.server.js:1:7
1: import supabase from '$lib/supabaseClient.js';
          ^
2: 
3: export async function load() {
error during build:
RollupError: "default" is not exported by "src/lib/supabaseClient.js", imported by "src/routes/reviewspage/+page.server.js".
    at error (file:///media/charliepi/HD/ats/ats-svelte-google/node_modules/rollup/dist/es/shared/node-entry.js:2245:30)
    at Module.error (file:///media/charliepi/HD/ats/ats-svelte-google/node_modules/rollup/dist/es/shared/node-entry.js:13572:16)
    at Module.traceVariable (file:///media/charliepi/HD/ats/ats-svelte-google/node_modules/rollup/dist/es/shared/node-entry.js:13997:29)
    at ModuleScope.findVariable (file:///media/charliepi/HD/ats/ats-svelte-google/node_modules/rollup/dist/es/shared/node-entry.js:12515:39)
    at FunctionScope.findVariable (file:///media/charliepi/HD/ats/ats-svelte-google/node_modules/rollup/dist/es/shared/node-entry.js:7073:38)
    at ChildScope.findVariable (file:///media/charliepi/HD/ats/ats-svelte-google/node_modules/rollup/dist/es/shared/node-entry.js:7073:38)
    at MemberExpression.bind (file:///media/charliepi/HD/ats/ats-svelte-google/node_modules/rollup/dist/es/shared/node-entry.js:9450:49)
    at CallExpression.bind (file:///media/charliepi/HD/ats/ats-svelte-google/node_modules/rollup/dist/es/shared/node-entry.js:5841:23)
    at CallExpression.bind (file:///media/charliepi/HD/ats/ats-svelte-google/node_modules/rollup/dist/es/shared/node-entry.js:9801:15)
    at MemberExpression.bind (file:///media/charliepi/HD/ats/ats-svelte-google/node_modules/rollup/dist/es/shared/node-entry.js:5841:23)
```

### System Info

```Shell
System:
    OS: Linux 6.2 Ubuntu 23.04 23.04 (Lunar Lobster)
    CPU: (4) arm64 Cortex-A72
    Memory: 3.90 GB / 7.63 GB
    Container: Yes
    Shell: 5.2.15 - /bin/bash
  Binaries:
    Node: 18.13.0 - /usr/bin/node
    npm: 9.2.0 - /usr/bin/npm
  Browsers:
    Chromium: 114.0.5735.198
  npmPackages:
    @sveltejs/adapter-auto: ^2.0.0 => 2.1.0 
    @sveltejs/adapter-static: ^2.0.2 => 2.0.2 
    @sveltejs/kit: ^1.20.4 => 1.21.0 
    svelte: ^4.0.0 => 4.0.3 
    vite: ^4.3.6 => 4.3.9
```

### Severity

annoyance

**Comment by PuruVJ** [comment]
You forgot to put `{ }`  around supabase in your import statement in the `+page.svelte`. It should be `import { supabase } from '$lib/supabaseClient.js'`

FYI, this is not a question for kit, recommend asking in [discord](https://svelte.dev/chat) chat in future :)

**Comment by cjsmocjsmo** [comment]
Thank you so much. I've been banging my head on this one for 2 days now, and come to find out it's something so simple :)

Sorry for the noise.

FYI Discord hates me and I hate Discord.  This is the only other form of communication available :)

**Comment by geoffrich** [comment]
In the future, support questions like this should not be opened as issues. If you don't want to use Discord, you can also open a [discussion](https://github.com/sveltejs/kit/discussions) on the repo.
