### ISSUE TITLE
Preview not working (npm run preview)

### ISSUE THREAD

**Issue by talgolan** [sveltejs/kit#10334]
### Describe the bug

The following occurs after a completely fresh installation.

npm run preview

error when starting preview server:
Error [ERR_MODULE_NOT_FOUND]: Cannot find module '/Volumes/.../zzz/.svelte-kit/output/server/internal.js' imported from /Volumes/.../zzz/node_modules/@sveltejs/kit/src/exports/vite/preview/index.js
    at new NodeError (node:internal/errors:399:5)
    at finalizeResolution (node:internal/modules/esm/resolve:232:11)
    at moduleResolve (node:internal/modules/esm/resolve:850:10)
    at defaultResolve (node:internal/modules/esm/resolve:1070:11)
    at DefaultModuleLoader.resolve (node:internal/modules/esm/loader:306:12)
    at DefaultModuleLoader.getModuleJob (node:internal/modules/esm/loader:155:32)
    at DefaultModuleLoader.import (node:internal/modules/esm/loader:265:12)
    at importModuleDynamically (node:internal/modules/esm/translators:107:35)
    at importModuleDynamicallyCallback (node:internal/modules/esm/utils:87:14)
    at preview (file:///Volumes/.../zzz/node_modules/@sveltejs/kit/src/exports/vite/preview/index.js:40:77)

### Reproduction

npm create svelte@latest zzz
cd zzz
npm install
npm run dev <-- this works
npm run preview <-- this fails with the error shared above.

### Logs

```Shell
npm run preview

> zzz@0.0.1 preview
> vite preview


error when starting preview server:
Error [ERR_MODULE_NOT_FOUND]: Cannot find module '/Volumes/.../zzz/.svelte-kit/output/server/internal.js' imported from /Volumes/.../zzz/node_modules/@sveltejs/kit/src/exports/vite/preview/index.js
    at new NodeError (node:internal/errors:399:5)
    at finalizeResolution (node:internal/modules/esm/resolve:232:11)
    at moduleResolve (node:internal/modules/esm/resolve:850:10)
    at defaultResolve (node:internal/modules/esm/resolve:1070:11)
    at DefaultModuleLoader.resolve (node:internal/modules/esm/loader:306:12)
    at DefaultModuleLoader.getModuleJob (node:internal/modules/esm/loader:155:32)
    at DefaultModuleLoader.import (node:internal/modules/esm/loader:265:12)
    at importModuleDynamically (node:internal/modules/esm/translators:107:35)
    at importModuleDynamicallyCallback (node:internal/modules/esm/utils:87:14)
    at preview (file:///Volumes/.../zzz/node_modules/@sveltejs/kit/src/exports/vite/preview/index.js:40:77)
```

### System Info

```Shell
System:
    OS: macOS 13.4.1
    CPU: (8) x64 Intel(R) Core(TM) i7-8569U CPU @ 2.80GHz
    Memory: 22.07 MB / 16.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 20.0.0 - /usr/local/opt/nvm/versions/node/v20.0.0/bin/node
    npm: 9.6.7 - /usr/local/opt/nvm/versions/node/v20.0.0/bin/npm
    pnpm: 8.6.6 - ~/Library/pnpm/pnpm
  Browsers:
    Chrome: 114.0.5735.198
    Safari: 16.5.1
  npmPackages:
    @sveltejs/adapter-auto: ^2.0.0 => 2.1.0
    @sveltejs/kit: ^1.20.4 => 1.22.1
    svelte: ^4.0.0 => 4.0.5
    vite: ^4.3.6 => 4.4.1
```

### Severity

blocking all usage of SvelteKit

**Comment by ghostdevv** [comment]
I think you forgot to run `npm run build`? That's the only way I can reproduce this

**Comment by Conduitry** [comment]
Whoops, yup, lol, I fell into the same trap when I followed the instructions in the repro.

Maybe we can do something to provide a more helpful error if there's no built application present.

**Comment by gtm-nayan** [comment]
> Maybe we can do something to provide a more helpful error if there's no built application present.

Yeah, has come up a few times. I was just doing that.

**Comment by talgolan** [comment]
Thanks.

npm run build
npm run preview

Problem solved.

**Comment by talgolan** [comment]
Perhaps this addition requirement should be included with the instructions that are provide when the following completes...

npm create svelte@latest <name>
