### ISSUE TITLE
Port forwarding on Chrome throws errors when getting /json and /json/version

### ISSUE THREAD

**Issue by itsthesteve** [sveltejs/kit#10428]
### Describe the bug

I ran into a non-breaking issue while testing a SvelteKit app when using Chrome to port forward to test on a physical phone. When `chrome://inspect` is open and ports are forwarded, there are recurring errors for failures to request `/json` and `/json/version` in the terminal. It doesn't seem to break functionality, but floods the terminal output with the same recurring error message.

I searched Google with a variety of terms as well as the open/closed issues without luck on anyone else running into the same thing, so I'm inclined to think that I'm missing something obvious, i.e. a port I'm unaware of.

I tried looking at what ports are opened when running the server, digging into the source to see if there was another port defined somewhere, etc but couldn't find anything. My network-foo isn't great.

### Reproduction

- Create a new Sveltekit app with `npm create svelte@latest port-forward`

Output:

```
npm create svelte@latest port-forward
Need to install the following packages:
  create-svelte@5.0.3
Ok to proceed? (y)

create-svelte version 5.0.3

┌  Welcome to SvelteKit!
│
◇  Which Svelte app template?
│  Skeleton project
│
◇  Add type checking with TypeScript?
│  Yes, using JavaScript with JSDoc comments
│
◇  Select additional options (use arrow keys/space bar)
│  none
│
└  Your project is ready!

✔ Type-checked JavaScript
  https://www.typescriptlang.org/tsconfig#checkJs

Install community-maintained integrations:
  https://github.com/svelte-add/svelte-add

Next steps:
  1: cd port-forward
  2: npm install (or pnpm install, etc)
  3: git init && git add -A && git commit -m "Initial commit" (optional)
  4: npm run dev -- --open

To close the dev server, hit Ctrl-C

Stuck? Visit us at https://svelte.dev/chat➤
```

- Run `cd port-forward; npm install`
- Run `npm run dev`
- Open `chrome://inspect` and forward `5173` to `localhost:5173` (the other listed ports in the following image are for Firebase emulators)

<img width="330" alt="Screen Shot 2023-07-23 at 9 11 38 PM" src="https://github.com/sveltejs/kit/assets/2624740/56591747-6d6d-4973-b0b4-4e0a1f02d4d9">

### Logs

```Shell
VITE v4.4.6  ready in 1206 ms

  ➜  Local:   http://localhost:5173/
  ➜  Network: use --host to expose
  ➜  press h to show help
Error: Not found: /json/version
    at resolve (/Users/steve/Projects/web/_sandbox/port-forward/node_modules/@sveltejs/kit/src/runtime/server/respond.js:480:13)
    at resolve (/Users/steve/Projects/web/_sandbox/port-forward/node_modules/@sveltejs/kit/src/runtime/server/respond.js:282:5)
    at #options.hooks.handle (/Users/steve/Projects/web/_sandbox/port-forward/node_modules/@sveltejs/kit/src/runtime/server/index.js:56:56)
    at Module.respond (/Users/steve/Projects/web/_sandbox/port-forward/node_modules/@sveltejs/kit/src/runtime/server/respond.js:279:40)
Error: Not found: /json
    at resolve (/Users/steve/Projects/web/_sandbox/port-forward/node_modules/@sveltejs/kit/src/runtime/server/respond.js:480:13)
    at resolve (/Users/steve/Projects/web/_sandbox/port-forward/node_modules/@sveltejs/kit/src/runtime/server/respond.js:282:5)
    at #options.hooks.handle (/Users/steve/Projects/web/_sandbox/port-forward/node_modules/@sveltejs/kit/src/runtime/server/index.js:56:56)
    at Module.respond (/Users/steve/Projects/web/_sandbox/port-forward/node_modules/@sveltejs/kit/src/runtime/server/respond.js:279:40)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
Error: Not found: /json/version
    at resolve (/Users/steve/Projects/web/_sandbox/port-forward/node_modules/@sveltejs/kit/src/runtime/server/respond.js:480:13)
    at resolve (/Users/steve/Projects/web/_sandbox/port-forward/node_modules/@sveltejs/kit/src/runtime/server/respond.js:282:5)
    at #options.hooks.handle (/Users/steve/Projects/web/_sandbox/port-forward/node_modules/@sveltejs/kit/src/runtime/server/index.js:56:56)
    at Module.respond (/Users/steve/Projects/web/_sandbox/port-forward/node_modules/@sveltejs/kit/src/runtime/server/respond.js:279:40)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)

// ad infinitum, once every few hundred ms (? ish)
```

### System Info

```Shell
System:
    OS: macOS 12.6.7
    CPU: (8) x64 Intel(R) Core(TM) i7-4770HQ CPU @ 2.20GHz
    Memory: 3.68 GB / 16.00 GB
    Shell: 5.6.2 - /usr/local/bin/zsh
  Binaries:
    Node: 18.14.0 - ~/.nvm/versions/node/v18.14.0/bin/node
    npm: 9.4.2 - ~/.nvm/versions/node/v18.14.0/bin/npm
    Watchman: 2023.02.27.00 - /usr/local/bin/watchman
  Browsers:
    Brave Browser: 114.1.52.126
    Chrome: 114.0.5735.198
    Firefox: 112.0.2
    Safari: 16.5.2
  npmPackages:
    @sveltejs/adapter-auto: ^2.0.0 => 2.1.0
    @sveltejs/kit: ^1.20.4 => 1.22.3
    svelte: ^4.0.5 => 4.1.1
    vite: ^4.4.2 => 4.4.6
```

### Severity

annoyance

**Comment by dummdidumm** [comment]
SvelteKit isn't aware of which port is used to serving it, so this is either an issue with Vite or Chrome. I also can't reproduce this given the instructions.

**Comment by jakobsturm** [comment]
To anyone running into this issue in the future. I managed to solve this issue by disabling "discover network targets" in `chrome://inspect`

![CleanShot 2024-10-15 at 12 05 09](https://github.com/user-attachments/assets/04efe142-a093-4849-a762-2fa0c6913885)
