### ISSUE TITLE
`adapter-vercel` crappy error message for route conflict on Windows

### ISSUE THREAD

**Issue by Sxxov** [sveltejs/kit#10463]
### Describe the bug

[Prerender route conflicts](https://kit.svelte.dev/docs/page-options#prerender-route-conflicts) fail with an `EPERM` copy error on Windows, instead of the [pretty linked one it's supposed to show](https://github.com/sveltejs/kit/blob/4e6213565eebc322f492f24de67644e178c5d5f2/packages/kit/src/core/postbuild/prerender.js#L381). I have a screenshot & a headache to show for it.

<img width="930" alt="image" src="https://github.com/sveltejs/kit/assets/50891910/c25450d5-2b22-452d-a2f3-93bee1313726">

### Reproduction

Run `npm run build`, & you'll see the pretty error.

https://stackblitz.com/edit/sveltejs-kit-template-default-ybqtwd?file=src%2Froutes%2Fbruh%2F%5Bid%5D%2F%2Bserver.js

### Logs

```Shell
> Using @sveltejs/adapter-vercel
error during build:
Error: EPERM: operation not permitted, copyfile 'C:\__Projects\Code\mew\.svelte-kit\output\prerendered\dependencies\api\v1\notion\meta' -> '.vercel\output\static\api\v1\notion\meta'
    at Object.copyFileSync (node:fs:2866:3)
    at go (file:///C:/__Projects/Code/mew/node_modules/@sveltejs/kit/src/utils/filesystem.js:70:8)
    at file:///C:/__Projects/Code/mew/node_modules/@sveltejs/kit/src/utils/filesystem.js:55:5
    at Array.forEach (<anonymous>)
    at go (file:///C:/__Projects/Code/mew/node_modules/@sveltejs/kit/src/utils/filesystem.js:54:25)
    at file:///C:/__Projects/Code/mew/node_modules/@sveltejs/kit/src/utils/filesystem.js:55:5
    at Array.forEach (<anonymous>)
    at go (file:///C:/__Projects/Code/mew/node_modules/@sveltejs/kit/src/utils/filesystem.js:54:25)
    at file:///C:/__Projects/Code/mew/node_modules/@sveltejs/kit/src/utils/filesystem.js:55:5
    at Array.forEach (<anonymous>)
```

### System Info

```Shell
System:
    OS: Windows 10 10.0.22621
    CPU: (16) x64 AMD Ryzen 9 4900HS with Radeon Graphics
    Memory: 2.33 GB / 15.42 GB
  Binaries:
    Node: 18.12.1 - C:\Program Files\nodejs\node.EXE
    npm: 9.5.1 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Edge: Spartan (44.22621.1992.0), Chromium (115.0.1901.188)
    Internet Explorer: 11.0.22621.1
  npmPackages:
    @sveltejs/adapter-vercel: ^3.0.1 => 3.0.1
    @sveltejs/kit: ^1.22.1 => 1.22.1
    svelte: ^4.0.5 => 4.0.5
    vite: ^4.4.2 => 4.4.2
```

### Severity

annoyance

**Comment by teemingc** [comment]
I can't reproduce this on a fresh project on Windows. Going to close this for now
