### ISSUE TITLE
@sveltejs/adapter-static asks to set a config value that is not valid

### ISSUE THREAD

**Issue by mikemaccana** [sveltejs/kit#10538]
### Describe the bug

During `npm run build` of a new Sveltekit application:
 
> error during build:
Error: adapter-static requires `config.kit.prerender.default` to be `true` unless you set the `fallback: true` option to create a single-page app. See https://github.com/sveltejs/kit/tree/master/packages/adapter-static#spa-mode for more information

Sure, will do:

```
const config = {
  ...

  kit: {
    prerender: {
      default: true,
    },
  },
  ...
}
```

Sveltekit then says this in invalid:

```
Error: Unexpected option config.kit.prerender.default
```

The [prerender docs](https://kit.svelte.dev/docs/configuration#prerender) do not mention a `default` key.

### Reproduction

Make a new Sveltekit app with folllowing config.

```
import adapter from '@sveltejs/adapter-static';

const config = {
  ...

  kit: {
    adapter: adapter(),
  },

  ...
};
```

### Logs

```Shell
> vite build

error during build:
Error: Unexpected option config.kit.prerender.default
    at file:///Users/mikemaccana/Code/solana/decentralized-ip/node_modules/@sveltejs/kit/src/core/config/options.js:314:12
    at file:///Users/mikemaccana/Code/solana/decentralized-ip/node_modules/@sveltejs/kit/src/core/config/options.js:321:18
    at file:///Users/mikemaccana/Code/solana/decentralized-ip/node_modules/@sveltejs/kit/src/core/config/options.js:321:18
    at validate_config (file:///Users/mikemaccana/Code/solana/decentralized-ip/node_modules/@sveltejs/kit/src/core/config/index.js:108:9)
    at process_config (file:///Users/mikemaccana/Code/solana/decentralized-ip/node_modules/@sveltejs/kit/src/core/config/index.js:80:20)
    at load_config (file:///Users/mikemaccana/Code/solana/decentralized-ip/node_modules/@sveltejs/kit/src/core/config/index.js:72:9)
    at async sveltekit (file:///Users/mikemaccana/Code/solana/decentralized-ip/node_modules/@sveltejs/kit/src/exports/vite/index.js:119:24)
    at async Promise.all (index 0)
    at async asyncFlatten (file:///Users/mikemaccana/Code/solana/decentralized-ip/node_modules/vite/dist/node/chunks/dep-e8f070e8.js:12623:16)
    at async resolveConfig (file:///Users/mikemaccana/Code/solana/decentralized-ip/node_modules/vite/dist/node/chunks/dep-e8f070e8.js:64022:29)
```

### System Info

```Shell
System:
    OS: macOS 13.4.1
    CPU: (12) arm64 Apple M2 Max
    Memory: 109.84 MB / 32.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 18.16.1 - /usr/local/bin/node
    npm: 9.8.0 - /usr/local/bin/npm
  Browsers:
    Edge: 115.0.1901.203
    Safari: 16.5.2
  npmPackages:
    @sveltejs/adapter-static: ^1.0.0-next.39 => 1.0.0-next.39
    @sveltejs/kit: ^1.20.1 => 1.20.1
    svelte: ^3.59.1 => 3.59.1
    vite: ^4.3.9 => 4.3.9
```

### Severity

blocking all usage of SvelteKit

**Comment by Conduitry** [comment]
You're on a pre-1.0 version of `@sveltejs/adapter-static` (`1.0.0-next.39`). Please update to the latest version.

**Comment by mikemaccana** [comment]
Thanks, did an upgrade to see if it had been fixed and was about to close this myself. The error now suggests working fixes.
