### ISSUE TITLE
bug: favicon not showing in new project

### ISSUE THREAD

**Issue by AdditionAddict** [sveltejs/kit#10564]
### Describe the bug

Creating a new project the favicon doesn't show

Trying to fix: 

The docs here suggest you can put a relative path https://kit.svelte.dev/docs/project-structure#project-files-src

> %sveltekit.assets% — either [paths.assets](https://kit.svelte.dev/docs/configuration#paths), if specified, or a relative path to [paths.base](https://kit.svelte.dev/docs/configuration#paths)

but https://kit.svelte.dev/docs/configuration#paths suggests this is false
if I try to set these
```
import adapter from "@sveltejs/adapter-auto";
import { vitePreprocess } from "@sveltejs/kit/vite";

/** @type {import('@sveltejs/kit').Config} */
const config = {
  // Consult https://kit.svelte.dev/docs/integrations#preprocessors
  // for more information about preprocessors
  preprocess: vitePreprocess(),

  kit: {
    // adapter-auto only supports some environments, see https://kit.svelte.dev/docs/adapter-auto for a list.
    // If your environment is not supported or you settled on a specific environment, switch out the adapter.
    // See https://kit.svelte.dev/docs/adapters for more information about adapters.
    adapter: adapter(),
    paths: {
      relative: true,
      assets: "./static",
    },
  },
};

export default config;
```

I just get `config.kit.paths.assets option must be an absolute path` errors

### Reproduction

```zsh
pnpm create svelte@latest check-assets-favicon

create-svelte version 5.0.5

┌  Welcome to SvelteKit!
│
◇  Which Svelte app template?
│  Skeleton project
│
◇  Add type checking with TypeScript?
│  Yes, using TypeScript syntax
│
◇  Select additional options (use arrow keys/space bar)
│  none
```

(also tried with full demo - same issue)

install and run dev
```
pnpm i
pnpm dev
```

The app works but the favicon isn't showing

### Logs

```Shell
*  Executing task: pnpm run dev 


> check-assets-favicon-full@0.0.1 dev /Users/andrew/dev/learning/Svelte/check-assets-favicon-full
> vite dev

error when starting dev server:
Error: config.kit.paths.assets option must be an absolute path, if specified. See https://kit.svelte.dev/docs/configuration#paths
    at file:///Users/andrew/dev/learning/Svelte/check-assets-favicon-full/node_modules/.pnpm/@sveltejs+kit@1.22.6_svelte@4.2.0_vite@4.4.9/node_modules/@sveltejs/kit/src/core/config/options.js:168:14
    at file:///Users/andrew/dev/learning/Svelte/check-assets-favicon-full/node_modules/.pnpm/@sveltejs+kit@1.22.6_svelte@4.2.0_vite@4.4.9/node_modules/@sveltejs/kit/src/core/config/options.js:336:43
    at file:///Users/andrew/dev/learning/Svelte/check-assets-favicon-full/node_modules/.pnpm/@sveltejs+kit@1.22.6_svelte@4.2.0_vite@4.4.9/node_modules/@sveltejs/kit/src/core/config/options.js:322:18
    at file:///Users/andrew/dev/learning/Svelte/check-assets-favicon-full/node_modules/.pnpm/@sveltejs+kit@1.22.6_svelte@4.2.0_vite@4.4.9/node_modules/@sveltejs/kit/src/core/config/options.js:322:18
    at file:///Users/andrew/dev/learning/Svelte/check-assets-favicon-full/node_modules/.pnpm/@sveltejs+kit@1.22.6_svelte@4.2.0_vite@4.4.9/node_modules/@sveltejs/kit/src/core/config/options.js:322:18
    at validate_config (file:///Users/andrew/dev/learning/Svelte/check-assets-favicon-full/node_modules/.pnpm/@sveltejs+kit@1.22.6_svelte@4.2.0_vite@4.4.9/node_modules/@sveltejs/kit/src/core/config/index.js:108:9)
    at process_config (file:///Users/andrew/dev/learning/Svelte/check-assets-favicon-full/node_modules/.pnpm/@sveltejs+kit@1.22.6_svelte@4.2.0_vite@4.4.9/node_modules/@sveltejs/kit/src/core/config/index.js:80:20)
    at load_config (file:///Users/andrew/dev/learning/Svelte/check-assets-favicon-full/node_modules/.pnpm/@sveltejs+kit@1.22.6_svelte@4.2.0_vite@4.4.9/node_modules/@sveltejs/kit/src/core/config/index.js:72:9)
    at async sveltekit (file:///Users/andrew/dev/learning/Svelte/check-assets-favicon-full/node_modules/.pnpm/@sveltejs+kit@1.22.6_svelte@4.2.0_vite@4.4.9/node_modules/@sveltejs/kit/src/exports/vite/index.js:119:24)
    at async Promise.all (index 0)
 ELIFECYCLE  Command failed with exit code 1.
```
```


### System Info

```Shell
System:
    OS: macOS 13.5
    CPU: (8) arm64 Apple M2
    Memory: 538.03 MB / 24.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 19.9.0 - ~/.nvm/versions/node/v19.9.0/bin/node
    Yarn: 1.22.19 - /opt/homebrew/bin/yarn
    npm: 9.6.3 - ~/.nvm/versions/node/v19.9.0/bin/npm
    pnpm: 8.6.9 - ~/Library/pnpm/pnpm
    Watchman: 2023.08.14.00 - /opt/homebrew/bin/watchman
  Browsers:
    Chrome: 116.0.5845.96
    Safari: 16.6
  npmPackages:
    @sveltejs/adapter-auto: ^2.0.0 => 2.1.0 
    @sveltejs/kit: ^1.20.4 => 1.22.6 
    svelte: ^4.0.5 => 4.2.0 
    vite: ^4.4.2 => 4.4.9
```

### Severity

annoyance

**Comment by s3812497** [comment]
You do not need to set `paths.assets` to get `%sveltekit.assets%` to work.

> %sveltekit.assets% — either [paths.assets](https://kit.svelte.dev/docs/configuration#paths), if specified, or a relative path to [paths.base](https://kit.svelte.dev/docs/configuration#paths)

This does not mean `paths.assets` can be a relative path. It means that it could be a relative path to `paths.base`.

Please provide a repository as a minimal reproduction where the favicons are not being detected.
