### ISSUE TITLE
Server assets cannot be read on the server after build

### ISSUE THREAD

**Issue by oxneat** [sveltejs/kit#10594]
### Describe the bug

Sveletekit PdfMake font import works fine locally but crushes when deployed to vercel  

### Reproduction

this is the code:

```
const fonts: TFontDictionary = {
    Futura: {
        //         FuturaPTBook.otf
        // FuturaPTCondBold.otf
        normal: `./static/fonts/FuturaPTBook.otf`,
        bold: `./static/fonts/FuturaPTBold.otf`
    }
};
const printer = new PdfPrinter(fonts);
```

i also created a fonts folder a the same place where the file exists and i imported the fonts using 
`import normal from "./fonts/FuturaPTBook.otf";` and i did this:
![Screenshot from 2023-08-21 18-09-25](https://github.com/sveltejs/kit/assets/62510442/7815b8d7-2e97-485f-b614-7d04cbcfb9f0)

```
const fonts: TFontDictionary = {
    Futura: {
        //         FuturaPTBook.otf
        // FuturaPTCondBold.otf
        normal: path.join(".",normal),
        bold: path.join(".",bold)
    }
};

```
but it worked locally and it crashed on vercel

### Logs

```Shell
Error: ENOENT: no such file or directory, open '_app/immutable/assets/FuturaPTCondBold.35d3f580.otf'
    at Object.openSync (node:fs:601:3)
    at Object.readFileSync (node:fs:469:35)
    at PDFFontFactory.open (/var/task/vercel/path0/node_modules/@foliojs-fork/pdfkit/js/pdfkit.js:3384:16)
    at PDFDocument.font (/var/task/vercel/path0/node_modules/@foliojs-fork/pdfkit/js/pdfkit.js:3454:33)
    at FontProvider.provideFont (/var/task/vercel/path0/node_modules/pdfmake/src/fontProvider.js:62:58)
    at /var/task/vercel/path0/node_modules/pdfmake/src/textTools.js:326:27
    at Array.forEach (<anonymous>)
    at measure (/var/task/vercel/path0/node_modules/pdfmake/src/textTools.js:298:13)
    at TextTools.buildInlines (/var/task/vercel/path0/node_modules/pdfmake/src/textTools.js:32:17)
    at DocMeasure.measureLeaf (/var/task/vercel/path0/node_modules/pdfmake/src/docMeasure.js:235:28) {
  errno: -2,
  syscall: 'open',
  code: 'ENOENT',
  path: '_app/immutable/assets/FuturaPTCondBold.35d3f580.otf'
}
```

### System Info

```Shell
System:
    OS: Linux 6.2 Ubuntu 22.04.3 LTS 22.04.3 LTS (Jammy Jellyfish)
    CPU: (4) x64 Intel(R) Core(TM) i5-3360M CPU @ 2.80GHz
    Memory: 2.68 GB / 7.68 GB
    Container: Yes
    Shell: 5.1.16 - /bin/bash
  Binaries:
    Node: 18.16.0 - ~/.nvm/versions/node/v18.16.0/bin/node
    Yarn: 3.6.0 - ~/.nvm/versions/node/v18.16.0/bin/yarn
    npm: 9.5.1 - ~/.nvm/versions/node/v18.16.0/bin/npm
    pnpm: 8.6.7 - ~/.nvm/versions/node/v18.16.0/bin/pnpm
  Browsers:
    Chrome: 115.0.5790.170
  npmPackages:
    @sveltejs/adapter-auto: ^2.0.0 => 2.1.0 
    @sveltejs/kit: ^1.20.4 => 1.22.3 
    svelte: ^4.0.5 => 4.0.5 
    vite: ^4.4.2 => 4.4.4
```

### Severity

serious, but I can work around it

**Comment by s3812497** [comment]
Please provide a minimal reproduction in the form of a repository that can be deployed to Vercel to reproduce this issue.

**Comment by oxneat** [comment]
@s3812497 Hello Tee Thanks for your help, i tried this and it worked locally but unfortunately it failed on vercel again and this is the error: 
`Error: ENOENT: no such file or directory, open './_app/immutable/assets/FuturaPTCondBold.35d3f580.otf'
    at Object.openSync (node:fs:601:3)
    at Object.readFileSync (node:fs:469:35)
    at PDFFontFactory.open (/var/task/vercel/path0/node_modules/@foliojs-fork/pdfkit/js/pdfkit.js:3384:16)
    at PDFDocument.font (/var/task/vercel/path0/node_modules/@foliojs-fork/pdfkit/js/pdfkit.js:3454:33)
    at FontProvider.provideFont (/var/task/vercel/path0/node_modules/pdfmake/src/fontProvider.js:62:58)
    at /var/task/vercel/path0/node_modules/pdfmake/src/textTools.js:326:27
    at Array.forEach (<anonymous>)
    at measure (/var/task/vercel/path0/node_modules/pdfmake/src/textTools.js:298:13)
    at TextTools.buildInlines (/var/task/vercel/path0/node_modules/pdfmake/src/textTools.js:32:17)
    at DocMeasure.measureLeaf (/var/task/vercel/path0/node_modules/pdfmake/src/docMeasure.js:235:28) {
  errno: -2,
  syscall: 'open',
  code: 'ENOENT',
  path: './_app/immutable/assets/FuturaPTCondBold.35d3f580.otf'
}`

**Comment by s3812497** [comment]
I don't think we're copying the server assets over / resolving the path correctly for some adapters (node, vercel, etc.). So, trying to read them on the server causes the file to not be found.

**Comment by oxneat** [comment]
@s3812497  Additionally __dirname and __filename don't work

**Comment by s3812497** [comment]
related https://github.com/sveltejs/kit/issues/4671

**Comment by diramazioni** [comment]
I'm a new user but... have you checked the `files.assets` in `svelte.config.js`? like
```
		files: {
			assets:  './src/lib/assets' 
		},
```

**Comment by ghostdevv** [comment]
> Additionally __dirname and __filename don't work

I believe the output is esm so you would need `import.meta.url`

**Comment by oxneat** [comment]
@diramazioni @s3812497 this didn't work

**Comment by oxneat** [comment]
> > Additionally __dirname and __filename don't work
> 
> I believe the output is esm so you would need `import.meta.url`

@ghostdevv @s3812497 this also didn't work

**Comment by oxneat** [comment]
@s3812497 hello guys is there anything new about this bug?

**Comment by s3812497** [comment]
@oxneat Sorry, about the long silence. I was stuck on this issue for a while but have now found the root cause.

Currently, SvelteKit treats server assets no differently from client assets. Hence, we need to add [to the builder methods](https://github.com/sveltejs/kit/blob/master/packages/kit/src/core/adapt/builder.js) available and modify existing adapters to correctly copy over the server assets to the correct path on the server.

In the case of Vercel, all assets currently live in the `.vercel/output/static/` directory as public assets. However, those aren't directly accessible by server code. They need to live in the `.vercel/output/functions/fn.func/` directory.

**Comment by oxneat** [comment]
@s3812497 thanks you for the feedback

**Comment by s3812497** [comment]
It seems that this is actually a known issue and is mentioned in the docs.
https://kit.svelte.dev/docs/adapter-vercel#troubleshooting

https://github.com/sveltejs/kit/pull/8441#pullrequestreview-1242913479

**Comment by wesbos** [comment]
I'm also running into this. I have a wasm file that needs to be included in a +server.ts route. How do I ensure it's included and accessible at runtime?

**Comment by s3812497** [comment]
> I'm also running into this. I have a wasm file that needs to be included in a +server.ts route. How do I ensure it's included and accessible at runtime?

See the last paragraph in https://github.com/sveltejs/kit/issues/10594#issuecomment-1727740392

It should be accessible if you can manually copy the files in.

**Comment by wesbos** [comment]
@s3812497 How do I do that? Do I need to modify the sveltekit built?

**Comment by s3812497** [comment]
> How do I do that? Do I need to modify the sveltekit built?

@wesbos That's right. A sort of post-build script.

```bash
# you can replace your package.json build script with the below
vite build && cp -r .svelte-kit/output/server/_app .vercel/output/functions/fn.func
```

```js
import { join } from "path";
import { FFmpeg } from "@ffmpeg.wasm/main";
import core from "@ffmpeg.wasm/core-mt";
import wasmPathAb from "@ffmpeg.wasm/core-mt/dist/core.wasm?url";
import { env } from "$env/dynamic/private";
import { dev } from "$app/environment";

let wasmPath = join(process.cwd(), wasmPathAb);

// when running `vite preview`, files are served from .svelte-kit
if (!dev && !env.VERCEL) {
  wasmPath = join(process.cwd(), '.svelte-kit/output/server', wasmPathAb)
}

export async function GET() {
  const ffmpeg = await FFmpeg.create({
    core,
    coreOptions: {
      wasmPath: wasmPath,
    },
  });
  return new Response(wasmPath);
}
```

**Comment by wesbos** [comment]
@s3812497 Thank you - is the `fn.func` dir supposed to be named something? Or literally "fn.func"? I tried the script but I still have the same issue. I can see the file in _app/immutable/assets/ dir

**Comment by s3812497** [comment]
> @s3812497 is the `fn.func` dir supposed to be named something? Or literally "fn.func"?

I believe so, unless you have split functions configured and have multiple function folders.

**Comment by HenkBourgonje** [comment]
@oxneat have you been able to get this to work for your font-related problem? I'm running into the same thing right now.

**Comment by oxneat** [comment]
> @oxneat have you been able to get this to work for your font-related problem on Vercel? I'm running into the same thing right now.

No unfortunately

**Comment by HenkBourgonje** [comment]
@oxneat too bad! Do you by any chance have any more ideas for the original problem this thread is about @eltigerchino?

**Comment by eltigerchino** [comment]
> @oxneat too bad! Do you by any chance have any more ideas for the original problem this thread is about @eltigerchino?

It's easy enough to update `adapter-vercel` to copy over all server assets into the functions folder.

However, I'm struggling to figure out how to easily determine which assets should go with which functions when the `split` config is enabled. This groups routes into different Vercel functions based on the exported `config` constant in +page.js.

The vite manifest maps the server assets to the file paths of the +layout.server and +page.server files in your project folder. So it'd be ideal to copy over only the server assets that will be used by the single server layout or multiple nested server layouts and the page server load. We should also take into account when a layout breaks out of the nested hierarchy. I'm not sure if this will create too much overhead for the adapter and slow it down.

It'd be easier to copy over the same server assets to every serverless function but that would make your build very large and so is one of the reasons this was not implemented earlier.

**Comment by wesbos** [comment]
Still banging my head against the wall with this. Ended up having to copy + paste the files into the vercel output after build:

```js
#!zx
const LOCAL_BUILD_PATH = '.svelte-kit/output/server/';
const VERCEL_BUILD_BASE_PATH = '.vercel/output/functions';
const vercelFuncDirs = (await $`ls -1d ${VERCEL_BUILD_BASE_PATH}/*.func`).stdout
	.split('\n')
	.map((v) => v.trim())
	.filter((v) => v !== '');

const outputDirs = [...vercelFuncDirs, LOCAL_BUILD_PATH];

for (const outputDir of outputDirs) {
	// We have to explicitly copy the WASM files to the output directory of each serverless function because Sveltekit + Vercel have no way of knowing that they need to be copied via static analysis.
	console.log(`Copying WASM files to ${outputDir}.`);
	await $`cp node_modules/@ffmpeg.wasm/core-mt/dist/core.wasm ${outputDir}`;
	await $`cp node_modules/@ffmpeg.wasm/core-mt/dist/core.worker.js ${outputDir}/core.worker.cjs`;
	await $`cp -r ./src/server/transcripts/audio ${outputDir}`;
}
```

Everyone is saying "simply reference the file in your script!" but it doesn't work. I've tried so many combos of Path.join() and fs.readFile

**Comment by eltigerchino** [comment]
> Everyone is saying "simply reference the file in your script!" but it doesn't work. I've tried so many combos of Path.join() and fs.readFile

This wouldn’t work because the files need to be copied specifically to the serverless function.

I have a PR ready but my only concern is that it copies all assets referenced, so images and fonts, etc would also end up in the serverless function bundle, increasing the size. Maybe there should be a way to filter the files included? https://github.com/sveltejs/kit/pull/10979

**Comment by eltigerchino** [comment]
Reopening because there still some cleanup to do

**Comment by Rich-Harris** [comment]
In 2.4.0 we added a new `$app/server` module with a `read` function that allows you to solve this problem.

- https://sveltekit-pdf-demo.vercel.app
- https://github.com/Rich-Harris/sveltekit-pdf-demo

Note that the demo uses `pdf-lib` rather than `pdfmake`. AFAICT `pdfmake` requires you to pass a filepath rather than an array buffer, which isn't ideal since we want to be as runtime-agnostic as possible. _Maybe_ we could add a function for getting the filepath for an asset to solve those use cases but it wouldn't make sense in non-Node-like environments (whereas we intend for `read` to eventually be supported as widely as possible).

For now I'll treat this issue as fixed. Thanks!

**Comment by wesbos** [comment]
@eltigerchino @Rich-Harris so we can now simply reference the file and it will be included in the build? We have a dependency that just assumes the .wasm file exists alongside it, no way to pass it in, so we have to do this post-build pre-deploy script: https://github.com/syntaxfm/website/blob/main/why_do_i_need_this.mjs#L14

**Comment by eltigerchino** [comment]
@wesbos that’s exactly it! This excellent PR https://github.com/sveltejs/kit/pull/11649 implements the file copying of server assets for the vercel adapter. I haven’t had the chance to try it out myself but you should be able to verify if the wasm files are in the build output of the serverless function
