### ISSUE TITLE
Note able to create sveltekit app with the npm create command on Ubuntu 22.03 on WSL2 - latest node and npm (fresh install yesterday)

### ISSUE THREAD

**Issue by BikiniBottomsVeryOwn** [sveltejs/kit#10762]
### Describe the bug

I am running the latest version of Node and NPM on ubuntu 22.04 running on WSL2. 

When I run `npm create svelte@latest my-app`

I get 

```
file:///home/jon/.npm/_npx/50a6160ffc29bafc/node_modules/create-svelte/bin.js:19
        const dir = await p.text({
                    ^^^^^

SyntaxError: Unexpected reserved word
    at Loader.moduleStrategy (internal/modules/esm/translators.js:133:18)
    at async link (internal/modules/esm/module_job.js:42:21)
npm ERR! code 1
npm ERR! path /home/jon
npm ERR! command failed
npm ERR! command sh -c create-svelte "my-app"

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/jon/.npm/_logs/2023-09-21T05_41_51_827Z-debug-0.log
```

### Reproduction

install npm and node on ubuntu 22.04 on WSL2 then run `npm create svelte@latest my-app`

### Logs

```Shell
0 verbose cli [ '/usr/bin/node', '/usr/bin/npm', 'init', 'svelte', 'my-app' ]
1 info using npm@8.5.1
2 info using node@v12.22.9
3 timing npm:load:whichnode Completed in 0ms
4 timing config:load:defaults Completed in 1ms
5 timing config:load:file:/usr/share/nodejs/npm/npmrc Completed in 1ms
6 timing config:load:builtin Completed in 2ms
7 timing config:load:cli Completed in 0ms
8 timing config:load:env Completed in 1ms
9 timing config:load:project Completed in 0ms
10 timing config:load:file:/home/jon/.npmrc Completed in 0ms
11 timing config:load:user Completed in 0ms
12 timing config:load:file:/etc/npmrc Completed in 0ms
13 timing config:load:global Completed in 0ms
14 timing config:load:validate Completed in 0ms
15 timing config:load:credentials Completed in 1ms
16 timing config:load:setEnvs Completed in 1ms
17 timing config:load Completed in 7ms
18 timing npm:load:configload Completed in 7ms
19 timing npm:load:setTitle Completed in 0ms
20 timing config:load:flatten Completed in 2ms
21 timing npm:load:display Completed in 4ms
22 verbose logfile /home/jon/.npm/_logs/2023-09-21T05_35_21_353Z-debug-0.log
23 timing npm:load:logFile Completed in 3ms
24 timing npm:load:timers Completed in 0ms
25 timing npm:load:configScope Completed in 0ms
26 timing npm:load Completed in 15ms
27 silly logfile start cleaning logs, removing 1 files
28 http fetch GET 200 https://registry.npmjs.org/create-svelte 606ms (cache miss)
29 timing arborist:ctor Completed in 1ms
30 timing arborist:ctor Completed in 1ms
31 timing arborist:ctor Completed in 0ms
32 timing arborist:ctor Completed in 0ms
33 timing command:init Completed in 727ms
34 verbose stack Error: command failed
34 verbose stack     at ChildProcess.<anonymous> (/usr/share/nodejs/@npmcli/promise-spawn/index.js:64:27)
34 verbose stack     at ChildProcess.emit (events.js:314:20)
34 verbose stack     at maybeClose (internal/child_process.js:1022:16)
34 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:287:5)
35 verbose pkgid jon@1.0.0
36 verbose cwd /home/jon
37 verbose Linux 5.15.90.1-microsoft-standard-WSL2
38 verbose argv "/usr/bin/node" "/usr/bin/npm" "init" "svelte" "my-app"
39 verbose node v12.22.9
40 verbose npm  v8.5.1
41 error code 1
42 error path /home/jon
43 error command failed
44 error command sh -c create-svelte "my-app"
45 verbose exit 1
46 timing npm Completed in 865ms
47 verbose code 1
48 error A complete log of this run can be found in:
48 error     /home/jon/.npm/_logs/2023-09-21T05_35_21_353Z-debug-0.log
```
```


### System Info

```Shell
Ubuntu 22.04 LTS on WSL2 - Windows 11

Latest node and npm, both re installed yesterday.
```

### Severity

blocking all usage of SvelteKit

### Additional Information

Hewp

**Comment by s3812497** [comment]
The log says `2 info using node@v12.22.9`. Can you try again with the latest version of node 16 or 18?
