### ISSUE TITLE
Dynamic route not prerendered with adapter-auto

### ISSUE THREAD

**Issue by juliuslipp** [sveltejs/kit#10770]
### Describe the bug

When using SvelteKit with the adapter-auto package, prerendering is not working as expected for dynamic routes. Despite having <a> elements set for the dynamic routes in the Svelte components, the prerendering process does not generate static pages for these routes and fails with an error message.

### Reproduction

1. Clone the Repo: ` https://github.com/juliuslipp/sveltekit-bug`
2. Install Deps `npm i / bun i`
3. Run Dev `npm i / bun i`
4. Click on the About link and see how it works.
5. Run `npm i / bun i`
6. See how it fails, even though the links are present and working.

### Logs

```Shell
$ vite build
▲ [WARNING] Cannot find base config file "./.svelte-kit/tsconfig.json" [tsconfig.json]

    ../tsconfig.json:2:12:
      2 │   "extends": "./.svelte-kit/tsconfig.json",
        ╵              ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~


vite v4.4.9 building SSR bundle for production...
transforming (1) .svelte-kit/generated/server/internal.js1:31:48 AM [vite-plugin-svelte] /private/tmp/not-workign/src/routes/+page.svelte:3:0 A11y: <a> element should have child content
1: <h1>Welcome to SvelteKit</h1>
2: <p>Visit <a href="https://kit.svelte.dev">kit.svelte.dev</a> to read the documentation</p>
3: <a href="/about"></a>
   ^
4: 
5: 
1:31:48 AM [vite-plugin-svelte] /private/tmp/not-workign/src/routes/+layout.svelte:2:0 A11y: <a> element should have child content
1: <script>import "../app.postcss";</script><slot></slot>
2: <a href="/about"></a>
   ^
✓ 76 modules transformed.
▲ [WARNING] Cannot find base config file "./.svelte-kit/tsconfig.json" [tsconfig.json]

    ../tsconfig.json:2:12:
      2 │   "extends": "./.svelte-kit/tsconfig.json",
        ╵              ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~


vite v4.4.9 building for production...
transforming (1) .svelte-kit/generated/client-optimized/app.js1:31:49 AM [vite-plugin-svelte] /private/tmp/not-workign/src/routes/+layout.svelte:2:0 A11y: <a> element should have child content
1: <script>import "../app.postcss";</script><slot></slot>
2: <a href="/about"></a>
   ^
1:31:49 AM [vite-plugin-svelte] /private/tmp/not-workign/src/routes/+page.svelte:3:0 A11y: <a> element should have child content
1: <h1>Welcome to SvelteKit</h1>
2: <p>Visit <a href="https://kit.svelte.dev">kit.svelte.dev</a> to read the documentation</p>
3: <a href="/about"></a>
   ^
4: 
5: 
✓ 68 modules transformed.
.svelte-kit/output/client/_app/version.json                                  0.03 kB │ gzip: 0.05 kB
.svelte-kit/output/client/vite-manifest.json                                 3.51 kB │ gzip: 0.57 kB
.svelte-kit/output/client/_app/immutable/assets/0.4f2311d7.css               4.37 kB │ gzip: 1.38 kB
.svelte-kit/output/client/_app/immutable/chunks/stores.1932f595.js           0.24 kB │ gzip: 0.17 kB
.svelte-kit/output/client/_app/immutable/chunks/control.f5b05b5f.js          0.25 kB │ gzip: 0.18 kB
.svelte-kit/output/client/_app/immutable/chunks/about.e5cdebdb.js            0.43 kB │ gzip: 0.31 kB
.svelte-kit/output/client/_app/immutable/nodes/0.9ab5e397.js                 0.78 kB │ gzip: 0.50 kB
.svelte-kit/output/client/_app/immutable/nodes/2.23482323.js                 0.83 kB │ gzip: 0.51 kB
.svelte-kit/output/client/_app/immutable/nodes/1.1f5951bf.js                 0.84 kB │ gzip: 0.52 kB
.svelte-kit/output/client/_app/immutable/chunks/preload-helper.a4192956.js   0.89 kB │ gzip: 0.55 kB
.svelte-kit/output/client/_app/immutable/nodes/3.02ce83f5.js                 1.19 kB │ gzip: 0.68 kB
.svelte-kit/output/client/_app/immutable/chunks/scheduler.e108d1fd.js        2.16 kB │ gzip: 1.02 kB
.svelte-kit/output/client/_app/immutable/chunks/singletons.7724a77a.js       2.85 kB │ gzip: 1.46 kB
.svelte-kit/output/client/_app/immutable/entry/app.167c2789.js               5.36 kB │ gzip: 1.93 kB
.svelte-kit/output/client/_app/immutable/chunks/index.a21d6cee.js            5.44 kB │ gzip: 2.31 kB
.svelte-kit/output/client/_app/immutable/entry/start.94bcd944.js            24.66 kB │ gzip: 9.73 kB
✓ built in 235ms

node:internal/event_target:1033
  process.nextTick(() => { throw err; });
                           ^
Error: The following routes were marked as prerenderable, but were not prerendered because they were not found while crawling your app:
  - /[...slug]

See https://kit.svelte.dev/docs/page-options#prerender-troubleshooting for info on how to solve this
    at prerender (file:///private/tmp/not-workign/node_modules/@sveltejs/kit/src/core/postbuild/prerender.js:475:9)
    at async MessagePort.<anonymous> (file:///private/tmp/not-workign/node_modules/@sveltejs/kit/src/utils/fork.js:22:16)
Emitted 'error' event on Worker instance at:
    at [kOnErrorMessage] (node:internal/worker:300:10)
    at [kOnMessage] (node:internal/worker:311:37)
    at MessagePort.<anonymous> (node:internal/worker:212:57)
    at [nodejs.internal.kHybridDispatch] (node:internal/event_target:757:20)
    at exports.emitMessage (node:internal/per_context/messageport:23:28)
```

### System Info

```Shell
System:
    OS: macOS 13.5
    CPU: (10) arm64 Apple M2 Pro
    Memory: 76.47 MB / 16.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 18.18.0 - ~/.nvm/versions/node/v18.18.0/bin/node
    Yarn: 1.22.19 - /opt/homebrew/bin/yarn
    npm: 10.1.0 - ~/.bun/bin/npm
    pnpm: 8.6.9 - ~/Library/pnpm/pnpm
  Browsers:
    Chrome: 117.0.5938.92
    Safari: 16.6
  npmPackages:
    @sveltejs/adapter-auto: ^2.1.0 => 2.1.0 
    @sveltejs/kit: ^1.25.0 => 1.25.0 
    svelte: ^4.2.1 => 4.2.1 
    vite: ^4.4.9 => 4.4.9
```

### Severity

serious, but I can work around it

**Comment by geoffrich** [comment]
The issue is that since `[...slug]` is a dynamic route, SvelteKit needs to know the different values of `slug` so it can generate those HTML files. It can do this one of two ways:
- follow links to these pages via _other_ prerendered pages. Since you're only prerendering the dynamic `[...slug]` route, SK doesn't have any prerendered pages to find links in.
- use the `entries` export to understand what the different values of `slug` are ([docs](https://kit.svelte.dev/docs/page-options#entries))

So you can fix this one of two ways:

1. Prerender your root `/` page. This way, SvelteKit will prerender the page at build time and discover the `/about` link within, which it will also prerender. You can do this by creating a `+page.js` file with `export const prerender = true`
2. Also export `entries` from your `[...slug]/+page.js`. This export should be a function that returns the different values of `slug`. For example:

```
export function entries() {
  return [
    {
      slug: "about"
    }
  ];
}
```

This function can be async if you it to fetch some data or do other async work to generate `entries`.

**Comment by s3812497** [comment]
https://kit.svelte.dev/docs/page-options#prerender-troubleshooting

> Pages not marked as prerenderable will be ignored and their links to other pages will not be crawled, even if some of them would be prerenderable.

The home page which has a link to `/about` is not marked as prerenderable. Hence, SvelteKit doesn't crawl it and can't prerender the dynamic route `/[...slug]`.

You will need to configure the `entries` option so that Kit knows what to prerender the slug with if it cannot find an entry point from another prerendered page.

```js
// src/routes/[...slug]/+page.js

/** @type {import('./$types').EntryGenerator} */
export function entries() {
	return [
		{ slug: 'about' }
	];
}

export const prerender = true;
```

Admittedly, this contradicts what the doc says about crawling starting from the root page of the app. So, I'm not sure if this is a doc issue or a bug.
> The prerenderer will start at the root of your app and generate files for any prerenderable pages or +server.js routes it finds.

https://kit.svelte.dev/docs/page-options#prerender

**Comment by juliuslipp** [comment]
Great, thanks for the clarification. Works great adding the entries!
