### ISSUE TITLE
svelte-package fails with "directory not empty, rmdir"

### ISSUE THREAD

**Issue by Ennoriel** [sveltejs/kit#10785]
### Describe the bug

When packaging a library with typesafe-i18n (and nothing else) configured inside the `lib` folder, **sometimes**, it fails on `rmdirSync`. But when looking at the folder trying to be deleted, it's empty, so I added a `try/catch` block around rmdirSync and it then fails on `statSync`. I had the problem last week on windows 10 and now have the problem on windows 11 as well (fresh install).

It also sometimes generates `.d.ts` files for `.ts` files inside the `i18n` folder but not always.

Finally, the problem is appearing both with npm and pnpm, in a monorepo and a in simple repo.

One of the error:
```
$ npm run package

> skeleton-package-2023-09-25@0.0.1 package
> svelte-kit sync && svelte-package && publint

> ENOTEMPTY: directory not empty, rmdir '\\?\C:\Users\me\Documents\code\skeleton-package-2023-09-25\.svelte-kit\__package__\__package_types_tmp__\i18n'
    at Object.rmdirSync (node:fs:1229:10)
    at _rmdirSync (node:internal/fs/rimraf:260:21)
    at rimrafSync (node:internal/fs/rimraf:193:7)
    at node:internal/fs/rimraf:253:9
    at Array.forEach (<anonymous>)
    at _rmdirSync (node:internal/fs/rimraf:250:7)
    at rimrafSync (node:internal/fs/rimraf:193:7)
    at Object.rmSync (node:fs:1278:10)
    at rimraf (file:///C:/Users/me/Documents/code/skeleton-package-2023-09-25/node_modules/@sveltejs/package/src/filesystem.js:16:5)
    at emit_dts (file:///C:/Users/me/Documents/code/skeleton-package-2023-09-25/node_modules/@sveltejs/package/src/typescript.js:59:2)
```

### Reproduction

https://github.com/Ennoriel/bug-sveltekit-package-rimraf/tree/master/src/lib/i18n

### System Info

```Shell
System:
    OS: Windows 10 10.0.22621
    CPU: (8) x64 Intel(R) Core(TM) i7-8565U CPU @ 1.80GHz
    Memory: 6.95 GB / 15.85 GB
  Binaries:
    Node: 18.17.1 - ~\AppData\Roaming\NodeJs\node.EXE
    npm: 9.6.7 - ~\AppData\Roaming\NodeJs\npm.CMD
    pnpm: 8.7.6 - ~\AppData\Roaming\NodeJs\pnpm.CMD
  Browsers:
    Edge: Spartan (44.22621.2283.0), Chromium (100.0.1185.36)
    Internet Explorer: 11.0.22621.1
  npmPackages:
    @sveltejs/adapter-auto: ^2.0.0 => 2.1.0
    @sveltejs/kit: ^1.20.4 => 1.25.1
    @sveltejs/package: ^2.0.0 => 2.2.2
    svelte: ^4.0.5 => 4.2.1
    vite: ^4.4.2 => 4.4.9
```

### Severity

blocking all usage of SvelteKit

**Comment by Ennoriel** [comment]
I tested without typesafe-i18n but with `ts` and `mts` files, some imported, some not imported and had the same behavior too (same repro but branch `without-typesafe`.

Sometimes on dev:
```
EPERM: operation not permitted, stat 'C:\Users\me\Documents\code\skeleton-package-2023-09-25\.svelte-kit\types\src\routes\$types.d.ts'
```

One important thing: I am using windows as a simple user, without Admin rights

**Comment by Rishab49** [comment]
not getting any error on ubuntu 22.04
system info
```
    Node: 18.17.1 - ~/.nvm/versions/node/v18.17.1/bin/node
    npm: 10.0.0 - ~/.nvm/versions/node/v18.17.1/bin/npm
    pnpm: 8.8.0 - ~/.local/share/pnpm/pnpm
```

![img](https://github.com/sveltejs/kit/assets/25582966/551ec6e8-b9b1-49e7-ac7e-74c934d47ece)

**Comment by aakash14goplani** [comment]
@Ennoriel @frederikhors - were you able to find any solution for this problem?

**Comment by teemingc** [comment]
I can't access the reproduction since it's been removed. I'm going to close this one but feel free to open a new issue if anyone can provide a minimal reproduction.
