### ISSUE TITLE
onNavigate fails with cannot read properties of undefined  (reading on_navigate)

### ISSUE THREAD

**Issue by IRooc** [sveltejs/kit#10792]
### Describe the bug

When I try the onNavigate demo repository https://github.com/geoffrich/sveltekit-view-transitions and do
`vite dev` in the folder everything works great, but when I do `vite build` and `vite preview` I get the following error in the console
``` 
Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'on_navigate')
    at singletons.0568c198.js:1:631
    at G (0.73a76149.js:1:2051)
    at K (0.73a76149.js:1:2917)
    at $e (index.b69d5e4d.js:1:4646)
    at new Z (0.73a76149.js:1:3013)
    at ue (index.b69d5e4d.js:1:3540)
    at Array.x (app.3d97f1dc.js:1:1886)
    at te (app.3d97f1dc.js:1:3790)
    at $e (index.b69d5e4d.js:1:4845)
    at new oe (app.3d97f1dc.js:1:5070)
```
and the viewTransitions don't work. 

### Reproduction

Repro 1:
- Clone repository https://github.com/geoffrich/sveltekit-view-transitions on windows.
- Do 'vite build' and then 'vite preview'
- In both Edge and Chrome you'll get the exception in the consol

Repro 2:
- create new Svelte project `npm create svelte@latest myapp`
- add +layout.svelte with the following code:
``` 
import { onNavigate } from '$app/navigation';


onNavigate((navigation) => {
	if (!document.startViewTransition) return;


	return new Promise((resolve) => {
		document.startViewTransition(async () => {
			resolve();
			await navigation.complete;
		});
	});
});
```
- do `vite build` and then `vite preview`
- you'll get the same error in the console

### System Info

```Shell
vite version: vite/4.4.9 win32-x64 node-v20.4.0
windows 10 
edge: Version 117.0.2045.41 (Official build) (64-bit)
chrome: Version 117.0.5938.92 (Official Build) (64-bit)
```

### Severity

serious, but I can work around it

### Additional Information

the demo still works but without the transitions.

**Comment by Rishab49** [comment]
are you still facing this issue? as I cloned the repo, `build` and `preview` it and it is working fine on my chrome and edge.
