### ISSUE TITLE
Can not build svelte library for production use

### ISSUE THREAD

**Issue by adamijak** [sveltejs/kit#10795]
### Describe the bug

Can not build svelte library to production.

### Reproduction

Run `npm run build` on library template with this config

```js
// vite.config.js
import { sveltekit } from '@sveltejs/kit/vite';
import { defineConfig } from 'vite';

export default defineConfig({
	build:{
		lib:{
			entry: './src/lib/index.js',
			name: 'MyComponent',
			fileName: 'my-component',
			formats: ['es'],
		},
	},
	plugins: [sveltekit()]
});

```

### Logs

```Shell
$ npm run build

> web@0.0.1 build
> vite build && npm run package

The following Vite config options will be overridden by SvelteKit:
  - build.outDir

vite v4.4.9 building SSR bundle for production...
✓ 76 modules transformed.
The following Vite config options will be overridden by SvelteKit:
  - build.outDir

vite v4.4.9 building for production...
✓ 64 modules transformed.
.svelte-kit/output/client/_app/version.json                              0.03 kB │ gzip:  0.05 kB
.svelte-kit/output/client/vite-manifest.json                             2.36 kB │ gzip:  0.43 kB
.svelte-kit/output/client/_app/immutable/assets/2.7716e323.css           0.94 kB │ gzip:  0.42 kB
.svelte-kit/output/client/_app/immutable/nodes/0.82c4394a.js             1.16 kB │ gzip:  0.51 kB
.svelte-kit/output/client/_app/immutable/nodes/1.5508bf94.js             1.68 kB │ gzip:  0.74 kB
.svelte-kit/output/client/_app/immutable/chunks/scheduler.22c8cedd.js    3.26 kB │ gzip:  1.27 kB
.svelte-kit/output/client/_app/immutable/chunks/singletons.3d0ec053.js   4.37 kB │ gzip:  1.81 kB
.svelte-kit/output/client/_app/immutable/entry/app.0741ab6b.js           8.10 kB │ gzip:  2.18 kB
.svelte-kit/output/client/_app/immutable/chunks/index.3b424d7a.js        8.72 kB │ gzip:  3.18 kB
.svelte-kit/output/client/_app/immutable/nodes/2.2d4f0617.js             9.94 kB │ gzip:  3.37 kB
.svelte-kit/output/client/_app/immutable/entry/start.a27a7a63.js        41.58 kB │ gzip: 12.77 kB
✓ built in 279ms
[vite-plugin-sveltekit-compile] Cannot read properties of undefined (reading 'filter')
✓ built in 691ms
error during build:
TypeError: Cannot read properties of undefined (reading 'filter')
    at Object.handler (file:///Users/adamijak/Git/adamijak/navigator/web/node_modules/@sveltejs/kit/src/exports/vite/index.js:744:24)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async PluginDriver.hookParallel (file:///Users/adamijak/Git/adamijak/navigator/web/node_modules/rollup/dist/es/shared/node-entry.js:25461:17)
    at async file:///Users/adamijak/Git/adamijak/navigator/web/node_modules/rollup/dist/es/shared/node-entry.js:26787:13
    at async catchUnfinishedHookActions (file:///Users/adamijak/Git/adamijak/navigator/web/node_modules/rollup/dist/es/shared/node-entry.js:25905:16)
    at async build (file:///Users/adamijak/Git/adamijak/navigator/web/node_modules/vite/dist/node/chunks/dep-df561101.js:48011:22)
    at async CAC.<anonymous> (file:///Users/adamijak/Git/adamijak/navigator/web/node_modules/vite/dist/node/cli.js:822:9)
```

### System Info

```Shell
System:
    OS: macOS 14.0
    CPU: (8) arm64 Apple M1 Pro
    Memory: 2.45 GB / 32.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 20.7.0 - /opt/homebrew/bin/node
    npm: 10.1.0 - /opt/homebrew/bin/npm
  Browsers:
    Safari: 17.0
  npmPackages:
    @sveltejs/adapter-static: ^2.0.3 => 2.0.3 
    @sveltejs/kit: ^1.20.4 => 1.25.1 
    @sveltejs/package: ^2.0.0 => 2.2.2 
    svelte: ^4.0.5 => 4.2.1 
    vite: ^4.4.2 => 4.4.9
```

### Severity

blocking an upgrade

**Comment by benmccann** [comment]
Can you please provide a repository to reproduce the issue?

**Comment by adamijak** [comment]
> Can you please provide a repository to reproduce the issue?

https://github.com/adamijak/svelte-issue

**Comment by paoloricciuti** [comment]
Is there a specific reason you are using vite library build instead of svelte-package?

**Comment by adamijak** [comment]
> Is there a specific reason you are using vite library build instead of svelte-package?

svelte-package did not produce single .js file in dist folder
my desired state is to compile lib to single .js and use svelte components as webcomponents

**Comment by eltigerchino** [comment]
It's currently recommended to use the official `svelte-package` package to build your library.
- https://svelte.dev/docs/kit/packaging
