### ISSUE TITLE
Vite define not replacing values in node_modules

### ISSUE THREAD

**Issue by Neo-Ciber94** [sveltejs/kit#10844]
### Describe the bug

When using `config.define` in svelte/kit is not replacing the values from `node_modules`

```ts
// vite.config.ts

import { sveltekit } from '@sveltejs/kit/vite';
import { defineConfig } from 'vite';

export default defineConfig({
	plugins: [sveltekit()],
	define: {
		'__HELLO_MESSAGE__': JSON.stringify('Hello Amigos!')
	}
});
```

This is not replacing the `__HELLO_MESSAGE__` in libraries in **node_modules** or not correctly, after build the generated chunks contains *'Hello Amigos!'*, but when running it throws: `ReferenceError: __HELLO_MESSAGE__ is not defined`

### Reproduction

I created this repo:

https://github.com/Neo-Ciber94/vite-define-node-modules

But in short:

```ts
// vite.config.ts

import { sveltekit } from '@sveltejs/kit/vite';
import { defineConfig } from 'vite';

export default defineConfig({
	plugins: [sveltekit()],
	define: {
		'__HELLO_MESSAGE__': JSON.stringify('Hello Amigos!')
	}
});
```

```svelte
<!-- +page.svelte -->
<script lang="ts">
	import { sayHelloVar } from 'say-hello-env';

	const message = sayHelloVar();
</script>

<h1 data-page-content>{message}</h1>
```

```ts
// This is a library in node_modules
// https://www.npmjs.com/package/say-hello-env

/**
 * Returns a hello message from the `__HELLO_MESSAGE__`.
 */
export function sayHelloVar() {
    return __HELLO_MESSAGE__;
}
```

When running this throws: `ReferenceError: __HELLO_MESSAGE__ is not defined`

### Logs

```shell
ReferenceError: __HELLO_MESSAGE__ is not defined\n    
at sayHelloVar (file:///***/define-test/node_modules/say-hello-env/dist/index.js:11:5)   \n    
at file:///***/define-test/.svelte-kit/output/server/entries/pages/_page.svelte.js:4:19  \n    
at Object.$$render (file:///***/define-test/.svelte-kit/output/server/chunks/ssr.js:84:18)\n    
at Object.default (file:///***/define-test/.svelte-kit/output/server/chunks/internal.js:68:98)\n    
at file:///***/define-test/.svelte-kit/output/server/entries/fallbacks/layout.svelte.js:3:42\n    
at Object.$$render (file:///***/define-test/.svelte-kit/output/server/chunks/ssr.js:84:18)\n    
at file:///***/define-test/.svelte-kit/output/server/chunks/internal.js:57:121\n    
at $$render (file:///***/define-test/.svelte-kit/output/server/chunks/ssr.js:84:18)      \n    
at Object.render (file:///***/define-test/.svelte-kit/output/server/chunks/ssr.js:92:20) \n    
at render_response (file:///***/define-test/.svelte-kit/output/server/index.js:1391:34)
```

### System Info

```shell
System:
    OS: Windows 10 10.0.22621
    CPU: (8) x64 Intel(R) Core(TM) i5-8300H CPU @ 2.30GHz
    Memory: 5.34 GB / 15.88 GB
  Binaries:
    Node: 18.17.0 - D:\Program Files\nodejs\node.EXE
    Yarn: 1.22.19 - D:\Program Files\nodejs\yarn.CMD
    npm: 9.6.7 - D:\Program Files\nodejs\npm.CMD
    pnpm: 8.7.6 - D:\Program Files\nodejs\pnpm.CMD
  Browsers:
    Edge: Spartan (44.22621.2283.0), Chromium (117.0.2045.60)
    Internet Explorer: 11.0.22621.1
```

### Severity

annoyance

**Comment by Rishab49** [comment]
Hey @Neo-Ciber94 try adding following to see if it works
```
ssr:{
 noExternal:['say-hello-env']
}

```

**Comment by Neo-Ciber94** [comment]
@Rishab49 thanks, that works.

Didn't know it need to be marked as noExternal to be reached by vite.

**Comment by Neo-Ciber94** [comment]
Closing this, `noExternal` was the solution.
