### ISSUE TITLE
Svelte "TypeError: Cannot read properties of undefined (reading 'from')" and 'Module "buffer" has been externalized for browser compatibility.'

### ISSUE THREAD

**Issue by Necoo33** [sveltejs/kit#10874]
### Describe the bug

Hello. I'm trying to create an authentication flow on svelte/sveltekit with using sveltekit api's and server side load function.

This is my "/" route:

```html

<script>
    let statusMessage = "";

    function changeStatusMessage(message){
        statusMessage = message;
    };

    async function handleSubmit(param){
        param.preventDefault();

        let nicknameInput = document.querySelector("#nicknameInput");
        let passwordInput = document.querySelector("#passwordInput");

        console.log("nickname input value: ", nicknameInput.value);
        console.log("password input value: ", passwordInput.value);

        let request = await fetch("/auth/logining", {
            method: "POST",
            headers: {
                "Content-Type": "application/json"
            },
            body: JSON.stringify({ nickname: nicknameInput.value, password: passwordInput.value })
        });

        let response = await request.json();

        console.log(response);

        if(!response.status){
            changeStatusMessage(response.message);
        } else {
            location.assign(`/panel?token=${response.body.token}`)
        };
    }

</script>

<h2 class="login-page-title">Necdetiye Ön Muhasebe Programına Hoş Geldiniz!</h2>

<main class="login-page">
    <form on:submit={handleSubmit}>
        <label for="nicknameInput">Kullanıcı Adı:</label>
        <input type="text" name="nickname" id="nicknameInput" placeholder="Kullanıcı Adınız">
        <label for="passwordInput">Şifre:</label>
        <input type="password" name="password" id="passwordInput" placeholder="Şifreniz">
        <input type="submit" value="Giriş Yap">
        <p>{statusMessage}</p>
    </form>
</main>

```

this is my "/auth/logining" api route:

```javascript

import { redirect, json } from "@sveltejs/kit";
import { fetchDatasWithFiltering } from "../../../lib/firebase";
import { decrypt4 } from "necdetiye-crypto";
import { sign } from "jsonwebtoken";

export async function POST(context){
    console.log("our context object: ", context);

    let body = await context.request.json();

    console.log("our body object: ", body);

    let getUserObject = await fetchDatasWithFiltering("users", "nickname", "==", body.nickname);

    console.log("our user object: ", getUserObject);

    if(!getUserObject || getUserObject.length === 0 || getUserObject[0].nickname !== body.nickname){
        return json({ status: false, message: "Hata: Bu kullanıcı ismine sahip hiçbir kullanıcı yok." });
    };

    if(decrypt4(getUserObject[0].password, "asdfsdasfasdsfd") !== body.password){
        return json({ status: false, message: "Hata: Kullanıcı şifresi yanlış." });
    };

    let userObj = {
        nickname: getUserObject[0].nickname,
        email: getUserObject[0].email,
        role: getUserObject[0].role
    }

    let jwtToken = sign({ "nickname": userObj.nickname,
                          "email": userObj.email,
                          "role": userObj.role }, "kfnlksdfhvnkjhsdfkgjs", { expiresIn: "100 days" });

    return new Response(JSON.stringify({
        status: 200,
        headers: {
            "Content-Type": "application/json"
        },
        body: { message: "successfull authentication", token: jwtToken }
    }));
};

```

When i take the positive response from that route, i redirect to the "/panel" route with a query parameter that contains jwt token that created.

This is the +page.js page of "/panel" route:

```javascript

import { redirect } from '@sveltejs/kit';
import { decode, verify } from 'jsonwebtoken';

/** @type {import('./$types').PageLoad} */
export function load({url, request, cookies}) {
    console.log("url object: ", url);
    console.log("our cookie: ", url.searchParams.get("token"))

    let ourToken = url.searchParams.get("token");

    if(!ourToken){
        throw redirect(303, "/?error=unauthorized");
    };

    let verifyToken = verify(ourToken, "kfnlksdfhvnkjhsdfkgjs");

    if(!verifyToken){
        throw redirect(303, "/?error=malformedtoken");
    };

    let user = decode(ourToken);

    console.log("/panel server side user obj: ", user);

    return {
        props: {
            data: user
        }
    }
}

```

this is my +layout.svelte page:

```html

<script>
    export let data;

    console.log("+layout.svelte page data: ", data);
</script>

<slot {data}></slot>

```

and this is +page.svelte file of "/panel" route/folder:

```html

<script>
    import { setContext, hasContext, getContext } from 'svelte';

    export let data;

    console.log("+page.svelte page data obj: ", data);

    if(!hasContext("user")){
        setContext("user", data.props.data);
    }

    console.log("our context: ", getContext("user"));
</script>

```

### Reproduction

I'm trying to create an authentication flow with this steps:

1 - i'm fetching a server api using fetch api and get jwt token from that api.

2 - i'm using "location.assign()" method with redirecting user to "/panel" route with a query parameter named token that contains token value.

3 - i'm again using jsonwebtoken liblary to verify and decode my jwt token on +page.js pages load function.

4 - i'm taking that user object on +layout.svelte function and sending it to inner routes.

5 - i take that user object on +page.svelte page of "/panel" route and use setContext, hasContext and getContext functions on it.

### Logs

```shell
My server logs like that:



url object:  URL {
  href: 'http://localhost:5173/panel?token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuaWNrbmFtZSI6ImFkbWluIiwiZW1haWwiOiJpbGtlcm1vYmlseWExMDlAZ21haWwuY29tIiwicm9sZSI6ImFkbWluIiwiaWF0IjoxNjk3Mzc0NDIxLCJleHAiOjE3MDYwMTQ0MjF9.PMYkl8Q9hGW9R1ztHFw8yeYdEsDmHTvyB-kNcGCrxW4',
  origin: 'http://localhost:5173',
  protocol: 'http:',
  username: '',
  password: '',
  host: 'localhost:5173',
  hostname: 'localhost',
  port: '5173',
  pathname: '/panel',
  search: '?token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuaWNrbmFtZSI6ImFkbWluIiwiZW1haWwiOiJpbGtlcm1vYmlseWExMDlAZ21haWwuY29tIiwicm9sZSI6ImFkbWluIiwiaWF0IjoxNjk3Mzc0NDIxLCJleHAiOjE3MDYwMTQ0MjF9.PMYkl8Q9hGW9R1ztHFw8yeYdEsDmHTvyB-kNcGCrxW4',
  searchParams: URLSearchParams {
    'token' => 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuaWNrbmFtZSI6ImFkbWluIiwiZW1haWwiOiJpbGtlcm1vYmlseWExMDlAZ21haWwuY29tIiwicm9sZSI6ImFkbWluIiwiaWF0IjoxNjk3Mzc0NDIxLCJleHAiOjE3MDYwMTQ0MjF9.PMYkl8Q9hGW9R1ztHFw8yeYdEsDmHTvyB-kNcGCrxW4' },
  hash: ''
}
our cookie:  eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuaWNrbmFtZSI6ImFkbWluIiwiZW1haWwiOiJpbGtlcm1vYmlseWExMDlAZ21haWwuY29tIiwicm9sZSI6ImFkbWluIiwiaWF0IjoxNjk3Mzc0NDIxLCJleHAiOjE3MDYwMTQ0MjF9.PMYkl8Q9hGW9R1ztHFw8yeYdEsDmHTvyB-kNcGCrxW4
/panel server side user obj:  {
  nickname: 'admin',
  email: 'blabla@gmail.com',
  role: 'admin',
  iat: 1697374421,
  exp: 1706014421
}
+layout.svelte page data:  {}
+page.svelte page data obj:  {
  props: {
    data: {
      nickname: 'admin',
      email: 'blabla@gmail.com',
      role: 'admin',
      iat: 1697374421,
      exp: 1706014421
    }
  }
}

```

but my browser outputs like that and on page it only wrotes "500 internal error":

```

client.js?v=de4db00a:2083 Module "buffer" has been externalized for browser compatibility. Cannot access "buffer.Buffer" in client code. See http://vitejs.dev/guide/troubleshooting.html#module-externalized-for-browser-compatibility for more details.
warn	@	client.js?v=de4db00a:2083
get	@	browser-external:buffer:9
node_modules/safe-buffer/index.js	@	index.js:4
__require	@	chunk-XNHBATJA.js?v=de4db00a:5
node_modules/jws/lib/sign-stream.js	@	sign-stream.js:2
__require	@	chunk-XNHBATJA.js?v=de4db00a:5
node_modules/jws/index.js	@	index.js:2
__require	@	chunk-XNHBATJA.js?v=de4db00a:5
node_modules/jsonwebtoken/decode.js	@	decode.js:1
__require	@	chunk-XNHBATJA.js?v=de4db00a:5
node_modules/jsonwebtoken/index.js	@	index.js:2
__require	@	chunk-XNHBATJA.js?v=de4db00a:5
(anonim)	@	index.js:8

```

```

client.js?v=de4db00a:2083 The next HMR update will cause the page to reload
warn	@	client.js?v=de4db00a:2083
handle_error	@	client.js?v=de4db00a:1328
_hydrate	@	client.js?v=de4db00a:1834
await in _hydrate (eş zamansız)		
start	@	start.js:22
(anonim)	@	panel?token=eyJhbGci…mHTvyB-kNcGCrxW4:28
Promise.then (eş zamansız)		
(anonim)	@	panel?token=eyJhbGci…mHTvyB-kNcGCrxW4:27

```

```

TypeError: Cannot read properties of undefined (reading 'from')
    at node_modules/safe-buffer/index.js (index.js:12:12)
    at __require (chunk-XNHBATJA.js?v=de4db00a:5:50)
    at node_modules/jws/lib/sign-stream.js (sign-stream.js:2:14)
    at __require (chunk-XNHBATJA.js?v=de4db00a:5:50)
    at node_modules/jws/index.js (index.js:2:18)
    at __require (chunk-XNHBATJA.js?v=de4db00a:5:50)
    at node_modules/jsonwebtoken/decode.js (decode.js:1:11)
    at __require (chunk-XNHBATJA.js?v=de4db00a:5:50)
    at node_modules/jsonwebtoken/index.js (index.js:2:11)
    at __require (chunk-XNHBATJA.js?v=de4db00a:5:50)

```

```

<Root> was created without expected prop 'form'
warn	@	client.js?v=de4db00a:2083
(anonim)	@	root.svelte:39
run	@	utils.js:41
(anonim)	@	Component.js:47
flush	@	scheduler.js:99
init	@	Component.js:164
Root	@	root.svelte:21
createProxiedComponent	@	svelte-hooks.js?v=de4db00a:341
ProxyComponent	@	proxy.js?v=de4db00a:242
Proxy<Root>	@	proxy.js?v=de4db00a:349
initialize	@	client.js?v=de4db00a:288
_hydrate	@	client.js?v=de4db00a:1840
await in _hydrate (eş zamansız)		
start	@	start.js:22
(anonim)	@	panel?token=eyJhbGci…mHTvyB-kNcGCrxW4:28
Promise.then (eş zamansız)		
(anonim)	@	panel?token=eyJhbGci…mHTvyB-kNcGCrxW4:27

```

I don't have any idea why this error happens. I run the "decode" function of jsonwebtoken liblary on +page.js file, which is suppose to be a server component. And how can i fix this weird error?
```


### System Info

```shell
System:
    OS: Windows 10 10.0.22621
    CPU: (8) x64 11th Gen Intel(R) Core(TM) i5-1135G7 @ 2.40GHz
    Memory: 9.12 GB / 23.70 GB
  Binaries:
    Node: 18.12.1 - D:\Node.js\node.EXE
    npm: 8.19.2 - D:\Node.js\npm.CMD
  Browsers:
    Edge: Chromium (118.0.2088.46)
    Internet Explorer: 11.0.22621.1
  npmPackages:
    svelte: ^4.0.5 => 4.2.1
```

### Severity

blocking all usage of svelte

**Comment by dominikg** [comment]
please provide a link to a complete and minimal reproduction. this is required. 

Note that it's very likely not an issue in kit but either the crypto library you use or your setup. We do not provide support on github issues and i recommend asking for help on https://svelte.dev/chat

**Comment by Necoo33** [comment]
> please provide a link to a complete and minimal reproduction. this is required. 
> 
> Note that it's very likely not an issue in kit but either the crypto library you use or your setup. We do not provide support on github issues and i recommend asking for help on https://svelte.dev/chat 
> 
> 
> 

Issue is quite easy: the "decode" function of node.js's famous most well known jsonwebtoken liblary is not working on +page.js page, which it suppose to be a server component. In node.js servers it works without any problem and because of that it should work on sveltekit's server components also, but i don't know why it doesn't. Issue is that, there is no need for me to sending a github repo for that.

**Comment by dominikg** [comment]
from our new issue dialog:
> A link to a repository, or a fork of https://node.new/sveltekit, that reproduces the issue. Reproductions must be [short, self-contained and correct](http://sscce.org/) and must not contain files or code that aren't relevant to the issue — please do NOT just paste a link to your project. Explaining how to reproduce is generally not enough. It pushes the burden of creating a reproduction project onto a small set of volunteer maintainers and isn't scalable. If no reproduction is provided, the issue will be closed.

again, this is not the place to ask how to set up authentication with sveltekit, this is the place to report reproducible bugs. "i don't know" doesn't count

**Comment by Necoo33** [comment]
> from our new issue dialog:
> > A link to a repository, or a fork of https://node.new/sveltekit, that reproduces the issue. Reproductions must be [short, self-contained and correct](http://sscce.org/) and must not contain files or code that aren't relevant to the issue — please do NOT just paste a link to your project. Explaining how to reproduce is generally not enough. It pushes the burden of creating a reproduction project onto a small set of volunteer maintainers and isn't scalable. If no reproduction is provided, the issue will be closed.
> 
> again, this is not the place to ask how to set up authentication with sveltekit, this is the place to report reproducible bugs. "i don't know" doesn't count
> 
> 

Okey, that's fine. I try to create authentication flow with other ways, if i couldn't, if your framework is not stable yet or it's too nitty gritty i use next.js and you'll lose a developer. I don't want any solution from you anymore. I never deal with adding a github repo or minimal reproduction for that simple thing. I'm not your servant. Your +page.js components not exactly work like server component. Do whatever you want that report.

**Comment by dummdidumm** [comment]
Sounds like you want `+layout/page.server.js`, not `+layout/page.js`, see https://kit.svelte.dev/docs/load#universal-vs-server

**Comment by Necoo33** [comment]
> Sounds like you want `+layout/page.server.js`, not `+layout/page.js`, see https://kit.svelte.dev/docs/load#universal-vs-server

thanks, it helped me.
