### ISSUE TITLE
Error 500 when accessing static assets using Bun

### ISSUE THREAD

**Issue by jerefrer** [sveltejs/kit#10927]
### Describe the bug

When using [Bun](https://bun.sh/guides/ecosystem/sveltekit), all requests to static content will fail wit a 500 error.

Therefore I cannot use Bun at all and had to fallback to pnpm.

Thanks for reading :)

### Reproduction

1. Run:

```bash
bun create svelte@latest example-app
bun install
bun run dev
```

2. Open `http://localhost:5173/favicon.png`

### Logs

```Shell
TypeError: parse is not a function
    at /home/lekshe/js/example-app/node_modules/sirv/build.js:168:18
    at file:///home/lekshe/js/example-app/node_modules/@sveltejs/kit/src/exports/vite/dev/index.js:390:7
    at call (file:///home/lekshe/js/example-app/node_modules/vite/dist/node/chunks/dep-bb8a8339.js:50689:7)
    at next (file:///home/lekshe/js/example-app/node_modules/vite/dist/node/chunks/dep-bb8a8339.js:50633:5)
    at Function.handle (file:///home/lekshe/js/example-app/node_modules/vite/dist/node/chunks/dep-bb8a8339.js:50636:3)
    at Server.app (file:///home/lekshe/js/example-app/node_modules/vite/dist/node/chunks/dep-bb8a8339.js:50501:37)
    at Server.emit (node:events:514:28)
    at parserOnIncoming (node:_http_server:1107:12)
    at HTTPParser.parserOnHeadersComplete (node:_http_common:119:17)
```

### System Info

```Shell
System:
    OS: Linux 5.15 Ubuntu 22.04.2 LTS 22.04.2 LTS (Jammy Jellyfish)
    CPU: (2) x64 Intel(R) Core(TM) i7-2760QM CPU @ 2.40GHz
    Memory: 1.11 GB / 3.83 GB
    Container: Yes
    Shell: 5.1.16 - /bin/bash
  Binaries:
    Node: 18.17.1 - ~/.nvm/versions/node/v18.17.1/bin/node
    Yarn: 1.22.19 - /mnt/c/Program Files/nodejs/yarn
    npm: 9.6.7 - ~/.nvm/versions/node/v18.17.1/bin/npm
    pnpm: 8.6.12 - ~/.local/share/pnpm/pnpm
  Browsers:
    Chrome: 116.0.5845.96
  npmPackages:
    @sveltejs/adapter-auto: ^2.0.0 => 2.1.0
    @sveltejs/kit: ^1.20.4 => 1.27.1
    svelte: ^4.0.5 => 4.2.2
    vite: ^4.4.2 => 4.5.0
```

### Severity

serious, but I can work around it

**Comment by johnyvelho** [comment]
same here

**Comment by eltigerchino** [comment]
I think the issue occurs because `bun` is resolving the dependencies incorrectly. It downloads the wrong version of `@polka/url` so the `parse` function which it exports and is needed by SvelteKit, doesn't exist.

If you look inside `node_modules`, and take a look at the `package.json` of the `sirv` package, you'll see that `@polka/url` specifies version `1.0.0-next.20`:
```json
  "dependencies": {
    "@polka/url": "^1.0.0-next.20",
    "mrmime": "^1.0.0",
    "totalist": "^3.0.0"
  }
```
However, `bun` is installing version `1.0.0-next.9` (take a look at the `@polka/url` folder in `node_modules` next).

I think this is a bun issue so I'll go ahead and close this for now.
