### ISSUE TITLE
Incorrect Paths for Font Assets in Vite 5 Build Output

### ISSUE THREAD

**Issue by vnphanquang** [sveltejs/kit#11085]
### Describe the bug

Paths for font assets are incorrect in build output. For example:

In vite 4: /_app/immutable/assets/font.woff2 (correct)
In vite 5: /_app/immutable/assets/nodes/font.woff2 (incorrect)

Note the added nodes directory. The actual font file still lives at /_app/immutable/assets/ and not in nodes. This nested nodes folder seems to be new in vite 5, it nows hosts all the built css.

### Reproduction

Please clone this repo https://github.com/vnphanquang/svelte-4-vite-5 and follow the steps below

1. Install dependencies `pnpm install`
3. Build `pnpm build`
4. Preview `pnpm preview`
5. Go to `/about` page
6. Verify in network tab, fonts files are 404 (there should also be console logs)

### Logs

```Shell
Below is log server when navigates to `/about`


Error: Not found: /_app/immutable/assets/nodes/fira-mono-latin-400-normal.yoy1YEIp.woff2
    at resolve (file:///[...truncated...]/.svelte-kit/output/server/index.js:3477:18)
    at resolve (file:///[...truncated...]/.svelte-kit/output/server/index.js:3304:34)
    at #options.hooks.handle (file:///[...truncated...]/.svelte-kit/output/server/index.js:3543:61)
    at respond (file:///[...truncated...]/.svelte-kit/output/server/index.js:3302:43)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
Error: Not found: /_app/immutable/assets/nodes/fira-mono-all-400-normal.dpry7Ug7.woff
    at resolve (file:///[...truncated...]/.svelte-kit/output/server/index.js:3477:18)
    at resolve (file:///[...truncated...]/.svelte-kit/output/server/index.js:3304:34)
    at #options.hooks.handle (file:///[...truncated...]/.svelte-kit/output/server/index.js:3543:61)
    at respond (file:///[...truncated...]/.svelte-kit/output/server/index.js:3302:43)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
```
```


### System Info

```Shell
System:
    OS: Linux 6.1 Arch Linux
    CPU: (4) x64 Intel(R) Core(TM) i5-4590 CPU @ 3.30GHz
    Memory: 2.48 GB / 15.57 GB
    Container: Yes
    Shell: 3.6.1 - /usr/bin/fish
  Binaries:
    Node: 14.21.3 - ~/.volta/tools/image/node/14.21.3/bin/node
    npm: 6.14.18 - ~/.volta/tools/image/node/14.21.3/bin/npm
    pnpm: 8.10.0 - ~/.volta/bin/pnpm
  npmPackages:
    @sveltejs/adapter-auto: ^2.0.0 => 2.1.1 
    @sveltejs/kit: ^1.27.4 => 1.27.6 
    svelte: ^4.0.5 => 4.2.5 
    vite: ^5.0.0 => 5.0.0 
```
```


### Severity

blocking an upgrade

### Additional Information

Initially reported in https://github.com/sveltejs/kit/issues/11062. Not a huge deal for me since i'm still on vite 4. But this should be resolved before support for vite 5 is officially announced.

**Comment by benmccann** [comment]
FYI @dominikg @bluwy

**Comment by benmccann** [comment]
The CSS contains a relative URL to the font `url(./fira-mono-all-400-normal.1e3b098c.woff)`. In Vite 4, the CSS is output into the `assets` directory: `.svelte-kit/output/client/_app/immutable/assets/0.fa9427ff.css`. In Vite 5, the CSS is output into the `nodes` directory: `.svelte-kit/output/client/_app/immutable/assets/nodes/0.e1dUBGNb.css`.

**Comment by benmccann** [comment]
Not sure if it's related, but the Rollup 4 migration guide states:

> Also, the path of a module is no longer prepended to the file name automatically but is included in the `[name]` placeholder.

However, it's unclear if this only occurs when `preserveModules: true`. We- have not set this and so would have the default value of `false`.

**Comment by benmccann** [comment]
My current assumption is that this issue is being caused by:

https://github.com/sveltejs/kit/blob/a7f8bdcfabce5cda85dd073a21d0afb6138a7a08/packages/kit/src/exports/vite/index.js#L536

**Comment by benmccann** [comment]
This was fixed in Vite 5.0.3

**Comment by ZuBB** [comment]
I am still (kind of) getting this. I have an error message in the browser's console, but I also see that the font has been loaded to the page and applied.

<img width="1073" alt="image" src="https://github.com/sveltejs/kit/assets/597016/555d6f30-9470-4a82-9ac5-dc6fb4a23215">

Any guesses what is going on?

**Comment by vnphanquang** [comment]
@ZuBB not sure there but it looks like that happened before vite dev server was connected so perhaps outdated cache. As long as you don't get the same error afterwards especially in build output. If you see the same error consistently, it's helpful to create a reproduction repo for maintainers to look at. Good luck.

**Comment by ZuBB** [comment]
I came to the conclusion that this is some bug with my browser. I see those errors even when the subject site is not opened. I have no idea how that can happen. Sorry for the false alarm

**Comment by vnphanquang** [comment]
@ZuBB Sometimes it's browser extension. Try incognito / private mode perhaps.
