### ISSUE TITLE
Error when loading date-fns dependency: Cannot read property 'browser' of null

### ISSUE THREAD

**Issue by kahverengi001** [sveltejs/kit#1111]
**Describe the bug**
After the first start of the project, and the first time visiting the localhost:3000, in the kit console it throws the below log.

**Logs**
<details>
  <summary>Logs</summary>

```
$ svelte-kit dev --host=0.0.0.0

  SvelteKit v1.0.0-next.80

  local:   http://localhost:3000
  network: http://192.168.1.228:3000
  network: http://172.16.171.1:3000
  network: http://172.16.253.1:3000
  network: http://172.28.0.1:3000


9:26:20 PM [vite] new dependencies found: date-fns, updating...
9:26:21 PM [vite] ✨ dependencies updated, reloading page...
Cannot read property 'browser' of null
TypeError: Cannot read property 'browser' of null
    at Module.load (/src/routes/_home.svelte:60:28)
    at load (eval at instantiateModule (/home/kahverengi/Projeler/Pano/Pano Web Platform UI/vanilla-theme/node_modules/vite/dist/node/chunks/dep-66eb515d.js:69030:9), <anonymous>:14:55)
    at load_node (file:///home/kahverengi/Projeler/Pano/Pano%20Web%20Platform%20UI/vanilla-theme/node_modules/@sveltejs/kit/dist/ssr.js:760:30)
    at respond (file:///home/kahverengi/Projeler/Pano/Pano%20Web%20Platform%20UI/vanilla-theme/node_modules/@sveltejs/kit/dist/ssr.js:982:21)
    at async render_page (file:///home/kahverengi/Projeler/Pano/Pano%20Web%20Platform%20UI/vanilla-theme/node_modules/@sveltejs/kit/dist/ssr.js:1130:20)
    at async render (file:///home/kahverengi/Projeler/Pano/Pano%20Web%20Platform%20UI/vanilla-theme/node_modules/@sveltejs/kit/dist/ssr.js:1260:10)
    at async ssr (file:///home/kahverengi/Projeler/Pano/Pano%20Web%20Platform%20UI/vanilla-theme/node_modules/@sveltejs/kit/dist/ssr.js:1247:10)
    at async Immediate.<anonymous> (file:///home/kahverengi/Projeler/Pano/Pano%20Web%20Platform%20UI/vanilla-theme/node_modules/@sveltejs/kit/dist/chunks/index2.js:3297:23)

```
</details>

**To Reproduce**
First, import date-fns package to your project. Then just simply import this in your component:
```
<script>
import { format } from "date-fns";
</script>
```

**Expected behavior**
Vite to load date-fns package successfully.

**Information about your SvelteKit Installation:**

<details>
  <summary>Diagnostics</summary>

 ```
 System:
    OS: Linux 5.10 Arch Linux
    CPU: (8) x64 Intel(R) Core(TM) i7-4720HQ CPU @ 2.60GHz
    Memory: 825.36 MB / 15.54 GB
    Container: Yes
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 15.14.0 - /usr/bin/node
    Yarn: 1.22.10 - /usr/bin/yarn
    npm: 7.10.0 - /usr/bin/npm
  Browsers:
    Chromium: 90.0.4430.72
    Firefox: 87.0
  npmPackages:
    @sveltejs/kit: next => 1.0.0-next.80 
    svelte: ^3.37.0 => 3.37.0 
    vite: ^2.1.5 => 2.1.5 
```
</details>

**Severity**
Well, it still works but dunno why does it throws this, if it works.

**Comment by benmccann** [comment]
It would be more useful to file this issue in the Vite repo. Vite maintainers won't discover it or fix it if it's in this repo.

It's possible that https://github.com/vitejs/vite/pull/3039 would fix this

**Comment by bluwy** [comment]
This should be fixed now based on Ben's link. And there has been a lot of changes to similar issues like this up till now, which might inadvertently fix this. Closing this, but do re-open if it's still an issue.
