### ISSUE TITLE
`svelte-kit build` throws an error if the `name` field is left out of `package.json`

### ISSUE THREAD

**Issue by emme1444** [sveltejs/kit#1112]
**Describe the bug**

In the new scaffold project created by `npm init svelte@next`, I can no longer remove the `name` field from the `package.json` file. Since, if I try to, whenever I use `svelte-kit build` to build for production, `svelte-kit` throws an error like this:

```
no name found in package.json
> no name found in package.json
Error: no name found in package.json
    at getPkgName (C:\Users\user\dev\p\project\app\node_modules\vite\dist\node\chunks\dep-66eb515d.js:44320:15)
    at doBuild (C:\Users\user\dev\p\project\app\node_modules\vite\dist\node\chunks\dep-66eb515d.js:44243:39)
    at async Object.build (C:\Users\user\dev\p\project\app\node_modules\vite\dist\node\chunks\dep-66eb515d.js:44174:16)
    at async build_service_worker (file:///C:/Users/user/dev/p/project/app/node_modules/@sveltejs/kit/dist/chunks/index5.js:952:2)
    at async build (file:///C:/Users/user/dev/p/project/app/node_modules/@sveltejs/kit/dist/chunks/index5.js:509:3)
    at async file:///C:/Users/user/dev/p/project/app/node_modules/@sveltejs/kit/dist/cli.js:678:23
```

It works fine with the `name` present.

This was not a problem when scaffolding a project a couple days ago.

**To Reproduce**

1. `npm init svelte@next`
2. Remove the `name` field from the `package.json` file
3. `svelte-kit build` (`npm run build`)

**Expected behavior**

No error is thrown.

**Stacktraces**

<details>
  <summary>Stack trace</summary>

```
Error: no name found in package.json
    at getPkgName (C:\Users\user\dev\p\project\app\node_modules\vite\dist\node\chunks\dep-66eb515d.js:44320:15)
    at doBuild (C:\Users\user\dev\p\project\app\node_modules\vite\dist\node\chunks\dep-66eb515d.js:44243:39)
    at async Object.build (C:\Users\user\dev\p\project\app\node_modules\vite\dist\node\chunks\dep-66eb515d.js:44174:16)
    at async build_service_worker (file:///C:/Users/user/dev/p/project/app/node_modules/@sveltejs/kit/dist/chunks/index5.js:952:2)
    at async build (file:///C:/Users/user/dev/p/project/app/node_modules/@sveltejs/kit/dist/chunks/index5.js:509:3)
    at async file:///C:/Users/user/dev/p/project/app/node_modules/@sveltejs/kit/dist/cli.js:678:23
```

</details>

**Information about your SvelteKit Installation:**

<details>
  <summary>Diagnostics</summary>

- The output of `npx envinfo --system --npmPackages svelte,@sveltejs/kit,vite --binaries --browsers`:

```
  System:
    OS: Windows 10 10.0.19042
    CPU: (4) x64 Intel(R) Core(TM) i5-4460  CPU @ 3.20GHz
    Memory: 11.88 GB / 23.92 GB
  Binaries:
    Node: 14.15.4 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.10 - ~\AppData\Roaming\npm\yarn.CMD
    npm: 6.14.10 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Chrome: 90.0.4430.72
    Edge: Spartan (44.19041.423.0), Chromium (89.0.774.77)
    Internet Explorer: 11.0.19041.1
  npmPackages:
    @sveltejs/kit: next => 1.0.0-next.80
    svelte: ^3.29.0 => 3.37.0
    vite: ^2.1.0 => 2.1.5
```

- Your adapter (e.g. Node, static, Vercel, Begin, etc...): 
  Node (`adapter-node`)
</details>

**Severity**

Not very severe.

**Additional context**

- From the stacktrace it looks like the error comes from Vite.

**Comment by benmccann** [comment]
Yes, you're correct that it's coming from Vite: https://github.com/vitejs/vite/blob/57980d27ee10f1f92e532a0975d4ab39ce27d3ed/packages/vite/src/node/build.ts#L397

If you'd like that behavior changed, you'd have to file the issue there since it's not coming from this codebase. If you do so, it would be helpful to explain why you'd like to leave `name` empty as it seems like a somewhat odd requirement and I expect it may not be prioritized without some explanation as to why it would be important to do
