### ISSUE TITLE
adapter-vercel + inlineStyleThreshold = build completed but stuck on deployment

### ISSUE THREAD

**Issue by eur2** [sveltejs/kit#11173]
### Describe the bug

Hi, I'm encountering a weird bug using SvelteKit, the Vercel adapter and deploying on Vercel:
When the building step is done on Vercel, the deployment summary and the other steps (running checks, assigning domains) are not done but the deployment duration is continuing. At the end, the deployment is failing.

I'm encountering this bug since a bit of time (one year and more) with different version of SvelteKit and adapter-vercel on different projects deployed on Vercel. Using NPM ou BUN, I get the same issue.
I just tried the last version of `adapter-vercel`(3.1.0) and using Node 20 on Vercel but I have the same issue as on Node 18 or 16.
To fix this issue, I'm just using `adapter-auto` instead of `adapter-vercel` and then all is fine.
The weird thing is that some projects are working with `adapter-vercel` and other not…

Has anyone encountered the same issue?

### Reproduction

Deploy this repo on vercel using default settings (Node 18, etc):
https://github.com/eur2/pl-bun

### System Info

```Shell
"@sveltejs/adapter-vercel": "^3.1.0",
		"@sveltejs/kit": "^1.27.6",
		"eslint": "^8.55.0",
		"eslint-config-prettier": "^9.0.0",
		"eslint-plugin-svelte": "^2.35.1",
		"prettier": "^3.1.0",
		"prettier-plugin-svelte": "^3.1.2",
		"svelte": "^4.2.8",
		"vite": "^4.5.0"
```

### Severity

annoyance

**Comment by eur2** [comment]
I just did a new test with a new project deployed on Vercel. 
Now either trying `adapter-vercel` or `adapter-auto` is not working anymore.
They both are stucked after building is done…
I'm using the last version of each pkg:
"@sveltejs/adapter-vercel": "^3.1.0",
"@sveltejs/kit": "^1.27.6",
"eslint": "^8.55.0",
"eslint-config-prettier": "^9.0.0",
"eslint-plugin-svelte": "^2.35.1",
"prettier": "^3.1.0",
"prettier-plugin-svelte": "^3.1.2",
"svelte": "^4.2.8",
"vite": "^4.5.0"

**Comment by eltigerchino** [comment]
can you share the error logs when your deployment fails?

**Comment by eur2** [comment]
There is not really an error log because I need to stop the deployment because the duration go infinite...

**Comment by eur2** [comment]
@eltigerchino Thank you for looking at the repo. There is no issue about the json request. 
In this repo, now I just removed `adapter-vercel` and remplaced with `adapter-auto`. The deployment on vercel is done in 19s !

**Comment by eltigerchino** [comment]
Very strange since adapter auto just downloads and installs adapter vercel

**Comment by eur2** [comment]
@eltigerchino On the public repo shared (https://github.com/eur2/pl-bun),
I just have tested to build locally:
- with adapter-vercel: build done but stuck (I have to manually close the command and that's probably why on Vercel the building duration is going infinite without completing the deployment)
- with adapter-auto: build done and the command is closed
It's going to be complicated to debug…

**Comment by eur2** [comment]
On another repo that also the issue, I have tested to build with `adapter-static`:
The build is fine when I'm not using `inlineStyleThreshold` in svelte.config.js if not it got stuck!
On the same repo, i have tested `adapter-vercel` without `inlineStyleThreshold`, here is the error log:
```
✓ built in 678ms
TypeError: terminated
    at Fetch.onAborted (node:internal/deps/undici/undici:11442:53)
    at Fetch.emit (node:events:514:28)
    at Fetch.terminate (node:internal/deps/undici/undici:10695:14)
    at Object.onError (node:internal/deps/undici/undici:11537:36)
    at Request.onError (/Users/gd/Developer/mbl-v3/node_modules/undici/lib/core/request.js:278:27)
    at errorRequest (/Users/gd/Developer/mbl-v3/node_modules/undici/lib/client.js:2285:13)
    at TLSSocket.onSocketClose (/Users/gd/Developer/mbl-v3/node_modules/undici/lib/client.js:1163:5)
    at TLSSocket.emit (node:events:526:35)
    at node:net:323:12
    at TCP.done (node:_tls_wrap:588:7) {
  [cause]: SocketError: other side closed
      at TLSSocket.onSocketEnd (/Users/gd/Developer/mbl-v3/node_modules/undici/lib/client.js:1129:22)
      at TLSSocket.emit (node:events:526:35)
      at endReadableNT (node:internal/streams/readable:1359:12)
      at process.processTicksAndRejections (node:internal/process/task_queues:82:21) {
    code: 'UND_ERR_SOCKET',
    socket: {
      localAddress: '192.168.1.17',
      localPort: 53469,
      remoteAddress: '188.114.96.7',
      remotePort: 443,
      remoteFamily: 'IPv4',
      timeout: undefined,
      bytesWritten: 619,
      bytesRead: 144020
    }
  }
}

node:internal/event_target:1016
  process.nextTick(() => { throw err; });
                           ^
Error: 500 /_filter
To suppress or handle this error, implement `handleHttpError` in https://kit.svelte.dev/docs/configuration#prerender
    at file:///Users/gd/Developer/mbl-v3/node_modules/@sveltejs/kit/src/core/config/options.js:212:13
    at file:///Users/gd/Developer/mbl-v3/node_modules/@sveltejs/kit/src/core/postbuild/prerender.js:64:25
    at save (file:///Users/gd/Developer/mbl-v3/node_modules/@sveltejs/kit/src/core/postbuild/prerender.js:403:4)
    at visit (file:///Users/gd/Developer/mbl-v3/node_modules/@sveltejs/kit/src/core/postbuild/prerender.js:236:3)
Emitted 'error' event on Worker instance at:
    at [kOnErrorMessage] (node:internal/worker:300:10)
    at [kOnMessage] (node:internal/worker:311:37)
    at MessagePort.<anonymous> (node:internal/worker:212:57)
    at [nodejs.internal.kHybridDispatch] (node:internal/event_target:741:20)
    at exports.emitMessage (node:internal/per_context/messageport:23:28)

Node.js v18.17.0
```
