### ISSUE TITLE
type-aware lints error with default generate eslint config

### ISSUE THREAD

**Issue by NullVoxPopuli** [sveltejs/kit#11209]
### Describe the bug

Hello!!! I'm new to svelte, first issue:

type-aware lints, when enabled, are not supported out of the box.

I also posted about this in the Discord: https://discord.com/channels/457912077277855764/1182013829626986516/1182013829626986516

### Reproduction

Project here: https://stackblitz.com/edit/stackblitz-starters-rvyx2s

- npm create svelte@latest my-app
  ```
  ❯ npm create svelte@latest my-app
  Need to install the following packages:
    create-svelte@5.3.3
  Ok to proceed? (y) y
  
  create-svelte version 5.3.3
  
  ┌  Welcome to SvelteKit!
  │
  ◇  Which Svelte app template?
  │  SvelteKit demo app
  │
  ◇  Add type checking with TypeScript?
  │  Yes, using TypeScript syntax
  │
  ◇  Select additional options (use arrow keys/space bar)
  │  Add ESLint for code linting, Add Prettier for code formatting, Add Vitest for unit testing
  │
  └  Your project is ready!
  
  ✔ Typescript
    Inside Svelte components, use <script lang="ts">
  
  ✔ ESLint
    https://github.com/sveltejs/eslint-plugin-svelte
  
  ✔ Prettier
    https://prettier.io/docs/en/options.html
    https://github.com/sveltejs/prettier-plugin-svelte#options
  
  ✔ Vitest
    https://vitest.dev
  
  Install community-maintained integrations:
    https://github.com/svelte-add/svelte-add
  
  Next steps:
    1: cd my-app
    2: npm install
    3: git init && git add -A && git commit -m "Initial commit" (optional)
    4: npm run dev -- --open
  
  To close the dev server, hit Ctrl-C
  
  Stuck? Visit us at https://svelte.dev/chat
  ```

- add to the lint config:
  ```js
  // existing
  		{
			files: ['*.svelte'],
			parser: 'svelte-eslint-parser',
			parserOptions: {
				parser: '@typescript-eslint/parser'
			},
  // new
			rules: {
				'@typescript-eslint/no-unsafe-argument': 'error',
				'@typescript-eslint/no-unsafe-assignment': 'error',
				'@typescript-eslint/no-unsafe-call': 'error',
				'@typescript-eslint/no-unsafe-member-access': 'error',
				'@typescript-eslint/no-unsafe-return': 'error'
			}
		}

  ```

- pnpm i
- pnpm eslint .

### Logs

```Shell
❯ pnpm eslint .

Oops! Something went wrong! :(

ESLint: 8.55.0

Error: Error while loading rule '@typescript-eslint/no-unsafe-argument': You have used a rule which requires parserServices to be generated. You must therefore provide a value for the "parserOptions.project" property for @typescript-eslint/parser.
Occurred while linting /home/projects/stackblitz-starters-rvyx2s/my-app/src/routes/+layout.svelte
    at getParserServices (/home/projects/stackblitz-starters-rvyx2s/my-app/node_modules/.pnpm/@typescript-eslint+utils@6.13.2_eslint@8.55.0_typescript@5.3.2/node_modules/@typescript-eslint/utils/dist/eslint-utils/getParserServices.js:29:15)
    at create (/home/projects/stackblitz-starters-rvyx2s/my-app/node_modules/.pnpm/@typescript-eslint+eslint-plugin@6.13.2_@typescript-eslint+parser@6.13.2_eslint@8.55.0_typescript@5.3.2/node_modules/@typescript-eslint/eslint-plugin/dist/rules/no-unsafe-argument.js:130:55)
    at create (/home/projects/stackblitz-starters-rvyx2s/my-app/node_modules/.pnpm/@typescript-eslint+utils@6.13.2_eslint@8.55.0_typescript@5.3.2/node_modules/@typescript-eslint/utils/dist/eslint-utils/RuleCreator.js:38:20)
    at createRuleListeners (/home/projects/stackblitz-starters-rvyx2s/my-app/node_modules/.pnpm/eslint@8.55.0/node_modules/eslint/lib/linter/linter.js:910:21)
    at runRules/< (/home/projects/stackblitz-starters-rvyx2s/my-app/node_modules/.pnpm/eslint@8.55.0/node_modules/eslint/lib/linter/linter.js:1081:110)
    at runRules (/home/projects/stackblitz-starters-rvyx2s/my-app/node_modules/.pnpm/eslint@8.55.0/node_modules/eslint/lib/linter/linter.js:1018:34)
    at _verifyWithoutProcessors (/home/projects/stackblitz-starters-rvyx2s/my-app/node_modules/.pnpm/eslint@8.55.0/node_modules/eslint/lib/linter/linter.js:1370:31)
    at _verifyWithProcessor/messageLists< (/home/projects/stackblitz-starters-rvyx2s/my-app/node_modules/.pnpm/eslint@8.55.0/node_modules/eslint/lib/linter/linter.js:1928:29)
    at _verifyWithProcessor (/home/projects/stackblitz-starters-rvyx2s/my-app/node_modules/.pnpm/eslint@8.55.0/node_modules/eslint/lib/linter/linter.js:1923:37)
    at _verifyWithConfigArray (/home/projects/stackblitz-starters-rvyx2s/my-app/node_modules/.pnpm/eslint@8.55.0/node_modules/eslint/lib/linter/linter.js:1815:25)
    at verify (/home/projects/stackblitz-starters-rvyx2s/my-app/node_modules/.pnpm/eslint@8.55.0/node_modules/eslint/lib/linter/linter.js:1452:65)
    at verifyAndFix (/home/projects/stackblitz-starters-rvyx2s/my-app/node_modules/.pnpm/eslint@8.55.0/node_modules/eslint/lib/linter/linter.js:2083:29)
    at verifyText (/home/projects/stackblitz-starters-rvyx2s/my-app/node_modules/.pnpm/eslint@8.55.0/node_modules/eslint/lib/cli-engine/cli-engine.js:254:48)
    at executeOnFiles (/home/projects/stackblitz-starters-rvyx2s/my-app/node_modules/.pnpm/eslint@8.55.0/node_modules/eslint/lib/cli-engine/cli-engine.js:834:38)
    at lintFiles (/home/projects/stackblitz-starters-rvyx2s/my-app/node_modules/.pnpm/eslint@8.55.0/node_modules/eslint/lib/eslint/eslint.js:551:23)
    at execute (/home/projects/stackblitz-starters-rvyx2s/my-app/node_modules/.pnpm/eslint@8.55.0/node_modules/eslint/lib/cli.js:402:36)
```

### System Info

```Shell
~/projects/stackblitz-starters-rvyx2s
❯ cd my-app/

~/projects/stackblitz-starters-rvyx2s/my-app
❯ npx envinfo --system --binaries --browsers --npmPackages "{svelte,@sveltejs/*,vite}"
Need to install the following packages:
  envinfo@7.11.0
Ok to proceed? (y) y

  System:
    OS: Linux 5.0 undefined
    CPU: (8) x64 Intel(R) Core(TM) i9-9880H CPU @ 2.30GHz
    Memory: 0 Bytes / 0 Bytes
    Shell: 1.0 - /bin/jsh
  Binaries:
    Node: 18.18.0 - /usr/local/bin/node
    Yarn: 1.22.19 - /usr/local/bin/yarn
    npm: 9.4.2 - /usr/local/bin/npm
    pnpm: 8.10.5 - /usr/local/bin/pnpm
```

### Severity

blocking all usage of SvelteKit

### Additional Information

Specifying the tsconfig.json,
```
        project: require.resolve(path.join(__dirname, 'tsconfig.json')),
```

<details><summary>whole file</summary>

const path = require('path');

/** @type { import("eslint").Linter.FlatConfig } */
module.exports = {
  root: true,
  extends: [
    'eslint:recommended',
    'plugin:@typescript-eslint/recommended',
    'plugin:svelte/recommended',
    'prettier',
  ],
  parser: '@typescript-eslint/parser',
  plugins: ['@typescript-eslint'],
  parserOptions: {
    sourceType: 'module',
    ecmaVersion: 2020,
    extraFileExtensions: ['.svelte'],
  },
  env: {
    browser: true,
    es2017: true,
    node: true,
  },
  overrides: [
    {
      files: ['*.svelte'],
      parser: 'svelte-eslint-parser',
      parserOptions: {
        parser: '@typescript-eslint/parser',
        project: require.resolve(path.join(__dirname, 'tsconfig.json')),
      },
      rules: {
        '@typescript-eslint/no-unsafe-argument': 'error',
        '@typescript-eslint/no-unsafe-assignment': 'error',
        '@typescript-eslint/no-unsafe-call': 'error',
        '@typescript-eslint/no-unsafe-member-access': 'error',
        '@typescript-eslint/no-unsafe-return': 'error',
      },
    },
  ],
};

</details>

then,
```bash
❯ pnpm eslint .

/home/projects/stackblitz-starters-rvyx2s/my-app/src/routes/+layout.svelte
  352:0  error  Parsing error: Cannot read file '/home/projects/stackblitz-starters-rvyx2s/my-app/.svelte-kit/tsconfig.json'

/home/projects/stackblitz-starters-rvyx2s/my-app/src/routes/+page.svelte
  352:0  error  Parsing error: Cannot read file '/home/projects/stackblitz-starters-rvyx2s/my-app/.svelte-kit/tsconfig.json'

/home/projects/stackblitz-starters-rvyx2s/my-app/src/routes/Counter.svelte
  352:0  error  Parsing error: Cannot read file '/home/projects/stackblitz-starters-rvyx2s/my-app/.svelte-kit/tsconfig.json'

/home/projects/stackblitz-starters-rvyx2s/my-app/src/routes/Header.svelte
  352:0  error  Parsing error: Cannot read file '/home/projects/stackblitz-starters-rvyx2s/my-app/.svelte-kit/tsconfig.json'

/home/projects/stackblitz-starters-rvyx2s/my-app/src/routes/about/+page.svelte
  352:0  error  Parsing error: Cannot read file '/home/projects/stackblitz-starters-rvyx2s/my-app/.svelte-kit/tsconfig.json'

/home/projects/stackblitz-starters-rvyx2s/my-app/src/routes/sverdle/+page.svelte
  352:0  error  Parsing error: Cannot read file '/home/projects/stackblitz-starters-rvyx2s/my-app/.svelte-kit/tsconfig.json'

/home/projects/stackblitz-starters-rvyx2s/my-app/src/routes/sverdle/how-to-play/+page.svelte
  352:0  error  Parsing error: Cannot read file '/home/projects/stackblitz-starters-rvyx2s/my-app/.svelte-kit/tsconfig.json'

✖ 7 problems (7 errors, 0 warnings)
```

that `.svelte-kit` directory is super suspicious, like the CWD that eslint is running is incorrect.

but adding a `..` to the tsconfig.json resolve, (as expected) errors earlier:
```
❯ pnpm eslint .

Oops! Something went wrong! :(

ESLint: 8.55.0

Error: Cannot read config file: /home/projects/stackblitz-starters-rvyx2s/my-app/.eslintrc.cjs
Error: Cannot find module '/home/projects/stackblitz-starters-rvyx2s/tsconfig.json'
Require stack:
- /home/projects/stackblitz-starters-rvyx2s/my-app/.eslintrc.cjs
- /home/projects/stackblitz-starters-rvyx2s/my-app/node_modules/.pnpm/@eslint+eslintrc@2.1.4/node_modules/@eslint/eslintrc/dist/eslintrc.cjs
- /home/projects/stackblitz-starters-rvyx2s/my-app/node_modules/.pnpm/eslint@8.55.0/node_modules/eslint/lib/cli-engine/cli-engine.js
- /home/projects/stackblitz-starters-rvyx2s/my-app/node_modules/.pnpm/eslint@8.55.0/node_modules/eslint/lib/eslint/eslint.js
- /home/projects/stackblitz-starters-rvyx2s/my-app/node_modules/.pnpm/eslint@8.55.0/node_modules/eslint/lib/eslint/index.js
- /home/projects/stackblitz-starters-rvyx2s/my-app/node_modules/.pnpm/eslint@8.55.0/node_modules/eslint/lib/cli.js
- /home/projects/stackblitz-starters-rvyx2s/my-app/node_modules/.pnpm/eslint@8.55.0/node_modules/eslint/bin/eslint.js
    at InternalError (https://stackblitzstartersrvyx2s-lde3.w-corp.staticblitz.com/blitz.6843a59c.js:64:14767)
    at Module._resolveFilename (https://stackblitzstartersrvyx2s-lde3.w-corp.staticblitz.com/blitz.6843a59c.js:55:12642)
    at resolve (https://stackblitzstartersrvyx2s-lde3.w-corp.staticblitz.com/blitz.6843a59c.js:98:2256)
    at  (/home/projects/stackblitz-starters-rvyx2s/my-app/.eslintrc.cjs:30:26)
    at function (https://stackblitzstartersrvyx2s-lde3.w-corp.staticblitz.com/blitz.6843a59c.js:352:208332)
    at Module.prototype._compile (https://stackblitzstartersrvyx2s-lde3.w-corp.staticblitz.com/blitz.6843a59c.js:55:14871)
    at Module._extensions[".js"] (https://stackblitzstartersrvyx2s-lde3.w-corp.staticblitz.com/blitz.6843a59c.js:55:15550)
    at Module.prototype.load (https://stackblitzstartersrvyx2s-lde3.w-corp.staticblitz.com/blitz.6843a59c.js:55:13457)
    at Module._load (https://stackblitzstartersrvyx2s-lde3.w-corp.staticblitz.com/blitz.6843a59c.js:55:10535)
    at Module.prototype.require (https://stackblitzstartersrvyx2s-lde3.w-corp.staticblitz.com/blitz.6843a59c.js:55:13775)
    at module.exports (/home/projects/stackblitz-starters-rvyx2s/my-app/node_modules/.pnpm/import-fresh@3.3.0/node_modules/import-fresh/index.js:32:59)
    at loadJSConfigFile (/home/projects/stackblitz-starters-rvyx2s/my-app/node_modules/.pnpm/@eslint+eslintrc@2.1.4/node_modules/@eslint/eslintrc/dist/eslintrc.cjs:2583:37)
    at loadConfigFile (/home/projects/stackblitz-starters-rvyx2s/my-app/node_modules/.pnpm/@eslint+eslintrc@2.1.4/node_modules/@eslint/eslintrc/dist/eslintrc.cjs:2667:20)
    at loadInDirectory (/home/projects/stackblitz-starters-rvyx2s/my-app/node_modules/.pnpm/@eslint+eslintrc@2.1.4/node_modules/@eslint/eslintrc/dist/eslintrc.cjs:2877:34)
    at _loadConfigInAncestors (/home/projects/stackblitz-starters-rvyx2s/my-app/node_modules/.pnpm/@eslint+eslintrc@2.1.4/node_modules/@eslint/eslintrc/dist/eslintrc.cjs:3871:46)
    at getConfigArrayForFile (/home/projects/stackblitz-starters-rvyx2s/my-app/node_modules/.pnpm/@eslint+eslintrc@2.1.4/node_modules/@eslint/eslintrc/dist/eslintrc.cjs:3792:18)
    at _iterateFilesRecursive (/home/projects/stackblitz-starters-rvyx2s/my-app/node_modules/.pnpm/eslint@8.55.0/node_modules/eslint/lib/cli-engine/file-enumerator.js:450:49)
    at iterateFiles (/home/projects/stackblitz-starters-rvyx2s/my-app/node_modules/.pnpm/eslint@8.55.0/node_modules/eslint/lib/cli-engine/file-enumerator.js:299:13)
    at executeOnFiles (/home/projects/stackblitz-starters-rvyx2s/my-app/node_modules/.pnpm/eslint@8.55.0/node_modules/eslint/lib/cli-engine/cli-engine.js:797:9)
    at lintFiles (/home/projects/stackblitz-starters-rvyx2s/my-app/node_modules/.pnpm/eslint@8.55.0/node_modules/eslint/lib/eslint/eslint.js:551:23)
    at execute (/home/projects/stackblitz-starters-rvyx2s/my-app/node_modules/.pnpm/eslint@8.55.0/node_modules/eslint/lib/cli.js:402:36)
```

So... is something going goofy with the svelte eslint plugin?

**Comment by drewkht** [comment]
Type-aware rules work fine in SvelteKit once you have it configured correctly. Maybe you just didn't show every command you typed throughout the process, but I didn't see that you ran `pnpm dev` before attempting to run ESLint. SvelteKit auto generates that .svelte-kit folder the first time you start the server, which includes a tsconfig.json file that's supposed to be extended by the tsconfig in the project root.

Normally the tsconfig that's created by the new project CLI tool handles extending the generated tsconfig but I didn't see that happening in your tsconfig you pasted.

https://kit.svelte.dev/docs/project-structure#project-files-tsconfig-json

**Comment by drewkht** [comment]
Since v5.x.x (can't remember the exact version) TypeScript supports extending multiple tsconfigs at once. In my SvelteKit projects, from the tsconfig in the root project folder I extend both my own, custom tsconfig that's a package in my monorepo and the auto-generated tsconfig in the .svelte-kit folder and it works fine.

As far as your question about why use the .svelte-kit folder at all - that I can't really say. I'm not involved in the development of SvelteKit in any way, just a fairly experienced Svelte dev that saw your post on Reddit and thought I might know the answer.

I will say, though, that starting issues for problems that are (likely) easily solvable by having thoroughly read the docs (the .svelte-kit folder of auto-generated code is pretty fundamental to SvelteKit and isn't by any means an obscure feature) and then questioning core design decisions of the library as if that's the problem is a bit offputting from the perspective of someone trying to decide whether to devote some time to trying to help. 🤷‍♂️
