### ISSUE TITLE
SvelteKit 2: static build fails "env" is not exported by "virtual:$env/static/private", imported by "src/routes/+page.server.ts"

### ISSUE THREAD

**Issue by fayez-nazzal** [sveltejs/kit#11378]
### Describe the bug

I have a static website that contains this import statement:

```js
import { env } from '$env/static/private';
```

The build fails with the message :
`RollupError: "env" is not exported by "virtual:$env/static/private", imported by "src/routes/+page.server.ts".`

### Reproduction

To reproduce, add a `.env` file with you environment variables and add use this `+page.server.js` file:

```js
import { env } from "$env/static/private";

export const prerender = true;

export const load = () => {
  return {
    exampleEnv: env.EXAMPLE,
  };
};
```

Here is a [repro repo](https://github.com/fayez-nazzal/sveltekit-prerender-env-issue) containing the example code used.

Even the import statement used is highlighted in red:
![image](https://github.com/sveltejs/kit/assets/49946791/193c2931-40c0-462e-ad10-034415f25663)

### Logs

```Shell
Here is the full log:


✓ 85 modules transformed.
"env" is not exported by "virtual:$env/static/private", imported by "src/routes/+page.server.ts".
file: /home/fayez/sveltekit-prerender-env-issue/src/routes/+page.server.ts:1:9
1: import { env } from "$env/static/private";
            ^
2: 
3: export const prerender = true;
error during build:
RollupError: "env" is not exported by "virtual:$env/static/private", imported by "src/routes/+page.server.ts".
    at error (file:///home/fayez/sveltekit-prerender-env-issue/node_modules/.pnpm/rollup@4.9.1/node_modules/rollup/dist/es/shared/parseAst.js:337:30)
    at Module.error (file:///home/fayez/sveltekit-prerender-env-issue/node_modules/.pnpm/rollup@4.9.1/node_modules/rollup/dist/es/shared/node-entry.js:12755:16)
    at Module.traceVariable (file:///home/fayez/sveltekit-prerender-env-issue/node_modules/.pnpm/rollup@4.9.1/node_modules/rollup/dist/es/shared/node-entry.js:13192:29)
    at ModuleScope.findVariable (file:///home/fayez/sveltekit-prerender-env-issue/node_modules/.pnpm/rollup@4.9.1/node_modules/rollup/dist/es/shared/node-entry.js:11609:39)
    at ReturnValueScope.findVariable (file:///home/fayez/sveltekit-prerender-env-issue/node_modules/.pnpm/rollup@4.9.1/node_modules/rollup/dist/es/shared/node-entry.js:5911:38)
    at FunctionBodyScope.findVariable (file:///home/fayez/sveltekit-prerender-env-issue/node_modules/.pnpm/rollup@4.9.1/node_modules/rollup/dist/es/shared/node-entry.js:5911:38)
    at MemberExpression.bind (file:///home/fayez/sveltekit-prerender-env-issue/node_modules/.pnpm/rollup@4.9.1/node_modules/rollup/dist/es/shared/node-entry.js:8471:49)
    at Property.bind (file:///home/fayez/sveltekit-prerender-env-issue/node_modules/.pnpm/rollup@4.9.1/node_modules/rollup/dist/es/shared/node-entry.js:4639:23)
    at ObjectExpression.bind (file:///home/fayez/sveltekit-prerender-env-issue/node_modules/.pnpm/rollup@4.9.1/node_modules/rollup/dist/es/shared/node-entry.js:4635:28)
    at ReturnStatement.bind (file:///home/fayez/sveltekit-prerender-env-issue/node_modules/.pnpm/rollup@4.9.1/node_modules/rollup/dist/es/shared/node-entry.js:4639:23)
 ELIFECYCLE  Command failed with exit code 1.
```
```


### System Info

```Shell
System:
    OS: Linux 6.1 EndeavourOS
    CPU: (8) x64 11th Gen Intel(R) Core(TM) i7-1195G7 @ 2.90GHz
    Memory: 5.37 GB / 15.33 GB
    Container: Yes
    Shell: 5.9 - /usr/bin/zsh
  Binaries:
    Node: 18.19.0 - /run/user/1000/fnm_multishells/22872_1702877718005/bin/node
    npm: 10.2.3 - /run/user/1000/fnm_multishells/22872_1702877718005/bin/npm
    pnpm: 8.12.1 - /run/user/1000/fnm_multishells/22872_1702877718005/bin/pnpm
  npmPackages:
    @sveltejs/adapter-auto: ^3.0.0 => 3.0.0 
    @sveltejs/kit: ^2.0.0 => 2.0.2 
    @sveltejs/vite-plugin-svelte: ^3.0.0 => 3.0.1 
    svelte: ^4.2.7 => 4.2.8 
    vite: ^5.0.3 => 5.0.10 

Using `pnpm` and `Node 18`, I also reproduced this issue using `npm` and `Node 20`.
```

### Severity

blocking an upgrade

**Comment by CaptainCodeman** [comment]
You should import the name of the env variable

**Comment by 524c** [comment]
What should we do now in an CI in Sveltekit 2?

My Drone CI build does not have any environment variables or static .env in the repository. The environment variables on my system are passed in the k8s deployment.
