### ISSUE TITLE
@sveltejs/enhanced-img doesn't work on GitHub Actions

### ISSUE THREAD

**Issue by dmotz** [sveltejs/kit#11528]
### Describe the bug

When building a SvelteKit project using `@sveltejs/enhanced-img` on GitHub, the build logs show the following message:

`@sveltejs/enhanced-img: vite-imagetools is not installed. Skipping build-time optimizations`

This results in images not being transformed and thus missing in the build output.

I've tried adding `vite-imagetools` as a direct dependency with no luck. I've also been sure to keep the lockfile in sync with package.json.

### Reproduction

To reproduce, build a SvelteKit project using `@sveltejs/enhanced-img` with GitHub Actions.

Here are my config files:

[package.json](https://github.com/dmotz/dmotz.github.com/blob/master/package.json)

[deploy.yml](https://github.com/dmotz/dmotz.github.com/blob/master/.github/workflows/deploy.yml)

### Logs

```Shell
> vite build

@sveltejs/enhanced-img: vite-imagetools is not installed. Skipping build-time optimizations
vite v5.0.11 building SSR bundle for production...
transforming...
✓ 94 modules transformed.
rendering chunks...
@sveltejs/enhanced-img: vite-imagetools is not installed. Skipping build-time optimizations
vite v5.0.11 building for production...
transforming...
✓ 85 modules transformed.
```

### System Info

```Shell
System:
    OS: Linux 6.2 Ubuntu 22.04.3 LTS 22.04.3 LTS (Jammy Jellyfish)
    CPU: (4) x64 AMD EPYC 7763 64-Core Processor
    Memory: 14.61 GB / 15.61 GB
    Container: Yes
    Shell: 5.1.16 - /bin/bash
  Binaries:
    Node: 20.10.0 - /opt/hostedtoolcache/node/20.10.0/x64/bin/node
    Yarn: 1.22.21 - /usr/local/bin/yarn
    npm: 10.2.3 - /opt/hostedtoolcache/node/20.10.0/x64/bin/npm
  Browsers:
    Chrome: 120.0.6099.109
    Chromium: 120.0.6099.0
  npmPackages:
    @sveltejs/adapter-auto: ^3.1.0 => 3.1.0 
    @sveltejs/adapter-static: ^3.0.1 => 3.0.1 
    @sveltejs/enhanced-img: ^0.1.7 => 0.1.7 
    @sveltejs/kit: ^2.0.6 => 2.0.6 
    svelte: ^4.0.0 => 4.2.8 
    vite: ^5.0.5 => 5.0.11
```

### Severity

serious, but I can work around it

**Comment by dmotz** [comment]
Thanks for taking a look. 

Here's what it reports with 0.1.8:

```
error during build:
Error [ERR_MODULE_NOT_FOUND]: Cannot find package 'sharp' imported from /home/runner/work/dmotz.github.com/dmotz.github.com/node_modules/vite-imagetools/dist/index.js
    at packageResolve (node:internal/modules/esm/resolve:844:9)
    at moduleResolve (node:internal/modules/esm/resolve:901:20)
    at defaultResolve (node:internal/modules/esm/resolve:1121:11)
    at ModuleLoader.defaultResolve (node:internal/modules/esm/loader:396:12)
    at ModuleLoader.resolve (node:internal/modules/esm/loader:[36](https://github.com/dmotz/dmotz.github.com/actions/runs/7496076143/job/20407431678#step:5:37)5:25)
    at ModuleLoader.getModuleJob (node:internal/modules/esm/loader:240:[38](https://github.com/dmotz/dmotz.github.com/actions/runs/7496076143/job/20407431678#step:5:39))
    at ModuleWrap.<anonymous> (node:internal/modules/esm/module_job:85:[39](https://github.com/dmotz/dmotz.github.com/actions/runs/7496076143/job/20407431678#step:5:40))
    at link (node:internal/modules/esm/module_job:84:36)
Error: Process completed with exit code 1.
```

Adding `sharp` as a root dependency gives this error:

```
error during build:
Error: Could not load the "sharp" module using the linux-x64 runtime
Possible solutions:
- Ensure optional dependencies can be installed:
    npm install --include=optional sharp
    yarn add sharp --ignore-engines
- Ensure your package manager supports multi-platform installation:
    See https://sharp.pixelplumbing.com/install#cross-platform
- Add platform-specific dependencies:
    npm install --os=linux --cpu=x64 sharp
    npm install --force @img/sharp-linux-x64
- Consult the installation documentation:
    See https://sharp.pixelplumbing.com/install
    at Object.<anonymous> (/home/runner/work/dmotz.github.com/dmotz.github.com/node_modules/imagetools-core/node_modules/sharp/lib/sharp.js:107:9)
    at Module._compile (node:internal/modules/cjs/loader:1376:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1435:10)
    at Module.load (node:internal/modules/cjs/loader:1207:32)
    at Module._load (node:internal/modules/cjs/loader:1023:12)
    at Module.require (node:internal/modules/cjs/loader:1235:19)
    at require (node:internal/modules/helpers:176:18)
    at Object.<anonymous> (/home/runner/work/dmotz.github.com/dmotz.github.com/node_modules/imagetools-core/node_modules/sharp/lib/constructor.js:10:1)
    at Module._compile (node:internal/modules/cjs/loader:1376:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1435:10)
Error: Process completed with exit code 1.
```

I pinned and set an override for `sharp@0.32.6` per https://github.com/lovell/sharp/issues/3870 but no luck.

**Comment by konstantinblaesi** [comment]
In my fedora 39 wsl2 instance I got this error as well
> Could not load the "sharp" module using the linux-x64 runtime
After trying the suggested commands (none worked) I think it was
> npm install --force @img/sharp-linux-x64
that got me on the right track. It's [package.json](url) had a conflict with my npm version

```json
 "engines": {
    "node": "^18.17.0 || ^20.3.0 || >=21.0.0",
    "npm": ">=9.6.5",
    "yarn": ">=3.2.0",
    "pnpm": ">=7.1.0",
    "glibc": ">=2.26"
  },
```
For some reason I had an outdated npm@9.6.3 in /usr/local/bin which was picked over my (up to date) /usr/bin/npm@10.5.0. After using the latter npm version the error went away. What's annoying is that `npm install` with npm@9.6.3 didn't report any issues, but it looks like the linux x64 sharp build was never installed.

**Comment by jasongitmail** [comment]
I also encounter Github Actions CI errors due to `enhanced:img` as well.  This same SvelteKit app that uses `enhanced:img` works locally (macOS) and works when deployed to Cloudflare Pages. 

Both `bun install` or `npm install` encounter issues on Github Actions CI, as if darwin-based versions of packages are somehow already present, but `node_modules` is _not_ committed to my repo.

I got past a couple errors by installing optional deps like this, but more and more errors are encountered:

```yml
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: Update npm to latest # aims to fix sveltejs/kit#11528
        run: npm install -g npm@latest
      - run: npm install @rollup/rollup-linux-x64-gnu --save-optional # fixed one error
      - run: npm install @cloudflare/workerd-linux-64 --save-optional # did not solve the related error
```
Errors:
```
npm ERR! Error while trying to sync SvelteKit config
npm ERR! Error: 
npm ERR! You installed workerd on another platform than the one you're currently using.
npm ERR! This won't work because workerd is written with native code and needs to
npm ERR! install a platform-specific binary executable.
npm ERR! 
npm ERR! Specifically the "@cloudflare/workerd-darwin-arm64" package is present but this platform
npm ERR! needs the "@cloudflare/workerd-linux-64" package instead. People often get into this
npm ERR! situation by installing workerd on macOS and copying "node_modules"
npm ERR! into a Docker image that runs Linux.
npm ERR! 
npm ERR! If you are installing with npm, you can try not copying the "node_modules"
npm ERR! directory when you copy the files over, and running "npm ci" or "npm install"
npm ERR! on the destination platform after the copy. Or you could consider using yarn
npm ERR! instead which has built-in support for installing a package on multiple
npm ERR! platforms simultaneously.
```

Versions:
```js
// package.json versions
"@sveltejs/enhanced-img": "^0.1.9",
"@sveltejs/adapter-cloudflare": "^4.2.0",
 "@sveltejs/kit": "^2.5.4",
```

Github Actions CI is on `runs-on: ubuntu-latest`

I tried "@sveltejs/enhanced-img" within `devDependencies` and `depencies` with the same result, both encounter errors.

**Comment by dmotz** [comment]
The root of this issue seems to be entirely caused by https://github.com/npm/cli/issues/4828.

In my [`deploy.yml`](https://github.com/dmotz/dmotz.github.com/blob/master/.github/workflows/deploy.yml#L21), I simply install the linux-x64 packages manually before the main install and the problem is resolved:

```yaml
- name: install dependencies
  run: |
    npm i @rollup/rollup-linux-x64-gnu
    npm i --cpu=x64 --os=linux sharp
    npm i
```

(Rollup was needed too for SvelteKit).

Closing this issue as it's really an npm bug.

**Comment by INTROX-AI** [comment]
Can you refer what is actually causing the issue more detailed
