### ISSUE TITLE
Cannot read property 'error' of undefined after 1.0.0-next.71

### ISSUE THREAD

**Issue by mhatvan** [sveltejs/kit#1157]
**Describe the bug**

**Logs**
```
TypeError: Cannot read property 'error' of undefined
    at normalize (file:///home/markus/Applications/Webdevelopment/markushatvan.com/node_modules/.pnpm/@sveltejs+kit@1.0.0-next.72_5a1e6f1b68430d6010b8aaf3f0fc8ed0/node_modules/@sveltejs/kit/dist/ssr.js:2192:13)
    at load_node (file:///home/markus/Applications/Webdevelopment/markushatvan.com/node_modules/.pnpm/@sveltejs+kit@1.0.0-next.72_5a1e6f1b68430d6010b8aaf3f0fc8ed0/node_modules/@sveltejs/kit/dist/ssr.js:2451:11)
    at async respond_with_error (file:///home/markus/Applications/Webdevelopment/markushatvan.com/node_modules/.pnpm/@sveltejs+kit@1.0.0-next.72_5a1e6f1b68430d6010b8aaf3f0fc8ed0/node_modules/@sveltejs/kit/dist/ssr.js:2525:3)
    at async respond (file:///home/markus/Applications/Webdevelopment/markushatvan.com/node_modules/.pnpm/@sveltejs+kit@1.0.0-next.72_5a1e6f1b68430d6010b8aaf3f0fc8ed0/node_modules/@sveltejs/kit/dist/ssr.js:2673:12)
    at async render_page (file:///home/markus/Applications/Webdevelopment/markushatvan.com/node_modules/.pnpm/@sveltejs+kit@1.0.0-next.72_5a1e6f1b68430d6010b8aaf3f0fc8ed0/node_modules/@sveltejs/kit/dist/ssr.js:2735:20)
    at async file:///home/markus/Applications/Webdevelopment/markushatvan.com/node_modules/.pnpm/@sveltejs+kit@1.0.0-next.72_5a1e6f1b68430d6010b8aaf3f0fc8ed0/node_modules/@sveltejs/kit/dist/ssr.js:2862:10
    at async ssr (file:///home/markus/Applications/Webdevelopment/markushatvan.com/node_modules/.pnpm/@sveltejs+kit@1.0.0-next.72_5a1e6f1b68430d6010b8aaf3f0fc8ed0/node_modules/@sveltejs/kit/dist/ssr.js:2849:10)
    at async Immediate.<anonymous> (file:///home/markus/Applications/Webdevelopment/markushatvan.com/node_modules/.pnpm/@sveltejs+kit@1.0.0-next.72_5a1e6f1b68430d6010b8aaf3f0fc8ed0/node_modules/@sveltejs/kit/dist/chunks/index2.js:3302:23)

```

**To Reproduce**

You can see it happening in here: https://github.com/mhatvan/markushatvan.com

If you bump up the version to anything higher than 71, you should be greeted with `TypeError: Cannot read property 'error' of undefined` for the `dev` and `build:prod` scripts once opening the browser.

Initially I thought it might have to do with switching from yarn to pnpm, but it fails on both.

**Expected behavior**
Development and production bundle to work.

**Information about your SvelteKit Installation:**

<details>
  <summary>Diagnostics</summary>

- Your browser: Brave Browser: 90.1.23.71

- Your adapter (e.g. Node, static, Vercel, Begin, etc...): @sveltejs/adapter-static
</details>

**Severity**
How severe an issue is this bug to you? Is this annoying, blocking some users, blocking an upgrade or blocking your usage of SvelteKit entirely?

It blocks me entirely from upgrading, since I can't develop or deploy.

**Comment by Conduitry** [comment]
Do you have a small repro? There have been many intentional breaking changes during pre-release of SvelteKit, and a crash when you upgrade does not necessarily indicate that there's a new bug.

https://github.com/mhatvan/markushatvan.com/blob/master/src/routes/%24error.svelte One thing I did notice is that your error page needs updating, as they no longer receive `error`/`status` as props - https://kit.svelte.dev/docs#layouts-error-pages

**Comment by GrygrFlzr** [comment]
This was fixed long ago for the default `$error.svelte` in `1.0.0-next.75`, you are on `1.0.0-next.71`, and the latest is `1.0.0-next.84` as per your pnpm lockfile.

In addition, the error page no longer receives the `status` and `error` props by default, you have to modify your `$error.svelte` to pass it in from `load`:

```svelte
<script context="module">
	export function load({ error, status }) {
		return {
			props: { error, status }
		};
	}
</script>
```

Closing given the currently available information. If you can still reproduce this issue after updating your kit version and your `$error.svelte`, we can re-open the issue.

**Comment by mhatvan** [comment]
My bad, I wrote this ticket in a hurry!

I actually upgraded locally to check with which version it breaks. Now I pushed a branch that has the latest dependencies and also uses the Sveltekit way of writing `$error.svelte`. Unfortunately it still breaks and the stack trace doesn't give an indication of what the cause could be.

https://github.com/mhatvan/markushatvan.com/tree/general-maintenance

**Comment by mhatvan** [comment]
@GrygrFlzr @Conduitry
 
I figured out the root cause of the issue:

This load function doesn't return anything (equal to `return undefined`), because I am generating Sitemap and RSS feed without the need to return data to the component.
```js
<script context="module">
  export async function load({ fetch }: LoadInput) {
    try {
      await fetch('/sitemap.xml');
      await fetch('/rss.xml');

    } catch (error) {
      console.error(error);
    }
  }
</script>
```

I simply added `return true` at the end of the try block and it works again.

Imo the error stack trace should point to this code, instead of throwing unspecific `error of undefined` within the SvelteKit code.
And probably the code should not break without a return too.
