### ISSUE TITLE
SvelteKit does not apply BaseUrl

### ISSUE THREAD

**Issue by Slyke** [sveltejs/kit#11741]
### Describe the bug

Using SvelteKit behind a reverse proxy doesn't seem to work if it is hosted under a subdirectory.

### Reproduction

1. Create a new SvelteKit project.
2. Setup base directory in Vite and Svelte configs:
`vite.config.js`:
```
import { sveltekit } from '@sveltejs/kit/vite';
import { defineConfig } from 'vitest/config';

const baseDir = process.env.BASE_URL || '/subdir-ui/';

export default defineConfig(({ command, mode, isSsrBuild, isPreview }) => {
  const config = {
    plugins: [sveltekit()],
    test: {
      include: ['src/**/*.{test,spec}.{js,ts}']
    },
    base: baseDir,
    
  };

  console.log('ViteConfig: ', { command, mode, isSsrBuild, isPreview, config });

  return config;
});
```

`svelte.config.js`:
```
import adapter from '@sveltejs/adapter-auto';
import { vitePreprocess } from '@sveltejs/vite-plugin-svelte';

const baseDir = process.env.BASE_URL || '/subdir-ui/';

/** @type {import('@sveltejs/kit').Config} */
const config = {
	preprocess: vitePreprocess(),
  kit: {
    adapter: adapter({
      fallback: 'index.html',
    }),
    paths: {
      base: baseDir
    }
  }
};

export default config;
```

3. Run `npm install && npm run dev`.

My nginx proxy setup:
```
  location ~ ^/subdir-ui(/|$) {
    add_header Access-Control-Allow-Origin *;
    add_header Access-Control-Allow-Methods "POST, GET, PATCH, DELETE, PUT, OPTIONS";
    add_header Access-Control-Allow-Headers "Origin, Authorization, Accept";
    add_header Access-Control-Allow-Credentials true;
    rewrite ^/subdir-ui/(.*) /$1 break;
    proxy_pass "http://local.mockup.sveltekit_ui:5173";
  }
```

### Logs

```Shell
sveltekit_ui  | ViteConfig:  {
sveltekit_ui  |   command: 'serve',
sveltekit_ui  |   mode: 'development',
sveltekit_ui  |   isSsrBuild: false,
sveltekit_ui  |   isPreview: false,
sveltekit_ui  |   config: {
sveltekit_ui  |     plugins: [ [Promise] ],
sveltekit_ui  |     test: { include: [Array] },
sveltekit_ui  |     base: '/subdir-ui/'
sveltekit_ui  |   }
sveltekit_ui  | }
sveltekit_ui  | The following Vite config options will be overridden by SvelteKit:
sveltekit_ui  |   - base
sveltekit_ui  | Forced re-optimization of dependencies
sveltekit_ui  |
sveltekit_ui  |   VITE v5.0.12  ready in 704 ms
sveltekit_ui  |
sveltekit_ui  |   ➜  Local:   http://localhost:5173/
sveltekit_ui  |   ➜  Network: http://172.23.0.7:5173/
sveltekit_ui  | SvelteKitError: Not found: /subdir-ui
sveltekit_ui  |     at resolve (/usr/svelte_ui/node_modules/@sveltejs/kit/src/runtime/server/respond.js:522:13)
sveltekit_ui  |     at resolve (/usr/svelte_ui/node_modules/@sveltejs/kit/src/runtime/server/respond.js:322:5)
sveltekit_ui  |     at #options.hooks.handle (/usr/svelte_ui/node_modules/@sveltejs/kit/src/runtime/server/index.js:71:56)
sveltekit_ui  |     at Module.respond (/usr/svelte_ui/node_modules/@sveltejs/kit/src/runtime/server/respond.js:319:40) {
sveltekit_ui  |   status: 404,
sveltekit_ui  |   text: 'Not Found'
sveltekit_ui  | }
nginx-revprox     | 172.23.0.1 - - [26/Jan/2024:06:19:54 +0000] "GET /subdir-ui HTTP/1.1" 404 941 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36" "-"
nginx-revprox     | 172.23.0.1 - - [26/Jan/2024:06:19:54 +0000] "GET /node_modules/@sveltejs/kit/src/runtime/client/entry.js HTTP/1.1" 200 590 "http://localhost:4080/subdir-ui" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36" "-"
nginx-revprox     | 172.23.0.1 - - [26/Jan/2024:06:19:54 +0000] "GET /@fs/usr/svelte_ui/.svelte-kit/generated/client/app.js HTTP/1.1" 200 601 "http://localhost:4080/subdir-ui" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36" "-"
nginx-revprox     | 172.23.0.1 - - [26/Jan/2024:06:19:54 +0000] "GET /favicon.png HTTP/1.1" 200 547 "http://localhost:4080/subdir-ui" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36" "-"
```
```


### System Info

```Shell
$ npx envinfo --system --binaries --browsers --npmPackages "{svelte,@sveltejs/*,vite}"
Need to install the following packages:
envinfo@7.11.0
Ok to proceed? (y) y

  System:
    OS: Linux 5.15 Ubuntu 20.04.3 LTS (Focal Fossa)
    CPU: (24) x64 AMD Ryzen 9 5900X 12-Core Processor
    Memory: 27.48 GB / 31.30 GB
    Container: Yes
    Shell: 5.0.17 - /bin/bash
  Binaries:
    Node: 20.11.0 - ~/.nvm/versions/node/v20.11.0/bin/node
    npm: 10.2.4 - ~/.nvm/versions/node/v20.11.0/bin/npm
```

### Severity

serious, but I can work around it

### Additional Information

Messing around with it, I can get assets to load with the correct prefixed URL, but `entry.js` and `app.js` always default to the domain level and never contain `subdir-ui` or whatever the BaseUrl is set to.

I tried the exact same setup with just Svelte and it works just fine.

**Comment by Slyke** [comment]
Found a solution:
Use adapter-node:
```
import adapter from '@sveltejs/adapter-node';
import { vitePreprocess } from '@sveltejs/vite-plugin-svelte';

const baseDir = process.env.BASE_URL || '/subdir-ui';

/** @type {import('@sveltejs/kit').Config} */
const config = {
  preprocess: vitePreprocess(),
  kit: {
    adapter: adapter({
      out: 'build',
      precompress: false,
      envPrefix: ''
    }),
    paths: {
      base: baseDir
    }
  }
};

export default config;
```

Remove URL rewrite rule from nginx:
```
# rewrite ^/subdir-ui/(.*) /$1 break; # <-- Remove this.
```
