### ISSUE TITLE
`adapter-node` does not serve filenames that end with `+`

### ISSUE THREAD

**Issue by hyunbinseo** [sveltejs/kit#11766]
### Describe the bug

```
static/academic-cap+.svg
static/academic-cap.svg
```

```html
<img src="/academic-cap+.svg">
<img src="/academic-cap.svg">
```

Served in `vite dev`

Former is not served in `vite preview` and `node build`

### Reproduction

https://stackblitz.com/edit/github-ilcgem?file=src%2Froutes%2F%2Bpage.svelte

```shell
npm run dev # works
npm run build
npm run preview # does not work
node build # does not work
```

### Logs

```Shell
SvelteKitError: Not found: /academic-cap+.svg
    at new SvelteKitError (/home/projects/github-ilcgem/build/server/index.js:1408:5)
    at resolve2 (/home/projects/github-ilcgem/build/server/index.js:4206:18)
    at resolve (/home/projects/github-ilcgem/build/server/index.js:4038:34)
    at #options.hooks.handle (/home/projects/github-ilcgem/build/server/index.js:4271:71)
    at respond (/home/projects/github-ilcgem/build/server/index.js:4036:43) {
  status: 404,
  text: 'Not Found'
}
```

### System Info

```Shell
System:
  OS: Linux 5.0 undefined
  CPU: (8) x64 Intel(R) Core(TM) i9-9880H CPU @ 2.30GHz
  Memory: 0 Bytes / 0 Bytes
  Shell: 1.0 - /bin/jsh
Binaries:
  Node: 18.18.0 - /usr/local/bin/node
  Yarn: 1.22.19 - /usr/local/bin/yarn
  npm: 10.2.3 - /usr/local/bin/npm
  pnpm: 8.14.0 - /usr/local/bin/pnpm
npmPackages:
  @sveltejs/adapter-node: ^4.0.1 => 4.0.1 
  @sveltejs/kit: ^2.3.3 => 2.5.0 
  @sveltejs/vite-plugin-svelte: ^3.0.1 => 3.0.2 
  svelte: ^4.2.8 => 4.2.9 
  vite: ^5.0.11 => 5.0.12
```

### Severity

serious, but I can work around it

**Comment by hyunbinseo** [comment]
This is a [sirv](https://github.com/lukeed/sirv/tree/master/packages/sirv) package issue.

Reproducible using the [example] provided in the Polka repository.

[example]: https://github.com/lukeed/polka/tree/main/examples/with-sirv

```
workspace
 ┣ public
 ┃ ┣ a+.txt - 404 Not Found
 ┃ ┗ a.txt -- Served
 ┣ index.js
 ┣ package.json
 ┗ pnpm-lock.yaml
```

```js
// index.js
const polka = require('polka');

const { PORT = 3000 } = process.env;
const serve = require('sirv')('public');

polka()
  .use(serve)
  .get('/health', (req, res) => {
    res.end('OK');
  })
  .listen(PORT, () => {
    console.log(`> Running on localhost:${PORT}`);
  });
```

**Comment by hyunbinseo** [comment]
Reference https://github.com/lukeed/sirv/issues/159
