### ISSUE TITLE
ERR_SVELTE_HYDRATION_MISMATCH with Svelte ^5.0.0-next.62

### ISSUE THREAD

**Issue by l1qu1d** [sveltejs/kit#11878]
### Describe the bug

Using Svelte `5.0.0-next.62` in Sveltekit causes `ERR_SVELTE_HYDRATION_MISMATCH` in fresh project.

### Reproduction

Create a new Sveltekit app and select the Svelte 5 preview.

- `npm create svelte@latest my-app`
- `Select Svelte 5 preview`
- `cd my-app`
- `npm install`
- `npm run dev`

### Logs

```Shell
ERR_SVELTE_HYDRATION_MISMATCH: Hydration failed because the initial UI does not match what was rendered on the server. TypeError: Cannot read properties of undefined (reading 'filename')
    at check_ownership (ownership.js:141:13)
    at Object.set (proxy.js:270:4)
    at root.svelte:45:67
    at render.js:1329:18
    at untrack (runtime.js:1384:10)
    at render.js:1329:4
    at execute_signal_fn (runtime.js:358:6)
    at execute_effect (runtime.js:536:29)
    at schedule_effect (runtime.js:632:4)
    at internal_create_effect (runtime.js:1409:3)


Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'filename')
    at check_ownership (ownership.js:141:13)
    at Object.set (proxy.js:270:4)
    at root.svelte:45:67
    at render.js:1329:18
    at untrack (runtime.js:1384:10)
    at render.js:1329:4
    at execute_signal_fn (runtime.js:358:6)
    at execute_effect (runtime.js:536:29)
    at schedule_effect (runtime.js:632:4)
    at internal_create_effect (runtime.js:1409:3)
```

### System Info

```Shell
system:
    OS: Windows 11 10.0.22631
    CPU: (16) x64 AMD Ryzen 7 7840U w/ Radeon  780M Graphics
    Memory: 3.36 GB / 15.19 GB
  Binaries:
    Node: 20.11.1 - C:\Program Files\nodejs\node.EXE
    npm: 10.4.0 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Edge: Chromium (121.0.2277.128), ChromiumDev (123.0.2400.1)
    Internet Explorer: 11.0.22621.1
  npmPackages:
    @sveltejs/adapter-auto: ^3.0.0 => 3.1.1
    @sveltejs/kit: ^2.0.0 => 2.5.0
    @sveltejs/vite-plugin-svelte: ^3.0.0 => 3.0.2
    svelte: ^5.0.0-next.1 => 5.0.0-next.62
    vite: ^5.0.3 => 5.1.3
```

### Severity

blocking an upgrade

**Comment by Rich-Harris** [comment]
Fixed by https://github.com/sveltejs/svelte/pull/10577 — thanks
