### ISSUE TITLE
request.json() throws unexpected "SyntaxError: Unexpected end of JSON input" error in +server.ts

### ISSUE THREAD

**Issue by techboy-coder** [sveltejs/kit#12004]
### Describe the bug

I'm trying to get a simple `GET` handler to work in my `+server.ts` file. The problem is that regardless of if I do pass a body, I don't pass on a body or pass on an empty body, my code throws an error. I've added checks which are supposed to check for empty requests and bodies.

```bash
> curl http://localhost:5173/api
{"message":"Internal Error"}
```

The problem stays with an empty body:

```bash
> curl --request GET \
  --url http://localhost:5173/api \ 
  --header 'Content-Type: application/json' \
  --data '{
  
}'
{"message":"Internal Error"}
```

And the problem also stays with an existent body:

```bash
> curl --request GET \
  --url http://localhost:5173/api \
  --header 'Content-Type: application/json' \
  --data '{
  "hello": "world"
}'
{"message":"Internal Error"}
```

### Reproduction

Example code:
```typescript
// +server.ts (/api)
import { json } from "@sveltejs/kit";
import type { RequestHandler } from "./$types";

export const GET: RequestHandler = async ({ request }) => {
    if (!request) return json({ msg: "no request" })
    let body = await request.json();
    if (body) {
        return json({ msg: "body found", body })
    }
    return json({ msg: "no body found" })
};

```

### Logs

```Shell
Error:

SyntaxError: Unexpected end of JSON input
    at JSON.parse (<anonymous>)
    at parseJSONFromBytes (node:internal/deps/undici/undici:4747:19)
    at successSteps (node:internal/deps/undici/undici:4718:27)
    at specConsumeBody (node:internal/deps/undici/undici:4724:9)
    at _Request.json (node:internal/deps/undici/undici:4614:18)
    at GET (/home/shividotio/Projects/Praktikum/Example/example/webapp/src/routes/api/+server.ts:6:30)
    at Module.render_endpoint (/home/shividotio/Projects/Praktikum/Example/example/webapp/node_modules/@sveltejs/kit/src/runtime/server/endpoint.js:43:24)
    at resolve (/home/shividotio/Projects/Praktikum/Example/example/webapp/node_modules/@sveltejs/kit/src/runtime/server/respond.js:443:23)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async Module.respond (/home/shividotio/Projects/Praktikum/Example/example/webapp/node_modules/@sveltejs/kit/src/runtime/server/respond.js:319:20)
```

### System Info

```Shell
System:
    OS: Linux 6.7 Fedora Linux 39 (Workstation Edition)
    CPU: (8) x64 11th Gen Intel(R) Core(TM) i7-1165G7 @ 2.80GHz
    Memory: 21.80 GB / 31.07 GB
    Container: Yes
    Shell: 5.9 - /usr/bin/zsh
  Binaries:
    Node: 20.10.0 - /usr/bin/node
    npm: 10.2.3 - /usr/bin/npm
    bun: 1.0.28 - ~/.bun/bin/bun


My package.json

{
  "name": "webapp",
  "version": "0.0.1",
  "private": true,
  "scripts": {
    "dev": "vite dev",
    "build": "vite build",
    "preview": "vite preview",
    "check": "svelte-kit sync && svelte-check --tsconfig ./tsconfig.json",
    "check:watch": "svelte-kit sync && svelte-check --tsconfig ./tsconfig.json --watch",
    "lint": "prettier --check . && eslint .",
    "format": "prettier --write .",
    "generate": "bun drizzle-kit generate:pg",
    "migrate": "bun ./src/db/migrate.ts"
  },
  "devDependencies": {
    "@sveltejs/adapter-auto": "^3.0.0",
    "@sveltejs/kit": "^2.0.0",
    "@sveltejs/vite-plugin-svelte": "^3.0.0",
    "@tailwindcss/typography": "^0.5.10",
    "@types/eslint": "8.56.0",
    "@typescript-eslint/eslint-plugin": "^6.0.0",
    "@typescript-eslint/parser": "^6.0.0",
    "autoprefixer": "^10.4.16",
    "drizzle-kit": "^0.20.14",
    "eslint": "^8.56.0",
    "eslint-config-prettier": "^9.1.0",
    "eslint-plugin-svelte": "^2.35.1",
    "postcss": "^8.4.32",
    "postcss-load-config": "^5.0.2",
    "prettier": "^3.1.1",
    "prettier-plugin-svelte": "^3.1.2",
    "prettier-plugin-tailwindcss": "^0.5.9",
    "svelte": "^4.2.7",
    "svelte-check": "^3.6.0",
    "tailwindcss": "^3.3.6",
    "tslib": "^2.4.1",
    "typescript": "^5.0.0",
    "vite": "^5.0.3"
  },
  "type": "module",
  "dependencies": {
    "@rich_harris/svelte-split-pane": "^1.1.1",
    "@types/underscore": "^1.11.15",
    "bits-ui": "^0.18.6",
    "clsx": "^2.1.0",
    "cmdk-sv": "^0.0.13",
    "dotenv": "^16.4.5",
    "drizzle-orm": "^0.29.3",
    "drizzle-zod": "^0.5.1",
    "formsnap": "^0.5.1",
    "graphql": "^16.8.1",
    "graphql-request": "^6.1.0",
    "immutable": "^5.0.0-beta.5",
    "lucide-svelte": "^0.335.0",
    "mode-watcher": "^0.2.1",
    "nanoid": "^5.0.6",
    "paneforge": "^0.0.2",
    "postgres": "^3.4.3",
    "snarkdown": "^2.0.0",
    "svelte-radix": "^1.0.1",
    "svelte-sonner": "^0.3.18",
    "sveltekit-superforms": "^2.9.0",
    "tailwind-merge": "^2.2.1",
    "tailwind-variants": "^0.2.0",
    "tinygradient": "^1.1.5",
    "underscore": "^1.13.6",
    "zod": "^3.22.4"
  }
}
```

### Severity

blocking an upgrade

### Additional Information

I'm using `bun run dev` (should not be the problem...)

**Comment by Conduitry** [comment]
GET requests shouldn't have a body. I imagine it's getting dropped at some point before your handler is getting called.

The `event.request` object also always exists regardless of whether there was a body associated with the request, so checking for `event.request` is not actually checking for anything useful.

`event.request.json()` will throw an error if the request body isn't in JSON form - which includes if it's an empty request body. It won't return a nullish value if there's no body.
