### ISSUE TITLE
adapter-cloudflare 4.2.0 broke waitUntil use inside hooks.server.ts (with prerendering)

### ISSUE THREAD

**Issue by maemigh** [sveltejs/kit#12003]
### Describe the bug

Using adapter-cloudflare 4.1.0, `npm run build` works fine. Upgrading to 4.2.0 causes `npm run build` to fail with:

```
✓ built in 3.21s
TypeError: Cannot read properties of undefined (reading 'waitUntil')

/Users/maemigh/arcana-website/node_modules/wrangler/wrangler-dist/cli.js:29573
            throw a;
            ^
Error: 500 /about
To suppress or handle this error, implement `handleHttpError` in https://kit.svelte.dev/docs/configuration#prerender
    at file:///Users/maemigh/arcana-website/node_modules/@sveltejs/kit/src/core/config/options.js:202:13
    at file:///Users/maemigh/arcana-website/node_modules/@sveltejs/kit/src/core/postbuild/prerender.js:65:25
    at save (file:///Users/maemigh/arcana-website/node_modules/@sveltejs/kit/src/core/postbuild/prerender.js:403:4)
    at visit (file:///Users/maemigh/arcana-website/node_modules/@sveltejs/kit/src/core/postbuild/prerender.js:236:3)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)

Node.js v21.5.0
```

### Reproduction

use `event.platform.context.waituntil` inside `hooks.server.ts` and use prerendering

### System Info

```Shell
System:
    OS: macOS 14.3.1
    CPU: (8) arm64 Apple M1
    Memory: 58.55 MB / 16.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 21.5.0 - /opt/homebrew/bin/node
    npm: 10.2.4 - /opt/homebrew/bin/npm
    pnpm: 8.7.0 - ~/Library/pnpm/pnpm
  Browsers:
    Brave Browser: 122.1.63.174
    Edge: 122.0.2365.92
    Firefox Nightly: 92.0a1
    Safari: 17.3.1
  npmPackages:
    @sveltejs/adapter-auto: ^3.0.0 => 3.1.1
    @sveltejs/adapter-cloudflare: ^4.2.0 => 4.2.0
    @sveltejs/kit: ^2.0.6 => 2.5.0
    @sveltejs/vite-plugin-svelte: ^3.0.0 => 3.0.2
    svelte: ^4.2.8 => 4.2.9
    vite: ^5.0.0 => 5.0.12

npx wrangler -v
 ⛅️ wrangler 3.34.2
-------------------
```

### Severity

blocking an upgrade

**Comment by maemigh** [comment]
I'll need some time for this. I've tried to reproduce on an app from scratch without luck.  I'll try tearing down my app piece by piece to until I have a minimal reproduction.

**Comment by eltigerchino** [comment]
We do not provide event.platform.context.waitUntil, etc. during prerendering since they aren't available anyway. Now the question is if we want to fail fast by throwing an error that asks devs to wrap any access to `event.platform` in a conditional such as `if (!building) { }`, log a warning and allow build to continue, or do nothing (fail silently). Leaning towards failing fast.

**Comment by maemigh** [comment]
Not sure if I have much to add here, but I did find the specific statement inside hooks that caused the problem. I have no idea why, and I cant share the code, but I can try wrapping it if it will help
