### ISSUE TITLE
Won't build with Ollama

### ISSUE THREAD

**Issue by Mark2M** [sveltejs/kit#12022]
### Describe the bug

Svelte (@latest) frontend importing ollama runs just fine in dev but when I try to build I get the following errors:

error during build:
RollupError: [vite-plugin-sveltekit-compile] node_modules/ollama/dist/index.js (11:13): "promises" is not exported by "__vite-browser-external", imported by "node_modules/ollama/dist/index.js".

Then further down I get (fulll output is below):
import { createHash } from 'crypto';
    at getRollupError (file:///vercel/path0/node_modules/rollup/dist/es/shared/parseAst.js:376:41)
    at error (file:///vercel/path0/node_modules/rollup/dist/es/shared/parseAst.js:372:42)
    at Module.error (file:///vercel/path0/node_modules/rollup/dist/es/shared/node-entry.js:13654:16)
    at Module.traceVariable (file:///vercel/path0/node_modules/rollup/dist/es/shared/node-entry.js:14102:29)
    at ModuleScope.findVariable (file:///vercel/path0/node_modules/rollup/dist/es/shared/node-entry.js:11805:39)
    at ChildScope.findVariable (file:///vercel/path0/node_modules/rollup/dist/es/shared/node-entry.js:6019:38)
    at ClassBodyScope.findVariable (file:///vercel/path0/node_modules/rollup/dist/es/shared/node-entry.js:6019:38)
    at ChildScope.findVariable (file:///vercel/path0/node_modules/rollup/dist/es/shared/node-entry.js:6019:38)
    at ChildScope.findVariable (file:///vercel/path0/node_modules/rollup/dist/es/shared/node-entry.js:6019:38)
    at FunctionScope.findVariable (file:///vercel/path0/node_modules/rollup/dist/es/shared/node-entry.js:6019:38)
Error: Command "npm run build" exited with 1

I had a quick look at the @node_modules/ollama/dist/index.javascript" file and didn't see any warnings etc. 

Anyone know how to get round this?

I flagged this as "blocking all usage of svelte" but actually it's only blocking deployment.

Cheers

Full build output:
vite v5.1.6 building SSR bundle for production...
✓ 92 modules transformed.
vite v5.1.6 building for production...
[plugin:vite:resolve] [plugin vite:resolve] Module "fs" has been externalized for browser compatibility, imported by "/Users/mdh/Desktop/SvelteKit-AI-FE/node_modules/ollama/dist/index.js". See https://vitejs.dev/guide/troubleshooting.html#module-externalized-for-browser-compatibility for more details.
[plugin:vite:resolve] [plugin vite:resolve] Module "path" has been externalized for browser compatibility, imported by "/Users/mdh/Desktop/SvelteKit-AI-FE/node_modules/ollama/dist/index.js". See https://vitejs.dev/guide/troubleshooting.html#module-externalized-for-browser-compatibility for more details.
[plugin:vite:resolve] [plugin vite:resolve] Module "crypto" has been externalized for browser compatibility, imported by "/Users/mdh/Desktop/SvelteKit-AI-FE/node_modules/ollama/dist/index.js". See https://vitejs.dev/guide/troubleshooting.html#module-externalized-for-browser-compatibility for more details.
[plugin:vite:resolve] [plugin vite:resolve] Module "os" has been externalized for browser compatibility, imported by "/Users/mdh/Desktop/SvelteKit-AI-FE/node_modules/ollama/dist/index.js". See https://vitejs.dev/guide/troubleshooting.html#module-externalized-for-browser-compatibility for more details.
✓ 86 modules transformed.
x Build failed in 356ms
x Build failed in 996ms
error during build:
RollupError: [vite-plugin-sveltekit-compile] node_modules/ollama/dist/index.js (11:13): "promises" is not exported by "__vite-browser-external", imported by "node_modules/ollama/dist/index.js".
file: /Users/mdh/Desktop/SvelteKit-AI-FE/node_modules/ollama/dist/index.js:11:13
 9: };
10: import * as utils from './utils.js';
11: import fs, { promises, createReadStream } from 'fs';
                 ^
12: import { join, resolve, dirname } from 'path';
13: import { createHash } from 'crypto';
file: /Users/mdh/Desktop/SvelteKit-AI-FE/node_modules/ollama/dist/index.js:11:13
 9: };
10: import * as utils from './utils.js';
11: import fs, { promises, createReadStream } from 'fs';
                 ^
12: import { join, resolve, dirname } from 'path';
13: import { createHash } from 'crypto';
    at getRollupError (file:///Users/mdh/Desktop/SvelteKit-AI-FE/node_modules/rollup/dist/es/shared/parseAst.js:376:41)
    at error (file:///Users/mdh/Desktop/SvelteKit-AI-FE/node_modules/rollup/dist/es/shared/parseAst.js:372:42)
    at Module.error (file:///Users/mdh/Desktop/SvelteKit-AI-FE/node_modules/rollup/dist/es/shared/node-entry.js:13654:16)
    at Module.traceVariable (file:///Users/mdh/Desktop/SvelteKit-AI-FE/node_modules/rollup/dist/es/shared/node-entry.js:14102:29)
    at ModuleScope.findVariable (file:///Users/mdh/Desktop/SvelteKit-AI-FE/node_modules/rollup/dist/es/shared/node-entry.js:11805:39)
    at ChildScope.findVariable (file:///Users/mdh/Desktop/SvelteKit-AI-FE/node_modules/rollup/dist/es/shared/node-entry.js:6019:38)
    at ClassBodyScope.findVariable (file:///Users/mdh/Desktop/SvelteKit-AI-FE/node_modules/rollup/dist/es/shared/node-entry.js:6019:38)
    at ChildScope.findVariable (file:///Users/mdh/Desktop/SvelteKit-AI-FE/node_modules/rollup/dist/es/shared/node-entry.js:6019:38)
    at ChildScope.findVariable (file:///Users/mdh/Desktop/SvelteKit-AI-FE/node_modules/rollup/dist/es/shared/node-entry.js:6019:38)
    at FunctionScope.findVariable (file:///Users/mdh/Desktop/SvelteKit-AI-FE/node_modules/rollup/dist/es/shared/node-entry.js:6019:38)

### Reproduction

I'm off out in 5, will stick something up on GH later tonight or tomorrow morning...

### System Info

```shell
System:
    OS: macOS 14.3.1
    CPU: (16) x64 Intel(R) Core(TM) i9-9980HK CPU @ 2.40GHz
    Memory: 16.25 GB / 32.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 20.11.1 - /usr/local/bin/node
    npm: 10.2.4 - /usr/local/bin/npm
  Browsers:
    Chrome: 122.0.6261.129
    Chrome Canary: 122.0.6255.0
    Safari: 17.3.1
  npmPackages:
    svelte: ^4.2.7 => 4.2.12
```

### Severity

blocking all usage of svelte

**Comment by gtm-nayan** [comment]
@Mark2M reminder that we need a proper reproduction in the form of a git repo to investigate and fix the issue. Otherwise it'll be closed.

**Comment by Mark2M** [comment]
Here you go...  https://github.com/Mark2M/sk-ollama-test

It'll work in dev, if you're running Ollama with tinillama you can even click the button and get a response, it just won't build.

Also note that I tried Ollama with remix and that produced the same error.

Cheers

**Comment by gtm-nayan** [comment]
Seems like you should be using the `ollama/browser` endpoint https://github.com/ollama/ollama-js#browser-usage

**Comment by Mark2M** [comment]
That sorted it, thanks very much.
Just had to change my imports from "ollama"to "ollama/browser".

**Comment by Mark2M** [comment]
Works as expected, thanks again
