### ISSUE TITLE
A clean installation of sveltekit tries to fetch /github-markdown-css and /WebExplain.vue.map

### ISSUE THREAD

**Issue by ctwhome** [sveltejs/kit#12078]
### Describe the bug

A clean installation performing `npm create svelte@latest my-app` wither skeleton or app example produces these weird errors, try to fetch `/github-markdown-css` and `/WebExplain.vue.map`
![image](https://github.com/sveltejs/kit/assets/4195550/569efaad-3d96-42e2-9203-1fa401a39631)

updating dependencies to latest versions

### Reproduction

1. in a new directory, install sveletekit with `npm create svelte@latest`
2. Choose skeleton project
3. Choose Typescript syntax
4. Add `eslint` and `prettier`
Next steps:
  1: cd my-app
  2: npm install
  3: npm run dev -- --open

### Logs

```Shell
VITE v5.2.8  ready in 401 ms

  ➜  Local:   http://localhost:5173/
  ➜  Network: http://192.168.1.225:5173/
  ➜  Network: http://192.168.1.29:5173/
  ➜  press h + enter to show help
SvelteKitError: Not found: /github-markdown-css
    at resolve (/Users/ctw/Sites/temp/my-app/node_modules/.pnpm/@sveltejs+kit@2.5.5_@sveltejs+vite-plugin-svelte@3.0.2_svelte@4.2.12_vite@5.2.8/node_modules/@sveltejs/kit/src/runtime/server/respond.js:522:13)
    at resolve (/Users/ctw/Sites/temp/my-app/node_modules/.pnpm/@sveltejs+kit@2.5.5_@sveltejs+vite-plugin-svelte@3.0.2_svelte@4.2.12_vite@5.2.8/node_modules/@sveltejs/kit/src/runtime/server/respond.js:322:5)
    at #options.hooks.handle (/Users/ctw/Sites/temp/my-app/node_modules/.pnpm/@sveltejs+kit@2.5.5_@sveltejs+vite-plugin-svelte@3.0.2_svelte@4.2.12_vite@5.2.8/node_modules/@sveltejs/kit/src/runtime/server/index.js:71:56)
    at Module.respond (/Users/ctw/Sites/temp/my-app/node_modules/.pnpm/@sveltejs+kit@2.5.5_@sveltejs+vite-plugin-svelte@3.0.2_svelte@4.2.12_vite@5.2.8/node_modules/@sveltejs/kit/src/runtime/server/respond.js:319:40)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5) {
  status: 404,
  text: 'Not Found'
}
SvelteKitError: Not found: /WebExplain.vue.map
    at resolve (/Users/ctw/Sites/temp/my-app/node_modules/.pnpm/@sveltejs+kit@2.5.5_@sveltejs+vite-plugin-svelte@3.0.2_svelte@4.2.12_vite@5.2.8/node_modules/@sveltejs/kit/src/runtime/server/respond.js:522:13)
    at resolve (/Users/ctw/Sites/temp/my-app/node_modules/.pnpm/@sveltejs+kit@2.5.5_@sveltejs+vite-plugin-svelte@3.0.2_svelte@4.2.12_vite@5.2.8/node_modules/@sveltejs/kit/src/runtime/server/respond.js:322:5)
    at #options.hooks.handle (/Users/ctw/Sites/temp/my-app/node_modules/.pnpm/@sveltejs+kit@2.5.5_@sveltejs+vite-plugin-svelte@3.0.2_svelte@4.2.12_vite@5.2.8/node_modules/@sveltejs/kit/src/runtime/server/index.js:71:56)
    at Module.respond (/Users/ctw/Sites/temp/my-app/node_modules/.pnpm/@sveltejs+kit@2.5.5_@sveltejs+vite-plugin-svelte@3.0.2_svelte@4.2.12_vite@5.2.8/node_modules/@sveltejs/kit/src/runtime/server/respond.js:319:40)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5) {
  status: 404,
  text: 'Not Found'
}
```

### System Info

```Shell
npx envinfo --system --binaries --browsers --npmPackages "{svelte,@sveltejs/*,vite}" System:
    OS: macOS 14.4
    CPU: (10) arm64 Apple M1 Max
    Memory: 529.28 MB / 32.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 20.10.0 - /usr/local/bin/node
    Yarn: 1.22.17 - ~/.yarn/bin/yarn
    npm: 10.2.3 - /usr/local/bin/npm
    pnpm: 8.15.6 - ~/Library/pnpm/pnpm
    bun: 1.0.1 - ~/.bun/bin/bun
  Browsers:
    Chrome: 123.0.6312.87
    Safari: 17.4
  npmPackages:
    @sveltejs/adapter-auto: ^3.0.0 => 3.2.0
    @sveltejs/kit: ^2.0.0 => 2.5.5
    @sveltejs/vite-plugin-svelte: ^3.0.0 => 3.0.2
    svelte: ^4.2.7 => 4.2.12
    vite: ^5.0.3 => 5.2.8
```

### Severity

serious, but I can work around it

**Comment by Conduitry** [comment]
Are you sure you don't still have a service worker installed on that same host/port from a previous application, or something like that?

**Comment by ctwhome** [comment]
Oh yei you are right, sorry for the bloat!
