### ISSUE TITLE
Failed to execute 'querySelector' on 'Document' (in `load`'s `fetch`)

### ISSUE THREAD

**Issue by csangonzo** [sveltejs/kit#1223]
**Describe the bug**
When using fetch in `load` and the url contains double quotes (`"`, haven't tested other special characters/symbols yet) it gives the following error (`500`):
```
Failed to execute 'querySelector' on 'Document': 'script[type="svelte-data"][url="<my_api_url>/apiv2/trips/trip_templates?$filter={"d":0}&$order_by=id&$direction=DESC"]' is not a valid selector.

Error: Failed to execute 'querySelector' on 'Document': 'script[type="svelte-data"][url="<my_api_url>/apiv2/trips/trip_templates?$filter={"d":0}&$order_by=id&$direction=DESC"]' is not a valid selector.
    at initial_fetch (http://localhost:1111/.svelte/dev/runtime/internal/start.js:353:26)
    at send (http://localhost:1111/src/lib/helpers/api.ts:15:10)
    at Module.get (http://localhost:1111/src/lib/helpers/api.ts:37:10)
    at load (http://localhost:1111/src/routes/templates/index.svelte?import:585:30)
    at Renderer._load_node (http://localhost:1111/.svelte/dev/runtime/internal/start.js:785:37)
    at Renderer.start (http://localhost:1111/.svelte/dev/runtime/internal/start.js:452:29)
    at async start (http://localhost:1111/.svelte/dev/runtime/internal/start.js:1022:15)
```

**To Reproduce**
Try a fetch (https://kit.svelte.dev/docs#loading-input-fetch) in `load` with a double quite in the query parameters, like `fetch('<my_api_url>/apiv2/trips/trip_templates?$filter={"d":0}&$order_by=id&$direction=DESC')`

**Expected behavior**
Load data from the requested source.

**Severity**
I was able to solve it with an additional `encodeURIComponent('$filter={"d":0}')` and it worked, but it would be nice if we didn't have to this.

**Comment by bluwy** [comment]
I'm not getting the error in the latest SvelteKit version anymore, perhaps it has been resolved after upgrading `node-fetch`.
