### ISSUE TITLE
Adapter vercel split option breaks form action

### ISSUE THREAD

**Issue by eltigerchino** [sveltejs/kit#12291]
Not sure if it might be related or not but I encounter another issue that happens in the exact same conditions.
Sadly I've been unable to find the time to create and deploy on Vercel a reproduction. Sorry if this is useless noise 🙏

### Issue: 

In a form action, I trigger an internal `fetch` call to a `+server.ts` route handler.
This route handler returns json data (`return json({ ... })`).
The route handler crashes with `TypeError: immutable` (full error below), and the action receives `{ message: 'Internal Error' }`. Despite what the error message implies, I'm not trying to either set cookies or headers anywhere.

### Conditions: 

- Only happens when deployed on Vercel
- Only happens if the route handler is deployed separately (marked with `split: true`)

### Error details

```
TypeError: immutable
    at _Headers.append (node:internal/deps/undici/undici:2105:17)
    at add_cookies_to_headers (file:///var/task/vercel/path0/apps/client/.svelte-kit/output/server/index.js:2320:13)
    at file:///var/task/vercel/path0/apps/client/.svelte-kit/output/server/index.js:2649:9
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async helpersHandle (file:///var/task/vercel/path0/apps/client/.svelte-kit/output/server/chunks/hooks.server.js:1181:18)
    at async respond (file:///var/task/vercel/path0/apps/client/.svelte-kit/output/server/index.js:2638:22)
    at async fetch (file:///var/task/vercel/path0/apps/client/.svelte-kit/output/server/index.js:2388:26)
```

### Environment

```
    "@sveltejs/adapter-vercel": "3.1.0",
    "@sveltejs/kit": "1.30.4",
    "svelte": "4.2.12",
```

And Node.js 20.x on Vercel.

_Originally posted by @benjaminwaterlot in https://github.com/sveltejs/kit/issues/11879#issuecomment-1971480386_

**Comment by eltigerchino** [comment]
@benjaminwaterlot please provide a downloadable minimal reproduction

**Comment by eltigerchino** [comment]
I'm closing this until a minimal reproduction is made available.

**Comment by wookiehangover** [comment]
I've been running into this to, searching for the error lead me here. I'll see about getting a isolated reproducable use-case together, but this is definitely an issue somewhere between the vercel apadter / undici / event.fetch

**Comment by sproott** [comment]
This problem arose for me when adding configuration to an individual function, namely setting the `maxDuration`. The problem went away when I removed this individual configuration and instead increased the max duration globally in `svelte.config.js`. I'll look into a reproduction.

**Comment by sproott** [comment]
Here it is: https://github.com/sproott/sveltekit-vercel-error-immutable

Additionally, I found out this only happens when the cookies are set on the event (see `hooks.server.ts`), which presumably triggers the `add_cookies_to_headers` function that causes the error.

**Comment by sproott** [comment]
Perhaps related: https://github.com/sveltejs/kit/issues/10366
