### ISSUE TITLE
different targeted production node js versions servers throw error

### ISSUE THREAD

**Issue by hamiednasser2** [sveltejs/kit#12388]
### Describe the bug

After doing everything for production release ..
adding node adapter
npm run build
Everything is ok, working fine in the development server.
In more than one production server it is not worked! it throw this error in log.
I used different versions of node server without success!

Can you explain the problem!

### Reproduction

not found

### Logs

```Shell
/home/dncenter/ameeer/index.js:1
import { handler } from './handler.js';
^^^^^^

SyntaxError: Cannot use import statement outside a module
    at internalCompileFunction (node:internal/vm:76:18)
    at wrapSafe (node:internal/modules/cjs/loader:1283:20)
    at Module._compile (node:internal/modules/cjs/loader:1328:27)
    at Module._extensions..js (node:internal/modules/cjs/loader:1422:10)
    at Module.load (node:internal/modules/cjs/loader:1203:32)
    at Module._load (node:internal/modules/cjs/loader:1019:12)
    at Module.require (node:internal/modules/cjs/loader:1231:19)
    at require (node:internal/modules/helpers:177:18)
    at startApplication (/usr/local/lsws/fcgi-bin/lsnode.js:48:15)
    at Object.<anonymous> (/usr/local/lsws/fcgi-bin/lsnode.js:16:1)

Node.js v18.20.2
/usr/local/lsws/fcgi-bin/lsnode.js:48
    var app = require(startupFile);
              ^

Error [ERR_REQUIRE_ESM]: require() of ES Module /home/dncenter/ameeer/index.js from /usr/local/lsws/fcgi-bin/lsnode.js not supported.
Instead change the require of index.js in /usr/local/lsws/fcgi-bin/lsnode.js to a dynamic import() which is available in all CommonJS modules.
    at startApplication (/usr/local/lsws/fcgi-bin/lsnode.js:48:15)
    at Object.<anonymous> (/usr/local/lsws/fcgi-bin/lsnode.js:16:1) {
  code: 'ERR_REQUIRE_ESM'
}

Node.js v18.20.2
/usr/local/lsws/fcgi-bin/lsnode.js:48
    var app = require(startupFile);
              ^

Error [ERR_REQUIRE_ESM]: require() of ES Module /home/dncenter/ameeer/index.js from /usr/local/lsws/fcgi-bin/lsnode.js not supported.
Instead change the require of index.js in /usr/local/lsws/fcgi-bin/lsnode.js to a dynamic import() which is available in all CommonJS modules.
    at startApplication (/usr/local/lsws/fcgi-bin/lsnode.js:48:15)
    at Object.<anonymous> (/usr/local/lsws/fcgi-bin/lsnode.js:16:1) {
  code: 'ERR_REQUIRE_ESM'
}

Node.js v18.20.2
/usr/local/lsws/fcgi-bin/lsnode.js:48
    var app = require(startupFile);
              ^

Error [ERR_REQUIRE_ESM]: require() of ES Module /home/dncenter/ameeer/index.js from /usr/local/lsws/fcgi-bin/lsnode.js not supported.
Instead change the require of index.js in /usr/local/lsws/fcgi-bin/lsnode.js to a dynamic import() which is available in all CommonJS modules.
    at startApplication (/usr/local/lsws/fcgi-bin/lsnode.js:48:15)
    at Object.<anonymous> (/usr/local/lsws/fcgi-bin/lsnode.js:16:1) {
  code: 'ERR_REQUIRE_ESM'
}

Node.js v18.20.2
/usr/local/lsws/fcgi-bin/lsnode.js:48
    var app = require(startupFile);
              ^

Error [ERR_REQUIRE_ESM]: require() of ES Module /home/dncenter/ameeer/index.js from /usr/local/lsws/fcgi-bin/lsnode.js not supported.
Instead change the require of index.js in /usr/local/lsws/fcgi-bin/lsnode.js to a dynamic import() which is available in all CommonJS modules.
    at startApplication (/usr/local/lsws/fcgi-bin/lsnode.js:48:15)
    at Object.<anonymous> (/usr/local/lsws/fcgi-bin/lsnode.js:16:1) {
  code: 'ERR_REQUIRE_ESM'
}

Node.js v18.20.2
/usr/local/lsws/fcgi-bin/lsnode.js:48
    var app = require(startupFile);
              ^

Error [ERR_REQUIRE_ESM]: require() of ES Module /home/dncenter/ameeer/index.js from /usr/local/lsws/fcgi-bin/lsnode.js not supported.
Instead change the require of index.js in /usr/local/lsws/fcgi-bin/lsnode.js to a dynamic import() which is available in all CommonJS modules.
    at startApplication (/usr/local/lsws/fcgi-bin/lsnode.js:48:15)
    at Object.<anonymous> (/usr/local/lsws/fcgi-bin/lsnode.js:16:1) {
  code: 'ERR_REQUIRE_ESM'
}

Node.js v20.12.2
/usr/local/lsws/fcgi-bin/lsnode.js:48
    var app = require(startupFile);
              ^

Error [ERR_REQUIRE_ESM]: require() of ES Module /home/dncenter/ameeer/index.js from /usr/local/lsws/fcgi-bin/lsnode.js not supported.
Instead change the require of index.js in /usr/local/lsws/fcgi-bin/lsnode.js to a dynamic import() which is available in all CommonJS modules.
    at startApplication (/usr/local/lsws/fcgi-bin/lsnode.js:48:15)
    at Object.<anonymous> (/usr/local/lsws/fcgi-bin/lsnode.js:16:1) {
  code: 'ERR_REQUIRE_ESM'
}

Node.js v20.12.2
/usr/local/lsws/fcgi-bin/lsnode.js:48
    var app = require(startupFile);
              ^

Error [ERR_REQUIRE_ESM]: require() of ES Module /home/dncenter/ameeer/index.js from /usr/local/lsws/fcgi-bin/lsnode.js not supported.
Instead change the require of index.js in /usr/local/lsws/fcgi-bin/lsnode.js to a dynamic import() which is available in all CommonJS modules.
    at startApplication (/usr/local/lsws/fcgi-bin/lsnode.js:48:15)
    at Object.<anonymous> (/usr/local/lsws/fcgi-bin/lsnode.js:16:1) {
  code: 'ERR_REQUIRE_ESM'
}

Node.js v20.12.2
/usr/local/lsws/fcgi-bin/lsnode.js:48
    var app = require(startupFile);
              ^

Error [ERR_REQUIRE_ESM]: require() of ES Module /home/dncenter/ameeer/index.js from /usr/local/lsws/fcgi-bin/lsnode.js not supported.
Instead change the require of index.js in /usr/local/lsws/fcgi-bin/lsnode.js to a dynamic import() which is available in all CommonJS modules.
    at startApplication (/usr/local/lsws/fcgi-bin/lsnode.js:48:15)
    at Object.<anonymous> (/usr/local/lsws/fcgi-bin/lsnode.js:16:1) {
  code: 'ERR_REQUIRE_ESM'
}

Node.js v20.12.2
/usr/local/lsws/fcgi-bin/lsnode.js:48
    var app = require(startupFile);
              ^

Error [ERR_REQUIRE_ESM]: require() of ES Module /home/dncenter/ameeer/index.js from /usr/local/lsws/fcgi-bin/lsnode.js not supported.
Instead change the require of index.js in /usr/local/lsws/fcgi-bin/lsnode.js to a dynamic import() which is available in all CommonJS modules.
    at startApplication (/usr/local/lsws/fcgi-bin/lsnode.js:48:15)
    at Object.<anonymous> (/usr/local/lsws/fcgi-bin/lsnode.js:16:1) {
  code: 'ERR_REQUIRE_ESM'
}

Node.js v20.12.2
/usr/local/lsws/fcgi-bin/lsnode.js:48
    var app = require(startupFile);
              ^

Error [ERR_REQUIRE_ESM]: require() of ES Module /home/dncenter/ameeer/index.js from /usr/local/lsws/fcgi-bin/lsnode.js not supported.
Instead change the require of index.js in /usr/local/lsws/fcgi-bin/lsnode.js to a dynamic import() which is available in all CommonJS modules.
    at startApplication (/usr/local/lsws/fcgi-bin/lsnode.js:48:15)
    at Object.<anonymous> (/usr/local/lsws/fcgi-bin/lsnode.js:16:1) {
  code: 'ERR_REQUIRE_ESM'
}

Node.js v20.12.2
```

### System Info

```Shell
System:
    OS: Windows 10 10.0.18362
    CPU: (4) x64 Intel(R) Core(TM) i7-3520M CPU @ 2.90GHz
    Memory: 1.54 GB / 7.90 GB
  Binaries:
    Node: 22.0.0 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.19 - C:\Program Files (x86)\Yarn\bin\yarn.CMD
    npm: 10.8.1 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Chrome: 126.0.6478.62
    Edge: Spartan (44.18362.449.0)
    Internet Explorer: 11.0.18362.1
  npmPackages:
    latest-version: ^7.0.0 => 7.0.0
```

### Severity

annoyance

### Additional Information

thanks no more info.

**Comment by Conduitry** [comment]
https://kit.svelte.dev/docs/adapter-node#deploying You need to deploy your `package.json` as well.
