### ISSUE TITLE
Using $app/environment inside web worker fails during build

### ISSUE THREAD

**Issue by minht11** [sveltejs/kit#12394]
### Describe the bug

Using $app/environment inside web worker fails during build
```js
const worker = new Worker(new URL('./worker/worker.ts', import.meta.url), {
	type: 'module',
})
...
// worker.ts
import { browser } from '$app/environment'

console.log('inside worker', browser)
```

### Reproduction

1. Goto https://www.sveltelab.dev/wwxy90a2fe8vp1h 
2. Run `npm run build`
3. Observe error

### Logs

```Shell
error during build:
[vite-plugin-sveltekit-compile] [vite:worker-import-meta-url] [vite]: Rollup failed to resolve import "__sveltekit/environment" from "/home/httpswwwsveltelabdev-dcnb-fnp5gm3c/node_modules/@sveltejs/kit/src/runtime/app/environment/index.js".
This is most likely unintended because it can break your application at runtime.
If you do want to externalize this module explicitly add it to
`build.rollupOptions.external`
file: /home/httpswwwsveltelabdev-dcnb-fnp5gm3c/src/lib/index.js
file: /home/httpswwwsveltelabdev-dcnb-fnp5gm3c/src/lib/index.js
[vite:worker-import-meta-url] [vite]: Rollup failed to resolve import "__sveltekit/environment" from "/home/httpswwwsveltelabdev-dcnb-fnp5gm3c/node_modules/@sveltejs/kit/src/runtime/app/environment/index.js".
This is most likely unintended because it can break your application at runtime.
If you do want to externalize this module explicitly add it to
`build.rollupOptions.external`
file: /home/httpswwwsveltelabdev-dcnb-fnp5gm3c/src/lib/index.js
    at viteWarn (file:///home/httpswwwsveltelabdev-dcnb-fnp5gm3c/node_modules/vite/dist/node/chunks/dep-BcXSligG.js:65859:17)
    at onRollupWarning (file:///home/httpswwwsveltelabdev-dcnb-fnp5gm3c/node_modules/vite/dist/node/chunks/dep-BcXSligG.js:65894:5)
    at onwarn (file:///home/httpswwwsveltelabdev-dcnb-fnp5gm3c/node_modules/vite/dist/node/chunks/dep-BcXSligG.js:48136:7)
    at eval (file:///home/httpswwwsveltelabdev-dcnb-fnp5gm3c/node_modules/rollup/dist/es/shared/node-entry.js:18539:13)
    at Object.logger (file:///home/httpswwwsveltelabdev-dcnb-fnp5gm3c/node_modules/rollup/dist/es/shared/node-entry.js:20187:9)
    at ModuleLoader.handleInvalidResolvedId (file:///home/httpswwwsveltelabdev-dcnb-fnp5gm3c/node_modules/rollup/dist/es/shared/node-entry.js:19129:26)
    at eval (file:///home/httpswwwsveltelabdev-dcnb-fnp5gm3c/node_modules/rollup/dist/es/shared/node-entry.js:19087:26)
```
```


### System Info

```Shell
System:
    OS: macOS 14.3.1
    CPU: (8) arm64 Apple M1
    Memory: 80.52 MB / 8.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 20.11.1 - ~/.proto/shims/node
    npm: 10.2.4 - ~/.proto/shims/npm
    pnpm: 9.1.4 - ~/.proto/shims/pnpm
    bun: 0.8.1 - /opt/homebrew/bin/bun
  Browsers:
    Brave Browser: 123.1.64.116
    Chrome: 126.0.6478.114
    Chrome Canary: 128.0.6551.0
    Edge: 126.0.2592.68
    Safari: 17.3.1
  npmPackages:
    @sveltejs/adapter-static: ^3.0.2 => 3.0.2 
    @sveltejs/kit: ^2.5.17 => 2.5.17 
    @sveltejs/vite-plugin-svelte: 4.0.0-next.3 => 4.0.0-next.3 
    svelte: 5.0.0-next.162 => 5.0.0-next.162 
    vite: ^5.3.1 => 5.3.1
```

### Severity

serious, but I can work around it

**Comment by shadow-identity** [comment]
My workaround is to import and init worker like this: 
```js
import { assets } from '$app/paths'

const Worker = await import(`${assets}/worker.js`)
const worker = new Worker.default()
```

You don't have to move worker to the actual static folder. It keeps working without it. 

And the bug is reproducible not only with `$app/environment` import. I don't have it in the project, but it was still failing.

**Comment by teemingc** [comment]
This is solved with in SvelteKit 3 now that the `$app/env` is generated and available in all environments
