### ISSUE TITLE
Cannot find svelte inspector when running dev server

### ISSUE THREAD

**Issue by f-llewellyn** [sveltejs/kit#12495]
### Describe the bug

Recently had to reinstall Windows and am trying to pick my svelte-kit project back up again. I get the following issue when trying to run the dev server:

```
error when starting dev server:
file:///C:/Users/llewe/Documents/web/projects/reg-message/reg-message-frontend/node_modules/.pnpm/@sveltejs+vite-plugin-svelte@3.1.1_svelte@4.2.18_vite@5.3.4/node_modules/@sveltejs/vite-plugin-svelte/src/index.js:3
import { svelteInspector } from '@sveltejs/vite-plugin-svelte-inspector';
         ^^^^^^^^^^^^^^^
SyntaxError: Named export 'svelteInspector' not found. The requested module '@sveltejs/vite-plugin-svelte-inspector' is a CommonJS module, which may not support all module.exports as named exports.
CommonJS modules can always be imported via the default export, for example using:

import pkg from '@sveltejs/vite-plugin-svelte-inspector';
const { svelteInspector } = pkg;

    at ModuleJob._instantiate (node:internal/modules/esm/module_job:171:21)
    at async ModuleJob.run (node:internal/modules/esm/module_job:254:5)
    at async ModuleLoader.import (node:internal/modules/esm/loader:474:24)
    at async load_config (file:///C:/Users/llewe/Documents/web/projects/reg-message/reg-message-frontend/node_modules/.pnpm/@sveltejs+kit@2.5.18_@sveltejs+vite-plugin-svelte@3.1.1_svelte@4.2.18_vite@5.3.4__svelte@4.2.18_vite@5.3.4/node_modules/@sveltejs/kit/src/core/config/index.js:70:17)
    at async sveltekit (file:///C:/Users/llewe/Documents/web/projects/reg-message/reg-message-frontend/node_modules/.pnpm/@sveltejs+kit@2.5.18_@sveltejs+vite-plugin-svelte@3.1.1_svelte@4.2.18_vite@5.3.4__svelte@4.2.18_vite@5.3.4/node_modules/@sveltejs/kit/src/exports/vite/index.js:130:24)
    at async Promise.all (index 0)
    at async asyncFlatten (file:///C:/Users/llewe/Documents/web/projects/reg-message/reg-message-frontend/node_modules/.pnpm/vite@5.3.4/node_modules/vite/dist/node/chunks/dep-D8YhmIY-.js:17369:12)
    at async resolveConfig (file:///C:/Users/llewe/Documents/web/projects/reg-message/reg-message-frontend/node_modules/.pnpm/vite@5.3.4/node_modules/vite/dist/node/chunks/dep-D8YhmIY-.js:66463:27)
    at async _createServer (file:///C:/Users/llewe/Documents/web/projects/reg-message/reg-message-frontend/node_modules/.pnpm/vite@5.3.4/node_modules/vite/dist/node/chunks/dep-D8YhmIY-.js:63050:18)
    at async CAC.<anonymous> (file:///C:/Users/llewe/Documents/web/projects/reg-message/reg-message-frontend/node_modules/.pnpm/vite@5.3.4/node_modules/vite/dist/node/cli.js:735:20)
```

When creating a new sveltekit project using the same package versions, the issue is not present.

### Reproduction

1. Install git bash for windows (v2.45.2) [here](https://git-scm.com/download/win)
2. Install pnpm v9.6.0 with `npm install -g pnpm@9.6.0`
3. Clone the repo found here: [f-llewellyn/reg-message-frontend](https://github.com/f-llewellyn/reg-message-frontend)
4. Navigate to the cloned repo
5. Run `pnpm i` to install the packages
6. Run `pnpm dev` to run the dev server

### System Info

```Shell
System:
    OS: Windows 11 10.0.22631
    CPU: (12) x64 AMD Ryzen 5 5600 6-Core Processor
    Memory: 18.20 GB / 31.91 GB
  Binaries:
    Node: 22.3.0 - C:\Program Files\nodejs\node.EXE
    npm: 10.8.1 - C:\Program Files\nodejs\npm.CMD
    pnpm: 9.6.0 - C:\Program Files\nodejs\pnpm.CMD
  Browsers:
    Edge: Chromium (126.0.2592.113)
    Internet Explorer: 11.0.22621.3527
  npmPackages:
    @sveltejs/adapter-auto: ^3.2.2 => 3.2.2
    @sveltejs/kit: ^2.5.18 => 2.5.18
    @sveltejs/vite-plugin-svelte: ^3.1.1 => 3.1.1
    svelte: ^4.2.18 => 4.2.18
    vite: ^5.3.4 => 5.3.4
```

### Severity

blocking all usage of SvelteKit

**Comment by f-llewellyn** [comment]
This appears to be an issue with pnpm, as when following the repro steps with npm the issue does not occur.
