### ISSUE TITLE
redirect : Data returned from action inside /login is not serializable: Cannot stringify arbitrary non-POJOs

### ISSUE THREAD

**Issue by jz9423** [sveltejs/kit#12494]
### Describe the bug

As of sveltekit 2.5.18, revoke a redirect() object from an Action fails with the following error when using npm run dev

```text
Error: Data returned from action inside /login is not serializable: Cannot stringify arbitrary non-POJOs (data..error)
```

### Reproduction

```+page.server.js```

```js
import { fail, redirect } from "@sveltejs/kit";

export const actions = {
  login: async ({ request, url, fetch }) => {
    let data = await request.formData();
    const account = data.get("account");
    const password = data.get("password");
   
    try {
      const response = await fetch("/api/login", options);
      const getLoginUser = await response.json();
      
      if (getLoginUser.status !== 0) {
        return fail(422, {
          account,
          password,
          error:
            "Status: " + getLoginUser.status + " ,Msg: " + getLoginUser.msg,
        });
      }
      if (!getLoginUser.data) {
        return fail(422, {
          account,
          password,
          error: "invalid data from server",
        });
      }
      locals.authed = true;
      locals.user = getLoginUser.data;
      
      if (url.searchParams.has("redirectTo")) {
        redirect(303, url.searchParams.get("redirectTo"));
      } else {
        redirect(303, "/index");
      }
    } catch (err) {
      let msg = err.message ? err.message : err;
      return fail(422, { account, password, error: msg });
    }
  }
};
```

```+page.svelte```

```html
<script>
  import { enhance } from "$app/forms";
  export let form;
</script>

<form id="loginForm" method="POST" action="?/login" use:enhance>
    <div class="item">
      <label for="username"
        ><span class="material-symbols-outlined"> person </span></label
      >
      <input
        type="text"
        id="username"
        name="account"
        placeholder="请输入用户名"
        value={form?.account ?? ""}
      />
    </div>
    <div class="item">
      <label for="username"
        ><span class="material-symbols-outlined"> lock </span></label
      >
      <input
        type="password"
        id="password"
        name="password"
        placeholder="请输入密码"
        value={form?.password ?? ""}
      />
    </div>
    {#if form?.error}
      <div class="item error">
        <span style="width: 30px;height: 39px;"></span>
        <span class="invalid">{form.error}</span>
      </div>
    {/if}
    <div class="item">
      <span style="width: 30px;height: 39px;"></span>
      <button type="submit" class="login-btn">登录</button>
    </div>
  </form>
```

### Logs

```Shell
Error: Data returned from action inside /login is not serializable: Cannot stringify arbitrary non-POJOs (data..error)
    at try_deserialize (D:\zdev\project\repl\node_modules\@sveltejs\kit\src\runtime\server\page\actions.js:286:10)
    at stringify_action_response (D:\zdev\project\repl\node_modules\@sveltejs\kit\src\runtime\server\page\actions.js:268:9)
    at Module.handle_action_json_request (D:\zdev\project\repl\node_modules\@sveltejs\kit\src\runtime\server\page\actions.js:64:11)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async resolve (D:\zdev\project\repl\node_modules\@sveltejs\kit\src\runtime\server\respond.js:446:18)
    at async Module.respond (D:\zdev\project\repl\node_modules\@sveltejs\kit\src\runtime\server\respond.js:319:20)
    at async file:///D:/zdev/project/repl/node_modules/@sveltejs/kit/src/exports/vite/dev/index.js:524:22
```

### System Info

```Shell
System:
    OS: Windows Server 2019 Datacenter
    CPU: Intel(R) Core(TM) i5-8250U CPU @ 1.60GHz 1.80GHz
    Memory: 8 GB (7.85 GB）
  Binaries:
    Node: 20.13.1 - d:\Program Files\nodejs\node.EXE
    npm: 10.5.2 - d:\Program Files\nodejs\npm.CMD
  Browsers:
    Chrome: 126.0.6478.128（x64）
  npmPackages:
    "@sveltejs/adapter-auto": "^3.2.2",
    "@sveltejs/kit": "^2.5.18",
    "@sveltejs/vite-plugin-svelte": "^3.1.1",
    "@types/node": "^20.14.12",
    "material-symbols": "^0.21.2",
    "notyf": "^3.10.0",
    "postcss": "^8.4.39",
    "sass": "^1.77.8",
    "svelte": "^4.2.18",
    "vite": "^5.3.4"
```

### Severity

blocking an upgrade

**Comment by eltigerchino** [comment]
The error you're catching in the try...catch block cannot be serialised by the server so you shouldn't return it in the `fail` function.

**Comment by jz9423** [comment]
thank you，problem solved
