### ISSUE TITLE
Cannot import $env/dynamic/private into client-side code should include context

### ISSUE THREAD

**Issue by eighty4** [sveltejs/kit#12550]
### Describe the problem

Importing `$env/dynamic/private` from `src/hooks.ts` throws an error about the import not supported in client side code, but it doesn't say that the error is coming from `src/hooks.ts`.

Here is the output from SvelteKit:

```
5:27:33 PM [vite] Internal server error: Cannot import $env/dynamic/private into client-side code
      at LoadPluginContext.load (file:///Users/adam/work/eighty4/music-lesson-studio/web/node_modules/.pnpm/@sveltejs+kit@2.5.20_@sveltejs+vite-plugin-svelte@3.1.1_svelte@5.0.0-next.184_vite@5.3.5_@typ_nktueinoag7c77ghffmdk4wvdm/node_modules/@sveltejs/kit/src/exports/vite/index.js:400:12)
      at PluginContainer.load (file:///Users/adam/work/eighty4/music-lesson-studio/web/node_modules/.pnpm/vite@5.3.5_@types+node@22.1.0/node_modules/vite/dist/node/chunks/dep-mCdpKltl.js:48754:17)
      at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
      at async loadAndTransform (file:///Users/adam/work/eighty4/music-lesson-studio/web/node_modules/.pnpm/vite@5.3.5_@types+node@22.1.0/node_modules/vite/dist/node/chunks/dep-mCdpKltl.js:51548:22)
      at async viteTransformMiddleware (file:///Users/adam/work/eighty4/music-lesson-studio/web/node_modules/.pnpm/vite@5.3.5_@types+node@22.1.0/node_modules/vite/dist/node/chunks/dep-mCdpKltl.js:61557:24) (x4)
```

### Describe the proposed solution

Error message should specify the source file in userland code causing the problem.

```
5:27:33 PM [vite] Internal server error: Cannot import $env/dynamic/private into client-side code which is done by src/hooks.ts
      at LoadPluginContext.load (file:///Users/adam/work/eighty4/music-lesson-studio/web/node_modules/.pnpm/@sveltejs+kit@2.5.20_@sveltejs+vite-plugin-svelte@3.1.1_svelte@5.0.0-next.184_vite@5.3.5_@typ_nktueinoag7c77ghffmdk4wvdm/node_modules/@sveltejs/kit/src/exports/vite/index.js:400:12)
      at PluginContainer.load (file:///Users/adam/work/eighty4/music-lesson-studio/web/node_modules/.pnpm/vite@5.3.5_@types+node@22.1.0/node_modules/vite/dist/node/chunks/dep-mCdpKltl.js:48754:17)
      at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
      at async loadAndTransform (file:///Users/adam/work/eighty4/music-lesson-studio/web/node_modules/.pnpm/vite@5.3.5_@types+node@22.1.0/node_modules/vite/dist/node/chunks/dep-mCdpKltl.js:51548:22)
      at async viteTransformMiddleware (file:///Users/adam/work/eighty4/music-lesson-studio/web/node_modules/.pnpm/vite@5.3.5_@types+node@22.1.0/node_modules/vite/dist/node/chunks/dep-mCdpKltl.js:61557:24) (x4)
```

The import of `$env/dynamic/private` could be in a source file imported by a source imported by a source that's eventually referenced in `src/hooks.ts`. The knowledge of `src/hooks.ts` being the cause of the client-side code infringing dependency and the eventual source infringing would be even more helpful:

```
5:27:33 PM [vite] Internal server error: Cannot import $env/dynamic/private into client-side code which is done by src/lib/data.ts and imported by src/hooks.ts which is a client-side only extension point
      at LoadPluginContext.load (file:///Users/adam/work/eighty4/music-lesson-studio/web/node_modules/.pnpm/@sveltejs+kit@2.5.20_@sveltejs+vite-plugin-svelte@3.1.1_svelte@5.0.0-next.184_vite@5.3.5_@typ_nktueinoag7c77ghffmdk4wvdm/node_modules/@sveltejs/kit/src/exports/vite/index.js:400:12)
      at PluginContainer.load (file:///Users/adam/work/eighty4/music-lesson-studio/web/node_modules/.pnpm/vite@5.3.5_@types+node@22.1.0/node_modules/vite/dist/node/chunks/dep-mCdpKltl.js:48754:17)
      at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
      at async loadAndTransform (file:///Users/adam/work/eighty4/music-lesson-studio/web/node_modules/.pnpm/vite@5.3.5_@types+node@22.1.0/node_modules/vite/dist/node/chunks/dep-mCdpKltl.js:51548:22)
      at async viteTransformMiddleware (file:///Users/adam/work/eighty4/music-lesson-studio/web/node_modules/.pnpm/vite@5.3.5_@types+node@22.1.0/node_modules/vite/dist/node/chunks/dep-mCdpKltl.js:61557:24) (x4)
```

### Importance

nice to have

**Comment by lcgp** [comment]
To trace it, open the `Context.load` function from the stack trace in your editor...

```diff
	const plugin_virtual_modules = {
		name: 'vite-plugin-sveltekit-virtual-modules',

		resolveId(id, importer) {
			// If importing from a service-worker, only allow $service-worker & $env/static/public, but none of the other virtual modules.
			// This check won't catch transitive imports, but it will warn when the import comes from a service-worker directly.
			// Transitive imports will be caught during the build.
			if (importer) {
				const parsed_importer = path.parse(importer);

				const importer_is_service_worker =
					parsed_importer.dir === parsed_service_worker.dir &&
					parsed_importer.name === parsed_service_worker.name;

				if (importer_is_service_worker && id !== '$service-worker' && id !== '$env/static/public') {
					throw new Error(
						`Cannot import ${id} into service-worker code. Only the modules $service-worker and $env/static/public are available in service workers.`
					);
				}
			}

			// treat $env/static/[public|private] as virtual
			if (id.startsWith('$env/') || id.startsWith('__sveltekit/') || id === '$service-worker') {
+ 				console.log({importer})
				return `\0virtual:${id}`;
			}
		},
```

**Comment by eltigerchino** [comment]
[Reproduction](https://stackblitz.com/edit/sveltejs-kit-template-default-hmkjmx?description=The%20default%20SvelteKit%20template,%20generated%20with%20create-svelte&file=src/hooks.ts&title=SvelteKit%20Default%20Template)
