### ISSUE TITLE
SvelteKitError: Not found: /preload.js.map

### ISSUE THREAD

**Issue by JeffWScott** [sveltejs/kit#12562]
### Describe the bug

`SvelteKitError: Not found: /preload.js.map
    at resolve (/home/.../projects/.../node_modules/@sveltejs/kit/src/runtime/server/respond.js:525:13)
    at resolve (/home/.../projects/.../node_modules/@sveltejs/kit/src/runtime/server/respond.js:325:5)
    at #options.hooks.handle (/home/.../projects/.../node_modules/@sveltejs/kit/src/runtime/server/index.js:71:56)
    at Module.respond (/home/.../projects/.../node_modules/@sveltejs/kit/src/runtime/server/respond.js:322:40)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5) {
  status: 404,
  text: 'Not Found'
}`

### Reproduction

npm run dev

### System Info

```Shell
Windows 11, WSL
```

### Severity

serious, but I can work around it

### Additional Information

I'm not sure why this is popping up.  The error doesn't give me anything to work with. 

As far as I can tell it only happens on "npm run dev" and not on production.

**Comment by Conduitry** [comment]
Do you have a service worker installed (perhaps from another app) that's requesting this file? I don't believe SK itself would be requesting this.

**Comment by JeffWScott** [comment]
> Do you have a service worker installed (perhaps from another app) that's requesting this file? I don't believe SK itself would be requesting this.

Yes this looks like the issue. Thank for your help!
