### ISSUE TITLE
LocalStorage undefined on build

### ISSUE THREAD

**Issue by acbp** [sveltejs/kit#1260]
**Describe the bug**
Whenever I use localStorage on JS file it crashes my app and my builds.
Could be something missing on vite configuration ?

**Logs**
```shell
08:59:45 [vite] page reload src/stores/projetos/store.js
08:59:45 [vite] Error when evaluating SSR module /src/stores/projetos/store.js:
ReferenceError: localStorage is not defined
    at /src/stores/projetos/store.js:22:3
    at subscribe (/home/lu/projetos/lab/mygoals/node_modules/svelte/store/index.js:54:9)
    at createList (/src/stores/projetos/store.js:21:2)
    at /src/stores/projetos/store.js:163:21
    at instantiateModule (/home/lu/projetos/lab/mygoals/node_modules/vite/dist/node/chunks/dep-994e0558.js:69063:166)
```

**To Reproduce**
Here my **store.js** and my **svelte.config.cjs**
```js
import { writable } from 'svelte/store';
export const list = writable([]);
list.subscribe((value) => {
    localStorage.setItem('myList', JSON.stringify(value));
});
```
```js
const sveltePreprocess = require('svelte-preprocess');
const statik = require('@sveltejs/adapter-static');
const pkg = require('./package.json');
const { resolve } = require("path");
// const node = require('@sveltejs/adapter-node');
// const netlify = require('@sveltejs/adapter-netlify');

/** @type {import('@sveltejs/kit').Config} */
module.exports = {
	preprocess: sveltePreprocess(),
	kit: {
		appDir: 'app',
		adapter: statik(),
		target: '#svelte',

		vite: () => ({
			resolve: {
				alias: {
					$stores: resolve("./src/stores"),
					$shared: resolve("./src/shared"),
				},
			},
			outDir: 'build',
			emptyOutDir: true,
		}),

		ssr: false,
		hydrate: true,
		router: true,
		prerender: {
			crawl: true,
			enabled: true,
			force: false,
			pages: ['*']
		},
		host: 'localhost',
		paths: {
			assets: '',
			base: '',
		},
	}
};
```

**Expected behavior**
Should buid and allow to use localStorage on any js file.

**Information about your SvelteKit Installation:**

<details>
  <summary>Diagnostics</summary>

I've used the get started setup

- The output of `npx envinfo --system --npmPackages svelte,@sveltejs/kit,vite --binaries --browsers`
```shell
  System:
    OS: Linux 5.10 Manjaro Linux
    CPU: (12) x64 AMD Ryzen 5 3600 6-Core Processor
    Memory: 2.18 GB / 15.61 GB
    Container: Yes
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 14.15.1 - ~/.asdf/installs/nodejs/14.15.1/bin/node
    Yarn: 1.22.10 - /usr/bin/yarn
    npm: 6.14.8 - ~/.asdf/installs/nodejs/14.15.1/bin/npm
    Watchman: 4.9.0 - /usr/bin/watchman
  Browsers:
    Firefox: 88.0
  npmPackages:
    @sveltejs/kit: next => 1.0.0-next.89 
    svelte: ^3.29.0 => 3.37.0 
    vite: ^2.1.0 => 2.2.3 
```
- Your browser
Any
- Your adapter 
Static
Node 
Netlify

</details>

**Severity**
High, it's blocking all build on netlify

**Additional context**
I've just try save some persistent data on localStorage until implement offline storage with Pouchdb

**Comment by Conduitry** [comment]
You need to make sure you're not using local storage on the server during SSR because it's not defined there. You also should be careful about stores on the server because they will by default be shared across all users of the app.
