### ISSUE TITLE
QuotaExceededError - You have exceeded the number of active timeouts you may set. max active timeouts: 10000, current active timeouts: 10000, finished timeouts: 4

### ISSUE THREAD

**Issue by ConProgramming** [sveltejs/kit#12683]
### Describe the bug

I got the following error in our serverside SvelteKit logs. It seems to have messed up a user session. It doesn't always happen, but it did once, and broke some important state. So important to fix this.

Error: {"code":22,"name":"QuotaExceededError","message":"You have exceeded the number of active timeouts you may set. max active timeouts: 10000, current active timeouts: 10000, finished timeouts: 4","stack":"QuotaExceededError: You have exceeded the number of active timeouts you may set. max active timeouts: 10000, current active timeouts: 10000, finished timeouts: 4\n    at worker.js:57475:15\n    at worker.js:171887:13\n    at Object.$$render (worker.js:314:19)\n    at worker.js:173830:97\n    at Object.$$render (worker.js:314:19)\n    at Object.default (worker.js:178270:72)\n    at Object.default (worker.js:142372:52)\n    at worker.js:142308:197\n    at Object.$$render (worker.js:314:19)\n    at worker.js:142359:77"}

### Reproduction

Honestly, no idea how to reproduce this. Best I can say is SvelteKit running on Cloudflare with a pretty advanced project.

### System Info

```Shell
Cloudflare Workers
```

### Severity

serious, but I can work around it

### Additional Information

Don't have a workaround right now.

**Comment by Antonio-Bennett** [comment]
I’m afraid this is not gonna go anywhere without a reproduction… just letting you know since it’s impossible to know what would need to be fixed

**Comment by ConProgramming** [comment]
Any knowledge of internal that could help me track this down? What in SvelteKit might use setTimeout ?

**Comment by paoloricciuti** [comment]
The stacktrace could help you (and us) to find the problem...what i would do is build you project locally, open the fine `./.svelte-kit/worker.js` use the gotoline function from vscode to jump to the lines in the stacktrace and try to see which code is creating `setTimeout`...it will very likely be a minified file but you/we could try to relate that to a specific part of the codebase to see if there's something that has to do with svelte or with some other library/some code that you wrote.

Without a reproduction, some code or even the versions of svelte and sveltekit that you are using this is like trying to find a needle in a haystack.

**Comment by Rich-Harris** [comment]
You can also disable minification in your `vite.config.js` (`build: { minify: false }`). I would look for any `setTimeout` calls in your codebase that don't have a corresponding `clearTimeout`.

**Comment by mechbear14** [comment]
The "timeout" in the logs seems to refer to Cloudflare Worker timeouts, not the `setTimeout` in the browser. Given the OP mentioned this log was on the server, the error seems to be in the SSR stage. I suggest checking the `load` functions in `+page.server.js` files and see how the timeouts were set there.

**Comment by elliott-with-the-longest-name-on-github** [comment]
This issue has been dead for a while. If you can still reproduce this issue, please: 
- `npx sv create my-repro`
- `git init && git add --all && git commit -m "Initial commit"`
- Add the code that minimally illustrates your issue
- `git add --all && git commit -m "Reproduce issue"`
- Create a repository on GutHub and upload your code
- Open a new issue with the reproduction

There's not much we can do here without more information. We might be able to help if you can provide a stack trace to the code creating the `setTimeout`.
