### ISSUE TITLE
A component can have a single top-level `<script>` element and/or a single top-level `<script context="module">` element

### ISSUE THREAD

**Issue by beeb** [sveltejs/kit#12723]
### Describe the bug

I'm trying to update my website to the latest versions of svelte and @sveltejs/vite-plugin-svelte but I'm faced with a new error:

`A component can have a single top-level <script> element and/or a single top-level <script context="module"> element`

I certainly don't have two script tags in my pages and components and so it looks like some preprocessing step added an empty `<script module></script>`. I'm unable to find where it comes from since I use a few plugins, maybe someone well versed in how vite and svelte functions can point me in the right direction!

### Reproduction

```console
git clone -b update-deps https://github.com/beeb/beeb-li.git
pnpm install
pnpm run build
```

### Logs

```Shell
❯ pnpm run build

> beeb-li@0.1.0 build /home/valentin/perso/beeb-li
> vite build

vite v5.4.8 building SSR bundle for production...
✓ 6 modules transformed.
x Build failed in 61ms
error during build:
[vite-plugin-svelte] [plugin vite-plugin-svelte] src/routes/blog/[post]/+page.svelte (2:0): src/routes/blog/[post]/+page.svelte:2:0 A component can have a single top-level `<script>` element and/or a single top-level `<script context="module">` element
file: /home/valentin/perso/beeb-li/src/routes/blog/[post]/+page.svelte:2:0

 1 |  <script module></script>
 2 |  <script lang="ts">
      ^
 3 |    import { mount } from 'svelte'
 4 |    import { siteTitle } from '$lib/config'

CompileError: A component can have a single top-level `<script>` element and/or a single top-level `<script context="module">` element
    at e (file:///home/valentin/perso/beeb-li/node_modules/.pnpm/svelte@5.0.0-next.205/node_modules/svelte/src/compiler/errors.js:29:8)
    at Module.script_duplicate (file:///home/valentin/perso/beeb-li/node_modules/.pnpm/svelte@5.0.0-next.205/node_modules/svelte/src/compiler/errors.js:1024:2)
    at element (file:///home/valentin/perso/beeb-li/node_modules/.pnpm/svelte@5.0.0-next.205/node_modules/svelte/src/compiler/phases/1-parse/state/element.js:327:29)
    at new Parser (file:///home/valentin/perso/beeb-li/node_modules/.pnpm/svelte@5.0.0-next.205/node_modules/svelte/src/compiler/phases/1-parse/index.js:84:12)
    at parse (file:///home/valentin/perso/beeb-li/node_modules/.pnpm/svelte@5.0.0-next.205/node_modules/svelte/src/compiler/phases/1-parse/index.js:294:17)
    at Module.compile (file:///home/valentin/perso/beeb-li/node_modules/.pnpm/svelte@5.0.0-next.205/node_modules/svelte/src/compiler/index.js:27:15)
    at compileSvelte (file:///home/valentin/perso/beeb-li/node_modules/.pnpm/@sveltejs+vite-plugin-svelte@4.0.0-next.7_svelte@5.0.0-next.205_vite@5.4.8/node_modules/@sveltejs/vite-plugin-svelte/src/utils/compile.js:135:22)
    at async Object.transform (file:///home/valentin/perso/beeb-li/node_modules/.pnpm/@sveltejs+vite-plugin-svelte@4.0.0-next.7_svelte@5.0.0-next.205_vite@5.4.8/node_modules/@sveltejs/vite-plugin-svelte/src/index.js:147:20)
    at async transform (file:///home/valentin/perso/beeb-li/node_modules/.pnpm/rollup@4.22.4/node_modules/rollup/dist/es/shared/node-entry.js:18848:16)
    at async ModuleLoader.addModuleSource (file:///home/valentin/perso/beeb-li/node_modules/.pnpm/rollup@4.22.4/node_modules/rollup/dist/es/shared/node-entry.js:19064:36)
 ELIFECYCLE  Command failed with exit code 1.
```

### System Info

```Shell
❯ pnpx envinfo --system --binaries --browsers --npmPackages "{svelte,@sveltejs/*,vite}"
Packages: +1
+
Progress: resolved 1, reused 0, downloaded 1, added 1, done

  System:
    OS: Linux 5.15 Ubuntu 22.04.4 LTS 22.04.4 LTS (Jammy Jellyfish)
    CPU: (32) x64 AMD Ryzen 9 7950X 16-Core Processor
    Memory: 29.64 GB / 30.92 GB
    Container: Yes
    Shell: 5.9 - /home/valentin/.nix-profile/bin/zsh
  Binaries:
    Node: 20.17.0 - /nix/store/gx7a5pkxz2y4nclgwjjqsf7nk651g7vx-nodejs-slim-20.17.0/bin/node
    pnpm: 9.10.0 - /nix/store/8zlqhgw5hbakbk2850wvky9x2vqbsqyw-pnpm-9.10.0/bin/pnpm
    bun: 1.1.20 - ~/.nix-profile/bin/bun
  npmPackages:
    @sveltejs/adapter-static: ^3.0.5 => 3.0.5
    @sveltejs/enhanced-img: ^0.3.8 => 0.3.8
    @sveltejs/kit: ^2.6.0 => 2.6.0
    @sveltejs/vite-plugin-svelte: 4.0.0-next.7 => 4.0.0-next.7
    svelte: 5.0.0-next.205 => 5.0.0-next.205
    vite: ^5.4.8 => 5.4.8
```

### Severity

blocking an upgrade

**Comment by dummdidumm** [comment]
Make sure you're on the latest version of Svelte 5, which knows about this syntax. It's the new way for writing `<script context="module">`

**Comment by beeb** [comment]
Oh my bad! I thought I had updated all the deps but svelte was pinned to next.205. Thanks!
