### ISSUE TITLE
Cannot stringify arbitrary non-POJOs error even with a POJO

### ISSUE THREAD

**Issue by liamwh** [sveltejs/kit#12776]
### Describe the bug

use:enhance with a form action isn't working even though the form action is minimal:

```ts
import { json } from '@sveltejs/kit';
import type { Actions } from './$types';

export const actions: Actions = {
	joinWaitlist: async ({ request }) => {
		const data = await request.formData();
		const email = data.get('email');

		if (!email || typeof email !== 'string') {
			return json({ success: false, message: 'Email is required' });
		}

		return json({ success: true, message: 'test' });
	}
} satisfies Actions;
```

```
Error: Data returned from action inside / is not serializable: Cannot stringify arbitrary non-POJOs
    at try_deserialize (/home/liam/git/svelte-bug-report/node_modules/.pnpm/@sveltejs+kit@2.6.3_@sveltejs+vite-plugin-svelte@4.0.0-next.7_svelte@5.0.0-next.263_vite@5.4._53xaqzfrcdojpv7yx4bdzzoxje/node_modules/@sveltejs/kit/src/runtime/server/page/actions.js:286:10)
    at stringify_action_response (/home/liam/git/svelte-bug-report/node_modules/.pnpm/@sveltejs+kit@2.6.3_@sveltejs+vite-plugin-svelte@4.0.0-next.7_svelte@5.0.0-next.263_vite@5.4._53xaqzfrcdojpv7yx4bdzzoxje/node_modules/@sveltejs/kit/src/runtime/server/page/actions.js:268:9)
    at Module.handle_action_json_request (/home/liam/git/svelte-bug-report/node_modules/.pnpm/@sveltejs+kit@2.6.3_@sveltejs+vite-plugin-svelte@4.0.0-next.7_svelte@5.0.0-next.263_vite@5.4._53xaqzfrcdojpv7yx4bdzzoxje/node_modules/@sveltejs/kit/src/runtime/server/page/actions.js:71:11)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async resolve (/home/liam/git/svelte-bug-report/node_modules/.pnpm/@sveltejs+kit@2.6.3_@sveltejs+vite-plugin-svelte@4.0.0-next.7_svelte@5.0.0-next.263_vite@5.4._53xaqzfrcdojpv7yx4bdzzoxje/node_modules/@sveltejs/kit/src/runtime/server/respond.js:454:18)
    at async Module.respond (/home/liam/git/svelte-bug-report/node_modules/.pnpm/@sveltejs+kit@2.6.3_@sveltejs+vite-plugin-svelte@4.0.0-next.7_svelte@5.0.0-next.263_vite@5.4._53xaqzfrcdojpv7yx4bdzzoxje/node_modules/@sveltejs/kit/src/runtime/server/respond.js:327:20)
    at async file:///home/liam/git/svelte-bug-report/node_modules/.pnpm/@sveltejs+kit@2.6.3_@sveltejs+vite-plugin-svelte@4.0.0-next.7_svelte@5.0.0-next.263_vite@5.4._53xaqzfrcdojpv7yx4bdzzoxje/node_modules/@sveltejs/kit/src/exports/vite/dev/index.js:525:22
```

### Reproduction

Link to minimal example [here](https://github.com/liamwh/svelte-bug-report).

Simply enter data into the form and hit submit. You'll see a 500 in the network tab and server logs.

### System Info

```Shell
System:
    OS: Linux 6.10 Garuda Linux
    CPU: (16) x64 AMD Ryzen 7 3800X 8-Core Processor
    Memory: 39.50 GB / 78.47 GB
    Container: Yes
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 22.3.0 - /home/linuxbrew/.linuxbrew/bin/node
    npm: 10.8.1 - /home/linuxbrew/.linuxbrew/bin/npm
    pnpm: 9.11.0 - /usr/bin/pnpm
  Browsers:
    Brave Browser: 129.1.70.117
    Chromium: 129.0.6668.70
  npmPackages:
    @sveltejs/adapter-auto: ^3.0.0 => 3.2.5 
    @sveltejs/kit: ^2.0.0 => 2.6.3 
    @sveltejs/vite-plugin-svelte: ^4.0.0-next.6 => 4.0.0-next.7 
    svelte: ^5.0.0-next.1 => 5.0.0-next.263 
    vite: ^5.0.3 => 5.4.8
```

### Severity

blocking an upgrade

**Comment by brunnerh** [comment]
`json` is for API endpoints (`+server.js`) and constructs a `Response` with the correct content type. Form actions should just return plain objects directly.

```diff
- import { json } from '@sveltejs/kit';
import type { Actions } from './$types';

export const actions: Actions = {
	joinWaitlist: async ({ request }) => {
		const data = await request.formData();
		const email = data.get('email');

		if (!email || typeof email !== 'string') {
-			return json({ success: false, message: 'Email is required' });
+			return { success: false, message: 'Email is required' };
		}

-		return json({ success: true, message: 'test' });
+		return { success: true, message: 'test' };
	}
} satisfies Actions;
```

**Comment by liamwh** [comment]
Thanks for the clarification, my bad. Is it an idea to include a better error message here in case someone repeats the same mistake I made?

**Comment by brunnerh** [comment]
I opened:
- #12787
