### ISSUE TITLE
Vercel Adapter failing to bundle sveltekit

### ISSUE THREAD

**Issue by DrewRidley** [sveltejs/kit#1281]
**Describe the bug**
A Cloud invocation on vercel indicates that sveltekit is not bundled in the application.

**Logs**
<details>
2021-04-30T04:23:13.209Z	898311b1-cdc5-4d50-9c95-bc29b2c59c4f	ERROR	Unhandled Promise Rejection 	{"errorType":"Runtime.UnhandledPromiseRejection","errorMessage":"Error [ERR_MODULE_NOT_FOUND]: Cannot find package '@sveltejs/kit' imported from /var/task/server/app.mjs","reason":{"errorType":"Error","errorMessage":"Cannot find package '@sveltejs/kit' imported from /var/task/server/app.mjs","code":"ERR_MODULE_NOT_FOUND","stack":["Error [ERR_MODULE_NOT_FOUND]: Cannot find package '@sveltejs/kit' imported from /var/task/server/app.mjs","    at packageResolve (internal/modules/esm/resolve.js:655:9)","    at moduleResolve (internal/modules/esm/resolve.js:696:18)","    at Loader.defaultResolve [as _resolve] (internal/modules/esm/resolve.js:810:11)","    at Loader.resolve (internal/modules/esm/loader.js:86:40)","    at Loader.getModuleJob (internal/modules/esm/loader.js:230:28)","    at ModuleWrap.<anonymous> (internal/modules/esm/module_job.js:56:40)","    at link (internal/modules/esm/module_job.js:55:36)"]},"promise":{},"stack":["Runtime.UnhandledPromiseRejection: Error [ERR_MODULE_NOT_FOUND]: Cannot find package '@sveltejs/kit' imported from /var/task/server/app.mjs","    at process.<anonymous> (/var/runtime/index.js:35:15)","    at process.emit (events.js:327:22)","    at processPromiseRejections (internal/process/promises.js:245:33)","    at processTicksAndRejections (internal/process/task_queues.js:94:32)"]}
Unknown application error occurred
</details>

**To Reproduce**
Not entirely sure but it should be reproducible if you clone https://github.com/DrewRidley/PantryBook and deploy to vercel.

**Expected behavior**
Sveltekit compiles without errors (which it does), but also bundles svelte with the distribution deployed to vercel (which it does not according to the exception)

**Information about your SvelteKit Installation:**
Not sure this information is pertinent to the error since all vercel deployments are the same in terms of hardware?

**Severity**
In this case it blocks the usage of sveltekit entirely, although I suspect if I created a fresh project with identical components it would work.

**Comment by DrewRidley** [comment]
I re-scaffolded the project and copied over all of my components and it no longer reproduces. Works fine now, not really sure what caused it. You are welcome to try to reproduce with older commits of the repository, but i'll close this issue since it was resolved so easily.
