### ISSUE TITLE
Error running SvelteKit application after using the sv CLI and yarn

### ISSUE THREAD

**Issue by MattL-NZ** [sveltejs/kit#12853]
### Describe the bug

I am getting the following error after creating a SvelteKit 5 application for the first time. 

```
error when starting dev server:
Error: Could not resolve peer dependency "@sveltejs/vite-plugin-svelte" relative to your project — please install it and try again.
```

### Reproduction

1. Run `npx sv create`
2. Create folder `svelte-test`
3. Select `SvelteKit minimal`
4. Select `Typescript`
5. Select `Prettier`, `Eslint` and `Tailwindcss`
6. Didn't select any additional Tailwind packages
7. Selected `yarn` as the package manager
8. Cd into the folder and run `yarn run dev`

Throws this error 

error when starting dev server:
Error: Could not resolve peer dependency "@sveltejs/vite-plugin-svelte" relative to your project — please install it and try again.

### Logs

```Shell
error when starting dev server:
Error: Could not resolve peer dependency "@sveltejs/vite-plugin-svelte" relative to your project — please install it and try again.
    at resolve_peer_dependency (file:///Users/mattlist/Developer/Matt/Web/svelte-5-test/.yarn/unplugged/@sveltejs-kit-virtual-3e4c0610cd/node_modules/@sveltejs/kit/src/utils/import.js:16:9)
    at sveltekit (file:///Users/mattlist/Developer/Matt/Web/svelte-5-test/.yarn/unplugged/@sveltejs-kit-virtual-3e4c0610cd/node_modules/@sveltejs/kit/src/exports/vite/index.js:156:27)
    at async Promise.all (index 0)
    at async asyncFlatten (file:///Users/mattlist/Developer/Matt/Web/svelte-5-test/.yarn/__virtual__/vite-virtual-fdb30d3253/5/.yarn/berry/cache/vite-npm-5.4.9-ed2668269d-10c0.zip/node_modules/vite/dist/node/chunks/dep-Cyk9bIUq.js:17501:12)
    at async resolveConfig (file:///Users/mattlist/Developer/Matt/Web/svelte-5-test/.yarn/__virtual__/vite-virtual-fdb30d3253/5/.yarn/berry/cache/vite-npm-5.4.9-ed2668269d-10c0.zip/node_modules/vite/dist/node/chunks/dep-Cyk9bIUq.js:66155:27)
    at async _createServer (file:///Users/mattlist/Developer/Matt/Web/svelte-5-test/.yarn/__virtual__/vite-virtual-fdb30d3253/5/.yarn/berry/cache/vite-npm-5.4.9-ed2668269d-10c0.zip/node_modules/vite/dist/node/chunks/dep-Cyk9bIUq.js:62747:18)
    at async CAC.<anonymous> (file:///Users/mattlist/Developer/Matt/Web/svelte-5-test/.yarn/__virtual__/vite-virtual-fdb30d3253/5/.yarn/berry/cache/vite-npm-5.4.9-ed2668269d-10c0.zip/node_modules/vite/dist/node/cli.js:735:20)
```
```


### System Info

```Shell
Running yarn 4.5.0
Node 20.15.0
```

### Severity

blocking all usage of SvelteKit

### Additional Information

Using `npm` as a package manager instead of `yarn` appears to work so this is possibly an issue with `yarn berry`?

**Comment by Conduitry** [comment]
See https://kit.svelte.dev/docs/faq#how-do-i-use-x-with-sveltekit-does-it-work-with-yarn-2 / https://kit.svelte.dev/docs/faq#how-do-i-use-x-with-sveltekit-how-do-i-use-with-yarn-3
