### ISSUE TITLE
enhanced-img cache is too sticky

### ISSUE THREAD

**Issue by Rich-Harris** [sveltejs/kit#13010]
### Describe the bug

If I have `<enhanced:img alt="..." src="./foo.png">`, and update `foo.png`, the page doesn't update. I have to nuke the cache with `rm -rf node_modules/.vite` and restart the dev server

### Reproduction

later

### System Info

```Shell
latest
```

### Severity

annoyance

**Comment by garikAsplund** [comment]
Hi, I just wanted to chime in and say that I didn't have to nuke the cache--just needed to restart the dev server each time. 

It seems to me in a quick once-over of the enhanced:img package that there isn't any caching or file watching in it per se, and instead it's relying on Vite's built-in features. Perhaps the real problem lay somewhere [in here](https://vite.dev/config/server-options.html#server-watch)?

And a broader question, do you know if there's a roadmap for enhanced:img or what needs to happen before it's production ready?

**Comment by benmccann** [comment]
`enhanced-img` has a cache and I don't know if it's needed anymore since `vite-imagetools` has its own cache now. We should probably just delete the `enhanced-img` one here: https://github.com/sveltejs/kit/blob/ab3784911accefd8d3bc292a80d8e3b825528fd3/packages/enhanced-img/src/vite-plugin.js#L23

I just made some bug fixes and improvements to the `vite-imagetools` caching

**Comment by benmccann** [comment]
Unfortunately this still appears to be an issue after a number of caching improvements in recent releases

**Comment by AbdullahShafqat-OG** [comment]
I ran into a related issue while developing on https://github.com/sveltejs/svelte.dev as well

The following routes failed to render locally:

```
/tutorial/svelte/svelte-window-bindings
/tutorial/svelte/svelte-body
```

Clearing caches did not fix the issue for me I tried both the following:
rm -rf node_modules/.vite
rm -rf node_modules/.cache

Error:
```
[500] GET /tutorial/svelte/svelte-body
Error: Asset does not exist: @imagetools/eaddc3c4715be98b2456c1add92d4dd6f68adb38
    at read (.../node_modules/@sveltejs/kit/src/runtime/app/server/index.js:73:8)
    at get (src/routes/tutorial/[...slug]/content.server.ts:86:19)
    at load_exercise (src/routes/tutorial/[...slug]/content.server.ts:122:18)
    at process.processTicksAndRejections (node:internal/process/task_queues:104:5)
    at async load (src/routes/tutorial/[...slug]/+page.server.ts:11:13)
```

For local workout I fixed it by patching the internal imagetools instance used by enhanced-img to skip /content/ assets:

```
if (enhanced.length > 1) {
    const imagetools = enhanced[1];
    const originalLoad = imagetools.load as Function;

    imagetools.load = function (id: string) {
        if (
            id.includes('/content/') &&
            /\.(avif|gif|heif|jpeg|jpg|png|tiff|webp)(\?.*)?$/.test(id)
        ) {
            return null;
        }
        return originalLoad.call(this, id);
    };
}
```

**Comment by ahkelly** [comment]
Is this the reason I have to generate 2 production builds every release as the first one always produces a blurry version of any new image added, whereas the second fixes it.

**Comment by benmccann** [comment]
There's been lots of caching fixes. f you try the SvelteKit 3 RC and corresponding enhanced-img RC then I think there's a good chance this has been fixed
