### ISSUE TITLE
Cannot npm run build, Error: Could not resolve "@node-rs/argon2-wasm32-wasi"

### ISSUE THREAD

**Issue by joshdstockdale** [sveltejs/kit#13061]
### Describe the bug

Trying to build with adapter-cloudflare but I get the following error: 

> Using @sveltejs/adapter-cloudflare
✘ [ERROR] Could not resolve "@node-rs/argon2-wasm32-wasi"

    node_modules/@node-rs/argon2/browser.js:1:14:
      1 │ export * from '@node-rs/argon2-wasm32-wasi'
        ╵               ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

  You can mark the path "@node-rs/argon2-wasm32-wasi" as external to exclude it from the bundle, which will remove this error and leave the unresolved path in the bundle.

Versions:
"@sveltejs/adapter-auto": "^3.0.0",
"@sveltejs/adapter-cloudflare": "^4.7.4",
"@sveltejs/kit": "^2.0.0",
"@sveltejs/vite-plugin-svelte": "^4.0.0",

I've tried a number of vite.config.ts fixes to mark the package as external but no success: 
```
export default defineConfig({
	plugins: [sveltekit()],
	build: {
		rollupOptions: {
			external: ['@node-rs/argon2-wasm32-wasi']
		}
	},
	ssr: {
		noExternal: ['oslo']
	}
});
```

Also, my svelte.config.js:
```
const config = {
	// Consult https://svelte.dev/docs/kit/integrations
	// for more information about preprocessors
	preprocess: vitePreprocess(),

	kit: {
		// adapter-auto only supports some environments, see https://svelte.dev/docs/kit/adapter-auto for a list.
		// If your environment is not supported, or you settled on a specific environment, switch out the adapter.
		// See https://svelte.dev/docs/kit/adapters for more information about adapters.
		adapter: adapter({
			routes: {
				include: ['/*'],
				exclude: ['<all>']
			},
			platformProxy: {
				environment: undefined,
				experimentalJsonConfig: false,
				persist: false
			}
		}),
		alias: {
			'@/*': './src/lib/*'
		}
	}
};
```

### Reproduction

https://stackblitz.com/edit/sveltejs-kit-template-default-fqgkti

### Logs

```Shell
> Using @sveltejs/adapter-cloudflare
✘ [ERROR] Could not resolve "@node-rs/argon2-wasm32-wasi"

    node_modules/@node-rs/argon2/browser.js:1:14:
      1 │ export * from '@node-rs/argon2-wasm32-wasi'
        ╵               ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

  You can mark the path "@node-rs/argon2-wasm32-wasi" as external to exclude it from the bundle, which will remove this error and leave the unresolved path in the bundle.

error during build:
Error: Bundling with esbuild failed with 1 error
    at adapt (file:///home/stockdale/Sites/deliverys-bane/node_modules/@sveltejs/adapter-cloudflare/index.js:140:11)
    at process.processTicksAndRejections (node:internal/process/task_queues:105:5)
    at async adapt (file:///home/stockdale/Sites/deliverys-bane/node_modules/@sveltejs/kit/src/core/adapt/index.js:38:2)
    at async finalise (file:///home/stockdale/Sites/deliverys-bane/node_modules/@sveltejs/kit/src/exports/vite/index.js:908:7)
    at async Object.handler (file:///home/stockdale/Sites/deliverys-bane/node_modules/@sveltejs/kit/src/exports/vite/index.js:938:5)
    at async PluginDriver.hookParallel (file:///home/stockdale/Sites/deliverys-bane/node_modules/rollup/dist/es/shared/node-entry.js:20734:17)
    at async Object.close (file:///home/stockdale/Sites/deliverys-bane/node_modules/rollup/dist/es/shared/node-entry.js:21712:13)
    at async build (file:///home/stockdale/Sites/deliverys-bane/node_modules/vite/dist/node/chunks/dep-CB_7IfJ-.js:65466:17)
    at async CAC.<anonymous> (file:///home/stockdale/Sites/deliverys-bane/node_modules/vite/dist/node/cli.js:828:5)
```

### System Info

```Shell
This also happens on cloudflare trying to build but here's my system:

  System:
    OS: Linux 6.8 Ubuntu 24.04.1 LTS 24.04.1 LTS (Noble Numbat)
    CPU: (4) x64 Intel(R) Core(TM) i5-3210M CPU @ 2.50GHz
    Memory: 2.94 GB / 9.62 GB
    Container: Yes
    Shell: 5.2.21 - /bin/bash
  Binaries:
    Node: 23.3.0 - /usr/local/bin/node
    npm: 10.9.0 - /usr/local/bin/npm
  Browsers:
    Chrome: 131.0.6778.85
  npmPackages:
    @sveltejs/adapter-auto: ^3.0.0 => 3.3.1 
    @sveltejs/adapter-cloudflare: ^4.7.4 => 4.7.4 
    @sveltejs/kit: ^2.0.0 => 2.8.3 
    @sveltejs/vite-plugin-svelte: ^4.0.0 => 4.0.2 
    svelte: ^5.0.0 => 5.2.7 
    vite: ^5.0.3 => 5.4.11
```

### Severity

annoyance

**Comment by eltigerchino** [comment]
Please provide a minimal reproduction.

**Comment by Devr-pro** [comment]
This a known issue, cloudflare itself doesn't support `wasm` modules, although don't know this can be fixed within sveltekit, would be very nice if so
For now [noble hashes](https://github.com/paulmillr/noble-hashes) have a js implementation which works

**Comment by sepeth** [comment]
> This a known issue, cloudflare itself doesn't support wasm modules, although don't know this can be fixed within sveltekit, would be very nice if so

But it says that it does on this page:

https://developers.cloudflare.com/workers/runtime-apis/webassembly/

> [WebAssembly ↗](https://webassembly.org/) (abbreviated Wasm) allows you to compile languages like [Rust](https://developers.cloudflare.com/workers/languages/rust/), Go, or C to a binary format that can run in a wide variety of environments, including [web browsers ↗](https://developer.mozilla.org/en-US/docs/WebAssembly#browser_compatibility), Cloudflare Workers, and other WebAssembly runtimes.

**Comment by Devr-pro** [comment]
> > This a known issue, cloudflare itself doesn't support wasm modules, although don't know this can be fixed within sveltekit, would be very nice if so
> 
> But it says that it does on this page:
> 
> [developers.cloudflare.com/workers/runtime-apis/webassembly](https://developers.cloudflare.com/workers/runtime-apis/webassembly/)
> 
> > [WebAssembly ↗](https://webassembly.org/) (abbreviated Wasm) allows you to compile languages like [Rust](https://developers.cloudflare.com/workers/languages/rust/), Go, or C to a binary format that can run in a wide variety of environments, including [web browsers ↗](https://developer.mozilla.org/en-US/docs/WebAssembly#browser_compatibility), Cloudflare Workers, and other WebAssembly runtimes.

Oh yes, I read that but whenever I tried to use the argon package, during build it doesn't seem to recognize `wasm` modules and fails it, I don't think that this is a issue within sveltekit itself, previously many people also reported this problem, but there's no fix currently it seems.

**Comment by eltigerchino** [comment]
With https://github.com/sveltejs/kit/pull/13132 merged, this error shouldn't appear. All bundling is delegated to Cloudflare's Wrangler during deployment.

**Comment by anhtuank7c** [comment]
I still faced this issue. I have to switch to `bcryptjs` as an alternative solution.

**Comment by eltigerchino** [comment]
> I still faced this issue. I have to switch to `bcryptjs` as an alternative solution.

Can you expand on the issue that you encountered? Did you use the latest Cloudflare adapter when building and deploying your app?

**Comment by anhtuank7c** [comment]
@eltigerchino I have latest cloudflare adapter, I also enabled the `compatibility_flags = ["nodejs_compat"]`

```
"@sveltejs/adapter-vercel": "^5.5.3",
```

**Comment by eltigerchino** [comment]
> [@eltigerchino](https://github.com/eltigerchino) I have latest cloudflare adapter, I also enabled the `compatibility_flags = ["nodejs_compat"]`
> 
> ```
> "@sveltejs/adapter-cloudflare": "^5.0.3",
> ```
> 
> This issue just happen when I deploy to Cloudflare Pages, I can run the application very well on my local machine (MacOS 5.3.1)

Can you create a minimal reproduction? Does the error happen on build or on deployment?

**Comment by anhtuank7c** [comment]
@eltigerchino sure, I will make a minimal repo to reproduce this issue.

**Comment by tropicbliss** [comment]
Faced the same issue, made my [own version](https://www.npmjs.com/package/argonia) of the @node-rs/argon2 package in the meantime, though I don't think it works with Cloudflare Pages, only Cloudflare Workers for some reason.

**Comment by alexanderniebuhr** [comment]
@tropicbliss I tried your version in a Cloudflare Worker and it worked great. But after I wanted to use it in my Sveltekit Project I get the following errors, any idea?

```
9:37:16 AM [vite] Error when evaluating SSR module /src/lib/auth.ts: failed to import "argonia"
|- TypeError [ERR_UNKNOWN_FILE_EXTENSION]: Unknown file extension ".wasm"
```

**Comment by alexanderniebuhr** [comment]
I found a solution for us, which seems to work during `dev` as well as on Cloudflare production deployments:

```
/**
 * Workaround: Development and production runtimes differ (Node.js vs workerd),
 * requiring different Argon2 libraries. We load @node-rs/argon2 in dev
 * and argonia in prod. Since argonia matches @node-rs/argon2 1:1 API,
 * it’s safe to use them interchangeably.
 */
function loadArgon2Module() {
  if (import.meta.env.DEV) {
    return import("@node-rs/argon2")
  }
  return import('argonia');
}

/**
 * Type guard to determine if the dynamically imported Argon2 library
 * is the production 'argonia' module rather than the development
 * '@node-rs/argon2' module. Both share the same API, but this
 * function lets TypeScript safely narrow the union type at compile
 * time, ensuring correct typings for methods like `verify()`.
 */
function isArgoniaModule(module: any): module is typeof import('argonia') {
  return !import.meta.env.DEV;
}
```

**Comment by skaldebane** [comment]
I get the same issue in with node-adapter. Happened when moving form actions to the new experimental remote functions.

**Comment by teemingc** [comment]
> I get the same issue in with node-adapter. Happened when moving form actions to the new experimental remote functions.

Please create a new issue with a minimal reproduction
