### ISSUE TITLE
`ERR_MODULE_NOT_FOUND` when running sveltekit sync or build with pnpm

### ISSUE THREAD

**Issue by Inglan** [sveltejs/kit#13134]
### Describe the bug

Updating to svelte 5.10.0 causes issues when running sync or build when using pnpm.

### Reproduction

Use pnpm, create a svelte project and run `pnpm exec svelte-kit sync`
https://github.com/Inglan/sveltekit-ERR_MODULE_NOT_FOUND-issue-reproduction

### Logs

```Shell
19:08:18.818	failed to load config from /opt/buildhome/repo/vite.config.ts
19:08:18.819	error during build:
19:08:18.819	Error [ERR_MODULE_NOT_FOUND]: Cannot find module '/opt/buildhome/repo/node_modules/.pnpm/@ampproject+remapping@2.3.0/node_modules/@jridgewell/gen-mapping/dist/gen-mapping.mjs' imported from /opt/buildhome/repo/node_modules/.pnpm/@ampproject+remapping@2.3.0/node_modules/@ampproject/remapping/dist/remapping.mjs
19:08:18.819	    at new NodeError (node:internal/errors:405:5)
19:08:18.819	    at finalizeResolution (node:internal/modules/esm/resolve:324:11)
19:08:18.820	    at moduleResolve (node:internal/modules/esm/resolve:943:10)
19:08:18.820	    at defaultResolve (node:internal/modules/esm/resolve:1129:11)
19:08:18.820	    at nextResolve (node:internal/modules/esm/loader:163:28)
19:08:18.820	    at ESMLoader.resolve (node:internal/modules/esm/loader:835:30)
19:08:18.820	    at ESMLoader.getModuleJob (node:internal/modules/esm/loader:424:18)
19:08:18.820	    at ModuleWrap.<anonymous> (node:internal/modules/esm/module_job:77:40)
19:08:18.821	    at link (node:internal/modules/esm/module_job:76:36)
19:08:18.830	 ELIFECYCLE  Command failed with exit code 1.
19:08:18.857	Failed: Error while executing user command. Exited with error code: 1
19:08:18.866	Failed: build command exited with code: 1
19:08:19.643	Failed: error occurred while running build command
```

### System Info

```Shell
This also occurs when building with cloudflare pages
  System:
    OS: Linux 6.12 Arch Linux
    CPU: (8) x64 Intel(R) Core(TM) i5-8350U CPU @ 1.70GHz
    Memory: 3.15 GB / 7.50 GB
    Container: Yes
    Shell: 3.7.1 - /usr/bin/fish
  Binaries:
    Node: 23.3.0 - /usr/bin/node
    npm: 10.9.2 - /usr/bin/npm
    pnpm: 9.13.2 - /usr/bin/pnpm
    bun: 1.1.38 - /usr/bin/bun
  Browsers:
    Brave Browser: 131.1.73.97
    Chromium: 131.0.6778.108

I am also using zen browser but that is not detected here
```

### Severity

blocking all usage of SvelteKit

**Comment by Inglan** [comment]
Logs when running locally from the start
```
 ~  →  npx sv create test
(node:109348) ExperimentalWarning: CommonJS module /usr/lib/node_modules/npm/node_modules/debug/src/node.js is loading ES Module /usr/lib/node_modules/npm/node_modules/supports-color/index.js using require().
Support for loading ES Module in require() is an experimental feature and might change at any time
(Use `node --trace-warnings ...` to show where the warning was created)
┌  Welcome to the Svelte CLI! (v0.6.6)
│
◇  Which template would you like?
│  SvelteKit minimal
│
◇  Add type checking with Typescript?
│  Yes, using Typescript syntax
│
◆  Project created
│
◇  What would you like to add to your project? (use arrow keys / space bar)
│  none
│
◇  Which package manager do you want to install dependencies with?
│  pnpm
│
◆  Successfully installed dependencies
│
◇  Project next steps ─────────────────────────────────────────────────────╮
│                                                                          │
│  1: cd test                                                              │
│  2: git init && git add -A && git commit -m "Initial commit" (optional)  │
│  3: pnpm dev --open                                                      │
│                                                                          │
│  To close the dev server, hit Ctrl-C                                     │
│                                                                          │
│  Stuck? Visit us at https://svelte.dev/chat                              │
│                                                                          │
├──────────────────────────────────────────────────────────────────────────╯
│
└  You're all set!

 ~  →  cd test
 ~  test  →  npx sv add tailwindcss
(node:109482) ExperimentalWarning: CommonJS module /usr/lib/node_modules/npm/node_modules/debug/src/node.js is loading ES Module /usr/lib/node_modules/npm/node_modules/supports-color/index.js using require().
Support for loading ES Module in require() is an experimental feature and might change at any time
(Use `node --trace-warnings ...` to show where the warning was created)
┌  Welcome to the Svelte CLI! (v0.6.6)
│
◇  Which plugins would you like to add?
│  none
│
◇  Which package manager do you want to install dependencies with?
│  pnpm
│
◆  Successfully setup add-ons
│
◆  Successfully installed dependencies
│
└  You're all set!

 ~  test  →  npx shadcn-svelte@next init

 ┌   shadcn-svelte  v1.0.0-next.4 
│
└  Error: Command failed with exit code 1: pnpm exec svelte-kit sync
> Cannot find module '/home/ingowolf/test/node_modules/.pnpm/@ampproject+remapping@2.3.0/node_modules/@jridgewell/gen-mapping/dist/gen-mapping.mjs' imported from /home/ingowolf/test/node_modules/.pnpm/@ampproject+remapping@2.3.0/node_modules/@ampproject/remapping/dist/remapping.mjs
    at finalizeResolution (node:internal/modules/esm/resolve:275:11)
    at moduleResolve (node:internal/modules/esm/resolve:860:10)
    at defaultResolve (node:internal/modules/esm/resolve:984:11)
    at ModuleLoader.defaultResolve (node:internal/modules/esm/loader:654:12)
    at #cachedDefaultResolve (node:internal/modules/esm/loader:603:25)
    at ModuleLoader.resolve (node:internal/modules/esm/loader:586:38)
    at ModuleLoader.getModuleJobForImport (node:internal/modules/esm/loader:242:38)
    at ModuleJob._link (node:internal/modules/esm/module_job:135:49)
    at makeError (file:///home/ingowolf/.npm/_npx/28febf0521d8db2e/node_modules/execa/lib/error.js:60:11)
    at handlePromise (file:///home/ingowolf/.npm/_npx/28febf0521d8db2e/node_modules/execa/index.js:124:26)
    at process.processTicksAndRejections (node:internal/process/task_queues:105:5)
    at async sn (file:///home/ingowolf/.npm/_npx/28febf0521d8db2e/node_modules/shadcn-svelte/dist/index.js:59:2264)
    at async qs (file:///home/ingowolf/.npm/_npx/28febf0521d8db2e/node_modules/shadcn-svelte/dist/index.js:181:1794)
    at async Command.<anonymous> (file:///home/ingowolf/.npm/_npx/28febf0521d8db2e/node_modules/shadcn-svelte/dist/index.js:181:1177)

 ~  test  1  →  
```

**Comment by bravier** [comment]
The issue doesn't come from SvelteKit but from `@jridgewell/gen-mapping`: https://github.com/jridgewell/gen-mapping/issues/14
