### ISSUE TITLE
error `document is not defined` using `bundleStrategy`'s `single` value

### ISSUE THREAD

**Issue by frederikhors** [sveltejs/kit#13203]
### Describe the bug

Using the new `bundleStrategy` `single` option I get this error:

```
node:internal/event_target:1101
  process.nextTick(() => { throw err; });
                           ^
ReferenceError [Error]: document is not defined
    at file:///C:/project/node_modules/.pnpm/quill@2.0.2/node_modules/quill/core/emitter.js:7:3
    at Array.forEach (<anonymous>)
    at file:///C:/project/node_modules/.pnpm/quill@2.0.2/node_modules/quill/core/emitter.js:6:8
    at ModuleJob.run (node:internal/modules/esm/module_job:271:25)
    at async onImport.tracePromise.__proto__ (node:internal/modules/esm/loader:547:26)
    at async analyse (file:///C:/project/node_modules/.pnpm/@sveltejs+kit@2.13.0_@sveltejs+vite-plugin-svelte@5.0.3_svelte@5.14.5_vite@6.0.4_@types+node@_ojxcsn2yei7eqzdkbuybifgz5y/node_modules/@sveltejs/kit/src/core/postbuild/analyse.js:42:19)
    at async MessagePort.<anonymous> (file:///C:/project/node_modules/.pnpm/@sveltejs+kit@2.13.0_@sveltejs+vite-plugin-svelte@5.0.3_svelte@5.14.5_vite@6.0.4_@types+node@_ojxcsn2yei7eqzdkbuybifgz5y/node_modules/@sveltejs/kit/src/utils/fork.js:23:16)

Node.js v22.12.0
```

using quill js editor in one of my component.

### Reproduction

I'm working on it...

### System Info

```Shell
npmPackages:
    @sveltejs/adapter-static: 3.0.6 => 3.0.6
    @sveltejs/kit: 2.13.0 => 2.13.0
    @sveltejs/vite-plugin-svelte: 5.0.3 => 5.0.3
    svelte: 5.14.5 => 5.14.5
    vite: 6.0.4 => 6.0.4
```

### Severity

blocking all usage of SvelteKit

**Comment by elliott-with-the-longest-name-on-github** [comment]
If you're still having this issue, please create a reproduction:
- `npx sv create my-repro`
- `git init && git add --all && git commit -m "Initial commit"`
- Add the code that minimally illustrates your issue
- `git add --all && git commit -m "Reproduce issue"`
- Create a repository on GutHub and upload your code
- Open a new issue with the reproduction
