### ISSUE TITLE
optimise builds for hash router apps

### ISSUE THREAD

**Issue by Rich-Harris** [sveltejs/kit#13217]
### Describe the problem

If `router.type === 'hash'` we don't need to create a server manifest or bundle routes etc

### Describe the proposed solution

-

### Importance

nice to have

**Comment by gevera** [comment]
Hey, @Rich-Harris 

Sveltekit throws an error on build when using hash router and setting in +layout.ts export const ssr = false;

```bash
node:internal/event_target:1094
  process.nextTick(() => { throw err; });
                           ^
Error: Page options are ignored when `router.type === 'hash'` (src/routes/+layout.ts has 'ssr')
    at analyse (file:///home/nixos/Projects/bobr/tg_quiz_mini_app/client/node_modules/@sveltejs/kit/src/core/postbuild/analyse.js:81:11)
    at async MessagePort.<anonymous> (file:///home/nixos/Projects/bobr/tg_quiz_mini_app/client/node_modules/@sveltejs/kit/src/utils/fork.js:23:16)
Emitted 'error' event on Worker instance at:
    at [kOnErrorMessage] (node:internal/worker:326:10)
    at [kOnMessage] (node:internal/worker:337:37)
    at MessagePort.<anonymous> (node:internal/worker:232:57)
    at [nodejs.internal.kHybridDispatch] (node:internal/event_target:820:20)
    at MessagePort.<anonymous> (node:internal/per_context/messageport:23:28)

Node.js v20.17.0

```

It makes sense we do not need to set the ssr to false since the hash type of the sveltekit router will do it automatically for us.
Besides, the SPA section in the docs don't seem to mention this. 

Should I create another issue regarding this?

**Comment by gevera** [comment]
Also, an intersing thing is that when using hash router, the url searchParams are not detected 
Here is an example

![image](https://github.com/user-attachments/assets/d8fc9a51-2a8e-44b2-b486-4f2c36fbb737)

In my case _$page.url.searchParams.get('question')_ should return **some_question_id**

**Comment by 7nik** [comment]
> Also, an intersing thing is that when using hash router, the url searchParams are not detected

[It was decided](https://github.com/sveltejs/kit/pull/13191#issuecomment-2558123802) that users should use the real search params:
/#/quiz/some_quiz_id?question=some_question_id → /?question=some_question_id#/quiz/some_quiz_id

**Comment by chrisvire** [comment]
@Rich-Harris, @gevera:

I am producing a PWA, so I think I want SSR = false. I want to use hash-based routing since I will be publishing multiple copies of the PWA (based on content in hundreds of minority languages -- each with its own PWA).
https://github.com/sveltejs/kit/issues/7443#issuecomment-2302886802

If I use hash-based routing, is SSR assumed?  I have to remove `export const ssr = false;` from my `/src/routes/+layout.js` file for hash-based routing to work. If I leave it in, I get the error that @gevera got:

```
node:internal/event_target:1083
  process.nextTick(() => { throw err; });
                           ^
Error: Page options are ignored when `router.type === 'hash'` (src/routes/+layout.js has 'ssr')
    at analyse (file:///Users/hubbard/codereview/appbuilder-pwa/node_modules/@sveltejs/kit/src/core/postbuild/analyse.js:81:11)
    at async MessagePort.<anonymous> (file:///Users/hubbard/codereview/appbuilder-pwa/node_modules/@sveltejs/kit/src/utils/fork.js:23:16)
Emitted 'error' event on Worker instance at:
    at [kOnErrorMessage] (node:internal/worker:326:10)
    at [kOnMessage] (node:internal/worker:337:37)
    at MessagePort.<anonymous> (node:internal/worker:232:57)
    at [nodejs.internal.kHybridDispatch] (node:internal/event_target:807:20)
    at exports.emitMessage (node:internal/per_context/messageport:23:28)
```

Shouldn't there be a configuration-based way to specify this (in svelte.config.js)?

**Comment by lumosminima** [comment]
> > Also, an intersing thing is that when using hash router, the url searchParams are not detected
> 
> [It was decided](https://github.com/sveltejs/kit/pull/13191#issuecomment-2558123802) that users should use the real search params: /#/quiz/some_quiz_id?question=some_question_id → /?question=some_question_id#/quiz/some_quiz_id

This feels weird.

```html
Old 🔥
https://ui.home.arpa/spaces/019400fb-6162-71d8-9d7c-e4ee053c8a32/accounts?type=liability&groupBy=tags

New 😅
https://ui.home.arpa/?type=liability&groupBy=tags#/spaces/019400fb-6162-71d8-9d7c-e4ee053c8a32/accounts
```
I use `goto()` for filtering and it broke my previous logic and I had to prepend the query:

```js
goto( `${resolveRoute(`/?${this.query.toString()}#/(app)/spaces/[id]`, { id: spaceId.current })}/accounts`, {
	        replaceState: true,
	        keepFocus: true,
	    }
	);
```
Wouldn't it have been better to add special handling when in hash mode so we didn't have to refactor when moving between hash and standard routing? That way it would have worked in both modes seamlessly. Even if my URL was ugly before due to uuid it still had meaning but now it looses that and feels different from all other URLs on internet. I think both prepended ?query and appended query should work. I can of course handle it on my own but this is precisely why I use frameworks.

**Comment by lumosminima** [comment]
@chrisvire hash-based routing is client side construct and everything is on a single "/" the hash part is not sent to server and routing is done on app level. The error could be worded better but it is simply saying "Your page option is not applicable to the current router mode you are using and is ignored" so just remove it.

**Comment by 7nik** [comment]
@lucrnz but the error says you have `export const ssr = ...` in the root +page which isn't allowed in the hash router.

**Comment by lucrnz** [comment]
> [@lucrnz](https://github.com/lucrnz) but the error says you have `export const ssr = ...` in the root +page which isn't allowed in the hash router.

Oh, I set it to `false` when following the [docs](https://svelte.dev/docs/kit/single-page-apps) for single page apps.

Removing it fixes the issue 👍🏻 

And yes, I read that hash router disables SSR already I just wanted to make sure (write the intention in code).

**Comment by kangruixiang** [comment]
I'm trying to build an electron app with sveltekit. 

In order for the load function to work correctly for client side loading, I have to have the line `export const ssr = false`. Otherwise, the app would not build. However, I have to also use hash routing, in which case I can't use the `export const ssr...` line.
