### ISSUE TITLE
SvelteKitError: Not found: /OneSignalSDKWorker.js

### ISSUE THREAD

**Issue by ryanbuckleyca** [sveltejs/kit#13211]
### Describe the bug

After setting up the tutorial sveltekit installer (choosing bun, typescript), I get the following error when I run `bun run dev`...

```
SvelteKitError: Not found: /OneSignalSDKWorker.js
    at resolve (/my-app/node_modules/@sveltejs/kit/src/runtime/server/respond.js:530:13)
    at resolve (/my-app/node_modules/@sveltejs/kit/src/runtime/server/respond.js:330:5)
    at init_promise.#options.hooks.handle (/my-app/node_modules/@sveltejs/kit/src/runtime/server/index.js:76:56)
    at Module.respond (/my-app/node_modules/@sveltejs/kit/src/runtime/server/respond.js:327:40)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5) {
  status: 404,
  text: 'Not Found'
}
```

### Reproduction

I just ran the set-up from `npx sv create my-app`.
- choose SvelteKit demo
- Yes to Typescript
- check prettier, vitest, playwright, tailwind, storybook
- install all three tailwind plugins
- choose bun for runtime

### Logs

```Shell
SvelteKitError: Not found: /OneSignalSDKWorker.js
    at resolve (/my-app/node_modules/@sveltejs/kit/src/runtime/server/respond.js:530:13)
    at resolve (/my-app/node_modules/@sveltejs/kit/src/runtime/server/respond.js:330:5)
    at init_promise.#options.hooks.handle (/my-app/node_modules/@sveltejs/kit/src/runtime/server/index.js:76:56)
    at Module.respond (/my-app/node_modules/@sveltejs/kit/src/runtime/server/respond.js:327:40)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5) {
  status: 404,
  text: 'Not Found'
}
```

### System Info

```Shell
System:
    OS: macOS 14.5
    CPU: (8) x64 Intel(R) Core(TM) i5-1038NG7 CPU @ 2.00GHz
    Memory: 706.98 MB / 16.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 21.1.0 - ~/.nvm/versions/node/v21.1.0/bin/node
    Yarn: 1.22.19 - /usr/local/bin/yarn
    npm: 10.2.0 - ~/.nvm/versions/node/v21.1.0/bin/npm
    bun: 1.1.21 - ~/.bun/bin/bun
  Browsers:
    Brave Browser: 131.1.73.91
    Chrome: 131.0.6778.205
    Safari: 17.5
  npmPackages:
    @sveltejs/adapter-auto: ^3.0.0 => 3.3.1 
    @sveltejs/kit: ^2.0.0 => 2.13.0 
    @sveltejs/vite-plugin-svelte: ^4.0.0 => 4.0.4 
    svelte: ^5.0.0 => 5.15.0 
    vite: ^5.4.11 => 5.4.11
```

### Severity

annoyance

**Comment by Conduitry** [comment]
You presumably have an old service worker installed from another app on the same origin that's requesting this.
