### ISSUE TITLE
Path handling during build with adapter-static

### ISSUE THREAD

**Issue by mvolfik** [sveltejs/kit#1329]
**Describe the bug**
Magic happens. Build fails with weird 404 when `paths: { base: "/" }` and there's `<a href="/">`, and creates a directory `buildfavicon.ico` instead of nonexistent file `build/favicon.ico`.

<details>
<summary><b>Logs</b></summary>

```
yarn run v1.22.10
warning package.json: No license field
$ svelte-kit build
vite v2.2.4 building for production...
✓ 14 modules transformed.
.svelte/output/client/_app/manifest.json                    1.18kb
.svelte/output/client/_app/pages/index.svelte-31924b7e.js   0.41kb / brotli: 0.26kb
.svelte/output/client/_app/layout.svelte-f07a7e7f.js        0.49kb / brotli: 0.29kb
.svelte/output/client/_app/assets/start-a8cd1609.css        0.16kb / brotli: 0.10kb
.svelte/output/client/_app/error.svelte-6645eba8.js         1.19kb / brotli: 0.57kb
.svelte/output/client/_app/chunks/vendor-43cd886a.js        5.05kb / brotli: 1.98kb
.svelte/output/client/_app/start-fec3b019.js                16.00kb / brotli: 5.12kb
vite v2.2.4 building SSR bundle for production...
✓ 9 modules transformed.
.svelte/output/server/app.js   8.86kb

Run npm run preview to preview your production build locally.

> Using @sveltejs/adapter-static
> 404  (linked from /)
Error: 404  (linked from /)
    at error (file:///tmp/test/node_modules/@sveltejs/kit/dist/chunks/index5.js:92:11)
    at visit (file:///tmp/test/node_modules/@sveltejs/kit/dist/chunks/index5.js:159:5)
    at async visit (file:///tmp/test/node_modules/@sveltejs/kit/dist/chunks/index5.js:219:6)
    at async prerender (file:///tmp/test/node_modules/@sveltejs/kit/dist/chunks/index5.js:228:5)
    at async Object.prerender (file:///tmp/test/node_modules/@sveltejs/kit/dist/chunks/index5.js:295:5)
    at async adapt (/tmp/test/node_modules/@sveltejs/adapter-static/index.cjs:10:4)
    at async adapt (file:///tmp/test/node_modules/@sveltejs/kit/dist/chunks/index5.js:321:2)
    at async file:///tmp/test/node_modules/@sveltejs/kit/dist/cli.js:590:5
error Command failed with exit code 1.
```
</details>

**To Reproduce**
```sh
$ npm init svelte@next test # create-svelte version 2.0.0-next.64, choose skeleton, no, no, no
$ cd test
$ yarn add -D @sveltejs/adapter-static@next # @next doesn't work, have to edit package.json manually then `yarn` to sync
$ cat > svelte.config.cjs
module.exports = {
  kit: {
    target: "#svelte",
    paths: { base: "/" },
    adapter: require("@sveltejs/adapter-static")(),
  },
};
$ yarn build # fails, HOWEVER: dir buildfavicon.ico/ is created !
$ # now remove favicon link from src/app.html
$ yarn build # builds ok
$ cat > src/routes/index.svelte
<a href="/">home</a>
$ yarn build # the error above
```

**Expected behavior**
Build correctly, application should assume that everything is served at `/`

**Information about your SvelteKit Installation:**

<details>
  <summary>Diagnostics</summary>

`npx envinfo --system --npmPackages svelte,@sveltejs/kit,vite,@sveltejs/adapter-static --binaries --browsers`

```
  System:
    OS: Linux 5.4 Ubuntu 20.04.2 LTS (Focal Fossa)
    CPU: (4) x64 Intel(R) Core(TM) i3-3110M CPU @ 2.40GHz
    Memory: 291.48 MB / 7.35 GB
    Container: Yes
    Shell: 3.1.0 - /usr/bin/fish
  Binaries:
    Node: 14.16.0 - ~/.local/bin/node
    Yarn: 1.22.10 - ~/.local/bin/yarn
    npm: 7.6.3 - ~/.local/bin/npm
  Browsers:
    Chromium: 90.0.4430.93
    Firefox: 88.0
  npmPackages:
    @sveltejs/adapter-static: next => 1.0.0-next.7 
    @sveltejs/kit: next => 1.0.0-next.96 
    svelte: ^3.34.0 => 3.38.2 
    vite: ^2.2.3 => 2.2.4 
```

</details>

**Severity**
After removing the `paths` config key everything works correctly, but [docs say](https://kit.svelte.dev/docs#configuration-paths) that `base` should be root-relative, but the default actually isn't (`''` [from docs](https://kit.svelte.dev/docs#configuration), idk where to look into code). So this is quite a bad footgun.

**Comment by mvolfik** [comment]
Yes, it succeeds in that case - but see the commends in reproduction commands, that's not the point of the bug report.

Also here is update for `create-svelte version 2.0.0-next.69`

`svelte.config.js`

```js
import adapter from "@sveltejs/adapter-static";

const config = {
  kit: {
    target: '#svelte',
    paths: { base: "/" },
    adapter: adapter(),
  }
};

export default config;
```

<details>
<summary>Output after the last step in reproduction</summary>

```
yarn run v1.22.10
warning package.json: No license field
$ svelte-kit build
vite v2.2.4 building for production...
✓ 14 modules transformed.
.svelte-kit/output/client/_app/manifest.json                    1.21kb
.svelte-kit/output/client/_app/pages/index.svelte-31924b7e.js   0.41kb / brotli: 0.26kb
.svelte-kit/output/client/_app/layout.svelte-904f1151.js        0.49kb / brotli: 0.29kb
.svelte-kit/output/client/_app/error.svelte-ec464882.js         1.19kb / brotli: 0.57kb
.svelte-kit/output/client/_app/assets/start-a8cd1609.css        0.16kb / brotli: 0.10kb
.svelte-kit/output/client/_app/chunks/vendor-43cd886a.js        5.05kb / brotli: 1.98kb
.svelte-kit/output/client/_app/start-7eac52b3.js                16.52kb / brotli: 5.24kb
vite v2.2.4 building SSR bundle for production...
✓ 9 modules transformed.
.svelte-kit/output/server/app.js   8.84kb

Run npm run preview to preview your production build locally.

> Using @sveltejs/adapter-static
> 404  (linked from /)
Error: 404  (linked from /)
    at error (file:///tmp/test/node_modules/@sveltejs/kit/dist/chunks/index5.js:93:11)
    at visit (file:///tmp/test/node_modules/@sveltejs/kit/dist/chunks/index5.js:160:5)
    at async visit (file:///tmp/test/node_modules/@sveltejs/kit/dist/chunks/index5.js:220:6)
    at async prerender (file:///tmp/test/node_modules/@sveltejs/kit/dist/chunks/index5.js:229:5)
    at async Object.prerender (file:///tmp/test/node_modules/@sveltejs/kit/dist/chunks/index5.js:296:5)
    at async adapt (file:///tmp/test/node_modules/@sveltejs/adapter-static/index.js:17:4)
    at async adapt (file:///tmp/test/node_modules/@sveltejs/kit/dist/chunks/index5.js:322:2)
    at async file:///tmp/test/node_modules/@sveltejs/kit/dist/cli.js:592:5
error Command failed with exit code 1.
```

</details>

Deps:

```
  npmPackages:
    @sveltejs/adapter-static: next => 1.0.0-next.8 
    @sveltejs/kit: next => 1.0.0-next.101 
    svelte: ^3.34.0 => 3.38.2 
    vite: ^2.2.3 => 2.2.4 
```

**Comment by jakemoves** [comment]
Didn’t mean to steer this in the wrong direction, was just trying to substantiate the issue :)

**Comment by triptych** [comment]
Thanks for the comment - it helps to unblock folks who are just trying to get the current builder to work.

**Comment by teds31** [comment]
Is there any resolution to this? I am experiencing the same issue with my blog using Prismic's API. It happens randomly and there were some cases were I was getting /blog/blog/blog/test-post
`> 404 /blog/blog/test-post (linked from /blog/test-post)`

**Comment by tw1t611** [comment]
For me, the error only occures, when `load()` returns a `404` and `__error.svelte` exists.
Therefor you can work around this, by returning `200`. In case of a graphql api, you can just remove the `404` response.
This doesn't fix the problem itself and you would need to show the `404 page content` if `props` are not set.

In my case, I removed this from  `load()`
```js
    return {
      status: 404,
      error: new Error(`Not found.`),
    }
```

On a REST api, that should work, can't test it though

```js
  return {
      status: 200,
      props
    };
```

**Comment by hperrin** [comment]
It seems I'm running into the same issue when setting base path to anything. I currently have it set to '/sciactive-site', and the build fails with a 404 looking for favicon.png, which is there.

**Comment by hperrin** [comment]
I was able to solve my issue by creating a symlink "_svelte_kit_assets" directed to the "docs" folder that becomes my GitHub pages site.

**Comment by Ghirigoro** [comment]
I'm experiencing something similar to @hperrin. If I set my base path assets can no longer be resolved (not just favicon - anything that was in my `static` folder).

**Comment by locriacyber** [comment]
Related to #2719. I think the default option (empty string) should be that all paths are relative. This makes hosting website non-root of a domain (like on Github Pages) easier.

**Comment by locriacyber** [comment]
This has to do with vite. When I set ".kit.paths.assets" to `.` and disable the check on the path, `./_app/` is passed to the as configuration, then to the function below in vite: 

```
/**
 * Resolve base. Note that some users use Vite to build for non-web targets like
 * electron or expects to deploy
 */
function resolveBaseUrl(base = '/', isBuild, logger) {
    // #1669 special treatment for empty for same dir relative base
    if (base === '' || base === './') {
        return isBuild ? base : '/';
    }
    if (base.startsWith('.')) {
        logger.warn(source.yellow.bold(`(!) invalid "base" option: ${base}. The value can only be an absolute ` +
            `URL, ./, or an empty string.`));
        base = '/';
    }
    // external URL
    if (isExternalUrl(base)) {
        if (!isBuild) {
            // get base from full url during dev
            const parsed = require$$0$6.parse(base);
            base = parsed.pathname || '/';
        }
    }
    else {
        // ensure leading slash
        if (!base.startsWith('/')) {
            logger.warn(source.yellow.bold(`(!) "base" option should start with a slash.`));
            base = '/' + base;
        }
    }
    // ensure ending slash
    if (!base.endsWith('/')) {
        logger.warn(source.yellow.bold(`(!) "base" option should end with a slash.`));
        base += '/';
    }
    return base;
}
```

**Comment by thedanielenavarra** [comment]
> 

Hi, I'm facing this issue too
I tried to build the project with this **svelte.config.js**:

```
import preprocess from 'svelte-preprocess';
import adapter from '@sveltejs/adapter-static';

/** @type {import('@sveltejs/kit').Config} */
const config = {
	preprocess: preprocess(),
	kit: {
		adapter: adapter({
			fallback: "index.html",
			path: {assets: ".", base: "/base"}
		})
	}
};

export default config;
```
But still all the sources of "index.html" refer to the absolute path "/_app/..."

What do you mean by:
 

> disable the check on the path?

And plus: where is the vite file you quoted located?

Thanks in advance for your help

**Comment by thedanielenavarra** [comment]
Ok, for those that will face this issue:

I figured out that if you set "paths" as **config.kit.paths** instead of **config.kit.adapter.paths** the actual sources in the rendered HTML page get updated when you build the project

import preprocess from 'svelte-preprocess';
import adapter from '@sveltejs/adapter-static';

```
/** @type {import('@sveltejs/kit').Config} */
const config = {
	preprocess: preprocess(),
	kit: {
		//		HERE:		//
		paths: {assets: "", base: "/sirar2"},

		adapter: adapter({
			fallback: "index.html",

			//		NOT HERE:		//
			//path: {assets: ".", base: "/base"}
		})
	}
};

export default config;
```

**Comment by Rich-Harris** [comment]
In the current version, `base: '/'` will fail with an error:

> config.kit.paths.base option must be a root-relative path that starts but doesn't end with '/'. See https://kit.svelte.dev/docs/configuration#paths

Opened #4713 to clarify that, but I'll close this first since `/` is already disallowed.

There's a lot of other noise in this thread — if there are other issues beyond the OP they'll need to be opened separately
