### ISSUE TITLE
vercel adapter build fail ERR_PACKAGE_PATH_NOT_EXPORTED

### ISSUE THREAD

**Issue by Wolfi-evo** [sveltejs/kit#1340]
From today on all my build are failing. Even rebuilds of previous successfull builds fail. 

10:27:19.775 | Error [ERR_PACKAGE_PATH_NOT_EXPORTED]: No "exports" main defined in /vercel/path0/node_modules/@sveltejs/adapter-vercel/package.json
-- | --
10:27:19.775 | at throwExportsNotFound (internal/modules/esm/resolve.js:290:9)
10:27:19.776 | at packageExportsResolve (internal/modules/esm/resolve.js:479:7)
10:27:19.776 | at resolveExports (internal/modules/cjs/loader.js:432:36)
10:27:19.776 | at Function.Module._findPath (internal/modules/cjs/loader.js:472:31)
10:27:19.776 | at Function.Module._resolveFilename (internal/modules/cjs/loader.js:867:27)
10:27:19.776 | at Function.Module._load (internal/modules/cjs/loader.js:725:27)
10:27:19.776 | at Module.require (internal/modules/cjs/loader.js:952:19)
10:27:19.776 | at require (internal/modules/cjs/helpers.js:88:18)
10:27:19.776 | at Object.<anonymous> (/vercel/path0/svelte.config.cjs:3:16)
10:27:19.776 | at Module._compile (internal/modules/cjs/loader.js:1063:30)

**Comment by Wolfi-evo** [comment]
had to change the svelte.config.cjs to svelte.config.js
