### ISSUE TITLE
[vite] Error when evaluating SSR module

### ISSUE THREAD

**Issue by chaosprint** [sveltejs/kit#1352]
**To Reproduce**
`npm init svelte@next svcmtest`
`cd svcmtest`
`npm i`
`npm i codemirror`

```
<script>
    import CodeMirror from 'codemirror';
</script>

<h1>Welcome to SvelteKit</h1>
<p>Visit <a href="https://kit.svelte.dev">kit.svelte.dev</a> to read the documentation</p>
```

Got the error:
```
8:03:19 AM [vite] hmr update /src/routes/index.svelte
8:03:19 AM [vite] new dependencies found: codemirror, updating...
8:03:19 AM [vite] ✨ dependencies updated, reloading page...
8:03:19 AM [vite] Error when evaluating SSR module C:\Users\chaosprint\dev\svcmtest\src\routes\index.svelte:     
ReferenceError: navigator is not defined
    at C:\Users\chaosprint\dev\svcmtest\node_modules\codemirror\lib\codemirror.js:18:19
    at C:\Users\chaosprint\dev\svcmtest\node_modules\codemirror\lib\codemirror.js:11:83
    at Object.<anonymous> (C:\Users\chaosprint\dev\svcmtest\node_modules\codemirror\lib\codemirror.js:14:2)      
    at Module._compile (internal/modules/cjs/loader.js:1015:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1035:10)
    at Module.load (internal/modules/cjs/loader.js:879:32)
    at Function.Module._load (internal/modules/cjs/loader.js:724:14)
    at Module.require (internal/modules/cjs/loader.js:903:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at nodeRequire (C:\Users\chaosprint\dev\svcmtest\node_modules\vite\dist\node\chunks\dep-2c03f3f9.js:69080:17)
navigator is not defined
ReferenceError: navigator is not defined
    at C:\Users\chaosprint\dev\svcmtest\node_modules\codemirror\lib\codemirror.js:18:19
    at C:\Users\chaosprint\dev\svcmtest\node_modules\codemirror\lib\codemirror.js:11:83
    at Object.<anonymous> (C:\Users\chaosprint\dev\svcmtest\node_modules\codemirror\lib\codemirror.js:14:2)
    at Module._compile (internal/modules/cjs/loader.js:1015:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1035:10)
    at Module.load (internal/modules/cjs/loader.js:879:32)
    at Function.Module._load (internal/modules/cjs/loader.js:724:14)
    at Module.require (internal/modules/cjs/loader.js:903:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at nodeRequire (C:\Users\chaosprint\dev\svcmtest\node_modules\vite\dist\node\chunks\dep-2c03f3f9.js:69080:17)
```

**Comment by chaosprint** [comment]
I guess it is the node issue. Navigator does not exist in node.

But wouldn't it be better if `npm init svelte@next` give us an option to select? There are already several selections to make.

**Comment by chaosprint** [comment]
change the config to
```
/** @type {import('@sveltejs/kit').Config} */

import adapter from '@sveltejs/adapter-static';
const config = {
	kit: {
		// hydrate the <div id="svelte"> element in src/app.html
		target: '#svelte',
		adapter: adapter({
			// default options are shown
			pages: 'build',
			assets: 'build',
			fallback: 'app.html'
		}),
		ssr: false
	}
};

export default config;
```
The index shows now, but the error retains

**Comment by Conduitry** [comment]
If CodeMirror tries to use browser-only APIs, you need to make sure that it is only run on the browser.

**Comment by Drishtianand19** [comment]
Facing the same error but i don't have svelte. So how can I resolve that?
