### ISSUE TITLE
Previously closed issue is back now with kit 1.0.0-next.102 / svelte 3.38.2

### ISSUE THREAD

**Issue by lgs** [sveltejs/kit#1387]
**Describe the bug**
TypeError: Cannot read property 'message' of undefined at __error.svelte:10:96

**Logs**
<details>
  <summary>Browser console error log</summary>

```
GEThttp://localhost:3000/account.html
[HTTP/1.1 500 Internal Server Error 74ms]

The character encoding of the HTML document was not declared. The document will render with garbled text in some browser configurations if the document contains characters from outside the US-ASCII range. The character encoding of the page must be declared in the document or in the transfer protocol.

```
</details>

**To Reproduce**
<details>
  <summary>The offending code is the following src/route/account.svelte component:</summary>

```
<svelte:head>
  <title>Account</title>
  <script src="https://js.stripe.com/v3/"></script>
  <script src="../client/account.js" defer></script>
</svelte:head>

<section class="text-gray-400 bg-gray-900 body-font">
  <div class="container px-5 py-24 mx-auto flex flex-wrap items-center">
    <div class="bg-gray-800 bg-opacity-50 rounded-lg p-8 flex flex-col">
      <h1>Account</h1>
      <a href="prices">Add a subscription</a>
      <a href="register">Restart demo</a>
      <h2>Subscriptions</h2>
      <div id="subscriptions">
        <!-- see account.js to see how this div is populated -->
      </div>
    </div>
  </div>
</section>
```

</details>

<details>
  <summary>which is calling the following ../client/account.js file:</summary>

```
document.addEventListener('DOMContentLoaded', async () => {
  // Fetch the list of subscriptions for this customer.
  const {subscriptions} = await fetch('/subscriptions').then((r) => r.json());

  // Construct and display each subscription, its status, last4 of the card
  // used, and the current period end.
  const subscriptionsDiv = document.querySelector('#subscriptions');
  subscriptionsDiv.innerHTML = subscriptions.data.map((subscription) => {
    return `
      <hr>
      <h4>
        <a href="https://dashboard.stripe.com/test/subscriptions/${subscription.id}">
          ${subscription.id}
        </a>
      </h4>

      <p>
        Status: ${subscription.status}
      </p>

      <p>
        Card last4: ${subscription.default_payment_method.card.last4}
      </p>

      <p>
        Current period end: ${new Date(subscription.current_period_end * 1000)}
      </p>

      <!--<a href="change-payment-method.html?subscription=${subscription.id}"> Update payment method </a><br />
      <a href="change-plan.html?subscription=${subscription.id}"> Change plan </a><br /> -->
      <a href="cancel.html?subscription=${subscription.id}"> Cancel </a><br />
    `;
  }).join('<br />');
});

```
</details>

 **UPDATE:** I get a way to reproduce this easily

I moked up a src/route/account.svelte component as a bar minimum HTML page without external JS file calling, like the following: 
```
<svelte:head>
    <title>Account Moke Up</title>
    <script src="https://js.stripe.com/v3/"></script>
</svelte:head>

<section>
    <h1> Account Moke Up </h1>
</section>
```
and I get the same error, but when I move ```<script src="https://js.stripe.com/v3/"></script>``` outside ```<svelte:head></svelte:head>``` everything works fine. 

Here the working code:
```
<svelte:head>
    <title>Account Moke Up</title>
</svelte:head>

<section>
    <h1> Account Moke Up </h1>
</section>

<script src="https://js.stripe.com/v3/"></script>
```

**Expected behavior**
Having more clear and expressive error for better debugging

**Stacktraces**

<details>
  <summary>Stack trace</summary>

```
TypeError: Cannot read property 'message' of undefined
    at __error.svelte:10:96
    at Object.$$render (/home/basenode/Svelte/svelte-kit-boot/node_modules/svelte/internal/index.js:1380:22)
    at Object.default (root.svelte:38:46)
    at eval (/home/basenode/Svelte/svelte-kit-boot/src/routes/__layout.svelte:20:32)
    at Object.$$render (/home/basenode/Svelte/svelte-kit-boot/node_modules/svelte/internal/index.js:1380:22)
    at root.svelte:36:44
    at $$render (/home/basenode/Svelte/svelte-kit-boot/node_modules/svelte/internal/index.js:1380:22)
    at Object.render (/home/basenode/Svelte/svelte-kit-boot/node_modules/svelte/internal/index.js:1388:26)
    at render_response (file:///home/basenode/Svelte/svelte-kit-boot/node_modules/@sveltejs/kit/dist/ssr.js:363:28)
    at async respond_with_error (file:///home/basenode/Svelte/svelte-kit-boot/node_modules/@sveltejs/kit/dist/ssr.js:908:10)

```
</details>

**Information about SvelteKit Installation:**

<details>
  <summary>Diagnostics</summary>

```
$ npx envinfo --system --npmPackages svelte,@sveltejs/kit,vite --binaries --browser
npx: installed 1 in 1.195s

  System:
    OS: Linux 5.8 Ubuntu 20.10 (Groovy Gorilla)
    CPU: (4) x64 Intel(R) Core(TM) i5-3320M CPU @ 2.60GHz
    Memory: 1.99 GB / 7.48 GB
    Container: Yes
    Shell: 5.0.17 - /bin/bash
  Binaries:
    Node: 14.16.1 - /usr/bin/node
    npm: 6.14.12 - /usr/bin/npm
  npmPackages:
    @sveltejs/kit: ^1.0.0-next.102 => 1.0.0-next.102 
    svelte: ^3.38.2 => 3.38.2 
    vite: ^2.2.4 => 2.2.4 

```

</details>

**Severity**
It makes it harder to debug SvelteKit projects and less enjoyable programming experience.

**Additional context**
...

**Comment by Conduitry** [comment]
Do you have a complete repro that can be cloned to see this?

**Comment by lgs** [comment]
the full work has Sripe private keys and a subscription workflow. It's tricky to moke it up like a "stand alone" outside chain of components ...

**Comment by lgs** [comment]
@Conduitry **UPDATE:** I get a way to reproduce this easily (added UPDATE in the previous bug report)

**Comment by Rich-Harris** [comment]
Sorry, not seeing anything like what you describe when I follow those repro instructions. You're going to need to put an [SSCCE](http://sscce.org/) in a repo

**Comment by lgs** [comment]
I cannot replicate on fresh installation sorry, this is probably due to me cluttering my env ? For example after updating @sveltejs/kit, postcss, tailwindcss, cssnano ... a bunch of times since I started and also moving and tuning svelte.config.cjs to svelte.config.js for ssr ...

I usually updated like this:
```
    rm package-lock.json
    npm cache clean --force
    npm update

```
Is that the proper way to keep up with "@sveltejs/kit": "next" and all my tailwindcss and css processors ? 

Fell free to close this down if it is not helpful, by my side I will probably start from scratch with a new svelte kit installation and moving one component at the time ... Suggestion?

**Comment by lgs** [comment]
Fixed now, see my previous update
