### ISSUE TITLE
@sveltejs/adapter-static: copyfile favicon.ico not permitted (npm run build)

### ISSUE THREAD

**Issue by Zerotask** [sveltejs/kit#1448]
**Describe the bug**
I developed an app and it worked with npm run dev. If I try to build it with npm run build, I get the error:
`EPERM: operation not permitted, copyfile 'C:\Users\Patrick\dev\internal\rust-jungle\static\favicon.ico' -> 'build\favicon.ico'`

I also tried running a terminal with admin permissions, but it results in the same error.

**Logs**
Please include browser console and server logs around the time this bug occurred.

**To Reproduce**
Create a new SvelteKit project, use the adapter-static, replace the favicon and try a npm run build.

**Expected behavior**
build succeeds without any errors.

**Stacktraces**
If you have a stack trace to include, we recommend putting inside a `<details>` block for the sake of the thread's readability:

<details>
  <summary>EPERM: operation not permitted, copyfile 'C:\Users\Patrick\dev\internal\rust-jungle\static\favicon.ico' -> 'build\favicon.ico'</summary>

```
> Using @sveltejs/adapter-static
> EPERM: operation not permitted, copyfile 'C:\Users\Patrick\dev\internal\rust-jungle\static\favicon.ico' -> 'build\favicon.ico'
Error: EPERM: operation not permitted, copyfile 'C:\Users\Patrick\dev\internal\rust-jungle\static\favicon.ico' -> 'build\favicon.ico'
    at Object.copyFileSync (node:fs:2797:3)
    at copy (file:///C:/Users/Patrick/dev/internal/rust-jungle/node_modules/@sveltejs/kit/dist/chunks/utils.js:39:15)
    at file:///C:/Users/Patrick/dev/internal/rust-jungle/node_modules/@sveltejs/kit/dist/chunks/utils.js:35:18
    at Array.forEach (<anonymous>)
    at copy (file:///C:/Users/Patrick/dev/internal/rust-jungle/node_modules/@sveltejs/kit/dist/chunks/utils.js:34:33)
    at Object.copy_static_files (file:///C:/Users/Patrick/dev/internal/rust-jungle/node_modules/@sveltejs/kit/dist/chunks/index5.js:290:4)
    at adapt (file:///C:/Users/Patrick/dev/internal/rust-jungle/node_modules/@sveltejs/adapter-static/index.js:14:10)
    at adapt (file:///C:/Users/Patrick/dev/internal/rust-jungle/node_modules/@sveltejs/kit/dist/chunks/index5.js:322:8)
    at file:///C:/Users/Patrick/dev/internal/rust-jungle/node_modules/@sveltejs/kit/dist/cli.js:616:11
```
</details>

**Information about your SvelteKit Installation:**

<details>
  <summary>Diagnostics</summary>

System:
    OS: Windows 10 10.0.19043
    CPU: (4) x64 Intel(R) Core(TM) i5-6500 CPU @ 3.20GHz
    Memory: 8.66 GB / 15.96 GB
  Binaries:
    Node: 16.1.0 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.10 - ~\AppData\Roaming\npm\yarn.CMD
    npm: 7.5.2 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Edge: Spartan (44.19041.964.0), Chromium (90.0.818.62)

- Your adapter (e.g. Node, static, Vercel, Begin, etc...): @sveltejs/adapter-static
</details>

**Comment by AsyncBanana** [comment]
I am having the same issue with adapter-static and favicons

**Comment by AsyncBanana** [comment]
I figured out the issue. I was including my static folder in my non static source folder, so it was being copied over twice. Hope this helps anyone else with this problem.

**Comment by madeleineostoja** [comment]
I get this issue when I try to set a custom `pages` dir, if I leave it as the deafult (`build`) it seems to work

**Comment by coder82** [comment]
I am having this issue as well with the latest version at current date (1.0.0-next.11).


```
λ npm run build                                                                             
                                                                                            
> ~TODO~@0.0.1 build                                                                        
> svelte-kit build                                                                          
                                                                                            
vite v2.3.4 building for production...                                                      
✓ 14 modules transformed.                                                                   
.svelte-kit/output/client/_app/manifest.json                    1.21kb                      
.svelte-kit/output/client/_app/layout.svelte-e1ebf6cd.js        0.49kb / brotli: 0.29kb     
.svelte-kit/output/client/_app/pages/index.svelte-ee768956.js   0.79kb / brotli: 0.42kb     
.svelte-kit/output/client/_app/error.svelte-08ac55d8.js         1.19kb / brotli: 0.57kb     
.svelte-kit/output/client/_app/assets/start-a8cd1609.css        0.16kb / brotli: 0.10kb     
.svelte-kit/output/client/_app/chunks/vendor-43cd886a.js        5.05kb / brotli: 1.98kb     
.svelte-kit/output/client/_app/start-4f7ba9f8.js                17.16kb / brotli: 5.49kb    
vite v2.3.4 building SSR bundle for production...                                           
✓ 9 modules transformed.                                                                    
.svelte-kit/output/server/app.js   8.88kb                                                   
                                                                                            
Run npm run preview to preview your production build locally.                               
                                                                                            
> Using @sveltejs/adapter-static                                                            
> 404 /favicon.ico (linked from /)                                                          
Error: 404 /favicon.ico (linked from /)                                                     
```

**Comment by C0ZEN** [comment]
FYI I had the same issue because:
- I build without a favicon
- I added one and rebuild
- Faced the issue due to the favicon folder
- I deleted the build folder and the rebuild and the issue is gone

**Comment by ignatiusmb** [comment]
The static adapter now clears output directory before building, which should solve this issue.

**Comment by Lucas-Pichette** [comment]
Getting the same issue:

```
Run npm run preview to preview your production build locally.

> Using @sveltejs/adapter-static
> 404 /favicon.ico (linked from /)
Error: 404 /favicon.ico (linked from /)
    at file:///C:/Users/Lucas%20Pichette/Desktop/Projects/websites/3.CodeFox-ClientWebsites/lolomcdart/svelteproject/lolomcdart/node_modules/@sveltejs/kit/dist/chunks/index4.js:86:11        
    at visit (file:///C:/Users/Lucas%20Pichette/Desktop/Projects/websites/3.CodeFox-ClientWebsites/lolomcdart/svelteproject/lolomcdart/node_modules/@sveltejs/kit/dist/chunks/index4.js:222:5)    at async visit (file:///C:/Users/Lucas%20Pichette/Desktop/Projects/websites/3.CodeFox-ClientWebsites/lolomcdart/svelteproject/lolomcdart/node_modules/@sveltejs/kit/dist/chunks/index4.js:293:6)
    at async prerender (file:///C:/Users/Lucas%20Pichette/Desktop/Projects/websites/3.CodeFox-ClientWebsites/lolomcdart/svelteproject/lolomcdart/node_modules/@sveltejs/kit/dist/chunks/index4.js:303:6)
    at async Object.prerender (file:///C:/Users/Lucas%20Pichette/Desktop/Projects/websites/3.CodeFox-ClientWebsites/lolomcdart/svelteproject/lolomcdart/node_modules/@sveltejs/kit/dist/chunks/index4.js:368:4)
    at async adapt (file:///C:/Users/Lucas%20Pichette/Desktop/Projects/websites/3.CodeFox-ClientWebsites/lolomcdart/svelteproject/lolomcdart/node_modules/@sveltejs/adapter-static/index.js:13:4)
    at async adapt (file:///C:/Users/Lucas%20Pichette/Desktop/Projects/websites/3.CodeFox-ClientWebsites/lolomcdart/svelteproject/lolomcdart/node_modules/@sveltejs/kit/dist/chunks/index4.js:393:2)
    at async file:///C:/Users/Lucas%20Pichette/Desktop/Projects/websites/3.CodeFox-ClientWebsites/lolomcdart/svelteproject/lolomcdart/node_modules/@sveltejs/kit/dist/cli.js:896:5
```

Seems that favicon.ico folder isn't being populated with the default favicon.ico that exists at the root of the static folder.
