### ISSUE TITLE
client-side routing not working

### ISSUE THREAD

**Issue by andyburke** [sveltejs/kit#1454]
**Describe the bug**
In ^1.0.0-next client-side routing seems to not be working due to changes in the route pattern matcher. I submitted a PR (#1446) that seems to address this for me.

**Logs**
Error: path/to/route not found

Error page shows that existent routes cannot be found. However, the routes are missing their initial /, which is causing the pattern matching to fail.

**To Reproduce**

**Expected behavior**
Client-side routing should find routes as expected.

**Stacktraces**
<details>
  <summary>Error</summary>

Not found: login

Error: Not found: login
    at Renderer._get_navigation_result (http://localhost:3000/.svelte-kit/dev/runtime/internal/start.js:688:11)
    at Renderer.update (http://localhost:3000/.svelte-kit/dev/runtime/internal/start.js:545:38)
    at Router._navigate (http://localhost:3000/.svelte-kit/dev/runtime/internal/start.js:246:23)
    at http://localhost:3000/.svelte-kit/dev/runtime/internal/start.js:145:9
</details>

**Information about your SvelteKit Installation:**

<details>
  <summary>Diagnostics</summary>

System:
    OS: Linux 5.11 Linux Mint 20.1 (Ulyssa)
    CPU: (8) x64 Intel(R) Core(TM) i7-10510U CPU @ 1.80GHz
    Memory: 2.73 GB / 39.06 GB
    Container: Yes
    Shell: 5.0.17 - /bin/bash
  Binaries:
    Node: 14.17.0 - /usr/bin/node
    Yarn: 1.22.10 - /usr/bin/yarn
    npm: 6.14.13 - /usr/bin/npm
  Browsers:
    Firefox: 88.0.1
  npmPackages:
    @sveltejs/kit: ^1.0.0-next.104 => 1.0.0-next.107 
    svelte: ^3.38.2 => 3.38.2 
    vite: ^2.3.2 => 2.3.2 

adapter-node: next
</details>

**Severity**
blocking

**Comment by andyburke** [comment]
This was caused by a config setting of:

```json
{
  "paths": {
    "base": "/"
  }
} 
```

I had this setting based on an example from, I think, an upgrade guide.

I'm not sure if having a base of '/' should break things, but that is the cause of what I was experiencing.
