### ISSUE TITLE
build error when replacing a directory with a file

### ISSUE THREAD

**Issue by lovasoa** [sveltejs/kit#1458]
**Describe the bug**
When changing a static asset from a directory to a file, a build error occurs

**Logs**
```
> EISDIR: illegal operation on a directory, copyfile '/my/project/dir/static/favicon/android-chrome-512x512.png' -> 'build/favicon/android-chrome-512x512.png'
```

**To Reproduce**
 - Create a sveltekit project with an asset at `static/x.y/file.txt`
 - Build it with adapter-static
 - Remove `static/x.y/file.txt`
 - Create a FILE at `static/x.y` and include it in the project
 - Build the project again

**Stacktraces**

<details>
  <summary>Stack trace</summary>

Error: EISDIR: illegal operation on a directory, copyfile '/myproject/static/favicon/android-chrome-512x512.png' -> 'build/favicon/android-chrome-512x512.png'
    at Object.copyFileSync (node:fs:2797:3)
    at copy (file:///myproject/node_modules/@sveltejs/kit/dist/chunks/utils.js:39:15)
    at file:///myproject/node_modules/@sveltejs/kit/dist/chunks/utils.js:35:18
    at Array.forEach (<anonymous>)
    at copy (file:///myproject/node_modules/@sveltejs/kit/dist/chunks/utils.js:34:33)
    at file:///myproject/node_modules/@sveltejs/kit/dist/chunks/utils.js:35:18
    at Array.forEach (<anonymous>)
    at copy (file:///myproject/node_modules/@sveltejs/kit/dist/chunks/utils.js:34:33)
    at Object.copy_static_files (file:///myproject/node_modules/@sveltejs/kit/dist/chunks/index5.js:290:4)
    at adapt (file:///myproject/node_modules/@sveltejs/adapter-static/index.js:14:10)
</details>

**Comment by Zerotask** [comment]
That's probably related with #1448

**Comment by ignatiusmb** [comment]
The static adapter now clears output directory before building, which should solve this issue.
