### ISSUE TITLE
"Invalid Content-Type application/xml" thrown when posting xml data

### ISSUE THREAD

**Issue by lovasoa** [sveltejs/kit#1488]
**Describe the bug**
When posting data with the content-type `application/xml`, SvelteKit throws an error. 

**Logs**

```
Invalid Content-Type application/xml
```

**To Reproduce**

In the default sveltekit app, run `npm run dev`, then, from a terminal : 

```
curl localhost:3000/xxx --header "Content-Type: application/xml" -v --data '<x></x>'
```

**Expected behavior**
A 404 error

**Actual behavior**
A 500 error

```
$ curl localhost:3000/xxx --header "Content-Type: application/xml" -v --data '<x></x>'
*   Trying ::1...
* TCP_NODELAY set
* Connection failed
* connect to ::1 port 3000 failed: Connection refused
*   Trying 127.0.0.1...
* TCP_NODELAY set
* Connected to localhost (127.0.0.1) port 3000 (#0)
> POST /xxx HTTP/1.1
> Host: localhost:3000
> User-Agent: curl/7.64.1
> Accept: */*
> Content-Type: application/xml
> Content-Length: 7
> 
* upload completely sent off: 7 out of 7 bytes
< HTTP/1.1 500 Internal Server Error
< Access-Control-Allow-Origin: *
< Date: Tue, 18 May 2021 19:44:40 GMT
< Connection: keep-alive
< Keep-Alive: timeout=5
< Transfer-Encoding: chunked
< 
Error: Invalid Content-Type application/xml
    at parse_body (file:///Users/olojkine/Developpement/sanipasse/node_modules/@sveltejs/kit/dist/ssr.js:1402:11)
    at respond (file:///Users/olojkine/Developpement/sanipasse/node_modules/@sveltejs/kit/dist/ssr.js:1514:11)
    at Immediate.<anonymous> (file:///Users/olojkine/Developpement/sanipasse/node_modules/@sveltejs/kit/dist/chunks/index.js:3305:29)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)* Closing connection 0
* Connection #0 to host localhost left intact
```

**Stacktraces**

<details>
  <summary>Stack trace</summary>

```
Error: Invalid Content-Type application/xml
    at parse_body (file:///Users/olojkine/Developpement/sanipasse/node_modules/@sveltejs/kit/dist/ssr.js:1402:11)
    at respond (file:///Users/olojkine/Developpement/sanipasse/node_modules/@sveltejs/kit/dist/ssr.js:1514:11)
    at Immediate.<anonymous> (file:///Users/olojkine/Developpement/sanipasse/node_modules/@sveltejs/kit/dist/chunks/index.js:3305:29)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
```

</details>

**Information about your SvelteKit Installation:**

<details>
  <summary>Diagnostics</summary>

```

  System:
    OS: macOS 11.2.2
    CPU: (12) x64 Intel(R) Core(TM) i7-8750H CPU @ 2.20GHz
    Memory: 292.30 MB / 16.00 GB
    Shell: 3.2.57 - /bin/bash
  Binaries:
    Node: 16.1.0 - /usr/local/bin/node
    Yarn: 1.22.10 - /usr/local/bin/yarn
    npm: 7.11.2 - /usr/local/bin/npm
  Browsers:
    Chrome: 90.0.4430.212
    Firefox: 88.0.1
    Safari: 14.0.3
  npmPackages:
    @sveltejs/kit: next => 1.0.0-next.107 
    svelte: ^3.34.0 => 3.38.2 
```

</details>

**Severity**
Just annoying for me, blocking for anyone who wants to migrate an api that accepts xml to sveltekit.

**Additional context**

This bug was already reported in https://github.com/sveltejs/kit/issues/852, which contained enough information for reproduction, but was closed without investigation.

**Comment by benmccann** [comment]
I believe this has been fixed
