### ISSUE TITLE
SvelteKit builds locally, but when deploying to Netlify with netlify-adapter, the build fails with error: `@supabase/supabase-js' does not provide an export named 'createClient' `

### ISSUE THREAD

**Issue by sbutler-gh** [sveltejs/kit#1489]
**Describe the bug**

When deploying a SvelteKit app to Netlify, using the `netlify-adapter`, the build fails with the error:

`@supabase/supabase-js' does not provide an export named 'createClient'`

However, when I run `npm run build` locally, the repository builds without any errors

**Logs**

```
7:54:00 PM: Build ready to start
7:54:02 PM: build-image version: 0582042f4fc261adc7bd8333f34884959c577302
7:54:02 PM: build-image tag: v3.7.6
7:54:02 PM: buildbot version: 03c6f9d243f25556225c9548fcb276f97b8bf623
7:54:02 PM: Fetching cached dependencies
7:54:02 PM: Failed to fetch cache, continuing with build
7:54:02 PM: Starting to prepare the repo for build
7:54:03 PM: No cached dependencies found. Cloning fresh repo
7:54:03 PM: git clone https://github.com/sbutler-gh/repository
7:54:04 PM: Preparing Git Reference refs/heads/dev
7:54:04 PM: Parsing package.json dependencies
7:54:06 PM: Different publish path detected, going to use the one specified in the Netlify configuration file: 'build' versus 'public' in the Netlify UI
7:54:06 PM: Different functions path detected, going to use the one specified in the Netlify configuration file: 'functions' versus '' in the Netlify UI
7:54:06 PM: Starting build script
7:54:06 PM: Installing dependencies
7:54:06 PM: Python version set to 2.7
7:54:07 PM: v12.18.0 is already installed.
7:54:08 PM: Now using node v12.18.0 (npm v6.14.4)
7:54:08 PM: Started restoring cached build plugins
7:54:08 PM: Finished restoring cached build plugins
7:54:08 PM: Attempting ruby version 2.7.1, read from environment
7:54:10 PM: Using ruby version 2.7.1
7:54:10 PM: Using PHP version 5.6
7:54:10 PM: Started restoring cached node modules
7:54:10 PM: Finished restoring cached node modules
7:54:10 PM: Installing NPM modules using NPM version 6.14.4
7:54:22 PM: npm WARN read-shrinkwrap This version of npm is compatible with lockfileVersion@1, but package-lock.json was generated for lockfileVersion@2. I'll try to do my best with it!
7:54:22 PM: > bufferutil@4.0.3 install /opt/build/repo/node_modules/bufferutil
7:54:22 PM: > node-gyp-build
7:54:23 PM: > utf-8-validate@5.0.5 install /opt/build/repo/node_modules/utf-8-validate
7:54:23 PM: > node-gyp-build
7:54:23 PM: > esbuild@0.11.23 postinstall /opt/build/repo/node_modules/esbuild
7:54:23 PM: > node install.js
7:54:24 PM: > svelte-preprocess@4.7.3 postinstall /opt/build/repo/node_modules/svelte-preprocess
7:54:24 PM: > echo "[svelte-preprocess] Don't forget to install the preprocessors packages that will be used: node-sass/sass, stylus, less, postcss & postcss-load-config, coffeescript, pug, etc..."
7:54:24 PM: [svelte-preprocess] Don't forget to install the preprocessors packages that will be used: node-sass/sass, stylus, less, postcss & postcss-load-config, coffeescript, pug, etc...
npm WARN ~TODO~@0.0.1 No repository field.
7:54:24 PM: npm WARN ~TODO~@0.0.1 No license field.
7:54:24 PM: npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@2.3.2 (node_modules/fsevents):
7:54:24 PM: npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@2.3.2: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
7:54:24 PM: added 498 packages from 343 contributors and audited 500 packages in 13.439s
7:54:25 PM: 50 packages are looking for funding
7:54:25 PM:   run `npm fund` for details
7:54:25 PM: found 0 vulnerabilities
7:54:25 PM: NPM modules installed
7:54:25 PM: Started restoring cached go cache
7:54:25 PM: Finished restoring cached go cache
7:54:25 PM: go version go1.14.4 linux/amd64
7:54:25 PM: go version go1.14.4 linux/amd64
7:54:25 PM: Installing missing commands
7:54:25 PM: Verify run directory
7:54:27 PM: ​
7:54:27 PM: ────────────────────────────────────────────────────────────────
7:54:27 PM:   Netlify Build                                                 
7:54:27 PM: ────────────────────────────────────────────────────────────────
7:54:27 PM: ​
7:54:27 PM: ❯ Version
7:54:27 PM:   @netlify/build 11.17.2
7:54:27 PM: ​
7:54:27 PM: ❯ Flags
7:54:27 PM:   deployId: 60a3ff38a2786e0007d20109
7:54:27 PM: ​
7:54:27 PM: ❯ Current directory
7:54:27 PM:   /opt/build/repo
7:54:27 PM: ​
7:54:27 PM: ❯ Config file
7:54:27 PM:   /opt/build/repo/netlify.toml
7:54:27 PM: ​
7:54:27 PM: ❯ Context
7:54:27 PM:   production
7:54:27 PM: ​
7:54:27 PM: ────────────────────────────────────────────────────────────────
7:54:27 PM:   1. build.command from netlify.toml                            
7:54:27 PM: ────────────────────────────────────────────────────────────────
7:54:27 PM: ​
7:54:27 PM: $ npm run build
7:54:27 PM: > ~TODO~@0.0.1 build /opt/build/repo
7:54:27 PM: > svelte-kit build
7:54:27 PM: (node:1389) ExperimentalWarning: The ESM module loader is experimental.
7:54:27 PM: vite v2.3.3 building for production...
7:54:28 PM: transforming...
7:54:42 PM: ✓ 96 modules transformed.
7:54:43 PM: rendering chunks...
7:54:59 PM: .svelte-kit/output/client/_app/manifest.json                               1.64kb
7:54:59 PM: .svelte-kit/output/client/_app/pages/index.svelte-cada8c67.js              0.14kb / brotli: 0.10kb
7:54:59 PM: .svelte-kit/output/client/_app/pages/__error.svelte-f4fa4b22.js            0.14kb / brotli: 0.10kb
7:54:59 PM: .svelte-kit/output/client/_app/chunks/singletons-bb9012b7.js               0.05kb / brotli: 0.05kb
7:54:59 PM: .svelte-kit/output/client/_app/pages/[slug].svelte-ec1023d5.js             0.14kb / brotli: 0.10kb
7:54:59 PM: .svelte-kit/output/client/_app/assets/start-0826e215.css                   0.18kb / brotli: 0.11kb
7:54:59 PM: .svelte-kit/output/client/_app/assets/vendor-119c9bb3.css                  7.66kb / brotli: 1.55kb
7:54:59 PM: .svelte-kit/output/client/_app/start-1a95caf6.js                           17.58kb / brotli: 5.58kb
7:54:59 PM: .svelte-kit/output/client/_app/pages/__layout.svelte-9141578b.js           49.85kb / brotli: 12.14kb
7:54:59 PM: .svelte-kit/output/client/_app/assets/pages/__layout.svelte-85885be8.css   86.98kb / brotli: 12.04kb
7:54:59 PM: .svelte-kit/output/client/_app/chunks/vendor-b335e5ae.js                   843.03kb / brotli: skipped (large chunk)
7:54:59 PM: 
7:54:59 PM: (!) Some chunks are larger than 500kb after minification. Consider:
7:54:59 PM: - Using dynamic import() to code-split the application
7:54:59 PM: - Use build.rollupOptions.output.manualChunks to improve chunking: https://rollupjs.org/guide/en/#outputmanualchunks
7:54:59 PM: - Adjust chunk size limit for this warning via build.chunkSizeWarningLimit.
7:54:59 PM: vite v2.3.3 building SSR bundle for production...
7:54:59 PM: transforming...
7:55:05 PM: ✓ 41 modules transformed.
7:55:05 PM: rendering chunks...
7:55:05 PM: .svelte-kit/output/server/app.js   286.21kb
7:55:05 PM: Run npm run preview to preview your production build locally.
7:55:05 PM: 
7:55:05 PM: > Using @sveltejs/adapter-netlify
**7:55:05 PM: > The requested module '@supabase/supabase-js' does not provide an export named 'createClient'
7:55:05 PM: file:///opt/build/repo/.svelte-kit/output/server/app.js:5
7:55:05 PM: import {createClient} from "@supabase/supabase-js";
7:55:05 PM:         ^^^^^^^^^^^^
7:55:05 PM: SyntaxError: The requested module '@supabase/supabase-js' does not provide an export named 'createClient'
7:55:05 PM:     at ModuleJob._instantiate (internal/modules/esm/module_job.js:92:21)
7:55:05 PM:     at async ModuleJob.run (internal/modules/esm/module_job.js:107:20)
7:55:05 PM:     at async Loader.import (internal/modules/esm/loader.js:179:24)
7:55:05 PM:     at async prerender (file:///opt/build/repo/node_modules/@sveltejs/kit/dist/chunks/index5.js:79:14)
7:55:05 PM:     at async Object.prerender (file:///opt/build/repo/node_modules/@sveltejs/kit/dist/chunks/index5.js:296:5)
7:55:05 PM:     at async adapt (file:///opt/build/repo/node_modules/@sveltejs/adapter-netlify/index.js:33:4)
7:55:05 PM:     at async adapt (file:///opt/build/repo/node_modules/@sveltejs/kit/dist/chunks/index5.js:322:2)
7:55:05 PM:     at async file:///opt/build/repo/node_modules/@sveltejs/kit/dist/cli.js:616:5**
7:55:05 PM: npm ERR! code ELIFECYCLE
7:55:05 PM: npm ERR! errno 1
7:55:05 PM: npm ERR! ~TODO~@0.0.1 build: `svelte-kit build`
7:55:05 PM: npm ERR! Exit status 1
7:55:05 PM: npm ERR!
7:55:05 PM: npm ERR! Failed at the ~TODO~@0.0.1 build script.
7:55:05 PM: npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
7:55:05 PM: npm ERR! A complete log of this run can be found in:
7:55:05 PM: npm ERR!     /opt/buildhome/.npm/_logs/2021-05-18T17_55_05_631Z-debug.log
7:55:05 PM: ​
7:55:05 PM: ────────────────────────────────────────────────────────────────
7:55:05 PM:   "build.command" failed                                        
7:55:05 PM: ────────────────────────────────────────────────────────────────
7:55:05 PM: ​
7:55:05 PM:   Error message
7:55:05 PM:   Command failed with exit code 1: npm run build
7:55:05 PM: ​
7:55:05 PM:   Error location
7:55:05 PM:   In build.command from netlify.toml:
7:55:05 PM:   npm run build
7:55:05 PM: ​
7:55:05 PM:   Resolved config
7:55:05 PM:   build:
7:55:05 PM:     command: npm run build
7:55:05 PM:     commandOrigin: config
7:55:05 PM:     publish: /opt/build/repo/build
7:55:05 PM:   functionsDirectory: /opt/build/repo/functions
7:55:06 PM: Caching artifacts
7:55:06 PM: Started saving node modules
7:55:06 PM: Finished saving node modules
7:55:06 PM: Started saving build plugins
7:55:06 PM: Finished saving build plugins
7:55:06 PM: Started saving pip cache
7:55:06 PM: Finished saving pip cache
7:55:06 PM: Started saving emacs cask dependencies
7:55:06 PM: Finished saving emacs cask dependencies
7:55:06 PM: Started saving maven dependencies
7:55:06 PM: Finished saving maven dependencies
7:55:06 PM: Started saving boot dependencies
7:55:06 PM: Finished saving boot dependencies
7:55:06 PM: Started saving rust rustup cache
7:55:06 PM: Finished saving rust rustup cache
7:55:06 PM: Started saving go dependencies
7:55:06 PM: Finished saving go dependencies
7:55:08 PM: Build failed due to a user error: Build script returned non-zero exit code: 2
7:55:08 PM: Creating deploy upload records
7:55:08 PM: Failing build: Failed to build site
7:55:08 PM: Failed during stage 'building site': Build script returned non-zero exit code: 2
7:55:08 PM: Finished processing build request in 1m6.448211496s
```

**To Reproduce**

My steps were something like this:

* Create new SvelteKit app
* Install supabase as devDependency using the svelte-add package
* Install the netlify-adapter and configure netlify.toml
* Set-up Netlify deployment from the GitHub repository

**Expected behavior**

Since the repository is building locally without any issues running `npm run build`, I expect it to build successfully on Netlify as well

**Severity**

Blocking deployment to Netlify.

**Additional context**

I tried the following troubleshoots, without any success:

* Updating all packages
* Switching supabase from devDependencies to dependencies and vice versa
* Adding  `vite: { optimizeDeps: { include: ["@supabase/supabase-js"] }` to svelte.config.js

**Comment by sbutler-gh** [comment]
Solution linked here:

https://github.com/supabase/supabase-js/issues/171#issuecomment-843617523

**Comment by sw-yx** [comment]
thanks for a well filed issue though

**Comment by sbutler-gh** [comment]
Thank you, @sw-yx!  Your words on learning in public have been a huge inspiration!
