### ISSUE TITLE
Using imported object as prop works in dev mode but fails on build

### ISSUE THREAD

**Issue by KonradHoeffner** [sveltejs/kit#1504]
**Describe the bug**
`npm run dev` works perfectly fine using an imported object as a prop for a component, but `npm run build` fails.

**Logs**
None, it does not even build.

**To Reproduce**
### src/testobject.js
    export default {message: "Hello World"}

### src/routes/TestComponent.svelte
```js
<script>
export let object;
console.log(object.message);
</script>
```

### src/routes/index.svelte
```js
<script>
import TestComponent from './TestComponent.svelte';
import testobject from './../testobject.js';
 </script>

<TestComponent object={testobject}/>
```

**Expected behavior**
If it should run in development mode via `npm run dev` it should also work with `npm run build`.

**Stacktraces**

<details>
  <summary>Stack trace</summary>
$ npm run build

> glossary@0.2.0 build
> svelte-kit build

vite v2.3.0 building for production...
✓ 35 modules transformed.
.svelte-kit/output/client/_app/manifest.json                               2.12kb
.svelte-kit/output/client/_app/pages/index.svelte-0f7cff73.js              0.46kb / brotli: 0.29kb
.svelte-kit/output/client/_app/pages/__layout.svelte-a0234d39.js           0.60kb / brotli: 0.36kb
.svelte-kit/output/client/_app/error.svelte-058624f9.js                    1.19kb / brotli: 0.57kb
.svelte-kit/output/client/_app/pages/TestComponent.svelte-584d8f4d.js      0.25kb / brotli: 0.17kb
.svelte-kit/output/client/_app/pages/faq.svelte-6a774a55.js                3.91kb / brotli: 1.37kb
.svelte-kit/output/client/_app/assets/start-a8cd1609.css                   0.16kb / brotli: 0.10kb
.svelte-kit/output/client/_app/pages/Glossary.svelte-210b03cb.js           7.25kb / brotli: 2.32kb
.svelte-kit/output/client/_app/assets/pages/__layout.svelte-9d96e07f.css   1.10kb / brotli: 0.43kb
.svelte-kit/output/client/_app/assets/pages/Glossary.svelte-fbf7104d.css   0.08kb / brotli: 0.06kb
.svelte-kit/output/client/_app/start-b7671000.js                           17.61kb / brotli: 5.50kb
.svelte-kit/output/client/_app/chunks/vendor-20ced20d.js                   23.38kb / brotli: 7.37kb
vite v2.3.0 building SSR bundle for production...
✓ 16 modules transformed.
.svelte-kit/output/server/app.js   21.95kb

Run npm run preview to preview your production build locally.

> Using @sveltejs/adapter-static
Hello World
TypeError: Cannot read property 'message' of undefined
    at file:///home/konrad/projekte/imise/glossar/.svelte-kit/output/server/app.js:222:22
    at Object.$$render (file:///home/konrad/projekte/imise/glossar/node_modules/svelte/internal/index.mjs:1377:22)
    at Object.default (file:///home/konrad/projekte/imise/glossar/.svelte-kit/output/server/app.js:53:117)
    at file:///home/konrad/projekte/imise/glossar/.svelte-kit/output/server/app.js:188:38
    at Object.$$render (file:///home/konrad/projekte/imise/glossar/node_modules/svelte/internal/index.mjs:1377:22)
    at file:///home/konrad/projekte/imise/glossar/.svelte-kit/output/server/app.js:52:78
    at $$render (file:///home/konrad/projekte/imise/glossar/node_modules/svelte/internal/index.mjs:1377:22)
    at Object.render (file:///home/konrad/projekte/imise/glossar/node_modules/svelte/internal/index.mjs:1385:26)
    at render_response (file:///home/konrad/projekte/imise/glossar/node_modules/@sveltejs/kit/dist/ssr.js:377:28)
    at async respond$1 (file:///home/konrad/projekte/imise/glossar/node_modules/@sveltejs/kit/dist/ssr.js:1142:10)
> 500 /TestComponent
Error: 500 /TestComponent
    at error (file:///home/konrad/projekte/imise/glossar/node_modules/@sveltejs/kit/dist/chunks/index5.js:93:11)
    at visit (file:///home/konrad/projekte/imise/glossar/node_modules/@sveltejs/kit/dist/chunks/index5.js:160:5)
    at async prerender (file:///home/konrad/projekte/imise/glossar/node_modules/@sveltejs/kit/dist/chunks/index5.js:229:5)
    at async Object.prerender (file:///home/konrad/projekte/imise/glossar/node_modules/@sveltejs/kit/dist/chunks/index5.js:296:5)
    at async adapt (file:///home/konrad/projekte/imise/glossar/node_modules/@sveltejs/adapter-static/index.js:17:4)
    at async adapt (file:///home/konrad/projekte/imise/glossar/node_modules/@sveltejs/kit/dist/chunks/index5.js:322:2)
    at async file:///home/konrad/projekte/imise/glossar/node_modules/@sveltejs/kit/dist/cli.js:592:5

</details>

**Information about your SvelteKit Installation:**

<details>
  <summary>Diagnostics</summary>

- The output of `npx envinfo --system --npmPackages svelte,@sveltejs/kit,vite --binaries --browsers`
  System:
    OS: Linux 5.12 Arch Linux
    CPU: (8) x64 Intel(R) Core(TM) i7-9700 CPU @ 3.00GHz
    Memory: 2.49 GB / 15.42 GB
    Container: Yes
    Shell: 5.1.8 - /bin/bash
  Binaries:
    Node: 16.1.0 - /usr/bin/node
    npm: 7.13.0 - /usr/bin/npm
  Browsers:
    Chromium: 90.0.4430.212
  npmPackages:
    @sveltejs/kit: next => 1.0.0-next.104 
    svelte: ^3.38.2 => 3.38.2 

- Your browser
Firefox 89

- Your adapter (e.g. Node, static, Vercel, Begin, etc...)
static
</details>

**Severity**
High, building impossible.

**Comment by benmccann** [comment]
It might work if you put it in `lib` and import via `$lib` instead

**Comment by KonradHoeffner** [comment]
That worked, thanks!
