### ISSUE TITLE
How to use vite plugins in kit?

### ISSUE THREAD

**Issue by SOVLOOKUP** [sveltejs/kit#1551]
I try to use [midway/hooks](https://github.com/midwayjs/hooks) in kit, it needs a vite plugin to work.
Everything works well with vite only. -> https://github.com/midwayjs/hooks/blob/master/examples/svelte
But when I adding the plugin in `svelte.config.js`, it runs faild. -> https://github.com/SOVLOOKUP/midway-svelte

**Here is the code:**

svelte.config.js
```js
import preprocess from 'svelte-preprocess';
import hooks from '@midwayjs/vite-plugin-hooks';
import { defineConfig } from 'vite';

/** @type {import('@sveltejs/kit').Config} */
const config = {
	// Consult https://github.com/sveltejs/svelte-preprocess
	// for more information about preprocessors
	preprocess: preprocess(),

	kit: {
		// hydrate the <div id="svelte"> element in src/app.html
		target: '#svelte',
		vite: defineConfig({
			plugins: [ hooks() ]
		})
	}
};

export default config;
```

**err:**
```
> ~TODO~@0.0.1 dev /home/sovlookup/桌面/my-app/test/my-app
> svelte-kit dev

hooks is not a function
TypeError: hooks is not a function
    at file:///home/sovlookup/%E6%A1%8C%E9%9D%A2/my-app/test/my-app/svelte.config.js:15:15                                                                                                   
    at ModuleJob.run (node:internal/modules/esm/module_job:175:25)                                                                                                                           
    at async Loader.import (node:internal/modules/esm/loader:178:24)                                                                                                                         
    at async load_config (file:///home/sovlookup/%E6%A1%8C%E9%9D%A2/my-app/test/my-app/node_modules/_@sveltejs_kit@1.0.0-next.109@@sveltejs/kit/dist/cli.js:464:17)                          
    at async get_config (file:///home/sovlookup/%E6%A1%8C%E9%9D%A2/my-app/test/my-app/node_modules/_@sveltejs_kit@1.0.0-next.109@@sveltejs/kit/dist/cli.js:519:10)                           
    at async file:///home/sovlookup/%E6%A1%8C%E9%9D%A2/my-app/test/my-app/node_modules/_@sveltejs_kit@1.0.0-next.109@@sveltejs/kit/dist/cli.js:577:18                                        
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! ~TODO~@0.0.1 dev: `svelte-kit dev`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the ~TODO~@0.0.1 dev script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/sovlookup/.npm/_logs/2021-05-25T09_11_03_984Z-debug.log
```

**Comment by UltraCakeBakery** [comment]
I have to do this for windicss:

```javascript
WindiCSS.default()
```

something like....

```javascript
plugins: [ hooks.default() ]
```
may work for you.

**Comment by SOVLOOKUP** [comment]
This is caused by [vite-plugin-svelte](https://github.com/sveltejs/vite-plugin-svelte). When `svelte.config.js` cannot be imported by ["dynamicImportDefault" function](https://github.com/sveltejs/vite-plugin-svelte/blob/main/packages/vite-plugin-svelte/src/utils/loadSvelteConfig.ts#L12), vite-plugin-svelte will use `require` to import it. 

https://github.com/sveltejs/vite-plugin-svelte/issues/47

**Comment by GitGangGuy** [comment]
Experiencing the same issue with a different plugin (`vite-plugin-compress`) as well. It's pretty annoying because now I don't get proper type annotations anymore and it took me a while to find this. The workaround from @UltraCakeBakery did work, thanks!
