### ISSUE TITLE
TypeError: render2 is not a function

### ISSUE THREAD

**Issue by mylastore** [sveltejs/kit#1623]
Not sure if this is a bug
This is the only difference
Production: node version 14.17.0
Dev: node version 14.16.0

When I run npm run build on dev it works but not on a production self hosted server this is what I get

```bash
✓ 76 modules transformed.
.svelte-kit/output/server/app.js   501.50kb
Run npm run preview to preview your production build locally.

> Using @sveltejs/adapter-node
TypeError: render2 is not a function
    at Object.handle (file:///home/admin/web/mylastore.com/public_html/.svelte-kit/output/server/app.js:80:26)
    at respond (file:///home/admin/web/mylastore.com/public_html/node_modules/@sveltejs/kit/dist/ssr.js:1514:30)
    at Module.render (file:///home/admin/web/mylastore.com/public_html/.svelte-kit/output/server/app.js:319:10)
    at visit (file:///home/admin/web/mylastore.com/public_html/node_modules/@sveltejs/kit/dist/chunks/index7.js:131:30)
    at prerender (file:///home/admin/web/mylastore.com/public_html/node_modules/@sveltejs/kit/dist/chunks/index7.js:245:11)
    at async Object.prerender (file:///home/admin/web/mylastore.com/public_html/node_modules/@sveltejs/kit/dist/chunks/index7.js:312:5)
    at async adapt (file:///home/admin/web/mylastore.com/public_html/node_modules/@sveltejs/adapter-node/index.js:28:4)
    at async adapt (file:///home/admin/web/mylastore.com/public_html/node_modules/@sveltejs/kit/dist/chunks/index7.js:338:2)
    at async file:///home/admin/web/mylastore.com/public_html/node_modules/@sveltejs/kit/dist/cli.js:654:5
> 500 /
Error: 500 /
    at error (file:///home/admin/web/mylastore.com/public_html/node_modules/@sveltejs/kit/dist/chunks/index7.js:94:11)
    at visit (file:///home/admin/web/mylastore.com/public_html/node_modules/@sveltejs/kit/dist/chunks/index7.js:176:5)
    at async prerender (file:///home/admin/web/mylastore.com/public_html/node_modules/@sveltejs/kit/dist/chunks/index7.js:245:5)
    at async Object.prerender (file:///home/admin/web/mylastore.com/public_html/node_modules/@sveltejs/kit/dist/chunks/index7.js:312:5)
    at async adapt (file:///home/admin/web/mylastore.com/public_html/node_modules/@sveltejs/adapter-node/index.js:28:4)
    at async adapt (file:///home/admin/web/mylastore.com/public_html/node_modules/@sveltejs/kit/dist/chunks/index7.js:338:2)
    at async file:///home/admin/web/mylastore.com/public_html/node_modules/@sveltejs/kit/dist/cli.js:654:5

```

**Comment by benmccann** [comment]
What version of `@sveltejs/adapter-node` are you using? The latest is `1.0.0-next.24`. A lot of errors are caused by using an old version

**Comment by mylastore** [comment]
> What version of `@sveltejs/adapter-node` are you using? The latest is `1.0.0-next.24`. A lot of errors are caused by using an old version

1.0.0-next.109

**Comment by benmccann** [comment]
That's your version of `@sveltejs/kit`. As I've already said, the latest version of `adapter-node` is `1.0.0-next.24`. You can find the version with `npx envinfo --npmPackages @sveltejs/adapter-node`

**Comment by mylastore** [comment]
> That's your version of `@sveltejs/kit`. As I've already said, the latest version of `adapter-node` is `1.0.0-next.24`. You can find the version with `npx envinfo --npmPackages @sveltejs/adapter-node`

found it  1.0.0-next.22

**Comment by benmccann** [comment]
Hmm. You could try updating to the latest version of both SvelteKit and the adapter

There's not much info here on how to cause the error. Could you share a repo that reproduces this?

**Comment by mylastore** [comment]
let me try updating both sveltekit and the adapter if that does not work, I could share the repo.

**Comment by mylastore** [comment]
ok, updated  to latest svelte and something else broke, but manage to correct that also and now the site is working on production server.

under svelte hooks they rename the method "render" to "resolve"
export async function handle({ request, render }) {
to
export async function handle({ request, resolve }) {

```bash
  "@sveltejs/adapter-node": "^1.0.0-next.24",
  "@sveltejs/kit": "^1.0.0-next.112",
```

**Comment by lovasoa** [comment]
The same thing happened to me today after a simple `npm update`. Why is this closed ?

**Comment by lovasoa** [comment]
Here is the repo (and hash) that reproduce the error: https://github.com/lovasoa/sanipasse/tree/82ec0f60440494038abbbbca14d2beeeea71bbdc

**Comment by pixelmund** [comment]
You should rename `render` in the handle hook to `resolve`. It got changed recently.

**Comment by lovasoa** [comment]
Yes, it looks like sveltekit silently renamed a function parameter. How are developers supposed to learn about that ?

**Comment by lovasoa** [comment]
Is there a changelog somewhere ?

**Comment by pixelmund** [comment]
https://github.com/sveltejs/kit/blob/master/packages/kit/CHANGELOG.md

**Comment by rsdavis** [comment]
If you are running into this (as I just did when updating), you need to rename "render" to "resolve" for the function argument in the `hooks.js` file. This file is included as part of the template, but it's optional, and it's likely you can just remove the file without an issue.
