### ISSUE TITLE
node build/index.js - Dynamic require of "fs" is not supported

### ISSUE THREAD

**Issue by yassinrais** [sveltejs/kit#1671]
**To Reproduce**
I start today building the project again , and the build didnt work anymore 

**Stacktraces**
If you have a stack trace to include, we recommend putting inside a `<details>` block for the sake of the thread's readability:

<details>
  <summary>Stack trace</summary>

file:///home/app/public_html/aaaaaaaaaaaa/releases/20210611102438Z/build/index.js:11
  throw new Error('Dynamic require of "' + x + '" is not supported');
        ^

Error: Dynamic require of "fs" is not supported
    at __require (file:///home/app/public_html/aaaaaaaaaaaa/releases/20210611102438Z/build/index.js:11:9)
    at node_modules/better-sqlite3/lib/database.js (file:///home/app/public_html/aaaaaaaaaaaa/releases/20210611102438Z/build/index.js:742:15)
    at __require2 (file:///home/app/public_html/aaaaaaaaaaaa/releases/20210611102438Z/build/index.js:14:44)
    at node_modules/better-sqlite3/lib/index.js (file:///home/app/public_html/aaaaaaaaaaaa/releases/20210611102438Z/build/index.js:816:22)
    at __require2 (file:///home/app/public_html/aaaaaaaaaaaa/releases/20210611102438Z/build/index.js:14:44)
    at file:///home/app/public_html/aaaaaaaaaaaa/releases/20210611102438Z/build/index.js:2687:40
    at ModuleJob.run (internal/modules/esm/module_job.js:152:23)
    at async Loader.import (internal/modules/esm/loader.js:177:24)
    at async Object.loadESM (internal/process/esm_loader.js:68:5)

</details>

**Information about your SvelteKit Installation:**

<details>
  <summary>Diagnostics</summary>

  System:
    OS: Linux 4.19 Debian GNU/Linux 10 (buster) 10 (buster)
    CPU: (1) x64 Intel Core Processor (Haswell, no TSX)
    Memory: 315.97 MB / 1.90 GB
    Container: Yes
    Shell: 5.0.3 - /bin/bash
  Binaries:
    Node: 14.17.0 - /usr/bin/node
    npm: 6.14.13 - /usr/bin/npm
  npmPackages:
    @sveltejs/adapter-node: ^1.0.0-next.22 => 1.0.0-next.25 
    @sveltejs/kit: ^1.0.0-next.109 => 1.0.0-next.114 
    svelte: ^3.38.1 => 3.38.2 

</details>

**Comment by Conduitry** [comment]
Please provide a reproduction.

**Comment by yassinrais** [comment]
**I resolve the issue** 

_The ``better-sqlite`` was in the ``devDependencies``_

With the old version of sveltekit builder , it was working fine , but
After the updates it not working anymore 

_its make the build index.js look like a client compiled script and not like a node script_

**Comment by benmccann** [comment]
> I resolve the issue

I will close this then. Thanks
