### ISSUE TITLE
[vite:terser] "_c" is redeclared

### ISSUE THREAD

**Issue by schicks** [sveltejs/kit#1690]
**Describe the bug**
When running `npm run build` the process crashes with `[vite:terser] "_c" is redeclared`. I believe this is related to a [bug in vite](https://github.com/vitejs/vite/issues/3363), which is being triggered by using vega lite. The other thread appears to describe a workaround, but I'm not sure how to use it from the context of sveltekit.

**Logs**
<details>
<pre>
vite v2.3.7 building for production...
transforming (799) node_modu[vite-plugin-svelte] The following packages did not export their `package.json` file so we could not check the "svelte" field. If you had difficulties importing svelte components from a package, then please contact the author and ask them to export the package.json file.
- json-stringify-pretty-compact
✓ 815 modules transformed.       
rendering chunks (10)...[vite:terser] "_c" is redeclared
> "_c" is redeclared
SyntaxError: "_c" is redeclared  
    at js_error (PROJ_FOLDER\node_modules\vite\dist\node\terser.js:9288:11)
    at TreeWalker.visit (PROJ_FOLDER\node_modules\vite\dist\node\terser.js:18265:17)
    at TreeWalker._visit (PROJ_FOLDER\node_modules\vite\dist\node\terser.js:13855:24)
    at AST_SymbolConst._walk (PROJ_FOLDER\node_modules\vite\dist\node\terser.js:12398:24)        
    at AST_VarDef.<anonymous> (PROJ_FOLDER\node_modules\vite\dist\node\terser.js:13090:23)       
    at TreeWalker._visit (PROJ_FOLDER\node_modules\vite\dist\node\terser.js:13859:21)
    at AST_VarDef._walk (PROJ_FOLDER\node_modules\vite\dist\node\terser.js:13089:24)
    at AST_Const.<anonymous> (PROJ_FOLDER\node_modules\vite\dist\node\terser.js:13060:32)        
    at TreeWalker._visit (PROJ_FOLDER\node_modules\vite\dist\node\terser.js:13859:21)
    at AST_Const._walk (PROJ_FOLDER\node_modules\vite\dist\node\terser.js:13057:24)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
</pre>
</details>

**To Reproduce**
https://github.com/schicks/sveltekit-vega-bug

Clean sveltekit project with a simple component to host vegalite graphs. Apparently just importing it is enough to cause the problem.

**Expected behavior**
I should be able to produce static output that can render vega lite graphs.

**System**

<details>
npx: installed 1 in 1.546s

  System:
    OS: Windows 10 10.0.19041
    CPU: (8) ia32 Intel(R) Core(TM) i7-6700K CPU @ 4.00GHz
    Memory: 12.44 GB / 23.95 GB
  Binaries:
    Node: 14.17.0 - C:\Program Files (x86)\nodejs\node.EXE
    Yarn: 1.7.0 - C:\Program Files (x86)\Yarn\bin\yarn.CMD
    npm: 6.14.13 - C:\Program Files (x86)\nodejs\npm.CMD
  npmPackages:
    @sveltejs/adapter-static: next => 1.0.0-next.13
    @sveltejs/kit: next => 1.0.0-next.115
    svelte: ^3.34.0 => 3.38.2
</details>

**Severity**
I need to be able to use vega graphs to use sveltekit. This is a personal project, so I don't have any real sense of urgency, but until I have a workaround I'm going to continue using gatsby.

**Comment by Conduitry** [comment]
It looks like the workaround would be to have `..., vite: { build: { minify: 'esbuild' } }, ...` in your `svelte.config.js`.

**Comment by schicks** [comment]
Ah, perfect! I stuck that under `kit` and it solved the problem in the test repo. I'm still learning my way around the config. Thanks for the help!
