### ISSUE TITLE
Aliases do not work in dynamic paths or when used inside template literals

### ISSUE THREAD

**Issue by UltraCakeBakery** [sveltejs/kit#1722]
**Describe the bug**
The following pseudo code fails to resolve the component even though the file exists and aliases are setup in the `svelte.config.js`

```javascript
function getComponent( component )
{
	return import( `$lib/components/${component}.svelte` )
}
```

This code right here however works perfectly fine:

```javascript
function getComponent( component )
{
	return import( `../src/lib/components/${component}.svelte` )
}
```

Passing a regular string without a variable is fine too:

```javascript
function getComponent()
{
	return import( '$lib/components/component.svelte' )
}
```

but when using a template string it fails again:
```javascript
function getComponent()
{
	return import( `$lib/components/component.svelte` )
}
```

**Logs**
`Cannot find module '$lib/component/test.svelte' from 'P:/project/src/routes'`

**To Reproduce**
1. init the most recent skeleton project
2. Create a `foo.svelte` component in lib 
3. Try running the snippets above

**Expected behavior**
I expect the components to resolve. I should be able to use both aliases and variables in my paths.

**Stacktraces**
<details>
  <summary>Stack trace</summary>

<pre>Error: Cannot find module '$lib/components/text.svelte' from 'P:/project/src/routes'
    at Function.resolveSync [as sync] (P:\project\node_modules\.pnpm\resolve@1.20.0\node_modules\resolve\lib\sync.js:102:15)
    at resolveFrom$6 (P:\project\node_modules\.pnpm\vite@2.3.7\node_modules\vite\dist\node\chunks\dep-bc228bbb.js:4053:29)
    at resolve (P:\project\node_modules\.pnpm\vite@2.3.7\node_modules\vite\dist\node\chunks\dep-bc228bbb.js:68728:22)
    at nodeRequire (P:\project\node_modules\.pnpm\vite@2.3.7\node_modules\vite\dist\node\chunks\dep-bc228bbb.js:68707:25)
    at ssrDynamicImport (P:\project\node_modules\.pnpm\vite@2.3.7\node_modules\vite\dist\node\chunks\dep-bc228bbb.js:68668:36)
    at [...page].svelte:27:42
    at Array.map (&lt;anonymous&gt;)
    at load ([...page].svelte:24:27)
    at load_node (file:///P:/project/node_modules/.pnpm/@sveltejs+kit@1.0.0-next.115_svelte@3.38.2/node_modules/@sveltejs/kit/dist/ssr.js:818:30)
    at respond$1 (file:///P:/project/node_modules/.pnpm/@sveltejs+kit@1.0.0-next.115_svelte@3.38.2/node_modules/@sveltejs/kit/dist/ssr.js:1039:21)</pre>

</details>

**Information about your SvelteKit Installation:**

<details>
  <summary>Diagnostics</summary>

  System:
    OS: Windows 10 10.0.19042
    CPU: (12) ia32 Intel(R) Core(TM) i7-10750H CPU @ 2.60GHz
    Memory: 3.86 GB / 15.75 GB
  Binaries:
    Node: 14.16.1 - C:\Program Files (x86)\nodejs\node.EXE
    npm: 6.14.12 - C:\Program Files (x86)\nodejs\npm.CMD
  Browsers:
    Edge: Spartan (44.19041.1023.0), Chromium (91.0.864.48)
    Internet Explorer: 11.0.19041.1
  npmPackages:
    @sveltejs/kit: next => 1.0.0-next.115
    svelte: ^3.38.2 => 3.38.2
</details>

**Severity**
Relatively high (pun intended) because the relative path works fine for now. But i am sure I will be running in to env issues down the line.

**Additional context**
I am running this function in a route's `load`. The same happens when running this outside of module context.
I am not sure this is a svelte-kit issue or vite issue.

**Comment by dummdidumm** [comment]
This sounds like an upstream Vite issue.

**Comment by benmccann** [comment]
Thanks for reporting, but there's probably very little we can do to fix this in SvelteKit. Please file an issue in the Vite tracker. It'd be helpful for others who search here if you also include a link to it
