### ISSUE TITLE
Run build fails using adapter-static - help understanding why.

### ISSUE THREAD

**Issue by sagive** [sveltejs/kit#1760]
**Describe the bug**
I am getting some errors when trying to build a static build using the adapter.

**Here is my config svelte.config**
```
import adapter from '@sveltejs/adapter-static';
import preprocess from 'svelte-preprocess';

/** @type {import('@sveltejs/kit').Config} */
const config = {
	// Consult https://github.com/sveltejs/svelte-preprocess
	// for more information about preprocessors
	preprocess: preprocess(),

	kit: {
		target: '#svelte',
		adapter: adapter({
			// default options are shown
			pages: 'build',
			assets: 'build',
			fallback: null
		})
	}
};

export default config;
```

**Error log output**
```
0 info it worked if it ends with ok
1 verbose cli [
1 verbose cli   'C:\\Program Files (x86)\\nodejs\\node.exe',
1 verbose cli   'C:\\Program Files (x86)\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'run',
1 verbose cli   'build'
1 verbose cli ]
2 info using npm@6.14.13
3 info using node@v14.17.0
4 verbose run-script [ 'prebuild', 'build', 'postbuild' ]
5 info lifecycle svelte-kit@0.0.1~prebuild: svelte-kit@0.0.1
6 info lifecycle svelte-kit@0.0.1~build: svelte-kit@0.0.1
7 verbose lifecycle svelte-kit@0.0.1~build: unsafe-perm in lifecycle true
8 verbose lifecycle svelte-kit@0.0.1~build: PATH: C:\Program Files (x86)\nodejs\node_modules\npm\node_modules\npm-lifecycle\node-gyp-bin;E:\Traning BOX\socialize-3rd\node_modules\.bin;C:\Program Files (x86)\Common Files\Intel\Shared Libraries\redist\intel64\compiler;C:\Python38\Scripts\;C:\Python38\;C:\Python27\;C:\Python27\Scripts;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0\;C:\WINDOWS\System32\OpenSSH\;C:\Program Files\Microsoft VS Code\bin;C:\Program Files\Git\cmd;C:\ProgramData\chocolatey\bin;C:\Program Files\NVIDIA Corporation\NVIDIA NvDLISR;C:\Program Files (x86)\nodejs\;C:\Users\imris\AppData\Local\Programs\Python\Python37-32\Scripts\;C:\Users\imris\AppData\Local\Programs\Python\Python37-32\;C:\Users\imris\AppData\Local\Microsoft\WindowsApps;C:\Program Files\Microsoft VS Code\bin;C:\Users\imris\AppData\Local\Programs\Microsoft VS Code\bin;C:\Users\imris\flutter\bin;C:\Users\imris\AppData\Local\GitHubDesktop\bin;C:\Users\imris\AppData\Local\Microsoft\WindowsApps;C:\Users\imris\AppData\Roaming\npm
9 verbose lifecycle svelte-kit@0.0.1~build: CWD: E:\Traning BOX\socialize-3rd
10 silly lifecycle svelte-kit@0.0.1~build: Args: [ '/d /s /c', 'svelte-kit build' ]
11 silly lifecycle svelte-kit@0.0.1~build: Returned: code: 1  signal: null
12 info lifecycle svelte-kit@0.0.1~build: Failed to exec build script
13 verbose stack Error: svelte-kit@0.0.1 build: `svelte-kit build`
13 verbose stack Exit status 1
13 verbose stack     at EventEmitter.<anonymous> (C:\Program Files (x86)\nodejs\node_modules\npm\node_modules\npm-lifecycle\index.js:332:16)
13 verbose stack     at EventEmitter.emit (events.js:376:20)
13 verbose stack     at ChildProcess.<anonymous> (C:\Program Files (x86)\nodejs\node_modules\npm\node_modules\npm-lifecycle\lib\spawn.js:55:14)
13 verbose stack     at ChildProcess.emit (events.js:376:20)
13 verbose stack     at maybeClose (internal/child_process.js:1055:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:288:5)
14 verbose pkgid svelte-kit@0.0.1
15 verbose cwd E:\Traning BOX\socialize-3rd
16 verbose Windows_NT 10.0.19042
17 verbose argv "C:\\Program Files (x86)\\nodejs\\node.exe" "C:\\Program Files (x86)\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "run" "build"
18 verbose node v14.17.0
19 verbose npm  v6.14.13
20 error code ELIFECYCLE
21 error errno 1
22 error svelte-kit@0.0.1 build: `svelte-kit build`
22 error Exit status 1
23 error Failed at the svelte-kit@0.0.1 build script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 1, true ]
```

I don't even understand the error,
any help would be appreciated 👍👍

**Comment by benmccann** [comment]
There's not enough info here to reproduce your issue

**Comment by sagive** [comment]
My apologies .. what else can i add? 
(and probably how)

its the sveltest latest - 2 weeks old

**Comment by benmccann** [comment]
Can you provide a repository where this occurs?

**Comment by sagive** [comment]
Here it is:
https://github.com/sagive/sveltemp

I don't know how to check what's not working so i cant 
even to try and debug it. May i ask what your checking?

Coming from PHP etc i am used to follow the error message (well.. mostly)..

Thank you very much 🙏

**Comment by benmccann** [comment]
You error logs look very strange. If I run `npm run dev` or `npm run build` I get the following error message, which pretty clearly explains the issue:
```
Error: Failed to resolve import "../firebase_config" from "src/services/firebase.ts". Does the file exist?
    at formatError (node_modules/vite/dist/node/chunks/dep-bc228bbb.js:44564:46)
    at TransformContext.error (node_modules/vite/dist/node/chunks/dep-bc228bbb.js:44560:19)
    at normalizeUrl (node_modules/vite/dist/node/chunks/dep-bc228bbb.js:69451:26)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async TransformContext.transform (node_modules/vite/dist/node/chunks/dep-bc228bbb.js:69584:57)
    at async Object.transform (node_modules/vite/dist/node/chunks/dep-bc228bbb.js:44765:30)
    at async transformRequest (node_modules/vite/dist/node/chunks/dep-bc228bbb.js:59029:29)
    at async instantiateModule (node_modules/vite/dist/node/chunks/dep-bc228bbb.js:68641:10)
```

**Comment by sagive** [comment]
omg, sorry - thats a matter of the git.ignore for that file that holds the DB keys...
its ok, its a temp DB anyhow. i pushed again with this file.

Bassicly i am stuck between 2 errors... 
if I remove the @ from firebase imports dev works but compiling doesn't.
if i add @ to the imports dev works but i get `firebase.auth is not a function`

I don't understand whats the problem... debuggin is weird 
(no page / line numb etc - how you got such a nice error with the file in question?)

**Comment by benmccann** [comment]
This isn't really the best place to ask for help about using a particular library. There's lots of people using Firebase with SvelteKit, so I'd recommend asking on Discord. You might be able to find a blog or something about it as well

**Comment by sagive** [comment]
But.. I am asking about errors in the build process. 
everything works in dev. 
nm, thanks for trying to help.
