### ISSUE TITLE
ReferenceError: fetch is not defined

### ISSUE THREAD

**Issue by istarkov** [sveltejs/kit#1784]
This [change](https://github.com/sveltejs/kit/commit/d729b0848f2f45586c5e19c7b689e6eb2eaee96e#diff-ed48923f0655f935bee505cdcbf40212129ff49a89c2c9d752bd63aa1e6282c4R191
) cause fetch is not defined error with sveltekit + node-adapter.

**Describe the bug**

Build svelte-kit project with node-adapter, 
execute with node v14.16.0, it fails with error "ReferenceError: fetch is not defined"

**Logs**
```
file:///root/realadvisor/netimmo.web/.build/index.js:1836
  serverFetch: hooks.serverFetch || fetch
                                    ^

ReferenceError: fetch is not defined
    at get_hooks (file:///root/realadvisor/netimmo.web/.build/index.js:1836:37)
    at init (file:///root/realadvisor/netimmo.web/.build/index.js:1681:12)
    at file:///root/realadvisor/netimmo.web/.build/index.js:1900:1
    at ModuleJob.run (internal/modules/esm/module_job.js:152:23)
    at async Loader.import (internal/modules/esm/loader.js:166:24)
    at async Object.loadESM (internal/process/esm_loader.js:68:5)
```

**To Reproduce**

```bash
npm init svelte@next my-app # use defaults
cd my-app
npm install @sveltejs/adapter-node@1.0.0-next.29
npm install
```

change svelte.config.js on

```javascript
import node from '@sveltejs/adapter-node';

/** @type {import('@sveltejs/kit').Config} */
const config = {
  kit: {
    // hydrate the <div id="svelte"> element in src/app.html
    target: '#svelte',
    adapter: node({
      out: '.build',
    }),
  },
};

export default config;
```

```bash
npm run build
node build
```

**Comment by stalkerg** [comment]
This `fetch` was in packages/kit/src/runtime/server/page/load_node.js  but now in packages/kit/src/core/dev/index.js hmm.

**Comment by stalkerg** [comment]
This file contain `import '../../install-fetch.js';` and inside we do `globalThis.fetch = fetch;` it's should be enough.

**Comment by stalkerg** [comment]
ok, reproduced and I know how to fix it

**Comment by vfilatov** [comment]
There is a work around while the hotfix above has not been committed yet.

src/hooks.js:
```javascript
/** @type {import('@sveltejs/kit').ServerFetch} */
export async function serverFetch(request) {
  /*
  if (request.url.startsWith('https://api.yourapp.com/')) {
    // clone the original request, but change the URL
    request = new Request(
      request.url.replace('https://api.yourapp.com/', 'http://localhost:9999/'),
      request
    );
  }
  */

  return fetch(request);
}
```
