### ISSUE TITLE
todos demo in dev can not work 

### ISSUE THREAD

**Issue by yehuozhili** [sveltejs/kit#1785]
I  use " npm init svelte@next my-app "  to create the todos demo . 
but  in  " npm run dev"   todos demo sometimes  doesnt work : 

```
request to http://api.svelte.dev/todos/48ae0b1e-0b98-458b-8919-c7542bba5f8d failed, reason: connect EACCES 104.21.42.235:80
FetchError: request to http://api.svelte.dev/todos/48ae0b1e-0b98-458b-8919-c7542bba5f8d failed, reason: connect EACCES 104.21.42.235:80
    at ClientRequest.<anonymous> (file:///D:/zx/my-app/node_modules/@sveltejs/kit/dist/install-fetch.js:1505:11)
    at ClientRequest.emit (events.js:315:20)
    at ClientRequest.EventEmitter.emit (domain.js:486:12)
    at Socket.socketErrorListener (_http_client.js:469:9)
    at Socket.emit (events.js:315:20)
    at Socket.EventEmitter.emit (domain.js:486:12)
    at emitErrorNT (internal/streams/destroy.js:106:8)
    at emitErrorCloseNT (internal/streams/destroy.js:74:3)
    at processTicksAndRejections (internal/process/task_queues.js:80:21)
```
In " npm run preview "  sometimes have this error ：

```
Cannot find module 'D:\zx\my-app\.svelte-kit\output\server\app.js' imported from D:\zx\my-app\node_modules\@sveltejs\kit\dist\chunks\index7.js
Error [ERR_MODULE_NOT_FOUND]: Cannot find module 'D:\zx\my-app\.svelte-kit\output\server\app.js' imported from D:\zx\my-app\node_modules\@sveltejs\kit\dist\chunks\index7.js
    at finalizeResolution (internal/modules/esm/resolve.js:276:11)
    at moduleResolve (internal/modules/esm/resolve.js:699:10)
    at Loader.defaultResolve [as _resolve] (internal/modules/esm/resolve.js:810:11)
    at Loader.resolve (internal/modules/esm/loader.js:85:40)
    at Loader.getModuleJob (internal/modules/esm/loader.js:229:28)
    at Loader.import (internal/modules/esm/loader.js:164:28)
    at importModuleDynamically (internal/modules/esm/translators.js:110:35)
    at exports.importModuleDynamicallyCallback (internal/process/esm_loader.js:30:14)
    at start (file:///D:/zx/my-app/node_modules/@sveltejs/kit/dist/chunks/index7.js:276:50)
    at file:///D:/zx/my-app/node_modules/@sveltejs/kit/dist/cli.js:914:10
```

my sveltekit version is next.119

I think it may be caused by the update. Because I have reported the above error every time after I update some code , and to recover it , I need to reinstall nodemodules

**Comment by benmccann** [comment]
I'm going to close this because it looks like you might have just had a temporary network issue. I haven't seen any other reports of this
