### ISSUE TITLE
build broken in next.119: `fetch is not defined`

### ISSUE THREAD

**Issue by kamholz** [sveltejs/kit#1787]
**Describe the bug**
If I do `npm run build` on SvelteKit next.119, and then try to start the app with `node build`, I get the following error:

```
file://.../app/build/index.js:2502
  serverFetch: hooks.serverFetch || fetch
                                    ^

ReferenceError: fetch is not defined
    at get_hooks (file://.../app/build/index.js:2502:37)
    at init (file://.../app/build/index.js:2207:12)
    at file://.../app/build/index.js:2554:1
    at ModuleJob.run (node:internal/modules/esm/module_job:175:25)
    at async Loader.import (node:internal/modules/esm/loader:178:24)
    at async Object.loadESM (node:internal/process/esm_loader:68:5)
    at async handleMainPromise (node:internal/modules/run_main:63:12)
```

I know that everything worked fine in next.117. This seems to be related to the serverFetch patch. I'm not aware of anything unusual in my code that should have caused it to break. In any case, the error suggests the issue is with SvelteKit itself.

**Information about your SvelteKit Installation:**

```
  System:
    OS: macOS 11.4
    CPU: (8) arm64 Apple M1
    Memory: 254.17 MB / 16.00 GB
    Shell: 3.2.57 - /bin/bash
  Binaries:
    Node: 16.4.0 - /opt/homebrew/bin/node
    npm: 7.19.0 - /opt/homebrew/bin/npm
  Browsers:
    Chrome: 91.0.4472.114
    Safari: 14.1.1
  npmPackages:
    @sveltejs/adapter-node: ^1.0.0-next.29 => 1.0.0-next.29 
    @sveltejs/kit: ^1.0.0-next.119 => 1.0.0-next.119 
    svelte: ^3.37.0 => 3.38.2
```

**Severity**
Highest. This makes it impossible for me to use SvelteKit on next.119.

**Comment by kamholz** [comment]
I see this is a duplicate, sorry!
