### ISSUE TITLE
ReferenceError: document is not defined

### ISSUE THREAD

**Issue by V0RT4C** [sveltejs/kit#1800]
**Describe the bug**
Built svelte-kit with node-adapter. After building the app and then starting it with "node build" the server starts and so far so good.
However, immediately when trying to load a page:

**Logs**

> ReferenceError: document is not defined
    at file:///home/arai/Documents/Projekt/sveltekit-test/build/index.js:2548:5
    at run (file:///home/arai/Documents/Projekt/sveltekit-test/build/index.js:1245:10)
    at Array.forEach (<anonymous>)
    at run_all (file:///home/arai/Documents/Projekt/sveltekit-test/build/index.js:1251:7)
    at Object.render (file:///home/arai/Documents/Projekt/sveltekit-test/build/index.js:1395:7)
    at render_response (file:///home/arai/Documents/Projekt/sveltekit-test/build/index.js:402:32)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async respond$1 (file:///home/arai/Documents/Projekt/sveltekit-test/build/index.js:937:12)
    at async render_page (file:///home/arai/Documents/Projekt/sveltekit-test/build/index.js:968:22)
    at async resolve (file:///home/arai/Documents/Projekt/sveltekit-test/build/index.js:1210:93)

This only happens when you force a refresh. When navigating around in the application everything seems fine until you inspect the source code where you will find that no HTML source has been generated either.

I am using load function to load data async before page load.

**Steps to reproduce*
1.
>npm init svelte@next my-app
cd my-app
npm install @sveltejs/adapter-node@next
npm install

2. Create a new page. Fetch data with load.
3. Build application and start server.
4. Navigate to the page.

**Specification**
Using NodeJS 14.16.0
@sveltejs/adapter-node: ^1.0.0-next.29
@sveltejs/kit: next

**Comment by V0RT4C** [comment]
Error was not related to adapter-node

**Comment by milcaunicorn** [comment]
What was the error then?
