### ISSUE TITLE
adapters will not load - adapter should be an object with an "adapt" method

### ISSUE THREAD

**Issue by robhicks** [sveltejs/kit#1812]
**Describe the bug**
I can't install any official adapter with the default settings. 

**Logs**
```shell
config.kit.adapter should be an object with an "adapt" method. See https://kit.svelte.dev/docs#adapters
Error: config.kit.adapter should be an object with an "adapt" method. See https://kit.svelte.dev/docs#adapters
    at Object.validate (file:///home/robhicks/Development/give-svelte/node_modules/@sveltejs/kit/dist/cli.js:189:13)
    at validate (file:///home/robhicks/Development/give-svelte/node_modules/@sveltejs/kit/dist/cli.js:583:28)
    at validate (file:///home/robhicks/Development/give-svelte/node_modules/@sveltejs/kit/dist/cli.js:581:19)
    at validate_config (file:///home/robhicks/Development/give-svelte/node_modules/@sveltejs/kit/dist/cli.js:670:20)
    at load_config (file:///home/robhicks/Development/give-svelte/node_modules/@sveltejs/kit/dist/cli.js:647:20)
    at async get_config (file:///home/robhicks/Development/give-svelte/node_modules/@sveltejs/kit/dist/cli.js:784:10)
    at async file:///home/robhicks/Development/give-svelte/node_modules/@sveltejs/kit/dist/cli.js:842:18
error Command failed with exit code 1.

```
**To Reproduce**
Try to install any official adapter with SvelteKit v1.0.0-next.118

**Information about your SvelteKit Installation:**
System:
    OS: Linux 5.12 Fedora 34 (Workstation Edition) 34 (Workstation Edition)
    CPU: (12) x64 Intel(R) Core(TM) i7-9850H CPU @ 2.60GHz
    Memory: 7.35 GB / 31.11 GB
    Container: Yes
    Shell: 5.8 - /usr/bin/zsh
  Binaries:
    Node: 14.16.1 - ~/.nvm/versions/node/v14.16.1/bin/node
    Yarn: 1.22.10 - ~/.nvm/versions/node/v14.16.1/bin/yarn
    npm: 6.14.12 - ~/.nvm/versions/node/v14.16.1/bin/npm
    Watchman: 0.0.0 - /usr/bin/watchman
  Browsers:
    Chrome: 91.0.4472.114
    Firefox: 89.0.2
  npmPackages:
    @sveltejs/adapter-node: ^1.0.0-next.0 => 1.0.0-next.0 
    @sveltejs/kit: next => 1.0.0-next.118 
    svelte: ^3.38.3 => 3.38.3

**Comment by babichjacob** [comment]
Install the `@next` version of adapters, not latest: https://github.com/sveltejs/kit/issues/1701#issuecomment-863528033
