### ISSUE TITLE
node build throws TypeError for @sveltejs/adapter-node

### ISSUE THREAD

**Issue by robhicks** [sveltejs/kit#1813]
**Describe the bug**
node build throws a TypeError

**To Reproduce**
1. install next version of SvelteKit.
2. install next version of @sveltejs/adapter-nod3

**Expected behavior**
The app should run. 

**System**
```
System:
    OS: Linux 5.12 Fedora 34 (Workstation Edition) 34 (Workstation Edition)
    CPU: (12) x64 Intel(R) Core(TM) i7-9850H CPU @ 2.60GHz
    Memory: 7.12 GB / 31.11 GB
    Container: Yes
    Shell: 5.8 - /usr/bin/zsh
  Binaries:
    Node: 14.16.1 - ~/.nvm/versions/node/v14.16.1/bin/node
    Yarn: 1.22.10 - ~/.nvm/versions/node/v14.16.1/bin/yarn
    npm: 6.14.12 - ~/.nvm/versions/node/v14.16.1/bin/npm
    Watchman: 0.0.0 - /usr/bin/watchman
  Browsers:
    Chrome: 91.0.4472.114
    Firefox: 89.0.2
  npmPackages:
    @sveltejs/adapter-node: ^1.0.0-next.30 => 1.0.0-next.30 
    @sveltejs/kit: next => 1.0.0-next.118 
    svelte: ^3.38.3 => 3.38.3
```

**Stacktraces**
```shell
file:///home/robhicks/Development/give-svelte/build/index.js:1549
  set_paths(settings.paths);
                     ^

TypeError: Cannot read property 'paths' of undefined
    at init (file:///home/robhicks/Development/give-svelte/build/index.js:1549:22)
    at file:///home/robhicks/Development/give-svelte/build/index.js:15207:1
    at ModuleJob.run (internal/modules/esm/module_job.js:152:23)
    at async Loader.import (internal/modules/esm/loader.js:166:24)
    at async Object.loadESM (internal/process/esm_loader.js:68:5)
error Command failed with exit code 1.
```
**Severity**
SvelteKit cannot be deployed on a node server.

**Comment by robhicks** [comment]
can't reproduce

**Comment by olsn** [comment]
I had the same issue - turns out it was my own mistake:
--> A local mismatch of my installed versions svelte-kit and @sveltejs/adapter-node

**Comment by yadoga** [comment]
> --> A local mismatch of my installed versions svelte-kit and @sveltejs/adapter-node

thanks, this solved the same issue for me, too.
