### ISSUE TITLE
Dynamic API route fails on build - ENOTDIR error

### ISSUE THREAD

**Issue by ekafyi** [sveltejs/kit#1815]
I have checked the Discord but have not found a solution. _Could_ be a bug, so reporting here.

Building dynamic API routes fails with this error:

>  ENOTDIR: not a directory, open 'build/api/sample_locations/foo.json'

```bash
Error: ENOTDIR: not a directory, open 'build/api/sample_locations/foo.json'
    at Object.openSync (node:fs:582:3)
    at writeFileSync (node:fs:2143:35)
    at file:///Users/MY_PROJECT_PATH/node_modules/@sveltejs/kit/dist/chunks/index7.js:192:5
    at Map.forEach (<anonymous>)
    at visit (file:///Users/MY_PROJECT_PATH/node_modules/@sveltejs/kit/dist/chunks/index7.js:179:17)
    at async prerender (file:///Users/MY_PROJECT_PATH/node_modules/@sveltejs/kit/dist/chunks/index7.js:248:4)
    at async Object.prerender (file:///Users/MY_PROJECT_PATH/node_modules/@sveltejs/kit/dist/chunks/index7.js:312:5)
    at async adapt (file:///Users/MY_PROJECT_PATH/node_modules/@sveltejs/adapter-static/index.js:17:4)
    at async adapt (file:///Users/MY_PROJECT_PATH/node_modules/@sveltejs/kit/dist/chunks/index7.js:338:2)
    at async file:///Users/MY_PROJECT_PATH/node_modules/@sveltejs/kit/dist/cli.js:656:5
```

The entire site is fully static and I'd like to build it as SSG (like Nextjs' `getStaticProps` and `getStaticPaths`). This error only occurs in build. Everything works perfectly in dev. 

I use adapter-static with default config.

```js
// svelte.config.js
export default {
	// Consult https://github.com/sveltejs/svelte-preprocess
	preprocess: [
		preprocess({
			postcss: true,
		}),
	],
	kit: {
		adapter: adapterStatic(),
		target: "#svelte",
		prerender: {
			crawl: false,
			enabled: true,
			force: false,
			pages: ["*", "/foo", "/bar"],
		},
	},
};
```

API route code:
```js
// src/routes/api/sample_locations/[slug].json.ts
export const get: RequestHandler = async ({ params }) => {
	const { slug } = params;
	// dummy hardcoded data to isolate the issue
	return {
		status: 200,
		body: {
			payload: { id: "123", name: "test item", slug },
		},
	};
};
```

page route code:
```
// src/routes/[slug].svelte
<script lang="ts" context="module">
	import type { Load } from "@sveltejs/kit";

	export const load: Load = async ({ page, fetch }) => {
		const slug = page.params.slug;

		const res = await fetch(`/api/sample_locations/${slug}.json`);

		if (res.ok) {
			const { payload } = await res.json();
			return {
				props: { location: payload },
			};
		}
		return {
			error: new Error(`Could not load data`),
		};
	};
</script>

<script lang="ts">
	export let location;
</script>

{#if location}
	<h1>{location.name || "no location name"}</h1>
{/if}
```

### Related

Someone posted the exact same error in Svelte Discord: https://discord.com/channels/457912077277855764/819723698415599626/860792596241711115 but there was no further discussion on it

Another post in Discord suggested clearing the build folder, but it didnt work for me https://discord.com/channels/457912077277855764/819723698415599626/823172383233409035

**Comment by ignatiusmb** [comment]
Can you provide a small repo? Also, can you run this and paste the output in a `details` tag. Hard guessing from issue not filled using the template, your installation might be outdated.

```
npx envinfo --system --npmPackages svelte,@sveltejs/kit,@sveltejs/adapter-node,@sveltejs/adapter-static,@sveltejs/adapter-begin,@sveltejs/adapter-netlify,@sveltejs/adapter-vercel vite --binaries --browsers
```

**Comment by ignatiusmb** [comment]
Closing due to inactivity and lack of information.
