### ISSUE TITLE
adapter-netlify next.18 breaks application 

### ISSUE THREAD

**Issue by bekos** [sveltejs/kit#1818]
After upgrading netlify-adapter from `.17` to `.18`  we get the following error when running the application on Netlify:

```
"errorType":"TypeError",
"errorMessage":"Cannot read property 'paths' of undefined",
"trace":[
    "TypeError: Cannot read property 'paths' of undefined",
    "    at init (/var/task/index.js:27711:22)",
    "    at Object.<anonymous> (/var/task/index.js:63127:1)",
    "    at Module._compile (internal/modules/cjs/loader.js:999:30)",
    "    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)",
    "    at Module.load (internal/modules/cjs/loader.js:863:32)",
    "    at Function.Module._load (internal/modules/cjs/loader.js:708:14)",
    "    at Module.require (internal/modules/cjs/loader.js:887:19)",
    "    at require (internal/modules/cjs/helpers.js:74:18)",
    "    at Object.<anonymous> (/var/task/render.js:1:18)",
    "    at Module._compile (internal/modules/cjs/loader.js:999:30)"
]
```

**Comment by benmccann** [comment]
I just upgraded my project to `.18` and did not have any issues. Can you provide a repo that reproduces this? Does this happen at build time or runtime?

**Comment by bekos** [comment]
This happens only on runtime. Unfortunately, I cannot share my repo and didn't have time to narrow it down 😞

**Comment by bekos** [comment]
Sorry for the noise, seems that upgrading Sveltekit to latest fixes it 🙈
