### ISSUE TITLE
caNN 

### ISSUE THREAD

**Issue by whiddershins** [sveltejs/kit#1828]
**Describe the bug**
Initial setup of sveltkit fails

**Logs**
npx: installed 5 in 1.139s
/Users/xxxx/.npm/_npx/37606/lib/node_modules/create-svelte/bin.js:2
import fs from 'fs';
^^^^^^

SyntaxError: Cannot use import statement outside a module

SyntaxError: Cannot use import statement outside a module
    at Module._compile (internal/modules/cjs/loader.js:895:18)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:995:10)
    at Module.load (internal/modules/cjs/loader.js:815:32)
    at Function.Module._load (internal/modules/cjs/loader.js:727:14)
    at Function.Module.runMain (internal/modules/cjs/loader.js:1047:10)
    at internal/main/run_main_module.js:17:11

**To Reproduce**
npm init svelte@next my-app

**Expected behavior**
a sveltkit app to scaffold itself

**Severity**
Prevents all usage of SvelteKit

Note: the more honest and specific you are here the more we will take you seriously.

**Additional context**

**Comment by dummdidumm** [comment]
What node version are you using? You need at least the latest 12.x .

**Comment by whiddershins** [comment]
it was 12.1.3, but you are right, updating to 14.17.2 fixed it, thank you
