### ISSUE TITLE
Error with sveltekit with svelte-apollo and adapter-netlify: Function called outside component initialization

### ISSUE THREAD

**Issue by v-bornov** [sveltejs/kit#1941]
### Describe the bug

I was using sveltekit with svelte-apollo and got error
"Function called outside component initialization"

And I've fixed it with changes in svelte.config.js

```
optimizeDeps: {
  exclude: ["svelte-apollo"],
},
```

But when I deploy my project with adapter-netlify

```
import preprocess from 'svelte-preprocess';
import adapter from '@sveltejs/adapter-netlify';

/** @type {import('@sveltejs/kit').Config} */
const config = {
	// Consult https://github.com/sveltejs/svelte-preprocess
	// for more information about preprocessors
	preprocess: [preprocess({
        "postcss": true
    })],

	kit: {
		adapter: adapter(), // currently the adapter does not take any options

		// hydrate the <div id="svelte"> element in src/app.html
		target: '#svelte',

		vite: {
			optimizeDeps: {
				exclude: ["svelte-apollo"],
			},
		}
	}
};

export default config;
```

I got the same error

```
Error: Function called outside component initialization
    at get_current_component (C:\Users\vbornov\Projects\svelte-try\node_modules\svelte\internal\index.js:816:15)
    at Object.setContext (C:\Users\vbornov\Projects\svelte-try\node_modules\svelte\internal\index.js:846:5)
    at setClient (C:\Users\vbornov\Projects\svelte-try\node_modules\svelte-apollo\dist\svelte-apollo.cjs.js:18:12)
    at file:///C:/Users/vbornov/Projects/svelte-try/.svelte-kit/output/server/app.js:288:3
    at Object.$$render (file:///C:/Users/vbornov/Projects/svelte-try/.svelte-kit/output/server/app.js:82:18)
    at file:///C:/Users/vbornov/Projects/svelte-try/.svelte-kit/output/server/app.js:155:78
    at $$render (file:///C:/Users/vbornov/Projects/svelte-try/.svelte-kit/output/server/app.js:82:18)
    at Object.render (file:///C:/Users/vbornov/Projects/svelte-try/.svelte-kit/output/server/app.js:90:20)
    at render_response (file:///C:/Users/vbornov/Projects/svelte-try/node_modules/@sveltejs/kit/dist/ssr.js:379:28)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
```

How to fix this error in @sveltejs/adapter-netlify ?

### Reproduction

https://github.com/v-bornov/svelte-try

### System Info

```shell
System:
    OS: Windows 10 10.0.19043
    CPU: (8) x64 Intel(R) Core(TM) i5-10210U CPU @ 1.60GHz
    Memory: 8.82 GB / 15.76 GB
  Binaries:
    Node: 14.15.5 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.10 - ~\AppData\Roaming\npm\yarn.CMD
    npm: 7.20.0 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Chrome: 91.0.4472.124
    Edge: Spartan (44.19041.1023.0), Chromium (91.0.864.70)
    Internet Explorer: 11.0.19041.1
  npmPackages:
    @sveltejs/adapter-netlify: ^1.0.0-next.23 => 1.0.0-next.23
    @sveltejs/kit: next => 1.0.0-next.131
    svelte: ^3.34.0 => 3.38.3
```

### Severity

annoyance

**Comment by benmccann** [comment]
I see they have a PR for SvelteKit support: https://github.com/timhall/svelte-apollo/pull/98. This is probably better to address in that repo unless it's clearly demonstrated that there's a bug in SvelteKit
