### ISSUE TITLE
"Cannot read property 'split' of undefined" is back with 1.0.0-next.132, eveything is ok with 1.0.0-next.131

### ISSUE THREAD

**Issue by quentincaffeino** [sveltejs/kit#1978]
### Describe the bug

Unable to dev or build on 1.0.0-next.132 due to `Cannot read property 'split' of undefined`

### Reproduction

Repro is my github page which is very scarce so I hope it can be useful.

Run:
```sh
git clone git@github.com:quentincaffeino/quentincaffeino.github.io.git
cd quentincaffeino.github.io
git checkout split-of-undefined-repro
pnpm i
pnpm dev -- --open
```

### Logs

```shell
Cannot read property 'split' of undefined
TypeError: Cannot read property 'split' of undefined
    at parse_body (file:///home/quentincaffeino/projects/quentincaffeino/quentincaffeino.github.io/node_modules/.pnpm/@sveltejs+kit@1.0.0-next.132_svelte@3.38.3/node_modules/@sveltejs/kit/dist/ssr.js:1425:57)
    at respond (file:///home/quentincaffeino/projects/quentincaffeino/quentincaffeino.github.io/node_modules/.pnpm/@sveltejs+kit@1.0.0-next.132_svelte@3.38.3/node_modules/@sveltejs/kit/dist/ssr.js:1557:11)
    at Object.fetch (file:///home/quentincaffeino/projects/quentincaffeino/quentincaffeino.github.io/node_modules/.pnpm/@sveltejs+kit@1.0.0-next.132_svelte@3.38.3/node_modules/@sveltejs/kit/dist/ssr.js:737:29)
    at Module.fetchGithubData (/src/lib/api/github.js:34:6)
    at load (index.svelte:10:42)
    at load_node (file:///home/quentincaffeino/projects/quentincaffeino/quentincaffeino.github.io/node_modules/.pnpm/@sveltejs+kit@1.0.0-next.132_svelte@3.38.3/node_modules/@sveltejs/kit/dist/ssr.js:857:30)
    at respond$1 (file:///home/quentincaffeino/projects/quentincaffeino/quentincaffeino.github.io/node_modules/.pnpm/@sveltejs+kit@1.0.0-next.132_svelte@3.38.3/node_modules/@sveltejs/kit/dist/ssr.js:1078:21)
    at async render_page (file:///home/quentincaffeino/projects/quentincaffeino/quentincaffeino.github.io/node_modules/.pnpm/@sveltejs+kit@1.0.0-next.132_svelte@3.38.3/node_modules/@sveltejs/kit/dist/ssr.js:1225:20)
    at async resolve (file:///home/quentincaffeino/projects/quentincaffeino/quentincaffeino.github.io/node_modules/.pnpm/@sveltejs+kit@1.0.0-next.132_svelte@3.38.3/node_modules/@sveltejs/kit/dist/ssr.js:1580:10)
    at async respond (file:///home/quentincaffeino/projects/quentincaffeino/quentincaffeino.github.io/node_modules/.pnpm/@sveltejs+kit@1.0.0-next.132_svelte@3.38.3/node_modules/@sveltejs/kit/dist/ssr.js:1553:10)
{
  has: [ 1, 31 ],
  keys: [
    { open: '\x1B[1m', close: '\x1B[22m', rgx: /\x1b\[22m/g },
    { open: '\x1B[31m', close: '\x1B[39m', rgx: /\x1b\[39m/g }
  ],
  reset: [Function: bound ],
  bold: [Function: bound ],
  dim: [Function: bound ],
  italic: [Function: bound ],
  underline: [Function: bound ],
  inverse: [Function: bound ],
  hidden: [Function: bound ],
  strikethrough: [Function: bound ],
  black: [Function: bound ],
  red: [Function: bound ],
  green: [Function: bound ],
  yellow: [Function: bound ],
  blue: [Function: bound ],
  magenta: [Function: bound ],
  cyan: [Function: bound ],
  white: [Function: bound ],
  gray: [Function: bound ],
  grey: [Function: bound ],
  bgBlack: [Function: bound ],
  bgRed: [Function: bound ],
  bgGreen: [Function: bound ],
  bgYellow: [Function: bound ],
  bgBlue: [Function: bound ],
  bgMagenta: [Function: bound ],
  bgCyan: [Function: bound ],
  bgWhite: [Function: bound ]
}
{
  has: [ 90 ],
  keys: [ { open: '\x1B[90m', close: '\x1B[39m', rgx: /\x1b\[39m/g } ],
  reset: [Function: bound ],
  bold: [Function: bound ],
  dim: [Function: bound ],
  italic: [Function: bound ],
  underline: [Function: bound ],
  inverse: [Function: bound ],
  hidden: [Function: bound ],
  strikethrough: [Function: bound ],
  black: [Function: bound ],
  red: [Function: bound ],
  green: [Function: bound ],
  yellow: [Function: bound ],
  blue: [Function: bound ],
  magenta: [Function: bound ],
  cyan: [Function: bound ],
  white: [Function: bound ],
  gray: [Function: bound ],
  grey: [Function: bound ],
  bgBlack: [Function: bound ],
  bgRed: [Function: bound ],
  bgGreen: [Function: bound ],
  bgYellow: [Function: bound ],
  bgBlue: [Function: bound ],
  bgMagenta: [Function: bound ],
  bgCyan: [Function: bound ],
  bgWhite: [Function: bound ]
}
```

### System Info

```shell
System:
    OS: Linux 5.9 elementary OS 5.1.7 Hera
    CPU: (6) x64 Intel(R) Core(TM) i5-8600K CPU @ 3.60GHz
    Memory: 1.27 GB / 31.30 GB
    Container: Yes
    Shell: 4.4.20 - /bin/bash
  Binaries:
    Node: 16.1.0 - ~/.local/bin/node
    Yarn: 1.22.5 - ~/.npm-global/bin/yarn
    npm: 7.11.2 - ~/.local/bin/npm
  Browsers:
    Brave Browser: 91.1.26.74
  npmPackages:
    @sveltejs/adapter-static: ^1.0.0-next.13 => 1.0.0-next.13 
    @sveltejs/kit: v1.0.0-next.131 => 1.0.0-next.131 
    svelte: ^3.38.3 => 3.38.3
```

### Severity

blocking an upgrade

**Comment by benmccann** [comment]
@quentincaffeino I can't run your example. There are multiple issues with it, but it seems that perhaps it requires a `VITE_GH_OAUTH_TOKEN`: https://github.com/sveltejs/kit/issues/1982#issuecomment-884497301. Can you share an example that I can run without needing to setup any accounts or credentials?

**Comment by quentincaffeino** [comment]
@benmccann, sorry, I completely forgot about that, I've pushed updated code to `split-of-undefined-repro` branch. Now reproduction would be:

```
git clone git@github.com:quentincaffeino/quentincaffeino.github.io.git
cd quentincaffeino.github.io
git checkout split-of-undefined-repro
pnpm i
pnpm dev -- --open
```

(also updated in first message)

Also now it is a completely different error. On 131 fetch completes successfully, and on 132 I get 404. It seems like it is trying to find that url inside svelte kit even though it does not match the url at all.

**Comment by benmccann** [comment]
That was fixed yesterday. Update to the latest SvelteKit
