### ISSUE TITLE
node scripts/build-templates fails on Windows

### ISSUE THREAD

**Issue by ryc76** [sveltejs/kit#2025]
### Describe the bug

Running node scripts/build-templates on Windows results in failure

```
(node:9796) UnhandledPromiseRejectionWarning: Error: EISDIR: illegal operation on a directory, read
    at Object.readSync (fs.js:592:3)
    at tryReadSync (fs.js:366:20)
    at Object.readFileSync (fs.js:403:19)
    at file:///C:/Users/SDE/WebstormProjects/teemu/packages/kit/packages/create-svelte/scripts/build-templates.js:157:24
    at Array.map (<anonymous>)
    at generate_shared (file:///C:/Users/SDE/WebstormProjects/teemu/packages/kit/packages/create-svelte/scripts/build-templates.js:156:4)
    at main (file:///C:/Users/SDE/WebstormProjects/teemu/packages/kit/packages/create-svelte/scripts/build-templates.js:196:23)
    at file:///C:/Users/SDE/WebstormProjects/teemu/packages/kit/packages/create-svelte/scripts/build-templates.js:200:1
    at ModuleJob.run (internal/modules/esm/module_job.js:152:23)
    at async Loader.import (internal/modules/esm/loader.js:166:24)
```

### Reproduction

Run node scripts\build-templates

### System Info

```shell
System:
    OS: Windows 10 10.0.19043
    CPU: (4) x64 Intel(R) Core(TM) i5-4570 CPU @ 3.20GHz
    Memory: 6.14 GB / 15.91 GB
  Binaries:
    Node: 14.16.0 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.4 - ~\AppData\Roaming\npm\yarn.CMD
    npm: 6.14.11 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Chrome: 92.0.4515.107
    Edge: Spartan (44.19041.1023.0), Chromium (92.0.902.55)
    Internet Explorer: 11.0.19041.1
  npmPackages:
    @sveltejs/eslint-config: github:sveltejs/eslint-config#v5.7.0 => 5.7.0
```

### Severity

annoyance

**Comment by Conduitry** [comment]
I can't reproduce this. This runs fine for me on Windows 10.

**Comment by Mlocik97** [comment]
I can't reproduce too.
