### ISSUE TITLE
Won't build with Firebase and Vercel Adapter

### ISSUE THREAD

**Issue by schnetzlerjoe** [sveltejs/kit#2053]
### Describe the bug

I cannot build and launch on vercel with the vercel adaptor and firebase.

### Reproduction

When I try to use firebase and Vercel adaptor with Svelte kit and run npm run build, the following error occurs (check the logs).

1. Create a blank project
2. Add firebase to it (Auth, Firestore, etc)
3. Add the vercel adaptor
4. Run npm run build

### Logs

```shell
16:01:49.198  	> Using @sveltejs/adapter-vercel
16:01:49.892  	> firebase.registerVersion is not a function
16:01:49.892  	TypeError: firebase.registerVersion is not a function
16:01:49.893  	    at file:///vercel/path0/node_modules/firebase/compat/app/dist/index.esm.js:23:10
16:01:49.893  	    at ModuleJob.run (internal/modules/esm/module_job.js:169:25)
16:01:49.893  	    at async Loader.import (internal/modules/esm/loader.js:177:24)
16:01:49.893  	    at async prerender (file:///vercel/path0/node_modules/@sveltejs/kit/dist/chunks/index6.js:113:14)
16:01:49.893  	    at async Object.prerender (file:///vercel/path0/node_modules/@sveltejs/kit/dist/chunks/index6.js:338:5)
16:01:49.893  	    at async adapt (file:///vercel/path0/node_modules/@sveltejs/adapter-vercel/index.js:56:4)
16:01:49.893  	    at async adapt (file:///vercel/path0/node_modules/@sveltejs/kit/dist/chunks/index6.js:383:2)
16:01:49.893  	    at async file:///vercel/path0/node_modules/@sveltejs/kit/dist/cli.js:959:5
```

### System Info

```shell
System:
    OS: Windows 10 10.0.18363
    CPU: (4) x64 Intel(R) Core(TM) i3-4020Y CPU @ 1.50GHz
    Memory: 494.73 MB / 3.91 GB
  Binaries:
    Node: 14.17.3 - C:\Program Files\nodejs\node.EXE
    npm: 7.11.2 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Chrome: 91.0.4472.124
    Edge: Spartan (44.18362.1474.0)
    Internet Explorer: 11.0.18362.1
  npmPackages:
    @sveltejs/adapter-vercel: next => 1.0.0-next.26
    @sveltejs/kit: next => 1.0.0-next.139
    svelte: ^3.34.0 => 3.41.0
    "@sveltejs/adapter-vercel": "next",
    "@sveltejs/kit": "next",
    "firebase": "^9.0.0-beta.7",
    "firebase-admin": "^9.11.0",
    "sirv-cli": "^1.0.0",
    "svelte": "^3.34.0",
    "svelte-switch": "0.0.4",
    "sveltefire": "^0.1.5",
    "vercel": "^23.0.1"
```

### Severity

blocking all usage of SvelteKit

**Comment by abdo643-HULK** [comment]
The Issue can be closed. It has been solved with [](https://github.com/sveltejs/kit/issues/1850)
