### ISSUE TITLE
Cannot run npm run dev

### ISSUE THREAD

**Issue by justingolden21** [sveltejs/kit#2162]
### Describe the bug

`npm run dev` crashes and nothing works.

I am new to svelte kit, but just starting with the boilerplate everything crashes.

### Reproduction

```
npm init svelte@next colors
cd colors
npx svelte-add tailwindcss --jit
npm i
```

chose skeleton app without typescript, with eslint and prettier

---

added adapter as seen: https://kit.svelte.dev/docs#adapters

netlify adapter: https://github.com/sveltejs/kit/tree/master/packages/adapter-netlify

`npm i -D @sveltejs/adapter-netlify@next`

in `svelte.config.js`: `import adapter from '@sveltejs/adapter-netlify';` and

```
	kit: {
		adapter: adapter(),
```

add netlify.toml

ran `npm run dev`

```cmd
npm run dev

> ~TODO~@0.0.1 dev
> svelte-kit dev


  SvelteKit v1.0.0-next.146

  network: not exposed
  local:   http://localhost:3000

  Use --host to expose server to other devices on this network


events.js:292
      throw er; // Unhandled 'error' event
      ^

Error: listen EADDRINUSE: address already in use 127.0.0.1:3000
    at Server.setupListenHandle [as _listen2] (net.js:1318:16)
    at listenInCluster (net.js:1366:12)
    at GetAddrInfoReqWrap.doListen [as callback] (net.js:1503:7)
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:69:8)
Emitted 'error' event on Server instance at:
    at emitErrorNT (net.js:1345:8)
    at processTicksAndRejections (internal/process/task_queues.js:80:21) {
  code: 'EADDRINUSE',
  errno: -4091,
  syscall: 'listen',
  address: '127.0.0.1',
  port: 3000
}
npm ERR! code 1
npm ERR! path C:\Users\Justin\Documents\GitHub\colors
npm ERR! command failed
npm ERR! command C:\WINDOWS\system32\cmd.exe /d /s /c svelte-kit dev

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Justin\AppData\Local\npm-cache\_logs\2021-08-11T01_02_34_209Z-debug.log
PS C:\Users\Justin\Documents\GitHub\colors>
```

### Logs

```shell
npm log

0 verbose cli [
0 verbose cli   'C:\\Program Files\\nodejs\\node.exe',
0 verbose cli   'C:\\Users\\Justin\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js',
0 verbose cli   'run',
0 verbose cli   'dev'
0 verbose cli ]
1 info using npm@7.5.4
2 info using node@v14.15.5
3 timing config:load:defaults Completed in 1ms
4 timing config:load:file:C:\Users\Justin\AppData\Roaming\npm\node_modules\npm\npmrc Completed in 1ms
5 timing config:load:builtin Completed in 2ms
6 timing config:load:cli Completed in 2ms
7 timing config:load:env Completed in 0ms
8 timing config:load:file:C:\Users\Justin\Documents\GitHub\colors\.npmrc Completed in 0ms
9 timing config:load:project Completed in 1ms
10 timing config:load:file:C:\Users\Justin\.npmrc Completed in 0ms
11 timing config:load:user Completed in 0ms
12 timing config:load:file:C:\Users\Justin\AppData\Roaming\npm\etc\npmrc Completed in 0ms
13 timing config:load:global Completed in 0ms
14 timing config:load:cafile Completed in 0ms
15 timing config:load:validate Completed in 0ms
16 timing config:load:setUserAgent Completed in 0ms
17 timing config:load:setEnvs Completed in 1ms
18 timing config:load Completed in 8ms
19 verbose npm-session 52bd74e5596b6ade
20 timing npm:load Completed in 18ms
21 timing command:run-script Completed in 638ms
22 verbose stack Error: command failed
22 verbose stack     at ChildProcess.<anonymous> (C:\Users\Justin\AppData\Roaming\npm\node_modules\npm\node_modules\@npmcli\promise-spawn\index.js:64:27)
22 verbose stack     at ChildProcess.emit (events.js:315:20)
22 verbose stack     at maybeClose (internal/child_process.js:1048:16)
22 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:288:5)
23 verbose pkgid ~TODO~@0.0.1
24 verbose cwd C:\Users\Justin\Documents\GitHub\colors
25 verbose Windows_NT 10.0.19042
26 verbose argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\Justin\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js" "run" "dev"
27 verbose node v14.15.5
28 verbose npm  v7.5.4
29 error code 1
30 error path C:\Users\Justin\Documents\GitHub\colors
31 error command failed
32 error command C:\WINDOWS\system32\cmd.exe /d /s /c svelte-kit dev
33 verbose exit 1
```
```


### System Info

```shell
Microsoft Windows [Version 10.0.19042.1110]
(c) Microsoft Corporation. All rights reserved.

C:\Users\Justin>npx envinfo --system --binaries --browsers --npmPackages "{svelte,@sveltejs/*,vite}"
Need to install the following packages:
  envinfo
Ok to proceed? (y) y

  System:
    OS: Windows 10 10.0.19042
    CPU: (12) x64 AMD Ryzen 5 1600 Six-Core Processor
    Memory: 6.47 GB / 15.95 GB
  Binaries:
    Node: 14.15.5 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.10 - ~\AppData\Roaming\npm\yarn.CMD
    npm: 7.5.4 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Chrome: 92.0.4515.131
    Edge: Spartan (44.19041.1023.0), Chromium (92.0.902.67)


C:\Users\Justin>
```

### Severity

serious, but I can work around it

**Comment by justingolden21** [comment]
Worth noting even after removing `import adapter from '@sveltejs/adapter-netlify';` and `adapter: adapter(),` it still fails

**Comment by justingolden21** [comment]
I had something else on that port. Still, this error should be handled gracefully, so I will keep this issue open for the time being. Thank you in advance for looking into this.

**Comment by Conduitry** [comment]
Deciding what to do when the port is occupied already has an issue, #2020. Closing this one.
