### ISSUE TITLE
Netlify Adapter Bug: The requested module 'svelte-hmr' does not provide an export named 'createMakeHot'

### ISSUE THREAD

**Issue by justingolden21** [sveltejs/kit#2173]
### Describe the bug

`The requested module 'svelte-hmr' does not provide an export named 'createMakeHot'` appears in Netlify and the build / deploy fails.

### Reproduction

These are the steps I followed (I took notes)

added adapter as seen: https://kit.svelte.dev/docs#adapters

netlify adapter: https://github.com/sveltejs/kit/tree/master/packages/adapter-netlify

`npm i -D @sveltejs/adapter-netlify@next`

in `svelte.config.js`: `import adapter from '@sveltejs/adapter-netlify';` and

```
kit: {
adapter: adapter(),
```

add netlify.toml

### Logs

```shell
<details>
<summary>Log from Netlify</summary>

1:28:00 AM: Build ready to start
1:28:02 AM: build-image version: c6001ed68662a13e5deb24abec2b46058c58248a
1:28:02 AM: build-image tag: v3.9.0
1:28:02 AM: buildbot version: f5b2aaa509f86a61b2b0b2186483ad1252cb9397
1:28:02 AM: Fetching cached dependencies
1:28:02 AM: Failed to fetch cache, continuing with build
1:28:02 AM: Starting to prepare the repo for build
1:28:02 AM: No cached dependencies found. Cloning fresh repo
1:28:02 AM: git clone https://github.com/justingolden21/colors
1:28:03 AM: Preparing Git Reference refs/heads/main
1:28:04 AM: Parsing package.json dependencies
1:28:04 AM: Different publish path detected, going to use the one specified in the Netlify configuration file: 'build/publish' versus 'build/publish/' in the Netlify UI
1:28:04 AM: Different functions path detected, going to use the one specified in the Netlify configuration file: 'build/functions' versus 'build/functions/' in the Netlify UI
1:28:05 AM: Starting build script
1:28:05 AM: Installing dependencies
1:28:05 AM: Python version set to 2.7
1:28:06 AM: v12.18.0 is already installed.
1:28:06 AM: Now using node v12.18.0 (npm v6.14.4)
1:28:06 AM: Started restoring cached build plugins
1:28:06 AM: Finished restoring cached build plugins
1:28:06 AM: Attempting ruby version 2.7.2, read from environment
1:28:08 AM: Using ruby version 2.7.2
1:28:08 AM: Using PHP version 5.6
1:28:08 AM: Started restoring cached node modules
1:28:08 AM: Finished restoring cached node modules
1:28:08 AM: Installing NPM modules using NPM version 6.14.4
1:28:16 AM: npm WARN read-shrinkwrap This version of npm is compatible with lockfileVersion@1, but package-lock.json was generated for lockfileVersion@2. I'll try to do my best with it!
1:28:16 AM: > esbuild@0.12.19 postinstall /opt/build/repo/node_modules/esbuild
1:28:16 AM: > node install.js
1:28:17 AM: > svelte-preprocess@4.7.4 postinstall /opt/build/repo/node_modules/svelte-preprocess
1:28:17 AM: > echo "[svelte-preprocess] Don't forget to install the preprocessors packages that will be used: node-sass/sass, stylus, less, postcss & postcss-load-config, coffeescript, pug, etc..."
1:28:17 AM: [svelte-preprocess] Don't forget to install the preprocessors packages that will be used: node-sass/sass, stylus, less, postcss & postcss-load-config, coffeescript, pug, etc...npm WARN notsup Unsupported engine for @sveltejs/kit@1.0.0-next.146: wanted: {"node":"^12.20 || >=14.13"} (current: {"node":"12.18.0","npm":"6.14.4"})
1:28:17 AM: npm WARN notsup Not compatible with your version of node/npm: @sveltejs/kit@1.0.0-next.146
1:28:17 AM: npm WARN notsup Unsupported engine for @sveltejs/vite-plugin-svelte@1.0.0-next.15: wanted: {"node":"^12.20 || ^14.13.1 || >= 16"} (current: {"node":"12.18.0","npm":"6.14.4"})
1:28:17 AM: npm WARN notsup Not compatible with your version of node/npm: @sveltejs/vite-plugin-svelte@1.0.0-next.15
1:28:17 AM: npm WARN colors@0.0.1 No repository field.
1:28:17 AM: npm WARN colors@0.0.1 No license field.
1:28:17 AM: npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@2.3.2 (node_modules/fsevents):
1:28:17 AM: npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@2.3.2: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
1:28:17 AM: added 308 packages from 263 contributors and audited 310 packages in 8.398s
1:28:17 AM: 42 packages are looking for funding
1:28:17 AM:   run `npm fund` for details
1:28:17 AM: found 0 vulnerabilities
1:28:17 AM: NPM modules installed
1:28:18 AM: Started restoring cached go cache
1:28:18 AM: Finished restoring cached go cache
1:28:18 AM: go version go1.14.4 linux/amd64
1:28:18 AM: go version go1.14.4 linux/amd64
1:28:18 AM: Installing missing commands
1:28:18 AM: Verify run directory
1:28:18 AM: ​
1:28:18 AM: ────────────────────────────────────────────────────────────────
1:28:18 AM:   Netlify Build                                                 
1:28:18 AM: ────────────────────────────────────────────────────────────────
1:28:18 AM: ​
1:28:18 AM: ❯ Version
1:28:18 AM:   @netlify/build 18.0.2
1:28:18 AM: ​
1:28:18 AM: ❯ Flags
1:28:18 AM:   baseRelDir: true
1:28:18 AM:   deployId: 6114db90d0cfb47f3fff8596
1:28:18 AM: ​
1:28:18 AM: ❯ Current directory
1:28:18 AM:   /opt/build/repo
1:28:18 AM: ​
1:28:18 AM: ❯ Config file
1:28:18 AM:   /opt/build/repo/netlify.toml
1:28:18 AM: ​
1:28:18 AM: ❯ Context
1:28:18 AM:   production
1:28:18 AM: ​
1:28:18 AM: ────────────────────────────────────────────────────────────────
1:28:18 AM:   1. build.command from netlify.toml                            
1:28:18 AM: ────────────────────────────────────────────────────────────────
1:28:18 AM: ​
1:28:18 AM: $ npm run build
1:28:18 AM: > colors@0.0.1 build /opt/build/repo
1:28:18 AM: > svelte-kit build
1:28:18 AM: (node:1358) ExperimentalWarning: The ESM module loader is experimental.
1:28:19 AM: > The requested module 'svelte-hmr' does not provide an export named 'createMakeHot'
1:28:19 AM: file:///opt/build/repo/node_modules/@sveltejs/vite-plugin-svelte/dist/index.js:240
1:28:19 AM: import { createMakeHot } from "svelte-hmr";
1:28:19 AM:          ^^^^^^^^^^^^^
1:28:19 AM: SyntaxError: The requested module 'svelte-hmr' does not provide an export named 'createMakeHot'
1:28:19 AM:     at ModuleJob._instantiate (internal/modules/esm/module_job.js:92:21)
1:28:19 AM:     at async ModuleJob.run (internal/modules/esm/module_job.js:107:20)
1:28:19 AM:     at async Loader.import (internal/modules/esm/loader.js:179:24)
1:28:19 AM:     at async file:///opt/build/repo/node_modules/@sveltejs/kit/dist/cli.js:916:22
1:28:19 AM: npm ERR! code ELIFECYCLE
1:28:19 AM: npm ERR! errno 1
1:28:19 AM: npm ERR! colors@0.0.1 build: `svelte-kit build`
1:28:19 AM: npm ERR! Exit status 1
1:28:19 AM: npm ERR!
1:28:19 AM: npm ERR! Failed at the colors@0.0.1 build script.
1:28:19 AM: npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
1:28:19 AM: npm ERR! A complete log of this run can be found in:
1:28:19 AM: npm ERR!     /opt/buildhome/.npm/_logs/2021-08-12T08_28_19_062Z-debug.log
1:28:19 AM: ​
1:28:19 AM: ────────────────────────────────────────────────────────────────
1:28:19 AM:   "build.command" failed                                        
1:28:19 AM: ────────────────────────────────────────────────────────────────
1:28:19 AM: ​
1:28:19 AM:   Error message
1:28:19 AM:   Command failed with exit code 1: npm run build
1:28:19 AM: ​
1:28:19 AM:   Error location
1:28:19 AM:   In build.command from netlify.toml:
1:28:19 AM:   npm run build
1:28:19 AM: ​
1:28:19 AM:   Resolved config
1:28:19 AM:   build:
1:28:19 AM:     command: npm run build
1:28:19 AM:     commandOrigin: config
1:28:19 AM:     publish: /opt/build/repo/build/publish
1:28:19 AM:     publishOrigin: config
1:28:19 AM:   functionsDirectory: /opt/build/repo/build/functions
1:28:19 AM: Caching artifacts
1:28:19 AM: Started saving node modules
1:28:19 AM: Finished saving node modules
1:28:19 AM: Started saving build plugins
1:28:19 AM: Finished saving build plugins
1:28:19 AM: Started saving pip cache
1:28:19 AM: Finished saving pip cache
1:28:19 AM: Started saving emacs cask dependencies
1:28:19 AM: Finished saving emacs cask dependencies
1:28:19 AM: Started saving maven dependencies
1:28:19 AM: Finished saving maven dependencies
1:28:19 AM: Started saving boot dependencies
1:28:19 AM: Finished saving boot dependencies
1:28:19 AM: Started saving rust rustup cache
1:28:19 AM: Finished saving rust rustup cache
1:28:19 AM: Started saving go dependencies
1:28:19 AM: Finished saving go dependencies
1:28:21 AM: Build failed due to a user error: Build script returned non-zero exit code: 2
1:28:22 AM: Creating deploy upload records
1:28:22 AM: Failing build: Failed to build site
1:28:22 AM: Failed during stage 'building site': Build script returned non-zero exit code: 2
1:28:22 AM: Finished processing build request in 19.887904081s
```
</details>
```


### System Info

```shell
C:\Users\Justin>npx envinfo --system --binaries --browsers --npmPackages "{svelte,@sveltejs/*,vite}"

  System:
    OS: Windows 10 10.0.19042
    CPU: (12) x64 AMD Ryzen 5 1600 Six-Core Processor
    Memory: 5.37 GB / 15.95 GB
  Binaries:
    Node: 14.15.5 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.10 - ~\AppData\Roaming\npm\yarn.CMD
    npm: 7.5.4 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Chrome: 92.0.4515.131
    Edge: Spartan (44.19041.1023.0), Chromium (92.0.902.67)


C:\Users\Justin>
```

### Severity

serious, but I can work around it

### Additional Information

I am fairly new to svelte kit, but just trying to deploy to netlify per your steps when I encounter this error.

Thanks in advance for looking into this 😄

**Comment by justingolden21** [comment]
I tried updating the `netlify.toml` and get this as my new output from Netlify:

```cmd
1:54:54 AM: Build ready to start
1:54:59 AM: Error checking out repo.
```

![image](https://user-images.githubusercontent.com/30274440/129168653-aef28ae7-368e-41b9-a862-ee694261b60b.png)

**Comment by bluwy** [comment]
SvelteKit does [have docs](https://github.com/sveltejs/kit/blob/master/packages/adapter-netlify/README.md#installation) to set the node version for netlify explicitly.
