### ISSUE TITLE
Error using re-exported of a svelte component 

### ISSUE THREAD

**Issue by GTime** [sveltejs/kit#2175]
### Describe the bug

I have an **index.ts** in my components directory I use to export all my components just so I can use them as below:
```ts
import { Money, Button } from '$lib/components'
``` 
rather than: 
```ts
import Money from '$lib/components/Money.svelte';
import Button from '$lib/components/Button.svelte';
```
This works fine, but the page breaks with a **500** error stating the component is not define when I use a re-exported component in a another re-exported component. For example using `Button` in `Money`.

### Reproduction

None

### System Info

```shell
500
Cannot read property 'Button' of null

TypeError: Cannot read property 'Button' of null
    at eval (/src/lib/components/admin/CreateProperty.svelte:104:69)
    at Object.$$render (C:\Users\godst\Workspace\AK\ak-web\node_modules\svelte\internal\index.js:1380:22)
    at add.svelte:51:23
    at Object.$$render (C:\Users\godst\Workspace\AK\ak-web\node_modules\svelte\internal\index.js:1380:22)
    at Object.default (root.svelte:38:46)
    at eval (C:\Users\godst\Workspace\AK\ak-web\src\routes\admin\properties\__layout.reset.svelte:33:34)
    at Object.$$render (C:\Users\godst\Workspace\AK\ak-web\node_modules\svelte\internal\index.js:1380:22)
    at root.svelte:36:44
    at $$render (C:\Users\godst\Workspace\AK\ak-web\node_modules\svelte\internal\index.js:1380:22)
    at Object.render (C:\Users\godst\Workspace\AK\ak-web\node_modules\svelte\internal\index.js:1388:26)
```

### Severity

serious, but I can work around it

**Comment by benmccann** [comment]
Can you provide a repo that reproduces this?

**Comment by benbender** [comment]
@GTime Also hit this "issue" a while ago and I assume you are importing the `Button`-component from your `$lib/components` which, in consequence, creates a circular dependency and breaks. 

I didn't think that this is a bug as it seems logical to me and is, afaik, default node-behaviour.

To circumvent this, you have to use `import Button from '$lib/components/Button.svelte';` in your `Money`-component...

**Comment by ignatiusmb** [comment]
The case is most likely what @benbender said, also default node-behavior and not much, if any, could be done on our side.
