### ISSUE TITLE
Resolution of absolute import fails

### ISSUE THREAD

**Issue by Spenhouet** [sveltejs/kit#2199]
### Describe the bug

An absolute import in my project fails.
I did just setup a bare Svelte Kit project, added a typescript/js file and tried to import it.
Relative imports work but absolute imports don't.
VS Code (IntelliSense) has no issue resolving the paths.

### Reproduction

1. Create a Svelte project with:

```console
npm init svelte@next svelte-app
```
(Skeleton project, TypeScript Yes, ESLint No, Prettier No)

2. Create a typescript or javascript file `mystore.ts` in `src/stores/`.

```typescript
import { writable } from "svelte/store";

export const test = writable()
```

3. Add absolute import to `src/routes/index.svelte`

```svelte
<script lang="ts">
    import { test } from "src/stores/mystore";
</script>
```

4. Try to run with `npm run dev`

### Logs

```shell
Failed to resolve import "src/stores/mystore" from "src/routes/index.svelte". Does the file exist?
7  |  } from "svelte/internal";
8  |  
9  |  import { test } from "src/stores/mystore";
   |                        ^
10 |  
11 |  const Routes = create_ssr_component(($$result, $$props, $$bindings, slots) => {
Error: Failed to resolve import "src/stores/mystore" from "src/routes/index.svelte". Does the file exist?
    at formatError (/home/spen/svelte-app-mui/node_modules/vite/dist/node/chunks/dep-c1a9de64.js:50738:46)
    at TransformContext.error (/home/spen/svelte-app-mui/node_modules/vite/dist/node/chunks/dep-c1a9de64.js:50734:19)
    at normalizeUrl (/home/spen/svelte-app-mui/node_modules/vite/dist/node/chunks/dep-c1a9de64.js:74223:26)
    at async TransformContext.transform (/home/spen/svelte-app-mui/node_modules/vite/dist/node/chunks/dep-c1a9de64.js:74356:57)
    at async Object.transform (/home/spen/svelte-app-mui/node_modules/vite/dist/node/chunks/dep-c1a9de64.js:50939:30)
    at async transformRequest (/home/spen/svelte-app-mui/node_modules/vite/dist/node/chunks/dep-c1a9de64.js:66763:29)
    at async instantiateModule (/home/spen/svelte-app-mui/node_modules/vite/dist/node/chunks/dep-c1a9de64.js:73412:10)
```

### System Info

```shell
npx: installed 1 in 1.622s

  System:
    OS: Linux 5.10 Ubuntu 20.04.2 LTS (Focal Fossa)
    CPU: (4) x64 Intel(R) Core(TM) i5-7200U CPU @ 2.50GHz
    Memory: 1.10 GB / 3.71 GB
    Container: Yes
    Shell: 5.0.17 - /bin/bash
  Binaries:
    Node: 14.17.4 - ~/.nvm/versions/node/v14.17.4/bin/node
    npm: 6.14.14 - ~/.nvm/versions/node/v14.17.4/bin/npm
  npmPackages:
    @sveltejs/kit: next => 1.0.0-next.147 
    svelte: ^3.34.0 => 3.42.1
```

### Severity

annoyance

### Additional Information

My `tsconfig.json` contains the following setting (unchanged from the Svelte Kit setup):

```json
{
	"compilerOptions": {
		"moduleResolution": "node",
		...
		"baseUrl": ".",
		...
	},
	"include": [
		"src/**/*.d.ts",
		"src/**/*.js",
		"src/**/*.ts",
		"src/**/*.svelte",
	]
}
```

**Comment by ignatiusmb** [comment]
That's not how imports work, you need to place them in `src/lib` (https://kit.svelte.dev/docs#modules-$lib) or set up an alias (https://kit.svelte.dev/faq#aliases).

**Comment by Spenhouet** [comment]
That is a strange default behavior, I don't know what I'm supposed to do with a `$lib` folder and the `$` sign is weird.
I fixed the imports with this configuration:

```plaintext
{
  kit: {
    target: '#svelte',
    vite: {
      resolve: {
        alias: {
          src: path.resolve('./src')
        }
      }
    }
  }
}
```

Now I can import everything from the `src` directory as expected.
Feels like this should be the default Svelte config provided by SvelteKit.
