### ISSUE TITLE
svelte-hmr gives SyntaxError when building

### ISSUE THREAD

**Issue by mbakker96** [sveltejs/kit#2216]
### Describe the bug

When building a new svelte application with @next I receive the following error. It makes no different selecting the SvelteKit demo app or the SvelteKit skeleton app. 

```
➜  my-app npm run dev -- --open

> ~TODO~@0.0.1 dev /Users/martijn/projects/mrw/my-app
> svelte-kit dev "--open"

(node:4685) ExperimentalWarning: The ESM module loader is experimental.
(node:4685) UnhandledPromiseRejectionWarning: file:///Users/martijn/projects/mrw/my-app/node_modules/@sveltejs/vite-plugin-svelte/dist/index.js:240
import { createMakeHot } from "svelte-hmr";
         ^^^^^^^^^^^^^
SyntaxError: The requested module 'svelte-hmr' is expected to be of type CommonJS, which does not support named exports. CommonJS modules can be imported by importing the default export.
For example:
import pkg from 'svelte-hmr';
const { createMakeHot } = pkg;
    at ModuleJob._instantiate (internal/modules/esm/module_job.js:97:21)
    at async ModuleJob.run (internal/modules/esm/module_job.js:143:20)
    at async Loader.import (internal/modules/esm/loader.js:182:24)
    at async file:///Users/martijn/projects/mrw/my-app/node_modules/@sveltejs/kit/dist/cli.js:873:19
(node:4685) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:4685) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

### Reproduction

```
$ npm init svelte@next my-app

✔ Which Svelte app template? › SvelteKit demo app
✔ Use TypeScript? … **No** / Yes <- same error when selecting yes
✔ Add ESLint for code linting? … **No** / Yes
✔ Add Prettier for code formatting? … **No** / Yes
✔ Copied project files

$ npm I

$ npm run dev -- --open
```

### Logs

```shell
npm init svelte@next my-app
npx: installed 5 in 1.417s
(node:4630) ExperimentalWarning: The ESM module loader is experimental.

create-svelte version 2.0.0-next.78

Welcome to SvelteKit!

This is beta software; expect bugs and missing features.

If you encounter a problem, open an issue on https://github.com/sveltejs/kit/issues if none exists already.

✔ Which Svelte app template? › SvelteKit demo app
✔ Use TypeScript? … *No* / Yes
✔ Add ESLint for code linting? … *No* / Yes
✔ Add Prettier for code formatting? … *No* / Yes
✔ Copied project files

Want to add other parts to your code base? Visit https://github.com/svelte-add/svelte-adders, a community project of commands to add particular functionality to Svelte projects


Next steps:
  1: cd my-app
  2: npm install (or pnpm install, etc)
  3: git init && git add -A && git commit -m "Initial commit" (optional step)
  4: npm run dev -- --open

To close the dev server, hit Ctrl-C

Stuck? Visit us at https://svelte.dev/chat

➜  mrw cd my-app
➜  my-app npm i

> esbuild@0.12.20 postinstall /Users/martijn/projects/mrw/my-app/node_modules/esbuild
> node install.js

npm notice created a lockfile as package-lock.json. You should commit this file.
npm WARN notsup Unsupported engine for @sveltejs/kit@1.0.0-next.151: wanted: {"node":"^12.20 || >=14.13"} (current: {"node":"12.19.1","npm":"6.14.8"})
npm WARN notsup Not compatible with your version of node/npm: @sveltejs/kit@1.0.0-next.151
npm WARN notsup Unsupported engine for @sveltejs/vite-plugin-svelte@1.0.0-next.17: wanted: {"node":"^12.20 || ^14.13.1 || >= 16"} (current: {"node":"12.19.1","npm":"6.14.8"})
npm WARN notsup Not compatible with your version of node/npm: @sveltejs/vite-plugin-svelte@1.0.0-next.17
npm WARN ~TODO~@0.0.1 No repository field.
npm WARN ~TODO~@0.0.1 No license field.

added 33 packages from 68 contributors and audited 33 packages in 2.278s

4 packages are looking for funding
  run `npm fund` for details

found 0 vulnerabilities

➜  my-app npm run dev -- --open

> ~TODO~@0.0.1 dev /Users/martijn/projects/mrw/my-app
> svelte-kit dev "--open"

(node:4685) ExperimentalWarning: The ESM module loader is experimental.
(node:4685) UnhandledPromiseRejectionWarning: file:///Users/martijn/projects/mrw/my-app/node_modules/@sveltejs/vite-plugin-svelte/dist/index.js:240
import { createMakeHot } from "svelte-hmr";
         ^^^^^^^^^^^^^
SyntaxError: The requested module 'svelte-hmr' is expected to be of type CommonJS, which does not support named exports. CommonJS modules can be imported by importing the default export.
For example:
import pkg from 'svelte-hmr';
const { createMakeHot } = pkg;
    at ModuleJob._instantiate (internal/modules/esm/module_job.js:97:21)
    at async ModuleJob.run (internal/modules/esm/module_job.js:143:20)
    at async Loader.import (internal/modules/esm/loader.js:182:24)
    at async file:///Users/martijn/projects/mrw/my-app/node_modules/@sveltejs/kit/dist/cli.js:873:19
(node:4685) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:4685) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```
```


### System Info

```shell
System:
    OS: macOS 12.0
    CPU: (8) x64 Intel(R) Core(TM) i7-7700HQ CPU @ 2.80GHz
    Memory: 312.14 MB / 16.00 GB
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 12.19.1 - ~/.nvm/versions/node/v12.19.1/bin/node
    npm: 6.14.8 - ~/.nvm/versions/node/v12.19.1/bin/npm
  Browsers:
    Chrome: 92.0.4515.131
    Firefox: 89.0.2
    Safari: 15.0
    Safari Technology Preview: 15.0
  npmPackages:
    @sveltejs/kit: next => 1.0.0-next.151
    svelte: ^3.34.0 => 3.42.1
```
```


### Severity

blocking all usage of SvelteKit

### Additional Information

_No response_

**Comment by mbakker96** [comment]
I just tried the same on my work Mac mini. When following the same steps, I was not able to reproduce it. 

```
System:
    OS: macOS 11.5
    CPU: (12) x64 Intel(R) Core(TM) i7-8700B CPU @ 3.20GHz
    Memory: 295.06 MB / 16.00 GB
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 14.17.5 - ~/.nvm/versions/node/v14.17.5/bin/node
    npm: 6.14.14 - ~/.nvm/versions/node/v14.17.5/bin/npm
  Browsers:
    Chrome: 92.0.4515.131
    Firefox: 88.0.1
    Safari: 14.1.2
    Safari Technology Preview: 14.2
  npmPackages:
    @sveltejs/kit: next => 1.0.0-next.151
    svelte: ^3.34.0 => 3.42.1
```

**Comment by ignatiusmb** [comment]
You need to upgrade your Node to the latest LTS version
