### ISSUE TITLE
Module context async load returning an error html response instead of json

### ISSUE THREAD

**Issue by charbelnicolas** [sveltejs/kit#2254]
### Describe the bug

When using the following code to fetch:

`<script context="module">

	export async function load({ fetch, page }) {
		const response = await fetch(`/users/verify/${page.params.id}`);
		const user = await response.json();
		return { props: { user } };
	}

</script>

<script>

	export let user;

</script>`

I get the following response:

`Response {
[1]   size: 0,
[1]   [Symbol(Body internals)]: {
[1]     body: <Buffer 3c 21 44 4f 43 54 59 50 45 20 68 74 6d 6c 3e 0a 3c 68 74 6d 6c 20 6c 61 6e 67 3d 22 65 6e 22 3e 0a 09 3c 68 65 61 64 3e 0a 09 09 3c 6d 65 74 61 20 63 ... 4298 more bytes>,
[1]     boundary: null,
[1]     disturbed: false,
[1]     error: null
[1]   },
[1]   [Symbol(Response internals)]: {
[1]     url: undefined,
[1]     status: 404,
[1]     statusText: '',
[1]     headers: {
[1]       'content-type': 'text/html',
[1]       'permissions-policy': 'interest-cohort=()'
[1]     },
[1]     counter: undefined,
[1]     highWaterMark: undefined
[1]   }
[1] }`

So I always get the following error:

`[1] Unexpected token < in JSON at position 0
[1] SyntaxError: Unexpected token < in JSON at position 0
[1]     at JSON.parse (<anonymous>)
[1]     at Proxy.<anonymous> (file:///home/charbel/Documents/websites/portal-svelte/html/node_modules/@sveltejs/kit/dist/ssr.js:916:22)
[1]     at async load ([id].svelte:5:21)
[1]     at async load_node (file:///home/charbel/Documents/websites/portal-svelte/html/node_modules/@sveltejs/kit/dist/ssr.js:944:12)
[1]     at async respond$1 (file:///home/charbel/Documents/websites/portal-svelte/html/node_modules/@sveltejs/kit/dist/ssr.js:1228:15)
[1]     at async render_page (file:///home/charbel/Documents/websites/portal-svelte/html/node_modules/@sveltejs/kit/dist/ssr.js:1392:19)
[1]     at async resolve (file:///home/charbel/Documents/websites/portal-svelte/html/node_modules/@sveltejs/kit/dist/ssr.js:1659:10)
[1]     at async respond (file:///home/charbel/Documents/websites/portal-svelte/html/node_modules/@sveltejs/kit/dist/ssr.js:1638:10)
[1]     at async Immediate.<anonymous> (file:///home/charbel/Documents/websites/portal-svelte/html/node_modules/@sveltejs/kit/dist/chunks/index.js:3511:22)`

If I make the same request through the terminal through cURL I get the correct response which should be:

`{ name: user.name, surname: user.surname, email: user.email }`

This is what the backend response looks like:

`return response.status(200).send({ name: user.name, surname: user.surname, email: user.email });`

Is this an error on my behalf or is this a bug in sveltekit?

### Reproduction

Please let me know if even with the above description a repo is needed. This doesn't seem like an easy task for a bug report.

### System Info

```shell
`
  System:
    OS: Linux 5.13 Arch Linux
    CPU: (8) x64 Intel(R) Core(TM) i7-6700K CPU @ 4.00GHz
    Memory: 28.58 GB / 31.31 GB
    Container: Yes
    Shell: 5.1.8 - /bin/bash
  Binaries:
    Node: 16.7.0 - /usr/bin/node
    npm: 7.21.0 - /usr/bin/npm
  Browsers:
    Chromium: 92.0.4515.159
`
```

### Severity

serious, but I can work around it

### Additional Information

I guess I could do an onMount and use a normal fetch but all the tutorials I've seen do it this way.

**Comment by mdynnl** [comment]
Hi, it's not very clear which framework/library is used for backend(express, polka, probably). The code provided doesn't look like svelte kit's endpoints/hooks. Please provide more info about backend if possible.

**Comment by charbelnicolas** [comment]
I'm using express. I guess I don't know how to use sveltekit's endpoints/hooks then (I don't use them at all).... I thought a simple fetch was all I needed, sorry.
