### ISSUE TITLE
Vercel function ReferenceError: module is not defined in ES module scope

### ISSUE THREAD

**Issue by sajeebrana** [sveltejs/kit#2269]
### Describe the bug

I have a simple vercel function
 'api/myfunc.js'
`module.exports = (req, res) => {
    res.status(200).json({message:"hi there"});
  };`
when i call the function `fetch('/api/myfunc')`  request fails. 
vercel message: **This Serverless Function has crashed.**

### Reproduction

use common js module.export, just like examples in vercel docs

### Logs

```shell
###  localhost 
Error [ERR_UNSUPPORTED_ESM_URL_SCHEME]: Only file and data URLs are supported by the default ESM loader. On Windows, absolute paths must be valid file:// URLs. Received protocol 'h:'
    at Loader.defaultResolve [as _resolve] (internal/modules/esm/resolve.js:791:11)
    at Loader.resolve (internal/modules/esm/loader.js:89:40)
    at Loader.getModuleJob (internal/modules/esm/loader.js:242:28)
    at Loader.import (internal/modules/esm/loader.js:177:28)
    at importModuleDynamically (internal/modules/cjs/loader.js:1015:27)
    at exports.importModuleDynamicallyCallback (internal/process/esm_loader.js:30:14)


### browser
/api/myfunc:1 Failed to load resource: the server responded with a status of 500 ()
SyntaxError: Unexpected token A in JSON at position 0
```

### System Info

```shell
System:
    OS: Windows 10 10.0.17763
    CPU: (4) x64 Intel(R) Core(TM) i5-4300U CPU @ 1.90GHz
    Memory: 3.86 GB / 7.90 GB
  Binaries:
    Node: 14.17.5 - C:\Program Files\nodejs\node.EXE
    npm: 6.14.14 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Internet Explorer: 11.0.17763.771
  npmPackages:
    @sveltejs/adapter-vercel: ^1.0.0-next.27 => 1.0.0-next.27
    @sveltejs/kit: next => 1.0.0-next.155
    svelte: ^3.34.0 => 3.42.2
```

### Severity

annoying

**Comment by sajeebrana** [comment]
You need to use ESM module export.
replace `module.exports` with `export default`
`export default (req, res) => { res.status(200).json({message:"hi there"}); };`
