### ISSUE TITLE
Unable to create a new Sveltekit project

### ISSUE THREAD

**Issue by biah** [sveltejs/kit#2312]
### Describe the bug

I just wanted to create a new Svelkekit project but am unable to run my project.
Am getting this error when I run `npm run dev -- open`

```
> svelte-kit dev "--open"

(node:3956) UnhandledPromiseRejectionWarning: file:///C:/Personal%20Files/www.kudadam.com.sveltekit/node_modules/@sveltejs/vite-plugin-svelte/dist/index.js:240
import { createMakeHot } from "svelte-hmr";
         ^^^^^^^^^^^^^
SyntaxError: The requested module 'svelte-hmr' does not provide an export named 'createMakeHot'
    at ModuleJob._instantiate (internal/modules/esm/module_job.js:92:21)
    at async ModuleJob.run (internal/modules/esm/module_job.js:107:20)
    at async Loader.import (internal/modules/esm/loader.js:179:24)
    at async file:///C:/Personal%20Files/www.kudadam.com.sveltekit/node_modules/@sveltejs/kit/dist/cli.js:975:19

(Use `node --trace-warnings ...` to show where the warning was created)
(node:3956) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:3956) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

### Reproduction

To reproduce, 
```enter svelte@next
npm install
npm run dev -- --open
```

### System Info

```shell
System:
    OS: Windows 7 6.1.7601
    CPU: (2) x64 Pentium(R) Dual-Core  CPU      E5300  @ 2.60GHz
    Memory: 361.25 MB / 1.95 GB
  Binaries:
    Node: 13.14.0 - C:\Program Files\nodejs\node.EXE
    npm: 6.14.4 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Internet Explorer: 8.0.7601.19104
  npmPackages:
    @sveltejs/kit: next => 1.0.0-next.158
    svelte: ^3.34.0 => 3.42.4
```

### Severity

blocking all usage of SvelteKit

**Comment by ignatiusmb** [comment]
Node version is outdated, upgrade to the latest LTS version.

**Comment by lgs** [comment]
Thanks @ignatiusmb, You've made my day too, I just fixed my deployment on Cloudflare Page too
