### ISSUE TITLE
Unhandled exceptions

### ISSUE THREAD

**Issue by benmccann** [sveltejs/kit#232]
If I do `throw new Error('something bad');` in `Nav.svelte` in `hn.svelte.dev` example it is handled appropriately. If I do `throw 'something bad';` then I just get a blank screen with no error details

(this is something TypeScript would catch for us :wink: In Sapper the types in our error handling explicitly allow for `Error|string`. We could cover it with a test too though it's a lot more code)

**Comment by GrygrFlzr** [comment]
Update, it now at least produces the following error:
```
TypeError: Cannot create property 'stack' on string 'something bad'
    at get_response (file:///C:/Users/GrygrFlzr/Documents/projects/sk-45c/node_modules/.pnpm/@sveltejs/kit@1.0.0-next.46_svelte@3.35.0+vite@2.0.5/node_modules/@sveltejs/kit/dist/ssr.js:2257:16)
    at async get_response (file:///C:/Users/GrygrFlzr/Documents/projects/sk-45c/node_modules/.pnpm/@sveltejs/kit@1.0.0-next.46_svelte@3.35.0+vite@2.0.5/node_modules/@sveltejs/kit/dist/ssr.js:2290:10)
    at async render_page (file:///C:/Users/GrygrFlzr/Documents/projects/sk-45c/node_modules/.pnpm/@sveltejs/kit@1.0.0-next.46_svelte@3.35.0+vite@2.0.5/node_modules/@sveltejs/kit/dist/ssr.js:2400:9)
    at async ssr (file:///C:/Users/GrygrFlzr/Documents/projects/sk-45c/node_modules/.pnpm/@sveltejs/kit@1.0.0-next.46_svelte@3.35.0+vite@2.0.5/node_modules/@sveltejs/kit/dist/ssr.js:2538:20)
    at async Immediate.<anonymous> (file:///C:/Users/GrygrFlzr/Documents/projects/sk-45c/node_modules/.pnpm/@sveltejs/kit@1.0.0-next.46_svelte@3.35.0+vite@2.0.5/node_modules/@sveltejs/kit/dist/chunks/index.js:3278:23)
```
https://github.com/sveltejs/kit/blob/5cd6f11aee6cd5edc5a758a5deb88925d3c9a50e/packages/kit/src/runtime/server/page.js#L238-L245
I guess we should check for the type of the error and convert it into an Error object before we attempt to set its stack?
Worth changing the type to `Error|string` as well.
