### ISSUE TITLE
adapter-static render2 is not a function

### ISSUE THREAD

**Issue by yaeszlo** [sveltejs/kit#2339]
### Describe the bug

Both the production and dev build does not ever succeed after upgrading the dependencies. 
The errors are definitely connected. I couldn't find anything in the changelog regarding the render and render2 functions in sveltekit package and neither in adapter-static package. 

the package versions are as follows: 
```
"@sveltejs/adapter-static": "1.0.0-next.17",
"@sveltejs/kit": "^1.0.0-next.160",
"svelte": "^3.42.4",
```

I tried downgrading the sveltekit dependency systematically to see if I get any result but I only got other errors. 

### Reproduction

1. Use specified dependencies 
2. Build the project either in dev or prod mode

### Logs

production build log:

```

✓ 119 modules transformed.
  .svelte-kit/output/server/app.js   392.66 KiB

Run npm run preview to preview your production build locally.

> Using @sveltejs/adapter-static
TypeError: render2 is not a function
at Object.handle (file:///G:/xxx/landing-page-sveltekit/.svelte-kit/output/server/app.js:1495:26)
at respond (file:///G:/xxx/landing-page-sveltekit/.svelte-kit/output/server/app.js:1211:33)
at Module.render (file:///G:/xxx/landing-page-sveltekit/.svelte-kit/output/server/app.js:1693:10)
at visit (file:///G:/xxx/landing-page-sveltekit/node_modules/@sveltejs/kit/dist/chunks/index5.js:164:30)
at prerender (file:///G:/xxx/landing-page-sveltekit/node_modules/@sveltejs/kit/dist/chunks/index5.js:290:12)
at async Object.prerender (file:///G:/xxx/landing-page-sveltekit/node_modules/@sveltejs/kit/dist/chunks/index5.js:351:4)
at async adapt (file:///G:/xxx/landing-page-sveltekit/node_modules/@sveltejs/adapter-static/index.js:13:4)
at async adapt (file:///G:/xxx/landing-page-sveltekit/node_modules/@sveltejs/kit/dist/chunks/index5.js:376:2)
at async file:///G:/xxx/landing-page-sveltekit/node_modules/@sveltejs/kit/dist/cli.js:1012:5
  > 500 /
Error: 500 /
at file:///G:/xxx/landing-page-sveltekit/node_modules/@sveltejs/kit/dist/chunks/index5.js:85:11
  at visit (file:///G:/xxx/landing-page-sveltekit/node_modules/@sveltejs/kit/dist/chunks/index5.js:212:5)
at async prerender (file:///G:/xxx/landing-page-sveltekit/node_modules/@sveltejs/kit/dist/chunks/index5.js:290:6)
at async Object.prerender (file:///G:/xxx/landing-page-sveltekit/node_modules/@sveltejs/kit/dist/chunks/index5.js:351:4)
at async adapt (file:///G:/xxx/landing-page-sveltekit/node_modules/@sveltejs/adapter-static/index.js:13:4)
at async adapt (file:///G:/xxx/landing-page-sveltekit/node_modules/@sveltejs/kit/dist/chunks/index5.js:376:2)
at async file:///G:/xxx/landing-page-sveltekit/node_modules/@sveltejs/kit/dist/cli.js:1012:5

  Process finished with exit code 1


```

dev build log:
```
warn - You have enabled the JIT engine which is currently in preview.
  warn - Preview features are not covered by semver, may introduce breaking changes, and can change at any time.
  render is not a function
TypeError: render is not a function
at Object.handle (/G:\xxx\landing-page-sveltekit\src\hooks:13:25)
at respond (file:///G:/xxx/landing-page-sveltekit/node_modules/@sveltejs/kit/dist/ssr.js:1641:30)
at Immediate.<anonymous> (file:///G:/xxx/landing-page-sveltekit/node_modules/@sveltejs/kit/dist/chunks/index.js:3515:28)
  render is not a function
TypeError: render is not a function
at Object.handle (/G:\xxx\landing-page-sveltekit\src\hooks:13:25)
at respond (file:///G:/xxx/landing-page-sveltekit/node_modules/@sveltejs/kit/dist/ssr.js:1641:30)
at Immediate.<anonymous> (file:///G:/xxx/landing-page-sveltekit/node_modules/@sveltejs/kit/dist/chunks/index.js:3515:28)
```

```
### System Info

System:
    OS: Windows 10 10.0.19042
    CPU: (4) x64 Intel(R) Core(TM) i5-6300HQ CPU @ 2.30GHz
    Memory: 1.86 GB / 7.80 GB
  Binaries:
    Node: 16.2.0 - C:\Program Files\nodejs\node.EXE
    npm: 7.13.0 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Chrome: 92.0.4515.159
    Edge: Spartan (44.19041.1023.0), Chromium (92.0.902.84)
  npmPackages:
    @sveltejs/adapter-static: 1.0.0-next.17 => 1.0.0-next.17
    @sveltejs/kit: ^1.0.0-next.160 => 1.0.0-next.160
    svelte: ^3.42.4 => 3.42.4

```

### Severity

blocking all usage of SvelteKit

### Additional Information

Severity is blocking because I had to upgrade the dependencies from sveltekit next110 & adapter-static next11 due to another error that prevented the build on the CI machine. Right now I have no way of deploying the website. Is there a working combination of sveltekit & adapter-static at this moment?

**Comment by benmccann** [comment]
please provide a project to reproduce this or it will be closed

**Comment by ignatiusmb** [comment]
> after upgrading the dependencies

This is almost certainly the `render` function not being renamed to `resolve` in hooks file.

**Comment by yaeszlo** [comment]
thank you @ignatiusmb 
is there any version of those dependencies that fix this issue? Or is it something I can handle myself?

**Comment by benmccann** [comment]
it's something you need to fix in your `src/hook.js` file. rename `render` to `resolve` there. https://kit.svelte.dev/docs#hooks-handle

**Comment by yaeszlo** [comment]
Indeed that solved the issue, but it wasn't working right away, so for anyone facing this problem here's a tip - after upgrading the dependencies and adjusting the `hooks.js` file, remove `.svelte-kit`, `build` and `node_modules` directories and run a fresh install.
