### ISSUE TITLE
node build fails when using routes with umlauts

### ISSUE THREAD

**Issue by noahsalvi** [sveltejs/kit#2403]
### Describe the bug

Building the project with a node adapter fails. This bug was implemented in kit.163

### Reproduction

- Create sveltekit project with the kit version being 163 or newer 
- Install and configure adapter-node
- Add route with umlaut character "ü.svelte". 
- npm run build

### Logs

```shell
404 /ü
Error: 404 /ü
    at file:///Users/noahsalvi/Downloads/testa/node_modules/@sveltejs/kit/dist/chunks/index5.js:85:11
    at visit (file:///Users/noahsalvi/Downloads/testa/node_modules/@sveltejs/kit/dist/chunks/index5.js:212:5)
    at async prerender (file:///Users/noahsalvi/Downloads/testa/node_modules/@sveltejs/kit/dist/chunks/index5.js:290:6)
    at async Object.prerender (file:///Users/noahsalvi/Downloads/testa/node_modules/@sveltejs/kit/dist/chunks/index5.js:351:4)
    at async adapt (file:///Users/noahsalvi/Downloads/testa/node_modules/@sveltejs/adapter-node/index.js:104:4)
    at async adapt (file:///Users/noahsalvi/Downloads/testa/node_modules/@sveltejs/kit/dist/chunks/index5.js:376:2)
    at async file:///Users/noahsalvi/Downloads/testa/node_modules/@sveltejs/kit/dist/cli.js:1008:5
error Command failed with exit code 1.
```

### System Info

```shell
System:
    OS: macOS 11.5.2
    CPU: (8) x64 Intel(R) Core(TM) i7-8559U CPU @ 2.70GHz
    Memory: 70.39 MB / 16.00 GB
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 16.4.0 - /usr/local/bin/node
    Yarn: 1.22.11 - /usr/local/bin/yarn
    npm: 7.18.1 - /usr/local/bin/npm
  Browsers:
    Chrome: 93.0.4577.63
    Edge: 91.0.864.71
    Firefox: 91.0.2
    Safari: 14.1.2
  npmPackages:
    @sveltejs/adapter-node: ^1.0.0-next.46 => 1.0.0-next.46 
    @sveltejs/kit: 1.0.0-next.163 => 1.0.0-next.163 
    svelte: ^3.34.0 => 3.42.5
```

### Severity

blocking an upgrade

**Comment by benmccann** [comment]
so sorry to keep breaking your app! I really think we're close to getting out all the wrinkles on this. thanks for your reports!

**Comment by noahsalvi** [comment]
@benmccann no worries :) 
SvelteKit is still in beta after all
