### ISSUE TITLE
Compiler: Error parsing component content

### ISSUE THREAD

**Issue by aidenlangley** [sveltejs/kit#2461]
### Describe the bug

It's not actually breaking my code, but it is being reported by `svelte-kit dev` and is probably having some side effect that is not super obvious.

Some strange behaviour can be observed on my site, [https://wowhub.co.nz](https://wowhub.co.nz). Navigating to the team triggers a re-render, and the path has an extra '/' appended to it, which seems unusual.

The error is as follows, and I can't infer anything from it unfortunately. My code looks okay and still runs okay...

```
CompileError [ParseError]: Unexpected token
    at error (/home/aidenlangley/Projects/web/svelte/wowhub.co.nz/node_modules/.pnpm/svelte@3.42.6/node_modules/svelte/compiler.js:17704:20)
    at Parser$1.error (/home/aidenlangley/Projects/web/svelte/wowhub.co.nz/node_modules/.pnpm/svelte@3.42.6/node_modules/svelte/compiler.js:17780:10)
    at Parser$1.acorn_error (/home/aidenlangley/Projects/web/svelte/wowhub.co.nz/node_modules/.pnpm/svelte@3.42.6/node_modules/svelte/compiler.js:17774:15)
    at Object.read_script [as read] (/home/aidenlangley/Projects/web/svelte/wowhub.co.nz/node_modules/.pnpm/svelte@3.42.6/node_modules/svelte/compiler.js:8469:17)
    at tag (/home/aidenlangley/Projects/web/svelte/wowhub.co.nz/node_modules/.pnpm/svelte@3.42.6/node_modules/svelte/compiler.js:16863:34)
    at new Parser$1 (/home/aidenlangley/Projects/web/svelte/wowhub.co.nz/node_modules/.pnpm/svelte@3.42.6/node_modules/svelte/compiler.js:17739:22)
    at Object.parse$3 [as parse] (/home/aidenlangley/Projects/web/svelte/wowhub.co.nz/node_modules/.pnpm/svelte@3.42.6/node_modules/svelte/compiler.js:17871:21)
    at replaceImages (/home/aidenlangley/Projects/web/svelte/wowhub.co.nz/node_modules/.pnpm/svelte-image@0.2.9/node_modules/svelte-image/src/main.js:554:18)
    at markup (/home/aidenlangley/Projects/web/svelte/wowhub.co.nz/node_modules/.pnpm/svelte-image@0.2.9/node_modules/svelte-image/src/main.js:667:21)
    at async process_markup (file:///home/aidenlangley/Projects/web/svelte/wowhub.co.nz/node_modules/.pnpm/svelte@3.42.6/node_modules/svelte/compiler.mjs:31557:23) {
  code: 'parse-error',
  start: { line: 6, column: 14, character: 251 },
  end: { line: 6, column: 14, character: 251 },
  pos: 251,
  filename: undefined,
  frame: "4:   import Tooltip from '../tooltip/Tooltip.svelte';\n" +
    "5:   import { TranslateDirection } from '../translate/types';\n" +
    "6:   import type { TeamMember } from './types';\n" +
    '                 ^\n' +
    '7: \n' +
    '8:   export let member: TeamMember;'
} Error parsing component content
CompileError [ParseError]: Unexpected token
    at error (/home/aidenlangley/Projects/web/svelte/wowhub.co.nz/node_modules/.pnpm/svelte@3.42.6/node_modules/svelte/compiler.js:17704:20)
    at Parser$1.error (/home/aidenlangley/Projects/web/svelte/wowhub.co.nz/node_modules/.pnpm/svelte@3.42.6/node_modules/svelte/compiler.js:17780:10)
    at Parser$1.acorn_error (/home/aidenlangley/Projects/web/svelte/wowhub.co.nz/node_modules/.pnpm/svelte@3.42.6/node_modules/svelte/compiler.js:17774:15)
    at Object.read_script [as read] (/home/aidenlangley/Projects/web/svelte/wowhub.co.nz/node_modules/.pnpm/svelte@3.42.6/node_modules/svelte/compiler.js:8469:17)
    at tag (/home/aidenlangley/Projects/web/svelte/wowhub.co.nz/node_modules/.pnpm/svelte@3.42.6/node_modules/svelte/compiler.js:16863:34)
    at new Parser$1 (/home/aidenlangley/Projects/web/svelte/wowhub.co.nz/node_modules/.pnpm/svelte@3.42.6/node_modules/svelte/compiler.js:17739:22)
    at Object.parse$3 [as parse] (/home/aidenlangley/Projects/web/svelte/wowhub.co.nz/node_modules/.pnpm/svelte@3.42.6/node_modules/svelte/compiler.js:17871:21)
    at replaceImages (/home/aidenlangley/Projects/web/svelte/wowhub.co.nz/node_modules/.pnpm/svelte-image@0.2.9/node_modules/svelte-image/src/main.js:554:18)
    at markup (/home/aidenlangley/Projects/web/svelte/wowhub.co.nz/node_modules/.pnpm/svelte-image@0.2.9/node_modules/svelte-image/src/main.js:667:21)
    at async process_markup (file:///home/aidenlangley/Projects/web/svelte/wowhub.co.nz/node_modules/.pnpm/svelte@3.42.6/node_modules/svelte/compiler.mjs:31557:23) {
  code: 'parse-error',
  start: { line: 6, column: 14, character: 251 },
  end: { line: 6, column: 14, character: 251 },
  pos: 251,
  filename: undefined,
  frame: "4:   import Tooltip from '../tooltip/Tooltip.svelte';\n" +
    "5:   import { TranslateDirection } from '../translate/types';\n" +
    "6:   import type { TeamMember } from './types';\n" +
    '                 ^\n' +
    '7: \n' +
    '8:   export let member: TeamMember;'
} Error parsing component content
```

### Reproduction

The repo is hosted here, nothing fancy about it, except I opt to use `pnpm` instead of `npm`.

https://github.com/aidenlangley/wowhub.co.nz

Starting the dev server, and navigating to the route: '/team' will trigger the error.

### System Info

```shell
npx: installed 1 in 0.524s

  System:
    OS: Linux 5.13 Fedora 34 (Workstation Edition) 34 (Workstation Edition)
    CPU: (8) x64 Intel(R) Core(TM) i7-8565U CPU @ 1.80GHz
    Memory: 347.91 MB / 15.27 GB
    Container: Yes
    Shell: 3.3.1 - /usr/bin/fish
  Binaries:
    Node: 14.17.6 - ~/.nvm/versions/node/v14.17.6/bin/node
    Yarn: 1.22.11 - ~/.nvm/versions/node/v14.17.6/bin/yarn
    npm: 6.14.15 - ~/.nvm/versions/node/v14.17.6/bin/npm
  Browsers:
    Chrome: 93.0.4577.82
    Firefox: 92.0
```

### Severity

annoyance

**Comment by benmccann** [comment]
This issue isn't coming from SvelteKit. It's possibly coming from https://github.com/matyunya/svelte-image or https://github.com/sveltejs/svelte. But there's also a good chance it's a usage issue. Maybe you have the preprocessors in the wrong order or omitted the TypeScript preprocessor?

Anyway, I'm going to close this since it's not related to SvelteKit

**Comment by mhatvan** [comment]
Pretty sure this is coming from svelte-image, which is unfortunately quite unmaintained and using outdated dependencies. I remember experiencing this exact issue as well back with Sapper.

**Comment by benmccann** [comment]
ah yes, I remember now that one of the dependencies has a bug that stops it from working with Vite / SvelteKit: https://github.com/woltapp/blurhash/issues/142
