### ISSUE TITLE
`svelte-kit package` requires there be an app.html file

### ISSUE THREAD

**Issue by chanced** [sveltejs/kit#2547]
### Describe the bug

`svelte-kit package` requires there be an app.html file.

### Reproduction

```#bash
npm init svelte@next project-name
cd project-name
npm i && npm i -D svelte2tsx typescript
rm src/app.html
echo "import preprocess from 'svelte-preprocess'; \n/** @type {import('@sveltejs/kit').Config} */ \nconst config = { preprocess: preprocess() }; \nexport default config;" > svelte.config.js
npm exec svelte-kit package
```

### Logs

```shell
▶ npm exec svelte-kit package
src/app.html does not exist
Error: src/app.html does not exist
    at validate_template (file:///Users/chance/Projects/spike/svelte-kit-without-apphtml/node_modules/@sveltejs/kit/dist/cli.js:688:9)
    at load_config (file:///Users/chance/Projects/spike/svelte-kit-without-apphtml/node_modules/@sveltejs/kit/dist/cli.js:708:2)
    at async get_config (file:///Users/chance/Projects/spike/svelte-kit-without-apphtml/node_modules/@sveltejs/kit/dist/cli.js:769:10)
    at async file:///Users/chance/Projects/spike/svelte-kit-without-apphtml/node_modules/@sveltejs/kit/dist/cli.js:924:18
```

### System Info

```shell
System:
    OS: macOS 11.5.2
    CPU: (8) x64 Intel(R) Core(TM) i7-6820HQ CPU @ 2.70GHz
    Memory: 105.45 MB / 16.00 GB
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 16.9.0 - ~/.nvm/versions/node/v16.9.0/bin/node
    npm: 7.21.1 - ~/.nvm/versions/node/v16.9.0/bin/npm
  Browsers:
    Brave Browser: 79.1.1.23
    Chrome: 94.0.4606.61
    Edge: 92.0.902.78
    Firefox: 91.0.2
    Safari: 14.1.2
  npmPackages:
    @sveltejs/kit: next => 1.0.0-next.179 
    svelte: ^3.42.6 => 3.43.1
```

### Severity

annoyance

**Comment by Conduitry** [comment]
I suppose this could probably safely be made optional for `svelte-kit package`, but part of the idea here is that you would also run the app normally (`svelte-kit dev`/`svelte-kit build`) to produce a demonstration of the included components, and that would fail without a `src/app.html`, so I'm not sure we'd want to be encouraging that sort of setup.

**Comment by chanced** [comment]
Yea, I totally get that. I guess I could switch my template files, per package, to {package}.html and that'd solve my issue of having numerous erroneous app.html files in a monorepo.

**Comment by martaver** [comment]
I am using storybook to generate the docs and testbed for my component library. In this case, there's no point having an app.html.

Can we re-open this and consider making the app.html optional for the `package` command?

**Comment by chanced** [comment]
@martaver reopened.
