### ISSUE TITLE
Better, more consistent error handling

### ISSUE THREAD

**Issue by Rich-Harris** [sveltejs/kit#260]
Different kinds of errors are all lumped in together during SSR, and it makes for a confusing experience. We can divide them into **load errors**, **eval errors**, **render errors** and **runtime errors**.

## Load errors

If you try to render a page but the code fails to load (because of a syntax error, for example), you get a generic 'Failed to load [url]: Unexpected token' error with a stack trace that points to kit's innards but gives you no help locating the error. This is rendered inside the `$error.svelte` component (or its placeholder):

```
Error: Failed to load /_app/routes/nope.js: Expected >
    at /Users/richard/Development/SVELTE/KIT/kit/packages/kit/src/api/dev/loader.js:61:11
    at /Users/richard/Development/SVELTE/KIT/kit/packages/kit/src/renderer/page.js:117:16
    at async Promise.all (index 1)
    at get_response (/Users/richard/Development/SVELTE/KIT/kit/packages/kit/src/renderer/page.js:113:16)
    at render_page (/Users/richard/Development/SVELTE/KIT/kit/packages/kit/src/renderer/page.js:257:10)
    at Object.render (/Users/richard/Development/SVELTE/KIT/kit/packages/kit/src/renderer/index.js:14:20)
    at /Users/richard/Development/SVELTE/KIT/kit/packages/kit/src/api/dev/index.js:177:22
```

If you navigate to that page instead, you see something along these lines:

<img width="1084" alt="Screen Shot 2020-12-11 at 10 45 32 AM" src="https://user-images.githubusercontent.com/1162160/101923957-0c2bca00-3b9e-11eb-9d3e-05a761360c0e.png">

> Ideally, we'd see the helpful overlay (with the code frame) in both SSR and CSR. These errors are dev only, because `snowpack build` would fail.

Edit: I think I was actually mistaken about this. The error overlay _is_ shown, because Snowpack broadcasts an HMR error which is immediately picked up by the HMR client, but it gets nuked as soon as the component hydrates, because by default SvelteKit owns the entire `<body>`. I think we probably need to change that behaviour.

## Eval errors

If a module loads but fails to evaluate, it does tell you which error the file occurred in during SSR, but the stack trace is wonky (the lines beginning `eval(...)` aren't mapped):

```
Error: eval error
    at eval (/_app/routes/nope.js:4:7)
    at initialize_module (/Users/richard/Development/SVELTE/KIT/kit/packages/kit/src/api/dev/loader.js:133:3)
    at /Users/richard/Development/SVELTE/KIT/kit/packages/kit/src/renderer/page.js:117:16
    at async Promise.all (index 1)
    at get_response (/Users/richard/Development/SVELTE/KIT/kit/packages/kit/src/renderer/page.js:113:16)
    at render_page (/Users/richard/Development/SVELTE/KIT/kit/packages/kit/src/renderer/page.js:257:10)
    at Object.render (/Users/richard/Development/SVELTE/KIT/kit/packages/kit/src/renderer/index.js:14:20)
    at /Users/richard/Development/SVELTE/KIT/kit/packages/kit/src/api/dev/index.js:177:22
```

Navigating to a page that depends on a module that fails to eval results in the following — the stack trace doesn't include irrelevant kit stuff, but nor is it sourcemapped:

```
Error: eval error
    at http://localhost:3000/_app/routes/nope.js:104:7
```

> These errors could appear in dev or prod. In dev it would be nice to see the overlay here. In both cases, we should probably strip out parts of the stack trace that point to kit, both because they're irrelevant and because we don't want to include details of the developer's filesystem in stack traces, lest the developer include them in production. Sourcemaps should be used if possible

## Render errors

This could mean an error in `preload` or in component instantiation. Here's a preload error in SSR:

```
Error: preload error
    at Object.preload (/_app/routes/nope.js:5:8)
    at /Users/richard/Development/SVELTE/KIT/kit/packages/kit/src/renderer/page.js:128:25
    at async Promise.all (index 1)
    at get_response (/Users/richard/Development/SVELTE/KIT/kit/packages/kit/src/renderer/page.js:113:16)
    at render_page (/Users/richard/Development/SVELTE/KIT/kit/packages/kit/src/renderer/page.js:257:10)
    at Object.render (/Users/richard/Development/SVELTE/KIT/kit/packages/kit/src/renderer/index.js:14:20)
    at /Users/richard/Development/SVELTE/KIT/kit/packages/kit/src/api/dev/index.js:177:22
```

And here's the same thing in CSR:

```
Error: preload error
    at Object.preload (http://localhost:3000/_app/routes/nope.js:105:8)
    at http://localhost:3000/_app/assets/runtime/internal/start.js:412:24
    at async Promise.all (index 1)
    at async Renderer.hydrate (http://localhost:3000/_app/assets/runtime/internal/start.js:385:13)
    at async Renderer.render (http://localhost:3000/_app/assets/runtime/internal/start.js:340:20)
    at async Router.navigate (http://localhost:3000/_app/assets/runtime/internal/start.js:176:3)
```

> These should basically be treated the same way as eval errors

Component instantiation is treated slightly differently. Here's SSR — very similar to a preload error:

```
Error: instantiate error
    at eval (/_app/routes/nope.js:9:8)
    at Object.$$render (/web_modules/svelte/internal.js:1341:22)
    at Object.default (/_app/assets/generated/root.js:36:103)
    at eval (/_app/assets/components/layout.js:5:41)
    at Object.$$render (/web_modules/svelte/internal.js:1341:22)
    at eval (/_app/assets/generated/root.js:33:50)
    at $$render (/web_modules/svelte/internal.js:1341:22)
    at Object.render (/web_modules/svelte/internal.js:1349:26)
    at get_response (/Users/richard/Development/SVELTE/KIT/kit/packages/kit/src/renderer/page.js:185:32)
    at render_page (/Users/richard/Development/SVELTE/KIT/kit/packages/kit/src/renderer/page.js:257:10)
```

But here's CSR:

<img width="1082" alt="Screen Shot 2020-12-11 at 11 18 06 AM" src="https://user-images.githubusercontent.com/1162160/101927508-937b3c80-3ba2-11eb-961a-03155b73e82b.png">

We get an overlay from svelte-hmr that we probably don't want — it looks different to all other kinds of errors, references a generated name (`<Nope>`) which is a bit confusing, and isn't sourcemapped. I don't know if there's a way to just let these errors propagate to Snowpack so that we get a regular overlay.

## Runtime errors

These only apply to CSR, because they happen after the component has instantiated:

<img width="1082" alt="Screen Shot 2020-12-11 at 11 16 37 AM" src="https://user-images.githubusercontent.com/1162160/101927346-5dd65380-3ba2-11eb-93eb-902b8e9ca845.png">

These are basically fine, though it'd be nice to have sourcemaps/frames here. Unsure whether and how that's possible.

**Comment by benmccann** [comment]
When we get to this we should also make sure to re-enable this test:
https://github.com/sveltejs/kit/blob/b6326c418338dff9be3e48c2b386fa8a1611c551/packages/kit/test/apps/basics/src/routes/errors/__tests__.js#L6

**Comment by Rich-Harris** [comment]
this issue is a bit out of date, closing
