### ISSUE TITLE
Sass now has the "evaluating SSR module" Error in dev mode

### ISSUE THREAD

**Issue by abdo643-HULK** [sveltejs/kit#2747]
### Describe the bug

The newest Version of kit and vite throw this error when starting the dev server but after a refresh everthing works fine. For the Build everthing works fine.

The same Error is also thrown when working with firebase auth.

### Reproduction

https://github.com/La-Mediterranee/Web-App

### Logs

```shell
11:53:50 AM [vite] Error when evaluating SSR module /node_modules/.pnpm/whatwg-url@5.0.0/node_modules/whatwg-url/lib/public-api.js?v=5f9ed3f7:
ReferenceError: exports is not defined
    at /node_modules/.pnpm/whatwg-url@5.0.0/node_modules/whatwg-url/lib/public-api.js?v=5f9ed3f7:3:1
    at instantiateModule (/home/abdo/la-mediterranee/Web-App/node_modules/.pnpm/vite@2.6.13_sass@1.43.4/node_modules/vite/dist/node/chunks/dep-85dbaaa7.js:66541:15)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
11:53:50 AM [vite] Error when evaluating SSR module /node_modules/.pnpm/node-fetch@2.6.5/node_modules/node-fetch/lib/index.mjs?v=5f9ed3f7:
ReferenceError: exports is not defined
    at /node_modules/.pnpm/whatwg-url@5.0.0/node_modules/whatwg-url/lib/public-api.js?v=5f9ed3f7:1:1
    at instantiateModule (/home/abdo/la-mediterranee/Web-App/node_modules/.pnpm/vite@2.6.13_sass@1.43.4/node_modules/vite/dist/node/chunks/dep-85dbaaa7.js:66541:15)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
11:53:50 AM [vite] Error when evaluating SSR module /node_modules/.pnpm/@firebase+auth@0.19.1_@firebase+app@0.7.6/node_modules/@firebase/auth/dist/node-esm/index.js?v=5f9ed3f7:
TypeError: Line must be greater than or equal to 1, got -1
    at BasicSourceMapConsumer.SourceMapConsumer_findMapping [as _findMapping] (/home/abdo/la-mediterranee/Web-App/node_modules/.pnpm/vite@2.6.13_sass@1.43.4/node_modules/vite/dist/node/chunks/dep-85dbaaa7.js:65402:13)
    at BasicSourceMapConsumer.SourceMapConsumer_originalPositionFor [as originalPositionFor] (/home/abdo/la-mediterranee/Web-App/node_modules/.pnpm/vite@2.6.13_sass@1.43.4/node_modules/vite/dist/node/chunks/dep-85dbaaa7.js:65471:22)
    at /home/abdo/la-mediterranee/Web-App/node_modules/.pnpm/vite@2.6.13_sass@1.43.4/node_modules/vite/dist/node/chunks/dep-85dbaaa7.js:66410:34
    at String.replace (<anonymous>)
    at /home/abdo/la-mediterranee/Web-App/node_modules/.pnpm/vite@2.6.13_sass@1.43.4/node_modules/vite/dist/node/chunks/dep-85dbaaa7.js:66400:21
    at Array.map (<anonymous>)
    at ssrRewriteStacktrace (/home/abdo/la-mediterranee/Web-App/node_modules/.pnpm/vite@2.6.13_sass@1.43.4/node_modules/vite/dist/node/chunks/dep-85dbaaa7.js:66399:10)
    at instantiateModule (/home/abdo/la-mediterranee/Web-App/node_modules/.pnpm/vite@2.6.13_sass@1.43.4/node_modules/vite/dist/node/chunks/dep-85dbaaa7.js:66544:28)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
11:53:50 AM [vite] Error when evaluating SSR module /node_modules/.pnpm/firebase@9.3.0/node_modules/firebase/auth/dist/index.mjs?v=5f9ed3f7:
TypeError: Line must be greater than or equal to 1, got -1
    at BasicSourceMapConsumer.SourceMapConsumer_findMapping [as _findMapping] (/home/abdo/la-mediterranee/Web-App/node_modules/.pnpm/vite@2.6.13_sass@1.43.4/node_modules/vite/dist/node/chunks/dep-85dbaaa7.js:65402:13)
    at BasicSourceMapConsumer.SourceMapConsumer_originalPositionFor [as originalPositionFor] (/home/abdo/la-mediterranee/Web-App/node_modules/.pnpm/vite@2.6.13_sass@1.43.4/node_modules/vite/dist/node/chunks/dep-85dbaaa7.js:65471:22)
    at /home/abdo/la-mediterranee/Web-App/node_modules/.pnpm/vite@2.6.13_sass@1.43.4/node_modules/vite/dist/node/chunks/dep-85dbaaa7.js:66410:34
    at String.replace (<anonymous>)
    at /home/abdo/la-mediterranee/Web-App/node_modules/.pnpm/vite@2.6.13_sass@1.43.4/node_modules/vite/dist/node/chunks/dep-85dbaaa7.js:66400:21
    at Array.map (<anonymous>)
    at ssrRewriteStacktrace (/home/abdo/la-mediterranee/Web-App/node_modules/.pnpm/vite@2.6.13_sass@1.43.4/node_modules/vite/dist/node/chunks/dep-85dbaaa7.js:66399:10)
    at instantiateModule (/home/abdo/la-mediterranee/Web-App/node_modules/.pnpm/vite@2.6.13_sass@1.43.4/node_modules/vite/dist/node/chunks/dep-85dbaaa7.js:66544:28)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
11:53:50 AM [vite] Error when evaluating SSR module /src/lib/firebase/auth.ts:
TypeError: Line must be greater than or equal to 1, got -1
    at BasicSourceMapConsumer.SourceMapConsumer_findMapping [as _findMapping] (/home/abdo/la-mediterranee/Web-App/node_modules/.pnpm/vite@2.6.13_sass@1.43.4/node_modules/vite/dist/node/chunks/dep-85dbaaa7.js:65402:13)
    at BasicSourceMapConsumer.SourceMapConsumer_originalPositionFor [as originalPositionFor] (/home/abdo/la-mediterranee/Web-App/node_modules/.pnpm/vite@2.6.13_sass@1.43.4/node_modules/vite/dist/node/chunks/dep-85dbaaa7.js:65471:22)
    at /home/abdo/la-mediterranee/Web-App/node_modules/.pnpm/vite@2.6.13_sass@1.43.4/node_modules/vite/dist/node/chunks/dep-85dbaaa7.js:66410:34
    at String.replace (<anonymous>)
    at /home/abdo/la-mediterranee/Web-App/node_modules/.pnpm/vite@2.6.13_sass@1.43.4/node_modules/vite/dist/node/chunks/dep-85dbaaa7.js:66400:21
    at Array.map (<anonymous>)
    at ssrRewriteStacktrace (/home/abdo/la-mediterranee/Web-App/node_modules/.pnpm/vite@2.6.13_sass@1.43.4/node_modules/vite/dist/node/chunks/dep-85dbaaa7.js:66399:10)
    at instantiateModule (/home/abdo/la-mediterranee/Web-App/node_modules/.pnpm/vite@2.6.13_sass@1.43.4/node_modules/vite/dist/node/chunks/dep-85dbaaa7.js:66544:28)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
11:53:50 AM [vite] Error when evaluating SSR module /src/lib/firebase/Auth.svelte:
TypeError: Line must be greater than or equal to 1, got -1
    at BasicSourceMapConsumer.SourceMapConsumer_findMapping [as _findMapping] (/home/abdo/la-mediterranee/Web-App/node_modules/.pnpm/vite@2.6.13_sass@1.43.4/node_modules/vite/dist/node/chunks/dep-85dbaaa7.js:65402:13)
    at BasicSourceMapConsumer.SourceMapConsumer_originalPositionFor [as originalPositionFor] (/home/abdo/la-mediterranee/Web-App/node_modules/.pnpm/vite@2.6.13_sass@1.43.4/node_modules/vite/dist/node/chunks/dep-85dbaaa7.js:65471:22)
    at /home/abdo/la-mediterranee/Web-App/node_modules/.pnpm/vite@2.6.13_sass@1.43.4/node_modules/vite/dist/node/chunks/dep-85dbaaa7.js:66410:34
    at String.replace (<anonymous>)
    at /home/abdo/la-mediterranee/Web-App/node_modules/.pnpm/vite@2.6.13_sass@1.43.4/node_modules/vite/dist/node/chunks/dep-85dbaaa7.js:66400:21
    at Array.map (<anonymous>)
    at ssrRewriteStacktrace (/home/abdo/la-mediterranee/Web-App/node_modules/.pnpm/vite@2.6.13_sass@1.43.4/node_modules/vite/dist/node/chunks/dep-85dbaaa7.js:66399:10)
    at instantiateModule (/home/abdo/la-mediterranee/Web-App/node_modules/.pnpm/vite@2.6.13_sass@1.43.4/node_modules/vite/dist/node/chunks/dep-85dbaaa7.js:66544:28)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
11:53:50 AM [vite] Error when evaluating SSR module /src/routes/_layoutProviders.svelte:
TypeError: Line must be greater than or equal to 1, got -1
    at BasicSourceMapConsumer.SourceMapConsumer_findMapping [as _findMapping] (/home/abdo/la-mediterranee/Web-App/node_modules/.pnpm/vite@2.6.13_sass@1.43.4/node_modules/vite/dist/node/chunks/dep-85dbaaa7.js:65402:13)
    at BasicSourceMapConsumer.SourceMapConsumer_originalPositionFor [as originalPositionFor] (/home/abdo/la-mediterranee/Web-App/node_modules/.pnpm/vite@2.6.13_sass@1.43.4/node_modules/vite/dist/node/chunks/dep-85dbaaa7.js:65471:22)
    at /home/abdo/la-mediterranee/Web-App/node_modules/.pnpm/vite@2.6.13_sass@1.43.4/node_modules/vite/dist/node/chunks/dep-85dbaaa7.js:66410:34
    at String.replace (<anonymous>)
    at /home/abdo/la-mediterranee/Web-App/node_modules/.pnpm/vite@2.6.13_sass@1.43.4/node_modules/vite/dist/node/chunks/dep-85dbaaa7.js:66400:21
    at Array.map (<anonymous>)
    at ssrRewriteStacktrace (/home/abdo/la-mediterranee/Web-App/node_modules/.pnpm/vite@2.6.13_sass@1.43.4/node_modules/vite/dist/node/chunks/dep-85dbaaa7.js:66399:10)
    at instantiateModule (/home/abdo/la-mediterranee/Web-App/node_modules/.pnpm/vite@2.6.13_sass@1.43.4/node_modules/vite/dist/node/chunks/dep-85dbaaa7.js:66544:28)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
11:53:50 AM [vite] Error when evaluating SSR module /src/routes/__layout.svelte:
TypeError: Line must be greater than or equal to 1, got -1
    at BasicSourceMapConsumer.SourceMapConsumer_findMapping [as _findMapping] (/home/abdo/la-mediterranee/Web-App/node_modules/.pnpm/vite@2.6.13_sass@1.43.4/node_modules/vite/dist/node/chunks/dep-85dbaaa7.js:65402:13)
    at BasicSourceMapConsumer.SourceMapConsumer_originalPositionFor [as originalPositionFor] (/home/abdo/la-mediterranee/Web-App/node_modules/.pnpm/vite@2.6.13_sass@1.43.4/node_modules/vite/dist/node/chunks/dep-85dbaaa7.js:65471:22)
    at /home/abdo/la-mediterranee/Web-App/node_modules/.pnpm/vite@2.6.13_sass@1.43.4/node_modules/vite/dist/node/chunks/dep-85dbaaa7.js:66410:34
    at String.replace (<anonymous>)
    at /home/abdo/la-mediterranee/Web-App/node_modules/.pnpm/vite@2.6.13_sass@1.43.4/node_modules/vite/dist/node/chunks/dep-85dbaaa7.js:66400:21
    at Array.map (<anonymous>)
    at ssrRewriteStacktrace (/home/abdo/la-mediterranee/Web-App/node_modules/.pnpm/vite@2.6.13_sass@1.43.4/node_modules/vite/dist/node/chunks/dep-85dbaaa7.js:66399:10)
    at instantiateModule (/home/abdo/la-mediterranee/Web-App/node_modules/.pnpm/vite@2.6.13_sass@1.43.4/node_modules/vite/dist/node/chunks/dep-85dbaaa7.js:66544:28)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
Line must be greater than or equal to 1, got -1
TypeError: Line must be greater than or equal to 1, got -1
    at BasicSourceMapConsumer.SourceMapConsumer_findMapping [as _findMapping] (/home/abdo/la-mediterranee/Web-App/node_modules/.pnpm/vite@2.6.13_sass@1.43.4/node_modules/vite/dist/node/chunks/dep-85dbaaa7.js:65402:13)
    at BasicSourceMapConsumer.SourceMapConsumer_originalPositionFor [as originalPositionFor] (/home/abdo/la-mediterranee/Web-App/node_modules/.pnpm/vite@2.6.13_sass@1.43.4/node_modules/vite/dist/node/chunks/dep-85dbaaa7.js:65471:22)
    at /home/abdo/la-mediterranee/Web-App/node_modules/.pnpm/vite@2.6.13_sass@1.43.4/node_modules/vite/dist/node/chunks/dep-85dbaaa7.js:66410:34
    at String.replace (<anonymous>)
    at /home/abdo/la-mediterranee/Web-App/node_modules/.pnpm/vite@2.6.13_sass@1.43.4/node_modules/vite/dist/node/chunks/dep-85dbaaa7.js:66400:21
    at Array.map (<anonymous>)
    at ssrRewriteStacktrace (/home/abdo/la-mediterranee/Web-App/node_modules/.pnpm/vite@2.6.13_sass@1.43.4/node_modules/vite/dist/node/chunks/dep-85dbaaa7.js:66399:10)
    at instantiateModule (/home/abdo/la-mediterranee/Web-App/node_modules/.pnpm/vite@2.6.13_sass@1.43.4/node_modules/vite/dist/node/chunks/dep-85dbaaa7.js:66544:28)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
```

### System Info

```shell
System:
    OS: Linux 5.10 Ubuntu 20.04.3 LTS (Focal Fossa)
    CPU: (4) x64 AMD Ryzen 7 3700X 8-Core Processor
    Memory: 744.60 MB / 3.84 GB
    Container: Yes
    Shell: 5.8 - /usr/bin/zsh
  Binaries:
    Node: 16.10.0 - ~/.nvm/versions/node/v16.10.0/bin/node
    Yarn: 1.22.10 - /mnt/c/Program Files/nodejs/yarn
    npm: 7.24.0 - ~/.nvm/versions/node/v16.10.0/bin/npm
  npmPackages:
    @sveltejs/adapter-cloudflare-workers: ^1.0.0-next.25 => 1.0.0-next.25 
    @sveltejs/adapter-netlify: ^1.0.0-next.35 => 1.0.0-next.35 
    @sveltejs/adapter-node: ^1.0.0-next.55 => 1.0.0-next.55 
    @sveltejs/adapter-static: ^1.0.0-next.21 => 1.0.0-next.21 
    @sveltejs/adapter-vercel: ^1.0.0-next.31 => 1.0.0-next.31 
    @sveltejs/kit: ^1.0.0-next.194 => 1.0.0-next.194 
    svelte: ^3.44.1 => 3.44.1 
    vite: ^2.6.13 => 2.6.13
```

### Severity

annoyance

**Comment by bluwy** [comment]
Do you know which version you were upgrading from that caused this error? Or better on which exact version that introduces this regression? It would help us narrow down the cause.

**Comment by abdo643-HULK** [comment]
> Do you know which version you were upgrading from that caused this error? Or better on which exact version that introduces this regression? It would help us narrow down the cause.

Like I said the newest one 194 with 193 it works normal

**Comment by Rich-Harris** [comment]
Feel free to open an issue with a repro as described in https://github.com/sveltejs/kit/blob/master/.github/ISSUE_TEMPLATE/bug_report.yml
