### ISSUE TITLE
adapter-static: Error when building site under Linux

### ISSUE THREAD

**Issue by shivjm** [sveltejs/kit#2796]
### Describe the bug

I’ve got an SK project I started back when it was at v1.0.0-next.107. It essentially consists of a single route which preloads data from a single endpoint. I just finished it and it works in dev mode, so I added adapter-static. Now I can build it on Windows with <kbd>svelte-kit build</kbd>, with the final output being:
```
> Using @sveltejs/adapter-static
  ✔ done
```
And <kbd>svelte-kit preview</kbd> works correctly.

However, <kbd>svelte-kit build</kbd> fails under (Alpine) Linux with an error about trying to open a directory as a file. This means I can’t deploy it anywhere.

Since I started with a much older version, it could just be that I need to update my code to use a new style, but I can’t see any problems based on the docs. I created an MWE using <kbd>npm init svelte@next</kbd>. (My project uses TypeScript, but I was able to reproduce it with a JavaScript skeleton project.) I’m attaching the link and the logs in the relevant fields. Here’s the file tree, just for completeness:
```
.
├── .gitignore
├── _data
│  └── foo.yaml
├── jsconfig.json
├── package-lock.json
├── package.json
├── README.md
├── src
│  ├── app.html
│  ├── global.d.ts
│  └── routes
│     ├── data.js
│     └── index.svelte
├── static
│  └── favicon.png
└── svelte.config.js
```

### Reproduction

https://github.com/shivjm/sveltekit-static-test

### Logs

```
> sveltekit-test@0.0.1 build /work.new
> svelte-kit build

vite v2.6.14 building for production...
✓ 14 modules transformed.
.svelte-kit/output/client/_app/manifest.json                    1.21 KiB
.svelte-kit/output/client/_app/layout.svelte-712392a1.js        0.53 KiB / gzip: 0.35 KiB
.svelte-kit/output/client/_app/error.svelte-55ba95a6.js         1.56 KiB / gzip: 0.74 KiB
.svelte-kit/output/client/_app/pages/index.svelte-db8ac5cc.js   0.74 KiB / gzip: 0.47 KiB
.svelte-kit/output/client/_app/start-ebb02e83.js                18.38 KiB / gzip: 6.80 KiB
.svelte-kit/output/client/_app/assets/start-61d1577b.css        0.16 KiB / gzip: 0.15 KiB
.svelte-kit/output/client/_app/chunks/vendor-af0f2ef7.js        7.08 KiB / gzip: 2.89 KiB
vite v2.6.14 building SSR bundle for production...
✓ 15 modules transformed.
.svelte-kit/output/server/app.js                      0.07 KiB
.svelte-kit/output/server/chunks/app-498ddc9a.js      47.98 KiB
.svelte-kit/output/server/chunks/data-e92d2162.js     0.20 KiB
.svelte-kit/output/server/chunks/layout-dc4a3a6e.js   0.23 KiB
.svelte-kit/output/server/chunks/error-31498736.js    0.71 KiB
.svelte-kit/output/server/chunks/index-3bbafa22.js    0.67 KiB

Run npm run preview to preview your production build locally.

> Using @sveltejs/adapter-static
> EISDIR: illegal operation on a directory, open 'build/data/'
Error: EISDIR: illegal operation on a directory, open 'build/data/'
    at Object.openSync (fs.js:497:3)
    at writeFileSync (fs.js:1528:35)
    at file:///work.new/node_modules/@sveltejs/kit/dist/chunks/index4.js:234:6
    at Map.forEach (<anonymous>)
    at visit (file:///work.new/node_modules/@sveltejs/kit/dist/chunks/index4.js:220:17)
    at async prerender (file:///work.new/node_modules/@sveltejs/kit/dist/chunks/index4.js:298:6)
    at async Object.prerender (file:///work.new/node_modules/@sveltejs/kit/dist/chunks/index4.js:363:4)
    at async adapt (file:///work.new/node_modules/@sveltejs/adapter-static/index.js:13:4)
    at async adapt (file:///work.new/node_modules/@sveltejs/kit/dist/chunks/index4.js:388:2)
    at async file:///work.new/node_modules/@sveltejs/kit/dist/cli.js:891:5
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! sveltekit-test@0.0.1 build: `svelte-kit build`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the sveltekit-test@0.0.1 build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2021-11-14T10_41_13_461Z-debug.log
```

### System Info

```shell
System:
    OS: Linux 5.10 Alpine Linux
    CPU: (16) x64 AMD Ryzen 7 2700 Eight-Core Processor
    Memory: 48.15 GB / 50.15 GB
    Container: Yes
    Shell: 1.31.1 - /bin/ash
  Binaries:
    Node: 14.18.1 - /usr/local/bin/node
    Yarn: 1.22.15 - /usr/local/bin/yarn
    npm: 6.14.15 - /usr/local/bin/npm
```

### Severity

blocking all usage of SvelteKit

**Comment by MacFJA** [comment]
From reading you code, I think the issue is cause by:

https://github.com/shivjm/sveltekit-static-test/blob/bd303de85018946bcf623b15dbe7b41b0c113b71/src/routes/index.svelte#L3

When the `adapter-static` is generating the page, it try to do the fetch, but fail as the directory don't exist

**Comment by shivjm** [comment]
Right, I figured it might be related in some way to `trailingSlash`. Would that qualify as a bug in adapter-static or should I be changing my code to accommodate it?

**Comment by shivjm** [comment]
Should this be working with adapter-static 1.0.0-next.29 and @sveltejs/kit 1.0.0-next.322? I’m seeing the same error even after updating the versions and running a fresh `npm install`.
