### ISSUE TITLE
Impossible to install dependencies for "SvelteKit demo app" with `npm`

### ISSUE THREAD

**Issue by designorant** [sveltejs/kit#2888]
### Describe the bug

What title says:

```
❯ npm install
npm ERR! code EUNSUPPORTEDPROTOCOL
npm ERR! Unsupported URL Type "workspace:": workspace:*
```

SvelteKit skeleton is fine, but demo app isn't. Running latest LTS with baked in `npm`, upgrading to latest `npm` doesn't help.

### Reproduction

```console
~/Projects/Code
❯ npm init svelte@next my-app

create-svelte version 2.0.0-next.86

Welcome to SvelteKit!

This is beta software; expect bugs and missing features.

If you encounter a problem, open an issue on https://github.com/sveltejs/kit/issues if none exists already.

✔ Which Svelte app template? › SvelteKit demo app
✔ Use TypeScript? … No / Yes
✔ Add ESLint for code linting? … No / Yes
✔ Add Prettier for code formatting? … No / Yes
✔ Copied project files
✔ Added ESLint.
Readme for ESLint and Svelte: https://github.com/sveltejs/eslint-plugin-svelte3
✔ Added Prettier.
General formatting options: https://prettier.io/docs/en/options.html
Svelte-specific formatting options: https://github.com/sveltejs/prettier-plugin-svelte#options

Want to add other parts to your code base? Visit https://github.com/svelte-add/svelte-adders, a community project of commands to add particular functionality to Svelte projects


Next steps:
  1: cd my-app
  2: npm install (or pnpm install, etc)
  3: git init && git add -A && git commit -m "Initial commit" (optional step)
  4: npm run dev -- --open

To close the dev server, hit Ctrl-C

Stuck? Visit us at https://svelte.dev/chat


~/Projects/Code   10s
❯ cd my-app

~/Projects/Code/my-app
❯ npm install
npm ERR! code EUNSUPPORTEDPROTOCOL
npm ERR! Unsupported URL Type "workspace:": workspace:*

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/designorant/.npm/_logs/2021-11-24T11_51_54_375Z-debug.log
```

### Logs

```shell
0 verbose cli [
0 verbose cli   '/Users/designorant/.nodenv/versions/16.13.0/bin/node',
0 verbose cli   '/Users/designorant/.nodenv/versions/16.13.0/bin/npm',
0 verbose cli   'install'
0 verbose cli ]
1 info using npm@8.1.0
2 info using node@v16.13.0
3 timing npm:load:whichnode Completed in 1ms
4 timing config:load:defaults Completed in 1ms
5 timing config:load:file:/Users/designorant/.nodenv/versions/16.13.0/lib/node_modules/npm/npmrc Completed in 0ms
6 timing config:load:builtin Completed in 1ms
7 timing config:load:cli Completed in 2ms
8 timing config:load:env Completed in 0ms
9 timing config:load:file:/Users/designorant/Code/my-app/.npmrc Completed in 0ms
10 timing config:load:project Completed in 1ms
11 timing config:load:file:/Users/designorant/.npmrc Completed in 0ms
12 timing config:load:user Completed in 0ms
13 timing config:load:file:/Users/designorant/.nodenv/versions/16.13.0/etc/npmrc Completed in 0ms
14 timing config:load:global Completed in 1ms
15 timing config:load:validate Completed in 0ms
16 timing config:load:credentials Completed in 1ms
17 timing config:load:setEnvs Completed in 1ms
18 timing config:load Completed in 8ms
19 timing npm:load:configload Completed in 8ms
20 timing npm:load:setTitle Completed in 17ms
21 timing npm:load:setupLog Completed in 1ms
22 timing config:load:flatten Completed in 3ms
23 timing npm:load:cleanupLog Completed in 2ms
24 timing npm:load:configScope Completed in 0ms
25 timing npm:load:projectScope Completed in 0ms
26 timing npm:load Completed in 34ms
27 timing arborist:ctor Completed in 1ms
28 timing arborist:ctor Completed in 0ms
29 timing idealTree:init Completed in 13ms
30 timing idealTree:userRequests Completed in 0ms
31 silly idealTree buildDeps
32 silly fetch manifest @fontsource/fira-mono@^4.5.0
33 http fetch GET 200 https://registry.npmjs.org/@fontsource%2ffira-mono 1693ms (cache revalidated)
34 silly fetch manifest @lukeed/uuid@^2.0.0
35 http fetch GET 200 https://registry.npmjs.org/@lukeed%2fuuid 1471ms (cache revalidated)
36 silly fetch manifest cookie@^0.4.1
37 http fetch GET 200 https://registry.npmjs.org/cookie 30ms (cache revalidated)
38 silly fetch manifest @sveltejs/adapter-auto@next
39 http fetch GET 200 https://registry.npmjs.org/@sveltejs%2fadapter-auto 1458ms (cache revalidated)
40 silly fetch manifest @sveltejs/kit@next
41 http fetch GET 200 https://registry.npmjs.org/@sveltejs%2fkit 1477ms (cache revalidated)
42 silly fetch manifest svelte@^3.34.0
43 http fetch GET 200 https://registry.npmjs.org/svelte 52ms (cache revalidated)
44 silly fetch manifest eslint@^7.32.0
45 http fetch GET 200 https://registry.npmjs.org/eslint 47ms (cache revalidated)
46 silly fetch manifest eslint-config-prettier@^8.3.0
47 http fetch GET 200 https://registry.npmjs.org/eslint-config-prettier 57ms (cache revalidated)
48 silly fetch manifest eslint-plugin-svelte3@^3.2.1
49 http fetch GET 200 https://registry.npmjs.org/eslint-plugin-svelte3 688ms (cache revalidated)
50 silly fetch manifest prettier@^2.4.1
51 http fetch GET 200 https://registry.npmjs.org/prettier 27ms (cache revalidated)
52 silly fetch manifest prettier-plugin-svelte@^2.4.0
53 http fetch GET 200 https://registry.npmjs.org/prettier-plugin-svelte 690ms (cache revalidated)
54 silly placeDep ROOT @fontsource/fira-mono@4.5.0 OK for: my-app@0.0.1 want: ^4.5.0
55 silly placeDep ROOT @lukeed/uuid@2.0.0 OK for: my-app@0.0.1 want: ^2.0.0
56 silly placeDep ROOT @sveltejs/adapter-auto@1.0.0-next.0 OK for: my-app@0.0.1 want: next
57 silly placeDep ROOT @sveltejs/kit@1.0.0-next.199 OK for: my-app@0.0.1 want: next
58 silly placeDep ROOT svelte@3.44.2 OK for: @sveltejs/kit@1.0.0-next.199 want: ^3.44.0
59 silly placeDep ROOT cookie@0.4.1 OK for: my-app@0.0.1 want: ^0.4.1
60 silly placeDep ROOT eslint@7.32.0 OK for: my-app@0.0.1 want: ^7.32.0
61 silly placeDep ROOT eslint-config-prettier@8.3.0 OK for: my-app@0.0.1 want: ^8.3.0
62 silly placeDep ROOT eslint-plugin-svelte3@3.2.1 OK for: my-app@0.0.1 want: ^3.2.1
63 silly placeDep ROOT prettier@2.4.1 OK for: my-app@0.0.1 want: ^2.4.1
64 silly placeDep ROOT prettier-plugin-svelte@2.5.0 OK for: my-app@0.0.1 want: ^2.4.0
65 silly fetch manifest @lukeed/csprng@^1.0.0
66 timing idealTree Completed in 7765ms
67 timing command:install Completed in 7783ms
68 verbose stack Error: Unsupported URL Type "workspace:": workspace:*
68 verbose stack     at unsupportedURLType (/Users/designorant/.nodenv/versions/16.13.0/lib/node_modules/npm/node_modules/npm-package-arg/npa.js:246:15)
68 verbose stack     at fromURL (/Users/designorant/.nodenv/versions/16.13.0/lib/node_modules/npm/node_modules/npm-package-arg/npa.js:306:13)
68 verbose stack     at Function.resolve (/Users/designorant/.nodenv/versions/16.13.0/lib/node_modules/npm/node_modules/npm-package-arg/npa.js:76:12)
68 verbose stack     at /Users/designorant/.nodenv/versions/16.13.0/lib/node_modules/npm/node_modules/@npmcli/arborist/lib/arborist/build-ideal-tree.js:1034:38
68 verbose stack     at Array.map (<anonymous>)
68 verbose stack     at visit (/Users/designorant/.nodenv/versions/16.13.0/lib/node_modules/npm/node_modules/@npmcli/arborist/lib/arborist/build-ideal-tree.js:1033:56)
68 verbose stack     at visitNode (/Users/designorant/.nodenv/versions/16.13.0/lib/node_modules/npm/node_modules/treeverse/lib/depth-descent.js:57:25)
68 verbose stack     at next (/Users/designorant/.nodenv/versions/16.13.0/lib/node_modules/npm/node_modules/treeverse/lib/depth-descent.js:44:19)
68 verbose stack     at depth (/Users/designorant/.nodenv/versions/16.13.0/lib/node_modules/npm/node_modules/treeverse/lib/depth-descent.js:82:10)
68 verbose stack     at depth (/Users/designorant/.nodenv/versions/16.13.0/lib/node_modules/npm/node_modules/treeverse/lib/depth.js:27:12)
69 verbose cwd /Users/designorant/Code/my-app
70 verbose Darwin 21.1.0
71 verbose argv "/Users/designorant/.nodenv/versions/16.13.0/bin/node" "/Users/designorant/.nodenv/versions/16.13.0/bin/npm" "install"
72 verbose node v16.13.0
73 verbose npm  v8.1.0
74 error code EUNSUPPORTEDPROTOCOL
75 error Unsupported URL Type "workspace:": workspace:*
76 verbose exit 1
```

### System Info

```shell
System:
    OS: macOS 12.0.1
    CPU: (16) x64 Intel(R) Core(TM) i9-9980HK CPU @ 2.40GHz
    Memory: 278.19 MB / 32.00 GB
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 16.13.0 - ~/.nodenv/versions/16.13.0/bin/node
    Yarn: 1.22.17 - /usr/local/bin/yarn
    npm: 8.1.0 - ~/.nodenv/versions/16.13.0/bin/npm
    Watchman: 2021.10.18.00 - /usr/local/bin/watchman
```

### Severity

annoyance

**Comment by bluwy** [comment]
This will be fixed by #2885. Should be merged soon.

**Comment by Conduitry** [comment]
This should be fixed now. The latest `create-svelte@next` templates no longer have `workspace:*` dependencies.

**Comment by Rich-Harris** [comment]
hold your horses, i ballsed things up again... https://github.com/sveltejs/kit/pull/2891

one sec

**Comment by Conduitry** [comment]
Well to be fair the dependencies install now, you just can't run the app 😶

**Comment by Conduitry** [comment]
Okay, yes, now it's working with the new adapter-auto fix.
