### ISSUE TITLE
No matching version found for picocolors@^1.0.0.

### ISSUE THREAD

**Issue by winston0410** [sveltejs/kit#2924]
### Describe the bug

Cannot install sveltekit now, receiving the following errors:

```
❯ npm i
npm ERR! code ETARGET
npm ERR! notarget No matching version found for picocolors@^1.0.0.
npm ERR! notarget In most cases you or one of your dependencies are requesting
npm ERR! notarget a package version that doesn't exist.

npm ERR! A complete log of this run can be found in:

```

### Reproduction

Create a package.json like this:

```
{
	"name": "ory-kratos-ui-template",
	"version": "0.0.1",
	"scripts": {
		"dev": "svelte-kit dev",
		"build": "svelte-kit build",
		"preview": "svelte-kit preview",
		"check": "svelte-check --tsconfig ./tsconfig.json",
		"check:watch": "svelte-check --tsconfig ./tsconfig.json --watch",
		"lint": "prettier --ignore-path .gitignore --check --plugin-search-dir=. . && eslint --ignore-path .gitignore .",
		"format": "prettier --ignore-path .gitignore --write --plugin-search-dir=. ."
	},
	"devDependencies": {
		"@sveltejs/kit": "next"
	},
	"type": "module"
}

```

Run npm install, and the error message should appear

### Logs

```shell
0 verbose cli [
0 verbose cli   '/nix/store/26lslfmvwyhspppbinznh111fyaxx62z-nodejs-16.13.0/bin/node',
0 verbose cli   '/etc/profiles/per-user/hugosum/bin/npm',
0 verbose cli   'i'
0 verbose cli ]
1 info using npm@8.1.0
2 info using node@v16.13.0
3 timing npm:load:whichnode Completed in 1ms
4 timing config:load:defaults Completed in 1ms
5 timing config:load:file:/nix/store/26lslfmvwyhspppbinznh111fyaxx62z-nodejs-16.13.0/lib/node_modules/npm/npmrc Completed in 1ms
6 timing config:load:builtin Completed in 1ms
7 timing config:load:cli Completed in 1ms
8 timing config:load:env Completed in 0ms
9 timing config:load:file:/home/hugosum/ory-kratos-ui-template/.npmrc Completed in 0ms
10 timing config:load:project Completed in 2ms
11 timing config:load:file:/home/hugosum/.config/npm/npmrc Completed in 2ms
12 timing config:load:user Completed in 2ms
13 timing config:load:file:/home/hugosum/.local/share/npm/etc/npmrc Completed in 0ms
14 timing config:load:global Completed in 0ms
15 timing config:load:validate Completed in 1ms
16 timing config:load:credentials Completed in 0ms
17 timing config:load:setEnvs Completed in 1ms
18 timing config:load Completed in 9ms
19 timing npm:load:configload Completed in 9ms
20 timing npm:load:setTitle Completed in 0ms
21 timing npm:load:setupLog Completed in 1ms
22 timing config:load:flatten Completed in 2ms
23 timing npm:load:cleanupLog Completed in 1ms
24 timing npm:load:configScope Completed in 0ms
25 timing npm:load:projectScope Completed in 1ms
26 timing npm:load Completed in 16ms
27 timing arborist:ctor Completed in 1ms
28 timing idealTree:init Completed in 95ms
29 timing idealTree:userRequests Completed in 1ms
30 silly idealTree buildDeps
31 silly fetch manifest @sveltejs/kit@next
32 timing arborist:ctor Completed in 0ms
33 http fetch GET 200 https://registry.npmjs.org/@sveltejs%2fkit 70ms (cache stale)
34 silly fetch manifest svelte@^3.43.0
35 http fetch GET 200 https://registry.npmjs.org/svelte 6ms (cache stale)
36 silly placeDep ROOT @sveltejs/kit@1.0.0-next.180 OK for: ory-kratos-ui-template@0.0.1 want: next
37 silly fetch manifest @sveltejs/vite-plugin-svelte@^1.0.0-next.26
38 silly fetch manifest cheap-watch@^1.0.4
39 silly fetch manifest vite@^2.6.3
40 http fetch GET 200 https://registry.npmjs.org/@sveltejs%2fvite-plugin-svelte 6ms (cache stale)
41 http fetch GET 200 https://registry.npmjs.org/cheap-watch 7ms (cache stale)
42 http fetch GET 200 https://registry.npmjs.org/vite 8ms (cache stale)
43 timing idealTree:#root Completed in 105ms
44 silly fetch manifest diff-match-patch@^1.0.5
45 http fetch GET 200 https://registry.npmjs.org/diff-match-patch 3ms (cache stale)
46 silly fetch manifest less@*
47 http fetch GET 200 https://registry.npmjs.org/less 4ms (cache stale)
48 silly fetch manifest sass@*
49 http fetch GET 200 https://registry.npmjs.org/sass 4ms (cache stale)
50 silly fetch manifest stylus@*
51 http fetch GET 200 https://registry.npmjs.org/stylus 2ms (cache stale)
52 silly placeDep ROOT @sveltejs/vite-plugin-svelte@1.0.0-next.27 OK for: @sveltejs/kit@1.0.0-next.180 want: ^1.0.0-next.26
53 silly placeDep ROOT vite@2.6.5 OK for: @sveltejs/vite-plugin-svelte@1.0.0-next.27 want: ^2.6.0
54 silly placeDep ROOT cheap-watch@1.0.4 OK for: @sveltejs/kit@1.0.0-next.180 want: ^1.0.4
55 silly fetch manifest @rollup/pluginutils@^4.1.1
56 silly fetch manifest kleur@^4.1.4
57 silly fetch manifest require-relative@^0.8.7
58 silly fetch manifest svelte-hmr@^0.14.7
59 silly fetch manifest esbuild@^0.13.2
60 silly fetch manifest postcss@^8.3.8
61 silly fetch manifest resolve@^1.20.0
62 silly fetch manifest rollup@^2.57.0
63 http fetch GET 200 https://registry.npmjs.org/require-relative 14ms (cache stale)
64 http fetch GET 200 https://registry.npmjs.org/kleur 16ms (cache stale)
65 http fetch GET 200 https://registry.npmjs.org/resolve 14ms (cache stale)
66 http fetch GET 200 https://registry.npmjs.org/@rollup%2fpluginutils 17ms (cache stale)
67 http fetch GET 200 https://registry.npmjs.org/postcss 15ms (cache stale)
68 http fetch GET 200 https://registry.npmjs.org/svelte-hmr 19ms (cache stale)
69 http fetch GET 200 https://registry.npmjs.org/esbuild 19ms (cache stale)
70 http fetch GET 200 https://registry.npmjs.org/rollup 22ms (cache stale)
71 timing idealTree:node_modules/@sveltejs/kit Completed in 60ms
72 silly fetch manifest svelte@^3.34.0
73 silly placeDep ROOT @rollup/pluginutils@4.1.1 OK for: @sveltejs/vite-plugin-svelte@1.0.0-next.27 want: ^4.1.1
74 silly placeDep ROOT kleur@4.1.4 OK for: @sveltejs/vite-plugin-svelte@1.0.0-next.27 want: ^4.1.4
75 silly placeDep ROOT require-relative@0.8.7 OK for: @sveltejs/vite-plugin-svelte@1.0.0-next.27 want: ^0.8.7
76 silly placeDep ROOT svelte-hmr@0.14.7 OK for: @sveltejs/vite-plugin-svelte@1.0.0-next.27 want: ^0.14.7
77 silly fetch manifest estree-walker@^2.0.1
78 http fetch GET 200 https://registry.npmjs.org/estree-walker 6ms (cache stale)
79 timing idealTree:node_modules/@sveltejs/vite-plugin-svelte Completed in 13ms
80 silly placeDep ROOT estree-walker@2.0.2 OK for: @rollup/pluginutils@4.1.1 want: ^2.0.1
81 timing idealTree:node_modules/@rollup/pluginutils Completed in 2ms
82 timing idealTree:node_modules/cheap-watch Completed in 0ms
83 timing idealTree:node_modules/estree-walker Completed in 0ms
84 timing idealTree:node_modules/kleur Completed in 0ms
85 timing idealTree:node_modules/require-relative Completed in 0ms
86 timing idealTree:node_modules/svelte-hmr Completed in 0ms
87 silly placeDep ROOT esbuild@0.13.4 OK for: vite@2.6.5 want: ^0.13.2
88 silly placeDep ROOT postcss@8.3.11 OK for: vite@2.6.5 want: ^8.3.8
89 silly placeDep ROOT resolve@1.20.0 OK for: vite@2.6.5 want: ^1.20.0
90 silly placeDep ROOT rollup@2.58.0 OK for: vite@2.6.5 want: ^2.57.0
91 silly fetch manifest esbuild-android-arm64@0.13.4
92 silly fetch manifest esbuild-darwin-64@0.13.4
93 silly fetch manifest esbuild-darwin-arm64@0.13.4
94 silly fetch manifest esbuild-freebsd-64@0.13.4
95 silly fetch manifest esbuild-freebsd-arm64@0.13.4
96 silly fetch manifest esbuild-linux-32@0.13.4
97 silly fetch manifest esbuild-linux-64@0.13.4
98 silly fetch manifest esbuild-linux-arm@0.13.4
99 silly fetch manifest esbuild-linux-arm64@0.13.4
100 silly fetch manifest esbuild-linux-mips64le@0.13.4
101 silly fetch manifest esbuild-linux-ppc64le@0.13.4
102 silly fetch manifest esbuild-openbsd-64@0.13.4
103 silly fetch manifest esbuild-sunos-64@0.13.4
104 silly fetch manifest esbuild-windows-32@0.13.4
105 silly fetch manifest esbuild-windows-64@0.13.4
106 silly fetch manifest esbuild-windows-arm64@0.13.4
107 silly fetch manifest nanoid@^3.1.30
108 silly fetch manifest picocolors@^1.0.0
109 silly fetch manifest source-map-js@^0.6.2
110 silly fetch manifest is-core-module@^2.2.0
111 silly fetch manifest path-parse@^1.0.6
112 http fetch GET 200 https://registry.npmjs.org/esbuild-darwin-arm64 37ms (cache stale)
113 http fetch GET 200 https://registry.npmjs.org/esbuild-freebsd-arm64 38ms (cache stale)
114 http fetch GET 200 https://registry.npmjs.org/esbuild-freebsd-64 39ms (cache stale)
115 http fetch GET 200 https://registry.npmjs.org/esbuild-linux-64 40ms (cache stale)
116 http fetch GET 200 https://registry.npmjs.org/esbuild-linux-32 43ms (cache stale)
117 http fetch GET 200 https://registry.npmjs.org/esbuild-darwin-64 45ms (cache stale)
118 http fetch GET 200 https://registry.npmjs.org/esbuild-linux-mips64le 46ms (cache stale)
119 http fetch GET 200 https://registry.npmjs.org/esbuild-android-arm64 50ms (cache stale)
120 http fetch GET 200 https://registry.npmjs.org/esbuild-linux-arm 48ms (cache stale)
121 http fetch GET 200 https://registry.npmjs.org/esbuild-sunos-64 48ms (cache stale)
122 http fetch GET 200 https://registry.npmjs.org/esbuild-linux-arm64 49ms (cache stale)
123 http fetch GET 200 https://registry.npmjs.org/esbuild-windows-arm64 48ms (cache stale)
124 http fetch GET 200 https://registry.npmjs.org/nanoid 48ms (cache stale)
125 http fetch GET 200 https://registry.npmjs.org/picocolors 49ms (cache stale)
126 http fetch GET 200 https://registry.npmjs.org/source-map-js 48ms (cache stale)
127 http fetch GET 200 https://registry.npmjs.org/is-core-module 47ms (cache stale)
128 http fetch GET 200 https://registry.npmjs.org/path-parse 48ms (cache stale)
129 http fetch GET 200 https://registry.npmjs.org/esbuild-windows-32 51ms (cache stale)
130 http fetch GET 200 https://registry.npmjs.org/esbuild-openbsd-64 53ms (cache stale)
131 http fetch GET 200 https://registry.npmjs.org/esbuild-windows-64 53ms (cache stale)
132 http fetch GET 200 https://registry.npmjs.org/esbuild-linux-ppc64le 57ms (cache stale)
133 timing idealTree:node_modules/vite Completed in 66ms
134 silly placeDep ROOT esbuild-android-arm64@0.13.4 OK for: esbuild@0.13.4 want: 0.13.4
135 silly placeDep ROOT esbuild-darwin-64@0.13.4 OK for: esbuild@0.13.4 want: 0.13.4
136 silly placeDep ROOT esbuild-darwin-arm64@0.13.4 OK for: esbuild@0.13.4 want: 0.13.4
137 silly placeDep ROOT esbuild-freebsd-64@0.13.4 OK for: esbuild@0.13.4 want: 0.13.4
138 silly placeDep ROOT esbuild-freebsd-arm64@0.13.4 OK for: esbuild@0.13.4 want: 0.13.4
139 silly placeDep ROOT esbuild-linux-32@0.13.4 OK for: esbuild@0.13.4 want: 0.13.4
140 silly placeDep ROOT esbuild-linux-64@0.13.4 OK for: esbuild@0.13.4 want: 0.13.4
141 silly placeDep ROOT esbuild-linux-arm@0.13.4 OK for: esbuild@0.13.4 want: 0.13.4
142 silly placeDep ROOT esbuild-linux-arm64@0.13.4 OK for: esbuild@0.13.4 want: 0.13.4
143 silly placeDep ROOT esbuild-linux-mips64le@0.13.4 OK for: esbuild@0.13.4 want: 0.13.4
144 silly placeDep ROOT esbuild-linux-ppc64le@0.13.4 OK for: esbuild@0.13.4 want: 0.13.4
145 silly placeDep ROOT esbuild-openbsd-64@0.13.4 OK for: esbuild@0.13.4 want: 0.13.4
146 silly placeDep ROOT esbuild-sunos-64@0.13.4 OK for: esbuild@0.13.4 want: 0.13.4
147 silly placeDep ROOT esbuild-windows-32@0.13.4 OK for: esbuild@0.13.4 want: 0.13.4
148 silly placeDep ROOT esbuild-windows-64@0.13.4 OK for: esbuild@0.13.4 want: 0.13.4
149 silly placeDep ROOT esbuild-windows-arm64@0.13.4 OK for: esbuild@0.13.4 want: 0.13.4
150 timing idealTree:node_modules/esbuild Completed in 15ms
151 timing idealTree:node_modules/esbuild-android-arm64 Completed in 0ms
152 timing idealTree:node_modules/esbuild-darwin-64 Completed in 0ms
153 timing idealTree:node_modules/esbuild-darwin-arm64 Completed in 0ms
154 timing idealTree:node_modules/esbuild-freebsd-64 Completed in 0ms
155 timing idealTree:node_modules/esbuild-freebsd-arm64 Completed in 0ms
156 timing idealTree:node_modules/esbuild-linux-32 Completed in 0ms
157 timing idealTree:node_modules/esbuild-linux-64 Completed in 0ms
158 timing idealTree:node_modules/esbuild-linux-arm Completed in 0ms
159 timing idealTree:node_modules/esbuild-linux-arm64 Completed in 0ms
160 timing idealTree:node_modules/esbuild-linux-mips64le Completed in 0ms
161 timing idealTree:node_modules/esbuild-linux-ppc64le Completed in 0ms
162 timing idealTree:node_modules/esbuild-openbsd-64 Completed in 0ms
163 timing idealTree:node_modules/esbuild-sunos-64 Completed in 0ms
164 timing idealTree:node_modules/esbuild-windows-32 Completed in 0ms
165 timing idealTree:node_modules/esbuild-windows-64 Completed in 0ms
166 timing idealTree:node_modules/esbuild-windows-arm64 Completed in 0ms
167 silly placeDep ROOT nanoid@3.1.30 OK for: postcss@8.3.11 want: ^3.1.30
168 silly placeDep node_modules/postcss picocolors@ OK for: postcss@8.3.11 want: ^1.0.0
169 silly placeDep ROOT source-map-js@0.6.2 OK for: postcss@8.3.11 want: ^0.6.2
170 timing idealTree:node_modules/postcss Completed in 7ms
171 timing idealTree:node_modules/nanoid Completed in 0ms
172 silly placeDep ROOT is-core-module@2.8.0 OK for: resolve@1.20.0 want: ^2.2.0
173 silly placeDep ROOT path-parse@1.0.7 OK for: resolve@1.20.0 want: ^1.0.6
174 silly fetch manifest has@^1.0.3
175 http fetch GET 200 https://registry.npmjs.org/has 4ms (cache stale)
176 timing idealTree:node_modules/resolve Completed in 5ms
177 silly placeDep ROOT has@1.0.3 OK for: is-core-module@2.8.0 want: ^1.0.3
178 silly fetch manifest function-bind@^1.1.1
179 http fetch GET 200 https://registry.npmjs.org/function-bind 5ms (cache stale)
180 timing idealTree:node_modules/is-core-module Completed in 7ms
181 silly placeDep ROOT function-bind@1.1.1 OK for: has@1.0.3 want: ^1.1.1
182 timing idealTree:node_modules/has Completed in 1ms
183 timing idealTree:node_modules/function-bind Completed in 0ms
184 timing idealTree:node_modules/path-parse Completed in 0ms
185 timing idealTree:node_modules/rollup Completed in 0ms
186 timing idealTree:node_modules/source-map-js Completed in 0ms
187 timing idealTree:node_modules/postcss/node_modules/picocolors Completed in 0ms
188 timing idealTree:buildDeps Completed in 281ms
189 timing idealTree:fixDepFlags Completed in 9ms
190 timing idealTree Completed in 386ms
191 timing command:install Completed in 405ms
192 verbose type range
193 verbose stack picocolors: No matching version found for picocolors@^1.0.0.
193 verbose stack     at module.exports (/nix/store/26lslfmvwyhspppbinznh111fyaxx62z-nodejs-16.13.0/lib/node_modules/npm/node_modules/npm-pick-manifest/index.js:209:23)
193 verbose stack     at /nix/store/26lslfmvwyhspppbinznh111fyaxx62z-nodejs-16.13.0/lib/node_modules/npm/node_modules/pacote/lib/registry.js:118:26
193 verbose stack     at async Promise.all (index 17)
193 verbose stack     at async Arborist.[buildDepStep] (/nix/store/26lslfmvwyhspppbinznh111fyaxx62z-nodejs-16.13.0/lib/node_modules/npm/node_modules/@npmcli/arborist/lib/arborist/build-ideal-tree.js:1046:5)
193 verbose stack     at async Arborist.buildIdealTree (/nix/store/26lslfmvwyhspppbinznh111fyaxx62z-nodejs-16.13.0/lib/node_modules/npm/node_modules/@npmcli/arborist/lib/arborist/build-ideal-tree.js:216:7)
193 verbose stack     at async Promise.all (index 1)
193 verbose stack     at async Arborist.reify (/nix/store/26lslfmvwyhspppbinznh111fyaxx62z-nodejs-16.13.0/lib/node_modules/npm/node_modules/@npmcli/arborist/lib/arborist/reify.js:149:5)
193 verbose stack     at async Install.install (/nix/store/26lslfmvwyhspppbinznh111fyaxx62z-nodejs-16.13.0/lib/node_modules/npm/lib/install.js:170:5)
194 verbose cwd /home/hugosum/ory-kratos-ui-template
195 verbose Linux 5.15.2
196 verbose argv "/nix/store/26lslfmvwyhspppbinznh111fyaxx62z-nodejs-16.13.0/bin/node" "/etc/profiles/per-user/hugosum/bin/npm" "i"
197 verbose node v16.13.0
198 verbose npm  v8.1.0
199 error code ETARGET
200 error notarget No matching version found for picocolors@^1.0.0.
201 error notarget In most cases you or one of your dependencies are requesting
201 error notarget a package version that doesn't exist.
202 verbose exit 1
```

### System Info

```shell
System:
    OS: Linux 5.15 NixOS 21.11 (Porcupine) 21.11 (Porcupine)
    CPU: (4) x64 Intel(R) Core(TM) i5-7360U CPU @ 2.30GHz
    Memory: 4.62 GB / 7.64 GB
    Container: Yes
    Shell: 5.8 - /nix/store/v7a5iyfh5g4sqqqay7zdxrj21m7s7zd0-zsh-5.8/bin/zsh
  Binaries:
    Node: 16.13.0 - /etc/profiles/per-user/hugosum/bin/node
    npm: 8.1.0 - /etc/profiles/per-user/hugosum/bin/npm
  Browsers:
    Brave Browser: 95.1.31.91
```

### Severity

blocking all usage of SvelteKit

**Comment by rmunn** [comment]
Can't reproduce here. Perhaps you had a temporary network failure while loading https://registry.npmjs.org/picocolors or something, because when I load that URL I see version 1.0.0 of picocolors.

Either that, or it's somehow specific to the NixOS distro, because that's the only thing I couldn't reproduce from your example. I used the `package.json` file you specified, and made sure I was running NPM 8, and `npm install` worked fine for me from that `package.json`.

Could you try again, and see if it works a second time? I suspect you just had a temporary network error that caused that one package to fail. If you can reproduce the error multiple times, then I'd suggest trying again on a Debian or Ubuntu box, to try to prove whether it's something related to NixOS.

**Comment by winston0410** [comment]
I have just tried it again, and still I am getting this error **until I have cleared the cache($XDG_CACHE_HOME/npm)** Maybe there was an error and somehow cached by npm. Closing it now as this should be upstream.
