### ISSUE TITLE
Rollup failed to resolve import "broadcast-channel"

### ISSUE THREAD

**Issue by conanchen** [sveltejs/kit#2942]
### Describe the bug

Rollup failed to resolve import "broadcast-channel"

### Reproduction

https://github.com/moreadgroup/moread-dapp-ebmaster/runs/4343503475?check_suite_focus=true

### Logs

```shell
✓ 70 modules transformed.
[vite]: Rollup failed to resolve import "broadcast-channel" from "node_modules/@sveltestack/svelte-query/svelte/queryCore/broadcastQueryClient-experimental/index.js".
> [vite]: Rollup failed to resolve import "broadcast-channel" from "node_modules/@sveltestack/svelte-query/svelte/queryCore/broadcastQueryClient-experimental/index.js".
This is most likely unintended because it can break your application at runtime.
If you do want to externalize this module explicitly add it to
`build.rollupOptions.external`
This is most likely unintended because it can break your application at runtime.
If you do want to externalize this module explicitly add it to
`build.rollupOptions.external`
Error: [vite]: Rollup failed to resolve import "broadcast-channel" from "node_modules/@sveltestack/svelte-query/svelte/queryCore/broadcastQueryClient-experimental/index.js".
This is most likely unintended because it can break your application at runtime.
If you do want to externalize this module explicitly add it to
`build.rollupOptions.external`
    at onRollupWarning (/home/runner/work/xyzapp/xyzapp/node_modules/vite/dist/node/chunks/dep-e0fe87f8.js:43253:19)
    at onwarn (/home/runner/work/xyzapp/xyzapp/node_modules/vite/dist/node/chunks/dep-e0fe87f8.js:43037:13)
    at Object.onwarn (/home/runner/work/xyzapp/xyzapp/node_modules/rollup/dist/shared/rollup.js:23003:13)
    at ModuleLoader.handleResolveId (/home/runner/work/xyzapp/xyzapp/node_modules/rollup/dist/shared/rollup.js:22347:26)
    at ModuleLoader.resolveDynamicImport (/home/runner/work/xyzapp/xyzapp/node_modules/rollup/dist/shared/rollup.js:22401:26)
    at async /home/runner/work/xyzapp/xyzapp/node_modules/rollup/dist/shared/rollup.js:22305:32
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
Error: failed to run `yarn svelte-kit build` with `sh -c`

Caused by:
    command failed

 app:spawn Command "/home/runner/work/xyzapp/xyzapp/node_modules/@tauri-apps/cli/bin/tauri-cli" failed with exit code: 1 +0ms
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
Error: Process completed with exit code 1.
```

### System Info

```shell
yarn global add envinfo && envinfo --system --npmPackages svelte,rollup,webpack --binaries --browsers
  shell: /bin/bash -e {0}
yarn global v1.22.15
[1/4] Resolving packages...
[2/4] Fetching packages...
[3/4] Linking dependencies...
[4/4] Building fresh packages...
success Installed "envinfo@7.8.1" with binaries:
      - envinfo
Done in 1.81s.

  System:
    OS: macOS 10.15.7
    CPU: (3) x64 Intel(R) Xeon(R) CPU E5-1650 v2 @ 3.50GHz
    Memory: 10.24 GB / 14.00 GB
    Shell: 3.2.57 - /bin/bash
  Binaries:
    Node: 14.18.1 - ~/hostedtoolcache/node/14.18.1/x64/bin/node
    Yarn: 1.22.15 - ~/.yarn/bin/yarn
    npm: 6.14.15 - ~/hostedtoolcache/node/14.18.1/x64/bin/npm
  Browsers:
    Chrome: 96.0.4664.55
    Edge: 95.0.1020.53
    Firefox: 94.0.1
    Safari: 15.1
```

### Severity

blocking an upgrade

**Comment by benmccann** [comment]
https://github.com/moreadgroup/moread-dapp-ebmaster doesn't exist, so I can't see how you've setup your code

`broadcast-channel` should be an optional dependency if you're using the latest `svelte-query` (`1.5.0`)
