### ISSUE TITLE
Sveltekit crashes on startup

### ISSUE THREAD

**Issue by jakthom** [sveltejs/kit#2943]
### Describe the bug

Unable to bootstrap a new Sveltekit app. Looks like it's blowing up here: https://github.com/sveltejs/kit/pull/2726/files#diff-3d3392afaae8a848f5862f73d4cfa9e50f984b68ecd1d91f6c414ece0de4f23bR114

```
 ❯❯❯ npm init svelte@next sample-app
npx: installed 5 in 1.42s

create-svelte version 2.0.0-next.89

Welcome to SvelteKit!

This is beta software; expect bugs and missing features.

Problems? Open an issue on https://github.com/sveltejs/kit/issues if none exists already.

✔ Which Svelte app template? › Skeleton project
✔ Use TypeScript? … No / Yes
✔ Add ESLint for code linting? … No / Yes
✔ Add Prettier for code formatting? … No / Yes

Your project is ready!
✔ Typescript
  Inside Svelte components, use <script lang="ts">
✔ ESLint
  https://github.com/sveltejs/eslint-plugin-svelte3
✔ Prettier
  https://prettier.io/docs/en/options.html
  https://github.com/sveltejs/prettier-plugin-svelte#options

Install community-maintained integrations:
  https://github.com/svelte-add/svelte-adders

Next steps:
  1: cd sample-app
  2: npm install (or pnpm install, etc)
  3: git init && git add -A && git commit -m "Initial commit" (optional)
  4: npm run dev -- --open

To close the dev server, hit Ctrl-C

Stuck? Visit us at https://svelte.dev/chat

~/Desktop ❯❯❯ cd sample-app
~/D/sample-app ❯❯❯ npm install

> esbuild@0.13.15 postinstall /Users/jakthom/Desktop/sample-app/node_modules/esbuild
> node install.js


> svelte-preprocess@4.9.8 postinstall /Users/jakthom/Desktop/sample-app/node_modules/svelte-preprocess
> echo "[svelte-preprocess] Don't forget to install the preprocessors packages that will be used: node-sass/sass, stylus, less, postcss & postcss-load-config, coffeescript, pug, etc..."

[svelte-preprocess] Don't forget to install the preprocessors packages that will be used: node-sass/sass, stylus, less, postcss & postcss-load-config, coffeescript, pug, etc...
npm notice created a lockfile as package-lock.json. You should commit this file.
npm WARN notsup Unsupported engine for @sveltejs/kit@1.0.0-next.201: wanted: {"node":">=14.13"} (current: {"node":"12.22.1","npm":"6.14.12"})
npm WARN notsup Not compatible with your version of node/npm: @sveltejs/kit@1.0.0-next.201
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: esbuild-android-arm64@0.13.15 (node_modules/esbuild/node_modules/esbuild-android-arm64):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for esbuild-android-arm64@0.13.15: wanted {"os":"android","arch":"arm64"} (current: {"os":"darwin","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: esbuild-freebsd-arm64@0.13.15 (node_modules/esbuild/node_modules/esbuild-freebsd-arm64):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for esbuild-freebsd-arm64@0.13.15: wanted {"os":"freebsd","arch":"arm64"} (current: {"os":"darwin","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: esbuild-linux-32@0.13.15 (node_modules/esbuild/node_modules/esbuild-linux-32):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for esbuild-linux-32@0.13.15: wanted {"os":"linux","arch":"ia32"} (current: {"os":"darwin","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: esbuild-freebsd-64@0.13.15 (node_modules/esbuild/node_modules/esbuild-freebsd-64):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for esbuild-freebsd-64@0.13.15: wanted {"os":"freebsd","arch":"x64"} (current: {"os":"darwin","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: esbuild-darwin-arm64@0.13.15 (node_modules/esbuild/node_modules/esbuild-darwin-arm64):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for esbuild-darwin-arm64@0.13.15: wanted {"os":"darwin","arch":"arm64"} (current: {"os":"darwin","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: esbuild-linux-arm@0.13.15 (node_modules/esbuild/node_modules/esbuild-linux-arm):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for esbuild-linux-arm@0.13.15: wanted {"os":"linux","arch":"arm"} (current: {"os":"darwin","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: esbuild-linux-arm64@0.13.15 (node_modules/esbuild/node_modules/esbuild-linux-arm64):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for esbuild-linux-arm64@0.13.15: wanted {"os":"linux","arch":"arm64"} (current: {"os":"darwin","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: esbuild-linux-64@0.13.15 (node_modules/esbuild/node_modules/esbuild-linux-64):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for esbuild-linux-64@0.13.15: wanted {"os":"linux","arch":"x64"} (current: {"os":"darwin","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: esbuild-linux-mips64le@0.13.15 (node_modules/esbuild/node_modules/esbuild-linux-mips64le):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for esbuild-linux-mips64le@0.13.15: wanted {"os":"linux","arch":"mips64el"} (current: {"os":"darwin","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: esbuild-linux-ppc64le@0.13.15 (node_modules/esbuild/node_modules/esbuild-linux-ppc64le):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for esbuild-linux-ppc64le@0.13.15: wanted {"os":"linux","arch":"ppc64"} (current: {"os":"darwin","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: esbuild-windows-32@0.13.15 (node_modules/esbuild/node_modules/esbuild-windows-32):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for esbuild-windows-32@0.13.15: wanted {"os":"win32","arch":"ia32"} (current: {"os":"darwin","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: esbuild-netbsd-64@0.13.15 (node_modules/esbuild/node_modules/esbuild-netbsd-64):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for esbuild-netbsd-64@0.13.15: wanted {"os":"netbsd","arch":"x64"} (current: {"os":"darwin","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: esbuild-sunos-64@0.13.15 (node_modules/esbuild/node_modules/esbuild-sunos-64):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for esbuild-sunos-64@0.13.15: wanted {"os":"sunos","arch":"x64"} (current: {"os":"darwin","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: esbuild-windows-64@0.13.15 (node_modules/esbuild/node_modules/esbuild-windows-64):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for esbuild-windows-64@0.13.15: wanted {"os":"win32","arch":"x64"} (current: {"os":"darwin","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: esbuild-windows-arm64@0.13.15 (node_modules/esbuild/node_modules/esbuild-windows-arm64):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for esbuild-windows-arm64@0.13.15: wanted {"os":"win32","arch":"arm64"} (current: {"os":"darwin","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: esbuild-openbsd-64@0.13.15 (node_modules/esbuild/node_modules/esbuild-openbsd-64):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for esbuild-openbsd-64@0.13.15: wanted {"os":"openbsd","arch":"x64"} (current: {"os":"darwin","arch":"x64"})
npm WARN notsup Unsupported engine for @sveltejs/vite-plugin-svelte@1.0.0-next.30: wanted: {"node":"^14.13.1 || >= 16"} (current: {"node":"12.22.1","npm":"6.14.12"})
npm WARN notsup Not compatible with your version of node/npm: @sveltejs/vite-plugin-svelte@1.0.0-next.30
npm WARN sample-app@0.0.1 No repository field.
npm WARN sample-app@0.0.1 No license field.

added 211 packages from 209 contributors and audited 229 packages in 6.038s

30 packages are looking for funding
  run `npm fund` for details

found 0 vulnerabilities

~/D/sample-app ❯❯❯ npm run dev

> sample-app@0.0.1 dev /Users/jakthom/Desktop/sample-app
> svelte-kit dev

file:///Users/jakthom/Desktop/sample-app/node_modules/@sveltejs/kit/dist/cli.js:861
			https = https || !!vite_config.server?.https;
			                                      ^

SyntaxError: Unexpected token '.'
    at Loader.moduleStrategy (internal/modules/esm/translators.js:140:18)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! sample-app@0.0.1 dev: `svelte-kit dev`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the sample-app@0.0.1 dev script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/jakthom/.npm/_logs/2021-11-28T18_31_20_941Z-debug.log
```

### Reproduction

Go through the `Getting Started` steps here:

https://kit.svelte.dev/docs#introduction-getting-started

### Logs

```shell
0 info it worked if it ends with ok
1 verbose cli [
1 verbose cli   '/Users/jakthom/.nodenv/versions/12.22.1/bin/node',
1 verbose cli   '/Users/jakthom/.nodenv/versions/12.22.1/bin/npm',
1 verbose cli   'run',
1 verbose cli   'dev'
1 verbose cli ]
2 info using npm@6.14.12
3 info using node@v12.22.1
4 verbose run-script [ 'predev', 'dev', 'postdev' ]
5 info lifecycle sample-app@0.0.1~predev: sample-app@0.0.1
6 info lifecycle sample-app@0.0.1~dev: sample-app@0.0.1
7 verbose lifecycle sample-app@0.0.1~dev: unsafe-perm in lifecycle true
8 verbose lifecycle sample-app@0.0.1~dev: PATH: /Users/jakthom/.nodenv/versions/12.22.1/lib/node_modules/npm/node_modules/npm-lifecycle/node-gyp-bin:/Users/jakthom/Desktop/sample-app/node_modules/.bin:/Users/jakthom/.nodenv/versions/12.22.1/bin:/usr/local/Cellar/nodenv/1.4.0/libexec:/Users/jakthom/.poetry/bin:/Users/jakthom/Library/pnpm:/usr/local/Caskroom/google-cloud-sdk/latest/google-cloud-sdk/bin:/Users/jakthom/.local/bin:/Users/jakthom/.nodenv/shims:/Users/jakthom/.pyenv/shims:/usr/local/bin:/usr/local/sbin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/go/bin
9 verbose lifecycle sample-app@0.0.1~dev: CWD: /Users/jakthom/Desktop/sample-app
10 silly lifecycle sample-app@0.0.1~dev: Args: [ '-c', 'svelte-kit dev' ]
11 silly lifecycle sample-app@0.0.1~dev: Returned: code: 1  signal: null
12 info lifecycle sample-app@0.0.1~dev: Failed to exec dev script
13 verbose stack Error: sample-app@0.0.1 dev: `svelte-kit dev`
13 verbose stack Exit status 1
13 verbose stack     at EventEmitter.<anonymous> (/Users/jakthom/.nodenv/versions/12.22.1/lib/node_modules/npm/node_modules/npm-lifecycle/index.js:332:16)
13 verbose stack     at EventEmitter.emit (events.js:314:20)
13 verbose stack     at ChildProcess.<anonymous> (/Users/jakthom/.nodenv/versions/12.22.1/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)
13 verbose stack     at ChildProcess.emit (events.js:314:20)
13 verbose stack     at maybeClose (internal/child_process.js:1022:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:287:5)
14 verbose pkgid sample-app@0.0.1
15 verbose cwd /Users/jakthom/Desktop/sample-app
16 verbose Darwin 21.1.0
17 verbose argv "/Users/jakthom/.nodenv/versions/12.22.1/bin/node" "/Users/jakthom/.nodenv/versions/12.22.1/bin/npm" "run" "dev"
18 verbose node v12.22.1
19 verbose npm  v6.14.12
20 error code ELIFECYCLE
21 error errno 1
22 error sample-app@0.0.1 dev: `svelte-kit dev`
22 error Exit status 1
23 error Failed at the sample-app@0.0.1 dev script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 1, true ]
```

### System Info

```shell
npx envinfo --system --binaries --browsers --npmPackages "{svelte,@sveltejs/*,vite}"
npx: installed 1 in 0.992s

  System:
    OS: macOS 12.0.1
    CPU: (12) x64 Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz
    Memory: 21.59 GB / 64.00 GB
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 12.22.1 - ~/.nodenv/versions/12.22.1/bin/node
    npm: 6.14.12 - ~/.nodenv/versions/12.22.1/bin/npm
  Browsers:
    Chrome: 96.0.4664.55
    Firefox: 94.0
    Safari: 15.1
  npmPackages:
    @sveltejs/adapter-auto: next => 1.0.0-next.3
    @sveltejs/kit: next => 1.0.0-next.201
    svelte: ^3.44.0 => 3.44.2
```

### Severity

annoyance

**Comment by dominikg** [comment]
sveltekit requires node 14 at least. You are on 12 as indicated by the error message
