### ISSUE TITLE
Build fails with vercel adapter

### ISSUE THREAD

**Issue by saiumesh535** [sveltejs/kit#2949]
### Describe the bug

Hello There. 

Production build fails with both auto and vercel adapter.

### Reproduction

Here's the repo https://github.com/saiumesh535/saiumesh-portfolio-svelte

### Logs

```shell
Cloning github.com/saiumesh535/saiumesh-portfolio-svelte (Branch: master, Commit: 3b22f93)
Cloning completed: 605.936ms
Analyzing source code...
Installing build runtime...
Build runtime installed: 2.750s
Looking up build cache...
Build Cache not found
Detected package.json
Installing dependencies...
> esbuild@0.13.15 postinstall /vercel/path0/node_modules/esbuild
> node install.js
> svelte-preprocess@4.9.8 postinstall /vercel/path0/node_modules/svelte-preprocess
> echo "[svelte-preprocess] Don't forget to install the preprocessors packages that will be used: node-sass/sass, stylus, less, postcss & postcss-load-config, coffeescript, pug, etc..."
[svelte-preprocess] Don't forget to install the preprocessors packages that will be used: node-sass/sass, stylus, less, postcss & postcss-load-config, coffeescript, pug, etc...
npm WARN saiumesh-portfolio-svelte@0.0.1 No repository field.
npm WARN saiumesh-portfolio-svelte@0.0.1 No license field.
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: esbuild-android-arm64@0.13.15 (node_modules/esbuild-android-arm64):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for esbuild-android-arm64@0.13.15: wanted {"os":"android","arch":"arm64"} (current: {"os":"linux","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: esbuild-darwin-64@0.13.15 (node_modules/esbuild-darwin-64):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for esbuild-darwin-64@0.13.15: wanted {"os":"darwin","arch":"x64"} (current: {"os":"linux","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: esbuild-darwin-arm64@0.13.15 (node_modules/esbuild-darwin-arm64):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for esbuild-darwin-arm64@0.13.15: wanted {"os":"darwin","arch":"arm64"} (current: {"os":"linux","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: esbuild-freebsd-64@0.13.15 (node_modules/esbuild-freebsd-64):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for esbuild-freebsd-64@0.13.15: wanted {"os":"freebsd","arch":"x64"} (current: {"os":"linux","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: esbuild-freebsd-arm64@0.13.15 (node_modules/esbuild-freebsd-arm64):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for esbuild-freebsd-arm64@0.13.15: wanted {"os":"freebsd","arch":"arm64"} (current: {"os":"linux","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: esbuild-linux-32@0.13.15 (node_modules/esbuild-linux-32):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for esbuild-linux-32@0.13.15: wanted {"os":"linux","arch":"ia32"} (current: {"os":"linux","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: esbuild-linux-arm@0.13.15 (node_modules/esbuild-linux-arm):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for esbuild-linux-arm@0.13.15: wanted {"os":"linux","arch":"arm"} (current: {"os":"linux","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: esbuild-linux-arm64@0.13.15 (node_modules/esbuild-linux-arm64):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for esbuild-linux-arm64@0.13.15: wanted {"os":"linux","arch":"arm64"} (current: {"os":"linux","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: esbuild-linux-mips64le@0.13.15 (node_modules/esbuild-linux-mips64le):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for esbuild-linux-mips64le@0.13.15: wanted {"os":"linux","arch":"mips64el"} (current: {"os":"linux","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: esbuild-linux-ppc64le@0.13.15 (node_modules/esbuild-linux-ppc64le):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for esbuild-linux-ppc64le@0.13.15: wanted {"os":"linux","arch":"ppc64"} (current: {"os":"linux","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: esbuild-netbsd-64@0.13.15 (node_modules/esbuild-netbsd-64):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for esbuild-netbsd-64@0.13.15: wanted {"os":"netbsd","arch":"x64"} (current: {"os":"linux","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@2.3.2 (node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@2.3.2: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: esbuild-windows-arm64@0.13.15 (node_modules/esbuild-windows-arm64):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for esbuild-windows-arm64@0.13.15: wanted {"os":"win32","arch":"arm64"} (current: {"os":"linux","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: esbuild-windows-64@0.13.15 (node_modules/esbuild-windows-64):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for esbuild-windows-64@0.13.15: wanted {"os":"win32","arch":"x64"} (current: {"os":"linux","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: esbuild-windows-32@0.13.15 (node_modules/esbuild-windows-32):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for esbuild-windows-32@0.13.15: wanted {"os":"win32","arch":"ia32"} (current: {"os":"linux","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: esbuild-sunos-64@0.13.15 (node_modules/esbuild-sunos-64):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for esbuild-sunos-64@0.13.15: wanted {"os":"sunos","arch":"x64"} (current: {"os":"linux","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: esbuild-openbsd-64@0.13.15 (node_modules/esbuild-openbsd-64):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for esbuild-openbsd-64@0.13.15: wanted {"os":"openbsd","arch":"x64"} (current: {"os":"linux","arch":"x64"})
added 208 packages from 206 contributors in 9.848s
30 packages are looking for funding
  run `npm fund` for details
Running "npm run build"
> saiumesh-portfolio-svelte@0.0.1 build /vercel/path0
> svelte-kit build
vite v2.6.14 building for production...
transforming...
✓ 27 modules transformed.
rendering chunks...
.svelte-kit/output/client/_app/manifest.json                                  1.85 KiB
.svelte-kit/output/client/_app/layout.svelte-5279acbf.js                      0.53 KiB / gzip: 0.35 KiB
.svelte-kit/output/client/_app/error.svelte-23f6bd68.js                       1.56 KiB / gzip: 0.74 KiB
.svelte-kit/output/client/_app/pages/index.svelte-edc13fa9.js                 4.84 KiB / gzip: 1.81 KiB
.svelte-kit/output/client/_app/pages/about/index.svelte-363e9739.js           3.58 KiB / gzip: 1.43 KiB
.svelte-kit/output/client/_app/assets/start-61d1577b.css                      0.16 KiB / gzip: 0.15 KiB
.svelte-kit/output/client/_app/assets/header-59c0de79.css                     0.33 KiB / gzip: 0.24 KiB
.svelte-kit/output/client/_app/start-74462e2e.js                              18.75 KiB / gzip: 6.91 KiB
.svelte-kit/output/client/_app/chunks/vendor-eee8ec4b.js                      7.33 KiB / gzip: 2.99 KiB
.svelte-kit/output/client/_app/chunks/header-3f8c6730.js                      0.95 KiB / gzip: 0.52 KiB
.svelte-kit/output/client/_app/assets/pages/about/index.svelte-9d481311.css   0.97 KiB / gzip: 0.39 KiB
.svelte-kit/output/client/_app/assets/pages/index.svelte-3d92ee38.css         3.26 KiB / gzip: 0.80 KiB
vite v2.6.14 building SSR bundle for production...
transforming...
✓ 28 modules transformed.
rendering chunks...
.svelte-kit/output/server/app.js                      0.07 KiB
.svelte-kit/output/server/chunks/app-9fde4462.js      50.01 KiB
.svelte-kit/output/server/chunks/layout-da7cd334.js   0.23 KiB
.svelte-kit/output/server/chunks/error-d441c5f4.js    0.71 KiB
.svelte-kit/output/server/chunks/index-30006f4a.js    2.99 KiB
.svelte-kit/output/server/chunks/header-82718567.js   0.49 KiB
.svelte-kit/output/server/chunks/index-974413bf.js    1.56 KiB
Run npm run preview to preview your production build locally.
> Using @sveltejs/adapter-auto
 > .svelte-kit/output/server/chunks/app-9fde4462.js:1495:25: error: Could not resolve "./index-b75365fa.js"
    1495 │       load: () => import("./index-b75365fa.js")
         ╵                          ~~~~~~~~~~~~~~~~~~~~~
 > .svelte-kit/output/server/chunks/app-9fde4462.js:1515:25: error: Could not resolve "./about-a1da8d00.js"
    1515 │       load: () => import("./about-a1da8d00.js")
         ╵                          ~~~~~~~~~~~~~~~~~~~~~
> Build failed with 2 errors:
.svelte-kit/output/server/chunks/app-9fde4462.js:1495:25: error: Could not resolve "./index-b75365fa.js"
.svelte-kit/output/server/chunks/app-9fde4462.js:1515:25: error: Could not resolve "./about-a1da8d00.js"
Error: Build failed with 2 errors:
.svelte-kit/output/server/chunks/app-9fde4462.js:1495:25: error: Could not resolve "./index-b75365fa.js"
.svelte-kit/output/server/chunks/app-9fde4462.js:1515:25: error: Could not resolve "./about-a1da8d00.js"
    at failureErrorWithLog (/vercel/path0/node_modules/esbuild/lib/main.js:1493:15)
    at /vercel/path0/node_modules/esbuild/lib/main.js:1151:28
    at runOnEndCallbacks (/vercel/path0/node_modules/esbuild/lib/main.js:1069:65)
    at buildResponseToResult (/vercel/path0/node_modules/esbuild/lib/main.js:1149:7)
    at /vercel/path0/node_modules/esbuild/lib/main.js:1258:14
    at /vercel/path0/node_modules/esbuild/lib/main.js:629:9
    at handleIncomingPacket (/vercel/path0/node_modules/esbuild/lib/main.js:726:9)
    at Socket.readFromStdout (/vercel/path0/node_modules/esbuild/lib/main.js:596:7)
    at Socket.emit (events.js:400:28)
    at addChunk (internal/streams/readable.js:293:12)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! saiumesh-portfolio-svelte@0.0.1 build: `svelte-kit build`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the saiumesh-portfolio-svelte@0.0.1 build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
npm ERR! A complete log of this run can be found in:
npm ERR!     /vercel/.npm/_logs/2021-11-29T17_29_08_414Z-debug.log
Error: Command "npm run build" exited with 1
```

### System Info

```shell
System:
    OS: macOS 12.0.1
    CPU: (8) x64 Apple M1
    Memory: 53.36 MB / 16.00 GB
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 14.15.5 - ~/.volta/tools/image/node/14.15.5/bin/node
    Yarn: 1.22.11 - ~/.volta/tools/image/yarn/1.22.11/bin/yarn
    npm: 6.14.11 - ~/.volta/tools/image/node/14.15.5/bin/npm
  Browsers:
    Brave Browser: 96.1.32.113
    Chrome: 96.0.4664.55
    Firefox: 94.0.2
    Firefox Nightly: 93.0a1
    Safari: 15.1
  npmPackages:
    @sveltejs/adapter-auto: next => 1.0.0-next.3 
    @sveltejs/adapter-vercel: ^1.0.0-next.31 => 1.0.0-next.31 
    @sveltejs/kit: ^1.0.0-next.201 => 1.0.0-next.201 
    svelte: ^3.44.0 => 3.44.2
```

### Severity

blocking an upgrade

**Comment by saiumesh535** [comment]
When I rename `index.scss` -> `app.scss` it works just fine

**Comment by micahlt** [comment]
Same issue here 😣

**Comment by caboe** [comment]
Same here. Node 14.

**Comment by saiumesh535** [comment]
This works well now just tried. didn't make any changes. pasting config file here 

```
import adapter from '@sveltejs/adapter-auto';
import preprocess from 'svelte-preprocess';

/** @type {import('@sveltejs/kit').Config} */
const config = {
	// Consult https://github.com/sveltejs/svelte-preprocess
	// for more information about preprocessors
	preprocess: preprocess(),

	kit: {
		adapter: adapter(),

		// hydrate the <div id="svelte"> element in src/app.html
		// target: '#svelte'
	}
};

export default config;
```

**Comment by saiumesh535** [comment]
This works well now just tried. didn't make any changes. pasting config file here

import adapter from '@sveltejs/adapter-auto';
import preprocess from 'svelte-preprocess';

/** @type {import('@sveltejs/kit').Config} */
const config = {
	// Consult https://github.com/sveltejs/svelte-preprocess
	// for more information about preprocessors
	preprocess: preprocess(),

	kit: {
		adapter: adapter(),

		// hydrate the <div id="svelte"> element in src/app.html
		// target: '#svelte'
	}
};

export default config;
