### ISSUE TITLE
Building with adapter-static breaks when adding global stylesheet

### ISSUE THREAD

**Issue by mzenz** [sveltejs/kit#2980]
### Describe the bug

`svelte-kit build` command fails when prerendering a SvelteKit site via `adapter-static`. Things work as expected in development mode (i.e. when running via `svelte-kit dev` command).

Repo: https://github.com/mzenz/sveltekit-adapter-static-bug

### Reproduction

- git clone https://github.com/mzenz/sveltekit-adapter-static-bug
- yarn && yarn build

### Logs

```shell
yarn run v1.22.17
warning package.json: No license field
$ svelte-kit build
vite v2.6.14 building for production...
✓ 14 modules transformed.
.svelte-kit/output/client/_app/manifest.json                    1.21 KiB
.svelte-kit/output/client/_app/layout.svelte-39935a5a.js        0.53 KiB / gzip: 0.35 KiB
.svelte-kit/output/client/_app/error.svelte-9a576e1f.js         1.56 KiB / gzip: 0.74 KiB
.svelte-kit/output/client/_app/pages/index.svelte-06800479.js   0.80 KiB / gzip: 0.47 KiB
.svelte-kit/output/client/_app/start-686d0d95.js                18.38 KiB / gzip: 6.81 KiB
.svelte-kit/output/client/_app/assets/start-61d1577b.css        0.16 KiB / gzip: 0.15 KiB
.svelte-kit/output/client/_app/chunks/vendor-af0f2ef7.js        7.08 KiB / gzip: 2.89 KiB
vite v2.6.14 building SSR bundle for production...
✓ 14 modules transformed.
.svelte-kit/output/server/app.js                      0.07 KiB
.svelte-kit/output/server/chunks/app-80c59b7c.js      48.61 KiB
.svelte-kit/output/server/chunks/layout-7184e027.js   0.23 KiB
.svelte-kit/output/server/chunks/error-94681021.js    0.71 KiB
.svelte-kit/output/server/chunks/index-e1f1c6c8.js    0.31 KiB

Run npm run preview to preview your production build locally.

> Using @sveltejs/adapter-static
> 404 /src/css/global.css (linked from /)
Error: 404 /src/css/global.css (linked from /)
    at file:///Users/martin/Development/test/svelte-bug/node_modules/@sveltejs/kit/dist/chunks/index4.js:86:11
    at visit (file:///Users/martin/Development/test/svelte-bug/node_modules/@sveltejs/kit/dist/chunks/index4.js:222:5)
    at async visit (file:///Users/martin/Development/test/svelte-bug/node_modules/@sveltejs/kit/dist/chunks/index4.js:293:6)
    at async prerender (file:///Users/martin/Development/test/svelte-bug/node_modules/@sveltejs/kit/dist/chunks/index4.js:303:6)
    at async Object.prerender (file:///Users/martin/Development/test/svelte-bug/node_modules/@sveltejs/kit/dist/chunks/index4.js:368:4)
    at async adapt (file:///Users/martin/Development/test/svelte-bug/node_modules/@sveltejs/adapter-static/index.js:13:4)
    at async adapt (file:///Users/martin/Development/test/svelte-bug/node_modules/@sveltejs/kit/dist/chunks/index4.js:393:2)
    at async file:///Users/martin/Development/test/svelte-bug/node_modules/@sveltejs/kit/dist/cli.js:896:5
error Command failed with exit code 1.
```
```


### System Info

```shell
System:
    OS: macOS 12.0.1
    CPU: (4) x64 Intel(R) Core(TM) i5-8210Y CPU @ 1.60GHz
    Memory: 161.21 MB / 16.00 GB
    Shell: 3.3.1 - /usr/local/bin/fish
  Binaries:
    Node: 17.0.1 - /usr/local/bin/node
    Yarn: 1.22.17 - /usr/local/bin/yarn
    npm: 8.1.0 - /usr/local/bin/npm
  npmPackages:
    @sveltejs/adapter-static: ^1.0.0-next.21 => 1.0.0-next.21
    @sveltejs/kit: next => 1.0.0-next.201
    svelte: ^3.44.0 => 3.44.2
```

### Severity

serious, but I can work around it

**Comment by AlanBreck** [comment]
If you move the css folder into the static folder, and reference it in app.html as `/css/global.css`, it should work.

The server looks at `static` as the root directory, and things in `src` get compiled and placed in the resulting build folder. As such, it doesn't recognize the `/src/...` path.

**Comment by mzenz** [comment]
> If you move the css folder into the static folder, and reference it in app.html as `/css/global.css`, it should work.
> 
> The server looks at `static` as the root directory, and things in `src` get compiled and placed in the resulting build folder. As such, it doesn't recognize the `/src/...` path.

@AlanBreck that does work but the problem I ran into is that anything inside the static folder does not get minified/preprocessed. I'd like styles to be minified/gziped as well like the rest of the bundle.

**Comment by AlanBreck** [comment]
In that case, you can leave it in the `src` folder, but import it into your Svelte component. Best place for that is usually the topmost `__layout.svelte` component.

```js
// __layout.svelte
import "../css/global.css
```

https://kit.svelte.dev/docs#layouts

**Comment by bluwy** [comment]
@AlanBreck Is correct. At the moment, the CSS path you had is hardcoded to only work in dev mode, hence it doesn't work after a build. Importing the css from `__layout.svelte` is the right way to go. Closing in favour of the solution.
