### ISSUE TITLE
new vite version break adapter-static build of svelte material UI

### ISSUE THREAD

**Issue by scippio** [sveltejs/kit#3016]
### Describe the bug

After update package vite from 2.6.14 to 2.7.1 it break build proces with adapter-static

### Reproduction

+ update package vite to 2.7.1
+ have some @smui packages
+ have adapter-static (1.0.0-next.21)

### Logs

```shell
...
.svelte-kit/output/server/chunks/__layout-616a4756.js   37.83 KiB
.svelte-kit/output/server/chunks/index-4bc5b1fd.js      1.27 KiB
.svelte-kit/output/server/chunks/error-42ca4523.js      0.74 KiB
.svelte-kit/output/server/chunks/index-2a3b487e.js      10.42 KiB

Run npm run preview to preview your production build locally.

> Using @sveltejs/adapter-static
TypeError [ERR_UNKNOWN_FILE_EXTENSION]: Unknown file extension ".svelte" for /path/client-svelte/node_modules/@smui/common/dist/elements/A.svelte
    at new NodeError (node:internal/errors:371:5)
    at Object.file: (node:internal/modules/esm/get_format:72:15)
    at defaultGetFormat (node:internal/modules/esm/get_format:85:38)
    at defaultLoad (node:internal/modules/esm/load:22:14)
    at ESMLoader.load (node:internal/modules/esm/loader:353:26)
    at ESMLoader.moduleProvider (node:internal/modules/esm/loader:274:58)
    at new ModuleJob (node:internal/modules/esm/module_job:66:26)
    at ESMLoader.#createModuleJob (node:internal/modules/esm/loader:291:17)
    at ESMLoader.getModuleJob (node:internal/modules/esm/loader:255:34)
    at async ModuleWrap.<anonymous> (node:internal/modules/esm/module_job:81:21)
TypeError [ERR_UNKNOWN_FILE_EXTENSION]: Unknown file extension ".svelte" for /path/client-svelte/node_modules/@smui/common/dist/elements/A.svelte
> 500 /
Error: 500 /
    at file:///path/client-svelte/node_modules/@sveltejs/kit/dist/chunks/index4.js:86:11
    at visit (file:///path/client-svelte/node_modules/@sveltejs/kit/dist/chunks/index4.js:217:5)
    at async prerender (file:///path/client-svelte/node_modules/@sveltejs/kit/dist/chunks/index4.js:298:6)
    at async Object.prerender (file:///path/client-svelte/node_modules/@sveltejs/kit/dist/chunks/index4.js:363:4)
    at async adapt (file:///path/client-svelte/node_modules/@sveltejs/adapter-static/index.js:13:4)
    at async adapt (file:///path/client-svelte/node_modules/@sveltejs/kit/dist/chunks/index4.js:388:2)
    at async file:///path/client-svelte/node_modules/@sveltejs/kit/dist/cli.js:891:5
```
```


### System Info

```shell
System:
    OS: Linux 5.4 Arch Linux
    CPU: (8) x64 Intel(R) Core(TM) i7-8650U CPU @ 1.90GHz
    Memory: 4.12 GB / 15.27 GB
    Container: Yes
    Shell: 5.1.12 - /bin/bash
  Binaries:
    Node: 17.1.0 - /usr/bin/node
    Yarn: 1.22.17 - /usr/bin/yarn
    npm: 8.1.3 - /usr/bin/npm
  Browsers:
    Chromium: 96.0.4664.45
    Firefox: 94.0.2
  npmPackages:
    @sveltejs/adapter-static: 1.0.0-next.21 => 1.0.0-next.21 
    @sveltejs/kit: 1.0.0-next.195 => 1.0.0-next.195 
    svelte: 3.44.2 => 3.44.2 
    vite: 2.6.14 => 2.6.14 
```

### Severity

annoyance

**Comment by benmccann** [comment]
Issue in that repo: https://github.com/hperrin/svelte-material-ui/issues/375

@scippio can you create a repository with the code in the end state per your instructions and post it here? We get quite a lot of issue reports, so it's too hard for us to do for every single issue that comes in. Thanks!

**Comment by bluwy** [comment]
From the issue linked above, there's a repro included there as well: https://github.com/alanko0511/smui-bug

**Comment by benmccann** [comment]
this is an issue with the library. closing in favor of https://github.com/hperrin/svelte-material-ui/issues/375
