### ISSUE TITLE
'$app/env' not found from file in `prisma/` directory

### ISSUE THREAD

**Issue by wvhulle** [sveltejs/kit#3067]
### Describe the bug

Using the line 

```
import { dev } from '$app/env'
```

inside a database seed function, crashes. It is unable to resolve the `$app` path.

### Reproduction

1. start a new svelte kit project
2. install ts-node and prisma
3. run the database seed function

Reproducible minimal crashing example:
https://github.com/wvhulle/-app-bug-report

### Logs

```shell
Running seed command ` node --experimental-specifier-resolution=node --loader ts-node/esm ./prisma/seed.ts` ...
/home/wvhulle/Documents/bug-report/node_modules/ts-node/src/index.ts:750
    return new TSError(diagnosticText, diagnosticCodes);
           ^
TSError: ⨯ Unable to compile TypeScript:
prisma/prisma.ts:2:21 - error TS2307: Cannot find module '$app/env' or its corresponding type declarations.

2 import { dev } from '$app/env';
                      ~~~~~~~~~~

    at createTSError (/home/wvhulle/Documents/bug-report/node_modules/ts-node/src/index.ts:750:12)
    at reportTSError (/home/wvhulle/Documents/bug-report/node_modules/ts-node/src/index.ts:754:19)
    at getOutput (/home/wvhulle/Documents/bug-report/node_modules/ts-node/src/index.ts:941:36)
    at Object.compile (/home/wvhulle/Documents/bug-report/node_modules/ts-node/src/index.ts:1243:30)
    at /home/wvhulle/Documents/bug-report/node_modules/ts-node/src/esm.ts:282:37
    at Generator.next (<anonymous>)
    at /home/wvhulle/Documents/bug-report/node_modules/ts-node/dist/esm.js:8:71
    at new Promise (<anonymous>)
    at __awaiter (/home/wvhulle/Documents/bug-report/node_modules/ts-node/dist/esm.js:4:12)
    at transformSource (/home/wvhulle/Documents/bug-report/node_modules/ts-node/dist/esm.js:127:16) {
  diagnosticText: "\x1B[96mprisma/prisma.ts\x1B[0m:\x1B[93m2\x1B[0m:\x1B[93m21\x1B[0m - \x1B[91merror\x1B[0m\x1B[90m TS2307: \x1B[0mCannot find module '$app/env' or its corresponding type declarations.\n" +
    '\n' +
    "\x1B[7m2\x1B[0m import { dev } from '$app/env';\n" +
    '\x1B[7m \x1B[0m \x1B[91m                    ~~~~~~~~~~\x1B[0m\n',
  diagnosticCodes: [ 2307 ]
}
```

### System Info

```shell
System:
    OS: Linux 5.15 Manjaro Linux
    CPU: (8) x64 11th Gen Intel(R) Core(TM) i5-1145G7 @ 2.60GHz
    Memory: 528.09 MB / 15.36 GB
    Container: Yes
    Shell: 3.3.1 - /usr/bin/fish
  Binaries:
    Node: 16.13.1 - /usr/bin/node
    Yarn: 1.22.17 - /usr/bin/yarn
    npm: 8.1.4 - /usr/bin/npm
  Browsers:
    Chromium: 96.0.4664.93
    Firefox: 95.0
  npmPackages:
    @sveltejs/adapter-auto: next => 1.0.0-next.4 
    @sveltejs/kit: next => 1.0.0-next.202 
    svelte: ^3.44.0 => 3.44.3
```

### Severity

blocking all usage of SvelteKit

**Comment by wvhulle** [comment]
Okay great 

Just using
```
import pkg from '@prisma/client';
const { PrismaClient } = pkg;
const prisma = new PrismaClient()
```

works.

Do you know how to get rid of the second line?
