### ISSUE TITLE
SCSS preprocessing in Svelte dependencies since Vite 2.7

### ISSUE THREAD

**Issue by hobbes7878** [sveltejs/kit#3071]
### Describe the bug

Since Vite 2.7, Svelte dependencies with SCSS styles don't seem to be correctly preprocessed before the components are handed off to esbuild, which throws an error for an invalid scss loader.

Filing this report with SvelteKit, though it may be better for vite-plugin-svelte? Happy to move if so.

For reference, the reproduction doesn't mess with Vite's `optimizeDeps` options, though have tried adding the library to both `include` and `exclude`, which produced other errors. Can reproduce those if needed, but figure this is furthest upstream example.

The dependency is our svelte components library, built with sveltekit's `package` option [here](https://github.com/reuters-graphics/graphics-svelte-components), for reference.

### Reproduction

https://stackblitz.com/edit/sveltekit-sbsfkj?file=svelte.config.js

### Logs

```shell
> Build failed with 1 error:
error: Invalid loader: "scss" (valid: js, jsx, ts, tsx, css, json, text, base64, dataurl, file, binary)
Error: Build failed with 1 error:
error: Invalid loader: "scss" (valid: js, jsx, ts, tsx, css, json, text, base64, dataurl, file, binary)
    at failureErrorWithLog (/home/projects/sveltekit-sbsfkj/node_modules/esbuild/lib/main.js:1493:15)
    at eval (/home/projects/sveltekit-sbsfkj/node_modules/esbuild/lib/main.js:1151:28)
    at runOnEndCallbacks (/home/projects/sveltekit-sbsfkj/node_modules/esbuild/lib/main.js:941:63)
    at buildResponseToResult (/home/projects/sveltekit-sbsfkj/node_modules/esbuild/lib/main.js:1149:7)
    at eval (/home/projects/sveltekit-sbsfkj/node_modules/esbuild/lib/main.js:1258:14)
    at eval (/home/projects/sveltekit-sbsfkj/node_modules/esbuild/lib/main.js:629:9)
    at handleIncomingPacket (/home/projects/sveltekit-sbsfkj/node_modules/esbuild/lib/main.js:726:9)
    at Socket.readFromStdout (/home/projects/sveltekit-sbsfkj/node_modules/esbuild/lib/main.js:596:7)
    at Socket.EventEmitter.emit (https://sveltekit-sbsfkj.w.staticblitz.com/blitz.a3339ebb87d0fe73c7995fe67420660e0dc95de2.js:6:126633)
    at Socket.w.emit (https://sveltekit-sbsfkj.w.staticblitz.com/blitz.a3339ebb87d0fe73c7995fe67420660e0dc95de2.js:6:1186904)
```

### System Info

```shell
System:
    OS: Linux undefined
    CPU: (4) x64 Intel(R) Core(TM) i9-9880H CPU @ 2.30GHz
    Memory: 0 Bytes / 0 Bytes
    Shell: Unknown - /bin/jsh
  Binaries:
    Node: 14.16.0 - /usr/local/bin/node
    Yarn: 1.22.10 - /bin/yarn
    npm: 7.17.0 - /bin/npm
```

### Severity

blocking an upgrade

**Comment by hobbes7878** [comment]
Was able to reproduce the issue in vite-plugin-svelte. Closing here in favour of that issue for now.
