### ISSUE TITLE
Cannot read properties of undefined (reading 'rimraf')

### ISSUE THREAD

**Issue by benjamin-kirkbride** [sveltejs/kit#3111]
### Describe the bug

Running `npm run build` with the `adapter-static` adapter results in an error:

Here is my `svelte.config.js`:

```
import adapter from "@sveltejs/adapter-static";

export default {
  kit: {
    adapter: adapter({
      // default options are shown
      pages: "build",
      assets: "build",
      fallback: null,
      precompress: false,
    }),
  },
};
```

### Reproduction

 1. install and configure the static adapter
 2. `npm run build`
 3. ???
 4. cry

### Logs

```shell
TypeError: Cannot read properties of undefined (reading 'rimraf')
    at adapt (file:///..../node_modules/@sveltejs/adapter-static/index.js:15:10)
    at adapt (file:///..../node_modules/@sveltejs/kit/dist/chunks/index5.js:322:8)
    at file:///..../node_modules/@sveltejs/kit/dist/cli.js:616:11
```

### System Info

```shell
System:
    OS: Linux 5.14 Debian GNU/Linux bookworm/sid
    CPU: (16) x64 AMD Ryzen 7 2700X Eight-Core Processor
    Memory: 864.09 MB / 23.40 GB
    Container: Yes
    Shell: 5.1.8 - /bin/bash
  Binaries:
    Node: 16.13.1 - ~/.nvm/versions/node/v16.13.1/bin/node
    Yarn: 1.22.17 - ~/.nvm/versions/node/v16.13.1/bin/yarn
    npm: 8.1.2 - ~/.nvm/versions/node/v16.13.1/bin/npm
  Browsers:
    Chrome: 94.0.4606.81
    Chromium: 90.0.4430.212
    Firefox: 93.0
  npmPackages:
    @sveltejs/adapter-node: next => 1.0.0-next.12 
    @sveltejs/adapter-static: ^1.0.0-next.23 => 1.0.0-next.23 
    @sveltejs/kit: next => 1.0.0-next.105 
    svelte: ^3.34.0 => 3.38.2 
```

### Severity

blocking all usage of SvelteKit

**Comment by benjamin-kirkbride** [comment]
I tried installing `rimraf` manually, to no availy

**Comment by babichjacob** [comment]
Your version of `@sveltejs/kit` is 98 versions behind — the latest is `1.0.0-next.203`.

Use `npm upgrade` to upgrade all dependencies by minor versions.

**Comment by benjamin-kirkbride** [comment]
That worked! thanks so much!
