### ISSUE TITLE
unicode routes with style tag don't load 

### ISSUE THREAD

**Issue by luminr** [sveltejs/kit#3125]
### Describe the bug

Hi. Routes with non-latin character in their names (e.g. `あ.svelte`)  don't compile if they have root-level style tags.

### Reproduction

https://stackblitz.com/edit/sveltekit-p8qavo?file=src%2Froutes%2Findex.svelte

### Logs

```shell
[plugin:vite-plugin-svelte] Failed to execute 'btoa' on 'WorkerGlobalScope': The string to be encoded contains characters outside of the Latin1 range.
/home/projects/sveltekit-p8qavo/src/routes/文.svelte
    at SourceMap.toUrl (file:///home/projects/sveltekit-p8qavo/node_modules/svelte/compiler.mjs:24897:72)
    at dom (file:///home/projects/sveltekit-p8qavo/node_modules/svelte/compiler.mjs:24967:56)
    at Module.compile (file:///home/projects/sveltekit-p8qavo/node_modules/svelte/compiler.mjs:31358:15)
    at compileSvelte2 (file:///home/projects/sveltekit-p8qavo/node_modules/@sveltejs/vite-plugin-svelte/dist/index.js:324:37)
    at async TransformContext.transform (file:///home/projects/sveltekit-p8qavo/node_modules/@sveltejs/vite-plugin-svelte/dist/index.js:1471:27)
    at async Object.transform (/home/projects/sveltekit-p8qavo/node_modules/vite/dist/node/chunks/dep-e0fe87f8.js:42396:30)
    at async doTransform (/home/projects/sveltekit-p8qavo/node_modules/vite/dist/node/chunks/dep-e0fe87f8.js:56801:29
```

### System Info

```shell
System:
    OS: Windows 10 10.0.22000
    CPU: -
    Memory: -
  Binaries:
    Node: 17.1.0 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.15 - C:\Program Files\nodejs\yarn.CMD
    npm: 8.1.2 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Edge: Spartan (44.22000.120.0), Chromium (96.0.1054.62)
    Internet Explorer: 11.0.22000.120
  npmPackages:
    @sveltejs/adapter-auto: next => 1.0.0-next.5
    @sveltejs/adapter-vercel: next => 1.0.0-next.32
    @sveltejs/kit: next => 1.0.0-next.206
    svelte: ^3.44.0 => 3.44.3
```

### Severity

serious, but I can work around it

**Comment by benmccann** [comment]
The stack trace shows the issue is in `node_modules/svelte/compiler.mjs`, so this would be a bug in the Svelte compiler
