### ISSUE TITLE
builder.rimraf is not a function

### ISSUE THREAD

**Issue by pavelloz** [sveltejs/kit#3135]
### Describe the bug

I upgraded from .22 to .24 and got this regression:

```
> Using @sveltejs/adapter-static
> builder.rimraf is not a function
TypeError: builder.rimraf is not a function
    at adapt (file:///Users/pavel/projects/test222/node_modules/@sveltejs/adapter-static/index.js:15:12)
    at adapt (file:///Users/pavel/projects/test222/node_modules/@sveltejs/kit/dist/chunks/index4.js:393:8)
    at file:///Users/pavel/projects/test222/node_modules/@sveltejs/kit/dist/cli.js:896:11
```

I see that there were some changes around that 9 https://github.com/sveltejs/kit/commit/ecb423b54d459be8c0693c723799be4171369afd#diff-f3af5914d90b42d7d1ab55f490a7a72f62616570e6f48e58ae1567f8f845260c ) so i decided to report bug.

Thanks for all your great work :)

### Edit

On second thought im not sure it is static-adapter fault. Im trying my best to make it work again, and even on .22 it does not. Which means it might be something else.

### Reproduction

Clone https://github.com/EinLinuus/sveltekit-tailwindcss-template
Change adapter to static
npm run build

### System Info

```shell
System:
    OS: macOS 12.1
    CPU: (10) arm64 Apple M1 Pro
    Memory: 76.98 MB / 16.00 GB
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 14.18.1 - ~/.nvm/versions/node/v14.18.1/bin/node
    Yarn: 1.22.17 - ~/.nvm/versions/node/v14.18.1/bin/yarn
    npm: 8.1.4 - ~/.nvm/versions/node/v14.18.1/bin/npm
  Browsers:
    Chrome: 96.0.4664.110
    Firefox: 95.0.2
    Safari: 15.2
  npmPackages:
    @sveltejs/adapter-auto: next => 1.0.0-next.3 
    @sveltejs/adapter-static: ^1.0.0-next.24 => 1.0.0-next.24 
    @sveltejs/kit: next => 1.0.0-next.201 
    svelte: ^3.44.0 => 3.44.2
```

### Severity

blocking all usage of SvelteKit

**Comment by felipeqq2** [comment]
Are you using the latest version of both `@sveltejs/adapter-static` and `@sveltejs/kit`?

**Comment by pavelloz** [comment]
I dont know, i pasted system info according to issue guidelines, so you can verify that.

**Comment by felipeqq2** [comment]
For me, the error was solved when updating @sveltejs/kit to v1.0.0-next.208.

**Comment by kdheepak** [comment]
I'm running into the exact same issue. I used `console.log(builder)` and I believe @pavelloz is correct, there's a regression in `adapter-static`.  I made the following diff:

```
$ git diff                                                                                                                                                                                                                                                 

packages/adapter-static/index.js
──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────

─────────────────────────────────────────────────────────────────────────────────────┐
12: export default function ({ pages = 'build', assets = pages, fallback, precompres │
─────────────────────────────────────────────────────────────────────────────────────┘
│ 12 │        name: '@sveltejs/adapter-static',                                                                                │ 12 │        name: '@sveltejs/adapter-static',
│ 13 │                                                                                                                         │ 13 │
│ 14 │        async adapt(builder) {                                                                                           │ 14 │        async adapt(builder) {
│    │                                                                                                                         │ 15 │            console.log(builder)
│ 15 │            builder.rimraf(assets);                                                                                      │ 16 │            builder.rimraf(assets);
│ 16 │            builder.rimraf(pages);                                                                                       │ 17 │            builder.rimraf(pages);
│ 17 │                                                                                                                         │ 18 │

```

and this is the output when running `npm run build`:

```
{
  utils: {
    log: [Function: log] {
      success: [Function (anonymous)],
      error: [Function (anonymous)],
      warn: [Function (anonymous)],
      minor: [Function: noop],
      info: [Function: noop]
    },
    rimraf: [Function: rimraf],
    mkdirp: [Function: mkdirp],
    copy: [Function: copy],
    copy_client_files: [Function: copy_client_files],
    copy_server_files: [Function: copy_server_files],
    copy_static_files: [Function: copy_static_files],
    prerender: [AsyncFunction: prerender]
  },
  config: {
    preprocess: {
      defaultLanguages: [Object],
      markup: [AsyncFunction: markup],
      script: [AsyncFunction: script],
      style: [AsyncFunction: style]
    },
    extensions: [ '.svelte' ],
    kit: {
      adapter: [Object],
      amp: false,
      appDir: '_app',
      files: [Object],
      floc: false,
      host: null,
      hostHeader: null,
      hydrate: true,
      package: [Object],
      paths: [Object],
      prerender: [Object],
      router: true,
      serviceWorker: [Object],
      ssr: true,
      target: '#svelte',
      trailingSlash: 'never',
      vite: [Function: input]
    }
  }
}
```

The `builder` object has `utils` that needs to be used in this function.

**Comment by Conduitry** [comment]
You're not on the latest version of `@sveltejs/kit`, which is currently `1.0.0-next.208`. There were coordinated breaking changes in Kit and in the adapters which were released at the same time.

I can't reproduce this on the skeleton app with the latest Kit and adapter-static.

**Comment by rawkode** [comment]
@Conduitry im on 208 and this error still persists 🙁

**Comment by kdheepak** [comment]
I had to delete my node_modules folder and reinstall everything, and then it all worked. Joys of living on the bleeding edge :)

**Comment by gtm-nayan** [comment]
Running into it with adapter-netlify next.37 and kit next.216, it builds and previews fine locally but fails on deploy.

I should note that locally I'm building with Vite v2.7.10, however netlify seems to want to use Vite v2.6.13, prefixing the build command with a ci doesn't help

**Comment by NetOpWibby** [comment]
> I had to delete my node_modules folder and reinstall everything, and then it all worked. Joys of living on the bleeding edge :)

This worked for me. I also had to update my kit config and add placeholder pages for broken links.
