### ISSUE TITLE
Response is not defined

### ISSUE THREAD

**Issue by AlexRMU** [sveltejs/kit#3221]
### Describe the bug

The page in the load function makes a request to endpoint, it returns a normal response, but an error appears:
```svelte
<script lang="ts" context="module">
    import type { Load } from "@sveltejs/kit";
    export const load: Load = async function ({ fetch }) {
        let res;
        try {
            res = await fetch("/api/"); //<-- here
            res = await res.json();
            if (res.ok) {
                return { props: { res: res } };
            }
        } catch (error) {
            return { status: 404, error: error as any };
        }
        return { status: 404, error: res };
    };
</script>
```
It is not in dev mode, but it is in the build from adapter-node.

### Reproduction

I'll do it if necessary, but I think there are enough logs.

### Logs

```shell
ReferenceError: Response is not defined
    at fetch (file:///D:/.../node_modules/@sveltejs/kit/dist/ssr.js:955:7)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async load2 (file:///D:/.../build/middlewares.js:1730:15)
    at async load_node (file:///D:/.../node_modules/@sveltejs/kit/dist/ssr.js:1058:12)
    at async respond$1 (file:///D:/.../node_modules/@sveltejs/kit/dist/ssr.js:1264:15)
    at async render_page (file:///D:/.../node_modules/@sveltejs/kit/dist/ssr.js:1454:19)
    at async resolve (file:///D:/.../node_modules/@sveltejs/kit/dist/ssr.js:1717:10)
    at async Object.handle (file:///D:/.../build/middlewares.js:11718:24)
    at async respond (file:///D:/.../node_modules/@sveltejs/kit/dist/ssr.js:1696:10)
    at async Array.<anonymous> (file:///D:/.../build/middlewares.js:11969:22)
```

### System Info

```shell
System:
    OS: Windows 10 10.0.19042
    CPU: (12) x64 AMD Ryzen 5 2600 Six-Core Processor
    Memory: 1.24 GB / 7.95 GB
  Binaries:
    Node: 16.6.1 - ~\AppData\Roaming\npm\node.CMD
    npm: 7.22.0 - ~\AppData\Roaming\npm\npm.CMD
  Browsers:
    Chrome: 96.0.4664.110
    Edge: Spartan (44.19041.423.0)
  npmPackages:
    @sveltejs/adapter-node: ^1.0.0-next.56 => 1.0.0-next.56
    @sveltejs/kit: ^1.0.0-next.202 => 1.0.0-next.202
    svelte: ^3.44.3 => 3.44.3
```

### Severity

blocking all usage of SvelteKit

**Comment by bluwy** [comment]
I did a quick look and the logs doesn't provide much info. Please provide a reproduction. It is necessary according to the issue template description.
