### ISSUE TITLE
routes with backslash `\` are not resolved.

### ISSUE THREAD

**Issue by Mlocik97** [sveltejs/kit#3341]
### Describe the bug

By RFC 3986 and RFC 1738, backslash in URL is allowed (or resp. should be encoded). So Repro should work. But instead it throws error.

### Reproduction

https://stackblitz.com/edit/sveltekit-ewdree?file=src/routes/w\w.svelte

### Logs

```shell
> Executing task: npm run dev <


> test@0.0.1 dev
> svelte-kit dev

 > .svelte-kit/dev/generated/manifest.js:5:14: error: Could not resolve "../../../src/routes/w/w.svelte"
    5 │   () => import("../../../src/routes/w/w.svelte")
      ╵                ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

> Build failed with 1 error:
.svelte-kit/dev/generated/manifest.js:5:14: error: Could not resolve "../../../src/routes/w/w.svelte"
.svelte-kit/dev/generated/manifest.js:5:14: error: Could not resolve "../../../src/routes/w/w.svelte"
    at failureErrorWithLog (/mnt/sda1/Programovanie/HTTP/test/node_modules/esbuild/lib/main.js:1493:15)
    at /mnt/sda1/Programovanie/HTTP/test/node_modules/esbuild/lib/main.js:1151:28
    at runOnEndCallbacks (/mnt/sda1/Programovanie/HTTP/test/node_modules/esbuild/lib/main.js:941:63)
    at buildResponseToResult (/mnt/sda1/Programovanie/HTTP/test/node_modules/esbuild/lib/main.js:1149:7)
    at /mnt/sda1/Programovanie/HTTP/test/node_modules/esbuild/lib/main.js:1258:14
    at /mnt/sda1/Programovanie/HTTP/test/node_modules/esbuild/lib/main.js:629:9
    at handleIncomingPacket (/mnt/sda1/Programovanie/HTTP/test/node_modules/esbuild/lib/main.js:726:9)
    at Socket.readFromStdout (/mnt/sda1/Programovanie/HTTP/test/node_modules/esbuild/lib/main.js:596:7)
    at Socket.emit (events.js:400:28)
    at Socket.emit (domain.js:475:12)
The terminal process "bash '-c', 'npm run dev'" terminated with exit code: 1.

Terminal will be reused by tasks, press any key to close it.
```

### System Info

```shell
System:
    OS: Linux 5.11 Ubuntu 20.04.3 LTS (Focal Fossa)
    CPU: (8) x64 Intel(R) Core(TM) i5-8300H CPU @ 2.30GHz
    Memory: 1.17 GB / 15.45 GB
    Container: Yes
    Shell: 5.0.17 - /bin/bash
  Browsers:
    Chrome: 97.0.4692.71
    Firefox: 96.0
  npmPackages:
    @sveltejs/adapter-auto: next => 1.0.0-next.10 
    @sveltejs/kit: next => 1.0.0-next.218 
    svelte: ^3.44.0 => 3.45.0
```

### Severity

annoyance

### Additional Information

Not sure if it's not supported because of fucking Windows and it's fucking filesystem (NTFS -> NSFW), but if "Page.svelte" and "page.svelte" at once works fine in project, I think this should too.

**Comment by benmccann** [comment]
I believe this code is generated by Vite. Can you try reproducing it in a Vite project without SvelteKit and filing a bug there? https://github.com/sveltejs/kit#bug-reporting

**Comment by Mlocik97** [comment]
In case of Vue, it doesn't fail, nor run... it just freeze. Hmmmm...
