### ISSUE TITLE
Static build fails when a `<link>` has an external URL

### ISSUE THREAD

**Issue by bseib** [sveltejs/kit#3402]
### Describe the bug

A static build fails when `<head>` contains a stylesheet `<link>` that has an external url. Example is the line `<link rel="stylesheet" href="/webjars/mdi__font/5.8.55/css/materialdesignicons.min.css">` below:

```html
<!DOCTYPE html>
<!-- app.html -->
<html lang="en">
    <head>
        <meta charset="utf-8" />
        <meta name="description" content="Svelte demo app" />
        <link rel="icon" href="%svelte.assets%/favicon.png" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="stylesheet" href="/webjars/mdi__font/5.8.55/css/materialdesignicons.min.css">
        %svelte.head%
    </head>
    <body>
        <div id="svelte">%svelte.body%</div>
    </body>
</html>
```

This svelte static built site is just one part of a broader website, and that stylesheet is served by another server.

This happens when doing a static build with the static adapter.

For `<a>` anchor tags, adding `rel=external` communicated that the link was external. But for a `<link>`, the `rel` attribute is already in use, so not sure what the options are to flag this to the static adapter. I did attempt to change `rel=stylesheet` to `rel=external`, just to see if a temporary hack/workaround could work, but the browser did not "figure out" that it was a stylesheet.

### Reproduction

Here's a repo with a simple reproduction of the issue: https://github.com/bseib/bug-sveltekit-external-link

Just run `npm run build` to reproduce the issue.

### Logs

```shell
$ npm run build
npm WARN lifecycle The node binary used for scripts is C:\Program Files (x86)\Nodist\bin\node.exe but npm is using C:\Program Files
(x86)\Nodist\v-x64\14.15.4\node.exe itself. Use the `--scripts-prepend-node-path` option to include the path for the node binary npm
 was executed with.

> bug-sveltekit-external-link@0.0.1 build C:\git\bug-sveltekit-external-link
> svelte-kit build

vite v2.7.12 building for production...
✓ 33 modules transformed.
.svelte-kit/output/client/_app/assets/svelte-logo-87df40b8.svg                           1.85 KiB
.svelte-kit/output/client/_app/assets/fira-mono-cyrillic-400-normal-046b609f.woff2       9.08 KiB
.svelte-kit/output/client/_app/assets/fira-mono-greek-ext-400-normal-8659ae46.woff2      7.85 KiB
.svelte-kit/output/client/_app/assets/fira-mono-greek-400-normal-1f8b3a07.woff2          10.48 KiB
.svelte-kit/output/client/_app/assets/fira-mono-cyrillic-ext-400-normal-b3140dd3.woff2   16.11 KiB
.svelte-kit/output/client/_app/assets/fira-mono-latin-ext-400-normal-b6331a25.woff2      11.84 KiB
.svelte-kit/output/client/_app/assets/fira-mono-latin-400-normal-a2f9dbe8.woff2          16.44 KiB
.svelte-kit/output/client/_app/assets/fira-mono-all-400-normal-0d19eb5d.woff             75.54 KiB
.svelte-kit/output/client/_app/manifest.json                                             2.37 KiB
.svelte-kit/output/client/_app/pages/__layout.svelte-596c528b.js                         4.74 KiB / gzip: 1.85 KiB
.svelte-kit/output/client/_app/error.svelte-dbc75124.js                                  1.56 KiB / gzip: 0.74 KiB
.svelte-kit/output/client/_app/pages/index.svelte-0e5270be.js                            4.12 KiB / gzip: 1.70 KiB
.svelte-kit/output/client/_app/start-0c50ebf6.js                                         22.09 KiB / gzip: 7.47 KiB
.svelte-kit/output/client/_app/pages/about.svelte-4326887f.js                            2.38 KiB / gzip: 1.10 KiB
.svelte-kit/output/client/_app/pages/todos/index.svelte-0ae12f53.js                      5.69 KiB / gzip: 2.36 KiB
.svelte-kit/output/client/_app/assets/pages/about.svelte-bf4528fa.css                    0.11 KiB / gzip: 0.10 KiB
.svelte-kit/output/client/_app/assets/pages/__layout.svelte-a7861b78.css                 4.96 KiB / gzip: 1.55 KiB
.svelte-kit/output/client/_app/assets/pages/index.svelte-c63fe1c6.css                    1.34 KiB / gzip: 0.47 KiB
.svelte-kit/output/client/_app/chunks/vendor-ee294e9e.js                                 14.16 KiB / gzip: 6.04 KiB
.svelte-kit/output/client/_app/assets/pages/todos/index.svelte-784042c1.css              3.70 KiB / gzip: 1.04 KiB
vite v2.7.12 building SSR bundle for production...
✓ 34 modules transformed.
.svelte-kit/output/server/manifest.json                           2.48 KiB
.svelte-kit/output/server/app.js                                  49.17 KiB
.svelte-kit/output/server/entries/endpoints/todos/index.json.js   0.43 KiB
.svelte-kit/output/server/entries/endpoints/todos/_uid_.json.js   0.42 KiB
.svelte-kit/output/server/entries/pages/__layout.svelte.js        4.57 KiB
.svelte-kit/output/server/entries/pages/error.svelte.js           0.72 KiB
.svelte-kit/output/server/entries/pages/index.svelte.js           8.03 KiB
.svelte-kit/output/server/entries/pages/about.svelte.js           1.30 KiB
.svelte-kit/output/server/entries/pages/todos/index.svelte.js     5.85 KiB
.svelte-kit/output/server/chunks/index-ee9fdf1a.js                4.16 KiB
.svelte-kit/output/server/chunks/_api-cf43c630.js                 0.60 KiB

Run npm run preview to preview your production build locally.

> Using @sveltejs/adapter-static
> 404 /webjars/mdi__font/5.8.55/css/materialdesignicons.min.css (linked from /)
    at file:///C:/git/bug-sveltekit-external-link/node_modules/@sveltejs/kit/dist/chunks/index5.js:314:11
    at visit (file:///C:/git/bug-sveltekit-external-link/node_modules/@sveltejs/kit/dist/chunks/index5.js:473:5)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! bug-sveltekit-external-link@0.0.1 build: `svelte-kit build`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the bug-sveltekit-external-link@0.0.1 build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
```

### System Info

```shell
System:
    OS: Windows 10 10.0.19042
    CPU: (8) x64 Intel(R) Core(TM) i7-3770 CPU @ 3.40GHz
    Memory: 3.73 GB / 15.81 GB
  Binaries:
    Node: 14.15.4 - C:\Program Files (x86)\Nodist\bin\node.EXE
    Yarn: 1.22.5 - C:\Program Files (x86)\Yarn\bin\yarn.CMD
    npm: 6.14.10 - C:\Program Files (x86)\Nodist\bin\npm.EXE
  Browsers:
    Chrome: 97.0.4692.71
    Edge: Spartan (44.19041.1266.0), Chromium (97.0.1072.62)
    Internet Explorer: 11.0.19041.1202
  npmPackages:
    @sveltejs/adapter-auto: next => 1.0.0-next.11
    @sveltejs/adapter-static: ^1.0.0-next.26 => 1.0.0-next.26
    @sveltejs/kit: ^1.0.0-next.229 => 1.0.0-next.232
    svelte: ^3.46.1 => 3.46.2
```

### Severity

blocking all usage of SvelteKit

**Comment by pavelloz** [comment]
I think in when you reference files in your entry .html file you have to have those files in your `/static` directory.

**Comment by Rich-Harris** [comment]
You need to use the `prerender.onError` option — create a function that ignores paths you know to be valid: https://kit.svelte.dev/docs#configuration-prerender

**Comment by longrunningprocess** [comment]
link to docs:  https://kit.svelte.dev/docs/configuration#prerender

**Comment by longrunningprocess** [comment]
FWIW, I just ran into the same thing and was surprised my build was failing for the href... 


```html
<a rel=external href=/auth/login class=button>Log back in again</a>
```

`auth/login` is actually proxied to another app, it's not part of the sveltekit app...  I can write a custom function as suggested by @Rich-Harris above but is there something wrong with the assumption that `rel=external` should not be crawled?
