### ISSUE TITLE
adapter-node ^1.0.0-next.64 - Cannot read properties of undefined (reading 'protocol') 

### ISSUE THREAD

**Issue by stolinski** [sveltejs/kit#3420]
### Describe the bug

`svelte-kit build` with 
"@sveltejs/adapter-node": "^1.0.0-next.64",
"@sveltejs/kit": "^1.0.0-next.234",

### Reproduction

https://stackblitz.com/edit/sveltekit-teapcf?file=svelte.config.js

### Logs

```shell
Cannot read properties of undefined (reading 'protocol')
    at default (file:///Users/scotttolinski/Sites/Level-Up-Tutorials/node_modules/.pnpm/@sveltejs+adapter-node@1.0.0-next.64/node_modules/@sveltejs/adapter-node/index.js:22:14)
    at file:///Users/scotttolinski/Sites/Level-Up-Tutorials/packages/ui/svelte.config.js:24:12
    at ModuleJob.run (node:internal/modules/esm/module_job:185:25)
    at async Promise.all (index 0)
    at async ESMLoader.import (node:internal/modules/esm/loader:281:24)
    at async load_config (file:///Users/scotttolinski/Sites/Level-Up-Tutorials/node_modules/.pnpm/@sveltejs+kit@1.0.0-next.234_sass@1.49.0+svelte@3.46.2/node_modules/@sveltejs/kit/dist/cli.js:849:17)
    at async file:///Users/scotttolinski/Sites/Level-Up-Tutorials/node_modules/.pnpm/@sveltejs+kit@1.0.0-next.234_sass@1.49.0+svelte@3.46.2/node_modules/@sveltejs/kit/dist/cli.js:983:19
```

### System Info

```shell
System:
    OS: macOS 12.1
    CPU: (10) arm64 Apple M1 Max
    Memory: 22.76 GB / 64.00 GB
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 17.0.1 - ~/.nvm/versions/node/v17.0.1/bin/node
    Yarn: 1.22.17 - ~/.nvm/versions/node/v17.0.1/bin/yarn
    npm: 8.1.0 - ~/.nvm/versions/node/v17.0.1/bin/npm
  Browsers:
    Chrome: 97.0.4692.71
    Firefox: 95.0.2
    Firefox Developer Edition: 96.0
    Safari: 15.2
  npmPackages:
    @sveltejs/kit: next => 1.0.0-next.234
    svelte: ^3.44.3 => 3.46.2
```

### Severity

blocking an upgrade

**Comment by nergmada** [comment]
I've had this same issue too, I've found that if you configure environment variable in your adapter config in `svelte.config.js` this error goes away

```javascript
adapter: adapter({
	env: {
		headers: {
			protocol: undefined,
		}
	}
}),
```
But now it's throwing an error regarding `BASE_ENV`

**Comment by lovasoa** [comment]
@nergmada : I opened a separate issue about the base_env problem: https://github.com/sveltejs/kit/issues/3424

**Comment by lovasoa** [comment]
But I think the root problem is that there doesn't seem to be automated tests that can catch adapter-node crashing in its default configuration

**Comment by ranjanified** [comment]
With following in my `svelte-config.js`...
```json
kit: {
    adapter: adapter({
      esbuild: () => {
        platform: 'browser'
      }
    }),
    prerender: {
      default: true
    }
  }
```
It's a different `property`...

```
> Using svelte-adapter-deno
X [ERROR] Cannot read properties of undefined (reading 'color')

    **************\node_modules\esbuild\lib\main.js:246:20:
      246 │   let value = object[key];
          ╵                     ^

    at getFlag (**************\node_modules\esbuild\lib\main.js:246:21)
    at pushLogFlags (**************\node_modules\esbuild\lib\main.js:290:15)
    at flagsForBuildOptions (**************\node_modules\esbuild\lib\main.js:398:3)
    at buildOrServeContinue (**************\node_modules\esbuild\lib\main.js:1220:9)
    at Object.buildOrServe (**************\node_modules\esbuild\lib\main.js:1166:9)
    at **************\node_modules\esbuild\lib\main.js:2092:17
    at new Promise (<anonymous>)
    at Object.build (**************\node_modules\esbuild\lib\main.js:2091:14)
    at Object.build (**************\node_modules\esbuild\lib\main.js:1938:51)
    at adapt (file:///**************/node_modules/svelte-adapter-deno/index.js:79:18)

1 error
> Build failed with 1 error:
**************\node_modules\esbuild\lib\main.js:246:20: ERROR: Cannot read properties of undefined (reading 'color')
**************\node_modules\esbuild\lib\main.js:246:20: ERROR: Cannot read properties of undefined (reading 'color')
    at failureErrorWithLog (**************\node_modules\esbuild\lib\main.js:1612:15)
    at **************\node_modules\esbuild\lib\main.js:1140:18
    at **************\node_modules\esbuild\lib\main.js:1135:9
    at **************\node_modules\esbuild\lib\main.js:675:9
    at handleIncomingPacket (**************\node_modules\esbuild\lib\main.js:772:9)
    at Socket.readFromStdout (**************\node_modules\esbuild\lib\main.js:641:7)
    at Socket.emit (node:events:527:28)
    at addChunk (node:internal/streams/readable:315:12)
    at readableAddChunk (node:internal/streams/readable:289:9)
    at Socket.Readable.push (node:internal/streams/readable:228:10)
```
