### ISSUE TITLE
Build fails on Windows from NTFS Junction Point

### ISSUE THREAD

**Issue by simsrw73** [sveltejs/kit#3579]
### Describe the bug

On Windows, `npm run dev` / `npm run build` / etc. fails if executed in a directory that is an NTFS junction point. It constructs invalid paths.

Not sure that this is a bug, but imay be worth noting.

### Reproduction

On my Windows 11 Pro, I have a junction point in my user directory that points to a directory on another drive.

C:\Users\simsrw73 => H:\projects

If I run `npm run dev` or `npm run build`, etc, from "H:\projects\svelte-proj", everything works as expected. If I run it from "~\projects\svelte-proj", I get pathing failures.

### Logs

```shell
# npm run dev -- --open
 
> learnsv@0.0.1 dev
> svelte-kit dev "--open"
 
Pre-bundling dependencies:
  svelte
  svelte/store
  svelte/animate
  svelte/easing
  svelte/internal
  (...and 2 more)
(this will be run only when your dependencies or config have changed)
 > dep:svelte_motion:2:14: error: Could not resolve "./H:/projects/learning-svelte/learnsv/node_modules/svelte/motion/index.mjs"
    2 │ export * from "./H:/projects/learning-svelte/learnsv/node_modules/svelte/motion/index.mjs"
      ╵               ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
 
 > dep:svelte:2:14: error: Could not resolve "./H:/projects/learning-svelte/learnsv/node_modules/svelte/index.mjs"
    2 │ export * from "./H:/projects/learning-svelte/learnsv/node_modules/svelte/index.mjs"
      ╵               ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
 
 > dep:svelte_animate:2:14: error: Could not resolve "./H:/projects/learning-svelte/learnsv/node_modules/svelte/animate/index.mjs"
    2 │ export * from "./H:/projects/learning-svelte/learnsv/node_modules/svelte/animate/index.mjs"
      ╵               ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
 
 > dep:svelte_easing:2:14: error: Could not resolve "./H:/projects/learning-svelte/learnsv/node_modules/svelte/easing/index.mjs"
    2 │ export * from "./H:/projects/learning-svelte/learnsv/node_modules/svelte/easing/index.mjs"
      ╵               ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
 
 > dep:svelte_internal:2:14: error: Could not resolve "./H:/projects/learning-svelte/learnsv/node_modules/svelte/internal/index.mjs"
    2 │ export * from "./H:/projects/learning-svelte/learnsv/node_modules/svelte/internal/index.mjs"
      ╵               ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
 
 > dep:svelte_store:2:14: error: Could not resolve "./H:/projects/learning-svelte/learnsv/node_modules/svelte/store/index.mjs"
    2 │ export * from "./H:/projects/learning-svelte/learnsv/node_modules/svelte/store/index.mjs"
      ╵               ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
 
 > dep:svelte_transition:2:14: error: Could not resolve "./H:/projects/learning-svelte/learnsv/node_modules/svelte/transition/index.mjs"
    2 │ export * from "./H:/projects/learning-svelte/learnsv/node_modules/svelte/transition/index.mjs"
      ╵               ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
 
> Build failed with 7 errors:
dep:svelte:2:14: error: Could not resolve "./H:/projects/learning-svelte/learnsv/node_modules/svelte/index.mjs"
dep:svelte_animate:2:14: error: Could not resolve "./H:/projects/learning-svelte/learnsv/node_modules/svelte/animate/index.mjs"
dep:svelte_easing:2:14: error: Could not resolve "./H:/projects/learning-svelte/learnsv/node_modules/svelte/easing/index.mjs"
dep:svelte_internal:2:14: error: Could not resolve "./H:/projects/learning-svelte/learnsv/node_modules/svelte/internal/index.mjs"
dep:svelte_motion:2:14: error: Could not resolve "./H:/projects/learning-svelte/learnsv/node_modules/svelte/motion/index.mjs"
...
dep:svelte:2:14: error: Could not resolve "./H:/projects/learning-svelte/learnsv/node_modules/svelte/index.mjs"
dep:svelte_animate:2:14: error: Could not resolve "./H:/projects/learning-svelte/learnsv/node_modules/svelte/animate/index.mjs"
dep:svelte_easing:2:14: error: Could not resolve "./H:/projects/learning-svelte/learnsv/node_modules/svelte/easing/index.mjs"
dep:svelte_internal:2:14: error: Could not resolve "./H:/projects/learning-svelte/learnsv/node_modules/svelte/internal/index.mjs"
dep:svelte_motion:2:14: error: Could not resolve "./H:/projects/learning-svelte/learnsv/node_modules/svelte/motion/index.mjs"
...
    at failureErrorWithLog (H:\projects\learning-svelte\learnsv\node_modules\esbuild\lib\main.js:1493:15)
    at H:\projects\learning-svelte\learnsv\node_modules\esbuild\lib\main.js:1151:28
    at runOnEndCallbacks (H:\projects\learning-svelte\learnsv\node_modules\esbuild\lib\main.js:941:63)
    at buildResponseToResult (H:\projects\learning-svelte\learnsv\node_modules\esbuild\lib\main.js:1149:7)
    at H:\projects\learning-svelte\learnsv\node_modules\esbuild\lib\main.js:1258:14
    at H:\projects\learning-svelte\learnsv\node_modules\esbuild\lib\main.js:629:9
    at handleIncomingPacket (H:\projects\learning-svelte\learnsv\node_modules\esbuild\lib\main.js:726:9)
    at Socket.readFromStdout (H:\projects\learning-svelte\learnsv\node_modules\esbuild\lib\main.js:596:7)
    at Socket.emit (node:events:390:28)
    at addChunk (node:internal/streams/readable:315:12)
```

### System Info

```shell
System:
    OS: Windows 10 10.0.22000
    CPU: (16) x64 Intel(R) Core(TM) i9-9900K CPU @ 3.60GHz
    Memory: 12.32 GB / 31.92 GB
  Binaries:
    Node: 16.13.2 - ~\scoop\apps\nvm\current\nodejs\nodejs\node.EXE
    npm: 8.1.2 - ~\scoop\apps\nvm\current\nodejs\nodejs\npm.CMD
  Browsers:
    Edge: Spartan (44.22000.120.0), Chromium (97.0.1072.69)
    Internet Explorer: 11.0.22000.120
  npmPackages:
    @sveltejs/adapter-auto: next => 1.0.0-next.17
    @sveltejs/kit: next => 1.0.0-next.247
    svelte: ^3.44.0 => 3.46.3
```

### Severity

annoyance

**Comment by dominikg** [comment]
Please check if it also happens in a vanilla vite project `npm init vite`.

**Comment by simsrw73** [comment]
It fails identically with vite.

**Comment by dominikg** [comment]
You should report this in vite repo then. Handling differences with windows file system in vite is a ****** . 
This use of junctions could be considered an edge case so if you don't rely on it completely i suggest you just don't run projects across these.

**Comment by Rich-Harris** [comment]
I'm going to close this as there's probably not much we can do about it within SvelteKit
