### ISSUE TITLE
Build manifest references non existent error page component

### ISSUE THREAD

**Issue by JeanJPNM** [sveltejs/kit#3625]
### Describe the bug

When starting dev or build mode on an app generated after running `npm init svelte@next`, an error is thrown saying that the default error page does not exist.

### Reproduction

Generate a template app using `npm init svelte@next` and start dev mode

### Logs

```shell
> svelte-kit-test-repo@0.0.1 dev C:\devenv\projects\svelte-kit-test-repo
> svelte-kit dev

 > .svelte-kit/generated/manifest.js:3:14: error: Could not resolve "..\\runtime\\components\\error.svelte" (mark it as external to exclude it from the bundle, or add ".catch()" to handle the failure at run-time)
    3 │   () => import("..\\runtime\\components\\error.svelte"),
      ╵                ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

> Build failed with 1 error:
.svelte-kit/generated/manifest.js:3:14: error: Could not resolve "..\\runtime\\components\\error.svelte" (mark it as external to exclude it from the bundle, or add ".catch()" to handle the failure at run-time)
.svelte-kit/generated/manifest.js:3:14: error: Could not resolve "..\\runtime\\components\\error.svelte" (mark it as external to exclude it from the bundle, or add ".catch()" to handle the failure at run-time)
    at failureErrorWithLog (C:\devenv\forks\kit\node_modules\.pnpm\esbuild@0.13.15\node_modules\esbuild\lib\main.js:1493:15)
    at runOnEndCallbacks (C:\devenv\forks\kit\node_modules\.pnpm\esbuild@0.13.15\node_modules\esbuild\lib\main.js:941:63)
    at buildResponseToResult (C:\devenv\forks\kit\node_modules\.pnpm\esbuild@0.13.15\node_modules\esbuild\lib\main.js:1149:7)
    at C:\devenv\forks\kit\node_modules\.pnpm\esbuild@0.13.15\node_modules\esbuild\lib\main.js:1258:14
    at C:\devenv\forks\kit\node_modules\.pnpm\esbuild@0.13.15\node_modules\esbuild\lib\main.js:629:9
    at handleIncomingPacket (C:\devenv\forks\kit\node_modules\.pnpm\esbuild@0.13.15\node_modules\esbuild\lib\main.js:726:9)
    at Socket.readFromStdout (C:\devenv\forks\kit\node_modules\.pnpm\esbuild@0.13.15\node_modules\esbuild\lib\main.js:596:7)
    at Socket.emit (events.js:400:28)
    at addChunk (internal/streams/readable.js:293:12)
```

### System Info

```shell
System:
    OS: Windows 10 10.0.19044
    CPU: (4) x64 Intel(R) Core(TM) i5-3230M CPU @ 2.60GHz
    Memory: 890.32 MB / 7.89 GB
  Binaries:
    Node: 14.18.3 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.17 - C:\Program Files\nodejs\yarn.CMD
    npm: 6.14.15 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Chrome: 97.0.4692.99
    Edge: Spartan (44.19041.1266.0), Chromium (97.0.1072.76)
    Internet Explorer: 11.0.19041.1202
  npmPackages:
    @sveltejs/adapter-auto: next => 1.0.0-next.17
    @sveltejs/kit: next => 1.0.0-next.250
    svelte: ^3.46.0 => 3.46.3
```

### Severity

annoyance

**Comment by benmccann** [comment]
I suspect this is a Windows-only bug or we'd have had other reports of it. None of the maintainers are on Windows except for one WSL user, so I'd love any help you can offer with this one

**Comment by JeanJPNM** [comment]
I'm closing this issue because the version of the svelte kit running on the repo was a fork linked via pnpm. The issue can't be reproduced after installing the right version of the svelte kit. Sorry.

**Comment by benmccann** [comment]
Thanks for following up and closing the issue!

If you have any desire to lend a hand with other Windows issues, we're currently looking for some help on https://github.com/vitejs/vite/pull/6518
