### ISSUE TITLE
Import issue with deeply nested dependency

### ISSUE THREAD

**Issue by antony** [sveltejs/kit#3626]
### Describe the bug

A tough one to name, as I'm not clear on the root cause. This is possible an issue with Vite based on @bluwy and my own discussions, but possibly also the vite-svelte plugin.

I have a pnpm monorepo which I have trimmed down to a few core files. A deeply nested require of an external (to the monorepo) dependency appears to cause a completely unrelated import issue with the `package.json` of a dependency which is native to the monorepo.

Trying to reduce nesting of components within the application appears to resolve the issue. I believe that all the exports are valid and correct.

Others trying to run this monorepo might stumble, since the dependency which causes the issue (not the one in the error message!) is private to us. I will grant Bjorn access so that he can investigate, and in the meantime try to reproduce with a non-private dependency.

I have upgraded the version of vite which SvelteKit uses in this repro to a recent beta version, in case that resolved the issue, however, it did not.

### Reproduction

https://github.com/beyonk-adventures/kit-dep-issue-repro

### Logs

```shell
18:20:47 [vite] Internal server error: Cannot find module '@beyonk/avatar/package.json' imported from '/home/antony/Projects/lander/components/brand/src/lib/header/@root'
  Plugin: vite:import-analysis
  File: /home/antony/Projects/lander/components/brand/src/lib/header/ProfileButton.svelte
      at viteResolve (/home/antony/Projects/lander/node_modules/.pnpm/vite@2.7.13_sass@1.43.4/node_modules/vite/dist/node/chunks/dep-f5552faa.js:60126:25)
      at Function._resolveFilename (/home/antony/Projects/lander/node_modules/.pnpm/vite@2.7.13_sass@1.43.4/node_modules/vite/dist/node/chunks/dep-f5552faa.js:60140:28)
      at Function.requireRelative.resolve (/home/antony/Projects/lander/node_modules/.pnpm/require-relative@0.8.7/node_modules/require-relative/index.js:30:17)
      at resolveViaPackageJsonSvelte (file:///home/antony/Projects/lander/node_modules/.pnpm/@sveltejs+vite-plugin-svelte@1.0.0-next.34_svelte@3.46.3+vite@2.7.13/node_modules/@sveltejs/vite-plugin-svelte/dist/index.js:1388:38)
      at Context.resolveId (file:///home/antony/Projects/lander/node_modules/.pnpm/@sveltejs+vite-plugin-svelte@1.0.0-next.34_svelte@3.46.3+vite@2.7.13/node_modules/@sveltejs/vite-plugin-svelte/dist/index.js:1532:26)
      at Object.resolveId (/home/antony/Projects/lander/node_modules/.pnpm/vite@2.7.13_sass@1.43.4/node_modules/vite/dist/node/chunks/dep-f5552faa.js:36922:55)
      at async TransformContext.resolve (/home/antony/Projects/lander/node_modules/.pnpm/vite@2.7.13_sass@1.43.4/node_modules/vite/dist/node/chunks/dep-f5552faa.js:36721:23)
      at async normalizeUrl (/home/antony/Projects/lander/node_modules/.pnpm/vite@2.7.13_sass@1.43.4/node_modules/vite/dist/node/chunks/dep-f5552faa.js:73701:34)
      at async TransformContext.transform (/home/antony/Projects/lander/node_modules/.pnpm/vite@2.7.13_sass@1.43.4/node_modules/vite/dist/node/chunks/dep-f5552faa.js:73843:57)
      at async Object.transform (/home/antony/Projects/lander/node_modules/.pnpm/vite@2.7.13_sass@1.43.4/node_modules/vite/dist/node/chunks/dep-f5552faa.js:36985:30)
```

### System Info

```shell
System:
    OS: Linux 5.11 Ubuntu 21.04 (Hirsute Hippo)
    CPU: (4) x64 Intel(R) Core(TM) i5-4300U CPU @ 1.90GHz
    Memory: 186.67 MB / 7.67 GB
    Container: Yes
    Shell: 5.8 - /usr/bin/zsh
  Binaries:
    Node: 14.18.1 - ~/.volta/tools/image/node/14.18.1/bin/node
    npm: 6.14.15 - ~/.volta/tools/image/node/14.18.1/bin/npm
  Browsers:
    Chrome: 96.0.4664.110
    Chromium: 97.0.4692.99
    Firefox: 95.0.1
```

### Severity

blocking all usage of SvelteKit

### Additional Information

Instructions to recreate are in the readme. Essentially install, run, and visit in the browser.

Unfortunately this is a complete blocker for me right now, I could work around it in a different monorepo application by not having a specific nested path in my browser, but on returning to my other application, simply loading the main url causes the error to occur.

**Comment by benmccann** [comment]
If I add `"@beyonk/avatar": "workspace:^0.2.3",` to `apps/marketing/package.json` then I no longer get the error (though I also don't see any contents rendered on the screen)

This seems likely to be a bug with pnpm monorepo support in `vite-plugin-svelte`. The stack trace includes this line: https://github.com/sveltejs/vite-plugin-svelte/blob/1901b424f0abc1212329fff7c4748eef383f9ec3/packages/vite-plugin-svelte/src/utils/resolve.ts#L6
