### ISSUE TITLE
"TypeError: Line must be greater than or equal to 1, got 0" when cross-fetching endpoints

### ISSUE THREAD

**Issue by danawoodman** [sveltejs/kit#3638]
### Describe the bug

When attempting to help a user on Discord who was trying to fetch from one endpoint (say `src/routes/foo.json.js`) from another (say `src/routes/bar.json.js`). I attempted this locally with the latest version of Kit and received a somewhat confusing error message:

```
TypeError: Line must be greater than or equal to 1, got 0
```

I'm not actually clear if doing such a thing is intended to be supported. If so, I would assume it should do what would be expected, if not, then perhaps it could present a clearer error to the user?

### Reproduction

Create two endpoints, one `src/routes/bar.json.js`:

```js
export async function get() {
  return {
    body: { bar: true },
    headers: { "content-type": "application/json" },
  };
}
```

... and `src/routes/foo.json.js`:

```js
export async function get() {
  const resp = await fetch("/bar.json");
  const bar = await resp.json();
  return {
    body: { bar },
    headers: { "content-type": "application/json" },
  };
}
```

Then attempt to access `/foo.json` and receive the above error.

### Logs

```shell
TypeError: Line must be greater than or equal to 1, got 0
    at BasicSourceMapConsumer.SourceMapConsumer_findMapping [as _findMapping] (/Users/danawoodman/code/webdev/node_modules/.pnpm/vite@2.7.13/node_modules/vite/dist/node/chunks/dep-f5552faa.js:58887:13)
    at BasicSourceMapConsumer.SourceMapConsumer_originalPositionFor [as originalPositionFor] (/Users/danawoodman/code/webdev/node_modules/.pnpm/vite@2.7.13/node_modules/vite/dist/node/chunks/dep-f5552faa.js:58956:22)
    at /Users/danawoodman/code/webdev/node_modules/.pnpm/vite@2.7.13/node_modules/vite/dist/node/chunks/dep-f5552faa.js:59897:34
    at String.replace (<anonymous>)
    at /Users/danawoodman/code/webdev/node_modules/.pnpm/vite@2.7.13/node_modules/vite/dist/node/chunks/dep-f5552faa.js:59885:21
    at Array.map (<anonymous>)
    at ssrRewriteStacktrace (/Users/danawoodman/code/webdev/node_modules/.pnpm/vite@2.7.13/node_modules/vite/dist/node/chunks/dep-f5552faa.js:59884:10)
    at Object.ssrFixStacktrace (/Users/danawoodman/code/webdev/node_modules/.pnpm/vite@2.7.13/node_modules/vite/dist/node/chunks/dep-f5552faa.js:60382:36)
    at Object.get_stack (file:///Users/danawoodman/code/webdev/node_modules/.pnpm/@sveltejs+kit@1.0.0-next.249_svelte@3.46.3/node_modules/@sveltejs/kit/dist/chunks/index.js:2472:14)
    at render_response (file:///Users/danawoodman/code/webdev/node_modules/.pnpm/@sveltejs+kit@1.0.0-next.249_svelte@3.46.3/node_modules/@sveltejs/kit/dist/chunks/index.js:1004:25)
```

### System Info

```shell
System:
    OS: macOS 11.6
    CPU: (8) arm64 Apple M1
    Memory: 151.55 MB / 16.00 GB
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 17.2.0 - /var/folders/j4/3_1h9_mn6w5g4p438nym2vl40000gn/T/fnm_multishells/16984_1643228350745/bin/node
    npm: 8.1.4 - /var/folders/j4/3_1h9_mn6w5g4p438nym2vl40000gn/T/fnm_multishells/16984_1643228350745/bin/npm
  Browsers:
    Brave Browser: 97.1.34.80
    Chrome: 97.0.4692.99
    Firefox: 91.0.2
    Safari: 15.0
  npmPackages:
    @sveltejs/adapter-auto: 1.0.0-next.17 => 1.0.0-next.17 
    @sveltejs/kit: 1.0.0-next.249 => 1.0.0-next.249 
    svelte: 3.46.3 => 3.46.3
```

### Severity

annoyance

**Comment by benmccann** [comment]
Would you mind pushing the code to a repository or https://sveltekit.new/ project? It will save us a bit of time in debugging this. Thanks!

**Comment by danawoodman** [comment]
@benmccann does this help? https://stackblitz.com/edit/sveltejs-kit-template-default-sbvdu1?file=src%2Froutes%2Ffoo.json.js&terminal=dev
