### ISSUE TITLE
adapter-static: specifying a kit.paths.base causes a 500 on build

### ISSUE THREAD

**Issue by hhhapz** [sveltejs/kit#3654]
### Describe the bug

The title basically describes it all. I have two commits on this example repository where the only thing I change is uncommenting the paths directory. Otherwise, it's the default template that is created when using `npm init`. 

### Reproduction

You can see the offending line change here: [hhhapz/kit-adapter-fail](https://github.com/hhhapz/kit-adapter-fail/commit/6d1926c4dfcf9e8d96043bfd72c12aa63e2769d8)

Here's the commands I ran:

```
pnpm init svelte@next static-example
pnpm install -D @sveltejs/adapter-static@next
<edit svelte.config.js, as seen in the above repo>
pnpm build
```

### Logs

Here is the full stack trace:

```
> Using @sveltejs/adapter-static
SyntaxError: Unexpected end of JSON input
    at JSON.parse (<anonymous>)
    at Proxy.<anonymous> (file:///home/h/code/web/static-example/.svelte-kit/output/server/app.js:1203:29)
    at async load (file:///home/h/code/web/static-example/.svelte-kit/output/server/entries/pages/todos/index.svelte.js:13:23)
    at async load_node (file:///home/h/code/web/static-example/.svelte-kit/output/server/app.js:1224:14)
    at async respond$1 (file:///home/h/code/web/static-example/.svelte-kit/output/server/app.js:1348:22)
    at async render_page (file:///home/h/code/web/static-example/.svelte-kit/output/server/app.js:1475:20)
    at async resolve (file:///home/h/code/web/static-example/.svelte-kit/output/server/app.js:1591:103)
    at async Object.handle (file:///home/h/code/web/static-example/.svelte-kit/output/server/app.js:1676:20)
    at async respond (file:///home/h/code/web/static-example/.svelte-kit/output/server/app.js:1561:22)
    at async visit (file:///home/h/code/web/static-example/node_modules/.pnpm/@sveltejs+kit@1.0.0-next.252_svelte@3.46.3/node_modules/@sveltejs/kit/dist/chunks/index5.js:534:20)
> 500 /todos
    at file:///home/h/code/web/static-example/node_modules/.pnpm/@sveltejs+kit@1.0.0-next.252_svelte@3.46.3/node_modules/@sveltejs/kit/dist/chunks/index5.js:407:11
    at visit (file:///home/h/code/web/static-example/node_modules/.pnpm/@sveltejs+kit@1.0.0-next.252_svelte@3.46.3/node_modules/@sveltejs/kit/dist/chunks/index5.js:581:5)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
 ELIFECYCLE  Command failed with exit code 1.
```

### System Info

```shell
System:
    OS: Linux 5.16 Arch Linux
    CPU: (12) x64 AMD Ryzen 5 2600 Six-Core Processor
    Memory: 10.55 GB / 15.62 GB
    Container: Yes
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 17.3.0 - /sbin/node
    Yarn: 1.22.17 - /sbin/yarn
    npm: 8.4.0 - /sbin/npm
  Browsers:
    Chromium: 97.0.4692.99
    Firefox: 96.0.3
  npmPackages:
    @sveltejs/adapter-auto: next => 1.0.0-next.17 
    @sveltejs/adapter-static: ^1.0.0-next.26 => 1.0.0-next.26 
    @sveltejs/kit: next => 1.0.0-next.252 
    svelte: ^3.46.0 => 3.46.3 
```

### Severity

blocking all usage of building SvelteKit, with the option enabled.

**Comment by mrkishi** [comment]
Is this still an issue? I couldn't reproduce it on `kit@next.306` and `adapter-static@next.29`. I got a different error but it was for a legitimate 404.
