### ISSUE TITLE
TypeError: Cannot read property 'info' of undefined

### ISSUE THREAD

**Issue by lamualfa** [sveltejs/kit#3864]
### Describe the bug

Error when run `npm run build` locally also in vercel.

![image](https://user-images.githubusercontent.com/39755201/153706960-4116f52b-f4b6-4eae-88b4-d081ab273ec4.png)

After searching for the cause of the problem, i found that `builder.log` has moved to `builder.utils.log`. I tried to change it to `builder.utils.log`, and the build process went back to normal.

https://github.com/sveltejs/kit/blob/52454ed4fe79c4385fd3a41d1f88767a4013319b/packages/adapter-auto/index.js#L11

# Logs

Before i change the `builder.log`:

```bash
Run npm run preview to preview your production build locally.

> Using @sveltejs/adapter-auto
> Cannot read property 'warn' of undefined
TypeError: Cannot read property 'warn' of undefined
    at adapt (file:///home/lamualfa/Repositories/lamualfa/tuban-petro-web/node_modules/@sveltejs/adapter-auto/index.js:35:16)
    at adapt (file:///home/lamualfa/Repositories/lamualfa/tuban-petro-web/node_modules/@sveltejs/kit/dist/chunks/index4.js:393:8)
    at file:///home/lamualfa/Repositories/lamualfa/tuban-petro-web/node_modules/@sveltejs/kit/dist/cli.js:896:11
```

After that:

```bash
Run npm run preview to preview your production build locally.

> Using @sveltejs/adapter-auto
  Could not detect a supported production environment. See https://kit.svelte.dev/docs#adapters to learn how to configure your app to run on the platform of your choosing
  ✔ done
```

# `@sveltejs/adapter-auto`

## Before

```js
import { adapters } from './adapters.js';

/** @type {import('.')} **/
export default function () {
	return {
		name: '@sveltejs/adapter-auto',

		async adapt(builder) {
			for (const candidate of adapters) {
				if (candidate.test()) {
					builder.log.info(`Detected environment: ${candidate.name}. Using ${candidate.module}`);

					let module;

					try {
						module = await import(candidate.module);
					} catch (error) {
						if (
							error.code === 'ERR_MODULE_NOT_FOUND' &&
							error.message.startsWith(`Cannot find package '${candidate.module}'`)
						) {
							throw new Error(
								`It looks like ${candidate.module} is not installed. Please install it and try building your project again.`
							);
						}

						throw error;
					}

					const adapter = module.default();
					return adapter.adapt(builder);
				}
			}

			builder.log.warn(
				'Could not detect a supported production environment. See https://kit.svelte.dev/docs#adapters to learn how to configure your app to run on the platform of your choosing'
			);
		}
	};
}
```

## After

```js
import { adapters } from './adapters.js';

/** @type {import('.')} **/
export default function () {
	return {
		name: '@sveltejs/adapter-auto',

		async adapt(builder) {
			for (const candidate of adapters) {
				if (candidate.test()) {
					builder.utils.log.info(`Detected environment: ${candidate.name}. Using ${candidate.module}`);

					let module;

					try {
						module = await import(candidate.module);
					} catch (error) {
						if (
							error.code === 'ERR_MODULE_NOT_FOUND' &&
							error.message.startsWith(`Cannot find package '${candidate.module}'`)
						) {
							throw new Error(
								`It looks like ${candidate.module} is not installed. Please install it and try building your project again.`
							);
						}

						throw error;
					}

					const adapter = module.default();
					return adapter.adapt(builder);
				}
			}

			builder.utils.log.warn(
				'Could not detect a supported production environment. See https://kit.svelte.dev/docs/adapters to learn how to configure your app to run on the platform of your choosing'
			);
		}
	};
}
```

### Reproduction

Delete the `node_modules` directory and run `npm install` again to install the new version of svelte-kit. Then run `npm run build` and you'll get this error.

### System Info

```shell
- `@sveltejs/adapter-auto`: `^1.0.0-next.22`
```

### Severity

blocking all usage of SvelteKit

**Comment by benmccann** [comment]
This sounds to me like you have incompatible versions of SvelteKit and the adapter. Please update both to the latest versions

**Comment by lamualfa** [comment]
solved by removing the `node_modules` folder and running `npm install`.
