### ISSUE TITLE
Demo App: Todo doesn't work without Javascript

### ISSUE THREAD

**Issue by decherd** [sveltejs/kit#3952]
### Describe the bug

The Demo App Todo page does not work without Javascript and returns a 500 status code along with this error: Body returned from shadow endpoint request handler must be a plain object.

### Reproduction

I don't think I need to link back to this repo. Again, it is just the demo app.

### Logs

```shell
Body returned from shadow endpoint request handler must be a plain object
Error: Body returned from shadow endpoint request handler must be a plain object
    at validate_shadow_output (file:///Users/drew/Projects/demo_app2/.svelte-kit/runtime/server/index.js:1999:9)
    at load_shadow_data (file:///Users/drew/Projects/demo_app2/.svelte-kit/runtime/server/index.js:1910:38)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async load_node (file:///Users/drew/Projects/demo_app2/.svelte-kit/runtime/server/index.js:1565:5)
    at async respond$1 (file:///Users/drew/Projects/demo_app2/.svelte-kit/runtime/server/index.js:2194:15)
    at async render_page (file:///Users/drew/Projects/demo_app2/.svelte-kit/runtime/server/index.js:2395:19)
    at async resolve (file:///Users/drew/Projects/demo_app2/.svelte-kit/runtime/server/index.js:2660:11)
    at async Object.handle (/Users/drew/Projects/demo_app2/src/hooks.ts:9:24)
    at async respond (file:///Users/drew/Projects/demo_app2/.svelte-kit/runtime/server/index.js:2567:20)
    at async file:///Users/drew/Projects/demo_app2/node_modules/@sveltejs/kit/dist/chunks/index.js:244:24
```

### System Info

```shell
System:
    OS: macOS 12.1
    CPU: (4) x64 Intel(R) Core(TM) i5-6360U CPU @ 2.00GHz
    Memory: 157.93 MB / 8.00 GB
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 16.14.0 - /usr/local/bin/node
    Yarn: 1.10.1 - /usr/local/bin/yarn
    npm: 8.3.1 - /usr/local/bin/npm
  Browsers:
    Chrome: 98.0.4758.80
    Firefox: 66.0.4
    Safari: 15.2
  npmPackages:
    @sveltejs/adapter-auto: next => 1.0.0-next.17
    @sveltejs/kit: next => 1.0.0-next.272
    svelte: ^3.46.0 => 3.46.4
```

### Severity

annoyance

**Comment by benmccann** [comment]
I believe this was fixed by https://github.com/sveltejs/kit/pull/3970
