### ISSUE TITLE
"Cannot read property 'rimraf' of undefined" when building using adapter-vercel

### ISSUE THREAD

**Issue by natevaughan** [sveltejs/kit#3999]
### Describe the bug

Hi, I'm upgrading SvelteKit to `^1.0.0-next.278` in order to take advantage of some newer features like `afterNavigate`.

The build and runtime work locally but I'm getting the following failure on Vercel:

```
> Using @sveltejs/adapter-vercel
> Cannot read property 'rimraf' of undefined
    at adapt (file:///vercel/path0/node_modules/@sveltejs/adapter-vercel/index.js:17:10)
    at adapt (file:///vercel/path0/node_modules/@sveltejs/kit/dist/chunks/index5.js:881:8)
    at file:///vercel/path0/node_modules/@sveltejs/kit/dist/cli.js:1062:11
```

I've cleared the build cache on Vercel.

### Reproduction

Run the following repo locally and deploy to Vercel. It should work locally but fail on Vercel.

https://github.com/natevaughan/launcher/tree/upgrade-sveltekit

### Logs

```shell
Cloning github.com/natevaughan/launcher (Branch: main, Commit: e42023e)
Cloning completed: 661.173ms
Analyzing source code...
Installing build runtime...
Build runtime installed: 2.984s
Looking up build cache...
Build Cache not found
Detected package.json
Installing dependencies...
Detected `package-lock.json` generated by npm 7...
> launcher@0.0.1 postinstall
> prisma generate || true
Prisma schema loaded from prisma/schema.prisma
✔ Generated Prisma Client (3.6.0 | library) to ./node_modules/@prisma/client in 229ms
You can now start using Prisma Client in your code. Reference: https://pris.ly/d/client

import { PrismaClient } from '@prisma/client'
const prisma = new PrismaClient()

added 424 packages in 18s
62 packages are looking for funding
  run `npm fund` for details
> launcher@0.0.1 build /vercel/path0
> svelte-kit build
vite v2.8.4 building for production...
transforming...
// ...
Run npm run preview to preview your production build locally.
> Using @sveltejs/adapter-vercel
> Cannot read property 'rimraf' of undefined
    at adapt (file:///vercel/path0/node_modules/@sveltejs/adapter-vercel/index.js:17:10)
    at adapt (file:///vercel/path0/node_modules/@sveltejs/kit/dist/chunks/index5.js:881:8)
    at file:///vercel/path0/node_modules/@sveltejs/kit/dist/cli.js:1062:11
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! launcher@0.0.1 build: `svelte-kit build`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the launcher@0.0.1 build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
npm ERR! A complete log of this run can be found in:
npm ERR!     /vercel/.npm/_logs/2022-02-18T21_24_46_615Z-debug.log
Error: Command "npm run build" exited with 1
```

### System Info

```shell
Vercel
```

### Severity

blocking an upgrade

**Comment by Conduitry** [comment]
What version of the Vercel adapter are you on? Is it the latest one?

**Comment by natevaughan** [comment]
I tried both `^1.0.0-next` and `next`

**Comment by benmccann** [comment]
That doesn't answer the question. You didn't provide the requested info:
```
npx envinfo --system --binaries --browsers --npmPackages "{svelte,@sveltejs/*,vite}"
```

You're almost certainly not on the latest one, but it's impossible to tell from the information provided. It's the `package-lock.json` that controls what version is used

**Comment by natevaughan** [comment]
```
  System:
    OS: macOS 12.0
    CPU: (10) x64 Apple M1 Max
    Memory: 7.36 GB / 64.00 GB
    Shell: 3.2.57 - /bin/bash
  Binaries:
    Node: 16.10.0 - /usr/local/bin/node
    Yarn: 1.22.10 - /usr/local/bin/yarn
    npm: 7.24.0 - /usr/local/bin/npm
    Watchman: 2021.09.13.00 - /usr/local/bin/watchman
  Browsers:
    Firefox: 97.0.1
    Safari: 15.0
  npmPackages:
    @sveltejs/adapter-vercel: ^1.0.0-next.0 => 1.0.0-next.31 
    @sveltejs/kit: ^1.0.0-next.278 => 1.0.0-next.278 
    svelte: ^3.34.0 => 3.46.4 

```

**Comment by natevaughan** [comment]
Honest question from a guy doing his best: where would I find info on compatible versions of adapters and sveltekit, or even just which version of each is the latest?

**Comment by natevaughan** [comment]
Nudge to the team to release versions with nominally matching numbers instead of separate sequences

**Comment by benmccann** [comment]
That's not going to happen until 1.0
