### ISSUE TITLE
Calling Endpoint from script fails with TypeError [ERR_INVALID_URL]: Invalid URL

### ISSUE THREAD

**Issue by faulander** [sveltejs/kit#4023]
### Describe the bug

I have this script section:

```
<script>
    import Search from "$lib/search.svelte";
    import ViewOptions from "$lib/views.svelte";
    import { onMount } from "svelte";

    let page;
    let showData = {
        shows: {},
        loading: true,
    };

    export async function getData(page) {
        const url = `/shows?page=${page}`;
        console.log(url);
        const res = await fetch(url);
        const shows = await res.json();
        showData = {
            shows: shows,
            loading: false,
        };
    }

    onMount(async () => {
        getData(page);
    });


    $: page, getData(page);
</script>
```
and the onMount works just fine. if i try to make it reactive, meaning to call the function whenever the page variable changes, i get this error in the console:
```

node:internal/errors:464
    ErrorCaptureStackTrace(err);
    ^

TypeError [ERR_INVALID_URL]: Invalid URL
    at new NodeError (node:internal/errors:371:5)
    at onParseError (node:internal/url:552:9)
    at new URL (node:internal/url:628:5)
    at new Request (file:///.../node_modules/@sveltejs/kit/dist/install-fetch.js:5907:16)
    at file:///.../node_modules/@sveltejs/kit/dist/install-fetch.js:6189:19
    at new Promise (<anonymous>)
    at fetch (file:///.../node_modules/@sveltejs/kit/dist/install-fetch.js:6187:9)
    at getData (/src/routes/index.svelte:23:21)
    at eval (/src/routes/index.svelte:37:10)
    at Object.$$render (/.../node_modules/svelte/internal/index.js:1745:22) {
  input: '/shows?page=undefined',
  code: 'ERR_INVALID_URL'
}
```
I don't understand that the function call works perfectly in the onMount section, but doesn't when called directly. It looks like it cannot find the endpoint. I would understand if i call it from the server (module-section) but clearly, i do not!

P.S.: I also tried with $: getData(page)
P.P.S.: Also postet this to SO with no answer: https://stackoverflow.com/questions/71190696/calling-endpoint-from-script-fails-with-typeerror-err-invalid-url-invalid-url

### Reproduction

Sorry, but i don't know how where i should reproduce an endpoint issue.

### Logs

```shell
node:internal/errors:464
    ErrorCaptureStackTrace(err);
    ^

TypeError [ERR_INVALID_URL]: Invalid URL
    at new NodeError (node:internal/errors:371:5)
    at onParseError (node:internal/url:552:9)
    at new URL (node:internal/url:628:5)
    at new Request (file:///.../node_modules/@sveltejs/kit/dist/install-fetch.js:5907:16)
    at file:///.../node_modules/@sveltejs/kit/dist/install-fetch.js:6189:19
    at new Promise (<anonymous>)
    at fetch (file:///.../node_modules/@sveltejs/kit/dist/install-fetch.js:6187:9)
    at getData (/src/routes/index.svelte:23:21)
    at eval (/src/routes/index.svelte:37:10)
    at Object.$$render (/.../node_modules/svelte/internal/index.js:1745:22) {
  input: '/shows?page=undefined',
  code: 'ERR_INVALID_URL'
```

### System Info

```shell
System:
    OS: macOS 12.1
    CPU: (8) x64 Apple M1
    Memory: 28.01 MB / 16.00 GB
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 16.13.0 - /usr/local/bin/node
    Yarn: 1.22.10 - /usr/local/bin/yarn
    npm: 8.1.0 - /usr/local/bin/npm
  Browsers:
    Chrome: 98.0.4758.102
    Firefox: 97.0.1
    Safari: 15.2
  npmPackages:
    @sveltejs/adapter-auto: next => 1.0.0-next.17 
    @sveltejs/kit: next => 1.0.0-next.260 
    svelte: ^3.44.0 => 3.46.4
```

### Severity

blocking all usage of SvelteKit

**Comment by Conduitry** [comment]
You do call it on the server. Reactive statements like `$: page, getData(page);` are run once during SSR, which results in calling the globally defined `fetch` on a relative URL, which is invalid. You should check whether you're on the server in the reactive statement before calling the function that calls `fetch`.

Also keep in mind that any asynchronous code that's run while rendering the component on the server is wasted cycles, because after a component has its props (after its `load` is run), rendering to HTML is a synchronous operation, and any asynchronous state changes are ignored.
