### ISSUE TITLE
error: Unterminated string literal

### ISSUE THREAD

**Issue by PortStone** [sveltejs/kit#4061]
### Describe the bug

Using script shortcut `//` results to `error: Unterminated string literal` on building.

### Reproduction

```
<svelte:head>
  <script src="//cdn.jsdelivr.net/npm/sweetalert2@11"></script>
</svelte:head>
```

### Logs

```shell
Note: This logs are from Bitbucket Pipeline.
Use of eval is strongly discouraged, as it poses security risks and may cause issues with minification
✓ 308 modules transformed.
rendering chunks...
.svelte-kit/output/client/_app/assets/fira-mono-greek-400-normal-a8be01ce.woff2          10.27 KiB
.svelte-kit/output/client/_app/assets/fira-mono-cyrillic-400-normal-c7d433fd.woff2       8.89 KiB
.svelte-kit/output/client/_app/assets/fira-mono-cyrillic-ext-400-normal-3df7909e.woff2   15.40 KiB
.svelte-kit/output/client/_app/assets/fira-mono-greek-ext-400-normal-9e2fe623.woff2      7.33 KiB
.svelte-kit/output/client/_app/assets/fira-mono-latin-ext-400-normal-6bfabd30.woff2      11.10 KiB
.svelte-kit/output/client/_app/assets/fira-mono-latin-400-normal-e43b3538.woff2          15.90 KiB
.svelte-kit/output/client/_app/assets/fira-mono-all-400-normal-1e3b098c.woff             75.55 KiB
.svelte-kit/output/client/_app/manifest.json                                             3.19 KiB
.svelte-kit/output/client/_app/pages/__layout.svelte-1baa6360.js                         14.31 KiB / gzip: 2.68 KiB
.svelte-kit/output/client/_app/error.svelte-09e52a8b.js                                  1.56 KiB / gzip: 0.74 KiB
.svelte-kit/output/client/_app/pages/about.svelte-59b5bc4b.js                            2.40 KiB / gzip: 1.09 KiB
.svelte-kit/output/client/_app/pages/login.svelte-edbafdea.js                            3.59 KiB / gzip: 1.54 KiB
.svelte-kit/output/client/_app/pages/todos/index.svelte-f064fc3a.js                      5.71 KiB / gzip: 2.36 KiB
.svelte-kit/output/client/_app/pages/index.svelte-77681705.js                            25.56 KiB / gzip: 7.80 KiB
.svelte-kit/output/client/_app/chunks/utils-3fa419fe.js                                  0.24 KiB / gzip: 0.20 KiB
.svelte-kit/output/client/_app/chunks/singletons-a6a7384f.js                             0.05 KiB / gzip: 0.07 KiB
.svelte-kit/output/client/_app/assets/pages/about.svelte-206e1d16.css                    0.11 KiB / gzip: 0.10 KiB
.svelte-kit/output/client/_app/assets/pages/login.svelte-9a85d203.css                    0.17 KiB / gzip: 0.14 KiB
.svelte-kit/output/client/_app/assets/pages/todos/index.svelte-cdb023bf.css              3.76 KiB / gzip: 1.04 KiB
.svelte-kit/output/client/_app/assets/pages/index.svelte-e75f4e32.css                    10.54 KiB / gzip: 2.85 KiB
.svelte-kit/output/client/_app/pages/app.svelte-8cfb00e3.js                              37.47 KiB / gzip: 8.76 KiB
.svelte-kit/output/client/_app/assets/vendor-95172eab.css                                0.20 KiB / gzip: 0.16 KiB
.svelte-kit/output/client/_app/start-fe78e137.js                                         23.87 KiB / gzip: 8.02 KiB
.svelte-kit/output/client/_app/assets/pages/app.svelte-e2ad3c08.css                      237.90 KiB / gzip: 26.34 KiB
.svelte-kit/output/client/_app/chunks/vendor-e53ed10c.js                                 486.97 KiB / gzip: 101.49 KiB
vite v2.7.13 building SSR bundle for production...
 > html:/opt/atlassian/pipelines/agent/build/src/routes/index.svelte:13:14: error: Unterminated string literal
    13 │ import "https:
       ╵               ^
> Build failed with 1 error:
html:/opt/atlassian/pipelines/agent/build/src/routes/index.svelte:13:14: error: Unterminated string literal
html:/opt/atlassian/pipelines/agent/build/src/routes/index.svelte:13:14: error: Unterminated string literal
    at failureErrorWithLog (/opt/atlassian/pipelines/agent/build/node_modules/esbuild/lib/main.js:1493:15)
    at /opt/atlassian/pipelines/agent/build/node_modules/esbuild/lib/main.js:1151:28
    at runOnEndCallbacks (/opt/atlassian/pipelines/agent/build/node_modules/esbuild/lib/main.js:941:63)
    at buildResponseToResult (/opt/atlassian/pipelines/agent/build/node_modules/esbuild/lib/main.js:1149:7)
    at /opt/atlassian/pipelines/agent/build/node_modules/esbuild/lib/main.js:1258:14
    at /opt/atlassian/pipelines/agent/build/node_modules/esbuild/lib/main.js:629:9
    at handleIncomingPacket (/opt/atlassian/pipelines/agent/build/node_modules/esbuild/lib/main.js:726:9)
    at Socket.readFromStdout (/opt/atlassian/pipelines/agent/build/node_modules/esbuild/lib/main.js:596:7)
    at Socket.emit (node:events:526:28)
    at addChunk (node:internal/streams/readable:324:12)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

### System Info

```shell
 System:
    OS: Linux 5.15 Gentoo/Linux
    CPU: (8) x64 Intel(R) Core(TM) i7-4770K CPU @ 3.50GHz
    Memory: 13.39 GB / 15.57 GB
    Container: Yes
    Shell: 5.1.16 - /bin/bash
  Binaries:
    Node: 17.5.0 - ~/.nvm/versions/node/v17.5.0/bin/node
    Yarn: 1.22.17 - /usr/bin/yarn
    npm: 8.4.1 - ~/.nvm/versions/node/v17.5.0/bin/npm
  Browsers:
    Chromium: 98.0.4758.102
    Firefox: 91.6.0esr
  npmPackages:
    @sveltejs/adapter-auto: next => 1.0.0-next.17
    @sveltejs/adapter-node: ^1.0.0-next.68 => 1.0.0-next.68
    @sveltejs/kit: next => 1.0.0-next.260
    svelte: ^3.46.0 => 3.46.4
```

### Severity

serious, but I can work around it

### Additional Information
```
The path of error (index.svelte:13:14) is completly missleading. The actual syntax error was like 20 lines below.
```

**Comment by bluwy** [comment]
The error seems to be coming from Vite's scanner when it assumes to `<script>` to be actual code to be scanned. Not sure the scanner is failing at that though, it should bail for https request.

**Comment by Rich-Harris** [comment]
Why is Vite scanning at all?

**Comment by bluwy** [comment]
In this case, according to the logs, the scanning is not for pre-bundling, but for automatic SSR externalization. It's so that it doesn't rely on `dependencies`/`devDependencies` semantics when bundling. However it has a loose parser for HTML-ish files, which failed for this edge case

**Comment by Rich-Harris** [comment]
Huh — I thought scanning was disabled by virtue of us setting `rollupOptions.input`. I must have misunderstood

**Comment by bluwy** [comment]
Thanks for the update @mcmxcdev. I believe the issue was caused because Vite strips `// bla` that looks like a single-line comment (during it's build process), hence the error. There were efforts that made it more robust. So it's not a scanner issue after all. Closing this as fixed.
