### ISSUE TITLE
`adapter-auto` fails to deploy the app to Cloudflare Pages

### ISSUE THREAD

**Issue by illright** [sveltejs/kit#4107]
### Describe the bug

At some point without changes to the CD pipeline, our deployments started failing. Upon investigation, I've discovered that both `adapter-auto` and `adapter-static` cause errors in the Cloudflare Pages build, however, `adapter-cloudflare` works just fine.

### Reproduction

https://github.com/aabounegm/cast/tree/040946094b806215576355d41f4edb075800e3ca

This is a project I'm working on, configured to auto-deploy to Cloudflare Pages. Below is a branch that introduces `adapter-cloudflare`, when the deployment finally started working again.

https://github.com/aabounegm/cast/tree/36c81e1a6477e582c97442565ad1464f89de0a9f

### Logs

```shell
Logs from _Building application_ of the Cloudflare Pages logs section, adapter-auto:

02:31:55.744	> Using @sveltejs/adapter-auto
02:31:56.025	 > .svelte-kit/cloudflare-tmp/_worker.js:1:20: error: Could not resolve "../output/server/app.js"
02:31:56.025	    1 │ import { App } from '../output/server/app.js';
02:31:56.025	      ╵                     ~~~~~~~~~~~~~~~~~~~~~~~~~
02:31:56.025	
02:31:56.032	> Build failed with 1 error:
02:31:56.032	.svelte-kit/cloudflare-tmp/_worker.js:1:20: error: Could not resolve "../output/server/app.js"
02:31:56.032	.svelte-kit/cloudflare-tmp/_worker.js:1:20: error: Could not resolve "../output/server/app.js"
02:31:56.032	    at failureErrorWithLog (/opt/buildhome/repo/node_modules/.pnpm/esbuild@0.13.15/node_modules/esbuild/lib/main.js:1493:15)
02:31:56.032	    at /opt/buildhome/repo/node_modules/.pnpm/esbuild@0.13.15/node_modules/esbuild/lib/main.js:1151:28
02:31:56.032	    at runOnEndCallbacks (/opt/buildhome/repo/node_modules/.pnpm/esbuild@0.13.15/node_modules/esbuild/lib/main.js:1069:65)
02:31:56.032	    at buildResponseToResult (/opt/buildhome/repo/node_modules/.pnpm/esbuild@0.13.15/node_modules/esbuild/lib/main.js:1149:7)
02:31:56.032	    at /opt/buildhome/repo/node_modules/.pnpm/esbuild@0.13.15/node_modules/esbuild/lib/main.js:1258:14
02:31:56.032	    at /opt/buildhome/repo/node_modules/.pnpm/esbuild@0.13.15/node_modules/esbuild/lib/main.js:629:9
02:31:56.032	    at handleIncomingPacket (/opt/buildhome/repo/node_modules/.pnpm/esbuild@0.13.15/node_modules/esbuild/lib/main.js:726:9)
02:31:56.032	    at Socket.readFromStdout (/opt/buildhome/repo/node_modules/.pnpm/esbuild@0.13.15/node_modules/esbuild/lib/main.js:596:7)
02:31:56.033	    at Socket.emit (node:events:520:28)
02:31:56.033	    at addChunk (node:internal/streams/readable:315:12)
02:31:56.050	 ELIFECYCLE  Command failed with exit code 1.
02:31:56.081	Failed: build command exited with code: 1


Logs from _Building application_ of the Cloudflare Pages logs section, adapter-static:

14:30:42.694	> Using @sveltejs/adapter-static
14:30:42.735	  Wrote site to "build"
14:30:42.735	  ✔ done
14:30:42.777	Finished
14:30:42.777	Note: No functions dir at /functions found. Skipping.
14:30:42.777	Validating asset output directory
14:30:42.777	Error: Output directory ".svelte-kit/cloudflare" not found.
```

### System Info

```shell
System:
    OS: Linux 5.10 Arch Linux
    CPU: (8) x64 Intel(R) Core(TM) i5-8265U CPU @ 1.60GHz
    Memory: 1.91 GB / 3.76 GB
    Container: Yes
    Shell: 3.3.1 - /bin/fish
  Binaries:
    Node: 17.5.0 - /usr/sbin/node
    Yarn: 1.22.17 - /usr/sbin/yarn
    npm: 8.5.1 - /usr/sbin/npm
  npmPackages:
    @sveltejs/adapter-auto: next => 1.0.0-next.17 
    @sveltejs/kit: next => 1.0.0-next.282 
    svelte: ^3.46.4 => 3.46.4
```

### Severity

annoyance

**Comment by geoffrich** [comment]
This error is because your SvelteKit version is not compatible with your adapter-auto version. There was a breaking change in [SvelteKit next.280](https://github.com/sveltejs/kit/blob/master/packages/kit/CHANGELOG.md#100-next280) that requires at least [adapter-auto next.24](https://github.com/sveltejs/kit/blob/master/packages/adapter-auto/CHANGELOG.md#100-next24).  Try running `npm i @sveltejs/adapter-auto@next` to install the most recent version.
