### ISSUE TITLE
Cannot call goto(...) on the server

### ISSUE THREAD

**Issue by robots4life** [sveltejs/kit#4307]
### Describe the bug

For latest installations with TS and JS `goto()` results in `Cannot call goto(...) on the server`.

### Reproduction

https://github.com/robots4life/gotots

```html
<script>
    import {goto} from '$app/navigation'

    goto('/profile')
</script>
<h1>Welcome to SvelteKit</h1>
<p>Visit <a href="https://kit.svelte.dev">kit.svelte.dev</a> to read the documentation</p>
```

https://github.com/robots4life/gotojs

```html
<script>
    import {goto} from '$app/navigation'

    goto('/profile')
</script>
<h1>Welcome to SvelteKit</h1>
<p>Visit <a href="https://kit.svelte.dev">kit.svelte.dev</a> to read the documentation</p>
```

### Logs

https://github.com/robots4life/gotots

`npm run dev`

```shell
Cannot call goto(...) on the server
Error: Cannot call goto(...) on the server
    at Module.eval (/.svelte-kit/runtime/app/navigation.js:8:9)
    at index.svelte:4:8
    at Object.$$render (/shared/httpd/gotots/node_modules/svelte/internal/index.js:1745:22)
    at Object.default (root.svelte:43:47)
    at eval (/.svelte-kit/runtime/components/layout.svelte:8:41)
    at Object.$$render (/shared/httpd/gotots/node_modules/svelte/internal/index.js:1745:22)
    at root.svelte:37:45
    at $$render (/shared/httpd/gotots/node_modules/svelte/internal/index.js:1745:22)
    at Object.render (/shared/httpd/gotots/node_modules/svelte/internal/index.js:1753:26)
    at render_response (file:///shared/httpd/gotots/.svelte-kit/runtime/server/index.js:1198:28)
```

https://github.com/robots4life/gotojs

`npm run dev`

```shell
Cannot call goto(...) on the server
Error: Cannot call goto(...) on the server
    at Module.eval (/.svelte-kit/runtime/app/navigation.js:8:9)
    at index.svelte:4:8
    at Object.$$render (/shared/httpd/gotojs/node_modules/svelte/internal/index.js:1745:22)
    at Object.default (root.svelte:43:47)
    at eval (/.svelte-kit/runtime/components/layout.svelte:8:41)
    at Object.$$render (/shared/httpd/gotojs/node_modules/svelte/internal/index.js:1745:22)
    at root.svelte:37:45
    at $$render (/shared/httpd/gotojs/node_modules/svelte/internal/index.js:1745:22)
    at Object.render (/shared/httpd/gotojs/node_modules/svelte/internal/index.js:1753:26)
    at render_response (file:///shared/httpd/gotojs/.svelte-kit/runtime/server/index.js:1198:28)
```

### System Info

Linux

```shell
  System:
    OS: Linux 5.4 Debian GNU/Linux 11 (bullseye) 11 (bullseye)
    CPU: (8) x64 Intel(R) Core(TM) i7-8550U CPU @ 1.80GHz
    Memory: 8.26 GB / 15.53 GB
    Container: Yes
    Shell: 5.1.4 - /bin/bash
  Binaries:
    Node: 17.4.0 - /opt/nvm/versions/node/v17.4.0/bin/node
    Yarn: 1.22.17 - /usr/bin/yarn
    npm: 8.3.1 - /opt/nvm/versions/node/v17.4.0/bin/npm
  npmPackages:
    @sveltejs/adapter-auto: next => 1.0.0-next.31 
    @sveltejs/kit: next => 1.0.0-next.295 
    svelte: ^3.44.0 => 3.46.4
```

Windows

```shell
System:
    OS: Windows 10 10.0.19043
    CPU: (8) x64 11th Gen Intel(R) Core(TM) i7-1165G7 @ 2.80GHz
    Memory: 8.69 GB / 15.80 GB
  Binaries:
    Node: 16.14.0 - C:\Program Files\nodejs\node.EXE
    npm: 8.3.1 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Edge: Spartan (44.19041.1266.0), Chromium (99.0.1150.30)
    Internet Explorer: 11.0.19041.1202
  npmPackages:
    @sveltejs/adapter-auto: next => 1.0.0-next.31
    @sveltejs/kit: next => 1.0.0-next.295
    svelte: ^3.44.0 => 3.46.4
```

### Severity

blocking all usage of SvelteKit

**Comment by mishrasatyam** [comment]
`goto` runs on browser. 
Use 
```js
import {browser} from '$app/env'
    if(browser){
        goto('/profile')
    }
```

**Comment by Conduitry** [comment]
You're getting this error because you indeed can't call `goto` on the server. What you should do instead depends on what you're trying to achieve. Please use Discord or GitHub discussions for support questions.

**Comment by wvanrensburg** [comment]
@robots4life Im with you.. I also get the error, and for what its worth for everyone saying you cant call it on the server, it isnt being called on the server. Its on a +page.svelte file (non server file). That should just work without a browser hack

**Comment by Zielak** [comment]
@wvanrensburg From what I understand, components are run on server when you have SSR enabled. Everything outside `onMount()` is evaluated server-side before sending it to the client.

In my case I'm doing redirection based on client-side store value, which wouldn't have any value assigned during server-side-rendering. Moving this chech and goto() inside `onMount()` helped.
