### ISSUE TITLE
Installing dependencies with only package.json (and lockfile) present fails

### ISSUE THREAD

**Issue by Conduitry** [sveltejs/kit#4366]
### Describe the bug

As noted [here](https://github.com/sveltejs/kit/issues/4165#issuecomment-1069803794), when dependencies are installed when only `package.json` (and a lockfile) are present results in a failure during `@sveltejs/kit`'s `prepare` script, which runs `svelte-kit sync`, which expects a full app to be present. Installing in this way is common when using multi-stage Docker builds, to optimize layer caching.

### Reproduction

1. Create a new project
2. Delete everything except `package.json`
3. Install dependencies

### Logs

```shell
> You need to create a svelte.config.js file. See https://kit.svelte.dev/docs/configuration
    at load_config (file:///.../node_modules/.pnpm/@sveltejs+kit@1.0.0-next.299_svelte@3.46.4/node_modules/@sveltejs/kit/dist/cli.js:780:9)
    at file:///.../node_modules/.pnpm/@sveltejs+kit@1.0.0-next.299_svelte@3.46.4/node_modules/@sveltejs/kit/dist/cli.js:1000:25
    at o.parse (/.../node_modules/.pnpm/sade@1.8.1/node_modules/sade/lib/index.js:1:3402)
    at file:///.../node_modules/.pnpm/@sveltejs+kit@1.0.0-next.299_svelte@3.46.4/node_modules/@sveltejs/kit/dist/cli.js:1008:6
    at ModuleJob.run (node:internal/modules/esm/module_job:198:25)
    at async Promise.all (index 0)
    at async ESMLoader.import (node:internal/modules/esm/loader:385:24)
    at async loadESM (node:internal/process/esm_loader:88:5)
    at async handleMainPromise (node:internal/modules/run_main:61:12)
```

### System Info

```shell
System:
    OS: Linux 5.10 Ubuntu 20.04.4 LTS (Focal Fossa)
    CPU: (8) x64 Intel(R) Core(TM) i7-9700 CPU @ 3.00GHz
    Memory: 23.46 GB / 24.98 GB
    Container: Yes
    Shell: 5.0.17 - /bin/bash
  Binaries:
    Yarn: 1.22.15
    npm: 8.5.2
  npmPackages:
    @sveltejs/adapter-auto: next => 1.0.0-next.33
    @sveltejs/kit: next => 1.0.0-next.299
    svelte: ^3.46.0 => 3.46.4
```

### Severity

blocking an upgrade

### Additional Information

Making `svelte-kit sync` a no-op when there's no `svelte.config.js` might be a step in the right direction, but I'm not positive that would be enough.

Maybe, when using Docker, the next build stage would have to run `svelte-kit sync` before it runs `svelte-kit build`? I'm not sure whether `sync` does anything that `build` wouldn't.

**Comment by Conduitry** [comment]
It looks like making `sync` a no-op might in fact be enough. (Maybe it could print a warning, as long as it still has a 0 exit code.) Anything in `.svelte-kit` that `sync` would have generated is also generated by `build` (and by `dev` for that matter).
