### ISSUE TITLE
Add rel=external to link attribute to Skeleton

### ISSUE THREAD

**Issue by robots4life** [sveltejs/kit#4430]
### Describe the bug

Installing the default Skeleton with TS and clicking on the link to https://kit.svelte.dev does not work.

### Reproduction

Cannot follow link https://kit.svelte.dev from deployed and/or local Sveltekit installation. This is pretty much the default skeleton installation with TS.

https://daiki-six.vercel.app/

### Logs

```shell
https://daiki-six.vercel.app/

Firefox

Uncaught (in promise) DOMException: The operation is insecure. start-f3a65506.js:1
    ge https://daiki-six.vercel.app/_app/start-f3a65506.js:1
    AsyncFunctionThrow self-hosted:704
    (Async: async)
    _start_router https://daiki-six.vercel.app/_app/start-f3a65506.js:1

Chrome
```js
start-f3a65506.js:1 Uncaught (in promise) DOMException: Failed to execute 'pushState' on 'History': A history state object with URL 'https://kit.svelte.dev/' cannot be created in a document with origin 'https://daiki-six.vercel.app' and URL 'https://daiki-six.vercel.app/'.
    at he (https://daiki-six.vercel.app/_app/start-f3a65506.js:1:13087)
    at async ge (https://daiki-six.vercel.app/_app/start-f3a65506.js:1:18752)
```

https://github.com/robots4life/daiki

Firefox `http://localhost:3000`
```js
Uncaught (in promise) DOMException: The operation is insecure. start.js:623
    navigate http://localhost:3000/@fs/shared/httpd/daiki/.svelte-kit/runtime/client/start.js:1256
    AsyncFunctionThrow self-hosted:704
    (Async: async)
    _start_router http://localhost:3000/@fs/shared/httpd/daiki/.svelte-kit/runtime/client/start.js:1460
```

Chrome `http://localhost:3000`
```js
start.js:623 Uncaught (in promise) DOMException: Failed to execute 'pushState' on 'History': A history state object with URL 'https://kit.svelte.dev/' cannot be created in a document with origin 'http://localhost:3000' and URL 'http://localhost:3000/'.
    at update (http://localhost:3000/@fs/shared/httpd/daiki/.svelte-kit/runtime/client/start.js:623:64)
    at async navigate (http://localhost:3000/@fs/shared/httpd/daiki/.svelte-kit/runtime/client/start.js:1241:3)
```
```


### System Info

```shell
System:
    OS: Linux 5.4 Debian GNU/Linux 11 (bullseye) 11 (bullseye)
    CPU: (8) x64 Intel(R) Core(TM) i7-8550U CPU @ 1.80GHz
    Memory: 6.10 GB / 15.53 GB
    Container: Yes
    Shell: 5.1.4 - /bin/bash
  Binaries:
    Node: 17.4.0 - /opt/nvm/versions/node/v17.4.0/bin/node
    Yarn: 1.22.17 - /usr/bin/yarn
    npm: 8.3.1 - /opt/nvm/versions/node/v17.4.0/bin/npm
  npmPackages:
    @sveltejs/adapter-auto: next => 1.0.0-next.33 
    @sveltejs/adapter-node: ^1.0.0-next.73 => 1.0.0-next.73 
    @sveltejs/kit: next => 1.0.0-next.302 
    svelte: ^3.44.0 => 3.46.4
```

### Severity

annoyance

**Comment by Conduitry** [comment]
There's a larger issue going on here. What's in the skeleton app (and in the default demo app) should be fine. The router should notice that the link is to a different origin and not try to handle it with client-side SPA navigation - but that's not what's happening, and then the history API is (rightfully) complaining about us adding a history item with a different origin.

**Comment by Conduitry** [comment]
Aha! This case _was_ already supposed to be handled by the code at https://github.com/sveltejs/kit/blob/2865f41874bad7e373398e88a33a10b947f07210/packages/kit/src/runtime/client/client.js#L219 but this bug is specifically happening when we're linking to the same path on a different origin, because the branch at https://github.com/sveltejs/kit/blob/2865f41874bad7e373398e88a33a10b947f07210/packages/kit/src/runtime/client/client.js#L205 is erroneously kicking in. (I'll update the issue title.)

I think the proper fix is to just additionally check `url.origin === location.origin`.

**Comment by patricknelson** [comment]
Tinkering with this on the weekends, I had only _just_ picked up SvelteKit (and Svelte) for the very first time only 2 weeks ago (_right after_ this broke). Naturally ,the _very first_ thing I try is linking to www.google.com and I was getting errors, so of course I assumed I was doing something wrong! 😄 Stumbled upon this (since I hadn't updated yet) since I was about to report a bug!

Thanks @robots4life  for finding this and thanks to @Conduitry for putting in the effort to get this to 1.0!
