### ISSUE TITLE
Issue with server-side fetch since version 1.0.0-next.253

### ISSUE THREAD

**Issue by bothness** [sveltejs/kit#4431]
### Describe the bug

I've been having issues with server-side fetch from version **1.0.0-next.253** onwards. It seems that the headers get re-written by Svelte Kit in a way that can corrupt certain requests.

[This is the specific change](https://github.com/sveltejs/kit/pull/3631) that seems to have caused the issue for me.

The same requests still seem to work fine on the client side.

### Reproduction

The options for my fetch requests look something like this. Unfortunately the GraphQL endpoint isn't a public one, so I can't share a "working" demo.

```
{
	body: REQUEST_STRING,
	headers: new Headers({
		"Content-Type": "application/json",
		"Authorization": "Basic " + CREDENTIALS
	}),
	method: "POST",
	mode: "cors"
}
```

Judging by the error log and my inspection of the response, it seems that the API is getting the request, but is returning an GUI console containing the query and result rather than a JSON response. This is causing the "unexpected token" error.

### Logs

```shell
Unexpected token < in JSON at position 2

SyntaxError: Unexpected token < in JSON at position 2
    at JSON.parse (<anonymous>)
    at Proxy.<anonymous> (APP_PATH/.svelte-kit/runtime/server/index.js:1835:21)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async Module.getData (/src/lib/utils.js:84:14)
    at async load (index.svelte:14:21)
    at async load_node (APP_PATH/.svelte-kit/runtime/server/index.js:1864:12)
    at async respond$1 (APP_PATH/.svelte-kit/runtime/server/index.js:2242:15)
    at async resolve (APP_PATH/.svelte-kit/runtime/server/index.js:2744:11)
    at async respond (APP_PATH/.svelte-kit/runtime/server/index.js:2688:20)
    at async APP_PATH/node_modules/@sveltejs/kit/dist/chunks/index.js:299:24
```

### System Info

```shell
System:
    OS: macOS 11.6.1
    CPU: (12) x64 Intel(R) Core(TM) i9-8950HK CPU @ 2.90GHz
    Memory: 1.14 GB / 32.00 GB
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 16.10.0 - ~/.nvm/versions/node/v16.10.0/bin/node
    npm: 7.18.1 - /usr/local/bin/npm
  Browsers:
    Chrome: 99.0.4844.83
    Firefox: 97.0.1
    Safari: 14.1.2
  npmPackages:
    @sveltejs/adapter-node: ^1.0.0-next.0 => 1.0.0-next.0 
    @sveltejs/adapter-static: ^1.0.0-next.17 => 1.0.0-next.26 
    @sveltejs/kit: ^1.0.0-next.252 => 1.0.0-next.302 
    svelte: ^3.34.0 => 3.46.4
```

### Severity

blocking an upgrade

**Comment by Conduitry** [comment]
Do you know what header is resulting in you getting HTML back from your API instead of your expected content? Is it `accept`? Can you override and manually pass a different value for that header to make this work in your app?

It might make sense for SvelteKit to also exclude that header when copying others over from the original request.

**Comment by bothness** [comment]
I'm not sure which header is causing that behaviour, and am not sure how to intercept/log the headers that are actually getting sent in a server-side request.

On the client side, besides **Host**, **Origin**, **Referred** and **authorisation**, these are the headers on a successful fetch request to the GraphQL API.

```
POST /graphql HTTP/1.
User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:97.0) Gecko/20100101 Firefox/97.0
Accept: */*
Accept-Language: en-GB,en;q=0.5
Accept-Encoding: gzip, deflate, br
content-type: application/json
Content-Length: 733
Connection: keep-alive
Sec-Fetch-Dest: empty
Sec-Fetch-Mode: cors
Sec-Fetch-Site: cross-site
DNT: 1
Sec-GPC: 1
```

**Comment by mrkishi** [comment]
The most likely culprit is `accept`, since now that we forward the navigation's headers it probably defaults to some `text/html,application/xml,...` variation. I also wouldn't be surprised if some API server tried to be helpful by interpreting `sec-fetch-dest: document` as an `accept: text/html` alternative.

However, do we really want to automagically forward headers? We can't guarantee it-just-works both client- and server-side as it's technically impossible to proxy all requests transparently, so maybe it'd help to make these differences intentionally apparent?

**Comment by itemodahl** [comment]
We probably have the same problem on our project. When requests go through the test domain "test.properDomain.com", it will not fetch data from our external api. While requesting the server ip directly, it will fetch data. 

This error started happening after we upgraded svelte kit from 229 -> 298. 

In the headers from requests through the test domain, X-FORWARDED-HOST contains two urls both the "test.properDomain.com" and the url to the api. `X-FORWARDED-HOST: "test.properDomain.com", "www.api-server.com"` .  And I suspect fetch from load is doing something magically there.

**Comment by bothness** [comment]
@mrkishi Thanks for the suggestion. It seems that explicitly setting both the Accept and Content-Type headers to "application/json" returns the right JSON response in the current version of Svelte Kit. So, my fetch request options now look something like this:

```
{
	body: REQUEST_STRING,
	headers: new Headers({
		"Accept": "application/json",
		"Content-Type": "application/json",
		"Authorization": "Basic " + CREDENTIALS
	}),
	method: "POST",
	mode: "cors"
}
```

This solves the immediate issue for me, but I'll leave it to others to decide if this still qualifies as a bug or if the discrepancies/pitfalls between server-side and client-side fetch just need to be documented somewhere.
