### ISSUE TITLE
Cannot use import statement outside a module

### ISSUE THREAD

**Issue by lovasoa** [sveltejs/kit#4504]
This is a followup on #2161. This issue had been fixed, but it was reintroduced in the latest sveltekit.

As asked, here is a reproduction: https://github.com/lovasoa/SvelteKit-2161

The stacktrace is

```
Cannot use import statement outside a module

/tmp/SvelteKit-2161/node_modules/@popperjs/core/dist/esm/popper.js:1
import { popperGenerator, detectOverflow } from "./createPopper.js";
^^^^^^

SyntaxError: Cannot use import statement outside a module
    at Object.compileFunction (node:vm:352:18)
    at wrapSafe (node:internal/modules/cjs/loader:1032:15)
    at Module._compile (node:internal/modules/cjs/loader:1067:27)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1155:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at ModuleWrap.<anonymous> (node:internal/modules/esm/translators:168:29)
    at ModuleJob.run (node:internal/modules/esm/module_job:195:25)
    at async Promise.all (index 0)
    at async ESMLoader.import (node:internal/modules/esm/loader:337:24)
```

> @lovasoa can you file a new issue with a reproduction? I don't have a way to reproduce and investigate at the moment

_Originally posted by @benmccann in https://github.com/sveltejs/kit/issues/2161#issuecomment-1085851247_

**Comment by king612** [comment]
+1. Breaking my build too.  Very annoying and may have to rip out Sveltestrap, which depends on it, which would make me have to look for a different framework.  This has to get fixed somehow.

**Comment by benmccann** [comment]
I'm not sure why this changed, but the sveltestrap package has been broken for a long time and it'd be nice to get https://github.com/bestguy/sveltestrap/pull/356 merged to fix it

**Comment by lovasoa** [comment]
The PR above you mention seems to break sveltestrap with sapper. Until the recent changes in sveltekit, the package worked in both sveltekit and sapper. It really sounds like something should be changed on sveltekit's side...

**Comment by Rich-Harris** [comment]
This is a bug in `@popperjs/core` — Node is behaving as it should. Popper should either

* use an `.mjs` extension for all the modules in `dist/esm/**/*.js`, or
* create a `dist/esm/package.json` with `{"type":"module"}`, or
* (ideally) put `{"type":"module"}` in the root `package.json`

It should also declare its exports using the `"exports"` field in package.json.

As far as I can tell, the package has been superseded by [floating-ui](https://github.com/floating-ui/floating-ui), which appears to do things differently, so maybe this is fixed already.

Either way, it can be worked around by populating Vite's `ssr.noExternal` config:

```js
/** @type {import('@sveltejs/kit').Config} */
const config = {
  kit: {
    vite: {
      ssr: {
        noExternal: ['@popperjs/core']
      }
    }
  }
};

export default config;
```

**Comment by kjeske** [comment]
It seems like the same happens with dayjs. `noExternal: ['@popperjs/core', 'dayjs']` helps.

**Comment by benmccann** [comment]
You can try dayjs 2.0 alpha as well since it will support ESM

**Comment by benallfree** [comment]
@Rich-Harris Your above solution is no longer working with the latest sveltekit. Any ideas?

Adding `"type": "module"` to `node_modules/@popperjs/core/package.json` does work though as mentioned in https://github.com/bestguy/sveltestrap/issues/463#issuecomment-1073273816

**Comment by nstuyvesant** [comment]
I am also running into this with @sveltejs/kit@1.0.0-next.490 and @carbon/charts...
```bash
Cannot use import statement outside a module
/Users/nates/dev/shy-svelte/node_modules/@carbon/charts/interfaces/enums.js:1
import * as EventEnums from './events';
^^^^^^
```

vite.config.js...
```javascript
/** @type {import('vite').UserConfig} */
const config = {
	build: {
		sourcemap: true
	},
	optimizeDeps: {
		include: ['@carbon/charts'],
		exclude: ['@carbon/telemetry']
	},
	plugins: [sveltekit()],
	server: {
		port: 3000,
		fs: {
			allow: ['..', '/api/file/']
		}
	},
	serviceWorker: {
		files: (filepath) => !/\.DS_Store/.test(filepath)
	},
	ssr: {
		noExternal: ['@carbon/charts', '@popperjs/core']
	}
}

export default config
```

**Comment by metonym** [comment]
@nstuyvesant Could you try removing `@carbon/charts` from `optimizeDeps.include`?

See a minimal [SvelteKit example set-up](https://github.com/metonym/carbon-charts-svelte-examples/tree/master/sveltekit-typescript).

**Comment by nstuyvesant** [comment]
I modified my vite.config.js it to...
```javascript
/** @type {import('vite').UserConfig} */
const config = {
	build: {
		sourcemap: true
	},
	optimizeDeps: {
		// include: ['@carbon/charts'],
		exclude: ['@carbon/telemetry']
	},
	plugins: [sveltekit()],
	server: {
		port: 3000,
		fs: {
			allow: ['..', '/api/file/']
		}
	},
	serviceWorker: {
		files: (filepath) => !/\.DS_Store/.test(filepath)
	},
	ssr: {
		// noExternal: [production && '@carbon/charts'].filter(Boolean)
		noExternal: ['@carbon/charts', 'carbon-components', '@popperjs/core'] // doesn't help at all
	}
}

export default config
```

After that, I got a series of warnings related to failing to load source map for various parts of @carbon/charts then errors  like...
```
Not found: /node_modules/@carbon/src/interfaces/enums.js.map
Error: Not found: /node_modules/@carbon/src/interfaces/enums.js.map
    at resolve (file:///Users/nates/dev/shy-svelte/node_modules/@sveltejs/kit/src/runtime/server/index.js:267:13)
    at Object.handle (/Users/nates/dev/shy-svelte/src/hooks.server.ts:23:24)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async respond (file:///Users/nates/dev/shy-svelte/node_modules/@sveltejs/kit/src/runtime/server/index.js:295:20)
    at async file:///Users/nates/dev/shy-svelte/node_modules/@sveltejs/kit/src/exports/vite/dev/index.js:406:22
Not found: /node_modules/@carbon/src/interfaces/events.js.map
Error: Not found: /node_modules/@carbon/src/interfaces/events.js.map
    at resolve (file:///Users/nates/dev/shy-svelte/node_modules/@sveltejs/kit/src/runtime/server/index.js:267:13)
    at Object.handle (/Users/nates/dev/shy-svelte/src/hooks.server.ts:23:24)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async respond (file:///Users/nates/dev/shy-svelte/node_modules/@sveltejs/kit/src/runtime/server/index.js:295:20)
    at async file:///Users/nates/dev/shy-svelte/node_modules/@sveltejs/kit/src/exports/vite/dev/index.js:406:22
Not found: /node_modules/@carbon/src/interfaces/index.js.map
Error: Not found: /node_modules/@carbon/src/interfaces/index.js.map
    at resolve (file:///Users/nates/dev/shy-svelte/node_modules/@sveltejs/kit/src/runtime/server/index.js:267:13)
    at Object.handle (/Users/nates/dev/shy-svelte/src/hooks.server.ts:23:24)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async respond (file:///Users/nates/dev/shy-svelte/node_modules/@sveltejs/kit/src/runtime/server/index.js:295:20)
    at async file:///Users/nates/dev/shy-svelte/node_modules/@sveltejs/kit/src/exports/vite/dev/index.js:406:22
Not found: /node_modules/@carbon/src/interfaces/a11y.js.map
Error: Not found: /node_modules/@carbon/src/interfaces/a11y.js.map
    at resolve (file:///Users/nates/dev/shy-svelte/node_modules/@sveltejs/kit/src/runtime/server/index.js:267:13)
    at Object.handle (/Users/nates/dev/shy-svelte/src/hooks.server.ts:23:24)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async respond (file:///Users/nates/dev/shy-svelte/node_modules/@sveltejs/kit/src/runtime/server/index.js:295:20)
    at async file:///Users/nates/dev/shy-svelte/node_modules/@sveltejs/kit/src/exports/vite/dev/index.js:406:22
Not found: /node_modules/@carbon/src/configuration-non-customizable.js.map
Error: Not found: /node_modules/@carbon/src/configuration-non-customizable.js.map
    at resolve (file:///Users/nates/dev/shy-svelte/node_modules/@sveltejs/kit/src/runtime/server/index.js:267:13)
    at Object.handle (/Users/nates/dev/shy-svelte/src/hooks.server.ts:23:24)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async respond (file:///Users/nates/dev/shy-svelte/node_modules/@sveltejs/kit/src/runtime/server/index.js:295:20)
    at async file:///Users/nates/dev/shy-svelte/node_modules/@sveltejs/kit/src/exports/vite/dev/index.js:406:22
Not found: /node_modules/@carbon/src/configuration.js.map
Error: Not found: /node_modules/@carbon/src/configuration.js.map
    at resolve (file:///Users/nates/dev/shy-svelte/node_modules/@sveltejs/kit/src/runtime/server/index.js:267:13)
    at Object.handle (/Users/nates/dev/shy-svelte/src/hooks.server.ts:23:24)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async respond (file:///Users/nates/dev/shy-svelte/node_modules/@sveltejs/kit/src/runtime/server/index.js:295:20)
    at async file:///Users/nates/dev/shy-svelte/node_modules/@sveltejs/kit/src/exports/vite/dev/index.js:406:22
Not found: /node_modules/@carbon/src/tools.js.map
Error: Not found: /node_modules/@carbon/src/tools.js.map
    at resolve (file:///Users/nates/dev/shy-svelte/node_modules/@sveltejs/kit/src/runtime/server/index.js:267:13)
    at Object.handle (/Users/nates/dev/shy-svelte/src/hooks.server.ts:23:24)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async respond (file:///Users/nates/dev/shy-svelte/node_modules/@sveltejs/kit/src/runtime/server/index.js:295:20)
    at async file:///Users/nates/dev/shy-svelte/node_modules/@sveltejs/kit/src/exports/vite/dev/index.js:406:22

```

**Comment by nstuyvesant** [comment]
I think my problem is that my component attempts to use Carbon Chart's enums...
```typescript
	import type { LineChartOptions, DonutChartOptions } from '@carbon/charts/interfaces'
	import { Alignments, ScaleTypes } from '@carbon/charts/interfaces/enums'
```

I'll try copying them into a file inside of my project.

**Comment by nstuyvesant** [comment]
Dropping the import of the two enums solved the problem but I had to redefine them locally.

**Comment by ivan-kleshnin** [comment]
> @Rich-Harris Your above solution is no longer working with the latest sveltekit, even when moving it to vite.config.js.

It works after cutting `kite >  vite` nesting. Fixed `@mobily/ts-belt` incompatibility for me:

**vite.config.ts**
```ts
export default defineConfig({
  ...
  ssr: {
    noExternal: ['@mobily/ts-belt'] // !!!
  }
})
```

**Comment by nstuyvesant** [comment]
> Dropping the import of the two enums solved the problem but I had to redefine them locally.

Since my earlier comment on this issue, I've made extensive changes to `@carbon/charts` and `@carbon/charts-svelte` that resolved my earlier issues.
