### ISSUE TITLE
import json not working in dependency

### ISSUE THREAD

**Issue by cormacmccarthy** [sveltejs/kit#4580]
### Describe the bug

If I npm install a dependency that uses `import something from 'something.json'` I get the following error when I try to build:

```
TypeError [ERR_UNKNOWN_FILE_EXTENSION]: Unknown file extension ".json" for /Users/cmcculloh/Prototypes/backups/for-bug/node_modules/working-json/baz.json
    at new NodeError (node:internal/errors:371:5)
    at Object.getFileProtocolModuleFormat [as file:] (node:internal/modules/esm/get_format:87:11)
    at defaultGetFormat (node:internal/modules/esm/get_format:102:38)
    at defaultLoad (node:internal/modules/esm/load:21:14)
    at ESMLoader.load (node:internal/modules/esm/loader:359:26)
    at ESMLoader.moduleProvider (node:internal/modules/esm/loader:280:58)
    at new ModuleJob (node:internal/modules/esm/module_job:66:26)
    at ESMLoader.#createModuleJob (node:internal/modules/esm/loader:297:17)
    at ESMLoader.getModuleJob (node:internal/modules/esm/loader:261:34)
    at async ModuleWrap.<anonymous> (node:internal/modules/esm/module_job:81:21)
```

### Reproduction

[Here](https://github.com/cmcculloh/for-bug) is an example sveltekit project that reproduces the issue that I made for this bug report.
[Here](https://github.com/cmcculloh/working-json) is the example module I am npm installing that I made for this bug report.

### Logs

```shell
TypeError [ERR_UNKNOWN_FILE_EXTENSION]: Unknown file extension ".json" for /Users/cmcculloh/Prototypes/backups/for-bug/node_modules/working-json/baz.json
    at new NodeError (node:internal/errors:371:5)
    at Object.getFileProtocolModuleFormat [as file:] (node:internal/modules/esm/get_format:87:11)
    at defaultGetFormat (node:internal/modules/esm/get_format:102:38)
    at defaultLoad (node:internal/modules/esm/load:21:14)
    at ESMLoader.load (node:internal/modules/esm/loader:359:26)
    at ESMLoader.moduleProvider (node:internal/modules/esm/loader:280:58)
    at new ModuleJob (node:internal/modules/esm/module_job:66:26)
    at ESMLoader.#createModuleJob (node:internal/modules/esm/loader:297:17)
    at ESMLoader.getModuleJob (node:internal/modules/esm/loader:261:34)
    at async ModuleWrap.<anonymous> (node:internal/modules/esm/module_job:81:21)
```

### System Info

```shell
System:
    OS: macOS 12.3
    CPU: (12) x64 Intel(R) Core(TM) i7-8850H CPU @ 2.60GHz
    Memory: 135.13 MB / 32.00 GB
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 16.14.0 - ~/.nvm/versions/node/v16.14.0/bin/node
    Yarn: 1.22.18 - /usr/local/bin/yarn
    npm: 8.3.1 - ~/.nvm/versions/node/v16.14.0/bin/npm
  Browsers:
    Brave Browser: 100.1.37.109
    Chrome: 100.0.4896.75
    Safari: 15.4
  npmPackages:
    @sveltejs/adapter-auto: next => 1.0.0-next.34 
    @sveltejs/kit: next => 1.0.0-next.310 
    svelte: ^3.44.0 => 3.47.0
```

### Severity

serious, but I can work around it

### Additional Information

My current workaround is to modify the dependency. I change the `.json` file to a `.js` file with `export default` at the beginning. This is sub-optimal, because in the actual project I am using this for the JSON file is 200,000+ lines of json that is generated by a process (so, I'll have to modify the process to instead generate a `.js` file with `export default` at the front, and I'm not 100% sure I can, because I'm not sure who owns the process).

**Comment by Conduitry** [comment]
Importing JSON in ESM is a syntax error unless you're using experimental type assertions - https://nodejs.org/api/esm.html#json-modules

If you have a dependency doing that, that's a bug in that dependency.

**Comment by cormacmccarthy** [comment]
@Conduitry Thanks. Adding that is causing a different error:

```
Prototypes/backups/for-bug % npm run build                                                                                                                                                     (master)for-bug

> for-bug@0.0.1 build
> svelte-kit build

vite v2.9.1 building for production...
✓ 14 modules transformed.
[commonjs] Unexpected token (1:29) in /Users/cmcculloh/Prototypes/backups/for-bug/node_modules/working-json/bar.js
file: /Users/cmcculloh/Prototypes/backups/for-bug/node_modules/working-json/bar.js:1:29
1: import baz from './baz.json' assert { type: 'json' };
                                ^
2: 
3: const Foo = {
/Users/cmcculloh/Prototypes/backups/for-bug/node_modules/rollup/dist/shared/rollup.js:19636
  var err = new SyntaxError(message);
            ^

SyntaxError: Unexpected token (1:29) in /Users/cmcculloh/Prototypes/backups/for-bug/node_modules/working-json/bar.js
    at Parser.pp$4.raise (/Users/cmcculloh/Prototypes/backups/for-bug/node_modules/rollup/dist/shared/rollup.js:19636:13)
    at Parser.pp$9.unexpected (/Users/cmcculloh/Prototypes/backups/for-bug/node_modules/rollup/dist/shared/rollup.js:16932:8)
    at Parser.pp$9.semicolon (/Users/cmcculloh/Prototypes/backups/for-bug/node_modules/rollup/dist/shared/rollup.js:16909:66)
    at Parser.pp$8.parseImport (/Users/cmcculloh/Prototypes/backups/for-bug/node_modules/rollup/dist/shared/rollup.js:17978:8)
    at Parser.pp$8.parseStatement (/Users/cmcculloh/Prototypes/backups/for-bug/node_modules/rollup/dist/shared/rollup.js:17108:49)
    at Parser.pp$8.parseTopLevel (/Users/cmcculloh/Prototypes/backups/for-bug/node_modules/rollup/dist/shared/rollup.js:16989:21)
    at Parser.parse (/Users/cmcculloh/Prototypes/backups/for-bug/node_modules/rollup/dist/shared/rollup.js:16762:15)
    at Function.parse (/Users/cmcculloh/Prototypes/backups/for-bug/node_modules/rollup/dist/shared/rollup.js:16812:35)
    at Graph.contextParse (/Users/cmcculloh/Prototypes/backups/for-bug/node_modules/rollup/dist/shared/rollup.js:22926:38)
    at tryParse (/Users/cmcculloh/Prototypes/backups/for-bug/node_modules/vite/dist/node/chunks/dep-611778e0.js:11062:12) {
  pos: 29,
  loc: {
    column: 29,
    file: '/Users/cmcculloh/Prototypes/backups/for-bug/node_modules/working-json/bar.js',
    line: 1
  },
  raisedAt: 35,
  frame: "1: import baz from './baz.json' assert { type: 'json' };\n" +
    '                                ^\n' +
    '2: \n' +
    '3: const Foo = {',
  id: '/Users/cmcculloh/Prototypes/backups/for-bug/node_modules/working-json/bar.js',
  hook: 'transform',
  code: 'PLUGIN_ERROR',
  plugin: 'commonjs',
  watchFiles: [
    '/Users/cmcculloh/Prototypes/backups/for-bug/.svelte-kit/runtime/client/start.js',
    '/Users/cmcculloh/Prototypes/backups/for-bug/.svelte-kit/runtime/components/layout.svelte',
    '/Users/cmcculloh/Prototypes/backups/for-bug/.svelte-kit/runtime/components/error.svelte',
    '/Users/cmcculloh/Prototypes/backups/for-bug/src/routes/index.svelte',
    '/Users/cmcculloh/Prototypes/backups/for-bug/node_modules/svelte/package.json',
    '/Users/cmcculloh/Prototypes/backups/for-bug/node_modules/svelte/store/package.json',
    '/Users/cmcculloh/Prototypes/backups/for-bug/node_modules/svelte/index.mjs',
    '/Users/cmcculloh/Prototypes/backups/for-bug/node_modules/svelte/store/index.mjs',
    '/Users/cmcculloh/Prototypes/backups/for-bug/.svelte-kit/runtime/paths.js',
    '/Users/cmcculloh/Prototypes/backups/for-bug/.svelte-kit/runtime/client/singletons.js',
    '/Users/cmcculloh/Prototypes/backups/for-bug/.svelte-kit/generated/root.svelte',
    '/Users/cmcculloh/Prototypes/backups/for-bug/.svelte-kit/generated/client-manifest.js',
    '/Users/cmcculloh/Prototypes/backups/for-bug/node_modules/svelte/internal/package.json',
    '/Users/cmcculloh/Prototypes/backups/for-bug/node_modules/svelte/internal/index.mjs',
    '/Users/cmcculloh/Prototypes/backups/for-bug/src/lib/foo.ts',
    '/Users/cmcculloh/Prototypes/backups/for-bug/node_modules/vite/package.json',
    '/Users/cmcculloh/Prototypes/backups/for-bug/.svelte-kit/generated/client-matchers.js',
    'vite/preload-helper',
    '/Users/cmcculloh/Prototypes/backups/for-bug/node_modules/working-json/package.json',
    '/Users/cmcculloh/Prototypes/backups/for-bug/node_modules/working-json/bar.js'
  ]
}

Node.js v17.9.0
```

Using `require` instead causes this error:
```

> for-bug@0.0.1 build
> svelte-kit build

vite v2.9.1 building for production...
✓ 15 modules transformed.
.svelte-kit/output/client/_app/manifest.json                    1.14 KiB
.svelte-kit/output/client/_app/layout.svelte-23d0f029.js        0.53 KiB / gzip: 0.35 KiB
.svelte-kit/output/client/_app/pages/index.svelte-2fa0edb9.js   0.60 KiB / gzip: 0.40 KiB
.svelte-kit/output/client/_app/error.svelte-bb9909e1.js         1.56 KiB / gzip: 0.74 KiB
.svelte-kit/output/client/_app/chunks/index-dd45c2ae.js         6.83 KiB / gzip: 2.79 KiB
.svelte-kit/output/client/_app/start-ebce25f7.js                22.59 KiB / gzip: 8.54 KiB
vite v2.9.1 building SSR bundle for production...
✓ 12 modules transformed.
Generated an empty chunk: "hooks"
.svelte-kit/output/server/manifest.json                        1.09 KiB
.svelte-kit/output/server/index.js                             65.52 KiB
.svelte-kit/output/server/entries/fallbacks/layout.svelte.js   0.24 KiB
.svelte-kit/output/server/entries/fallbacks/error.svelte.js    0.72 KiB
.svelte-kit/output/server/entries/pages/index.svelte.js        0.36 KiB
.svelte-kit/output/server/chunks/index-2dc61825.js             2.29 KiB
.svelte-kit/output/server/chunks/hooks-1c45ba0b.js             0.00 KiB
ReferenceError: require is not defined in ES module scope, you can use import instead
This file is being treated as an ES module because it has a '.js' file extension and '/Users/cmcculloh/Prototypes/backups/for-bug/package.json' contains "type": "module". To treat it as a CommonJS script, rename it to use the '.cjs' file extension.
    at file:///Users/cmcculloh/Prototypes/backups/for-bug/node_modules/working-json/bar.js:1:13
    at ModuleJob.run (node:internal/modules/esm/module_job:198:25)
    at async Promise.all (index 0)
    at async ESMLoader.import (node:internal/modules/esm/loader:409:24)
    at async Promise.all (index 1)
    at async respond$1 (file:///Users/cmcculloh/Prototypes/backups/for-bug/.svelte-kit/output/server/index.js:1480:13)
    at async resolve (file:///Users/cmcculloh/Prototypes/backups/for-bug/.svelte-kit/output/server/index.js:1859:105)
    at async respond (file:///Users/cmcculloh/Prototypes/backups/for-bug/.svelte-kit/output/server/index.js:1815:22)
    at async visit (file:///Users/cmcculloh/Prototypes/backups/for-bug/node_modules/@sveltejs/kit/dist/chunks/index2.js:1094:20)
> 500 /
    at file:///Users/cmcculloh/Prototypes/backups/for-bug/node_modules/@sveltejs/kit/dist/chunks/index2.js:980:11
    at save (file:///Users/cmcculloh/Prototypes/backups/for-bug/node_modules/@sveltejs/kit/dist/chunks/index2.js:1213:4)
    at visit (file:///Users/cmcculloh/Prototypes/backups/for-bug/node_modules/@sveltejs/kit/dist/chunks/index2.js:1104:3)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
```

Using `import()` with `await` causes this error:
```

> for-bug@0.0.1 build
> svelte-kit build

vite v2.9.1 building for production...
✓ 16 modules transformed.
rendering chunks (1)...[vite:esbuild-transpile] Transform failed with 1 error:
pages/index.svelte-4273c36b.js:3:12: ERROR: Top-level await is not available in the configured target environment ("chrome87", "edge88", "es2019", "firefox78", "safari13.1")

Top-level await is not available in the configured target environment ("chrome87", "edge88", "es2019", "firefox78", "safari13.1")
1  |  import { S as SvelteComponent, i as init, s as safe_not_equal, e as element, t as text, k as space, c as claim_element, a as children, h as claim_text, d as detach, m as claim_space, g as insert_hydration, J as append_hydration, n as noop } from '../chunks/index-dd45c2ae.js';
2  |  
3  |  const baz = await import('../chunks/baz-2277351f.js');
   |              ^
4  |  
5  |  const Foo = {

> Transform failed with 1 error:
pages/index.svelte-4273c36b.js:3:12: ERROR: Top-level await is not available in the configured target environment ("chrome87", "edge88", "es2019", "firefox78", "safari13.1")
pages/index.svelte-4273c36b.js:3:12: ERROR: Top-level await is not available in the configured target environment ("chrome87", "edge88", "es2019", "firefox78", "safari13.1")
    at failureErrorWithLog (/Users/cmcculloh/Prototypes/backups/for-bug/node_modules/esbuild/lib/main.js:1603:15)
    at /Users/cmcculloh/Prototypes/backups/for-bug/node_modules/esbuild/lib/main.js:1392:29
    at /Users/cmcculloh/Prototypes/backups/for-bug/node_modules/esbuild/lib/main.js:666:9
    at handleIncomingPacket (/Users/cmcculloh/Prototypes/backups/for-bug/node_modules/esbuild/lib/main.js:763:9)
    at Socket.readFromStdout (/Users/cmcculloh/Prototypes/backups/for-bug/node_modules/esbuild/lib/main.js:632:7)
    at Socket.emit (node:events:527:28)
    at addChunk (node:internal/streams/readable:324:12)
    at readableAddChunk (node:internal/streams/readable:297:9)
    at Socket.Readable.push (node:internal/streams/readable:234:10)
    at Pipe.onStreamRead (node:internal/stream_base_commons:190:23)

```

It's fine if you guys don't support it yet. I wanted to get it on your radar, and also note a solution for others that might run into this (none of the other commonly proposed solutions to this have worked). There's a similar-ish errors in Node 16 btw.

**Comment by cormacmccarthy** [comment]
@Conduitry I should also note that moving the code out of the module and making it native to the sveltekit project works just fine (which is why I specified that import json isn't working in a dependency, since it works if within the sveltekit project itself).
