### ISSUE TITLE
[adapter-cloudflare] doesn't work with html-minifier

### ISSUE THREAD

**Issue by raduab** [sveltejs/kit#4590]
### Describe the bug

Adding [html-minifer](https://www.npmjs.com/package/html-minifier) as a hook breaks the build when using [adapter-cloudflare](https://www.npmjs.com/package/@sveltejs/adapter-cloudflare)

### Reproduction

Setup a SvelteKit project as normal:

```shell
npm init svelte my-app
cd my-app
npm install --save-dev @sveltejs/adapter-cloudflare
npm install
```

Edit the `svelte.config.js` file to use the `adapter-cloudflare` adapter:

```javascript
import adapter from '@sveltejs/adapter-cloudflare'

/** @type {import('@sveltejs/kit').Config} */
const config = {
  kit: {
    adapter: adapter(),
  },
}

export default config
```

Create `src/hooks.js` to use the `html-minifier` to minify the HTML code, as per the [documentation](https://kit.svelte.dev/docs/migrating#integrations-html-minifier):

```javascript
import { minify } from 'html-minifier';
import { prerendering } from '$app/env';
 
const minification_options = {
  collapseBooleanAttributes: true,
  collapseWhitespace: true,
  conservativeCollapse: true,
  decodeEntities: true,
  html5: true,
  ignoreCustomComments: [/^#/],
  minifyCSS: true,
  minifyJS: false,
  removeAttributeQuotes: true,
  removeComments: true,
  removeOptionalTags: true,
  removeRedundantAttributes: true,
  removeScriptTypeAttributes: true,
  removeStyleLinkTypeAttributes: true,
  sortAttributes: true,
  sortClassName: true
};
 
/** @type {import('@sveltejs/kit').[Handle](https://kit.svelte.dev/docs/types#sveltejs-kit-handle)} */
export async function handle({ event, resolve }) {
  const response = await resolve(event);
 
  if (prerendering && response.headers.get('content-type') === 'text/html') {
    return new Response(minify(await response.text(), minification_options), {
      status: response.status,
      headers: response.headers
    });
  }
 
  return response;
}
```

Run `npm run build`

### Logs

```shell
> Build failed with 21 errors:
node_modules/clean-css/lib/options/format.js:1:30: ERROR: Could not resolve "os"
node_modules/clean-css/lib/options/inline-request.js:1:18: ERROR: Could not resolve "url"
node_modules/clean-css/lib/options/rebase-to.js:1:19: ERROR: Could not resolve "path"
node_modules/clean-css/lib/reader/apply-source-maps.js:1:17: ERROR: Could not resolve "fs"
node_modules/clean-css/lib/reader/apply-source-maps.js:2:19: ERROR: Could not resolve "path"
...
node_modules/clean-css/lib/options/format.js:1:30: ERROR: Could not resolve "os"
node_modules/clean-css/lib/options/inline-request.js:1:18: ERROR: Could not resolve "url"
node_modules/clean-css/lib/options/rebase-to.js:1:19: ERROR: Could not resolve "path"
node_modules/clean-css/lib/reader/apply-source-maps.js:1:17: ERROR: Could not resolve "fs"
node_modules/clean-css/lib/reader/apply-source-maps.js:2:19: ERROR: Could not resolve "path"
```

### System Info

```shell
System:
    OS: Linux 5.17 Arch Linux
    CPU: (8) x64 11th Gen Intel(R) Core(TM) i7-11370H @ 3.30GHz
    Memory: 8.93 GB / 31.14 GB
    Container: Yes
    Shell: 5.1.16 - /bin/bash
  Binaries:
    Node: 17.9.0 - /usr/bin/node
    Yarn: 1.22.18 - /usr/bin/yarn
    npm: 8.5.5 - /usr/bin/npm
  Browsers:
    Chromium: 100.0.4896.75
    Firefox: 99.0
  npmPackages:
    @sveltejs/adapter-cloudflare: ^1.0.0-next.17 => 1.0.0-next.17 
    @sveltejs/kit: next => 1.0.0-next.311 
    html-minifier: ^4.0.0 => 4.0.0 
    svelte: ^3.44.0 => 3.47.0
```

### Severity

blocking all usage of SvelteKit

### Additional Information

Prevents deploying to Cloudflare in production

**Comment by Conduitry** [comment]
If clean-css (a dependency of html-minifier) uses Node APIs, I don't think there's anything to be done here, except maybe document it. You'd need something that doesn't use Node APIs to use it in Cloudflare.

**Comment by raduab** [comment]
Understood, I will close this now. Thank you!

**Comment by kelvindecosta** [comment]
Just wanted to mention that Vercel Edge deployments, made via `adapter-vercel`, will also break because of the same reason.
`html-minifier` relies on `clean-css` which is using Node APIs.

You'd get the following error messages in the functions log:

```
Error: Dynamic require of "os" is not supported
    at ../../../../.svelte-kit/vercel-tmp/render/edge.js:9:7
    at ../../../../node_modules/.pnpm/clean-css@4.2.4/node_modules/clean-css/lib/options/format.js:1:22
    at ../../../../.svelte-kit/vercel-tmp/render/edge.js:9:7
    at ../../../../node_modules/.pnpm/clean-css@4.2.4/node_modules/clean-css/lib/optimizer/level-1/tidy-rules.js:1:13
    at ../../../../.svelte-kit/vercel-tmp/render/edge.js:9:7
    at ../../../../node_modules/.pnpm/clean-css@4.2.4/node_modules/clean-css/lib/optimizer/level-1/optimize.js:5:16
    at ../../../../.svelte-kit/vercel-tmp/render/edge.js:9:7
    at ../../../../node_modules/.pnpm/clean-css@4.2.4/node_modules/clean-css/lib/clean.js:9:21
    at ../../../../.svelte-kit/vercel-tmp/render/edge.js:9:7
    at ../../../../node_modules/.pnpm/clean-css@4.2.4/node_modules/clean-css/index.js:1:17```
