### ISSUE TITLE
Invalid URL when fetching internal standalone endpoint from another standalone endpoint

### ISSUE THREAD

**Issue by reesericci** [sveltejs/kit#4593]
### Describe the bug

If I try to fetch a standalone endpoint from another standalone endpoint, it doesn't work because the patched version of fetch isn't passed to standalone endpoints (get, post, etc.)

### Reproduction

https://stackblitz.com/edit/sveltejs-kit-template-default-sz2g9d?file=src/routes/fetch.js

Try to visit /fetch

### Logs

```shell
Invalid URL
TypeError [ERR_INVALID_URL]: Invalid URL
    at new NodeError (node:internal/errors:371:5)
    at onParseError (node:internal/url:552:9)
    at parse (<anonymous>)
    at new URL (node:internal/url:632:5)
    at new Request (file:///var/home/reesericci/js/web/thoughts/node_modules/@sveltejs/kit/dist/install-fetch.js:5907:16)
    at file:///var/home/reesericci/js/web/thoughts/node_modules/@sveltejs/kit/dist/install-fetch.js:6189:19
    at new Promise (<anonymous>)
    at fetch (file:///var/home/reesericci/js/web/thoughts/node_modules/@sveltejs/kit/dist/install-fetch.js:6187:9)
    at get (/var/home/reesericci/js/web/thoughts/src/routes/thoughts/[id].ts:4:20)
    at load_shadow_data (file:///var/home/reesericci/js/web/thoughts/.svelte-kit/runtime/server/index.js:1981:25)
```

### System Info

```shell
System:
    OS: Linux 5.16 Fedora Linux 35 (Container Image)
    CPU: (8) x64 Intel(R) Core(TM) i5-8265U CPU @ 1.60GHz
    Memory: 836.83 MB / 15.30 GB
    Container: Yes
    Shell: 5.1.8 - /bin/bash
  Binaries:
    Node: 17.3.0 - ~/.nvm/versions/node/v17.3.0/bin/node
    npm: 8.6.0 - ~/js/web/thoughts/node_modules/.bin/npm
  npmPackages:
    @sveltejs/adapter-auto: next => 1.0.0-next.34 
    @sveltejs/kit: next => 1.0.0-next.310 
    svelte: ^3.44.0 => 3.47.0
```

### Severity

serious, but I can work around it

**Comment by benmccann** [comment]
Your endpoint is fetching itself, which would be an infinite loop

This has nothing to do with whether or not it's the patched endpoint. It's because you need a full qualified URL

You also are missing an `await`. It should look more like:

```
export async function get({ url }) {
	const res = await fetch(new URL('/data', url));
	const json = await res.json();
	return json;
}
```

**Comment by reesericci** [comment]
but load() doesn't need a fully qualified url
