### ISSUE TITLE
adapter-static build with `trailingSlash: "alway"` option fails.

### ISSUE THREAD

**Issue by falsetru** [sveltejs/kit#4758]
### Describe the bug

build command try to access a file with trailing slash. (ex. `/favicon.png` -> `/favicon.png/`)

### Reproduction

- create app  using create-svelte, 'SvelteKit demo app'.
```
npm init svelte@next my-app  # Choose default options
cd my-app
```
- Add adapter-static
```
npm add -D @sveltejs/adapter-static@next
npm rm -D @sveltejs/adapter-auto
npm install
```
- Adjust `svelte.config.js` to use adapter-static, and `trailingSlash: 'always'` option.
```diff
--- a/svelte.config.js
+++ b/svelte.config.js
@@ -1,9 +1,10 @@
-import adapter from '@sveltejs/adapter-auto';
+import adapter from '@sveltejs/adapter-static';
 
 /** @type {import('@sveltejs/kit').Config} */
 const config = {
        kit: {
                adapter: adapter(),
+               trailingSlash: 'always',
 
                // Override http methods in the Todo forms
                methodOverride: {
```
- run build
```
npm run build
```

### Logs

```shell
npm run build

> my-app@0.0.1 build
> svelte-kit build

vite v2.9.6 building for production...
✓ 34 modules transformed.
.svelte-kit/output/client/_app/assets/svelte-logo-87df40b8.svg                           1.85 KiB
.svelte-kit/output/client/_app/assets/fira-mono-cyrillic-ext-400-normal-3df7909e.woff2   15.40 KiB
.svelte-kit/output/client/_app/assets/fira-mono-cyrillic-400-normal-c7d433fd.woff2       8.89 KiB
.svelte-kit/output/client/_app/assets/fira-mono-greek-ext-400-normal-9e2fe623.woff2      7.33 KiB
.svelte-kit/output/client/_app/assets/fira-mono-greek-400-normal-a8be01ce.woff2          10.27 KiB
.svelte-kit/output/client/_app/assets/fira-mono-latin-ext-400-normal-6bfabd30.woff2      11.10 KiB
.svelte-kit/output/client/_app/assets/fira-mono-latin-400-normal-e43b3538.woff2          15.90 KiB
.svelte-kit/output/client/_app/assets/fira-mono-all-400-normal-1e3b098c.woff             75.55 KiB
.svelte-kit/output/client/_app/manifest.json                                             2.67 KiB
.svelte-kit/output/client/_app/pages/__layout.svelte-7a649169.js                         4.76 KiB / gzip: 1.86 KiB
.svelte-kit/output/client/_app/error.svelte-f6969740.js                                  1.56 KiB / gzip: 0.75 KiB
.svelte-kit/output/client/_app/pages/about.svelte-103011ed.js                            2.51 KiB / gzip: 1.15 KiB
.svelte-kit/output/client/_app/pages/index.svelte-1e12193f.js                            5.47 KiB / gzip: 2.42 KiB
.svelte-kit/output/client/_app/pages/todos/index.svelte-43bb6c2c.js                      6.86 KiB / gzip: 2.88 KiB
.svelte-kit/output/client/_app/chunks/index-a0e90cc4.js                                  0.43 KiB / gzip: 0.30 KiB
.svelte-kit/output/client/_app/chunks/singletons-d1fb5791.js                             0.05 KiB / gzip: 0.07 KiB
.svelte-kit/output/client/_app/assets/pages/about.svelte-bf4528fa.css                    0.11 KiB / gzip: 0.10 KiB
.svelte-kit/output/client/_app/start-08e46c80.js                                         23.34 KiB / gzip: 8.67 KiB
.svelte-kit/output/client/_app/assets/pages/__layout.svelte-15681802.css                 4.96 KiB / gzip: 1.55 KiB
.svelte-kit/output/client/_app/chunks/index-2db0445a.js                                  11.77 KiB / gzip: 5.00 KiB
.svelte-kit/output/client/_app/assets/pages/index.svelte-d0605c9c.css                    1.43 KiB / gzip: 0.51 KiB
.svelte-kit/output/client/_app/assets/pages/todos/index.svelte-a910a02d.css              3.70 KiB / gzip: 1.03 KiB
vite v2.9.6 building SSR bundle for production...
✓ 35 modules transformed.
.svelte-kit/output/server/manifest.json                         2.32 KiB
.svelte-kit/output/server/index.js                              75.29 KiB
.svelte-kit/output/server/entries/endpoints/todos/index.js      1.33 KiB
.svelte-kit/output/server/entries/pages/__layout.svelte.js      4.60 KiB
.svelte-kit/output/server/entries/fallbacks/error.svelte.js     0.72 KiB
.svelte-kit/output/server/entries/pages/about.svelte.js         1.38 KiB
.svelte-kit/output/server/entries/pages/index.svelte.js         8.18 KiB
.svelte-kit/output/server/entries/pages/todos/index.svelte.js   5.92 KiB
.svelte-kit/output/server/chunks/index-19ef195d.js              3.94 KiB
.svelte-kit/output/server/chunks/hooks-0bab96cd.js              0.48 KiB
> 404 /favicon.png/ (linked from /)
    at file:///tmp/my-app/node_modules/@sveltejs/kit/dist/chunks/index2.js:988:11
    at save (file:///tmp/my-app/node_modules/@sveltejs/kit/dist/chunks/index2.js:1208:4)
    at visit (file:///tmp/my-app/node_modules/@sveltejs/kit/dist/chunks/index2.js:1099:3)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
```
```


### System Info

```shell
System:
    OS: Linux 5.13 Ubuntu 21.10 21.10 (Impish Indri)
    CPU: (4) x64 Intel(R) Core(TM) i7-7600U CPU @ 2.80GHz
    Memory: 791.54 MB / 15.38 GB
    Container: Yes
    Shell: 5.8 - /usr/bin/zsh
  Binaries:
    Node: 14.19.1 - /usr/bin/node
    Yarn: 1.22.11 - ~/.npm-packages/bin/yarn
    npm: 8.5.0 - ~/.npm-packages/bin/npm
  Browsers:
    Chrome: 101.0.4951.41
    Firefox: 99.0
  npmPackages:
    @sveltejs/adapter-static: ^1.0.0-next.29 => 1.0.0-next.29 
    @sveltejs/kit: next => 1.0.0-next.322 
    svelte: ^3.46.0 => 3.47.0
```

### Severity

blocking an upgrade

### Additional Information

Downgrading from @sveltejs/kit@1.0.0-next.322 to @sveltejs/kit@1.0.0-next.321 solves issue.

**Comment by Masstronaut** [comment]
`@sveltejs/kit: next => 1.0.0-next.322` also seems to have broken the output file structure `static-adapter` builds.

```
src/routes/[param]/index.svelte
src/routes/[param]/file.json.js
src/routes/[param]/index.json.js
```

Generates the following output files in the build folder:
```
[param]/file.json
[param].html
[param].json
```

This broke all paths using a route parameter for a github pages deployment I had set up.
