### ISSUE TITLE
$lib alias does not work while dynamically importing a component when using string interpolation

### ISSUE THREAD

**Issue by jhubbardsf** [sveltejs/kit#4982]
### Describe the bug

A dynamically imported component, with a variable in the path, breaks if using the $lib alias. Example below:
```ts
<script lang='ts'>
    import { onMount } from "svelte";

    let TestComponent: any;
    const componentName = 'TestComponent.svelte';
    onMount(async ()=>{
        TestComponent = (await import(`../lib/${componentName}`)).default; // THIS WORKS
        // TestComponent = (await import(`$lib/${componentName}`)).default; // THIS DOES NOT WORK
    });
    
</script>

<svelte:component this={TestComponent}/>
```

### Reproduction

Create a new SvelteKit app. Create a TestComponent.svelte file with something in it. Try to dynamically import the component using string interpolation in the path.

### Logs

```shell
importTest.svelte? [sm]:8 Uncaught (in promise) TypeError: Failed to resolve module specifier '$lib/TestComponent.svelte'
    at importTest.svelte? [sm]:8:47
    at run (index.mjs:18:12)
    at Array.map (<anonymous>)
    at index.mjs:1816:45
    at flush (index.mjs:1075:17)
    at init (index.mjs:1908:9)
    at new Root (root.svelte? [sm]:16:25)
    at createProxiedComponent (svelte-hooks.js:341:9)
    at new ProxyComponent (proxy.js:242:7)
    at new Proxy<Root> (proxy.js:349:11)
```

### System Info

```shell
System:
    OS: macOS 12.0.1
    CPU: (10) arm64 Apple M1 Pro
    Memory: 109.64 MB / 16.00 GB
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 17.6.0 - ~/.nvm/versions/node/v17.6.0/bin/node
    Yarn: 1.22.17 - /opt/homebrew/bin/yarn
    npm: 8.5.1 - ~/.nvm/versions/node/v17.6.0/bin/npm
  Browsers:
    Brave Browser: 101.1.38.111
    Chrome: 101.0.4951.64
    Firefox: 96.0.3
    Firefox Developer Edition: 98.0
    Safari: 15.1
  npmPackages:
    @sveltejs/adapter-auto: next => 1.0.0-next.43
    @sveltejs/kit: next => 1.0.0-next.335
    svelte: ^3.46.0 => 3.48.0
```

### Severity

serious, but I can work around it

**Comment by dummdidumm** [comment]
Probably a Vite thing

**Comment by bluwy** [comment]
This will be supported in Vite 3 from https://github.com/vitejs/vite/pull/7756
