### ISSUE TITLE
[docs] document setting Node version for `adapter-vercel`

### ISSUE THREAD

**Issue by y0zong** [sveltejs/kit#5055]
### Describe the bug

```
2022-05-24T13:27:38.910Z  Uploading build outputs...
2022-05-24T13:27:39.520Z   > vc-file-system:index.js:604:20: error: Could not resolve "crypto" (use "platform: 'node'" when building for node)
2022-05-24T13:27:39.520Z      604 │ import crypto2 from "crypto";
2022-05-24T13:27:39.520Z          ╵                     ~~~~~~~~
2022-05-24T13:27:39.521Z  
2022-05-24T13:27:39.524Z  Error: Build failed with 1 error:
2022-05-24T13:27:39.524Z  vc-file-system:index.js:604:20: error: Could not resolve "crypto" (use "platform: 'node'" when building for node)
2022-05-24T13:27:39.524Z      at failureErrorWithLog (/var/task/node_modules/esbuild/lib/main.js:1449:15)
2022-05-24T13:27:39.524Z      at /var/task/node_modules/esbuild/lib/main.js:1131:28
2022-05-24T13:27:39.524Z      at runOnEndCallbacks (/var/task/node_modules/esbuild/lib/main.js:921:63)
2022-05-24T13:27:39.524Z      at buildResponseToResult (/var/task/node_modules/esbuild/lib/main.js:1129:7)
2022-05-24T13:27:39.524Z      at /var/task/node_modules/esbuild/lib/main.js:1236:14
2022-05-24T13:27:39.524Z      at /var/task/node_modules/esbuild/lib/main.js:609:9
2022-05-24T13:27:39.525Z      at handleIncomingPacket (/var/task/node_modules/esbuild/lib/main.js:706:9)
2022-05-24T13:27:39.525Z      at Socket.readFromStdout (/var/task/node_modules/esbuild/lib/main.js:576:7)
2022-05-24T13:27:39.525Z      at Socket.emit (events.js:400:28)
2022-05-24T13:27:39.525Z      at addChunk (internal/streams/readable.js:293:12) {
2022-05-24T13:27:39.525Z    errors: [
2022-05-24T13:27:39.525Z      {
2022-05-24T13:27:39.525Z        detail: undefined,
2022-05-24T13:27:39.525Z        location: [Object],
2022-05-24T13:27:39.525Z        notes: [],
2022-05-24T13:27:39.525Z        pluginName: '',
2022-05-24T13:27:39.525Z        text: `Could not resolve "crypto" (use "platform: 'node'" when building for node)`
2022-05-24T13:27:39.525Z      }
2022-05-24T13:27:39.525Z    ],
2022-05-24T13:27:39.526Z    warnings: [],
2022-05-24T13:27:39.526Z    step: 'UPLOADING_BUILD_OUTPUTS'
2022-05-24T13:27:39.526Z  }
```

### Reproduction

run `ENABLE_VC_BUILD=1 npm run build` build success in local, but failed when `vercel deploy`, I don't know it's a adapter-vercel bug or vercel edge function bug, since vercel docment only show `next.js` use case I ask here see if I'm miss something?

### System Info

```shell
@svelte/kit 1.0.0-next.342
@svelte/adapter-vercel 1.0.0-next.54
node 18.0.0
vercel CLI 24.2.4
```

### Severity

blocking an upgrade

**Comment by Rich-Harris** [comment]
It looks like you're importing Node's `crypto` module somewhere in your app? That won't work in an edge function. If it's in your code you should just use the web crypto API (available as the `crypto` global); if it's in a library then you should either use a different library or use `edge: false`. 

Can't provide any more diagnosis than that because you didn't provide a reproduction.

**Comment by Avi-ADAM** [comment]
for me it's fails with edge: false , it just happened suddenly  this is the errors i get, also for couple of weeks i get errore with node version that the version is 14.19 and should be more then 16 for this i use "--install.ignore-engines true" inside .yarnrc file that i created
```


$ svelte-kit build --verbose
--
23:28:13.033 | (node:530) UnhandledPromiseRejectionWarning: file:///vercel/path0/node_modules/@sveltejs/kit/dist/node/polyfills.js:8
23:28:13.033 | import { webcrypto } from 'crypto';
23:28:13.033 | ^^^^^^^^^
23:28:13.034 | SyntaxError: The requested module 'crypto' does not provide an export named 'webcrypto'
23:28:13.034 | at ModuleJob._instantiate (internal/modules/esm/module_job.js:124:21)
23:28:13.034 | at async ModuleJob.run (internal/modules/esm/module_job.js:179:5)
23:28:13.034 | at async Loader.import (internal/modules/esm/loader.js:178:24)
23:28:13.034 | at async file:///vercel/path0/node_modules/@sveltejs/kit/dist/cli.js:1003:22
23:28:13.034 | (Use `node --trace-warnings ...` to show where the warning was created)
23:28:13.035 | (node:530) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
23:28:13.035 | (node:530) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
23:28:13.039 | Done in 0.26s.
23:28:13.055 | Error: No Output Directory named "public" found after the Build completed. You can configure the Output Directory in your Project Settings. Learn More: https://vercel.link/missing-public-directory


```

**Comment by Rich-Harris** [comment]
> i use "--install.ignore-engines true" inside .yarnrc file that i created

yeah, so maybe don't do that? The engine restrictions are there for a reason. SvelteKit requires Node 16.7 or higher to build.

**Comment by Avi-ADAM** [comment]
but then i get this error
`<html>
<body>


error @sveltejs/kit@1.0.0-next.343: The engine "node" is incompatible with this module. Expected version ">=16". Got "14.19.0"
--
00:40:04.688 | error Found incompatible module.
00:40:04.689 | info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
00:40:04.708 | Error: Command "yarn install" exited with 1


</body>
</html>`
my computer node is 18.2 and on my package.json under dependencies is ""node": "^17.7.2","

**Comment by Rich-Harris** [comment]
If you see an error message, it means you need to _fix the error_, not add a setting like `ignore-engines` which silences it without actually doing anything about it.

In this case, that means changing the Node version Vercel uses to build and run your project. For new projects, it will default to 16 automatically, but if you have an older project you will need to change it in your project settings here:

<img width="645" alt="image" src="https://user-images.githubusercontent.com/1162160/170140511-a768af38-7f55-4a6d-b8d6-daef83e4c724.png">

**Comment by Avi-ADAM** [comment]
i added ```
"engines": {
    "node": "16.x"
  },
``` to my packge.json and it solved for me

**Comment by y0zong** [comment]
> It looks like you're importing Node's crypto module somewhere in your app?

yse, according to your hint I found the problem, `nanoid` which in my project use node crypto (`import crypto from 'crypto'`) and lock the node version to *16.x* fix this, Thank you very much for your quick reply!!

**Comment by vishnusankaran** [comment]
I faced the same issue when tyring to run dev local on an older sveltekit project. I had to:

1. Upgrade to `lts/gallium`
2. Remove `target` property from the `svelte.config.json`
3. Change `%svelte.(body,head,assets)%` to `%sveltekit.(body,head,assets)%` in app.html

```
> svelte-kit dev

(node:14844) UnhandledPromiseRejectionWarning: file:///<pwd>/node_modules/.pnpm/@sveltejs+kit@1.0.0-next.350_svelte@3.48.0/node_modules/@sveltejs/kit/dist/node/polyfills.js:11
import { webcrypto } from 'crypto';
^^^^^^^^^
SyntaxError: The requested module 'crypto' does not provide an export named 'webcrypto'
at ModuleJob._instantiate (internal/modules/esm/module_job.js:120:21)
at async ModuleJob.run (internal/modules/esm/module_job.js:165:5)
at async Loader.import (internal/modules/esm/loader.js:177:24)
at async start (file:///<pwd>/node_modules/.pnpm/@sveltejs+kit@1.0.0-next.350_svelte@3.48.0/node_modules/@sveltejs/kit/dist/cli.js:833:24)
```

@Rich-Harris 
I assume it broke because my package.json had `"@sveltejs/kit": "next",` and the newer versions of the kit had a few breaking changes and requried newer version for node?
