### ISSUE TITLE
TypeError: undefined is not an object (evaluating 'o[d-1][2]') in production but not dev

### ISSUE THREAD

**Issue by nstuyvesant** [sveltejs/kit#5119]
### Describe the bug

My project uses Carbon Charts Svelte. When running in dev, I have a page that loads with a **LineChart** that looks fine. When I run an `npm run build` then try to execute via `node build`, that page in Safari throws this JavaScript error:
```
Unhandled Promise Rejection: TypeError: undefined is not an object (evaluating 'o[p-1][2]')
```

When running in Chrome, the error looks a little different...
```
index.svelte-64343f7e.js:1 Uncaught (in promise) TypeError: Cannot read properties of undefined (reading '2')
    at u (index.svelte-64343f7e.js:1:109197)
    at s (index.svelte-64343f7e.js:1:108955)
    at c.ticks (index.svelte-64343f7e.js:1:118840)
    at n.render (index.svelte-64343f7e.js:73:13561)
    at index.svelte-64343f7e.js:73:25017
    at Array.forEach (<anonymous>)
    at n.render (index.svelte-64343f7e.js:73:24975)
    at index.svelte-64343f7e.js:73:10535
    at Array.forEach (<anonymous>)
    at HTMLDivElement.<anonymous> (index.svelte-64343f7e.js:73:10465)
```

I'm really lost as to where this is going South but if I comment out the **LineChart** on that page, I do not get an error.

Running in dev does not exhibit this problem.

The problem started within the past month or so and the only thing that changed was the SvelteKit and Adapter-Node versions.

### Reproduction

1. `git clone https://github.com/nstuyvesant/carbon-example.git`
2. `cd carbon-example`
3. `npm install`
4. `npm run build`
5. `node build`
6. Browse to http://localhost:3000
7. Look at JavaScript error in browser's console.

To see it run without the JavasScript error, `npm run dev`.

### System Info

```shell
System:
    OS: macOS 12.4
    CPU: (10) arm64 Apple M1 Pro
    Memory: 2.06 GB / 32.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 16.15.0 - /opt/homebrew/bin/node
    Yarn: 1.22.19 - /opt/homebrew/bin/yarn
    npm: 8.11.0 - /opt/homebrew/bin/npm
  Browsers:
    Chrome: 102.0.5005.61
    Firefox: 100.0.2
    Safari: 15.5
  npmPackages:
    @sveltejs/adapter-auto: next => 1.0.0-next.48 
    @sveltejs/kit: next => 1.0.0-next.345 
    svelte: ^3.48.0 => 3.48.0
```

### Severity

blocking an upgrade

**Comment by nstuyvesant** [comment]
So much has changed since this occurred. Not seeing it any longer.
