### ISSUE TITLE
NPM package using getContext/setContext doesn't work 

### ISSUE THREAD

**Issue by enyo** [sveltejs/kit#5132]
### Describe the bug

I have distilled the issue to this:

- Create an npm package that exposes a function that uses `setContext` or `getContext`
- Make sure that repo does not have `svelte` as a direct dependency but only as `peerDependency` (or not even that)
- Import the package and use the function
- It crashes with: **Function called outside component initialization**

This only happens as npm package, using a local dependency works fine.

### Reproduction

I tried reproducing in a REPL but it works fine: https://svelte.dev/repl/71e6719fc2734399b68904c9af31ccd1?version=3.48.0

That's why I assume it's a Svelte Kit issue. Here is the minimal reproduction repo:

https://github.com/enyo/context-issue

It contains the package, where the `dist/index.js` has this content:

```js
import { setContext } from 'svelte';

const testSetContext = () => setContext('test', 'value');

export { testSetContext };
//# sourceMappingURL=index.js.map
```

and a svelte kit app that uses it.

### System Info

```shell
System:
    OS: macOS 12.3.1
    CPU: (10) arm64 Apple M1 Pro
    Memory: 293.67 MB / 32.00 GB
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 17.9.0 - ~/.nvm/versions/node/v17.9.0/bin/node
    Yarn: 1.22.18 - ~/.nvm/versions/node/v17.9.0/bin/yarn
    npm: 8.5.5 - ~/.nvm/versions/node/v17.9.0/bin/npm
  Browsers:
    Chrome: 102.0.5005.61
    Firefox: 100.0.2
    Safari: 15.4
    Safari Technology Preview: 15.4
  npmPackages:
    @sveltejs/adapter-auto: next => 1.0.0-next.50 
    @sveltejs/kit: next => 1.0.0-next.347 
    svelte: ^3.44.0 => 3.48.0
```

### Severity

blocking all usage of SvelteKit

**Comment by dominikg** [comment]
This error usually happens when there are multiple versions of svelte, which means that the `resolve.dedupe` config vite-plugin-svelte adds to the vite config has failed.

It's a strange coincidence but a similar error just happened today with alpha testing of vite-3  in a test for vite-plugin-svelte: https://github.com/sveltejs/vite-plugin-svelte/blob/main/packages/e2e-tests/kit-node

Some information that can help track this down:

stacktrace from vite-plugin-svelte test
```shell
Error: Function called outside component initialization
    at get_current_component (file:///home/dominikg/develop/vitejs/vite-ecosystem-ci/workspace/svelte/vite-plugin-svelte/node_modules/.pnpm/svelte@3.48.0/node_modules/svelte/internal/index.mjs:953:15)
    at setContext (file:///home/dominikg/develop/vitejs/vite-ecosystem-ci/workspace/svelte/vite-plugin-svelte/node_modules/.pnpm/svelte@3.48.0/node_modules/svelte/internal/index.mjs:985:5)
    at Proxy.setSomeContext (file:///home/dominikg/develop/vitejs/vite-ecosystem-ci/workspace/svelte/vite-plugin-svelte/packages/e2e-tests/_test_dependencies/svelte-api-only/index.js:4:2)
    at index.svelte:35:1
    at Object.$$render (/home/dominikg/develop/vitejs/vite-ecosystem-ci/workspace/svelte/vite-plugin-svelte/node_modules/.pnpm/svelte@3.48.0/node_modules/svelte/internal/index.js:1758:22)
    at Object.default (root.svelte:43:39)
    at eval (/.svelte-kit/runtime/components/layout.svelte:8:41)
    at Object.$$render (/home/dominikg/develop/vitejs/vite-ecosystem-ci/workspace/svelte/vite-plugin-svelte/node_modules/.pnpm/svelte@3.48.0/node_modules/svelte/internal/index.js:1758:22)
    at root.svelte:37:37
    at $$render (/home/dominikg/develop/vitejs/vite-ecosystem-ci/workspace/svelte/vite-plugin-svelte/node_modules/.pnpm/svelte@3.48.0/node_modules/svelte/internal/index.js:1758:22)
````

in this stacktrace svelte is referenced in node_modules, but another version of svelte exists in vite's optimizedDeps in `node_modules/.vite/`, so when this second svelte is loaded, it doesn't have the state of the first instance and this error happens.

**Comment by enyo** [comment]
@dominikg mh, yes I assumed that it had something to do with deduping not working, I'm just really stumped because the package doesn't have a `svelte` dependency by itself. So where does the second version come from?

Is there a workaround for this that you know of?

**Comment by dominikg** [comment]
you can try playing with `optimizeDeps.exclude` and `optimizeDeps.include`. 

vite-plugin-svelte should generate a working configuration for that, you can see it when you run with `DEBUG=vite:* npm run dev`

thanks for uploading the dependency tmp-context-issue to the npm registry, i was able to reproduce the same error outside of sveltekit: https://stackblitz.com/edit/vitejs-vite-aegr3m?file=package.json,src%2Fmain.js&terminal=dev

color me stumped too.

**Comment by enyo** [comment]
I didn't get it to work with either `optimizeDeps.exclude` or `include`.

**Comment by gtm-nayan** [comment]
Unfortunately, I also found it by fiddling around with the config values so I don't have a definite answer as to why it works. My thought process was if it's force bundled the package would reference the same svelte instance as the app.

**Comment by enyo** [comment]
I tried the same fix in other projects and it surfaced other bugs that I wasn't able to get rid of, so `ssr.noExternal` workaround is not viable unfortunately.

**Comment by enyo** [comment]
@dominikg so is it safe to say that this issue is cause by `vite-plugin-svelte`?
