### ISSUE TITLE
Can't get the host origin in stores.js file

### ISSUE THREAD

**Issue by xeroticikot** [sveltejs/kit#5133]
### Describe the bug

Below is my stores.js file code

`
import { writable } from 'svelte/store';
import {page} from "$app/stores";

let gs;

console.log(page.url);

export const currentHost = writable(page.url);

const response = await fetch(`http://localhost:3000/data/settings/gs.json`);
gs = await response.json();

export const darkMode = writable(gs.dark_mode ? gs.dark_mode : false);
export const pageTitle = writable("");
export const siteName = writable(gs.site_name ? gs.site_name : "");
export const siteMoto = writable(gs.site_moto ? gs.site_moto : "");
export const siteLogo = writable(gs.site_logo ? gs.site_logo : "");
export const siteFavicon = writable(gs.site_favicon ? gs.site_favicon : "");
export const topMenu = writable(gs.top_menu ? gs.top_menu : null);
export const mainMenu = writable(gs.main_menu ? gs.main_menu : null);
export const footerMenu = writable(gs.footer_menu ? gs.footer_menu : null);
export const sideBar = writable(gs.sidebar ? gs.sidebar : null);
export const defaultHome = writable(gs.default_home ? gs.default_home : null);
export const maintenanceMode = writable(gs.maintenance_mode ? gs.maintenance_mode : false);

`

As you can see http://localhost is called manually, fetch is not automatically adding host origin. So I wanted to get the host origin manually, searched google & stackoverflow for solutions, but nothing's working as expected. Tried {page} from '$app/stores', but it returns undefined.

### Reproduction

 https://node.new/sveltekit

### System Info

```shell
NODE_VERSION = 16
```

### Severity

annoyance

**Comment by accuser** [comment]
I think you want `$page`, not `page`. The `import` is the same, but the way you are accessing `page` is not correct for your usage.

```
import {page} from "$app/stores";

console.log($page.url);
```

**Comment by accuser** [comment]
My bad. `page` (as imported) is a store, and only exposes `subscribe()`. If you want to access the value in the module, you will need to use `get()` (also from `$app/stores`) to access it:

```
import { page } from '$app/stores';
import { get } from 'svelte/store';

console.log(get(page).url)
```

If you use the store in a `.svelte` file, you can use the `$` shorthand:

```
<script>
	import { page } from '$app/stores';
</script>

{$page.url}
```

**Comment by xeroticikot** [comment]
this returns the following error---

Error: Function called outside component initialization
    at get_current_component (E:\WORKPLACE\SVELTEST\node_modules\svelte\internal\index.js:956:15)
    at Proxy.getContext (E:\WORKPLACE\SVELTEST\node_modules\svelte\internal\index.js:992:12)
    at getStores (/.svelte-kit/runtime/app/stores.js:24:39)
    at Object.subscribe (/.svelte-kit/runtime/app/stores.js:50:17)
    at subscribe (E:\WORKPLACE\SVELTEST\node_modules\svelte\internal\index.js:59:25)
    at Proxy.get_store_value (E:\WORKPLACE\SVELTEST\node_modules\svelte\internal\index.js:64:5)
    at eval (/src/store.js:8:35)
    at async instantiateModule (E:\WORKPLACE\SVELTEST\\node_modules\vite\dist\node\chunks\dep-59dc6e00.js:59333:9)
