### ISSUE TITLE
import jquery in layout file, get error

### ISSUE THREAD

**Issue by kuchaguangjie** [sveltejs/kit#5220]
### Describe the bug

When import jquery in `__layout.svelte` via `import * as j$ from 'jquery'`, get error:
```
TypeError: __vite_ssr_import_3__ is not a function
    at eval (/src/routes/__layout.svelte:31:18)
    at Object.$$render (/mnt/star/workplace/jetbrains/webstorm_workplace/go-fit-web/node_modules/.pnpm/registry.npmmirror.com+svelte@3.48.0/node_modules/svelte/internal/index.js:1758:22)
    at eval (/.svelte-kit/generated/root.svelte:50:126)
    at $$render (/mnt/star/workplace/jetbrains/webstorm_workplace/go-fit-web/node_modules/.pnpm/registry.npmmirror.com+svelte@3.48.0/node_modules/svelte/internal/index.js:1758:22)
    at Object.render (/mnt/star/workplace/jetbrains/webstorm_workplace/go-fit-web/node_modules/.pnpm/registry.npmmirror.com+svelte@3.48.0/node_modules/svelte/internal/index.js:1766:26)
    at render_response (file:///mnt/star/workplace/jetbrains/webstorm_workplace/go-fit-web/.svelte-kit/runtime/server/index.js:1202:27)
    at async respond_with_error (file:///mnt/star/workplace/jetbrains/webstorm_workplace/go-fit-web/.svelte-kit/runtime/server/index.js:2632:10)
    at async respond$1 (file:///mnt/star/workplace/jetbrains/webstorm_workplace/go-fit-web/.svelte-kit/runtime/server/index.js:2887:4)
    at async resolve (file:///mnt/star/workplace/jetbrains/webstorm_workplace/go-fit-web/.svelte-kit/runtime/server/index.js:3267:11)
    at async respond (file:///mnt/star/workplace/jetbrains/webstorm_workplace/go-fit-web/.svelte-kit/runtime/server/index.js:3211:20)
```
But the import works in non-layout files, any idea why this happen, and is there anyway to fix it?

### Reproduction

- in `__layout.svelte`, import jquery via: `import * as j$ from 'jquery'`
- refresh the page,

### Logs

```shell
TypeError: __vite_ssr_import_3__ is not a function
    at eval (/src/routes/__layout.svelte:31:18)
    at Object.$$render (/mnt/star/workplace/jetbrains/webstorm_workplace/go-fit-web/node_modules/.pnpm/registry.npmmirror.com+svelte@3.48.0/node_modules/svelte/internal/index.js:1758:22)
    at eval (/.svelte-kit/generated/root.svelte:50:126)
    at $$render (/mnt/star/workplace/jetbrains/webstorm_workplace/go-fit-web/node_modules/.pnpm/registry.npmmirror.com+svelte@3.48.0/node_modules/svelte/internal/index.js:1758:22)
    at Object.render (/mnt/star/workplace/jetbrains/webstorm_workplace/go-fit-web/node_modules/.pnpm/registry.npmmirror.com+svelte@3.48.0/node_modules/svelte/internal/index.js:1766:26)
    at render_response (file:///mnt/star/workplace/jetbrains/webstorm_workplace/go-fit-web/.svelte-kit/runtime/server/index.js:1202:27)
    at async respond_with_error (file:///mnt/star/workplace/jetbrains/webstorm_workplace/go-fit-web/.svelte-kit/runtime/server/index.js:2632:10)
    at async respond$1 (file:///mnt/star/workplace/jetbrains/webstorm_workplace/go-fit-web/.svelte-kit/runtime/server/index.js:2887:4)
    at async resolve (file:///mnt/star/workplace/jetbrains/webstorm_workplace/go-fit-web/.svelte-kit/runtime/server/index.js:3267:11)
    at async respond (file:///mnt/star/workplace/jetbrains/webstorm_workplace/go-fit-web/.svelte-kit/runtime/server/index.js:3211:20)
```

### System Info

```shell
System:
    OS: Linux 5.14 Linux Mint 20.1 (Ulyssa)
    CPU: (8) x64 Intel(R) Core(TM) i7-4720HQ CPU @ 2.60GHz
    Memory: 333.52 MB / 15.55 GB
    Container: Yes
    Shell: 5.0.17 - /bin/bash
  Binaries:
    Node: 16.13.1 - ~/.nvm/versions/node/v16.13.1/bin/node
    Yarn: 1.22.17 - ~/.nvm/versions/node/v16.13.1/bin/yarn
    npm: 8.11.0 - ~/.nvm/versions/node/v16.13.1/bin/npm
  Browsers:
    Chrome: 102.0.5005.115
  npmPackages:
    @sveltejs/adapter-auto: next => 1.0.0-next.50 
    @sveltejs/kit: next => 1.0.0-next.350 
    svelte: ^3.48.0 => 3.48.0 

```

### Severity

serious, but I can work around it

**Comment by Mlocik97** [comment]
jQuery is client-side lib that is self-registering... so ofc it will not work, if you import it in Component that is server-side rendered. You will either need to ad `?client` parameter, or use dynamic import in `onMount` (or resp, browser check).

See: https://kit.svelte.dev/faq#integrations-how-do-i-use-a-client-side-only-library-that-depends-on-document-or-window

**Comment by kuchaguangjie** [comment]
@Mlocik97  Import jquery in component works well in my project.
The problem is it doesn't work when import in `__layout.svelte`

**Comment by kuchaguangjie** [comment]
@Mlocik97 jquery can be imported in svelte component, simply via `import * as $j from 'jquery';`, refer: https://stackoverflow.com/a/58222999
The problem is with `__layout.svelte`.

**Comment by benmccann** [comment]
We highly recommend against using jquery with Svelte

**Comment by Mlocik97** [comment]
And not with just Svelte... but I would recommend against using jquery at all.

**Comment by UltraCakeBakery** [comment]
I have a dislike for jQuery in svelte applications as much as others, but this error he got also happens with other third party libraries. I hope this issue gets looked into properly and not waved away because this person wants to use jquery inside of svelte..

**Comment by benmccann** [comment]
You have to use ESM or CJS source code. JQuery looks to be CJS + AMD. It's not very well packaged that it's shipping multiple formats in the same file. It should ship multiple versions for different use cases

In any case, there's nothing to be done in SvelteKit. If there's anything that can be changed it would need to be in Vite: https://github.com/sveltejs/kit#bug-reporting
