### ISSUE TITLE
SyntaxError: Named export '...' not found

### ISSUE THREAD

**Issue by endremborza** [sveltejs/kit#5325]
### Describe the bug

I started building a [simple visualization](https://github.com/endremborza/qft-viz) with sveltekit yesterday, it was a great experience up until trying to add gh-pages package and running `npm run build`. I am quite new to svelte and javascript so I had quite a bit of trouble looking into what is going on here.

### Reproduction

it is a very small project, that reproduces the issue after `npm run build`: https://github.com/endremborza/qft-viz

I didn't do much, but 

```bash
npm create svelte qft-app
cd qft-app
npm install @rollup/plugin-json --save
npm install svelte-vega --save
npm install gh-pages --save-dev
```

change the `svelte.config` to the one in the repo and add a slightly modified vega-lite example straight from https://github.com/vega/svelte-vega/blob/main/packages/storybook/stories/SvelteVegaLiteDemo.svelte

then ran

```npm run build```

I assumed the problem is with sveltekit as the issue comes up in the built `.svelte-kit/output/server/entries/pages/index.svelte.js:2`

### Logs

```shell
> qft-app@0.0.1 build
> svelte-kit build

vite v2.9.13 building for production...
✓ 787 modules transformed.
  Client build completed. Wrote 5 chunks and 10 assets
  Building server
.svelte-kit/output/client/_app/immutable/assets/fira-mono-cyrillic-ext-400-normal-3df7909e.woff2   15.40 KiB
.svelte-kit/output/client/_app/immutable/assets/fira-mono-greek-400-normal-a8be01ce.woff2          10.27 KiB
.svelte-kit/output/client/_app/immutable/assets/fira-mono-cyrillic-400-normal-c7d433fd.woff2       8.89 KiB
.svelte-kit/output/client/_app/immutable/assets/fira-mono-greek-ext-400-normal-9e2fe623.woff2      7.33 KiB
.svelte-kit/output/client/_app/immutable/assets/fira-mono-latin-ext-400-normal-6bfabd30.woff2      11.10 KiB
.svelte-kit/output/client/_app/immutable/assets/fira-mono-latin-400-normal-e43b3538.woff2          15.90 KiB
.svelte-kit/output/client/_app/immutable/assets/fira-mono-all-400-normal-1e3b098c.woff             75.55 KiB
.svelte-kit/output/client/_app/immutable/manifest.json                                             1.67 KiB
.svelte-kit/output/client/_app/immutable/pages/__layout.svelte-047db726.js                         0.71 KiB / gzip: 0.47 KiB
.svelte-kit/output/client/_app/immutable/error.svelte-bd9484bf.js                                  1.56 KiB / gzip: 0.74 KiB
.svelte-kit/output/client/_app/immutable/assets/pages/index.svelte-29920c36.css                    0.17 KiB / gzip: 0.13 KiB
.svelte-kit/output/client/_app/immutable/assets/pages/__layout.svelte-5bf667f3.css                 3.49 KiB / gzip: 1.17 KiB
.svelte-kit/output/client/_app/immutable/chunks/index-ec780ff8.js                                  7.77 KiB / gzip: 3.12 KiB
.svelte-kit/output/client/_app/immutable/start-c156750f.js                                         23.14 KiB / gzip: 8.77 KiB
vite v2.9.13 building SSR bundle for production...
✓ 22 modules transformed.
.svelte-kit/output/server/manifest.json                       1.60 KiB
.svelte-kit/output/server/index.js                            72.72 KiB
.svelte-kit/output/server/entries/pages/__layout.svelte.js    4.94 KiB
.svelte-kit/output/server/entries/fallbacks/error.svelte.js   0.72 KiB
.svelte-kit/output/server/entries/pages/index.svelte.js       6.73 KiB
.svelte-kit/output/server/chunks/index-5f02e38a.js            3.55 KiB
.svelte-kit/output/server/chunks/hooks-93fa095d.js            0.46 KiB
  Prerendering
.svelte-kit/output/client/_app/immutable/pages/index.svelte-a0a99dc4.js                            852.82 KiB / gzip: 287.23 KiB

(!) Some chunks are larger than 500 KiB after minification. Consider:
- Using dynamic import() to code-split the application
- Use build.rollupOptions.output.manualChunks to improve chunking: https://rollupjs.org/guide/en/#outputmanualchunks
- Adjust chunk size limit for this warning via build.chunkSizeWarningLimit.
file:///home/borza/mega/hacking/packages/js/qft/.svelte-kit/output/server/entries/pages/index.svelte.js:2
import { vega } from "vega-embed";
         ^^^^
SyntaxError: Named export 'vega' not found. The requested module 'vega-embed' is a CommonJS module, which may not support all module.exports as named exports.
CommonJS modules can always be imported via the default export, for example using:

import pkg from 'vega-embed';
const { vega } = pkg;

    at ModuleJob._instantiate (node:internal/modules/esm/module_job:128:21)
    at async ModuleJob.run (node:internal/modules/esm/module_job:194:5)
    at async Promise.all (index 0)
    at async ESMLoader.import (node:internal/modules/esm/loader:385:24)
    at async Promise.all (index 1)
    at async respond$1 (file:///home/borza/mega/hacking/packages/js/qft/.svelte-kit/output/server/index.js:1751:13)
    at async resolve (file:///home/borza/mega/hacking/packages/js/qft/.svelte-kit/output/server/index.js:2140:105)
    at async Object.handle (file:///home/borza/mega/hacking/packages/js/qft/.svelte-kit/output/server/chunks/hooks-93fa095d.js:5:20)
    at async respond (file:///home/borza/mega/hacking/packages/js/qft/.svelte-kit/output/server/index.js:2095:22)
    at async visit (file:///home/borza/mega/hacking/packages/js/qft/node_modules/@sveltejs/kit/dist/vite.js:1121:20)
[vite-plugin-svelte-kit] 500 /
> 500 /
    at file:///home/borza/mega/hacking/packages/js/qft/node_modules/@sveltejs/kit/dist/vite.js:1020:11
    at save (file:///home/borza/mega/hacking/packages/js/qft/node_modules/@sveltejs/kit/dist/vite.js:1239:4)
    at visit (file:///home/borza/mega/hacking/packages/js/qft/node_modules/@sveltejs/kit/dist/vite.js:1130:3)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
```

### System Info

```shell
System:
    OS: Linux 5.15 Ubuntu 22.04 LTS 22.04 LTS (Jammy Jellyfish)
    CPU: (20) x64 12th Gen Intel(R) Core(TM) i7-12700H
    Memory: 18.30 GB / 31.08 GB
    Container: Yes
    Shell: 5.1.16 - /bin/bash
  Binaries:
    Node: 16.15.1 - ~/.nvm/versions/node/v16.15.1/bin/node
    npm: 8.11.0 - ~/.nvm/versions/node/v16.15.1/bin/npm
  npmPackages:
    @sveltejs/adapter-auto: next => 1.0.0-next.52 
    @sveltejs/kit: next => 1.0.0-next.355 
    svelte: ^3.46.0 => 3.48.0
```

### Severity

blocking all usage of SvelteKit

### Additional Information

The issue might be with svelte-vega, but I cannot really tell. Any guidance is welcome, I have been looking for a long time in obscure issues which have been closed for reasons not immediately celar, looked into all the phrases I couldn't understand here: https://github.com/sveltejs/kit/blob/master/documentation/faq/70-packages.md but still can't tell how to deploy a simple app to github pages.

**Comment by benmccann** [comment]
`svelte-vega` looks to be improperly packaged. It has a UMD file in `main` which is invalid. Node.js will try to load whatever is in `main` and can't load UMD files. Please file a bug against `svelte-vega` asking the author to put a CJS or ESM (if they also put `"type": "module") in the `main` field. You may also share https://kit.svelte.dev/faq#packages with them as they are currently violating bullet three
