### ISSUE TITLE
Slightly normalize requests before passing them to Undici

### ISSUE THREAD

**Issue by Conduitry** [sveltejs/kit#5380]
### Describe the problem

The global `fetch` that now uses Undici under the hood is now a lot more finicky in a few areas than it previously was when using node-fetch. A partial list, which can be expanded when we run into more things:

- `fetch(..., { method: 'patch' })` does not work. Undici needs `PATCH`, although other verbs work in lowercase. This is, I understand, in compliance with some spec, but it's annoying
- `fetch(event.request)` in the `handle` hook to proxy a given incoming request also does not work because of the presence of the `connection` header in the request. This needs to be manually removed (`event.request.headers.delete('connection')`) before calling `fetch`.

### Describe the proposed solution

Lobby Undici to be less anal about the spec.

When that inevitably fails, normalize the values passed to the global `fetch`, preferably without mutating user input. This will admittedly get a bit hairy when trying to support `fetch(url, opts)` and `fetch(opts)` and `fetch(Request)`.

### Alternatives considered

Documentation, I guess.

### Importance

would make my life easier

**Comment by Rich-Harris** [comment]
Given that Undici is identical to Node 18's built-in `fetch`, and is also used in other environments, I think we'd ultimately be doing our users a disservice if we did this:

```js
globalThis.fetch = (info, init) => undici.fetch(normalise_info(info), normalise_init(init));
```

_Maybe_ there's some merit in throwing an error if `method` is lowercase, etc, but ultimately I think people need to learn to do things the spec-compliant way, however annoying that is. (FWIW, `fetch(url, { method: 'patch' })` fails with a 400 error in the browser, so `node-fetch` really _is_ being too permissive.)

I do agree with deleting the `connection` header though

**Comment by Rich-Harris** [comment]
Oh, I guess I thought this was happening because of a `fetch` inside a `load`. What's your use case for `fetch(event.request)`? Maybe that's something that should be on the user too

**Comment by Conduitry** [comment]
It is happening because of a `fetch` in `load`, but this is getting mapped back to `handle` during SSR.

I have APIs on the same domain as is serving the frontend that are getting served by something outside of the SvelteKit app. There's something sitting between the browser and the application that ensures that appropriate URLs are mapped to the frontend and others are mapped to the APIs. This needs to work during SSR as well.

I want to be able to run `fetch('/api/whatever')` in `load`s. On the browser, this works fine. On the server, I need to conditionally (say, if `event.url.pathname.startsWith('/api/')`) proxy this in `handle` with `fetch(event.request)` so that these requests go out to the real internet instead of trying to handle them with SvelteKit. As of the switch to Undici, I also need to first `event.request.headers.delete('connection')` or else Undici complains.

**Comment by Conduitry** [comment]
Oh! I guess you're saying that stripping out the `connection` header can happen when `load`'s `fetch` is deciding which headers to copy into the constructed `request` that gets passed to `handle` during SSR. Whoops. Yeah that makes sense to me.

**Comment by tarngerine** [comment]
Gah i spent an hour debugging why my patch requests were breaking — the uppercase helped one of them! Thank you!

...but i'm running into another issue, which i am guessing is also undici-related because it broke after updating from 360-372, where passing a Blob as a body results in some sort of parsing/serialization error (it looks like body gets stringified?). any hints here would be super helpful! Thanks

```js
const formWithImage = new FormData();
formWithImage.append('avatar', form.get('avatar')!);
const blob = formDataToBlob(formWithImage);
const avatarApi = api({
  method: 'PATCH',
  resource: `v1/users/avatar`,
  contentType: blob.type,
  headers: {
    ...request.headers
  },
  body: blob,
  token: locals.access_token
})
```

```
Blob: Expected [object Blob] to be an instance of Blob.
TypeError: Blob: Expected [object Blob] to be an instance of Blob.
    at Object.webidl.errors.exception (file:///Users/tarng/Code/_clients/maitsu/maitsu-svelte/node_modules/@sveltejs/kit/dist/node/polyfills.js:817:10)
    at Object.Blob (file:///Users/tarng/Code/_clients/maitsu/maitsu-svelte/node_modules/@sveltejs/kit/dist/node/polyfills.js:1081:22)
    at Object.webidl.converters.XMLHttpRequestBodyInit (file:///Users/tarng/Code/_clients/maitsu/maitsu-svelte/node_modules/@sveltejs/kit/dist/node/polyfills.js:8599:31)
    at webidl.converters.BodyInit (file:///Users/tarng/Code/_clients/maitsu/maitsu-svelte/node_modules/@sveltejs/kit/dist/node/polyfills.js:8633:29)
    at file:///Users/tarng/Code/_clients/maitsu/maitsu-svelte/node_modules/@sveltejs/kit/dist/node/polyfills.js:1164:13
    at Object.RequestInit (file:///Users/tarng/Code/_clients/maitsu/maitsu-svelte/node_modules/@sveltejs/kit/dist/node/polyfills.js:1138:18)
    at new Request (file:///Users/tarng/Code/_clients/maitsu/maitsu-svelte/node_modules/@sveltejs/kit/dist/node/polyfills.js:8718:31)
    at Agent$1.fetch (file:///Users/tarng/Code/_clients/maitsu/maitsu-svelte/node_modules/@sveltejs/kit/dist/node/polyfills.js:10279:22)
    at fetch (file:///Users/tarng/Code/_clients/maitsu/maitsu-svelte/node_modules/@sveltejs/kit/dist/node/polyfills.js:12199:22)
    at Module.api (/Users/tarng/Code/_clients/maitsu/maitsu-svelte/src/lib/api.ts:25:9)
```

**Comment by Rich-Harris** [comment]
for posterity, the above issue was resolved here: https://github.com/sveltejs/kit/issues/5550

**Comment by Conduitry** [comment]
I think we can close this now. The parts that seemed in-scope and desirable have been done. If other things arise, they should be tracked with their own issue, rather than being added to this one.
