### ISSUE TITLE
sveltekit 359  run dev and build fails, test with vitest only on svelte components. 

### ISSUE THREAD

**Issue by ar4hc** [sveltejs/kit#5389]
### Describe the bug

using 359, after doing the suggested changes from sveltekit to vite in package.json i get some  strange behaviour.

i'm sure its some misconfiguration on my parts but i have no clue where to start looking..

if i run `pnpm run dev` i get this

```
  vite v2.9.13 dev server running at:

  > Local:    http://::1,127.0.0.1:3000/
  > Network:  http://192.168.178.42:3000/

  ready in 168ms.
```

and the server  respond to any request with a 404, no log output  at all..

and `pnpm run build` gives:

```
> vite build

vite v2.9.13 building for production...
✓ 0 modules transformed.
Could not resolve entry module (index.html).
error during build:
Error: Could not resolve entry module (index.html).
    at error (/foo.../node_modules/.pnpm/rollup@2.75.7/node_modules/rollup/dist/shared/rollup.js:198:30)
    at ModuleLoader.loadEntryModule (/foo.../node_modules/.pnpm/rollup@2.75.7/node_modules/rollup/dist/shared/rollup.js:22527:20)
```

running tests works for some (simple?) tests and fails for svelte components with errors like

```
 FAIL  src/routes/about.test.js [ src/routes/about.test.js ]
Error: Failed to parse source for import analysis because the content contains invalid JS syntax. If you are using JSX, make sure to name the file with the .jsx or .tsx extension.
 ❯ formatError node_modules/.pnpm/vite@2.9.13/node_modules/vite/dist/node/chunks/dep-80fe9c6b.js:39055:46
 ❯ TransformContext.error node_modules/.pnpm/vite@2.9.13/node_modules/vite/dist/node/chunks/dep-80fe9c6b.js:39051:19
 ❯ TransformContext.transform node_modules/.pnpm/vite@2.9.13/node_modules/vite/dist/node/chunks/dep-80fe9c6b.js:58269:22
 ❯ Object.transform node_modules/.pnpm/vite@2.9.13/node_modules/vite/dist/node/chunks/dep-80fe9c6b.js:39292:30
 ❯ doTransform node_modules/.pnpm/vite@2.9.13/node_modules/vite/dist/node/chunks/dep-80fe9c6b.js:50012:29
```

i'm using pnpm, see below for details.

and  `svelte.config.js`:

```js
import node from '@sveltejs/adapter-node';
import preprocess from 'svelte-preprocess';
import sveltePreprocess from 'svelte-preprocess';
import tailwind from 'tailwindcss';
import autoprefixer from 'autoprefixer';

/** @type {import('@sveltejs/kit').Config} */
const config = {
	// prerender: { enabled: false },
	preprocess: [
		sveltePreprocess(),
		preprocess({
			postcss: {
				plugins: [tailwind, autoprefixer],
			},
		}),
	],
	kit: {
		alias: {
			$components: 'src/components',
			$utils: 'src/utils',
		},
		adapter: node(),
		// hydrate the <div id="svelte"> element in src/app.html
		// target: '#svelte',
		vite: {
			server: { proxy: {} },
		},
	},
};

export default config;
```

i'm using tailwind for CSS...

and the new vite config in `svelte.config.js` is:

```js

import { sveltekit } from '@sveltejs/kit/vite';

// const production = process.env.NODE_ENV === 'production';

/** @type {import('vite').UserConfig} */
const config = {
  define: {
    // Eliminate in-source test code
    'import.meta.vitest': 'undefined',
  },
  server: { proxy: {} },
  test: {
    // jest like globals
    globals: true,
    environment: 'jsdom',
    setupFiles: ['src/setupTests.js'],
    // in-source testing
    includeSource: ['src/**/*.{js,ts,svelte}'],
  },
  plugins: [sveltekit()]
};

export default config;
```

as i'm using vitest too.

Any clues what went wrong...?

### Reproduction

run "pnpm run dev" or "pnm run build" or "pnpm run test", with the above config...

### System Info

```shell
System:
    OS: macOS 11.6.7
    CPU: (12) x64 Intel(R) Core(TM) i9-8950HK CPU @ 2.90GHz
    Memory: 493.58 MB / 32.00 GB
    Shell: 5.9 - /usr/local/bin/zsh
  Binaries:
    Node: 18.4.0 - /usr/local/bin/node
    Yarn: 3.2.1 - /usr/local/bin/yarn
    npm: 8.12.1 - /usr/local/bin/npm
    Watchman: 2022.07.04.00 - /usr/local/bin/watchman
  Browsers:
    Firefox: 102.0
    Safari: 15.5

pnpm@7.5.0 from corepack

  v8: '10.2.154.4-node.8',
```

### Severity

annoyance

**Comment by wickning1** [comment]
I had a similarly dumb problem where I didn't copy vite.config.js in my Dockerfile and got the same error. This ticket helped me figure it out.
