### ISSUE TITLE
TypeError: Cannot read properties of undefined when running build command

### ISSUE THREAD

**Issue by hiromaily** [sveltejs/kit#5418]
### Describe the bug

command `vite build` doesn't work by the following error
```
TypeError: Cannot read properties of undefined (reading 'Long')
    at file:///Users/me/app/.svelte-kit/output/server/entries/pages/index.svelte.js:304:14
    at ModuleJob.run (node:internal/modules/esm/module_job:185:25)
    at async Promise.all (index 0)
    at async ESMLoader.import (node:internal/modules/esm/loader:281:24)
    at async Promise.all (index 1)
    at async respond$1 (file:///Users/me/app/.svelte-kit/output/server/index.js:1754:13)
    at async resolve (file:///Users/me/app/.svelte-kit/output/server/index.js:2148:105)
    at async respond (file:///Users/me/app/.svelte-kit/output/server/index.js:2103:22)
    at async visit (file:///Users/me/app/node_modules/@sveltejs/kit/dist/vite.js:1193:20)
```
this is caused by this code
```
if (_m0.util.Long !== Long) {
```
util of _m0 is undefined somehow.

import path of _m0 is 
```
import * as _m0 from "protobufjs/minimal.js";
```

However, `vite dev` works.

And I'm curious `import` run twice in generated file index.svelte.js
```
import * as _m0 from "protobufjs/minimal.js";
import _m0__default from "protobufjs/minimal.js";
```

### package.json
```package.json
{
	"name": "app3",
	"version": "0.0.1",
	"scripts": {
		"dev": "vite dev",
		"build": "vite build",
		"package": "svelte-kit package",
		"preview": "vite preview",
		"prepare": "svelte-kit sync",
		"check": "svelte-check --tsconfig ./tsconfig.json",
		"check:watch": "svelte-check --tsconfig ./tsconfig.json --watch",
		"lint": "prettier --check --plugin-search-dir=. . && eslint .",
		"format": "prettier --write --plugin-search-dir=. ."
	},
	"devDependencies": {
		"@sveltejs/adapter-auto": "next",
		"@sveltejs/kit": "next",
		"@typescript-eslint/eslint-plugin": "^5.27.0",
		"@typescript-eslint/parser": "^5.27.0",
		"eslint": "^8.16.0",
		"eslint-config-prettier": "^8.3.0",
		"eslint-plugin-svelte3": "^4.0.0",
		"prettier": "^2.6.2",
		"prettier-plugin-svelte": "^2.7.0",
		"svelte": "^3.48.0",
		"svelte-check": "^2.7.1",
		"svelte-preprocess": "^4.10.6",
		"tslib": "^2.3.1",
		"typescript": "^4.7.2",
		"vite": "^2.9.13"
	},
	"type": "module",
	"dependencies": {
		"@cosmjs/launchpad": "^0.27.1",
		"@cosmjs/stargate": "^0.28.10",
		"protobufjs": "^6.11.3",
		"secretjs": "^0.17.5"
	}
}
```

### Reproduction
visit this apps https://github.com/hiromaily/svelte-sample/tree/main/app
then, run the following command.
```
npm run build
```

`npm run dev` works without any problems.

### Logs

```shell
$ NODE_OPTIONS='--es-module-specifier-resolution=node' npm run build

TypeError: Cannot read properties of undefined (reading 'Long')
    at file:///Users/me/app/.svelte-kit/output/server/entries/pages/index.svelte.js:304:14
    at ModuleJob.run (node:internal/modules/esm/module_job:185:25)
    at async Promise.all (index 0)
    at async ESMLoader.import (node:internal/modules/esm/loader:281:24)
    at async Promise.all (index 1)
    at async respond$1 (file:///Users/me/app/.svelte-kit/output/server/index.js:1754:13)
    at async resolve (file:///Users/me/app/.svelte-kit/output/server/index.js:2148:105)
    at async respond (file:///Users/me/app/.svelte-kit/output/server/index.js:2103:22)
    at async visit (file:///Users/me/app/node_modules/@sveltejs/kit/dist/vite.js:1193:20)
[vite-plugin-svelte-kit] 500 /
```

### System Info

```shell
System:
    OS: macOS 12.3.1
    CPU: (8) x64 Intel(R) Core(TM) i7-1068NG7 CPU @ 2.30GHz
    Memory: 91.72 MB / 32.00 GB
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 16.13.0 - ~/.nodebrew/current/bin/node
    Yarn: 1.22.15 - ~/.nodebrew/current/bin/yarn
    npm: 8.9.0 - ~/.nodebrew/current/bin/npm
  Browsers:
    Chrome: 103.0.5060.114
    Safari: 15.4
  npmPackages:
    svelte: ^3.48.0 => 3.48.0
```

### Severity

blocking all usage of SvelteKit

**Comment by gtm-nayan** [comment]
> Reproductions must be [short, self-contained and correct](http://sscce.org/) and **must not contain files or code that aren't relevant to the issue — please do NOT just paste a link to your project**.

**Comment by hiromaily** [comment]
this problem may be caused this issue
https://github.com/protobufjs/protobuf.js/issues/1673

**Comment by hiromaily** [comment]
I've already tried similar issue https://github.com/vitejs/vite/issues/8395
Then modified rollup version in package.json
```
	"overrides": {
		"rollup": "2.76.0"
	}
```
But it still doesn't work

**Comment by hiromaily** [comment]
Though, I've already mentioned in main topic,
And I'm curious `import` run twice in generated file index.svelte.js
```
import * as _m0 from "protobufjs/minimal.js";
import _m0__default from "protobufjs/minimal.js";
```
Somehow 2 imports run and first one causes error in this time and that style looks wroing for ESM

**Comment by bluwy** [comment]
I don't think this is a SvelteKit issue. I've replied over at https://github.com/vitejs/vite/issues/9018#issuecomment-1179692305

**Comment by hiromaily** [comment]
Thanks @bluwy
