### ISSUE TITLE
Error with fresh sveltekit app

### ISSUE THREAD

**Issue by junreyb** [sveltejs/kit#5495]
### Describe the bug

Just created a new sveltekit app and it's throwing an error right after running `npm run dev`:

```bash
Function called outside component initialization
Error: Function called outside component initialization
```

### Reproduction

- `npm create svelte my-app`
- `cd my-app`
- `npm install`
- `npm run dev -- --open`

### Logs

```shell
Function called outside component initialization
Error: Function called outside component initialization
    at get_current_component (/node_modules/svelte/internal/index.mjs:953:15)
    at Module.setContext (/node_modules/svelte/internal/index.mjs:985:5)
    at root.svelte:14:1
    at $$render (/node_modules/svelte/internal/index.mjs?v=70fc108d:1770:22)
    at Object.render (/node_modules/svelte/internal/index.mjs?v=70fc108d:1778:26)
    at render_response (file:///Users/jbeduya/code/playground/sveltekit/my-app/.svelte-kit/runtime/server/index.js:1383:27)
    at async respond$1 (file:///Users/jbeduya/code/playground/sveltekit/my-app/.svelte-kit/runtime/server/index.js:2996:4)
    at async resolve (file:///Users/jbeduya/code/playground/sveltekit/my-app/.svelte-kit/runtime/server/index.js:3346:11)
    at async respond (file:///Users/jbeduya/code/playground/sveltekit/my-app/.svelte-kit/runtime/server/index.js:3290:20)
    at async file:///Users/jbeduya/code/playground/sveltekit/my-app/node_modules/@sveltejs/kit/dist/vite.js:2324:22

Function called outside component initialization
Error: Function called outside component initialization
    at get_current_component (/node_modules/svelte/internal/index.mjs:953:15)
    at Module.setContext (/node_modules/svelte/internal/index.mjs:985:5)
    at root.svelte:14:1
    at $$render (/node_modules/svelte/internal/index.mjs?v=70fc108d:1770:22)
    at Object.render (/node_modules/svelte/internal/index.mjs?v=70fc108d:1778:26)
    at render_response (file:///Users/jbeduya/code/playground/sveltekit/my-app/.svelte-kit/runtime/server/index.js:1383:27)
    at async respond_with_error (file:///Users/jbeduya/code/playground/sveltekit/my-app/.svelte-kit/runtime/server/index.js:2758:10)
    at async respond$1 (file:///Users/jbeduya/code/playground/sveltekit/my-app/.svelte-kit/runtime/server/index.js:3013:4)
    at async resolve (file:///Users/jbeduya/code/playground/sveltekit/my-app/.svelte-kit/runtime/server/index.js:3346:11)
    at async respond (file:///Users/jbeduya/code/playground/sveltekit/my-app/.svelte-kit/runtime/server/index.js:3290:20)
```

### System Info

```shell
System:
    OS: macOS 12.4
    CPU: (8) arm64 Apple M1
    Memory: 84.08 MB / 16.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 16.15.1 - ~/.volta/tools/image/node/16.15.1/bin/node
    Yarn: 1.22.18 - ~/.volta/tools/image/yarn/1.22.18/bin/yarn
    npm: 8.11.0 - ~/.volta/tools/image/node/16.15.1/bin/npm
  Browsers:
    Brave Browser: 96.1.32.106
    Chrome: 103.0.5060.114
    Firefox: 98.0.1
    Safari: 15.5
  npmPackages:
    @sveltejs/adapter-auto: next => 1.0.0-next.57 
    @sveltejs/kit: next => 1.0.0-next.370 
    svelte: ^3.44.0 => 3.49.0 
    vite: ^2.9.13 => 2.9.14
```

### Severity

blocking all usage of SvelteKit

**Comment by graywolf336** [comment]
I can confirm, bumping `"@sveltejs/kit"` to the latest version just released fixes the issue. Thank you for the quick work!

**Comment by Conduitry** [comment]
Yup, looks good.
