### ISSUE TITLE
@sveltejs/kit and vite@3 broke .svelte file processing in packages

### ISSUE THREAD

**Issue by sserdyuk** [sveltejs/kit#5549]
### Describe the bug

We use the excellent @rgossiaux/svelte-heroicons package to render icons, and the recent change in Sveltekit and Vite broke the project. The page now fails to load with a 500 error and a `Unknown file extension ".svelte"` message. 

The last known working version of Sveltekit is "1.0.0-next.360" with Vite "2.9.13".

This might be related to https://github.com/sveltejs/kit/issues/5542

### Reproduction

Here's a an example of [the issue](https://stackblitz.com/edit/sveltejs-kit-template-default-mubpwk?file=src/routes/index.svelte)

### Logs

```shell
❯ npm run dev
$ vite dev

  VITE v3.0.0  ready in 1227 ms

  ➜  Local:   http://localhost:5173/
  ➜  Network: use --host to expose
Unknown file extension ".svelte" for /home/projects/sveltejs-kit-template-default-mubpwk/node_modules/@rgossiaux/svelte-heroicons/outline/AcademicCap/AcademicCap.svelte
TypeError [ERR_UNKNOWN_FILE_EXTENSION]: Unknown file extension ".svelte" for /home/projects/sveltejs-kit-template-default-mubpwk/node_modules/@rgossiaux/svelte-heroicons/outline/AcademicCap/AcademicCap.svelte
    at TypeError.get (https://sveltejs-kit-template-default-mubpwk.w.staticblitz.com/blitz.9dc2007b053e3e7ca4daf0ec1a74b5c3910935fe.js:6:292488)
    at instantiateModule (file:///home/projects/sveltejs-kit-template-default-mubpwk/node_modules/vite/dist/node/chunks/dep-561c5231.js:50345:15)
^C
```

### System Info

```shell
❯ npx envinfo --system --binaries --browsers --npmPackages "{svelte,@sveltejs/*,vite}"
success Install finished in 0.737s


  System:
    OS: Linux 5.0 undefined
    CPU: (4) x64 Intel(R) Core(TM) i9-9880H CPU @ 2.30GHz
    Memory: 0 Bytes / 0 Bytes
    Shell: 1.0 - /bin/jsh
  Binaries:
    Node: 16.14.2 - /usr/local/bin/node
    Yarn: 1.22.10 - /bin/yarn
    npm: 7.17.0 - /bin/npm
  npmPackages:
    @sveltejs/adapter-auto: next => 1.0.0-next.60 
    @sveltejs/kit: next => 1.0.0-next.377 
    svelte: ^3.46.0 => 3.49.0 
    vite: ^3.0.0 => 3.0.0
```

### Severity

blocking an upgrade

**Comment by ifiokjr** [comment]
@sserdyuk try [this](https://vitejs.dev/guide/migration.html#ssr-changes) as a temporary workaround in your `vite.config.js` file.

```diff
// vite.config.js
import { sveltekit } from '@sveltejs/kit/vite';
import { defineConfig } from 'vite';

export default defineConfig({
  plugins: [sveltekit()],
+  legacy: { buildSsrCjsExternalHeuristics: true },
});
```

**Comment by lmtr0** [comment]
I'm having the same issue, and here is another work around (if you have a component library like me):

before `svelte-kit dev` went out of use, I exported all my components from index.ts and I could import them like this:  
```
<script>
import {Btn, Dots, Skeleton, SkeletonBox} from "@higenku/theme"
</script>
```
now, i removed all the exports and to import something:
```
<script lang="ts">
import Btn from "@higenku/theme/src/Btn.svelte"
import Dots from "@higenku/theme/src/Dots.svelte"
import Skeleton from "@higenku/theme/src/loaders/Skeleton.svelte"
import SkeletonBox from "@higenku/theme/src/loaders/SkeletonBox.svelte"

</script>
```

the build error is the same

**Comment by sserdyuk** [comment]
> @sserdyuk try [this](https://vitejs.dev/guide/migration.html#ssr-changes) as a temporary workaround in your `vite.config.js` file.
> 
> ```diff
> // vite.config.js
> import { sveltekit } from '@sveltejs/kit/vite';
> import { defineConfig } from 'vite';
> 
> export default defineConfig({
>   plugins: [sveltekit()],
> +  legacy: { buildSsrCjsExternalHeuristics: true },
> });
> ```

Thank you. It does help.

**Comment by dominikg** [comment]
another workaround is to add  an ssr.noExternal entry for the problematic import that uses `/**` at the end.
 This is a bug in vite-3 and will be fixed.

```diff
// vite.config.js
import { sveltekit } from '@sveltejs/kit/vite';
import { defineConfig } from 'vite';
 
export default defineConfig({
  plugins: [sveltekit()],
+  ssr: { noExternal: ['@rgossiaux/svelte-heroicons/**'] }
});
```

**Comment by dominikg** [comment]
and here is a more generic workaround using a vite plugin to modify the ssr.noExternal configuration.
```js
import { sveltekit } from '@sveltejs/kit/vite';

/** @type {import('vite').UserConfig} */
const config = {
	plugins: [
		sveltekit(),
		// utility plugin to append `/**` to strings in ssr.noExternal
		{
			name: 'vite-plugin-patch-ssr-noexternal',
			enforce: 'post',
			config(cfg) {
				if (!cfg.ssr?.noExternal) return;
				cfg.ssr.noExternal = cfg.ssr.noExternal.map((x) =>
					typeof x !== 'string' || x.includes('*') ? x : `${x}${!x.endsWith('/') ? '/' : ''}**`
				);
			}
		}
	]
};

export default config;
```

**Comment by lmtr0** [comment]
It's merged

**Comment by dominikg** [comment]
yes, a vite release that includes the fix should be available in the next days. Until then you can continue to use one of the workarounds above or also something like pnpm patch to patch your local vite with that PR.

**Comment by bluwy** [comment]
The fix in Vite has been released in Vite 3.0.1. Upgrading to it should fix the issue.

**Comment by lmtr0** [comment]
I test it with vite 3.0.2 and got the same error:
```
VITE v3.0.2  ready in 238 ms

  ➜  Local:   http://localhost:3000/
  ➜  Network: use --host to expose
Unknown file extension ".svelte" for /home/me/repo/sdks/theme/@higenku/theme/src/footer/Footer.svelte
TypeError [ERR_UNKNOWN_FILE_EXTENSION]: Unknown file extension ".svelte" for /home/me/repo/sdks/theme/@higenku/theme/src/footer/Footer.svelte
    at new NodeError (node:internal/errors:388:5)
    at Object.getFileProtocolModuleFormat [as file:] (node:internal/modules/esm/get_format:80:11)
    at defaultGetFormat (node:internal/modules/esm/get_format:122:38)
    at defaultLoad (node:internal/modules/esm/load:21:20)
    at ESMLoader.load (node:internal/modules/esm/loader:431:26)
    at ESMLoader.moduleProvider (node:internal/modules/esm/loader:350:22)
    at new ModuleJob (node:internal/modules/esm/module_job:66:26)
    at #createModuleJob (node:internal/modules/esm/loader:369:17)
    at ESMLoader.getModuleJob (node:internal/modules/esm/loader:328:34)
    at async ModuleWrap.<anonymous> (node:internal/modules/esm/module_job:82:21)
   ```
   
   sample code: <br>
   index.ts in the library:
```js
import Footer from "./footer/Footer.svelte";
export {
    Footer,
};
```

tests/src/routes/__layout.svelte:
```js
<script lang="ts">
import {Footer} from "@higenku/theme"
</script>
```

![image](https://user-images.githubusercontent.com/57605930/179559975-381f03a8-a1e5-4e72-8414-e247f973d832.png)

Source code: https://gitlab.com/higenku/sdks/theme currently on the `wip` branch

**Comment by lmtr0** [comment]
I tried this:
```js
// vite.config.js
import { sveltekit } from '@sveltejs/kit/vite';

/** @type {import('vite').UserConfig} */
const config = {
    plugins: [sveltekit(),
        {
			name: 'vite-plugin-patch-ssr-noexternal',
			enforce: 'post',
			config(cfg) {
				if (!cfg.ssr?.noExternal) return;
				cfg.ssr.noExternal = cfg.ssr.noExternal.map((x) =>
					typeof x !== 'string' || x.includes('*') || x.endsWith('/**') ? x : `${x}${!x.endsWith('/') ? '/' : ''}**`
				);
			}
		}
    ],
    server: {
        port: 3000,
    },
    deps: {
        inline: ['@higenku/theme'],
    }
};

export default config;
```
but even this did not work
