### ISSUE TITLE
Undici throwing error on blob

### ISSUE THREAD

**Issue by tarngerine** [sveltejs/kit#5550]
### Describe the bug

After updating from 350->372, one of my endpoints broke. I traced it to `undici`, which isn't recognizing the Blob I'm fetching. This was not an issue with `node-fetch`.

It's quite possible that there is a smarter way to do what I'm trying to do (split out a part of a form submission, i.e. an image upload, and send it to a separate endpoint to upload from the rest of the form), and if so, I'd love any guidance.

### Reproduction

https://github.com/tarngerine/blob-undici

https://stackblitz.com/github/tarngerine/blob-undici?file=src/routes/index.ts

### Logs

```shell
500

Blob: Expected [object Blob] to be an instance of Blob.
TypeError: Blob: Expected [object Blob] to be an instance of Blob.
    at Object.webidl.errors.exception (file:///Users/tarng/Code/blob-undici/node_modules/@sveltejs/kit/dist/node/polyfills.js:817:10)
    at Object.Blob (file:///Users/tarng/Code/blob-undici/node_modules/@sveltejs/kit/dist/node/polyfills.js:1081:22)
    at Object.webidl.converters.XMLHttpRequestBodyInit (file:///Users/tarng/Code/blob-undici/node_modules/@sveltejs/kit/dist/node/polyfills.js:8599:31)
    at webidl.converters.BodyInit (file:///Users/tarng/Code/blob-undici/node_modules/@sveltejs/kit/dist/node/polyfills.js:8633:29)
    at file:///Users/tarng/Code/blob-undici/node_modules/@sveltejs/kit/dist/node/polyfills.js:1164:13
    at Object.RequestInit (file:///Users/tarng/Code/blob-undici/node_modules/@sveltejs/kit/dist/node/polyfills.js:1138:18)
    at new Request (file:///Users/tarng/Code/blob-undici/node_modules/@sveltejs/kit/dist/node/polyfills.js:8718:31)
    at Agent$1.fetch (file:///Users/tarng/Code/blob-undici/node_modules/@sveltejs/kit/dist/node/polyfills.js:10279:22)
    at fetch (file:///Users/tarng/Code/blob-undici/node_modules/@sveltejs/kit/dist/node/polyfills.js:12202:22)
    at patch (/Users/tarng/Code/blob-undici/src/routes/index.ts:18:24)
```

### System Info

```shell
System:
    OS: macOS 12.4
    CPU: (10) arm64 Apple M1 Pro
    Memory: 357.05 MB / 32.00 GB
    Shell: 3.2.2 - /usr/local/bin/fish
  Binaries:
    Node: 16.14.2 - /usr/local/bin/node
    Yarn: 1.22.18 - /usr/local/bin/yarn
    npm: 8.5.0 - /usr/local/bin/npm
  Browsers:
    Brave Browser: 102.1.39.111
    Firefox: 94.0.2
    Safari: 15.5
  npmPackages:
    @sveltejs/adapter-auto: next => 1.0.0-next.60 
    @sveltejs/kit: next => 1.0.0-next.376 
    svelte: ^3.44.0 => 3.49.0 
    vite: ^3.0.0 => 3.0.0
```

### Severity

blocking an upgrade

### Additional Information

The error `Blob: Expected [object Blob] to be an instance of Blob.` is from https://github.com/nodejs/undici/blob/aa8782cfcc24fe116cf27c34e65a057fbcbac3ba/lib/fetch/webidl.js#L285

**Comment by Rich-Harris** [comment]
It turns out you were relying on `formdata-polyfill` happening to use the same `Blob` implementation as `node-fetch`, namely `fetch-blob`. Undici uses `require('node:buffer').Blob` instead.

I thought you might be able to coerce your blob like so...

```diff
+import { Blob } from 'node:buffer';

// ...

-const blob = formDataToBlob(formWithImage);
+let blob = formDataToBlob(formWithImage);
const contentTypeWithBoundary = blob.type;

+blob = new Blob([await blob.arrayBuffer()], { type: blob.type });
```

...though that doesn't seem to completely solve the issue. Regardless, you'll need to use the built-in `buffer.Blob` rather than the `fetch-blob` one.

Unrelated to the issue at hand, but in your repro the `fetch` that immediately follows it will fail because server-side fetches must be absolute:

```diff
-export const PATCH: RequestHandler = async ({ request }) => {
+export const PATCH: RequestHandler = async ({ url, request }) => {

// ...

-const response = await fetch('/api/file', {
+const response = await fetch(new URL('/api/file', url).href, {
```

**Comment by tarngerine** [comment]
thanks, turns out https://github.com/jimmywarting/FormData/blob/5ddea9e0de2fc5e246ab1b2f9d404dee0c319c02/formdata-to-blob.js accepts a custom Blob class, so passing `import {Blob} from 'buffer'` into that fixes this

thank you for the fast response, really appreciate it!
