### ISSUE TITLE
Build fails with `Vite@3` and `@sveltejs/kit` when dynamic importing JSON files

### ISSUE THREAD

**Issue by raduab** [sveltejs/kit#5593]
### Describe the bug

The build fails with `Vite@3.0.1` and `@sveltejs/kit@1.0.0-next.377`. This is the build error I get:

```shell
error during build:
Error: Cannot split a chunk that has already been edited (27:147 – "{
  const locale = await __variableDynamicImportRuntimeHelper(
    Object.assign({
      '../../static/locale/en-GB.json': () =>
        __vitePreload(
          () => import('../../static/locale/en-GB.json'),
          __VITE_IS_MODERN__ ? '__VITE_PRELOAD__' : void 0,
        ),
    }),
    `../../static/locale/${language}.json`,
  )
}")
    at MagicString._splitChunk (file:///.../node_modules/rollup/dist/es/shared/rollup.js:1033:10)
    at MagicString._split (file:///.../node_modules/rollup/dist/es/shared/rollup.js:1023:43)
    at MagicString.overwrite (file:///.../node_modules/rollup/dist/es/shared/rollup.js:806:8)
    at ImportExpression.renderFinalResolution (file:///.../node_modules/rollup/dist/es/shared/rollup.js:10250:14)
    at Chunk.finaliseDynamicImports (file:///.../node_modules/rollup/dist/es/shared/rollup.js:15009:22)
    at Chunk.render (file:///.../node_modules/rollup/dist/es/shared/rollup.js:14808:14)
    at file:///.../node_modules/rollup/dist/es/shared/rollup.js:15988:52
    at Array.map (<anonymous>)
    at Bundle.addFinalizedChunksToBundle (file:///.../node_modules/rollup/dist/es/shared/rollup.js:15986:34)
    at Bundle.generate (file:///.../node_modules/rollup/dist/es/shared/rollup.js:15966:24)
```

This appears to be related to dynamically importing a JSON file when server-rendering, which worked in previous versions. 

### Reproduction

Without changing any code, when upgrading Vite from 2.9 to 3.0.1 and SvelteKit from 370 to 377 the build breaks.

### System Info

```shell
System:
    OS: Linux 5.18 Arch Linux
    CPU: (8) x64 11th Gen Intel(R) Core(TM) i7-11370H @ 3.30GHz
    Memory: 5.41 GB / 31.14 GB
    Container: Yes
    Shell: 5.1.16 - /bin/bash
  Binaries:
    Node: 18.5.0 - /usr/bin/node
    Yarn: 1.22.19 - /usr/bin/yarn
    npm: 8.13.2 - /usr/bin/npm
  Browsers:
    Chromium: 103.0.5060.114
    Firefox: 102.0.1
  npmPackages:
    @sveltejs/adapter-cloudflare: 1.0.0-next.29 => 1.0.0-next.29 
    @sveltejs/kit: 1.0.0-next.377 => 1.0.0-next.377 
    svelte: ^3.49.0 => 3.49.0 
    vite: ^3.0.1 => 3.0.1
```

### Severity

blocking an upgrade

### Additional Information

The build fails with both `adapter-cloudflare` and `adapter-node` at latest versions

**Comment by raduab** [comment]
You are right! Thank you. I'll close this now.
