### ISSUE TITLE
SvelteKit crashes (500) when using slot props on an iterated slot in a component with multiple slots

### ISSUE THREAD

**Issue by tarngerine** [sveltejs/kit#5751]
### Describe the bug

Given a `<Component>` with a default `<slot />` and a named `<slot name="name" />`:

- if the default `<slot />` is inside an iterator `{#each items as item}<slot {item} />{/each}` and has a slot prop
- and the consumer of the `<Component>` uses both default and named slots, as well as the slot prop
- the server will crash

### Reproduction

See: https://stackblitz.com/github/tarngerine/slot-prop-undefined?file=src/routes/Feed.svelte

- load page
- expect: no 500
- actual: 500s: `item is not defined`

### Logs

```shell
item is not defined
ReferenceError: item is not defined
    at eval (/src/routes/Feed.svelte:19:33)
    at Object.$$render (/node_modules/svelte/internal/index.mjs:1770:22)
    at eval (/src/routes/index.svelte:13:92)
    at Object.$$render (/node_modules/svelte/internal/index.mjs:1770:22)
    at Object.default (root.svelte:43:39)
    at eval (/.svelte-kit/runtime/components/layout.svelte:8:41)
    at Object.$$render (/node_modules/svelte/internal/index.mjs:1770:22)
    at root.svelte:37:37
    at $$render (/node_modules/svelte/internal/index.mjs:1770:22)
    at Object.render (/node_modules/svelte/internal/index.mjs:1778:26)
```

### System Info

```shell
System:
    OS: macOS 12.4
    CPU: (10) arm64 Apple M1 Pro
    Memory: 597.69 MB / 32.00 GB
    Shell: 3.2.2 - /usr/local/bin/fish
  Binaries:
    Node: 16.14.2 - /usr/local/bin/node
    Yarn: 1.22.18 - /usr/local/bin/yarn
    npm: 8.5.0 - /usr/local/bin/npm
  Browsers:
    Brave Browser: 103.1.41.100
    Firefox: 94.0.2
    Safari: 15.5
  npmPackages:
    @sveltejs/adapter-auto: next => 1.0.0-next.64 
    @sveltejs/kit: next => 1.0.0-next.396 
    svelte: ^3.44.0 => 3.49.0 
    vite: ^3.0.0 => 3.0.3
```

### Severity

serious, but I can work around it

### Additional Information

I've included in the demo repo some workarounds that "fix" the bug:

1. do not used default slot, make all slots named
2. only use a single default slot

**Comment by benmccann** [comment]
The sourcemaps seem screwed up in dev mode here

If you run it in preview mode you see the error is at:
```
${slots.footer ? slots.footer({ item }) : ``}`
```

But there's nowhere that `item` is defined. This looks like a bug in the Svelte compiler, so I'm going to transfer it to that repo
