### ISSUE TITLE
hmr error with svelte.config.ts

### ISSUE THREAD

**Issue by skht777** [sveltejs/kit#5762]
### Describe the bug

hmr error occured when I use svelte.config.ts instead of svelte.config.js
<img width="708" alt="スクリーンショット 2022-07-30 23 10 18" src="https://user-images.githubusercontent.com/7084281/181918204-7678bcf2-9a33-4ae7-bf16-d7183450c9ff.png">

### Reproduction

https://stackblitz.com/edit/sveltejs-kit-template-default-xblytq?file=src/app.html

### Logs

```shell
proxy.js:15 [HMR][Svelte] Unrecoverable HMR error in <Root>: next update will trigger a full reload
logError @ proxy.js:15
root.svelte:706 Uncaught (in promise) Error: options.hydrate only works if the component was compiled with the `hydratable: true` option
    at Object.claim [as l] (root.svelte:706:10)
    at init (chunk-ZQ7TCJTX.js?v=f40cf025:1728:34)
    at new Root (root.svelte:869:3)
    at createProxiedComponent (svelte-hooks.js:341:9)
    at new ProxyComponent (proxy.js:242:7)
    at new Proxy<Root> (proxy.js:349:11)
    at initialize (start.js:828:10)
    at Object._hydrate (start.js:1797:4)
    at async start (start.js:1834:3)
```

### System Info

```shell
System:
    OS: macOS 12.4
    CPU: (10) arm64 Apple M1 Pro
    Memory: 180.78 MB / 16.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 18.4.0 - ~/.asdf/installs/nodejs/18.4.0/bin/node
    npm: 8.12.1 - ~/.asdf/plugins/nodejs/shims/npm
  Browsers:
    Chrome: 103.0.5060.134
    Safari: 15.5
  npmPackages:
    @sveltejs/adapter-static: next => 1.0.0-next.38 
    @sveltejs/kit: next => 1.0.0-next.398 
    svelte: ^3.49.0 => 3.49.0 
    vite: ^3.0.4 => 3.0.4 

```

### Severity

serious, but I can work around it

**Comment by dominikg** [comment]
svelte.config.ts is not supported. Use svelte.config.js
