### ISSUE TITLE
After SvelteKit 1.0.0-next.397, build hangs without displaying errors

### ISSUE THREAD

**Issue by nstuyvesant** [sveltejs/kit#5786]
### Describe the bug

After upgrading to any version of SvelteKit after 1.0.0-next.397, when running `npm run build` (vite build), it gets to a specific point in the process then never completes. No error messages:
```bash
% npm run build

> shy-svelte@3.0.3 build
> vite build

vite v3.0.4 building for production...
✓ 1737 modules transformed.
```

I am using vite@3.0.4 and @sveltejs/adapter-node@1.0.0-next.85. The version of these packages appears to have no effect on the inability to complete the build.

### Reproduction

1. `git clone https://github.com/nstuyvesant/shy-svelte.git`
2. `cd shy-svelte`
3. Change version of @sveltejs/kit to 1.0.0-next.398 in package.json (or change to "latest")
4. `npm install`
5. `npx vite build` (or `npm run build`) - use first one if you don't want to include my post-build script (will reproduce issue easily)

This build will never complete (or throw an error).

Change the SvelteKit version back to 1.0.0-next.397 and retry. Build will complete without problems.

### Logs

```shell
% npm run build

> shy-svelte@3.0.3 build
> vite build

vite v3.0.4 building for production...
✓ 1737 modules transformed.
```

### System Info

```shell
System:
    OS: macOS 12.4
    CPU: (10) arm64 Apple M1 Pro
    Memory: 1.90 GB / 32.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 18.7.0 - /opt/homebrew/bin/node
    npm: 8.15.1 - /opt/homebrew/bin/npm
  Browsers:
    Chrome: 103.0.5060.134
    Firefox: 102.0.1
    Safari: 15.5
  npmPackages:
    @sveltejs/adapter-node: latest => 1.0.0-next.85 
    @sveltejs/kit: 1.0.0-next.397 => 1.0.0-next.397 
    svelte: ^3.49.0 => 3.49.0 
    vite: ^3.0.4 => 3.0.4
```

### Severity

blocking an upgrade

### Additional Information

Another person on Discord ran into this with their project as well. A change in 1.0.0-next.398 in combination with my project seems to be the cause.

**Comment by nstuyvesant** [comment]
OK, found the problem... I upgraded to SvelteKit 1.0.0-next.398 but did not remove
```
/// <reference types="@sveltejs/kit" />
```
from my app.d.ts file per the change from this PR... https://github.com/sveltejs/kit/pull/5745.

After removing it, the build completes without problems on 1.0.0-next.398+.

I would still argue this is a problem. An error should be generated rather than the build hanging.

**Comment by dummdidumm** [comment]
I'm very surprised that a duplicate reference to types makes this hang - wonder what's going on there. AFAIK vite doesn't even try to type-check, so why would it interfere with the build?

**Comment by nstuyvesant** [comment]
Actually - my mistake as I neglected to do an `npm update` so it was working with 1.0.0-next.397 (but not thereafter).

**Comment by benmccann** [comment]
Three changes in 398: https://github.com/sveltejs/kit/blob/master/packages/kit/CHANGELOG.md#100-next398

**Comment by tcc-sejohnson** [comment]
> Three changes in 398: https://github.com/sveltejs/kit/blob/master/packages/kit/CHANGELOG.md#100-next398

I'll try to take a look at this today. My bet is that the illegal module analysis may be entering a cyclical import and not breaking out like it should.

**Comment by nstuyvesant** [comment]
On discord, saw some comments about builds getting very long (went from 30 seconds to 15 minutes) after 1.0.0-next.397. Perhaps related?

**Comment by benmccann** [comment]
@tcc-sejohnson I think that is the cause. The build completes when I comment out the call to `prevent_illegal_rollup_imports` in `writeBundle`

**Comment by nstuyvesant** [comment]
Interesting. If I do `npx vite build --debug` with my project, I get some warnings about missing exports but those were never blocking before...
```bash
 vite:vite-plugin-svelte dependency helmet does not export package.json Error [ERR_PACKAGE_PATH_NOT_EXPORTED]: Package subpath './package.json' is not defined by "exports" in /Users/nates/dev/shy-svelte/node_modules/helmet/package.json
    at new NodeError (node:internal/errors:387:5)
    at throwExportsNotFound (node:internal/modules/esm/resolve:439:9)
    at packageExportsResolve (node:internal/modules/esm/resolve:718:3)
    at resolveExports (node:internal/modules/cjs/loader:493:36)
    at Module._findPath (node:internal/modules/cjs/loader:533:31)
    at Module._resolveFilename (node:internal/modules/cjs/loader:942:27)
    at Module._load (node:internal/modules/cjs/loader:804:27)
    at Module.require (node:internal/modules/cjs/loader:1022:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at resolveDependencyData (file:///Users/nates/dev/shy-svelte/node_modules/@sveltejs/vite-plugin-svelte/dist/index.js:620:17) {
  code: 'ERR_PACKAGE_PATH_NOT_EXPORTED'
} +2ms
  vite:vite-plugin-svelte dependency d3 does not export package.json Error [ERR_PACKAGE_PATH_NOT_EXPORTED]: Package subpath './package.json' is not defined by "exports" in /Users/nates/dev/shy-svelte/node_modules/d3/package.json
    at new NodeError (node:internal/errors:387:5)
    at throwExportsNotFound (node:internal/modules/esm/resolve:439:9)
    at packageExportsResolve (node:internal/modules/esm/resolve:718:3)
    at resolveExports (node:internal/modules/cjs/loader:493:36)
    at Module._findPath (node:internal/modules/cjs/loader:533:31)
    at Module._resolveFilename (node:internal/modules/cjs/loader:942:27)
    at Module._load (node:internal/modules/cjs/loader:804:27)
    at Module.require (node:internal/modules/cjs/loader:1022:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at resolveDependencyData (file:///Users/nates/dev/shy-svelte/node_modules/@sveltejs/vite-plugin-svelte/dist/index.js:620:17) {
  code: 'ERR_PACKAGE_PATH_NOT_EXPORTED'
} +6ms
  vite:vite-plugin-svelte dependency sass does not export package.json Error [ERR_PACKAGE_PATH_NOT_EXPORTED]: Package subpath './package.json' is not defined by "exports" in /Users/nates/dev/shy-svelte/node_modules/sass/package.json
    at new NodeError (node:internal/errors:387:5)
    at throwExportsNotFound (node:internal/modules/esm/resolve:439:9)
    at packageExportsResolve (node:internal/modules/esm/resolve:718:3)
    at resolveExports (node:internal/modules/cjs/loader:493:36)
    at Module._findPath (node:internal/modules/cjs/loader:533:31)
    at Module._resolveFilename (node:internal/modules/cjs/loader:942:27)
    at Module._load (node:internal/modules/cjs/loader:804:27)
    at Module.require (node:internal/modules/cjs/loader:1022:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at resolveDependencyData (file:///Users/nates/dev/shy-svelte/node_modules/@sveltejs/vite-plugin-svelte/dist/index.js:620:17) {
  code: 'ERR_PACKAGE_PATH_NOT_EXPORTED'
} +2ms
```

**Comment by jiyosub** [comment]
I am seeing this too, but it's not hanging, just amazingly slow.  For me, findSvelteDependencies takes around 15 minutes.  Please find attached output of my build process.  Line 1018 takes ~18 minutes.
[build.out.txt](https://github.com/sveltejs/kit/files/9246085/build.out.txt)

If if I downgrade to 1.0.0-next.397, my build is fine.

**Comment by nstuyvesant** [comment]
@jiyosub - Was looking at your build.out.txt - there is a private key in it so you should probably remove the file from your comment. I will delete what I just downloaded and wash eyes out ;-)

**Comment by jiyosub** [comment]
Thanks.  Fixed that and rotated those keys.

**Comment by jiyosub** [comment]
> On discord, saw some comments about builds getting very long (went from 30 seconds to 15 minutes) after 1.0.0-next.397. Perhaps related?

That was mine.

**Comment by nstuyvesant** [comment]
Thanks! My build just completed with 1.0.0-next.402

**Comment by helmar81** [comment]
Having similar issue:
error during build:
Error: ENOTEMPTY: directory not empty, rmdir '\\?\C:\Users\User\my-CV\.svelte-kit\output\server\chunks'
