### ISSUE TITLE
Not able to run npm run test for playwright after installing npx svelte-add@latest tailwindcss

### ISSUE THREAD

**Issue by shinokada** [sveltejs/kit#5842]
### Describe the bug

Freshly installed SvelteKit with TailwindCSS, Playwright, ESlint, Prettier is not able to run `npm run test`:

```
❯ npm run test

> flowbite-svelte-blocks-2@0.0.1 test
> playwright test

(node:71423) ExperimentalWarning: --experimental-loader is an experimental feature. This feature could change at any time
(Use `node --trace-warnings ...` to show where the warning was created)

Running 1 test using 1 worker

[WebServer] (node:71427) ExperimentalWarning: --experimental-loader is an experimental feature. This feature could change at any time
(Use `node --trace-warnings ...` to show where the warning was created)
[WebServer] (node:71428) ExperimentalWarning: --experimental-loader is an experimental feature. This feature could change at any time
(Use `node --trace-warnings ...` to show where the warning was created)
[WebServer] (node:71428) ExperimentalWarning: stream/web is an experimental feature. This feature could change at any time
[WebServer] [vite:css] Failed to load PostCSS config (searchPath: /Users/shinichiokada/Svelte/Flowbite-svelte/flowbite-svelte-blocks-2): [ReferenceError] require is not defined in ES module scope, you can use import instead
ReferenceError: require is not defined in ES module scope, you can use import instead
    at file:///Users/shinichiokada/Svelte/Flowbite-svelte/flowbite-svelte-blocks-2/postcss.config.cjs:1:21
    at ModuleJob.run (node:internal/modules/esm/module_job:185:25)
    at async Promise.all (index 0)
    at ESMLoader.import (node:internal/modules/esm/loader:281:24)
    at importDefault (file:///Users/shinichiokada/Svelte/Flowbite-svelte/flowbite-svelte-blocks-2/node_modules/.pnpm/vite@3.0.4/node_modules/vite/dist/node/chunks/dep-71eb12cb.js:25930:18)
    at Object.search (file:///Users/shinichiokada/Svelte/Flowbite-svelte/flowbite-svelte-blocks-2/node_modules/.pnpm/vite@3.0.4/node_modules/vite/dist/node/chunks/dep-71eb12cb.js:18367:38)
    at resolvePostcssConfig (file:///Users/shinichiokada/Svelte/Flowbite-svelte/flowbite-svelte-blocks-2/node_modules/.pnpm/vite@3.0.4/node_modules/vite/dist/node/chunks/dep-71eb12cb.js:42395:22)
    at compileCSS (file:///Users/shinichiokada/Svelte/Flowbite-svelte/flowbite-svelte-blocks-2/node_modules/.pnpm/vite@3.0.4/node_modules/vite/dist/node/chunks/dep-71eb12cb.js:42163:27)
    at Object.transform (file:///Users/shinichiokada/Svelte/Flowbite-svelte/flowbite-svelte-blocks-2/node_modules/.pnpm/vite@3.0.4/node_modules/vite/dist/node/chunks/dep-71eb12cb.js:41786:55)
    at transform (file:///Users/shinichiokada/Svelte/Flowbite-svelte/flowbite-svelte-blocks-2/node_modules/.pnpm/rollup@2.77.2/node_modules/rollup/dist/es/shared/rollup.js:21911:16)
    at ModuleLoader.addModuleSource (file:///Users/shinichiokada/Svelte/Flowbite-svelte/flowbite-svelte-blocks-2/node_modules/.pnpm/rollup@2.77.2/node_modules/rollup/dist/es/shared/rollup.js:22136:30)
file: /Users/shinichiokada/Svelte/Flowbite-svelte/flowbite-svelte-blocks-2/src/app.css
error during build:

Error: Process from config.webServer was not able to start. Exit code: 1

  1 skipped
```

### Reproduction

```
npm init svelte@next flowbite-svelte-blocks-2
cd flowbite-svelte-blocks-2
pnpm i
npx svelte-add@latest tailwindcss
pnpm i
npm run test
```

<img width="1207" alt="image" src="https://user-images.githubusercontent.com/147320/183261534-a33ef155-f928-4240-abd8-9f2ce7d976a2.png">

### System Info

```shell
❯ npx envinfo --system --binaries --browsers --npmPackages "{svelte,@sveltejs/*,vite}"

  System:
    OS: macOS 12.5
    CPU: (8) arm64 Apple M1
    Memory: 62.48 MB / 16.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 16.13.0 - ~/.nvm/versions/node/v16.13.0/bin/node
    npm: 8.1.0 - ~/.nvm/versions/node/v16.13.0/bin/npm
  Browsers:
    Brave Browser: 104.1.42.86
    Chrome: 103.0.5060.134
    Chrome Canary: 106.0.5222.0
    Firefox: 103.0.1
    Safari: 15.6
  npmPackages:
    @sveltejs/adapter-auto: 1.0.0-next.64 => 1.0.0-next.64 
    @sveltejs/kit: 1.0.0-next.403 => 1.0.0-next.403 
    svelte: ^3.49.0 => 3.49.0 
    vite: ^3.0.4 => 3.0.4 
```

### Severity

serious, but I can work around it

### Additional Information

package.json:

```
{
	"name": "flowbite-svelte-blocks-3",
	"version": "0.0.1",
	"scripts": {
		"dev": "vite dev",
		"build": "vite build",
		"package": "svelte-kit package",
		"preview": "vite preview",
		"test": "playwright test",
		"check": "svelte-check --tsconfig ./tsconfig.json",
		"check:watch": "svelte-check --tsconfig ./tsconfig.json --watch",
		"lint": "prettier --check --plugin-search-dir=. . && eslint .",
		"format": "prettier --write --plugin-search-dir=. ."
	},
	"devDependencies": {
		"@playwright/test": "^1.22.2",
		"@sveltejs/adapter-auto": "next",
		"@sveltejs/kit": "next",
		"@typescript-eslint/eslint-plugin": "^5.27.0",
		"@typescript-eslint/parser": "^5.27.0",
		"eslint": "^8.16.0",
		"eslint-config-prettier": "^8.3.0",
		"eslint-plugin-svelte3": "^4.0.0",
		"prettier": "^2.6.2",
		"prettier-plugin-svelte": "^2.7.0",
		"svelte": "^3.44.0",
		"svelte-check": "^2.7.1",
		"svelte-preprocess": "^4.10.7",
		"tslib": "^2.3.1",
		"typescript": "^4.7.4",
		"vite": "^3.0.0",
		"postcss": "^8.4.14",
		"postcss-load-config": "^4.0.1",
		"autoprefixer": "^10.4.7",
		"tailwindcss": "^3.1.5"
	},
	"type": "module"
}
```

**Comment by baseballyama** [comment]
I passed tests if I use `pnpm test` instead of `npm run test`.

**Comment by shinokada** [comment]
When I run `pnpm test`, I get the same error.

**Comment by baseballyama** [comment]
It seems to be related to CJS / ESM issue but not sure for now.
I cannot reproduce with the current repl steps, so more specific reproduction steps , or a create repository on stackblitz is necessary.

**Comment by shinokada** [comment]
Stackblitz doesn't allow to install playwright so I created a repo.

[stackblitz](https://github.com/shinokada/playwright-test-repo)

**Comment by babichjacob** [comment]
Upgrade to a newer version of Node 16 (e.x. `16.16.0`) or Node 18 (e.x. `18.7.0`). I didn't have the issue until I downgraded to the version you listed, and it went away again when I upgraded back to a newer version.

**Comment by shinokada** [comment]
Thanks. v16.16.0 worked.
