### ISSUE TITLE
Accessing contexts in afterNavigate fails

### ISSUE THREAD

**Issue by philippschladitz** [sveltejs/kit#5876]
### Describe the bug

Whenever I try to access the context of a component by calling getContext inside of afterNavigate() the app fails and throws the error:
`Function called outside component initialization`
Other variables of the component can be accessed but the getContext/setContext api is not working which is cumbersome to work around.

The following example is failing:
```
<script>
    import { getContext } from "svelte";
    import { afterNavigate } from "$app/navigation";

    afterNavigate(() => {
        const store = getContext("test").store;
        store.set(2);
    });
</script>
```

### Reproduction

In the repository I linked below, you can find two routes which theoretically should work but fail with the error mentioned above.

https://github.com/philippschladitz/svelte-context-bug

### Logs

```shell
index.mjs:953 Uncaught (in promise) Error: Function called outside component initialization
    at get_current_component (index.mjs:953:15)
    at getContext (index.mjs:989:12)
    at index.svelte? [sm]:6:23
    at start.js:836:45
    at Array.forEach (<anonymous>)
    at initialize (start.js:836:29)
    at Object._hydrate (start.js:1797:4)
    at async start (start.js:1834:3)
```

### System Info

```shell
System:
    OS: Linux 5.13 Linux Mint 20.3 (Una)
    CPU: (16) x64 AMD Ryzen 7 3700X 8-Core Processor
    Memory: 10.03 GB / 15.55 GB
    Container: Yes
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 16.14.2 - ~/.nvm/versions/node/v16.14.2/bin/node
    npm: 8.5.0 - ~/.nvm/versions/node/v16.14.2/bin/npm
  Browsers:
    Chrome: 100.0.4896.60
    Firefox: 98.0.2
  npmPackages:
    @sveltejs/adapter-auto: next => 1.0.0-next.64 
    @sveltejs/kit: next => 1.0.0-next.405 
    svelte: ^3.44.0 => 3.49.0 
    vite: ^3.0.0 => 3.0.6
```

### Severity

serious, but I can work around it

**Comment by philippschladitz** [comment]
I just realized that this behaviour is how it is supposed to work. Closing this issue..
