### ISSUE TITLE
Update/install with pnpm fails with latest version of kit

### ISSUE THREAD

**Issue by ollema** [sveltejs/kit#5894]
### Describe the bug

I wanted to check out the new changes, tried to update and tried a clean install
```
$ pnpm update
Packages: +24 -10
++++++++++++++++++++++++----------
Progress: resolved 231, reused 210, downloaded 0, added 0, done
node_modules/.pnpm/@sveltejs+kit@1.0.0-next.406_svelte@3.49.0+vite@3.0.7/node_modules/@sveltejs/kit: Running postinstall script, failed in 197ms
.../node_modules/@sveltejs/kit postinstall$ node svelte-kit.js sync
│ > The filesystem router API has changed, see https://github.com/sveltejs/kit/discussions/5774 for details
│     at create_manifest_data (file:///home/s0001325/work/sersophane/node_modules/.pnpm/@sveltejs+kit@1.0.0-next.406_svelte@3.49.0+vite@3.0.7/node_modules/@sveltejs/kit/src/core/sync/c
│     at create (file:///home/s0001325/work/sersophane/node_modules/.pnpm/@sveltejs+kit@1.0.0-next.406_svelte@3.49.0+vite@3.0.7/node_modules/@sveltejs/kit/src/core/sync/sync.js:25:24)
│     at Module.all (file:///home/s0001325/work/sersophane/node_modules/.pnpm/@sveltejs+kit@1.0.0-next.406_svelte@3.49.0+vite@3.0.7/node_modules/@sveltejs/kit/src/core/sync/sync.js:58:
│     at file:///home/s0001325/work/sersophane/node_modules/.pnpm/@sveltejs+kit@1.0.0-next.406_svelte@3.49.0+vite@3.0.7/node_modules/@sveltejs/kit/src/cli.js:71:15
└─ Failed in 197ms
 ELIFECYCLE  Command failed with exit code 1.

 $ pnpm install
Packages: +210
++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
Packages are hard linked from the content-addressable store to the virtual store.
  Content-addressable store is at: /home/s0001325/.local/share/pnpm/store/v3
  Virtual store is at:             node_modules/.pnpm
Progress: resolved 231, reused 210, downloaded 0, added 210, done
node_modules/.pnpm/svelte-preprocess@4.10.7_uslzfc62di2n2otc2tvfklnwji/node_modules/svelte-preprocess: Running postinstall script, done in 15ms
node_modules/.pnpm/@sveltejs+kit@1.0.0-next.406_svelte@3.49.0+vite@3.0.7/node_modules/@sveltejs/kit: Running postinstall script, failed in 200ms
.../node_modules/@sveltejs/kit postinstall$ node svelte-kit.js sync
│ > The filesystem router API has changed, see https://github.com/sveltejs/kit/discussions/5774 for details
│     at create_manifest_data (file:///home/s0001325/work/sersophane/node_modules/.pnpm/@sveltejs+kit@1.0.0-next.406_svelte@3.49.0+vite@3.0.7/node_modules/@sveltejs/kit/src/core/sync/c
│     at create (file:///home/s0001325/work/sersophane/node_modules/.pnpm/@sveltejs+kit@1.0.0-next.406_svelte@3.49.0+vite@3.0.7/node_modules/@sveltejs/kit/src/core/sync/sync.js:25:24)
│     at Module.all (file:///home/s0001325/work/sersophane/node_modules/.pnpm/@sveltejs+kit@1.0.0-next.406_svelte@3.49.0+vite@3.0.7/node_modules/@sveltejs/kit/src/core/sync/sync.js:58:
│     at file:///home/s0001325/work/sersophane/node_modules/.pnpm/@sveltejs+kit@1.0.0-next.406_svelte@3.49.0+vite@3.0.7/node_modules/@sveltejs/kit/src/cli.js:71:15
└─ Failed in 200ms
 ELIFECYCLE  Command failed with exit code 1.
```
### Reproduction

```
> git clone git@github.com:ollema/sersophane.git
> cd sersophane
> pnpm install
```

### System Info

```shell
System:
    OS: Linux 5.15 Ubuntu 20.04.4 LTS (Focal Fossa)
    CPU: (16) x64 Intel(R) Core(TM) i9-10885H CPU @ 2.40GHz
    Memory: 19.60 GB / 31.20 GB
    Container: Yes
    Shell: 5.0.17 - /bin/bash
  Binaries:
    Node: 18.7.0 - ~/.nvm/versions/node/v18.7.0/bin/node
    npm: 8.15.0 - ~/.nvm/versions/node/v18.7.0/bin/npm
  Browsers:
    Chrome: 104.0.5112.79
  npmPackages:
    @sveltejs/adapter-node: next => 1.0.0-next.86 
    @sveltejs/kit: next => 1.0.0-next.406 
    svelte: ^3.49.0 => 3.49.0 
    vite: ^3.0.7 => 3.0.7
```

### Severity

blocking an upgrade

**Comment by Rich-Harris** [comment]
Yep, you'll need to `npx svelte-migrate routes` before you can use the new version

**Comment by ollema** [comment]
aha, when I read the migrations guide (https://github.com/sveltejs/kit/discussions/5774) I thought the order was:

1. `pnpm update`
2. `npx svelte-migrate routes`

but I guess it was the other way around

**Comment by ollema** [comment]
now it works, thanks!

**Comment by Rich-Harris** [comment]
gotcha, clarified the order on https://github.com/sveltejs/kit/discussions/5774

**Comment by ZerdoX-x** [comment]
I was reproducing bug for another repo and was clearing everything out from my production project. In the end of that, when my minimal reproduction repo was ready, I decided to bump all my dependencies (in case bug already fixed). After successfully migrating to new sveltekit, I was still getting error after installing dependencies:

```
The filesystem router API has changed, see https://github.com/sveltejs/kit/discussions/5774 for details
│     at create_manifest_data (file:///.../issue-reproducer/prettier-svelte-kit-2/node_modules/.pnpm/@sveltejs+kit@1.0
│     at create (file:///.../issue-reproducer/prettier-svelte-kit-2/node_modules/.pnpm/@sveltejs+kit@1.0.0-next.406_sv
│     at Module.all (file:///.../issue-reproducer/prettier-svelte-kit-2/node_modules/.pnpm/@sveltejs+kit@1.0.0-next.40
│     at file:///.../issue-reproducer/prettier-svelte-kit-2/node_modules/.pnpm/@sveltejs+kit@1.0.0-next.406_svelte@3.4
└─ Failed in 144ms
```

This was really unexpectedly for me, but new version of sveltekit requires `+page.svelte` in your router directory. For my bug reproduction only `__layout` (`+layout`) was enough. Killed about 30 minutes on this.
