### ISSUE TITLE
Missing "./data" export in "@sveltejs/kit" package

### ISSUE THREAD

**Issue by acarl005** [sveltejs/kit#5902]
### Describe the bug

I migrated after the big routing overhaul. Trying to import the error function so I can throw errors in an endpoint is causing an import error.

```js
import { error } from '@sveltejs/kit/data';
```

```
Error: Missing "./data" export in "@sveltejs/kit" package
    at bail (file:///home/projects/sveltejs-kit-template-default-sbiu9n/node_modules/vite/dist/node/chunks/dep-0f13c890.js:33660:8)
    at resolve (file:///home/projects/sveltejs-kit-template-default-sbiu9n/node_modules/vite/dist/node/chunks/dep-0f13c890.js:33737:10)
    at resolveExports (file:///home/projects/sveltejs-kit-template-default-sbiu9n/node_modules/vite/dist/node/chunks/dep-0f13c890.js:34479:12)
    at resolveDeepImport (file:///home/projects/sveltejs-kit-template-default-sbiu9n/node_modules/vite/dist/node/chunks/dep-0f13c890.js:34497:31)
    at tryNodeResolve (file:///home/projects/sveltejs-kit-template-default-sbiu9n/node_modules/vite/dist/node/chunks/dep-0f13c890.js:34213:20)
    at Context.resolveId (file:///home/projects/sveltejs-kit-template-default-sbiu9n/node_modules/vite/dist/node/chunks/dep-0f13c890.js:34015:28)
    at Object.resolveId (file:///home/projects/sveltejs-kit-template-default-sbiu9n/node_modules/vite/dist/node/chunks/dep-0f13c890.js:35273:55)
    at async TransformContext.resolve (file:///home/projects/sveltejs-kit-template-default-sbiu9n/node_modules/vite/dist/node/chunks/dep-0f13c890.js:35038:23)
    at async normalizeUrl (file:///home/projects/sveltejs-kit-template-default-sbiu9n/node_modules/vite/dist/node/chunks/dep-0f13c890.js:40290:34)
    at async TransformContext.transform (file:///home/projects/sveltejs-kit-template-default-sbiu9n/node_modules/vite/dist/node/chunks/dep-0f13c890.js:40430:47)
```

### Reproduction

https://stackblitz.com/edit/sveltejs-kit-template-default-sbiu9n?file=src%2Froutes%2F%2Bpage.server.js&terminal=dev

### System Info

```shell
npx envinfo --system --binaries --browsers --npmPackages "{svelte,@sveltejs/*,vite}"


  System:
    OS: Linux 5.0 undefined
    CPU: (4) x64 Intel(R) Core(TM) i9-9880H CPU @ 2.30GHz
    Memory: 0 Bytes / 0 Bytes
    Shell: 1.0 - /bin/jsh
  Binaries:
    Node: 16.14.2 - /usr/local/bin/node
    Yarn: 1.22.10 - /bin/yarn
    npm: 7.17.0 - /bin/npm
  npmPackages:
    @sveltejs/adapter-auto: next => 1.0.0-next.64 
    @sveltejs/kit: next => 1.0.0-next.406 
    svelte: ^3.46.0 => 3.49.0 
    vite: ^3.0.0 => 3.0.7
```

### Severity

blocking an upgrade

### Additional Information

I think the [`exports`](https://github.com/sveltejs/kit/blob/master/packages/kit/package.json#L76) field of Kit's `package.json` needs to list `data` as an export?

**Comment by Conduitry** [comment]
https://kit.svelte.dev/docs/load#errors `error` lives directly in `@sveltejs/kit`. Is there something somewhere that refers to it as living in `@sveltejs/kit/data`?

**Comment by acarl005** [comment]
@Conduitry yes, the migration guide https://github.com/sveltejs/kit/discussions/5774

**Comment by Conduitry** [comment]
Ah. Alrighty. The migration script itself inserts the correct imports. I've updated the comments in the migration guide. Thanks!
