### ISSUE TITLE
"parent is not a function" when requesting page endpoint

### ISSUE THREAD

**Issue by CaptainCodeman** [sveltejs/kit#5936]
### Describe the bug

Requesting a `+page.server.ts` endpoint to do a GET request works, but fails if an await for parent data is added to it.

### Reproduction

Add `\+layout.server.ts`:

```ts
import type { LayoutServerLoad } from "./$types";

export const load: LayoutServerLoad = async ({ }) => {
  return {
    site: 'My Site'
  }
}
```

Add `\+page.server.ts`:

```ts
import type { PageServerLoad } from "./$types";

export const load: PageServerLoad = async ({ parent }) => {
  const site = await parent()

  return {
    ...site,
    name: 'test'
  }
}
```

Request page with `accept: application/json` http header.

### Logs

```shell
parent is not a function
TypeError: parent is not a function
    at load (/Users/simon/dev/temp/sk-411/src/routes/+page.server.ts:5:21)
    at handle_json_request (file:///Users/simon/dev/temp/sk-411/node_modules/.pnpm/@sveltejs+kit@1.0.0-next.411_svelte@3.49.0+vite@3.0.8/node_modules/@sveltejs/kit/src/runtime/server/page/index.js:357:32)
    at render_page (file:///Users/simon/dev/temp/sk-411/node_modules/.pnpm/@sveltejs+kit@1.0.0-next.411_svelte@3.49.0+vite@3.0.8/node_modules/@sveltejs/kit/src/runtime/server/page/index.js:42:11)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async resolve (file:///Users/simon/dev/temp/sk-411/node_modules/.pnpm/@sveltejs+kit@1.0.0-next.411_svelte@3.49.0+vite@3.0.8/node_modules/@sveltejs/kit/src/runtime/server/index.js:308:11)
    at async respond (file:///Users/simon/dev/temp/sk-411/node_modules/.pnpm/@sveltejs+kit@1.0.0-next.411_svelte@3.49.0+vite@3.0.8/node_modules/@sveltejs/kit/src/runtime/server/index.js:202:20)
    at async file:///Users/simon/dev/temp/sk-411/node_modules/.pnpm/@sveltejs+kit@1.0.0-next.411_svelte@3.49.0+vite@3.0.8/node_modules/@sveltejs/kit/src/vite/dev/index.js:396:22
```

### System Info

```shell
System:
    OS: macOS 12.5
    CPU: (6) x64 Intel(R) Core(TM) i5-8500B CPU @ 3.00GHz
    Memory: 951.54 MB / 32.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 16.14.0 - /usr/local/bin/node
    npm: 8.3.1 - /usr/local/bin/npm
  Browsers:
    Brave Browser: 102.1.39.111
    Chrome: 104.0.5112.79
    Chrome Canary: 106.0.5243.0
    Firefox: 103.0.2
    Safari: 15.6
    Safari Technology Preview: 16.0
  npmPackages:
    @sveltejs/adapter-auto: next => 1.0.0-next.64 
    @sveltejs/kit: next => 1.0.0-next.411 
    svelte: ^3.44.0 => 3.49.0 
    vite: ^3.0.0 => 3.0.8
```

### Severity

blocking an upgrade

**Comment by martinbeentjes** [comment]
I've been struggling with this, thanks for this one. I think I am experiencing the same right now.

**Comment by Rich-Harris** [comment]
What's the use case for making an `accept: application/json` request to a page? The code is there for historical reasons, but now that I think about it it's a bit of a strange thing to have. You can't (for example) request JSON from a `+layout.server.js`, so why `load` in `+page.server.js` should get this treatment eludes me. My inclination is to remove it.

At the very least the current behaviour would conflict with #5896.

**Comment by CaptainCodeman** [comment]
I'm only using `load` in`+page.server.js` because it's now the only way to support the URLs that I need to. I'd prefer to be able to use the endpoint + page combination as before.

I need to be able to decide what routes and methods my app responds to and how. If a router isn't capable of supporting that then IMO it isn't really a true router anymore.

**Comment by CaptainCodeman** [comment]
I guess what I'm after is the ability to use the router at the lowest level. I think all the other stuff should be extras built on top of that, but should be extras, not replacements. It should still be possible to have a plain burger without the magical, erm, sprinkles on top.

I appreciate some people will love all the extra form handling stuff, but I'd prefer to use ye-olde GET and POST directly myself if I want to.

I'm probably mixing up a few requests, but they are all inter-related (the server endpoint co-existence and the form actions).

**Comment by Rich-Harris** [comment]
RIght, but that's all covered by #5896, no?

**Comment by lkj4** [comment]
> What's the use case for making an accept: application/json request to a page? 

@Rich-Harris You don't need two endpoint files for the same thing, my use case (posted this in the wrong issue before):

- I have bigger content properties but send only smaller, requested chunks via REST
- With the initial pageload the user gets the first part w/o a ded. api request
- Then, within the client the user can request further parts without the need to reload the page. Both use the exact same API and DB call

With the new routing, I need now two files that do the same. 

>  My inclination is to remove it.

This broke my app. No chance to get this feature back?

**Comment by lkj4** [comment]
@Rich-Harris any reason not to let `+page.server.ts` handle pure json requests, again?

**Comment by lkj4** [comment]
True! This is what I do as a work-around now with `+server.ts` in a ded. API folder tree. If `+page.server.ts` handled pure json, I need one file only, `+page.server.ts` (1), not `+server.ts` (2) and have response types preserved without the need to declare types in (1) and redeclare them in (2) though.

**Comment by lkj4** [comment]
Don't want to annoy you guys but I still don't see any reason not to let `+page.server.ts` handle pure json requests, again and why this was disabled.
