### ISSUE TITLE
check_serializability fails for Date

### ISSUE THREAD

**Issue by cdcarson** [sveltejs/kit#6093]
### Describe the bug

I'm getting the following error passing a `Date` from the server.

```bash
Error: data.currentServerDate returned from 'load' in src/routes/+layout.server.ts cannot be serialized as JSON
    at check_serializability (file:///Users/chriscarson/linketysplit-dev-august/sk-date-serialization-issue/node_modules/@sveltejs/kit/src/runtime/server/page/load_data.js:126:8)
    at check_serializability (file:///Users/chriscarson/linketysplit-dev-august/sk-date-serialization-issue/node_modules/@sveltejs/kit/src/runtime/server/page/load_data.js:120:5)
    at load_server_data (file:///Users/chriscarson/linketysplit-dev-august/sk-date-serialization-issue/node_modules/@sveltejs/kit/src/runtime/server/page/load_data.js:34:3)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async file:///Users/chriscarson/linketysplit-dev-august/sk-date-serialization-issue/node_modules/@sveltejs/kit/src/runtime/server/page/index.js:163:13
```

`Date` is serializable to JSON. The problem is check_serializability.https://github.com/sveltejs/kit/blob/566776afcdae54c6f60f4eaf75933b3041c96fb2/packages/kit/src/runtime/server/page/load_data.js#L96

I understand the function gives you the key of the offending non-serializable type. But the error thrown from `JSON.stringify` is already pretty descriptive...

```bash
const foo = BigInt(3);
const bar = {foo}
JSON.stringify(bar)
VM270:1 Uncaught TypeError: Do not know how to serialize a BigInt
    at JSON.stringify (<anonymous>)
    at <anonymous>:1:6
(anonymous) @ VM270:1

```

If you do want to keep track of the path, maybe we can just add a try/catch before we throw (untested):

```js
/**
 * Check that the data can safely be serialized to JSON
 * @param {any} value
 * @param {string} id
 * @param {string} path
 */

function check_serializability(value, id, path) {
  const type = typeof value;

  if (type === 'string' || type === 'boolean' || type === 'number' || type === 'undefined') {
    // primitives are fine
    return;
  }

  if (type === 'object') {
    // nulls are fine...
    if (!value) return;

    // ...so are plain arrays...
    if (Array.isArray(value)) {
      value.forEach((child, i) => {
        check_serializability(child, id, `${path}[${i}]`);
      });
      return;
    }

    // ...and objects
    const tag = Object.prototype.toString.call(value);
    if (tag === '[object Object]') {
      for (const key in value) {
        check_serializability(value[key], id, `${path}.${key}`);
      }
      return;
    }
  }
 // added to handle things that fail the above tests
  try {
    JSON.stringify(value);
    return;
  } catch (error) {
    //ignore
  }

  throw new Error(`${path} returned from 'load' in ${id} cannot be serialized as JSON`);
}
```

### Reproduction

https://github.com/cdcarson/sk-date-serialization-issue.git

### System Info

```shell
ystem:
    OS: macOS 12.4
    CPU: (8) arm64 Apple M1
    Memory: 167.59 MB / 8.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 16.13.2 - ~/.nvm/versions/node/v16.13.2/bin/node
    npm: 8.1.2 - ~/.nvm/versions/node/v16.13.2/bin/npm
  Browsers:
    Chrome: 104.0.5112.101
    Safari: 15.5
  npmPackages:
    @sveltejs/adapter-auto: next => 1.0.0-next.64 
    @sveltejs/kit: next => 1.0.0-next.426 
    @sveltejs/package: next => 1.0.0-next.1 
    svelte: ^3.44.0 => 3.49.0 
    vite: ^3.0.0 => 3.0.9
```

### Severity

blocking all usage of SvelteKit

### Additional Information

I'm blocked until this is fixed, so I'll take a stab at modifying the function and writing tests.

**Comment by cdcarson** [comment]
That's a really bad design decision. The notion that I can't be trusted to rehydrate `Date` on the client in the correct way. Whew. 'Nuff said.

**Comment by lulucas** [comment]
Prisma Decimal has the same issue.

**Comment by DePasqualeOrg** [comment]
Starting with one of the recent updates, I've been having related issues with Prisma and timestamps stored as BigInt.

**Comment by cdcarson** [comment]
@DePasqualeOrg `BigInt` isn't [JSON serializable -- you have to do that yourself](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/BigInt#use_within_json). It's not a SvelteKit specific limitation, like `Date` currently is.  I raised the issue of serialization today here: https://github.com/sveltejs/kit/discussions/6143#discussion-4322035 and it looks like SvelteKit are working on de/serialization of both `Date` and `BigInt` in https://github.com/sveltejs/kit/issues/6008.

@lulucas I'm not directly familiar with Prisma Decimal, but it looks like it's a class with methods rather than a plain object: https://mikemcl.github.io/decimal.js. Can you serialize it to JSON yourself, outside Kit? If you can, it probably means that Kit's `check_serializability` is objecting to it on those grounds.
