### ISSUE TITLE
Failed to build pre-rendered app with ``adapter-static``.

### ISSUE THREAD

**Issue by gyurielf** [sveltejs/kit#6137]
### Describe the bug

I've upgraded to the latest version of the sveltekit in my app and resolved all of the migrations etc.., but now I cannot build (and pre-render) it with ``adapter-static``.

I thought that was my fault somewhere, but as you see, I created a repo with the original sveltekit demo app, and something wrong there either.

### Reproduction
https://github.com/gyurielf/svelte-kit-prerender-test

### Logs
```shell
> prerender-test@0.0.1 build
> vite build

vite v3.0.9 building for production...
✓ 52 modules transformed.
.svelte-kit/output/client/_app/immutable/assets/svelte-logo-87df40b8.svg                           1.85 KiB
.svelte-kit/output/client/_app/immutable/assets/fira-mono-cyrillic-ext-400-normal-3df7909e.woff2   15.40 KiB
.svelte-kit/output/client/_app/immutable/assets/fira-mono-cyrillic-400-normal-c7d433fd.woff2       8.89 KiB
.svelte-kit/output/client/_app/immutable/assets/fira-mono-greek-400-normal-a8be01ce.woff2          10.27 KiB
.svelte-kit/output/client/_app/immutable/assets/fira-mono-latin-400-normal-e43b3538.woff2          15.90 KiB
.svelte-kit/output/client/_app/immutable/assets/fira-mono-greek-ext-400-normal-9e2fe623.woff2      7.33 KiB
.svelte-kit/output/client/_app/immutable/assets/fira-mono-latin-ext-400-normal-6bfabd30.woff2      11.10 KiB
.svelte-kit/output/client/_app/immutable/assets/fira-mono-all-400-normal-1e3b098c.woff             75.55 KiB
.svelte-kit/output/client/vite-manifest.json                                                       7.60 KiB
.svelte-kit/output/client/_app/immutable/components/error.svelte-1aa22767.js                       1.54 KiB / gzip: 0.71 KiB
.svelte-kit/output/client/_app/immutable/components/pages/_layout.svelte-818ca664.js               4.50 KiB / gzip: 1.74 KiB
.svelte-kit/output/client/_app/immutable/components/pages/_page.svelte-60cbe889.js                 5.46 KiB / gzip: 2.42 KiB
.svelte-kit/output/client/_app/immutable/components/pages/about/_page.svelte-4c2aaaa2.js           2.46 KiB / gzip: 1.11 KiB
.svelte-kit/output/client/_app/immutable/modules/pages/_page.ts-e9fa0128.js                        0.07 KiB / gzip: 0.08 KiB
.svelte-kit/output/client/_app/immutable/start-be845c33.js                                         22.92 KiB / gzip: 8.72 KiB
.svelte-kit/output/client/_app/immutable/modules/pages/about/_page.ts-e8ab19e6.js                  0.11 KiB / gzip: 0.11 KiB
.svelte-kit/output/client/_app/immutable/chunks/singletons-e5e57fbd.js                             0.05 KiB / gzip: 0.07 KiB
.svelte-kit/output/client/_app/immutable/components/pages/todos/_page.svelte-a806b8ca.js           6.86 KiB / gzip: 2.88 KiB
.svelte-kit/output/client/_app/immutable/chunks/index-67daab9a.js                                  0.43 KiB / gzip: 0.31 KiB
.svelte-kit/output/client/_app/immutable/chunks/stores-87dd2ac2.js                                 0.53 KiB / gzip: 0.31 KiB
.svelte-kit/output/client/_app/immutable/chunks/_page-802cc2a3.js                                  0.14 KiB / gzip: 0.14 KiB
.svelte-kit/output/client/_app/immutable/chunks/_page-efb9c460.js                                  0.18 KiB / gzip: 0.16 KiB
.svelte-kit/output/client/_app/immutable/chunks/0-5939c936.js                                      0.15 KiB / gzip: 0.13 KiB
.svelte-kit/output/client/_app/immutable/chunks/1-3fa30a9b.js                                      0.14 KiB / gzip: 0.13 KiB
.svelte-kit/output/client/_app/immutable/chunks/index-98702734.js                                  11.48 KiB / gzip: 4.90 KiB
.svelte-kit/output/client/_app/immutable/chunks/2-e130a139.js                                      0.20 KiB / gzip: 0.15 KiB
.svelte-kit/output/client/_app/immutable/chunks/3-c898f07b.js                                      0.18 KiB / gzip: 0.15 KiB
.svelte-kit/output/client/_app/immutable/chunks/4-515ea953.js                                      0.18 KiB / gzip: 0.15 KiB
.svelte-kit/output/client/_app/immutable/assets/+page-8bad58d3.css                                 1.45 KiB / gzip: 0.52 KiB
.svelte-kit/output/client/_app/immutable/assets/+page-9682aba9.css                                 0.11 KiB / gzip: 0.10 KiB
.svelte-kit/output/client/_app/immutable/assets/+layout-c589ff87.css                               4.84 KiB / gzip: 1.54 KiB
.svelte-kit/output/client/_app/immutable/assets/+page-5c3529b5.css                                 3.70 KiB / gzip: 1.03 KiB
vite v3.0.9 building SSR bundle for production...
✓ 58 modules transformed.
.svelte-kit/output/server/vite-manifest.json                       3.05 KiB
.svelte-kit/output/server/index.js                                 59.23 KiB
.svelte-kit/output/server/entries/pages/_layout.svelte.js          4.09 KiB
.svelte-kit/output/server/entries/fallbacks/error.svelte.js        0.60 KiB
.svelte-kit/output/server/entries/pages/_page.svelte.js            7.10 KiB
.svelte-kit/output/server/entries/pages/_page.ts.js                0.05 KiB
.svelte-kit/output/server/entries/pages/about/_page.svelte.js      1.25 KiB
.svelte-kit/output/server/entries/pages/about/_page.ts.js          0.15 KiB
.svelte-kit/output/server/entries/pages/todos/_page.svelte.js      5.92 KiB
.svelte-kit/output/server/entries/pages/todos/_page.server.ts.js   1.22 KiB
.svelte-kit/output/server/chunks/index.js                          4.15 KiB
.svelte-kit/output/server/chunks/index2.js                         0.73 KiB
.svelte-kit/output/server/chunks/index3.js                         1.29 KiB
.svelte-kit/output/server/chunks/stores.js                         0.81 KiB
.svelte-kit/output/server/chunks/hooks.js                          0.49 KiB
Error: Cannot prerender pages that have endpoints with mutative methods
    at render_page (file:///home/xyz/work/own/prerender-test/.svelte-kit/output/server/index.js:1207:15)
    at async resolve (file:///home/xyz/work/own/prerender-test/.svelte-kit/output/server/index.js:1683:92)
    at async Object.handle (file:///home/xyz/work/own/prerender-test/.svelte-kit/output/server/chunks/hooks.js:5:20)
    at async respond (file:///home/xyz/work/own/prerender-test/.svelte-kit/output/server/index.js:1592:22)
    at async visit (file:///home/xyz/work/own/prerender-test/node_modules/@sveltejs/kit/src/core/prerender/prerender.js:214:20)
file:///home/xyz/work/own/prerender-test/node_modules/@sveltejs/kit/src/core/prerender/prerender.js:48
                                throw new Error(format_error(details, config));
                                      ^

Error: 500 /todos/ (linked from /todos)
    at file:///home/xyz/work/own/prerender-test/node_modules/@sveltejs/kit/src/core/prerender/prerender.js:48:11
    at save (file:///home/xyz/work/own/prerender-test/node_modules/@sveltejs/kit/src/core/prerender/prerender.js:336:4)
    at visit (file:///home/xyz/work/own/prerender-test/node_modules/@sveltejs/kit/src/core/prerender/prerender.js:223:3)
[vite-plugin-svelte-kit] Prerendering failed with code 1
error during build:
Error: Prerendering failed with code 1
    at ChildProcess.<anonymous> (file:///home/xyz/work/own/prerender-test/node_modules/@sveltejs/kit/src/vite/index.js:417:14)
    at ChildProcess.emit (node:events:527:28)
    at Process.ChildProcess._handle.onexit (node:internal/child_process:291:12)
```

### System Info

```shell
System:
    OS: Linux 5.15 Ubuntu 20.04.4 LTS (Focal Fossa)
    CPU: (12) x64 Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz
    Memory: 10.42 GB / 15.48 GB
    Container: Yes
    Shell: 5.0.17 - /bin/bash
  Binaries:
    Node: 16.16.0 - ~/.local/share/pnpm/node
    npm: 8.17.0 - ~/.local/share/pnpm/npm
  Browsers:
    Chrome: 104.0.5112.79
    Firefox: 103.0
  npmPackages:
    @sveltejs/adapter-static: ^1.0.0-next.39 => 1.0.0-next.39 
    @sveltejs/kit: ^1.0.0-next.427 => 1.0.0-next.427 
    svelte: ^3.49.0 => 3.49.0 
    vite: ^3.0.9 => 3.0.9
```

### Severity

blocking an upgrade

**Comment by Conduitry** [comment]
As explained in the issue template form:

> Reproductions must be [short, self-contained and correct](http://sscce.org/) and must not contain files or code that aren't relevant to the issue — please do NOT just paste a link to your project.

**Comment by Conduitry** [comment]
For the sample app with adapter-static, the logs tell you what's wrong: there is a server-side endpoint, which cannot be prerendered (`Error: Cannot prerender pages that have endpoints with mutative methods`). For your actual project, something else is going on, presumably related to trying to treat CommonJS code as ESM code, possibly because Babel is transpiling it.

**Comment by gyurielf** [comment]
> As explained in the issue template form:
> 
> > Reproductions must be [short, self-contained and correct](http://sscce.org/) and must not contain files or code that aren't relevant to the issue — please do NOT just paste a link to your project.

Right.
I've deleted my part, now it's just the original svelte-kit created app, with adapter-static.

**Comment by gyurielf** [comment]
> For the sample app with adapter-static, the logs tell you what's wrong: there is a server-side endpoint, which cannot be prerendered (`Error: Cannot prerender pages that have endpoints with mutative methods`). For your actual project, something else is going on, presumably related to trying to treat CommonJS code as ESM code, possibly because Babel is transpiling it.

But it's works fine before. E.g. on: ``"@sveltejs/kit": "^1.0.0-next.411",``

**Comment by gyurielf** [comment]
I'll do some debug to ensure, what's going on. Until that I close this.
Thanks for the notice about issue template. Next time I'll create that way.
