### ISSUE TITLE
redirect in a layout fails if there is no page for it.

### ISSUE THREAD

**Issue by tedsteen** [sveltejs/kit#6213]
### Describe the bug

If you redirect in a layout that does not have a page you get the error
```
Error: {"status":301,"location":"/gb"}
    at Module.coalesce_to_error (file:///home/projects/sveltejs-kit-template-default-zpo2qc/node_modules/@sveltejs/kit/src/utils/error.js:27:5)
    at Module.respond_with_error (file:///home/projects/sveltejs-kit-template-default-zpo2qc/node_modules/@sveltejs/kit/src/runtime/server/page/respond_with_error.js:100:33)
    at async resolve (file:///home/projects/sveltejs-kit-template-default-zpo2qc/node_modules/@sveltejs/kit/src/runtime/server/index.js:382:13)
    at async respond (file:///home/projects/sveltejs-kit-template-default-zpo2qc/node_modules/@sveltejs/kit/src/runtime/server/index.js:217:20)
    at async eval (file:///home/projects/sveltejs-kit-template-default-zpo2qc/node_modules/@sveltejs/kit/src/vite/dev/index.js:416:22)
```

### Reproduction

https://stackblitz.com/edit/sveltejs-kit-template-default-zpo2qc?file=src%2Froutes%2F%2Blayout.server.ts

### System Info

```shell
System:
    OS: macOS 12.5.1
    CPU: (10) arm64 Apple M1 Pro
    Memory: 467.41 MB / 32.00 GB
    Shell: 5.9 - /opt/homebrew/bin/zsh
  Binaries:
    Node: 18.7.0 - /opt/homebrew/bin/node
    npm: 8.18.0 - /opt/homebrew/bin/npm
  Browsers:
    Brave Browser: 104.1.42.97
    Safari: 15.6.1
  npmPackages:
    @sveltejs/adapter-auto: next => 1.0.0-next.65
    @sveltejs/kit: next => 1.0.0-next.429
    svelte: ^3.44.0 => 3.49.0
    vite: ^3.0.0 => 3.0.9
```

### Severity

annoyance

**Comment by Rich-Harris** [comment]
This is expected behaviour, sort of. You're not encountering the redirect while attempting to navigate to `/`, you're encountering the redirect because SvelteKit _couldn't_ navigate to `/` — there's no such route. If SvelteKit fails to match a route, it renders the root `+layout` and `+error`, and in the process of so doing it hits the `throw redirect`.

When something is thrown during that process, we end up here: https://github.com/sveltejs/kit/blob/82aed98156eb74579ce80d756e6cd383e6b742d4/packages/kit/src/runtime/server/page/respond_with_error.js#L85-L91

We _could_ respect the redirect, though it feels slightly fraught — people redirecting when errors happen has historically been a source of confusion with SvelteKit, and it's one of the factors that lead to us removing `load` from `+error` pages.

Regardless, the best solution here would be to create the `+page` with the redirect.

**Comment by tedsteen** [comment]
In our case it's something like this.
`/src/routes/[market]/sub/paths/go/here`
In my `/src/routes/+layout.ts` I know when you are trying to hit a wrong [market] and would like to redirect you to a correct one, this will currently only work when you try to hit sub paths that actually exist.
