### ISSUE TITLE
Prerender crash with the new advanced layout feature

### ISSUE THREAD

**Issue by mquandalle** [sveltejs/kit#6230]
### Describe the bug

`vite build` crashes with an error related to a non existing path when the new advanced layout feature is used in the same app than a prerendered `+page.js`.

### Reproduction

https://stackblitz.com/edit/sveltejs-kit-template-default-tvrqmc?file=README.md

### Logs

```shell
Error: 404 /(example)/about
    at eval (file:///home/projects/sveltejs-kit-template-default-tvrqmc/node_modules/@sveltejs/kit/src/core/prerender/prerender.js:63:11)
    at save (file:///home/projects/sveltejs-kit-template-default-tvrqmc/node_modules/@sveltejs/kit/src/core/prerender/prerender.js:352:4)
    at visit (file:///home/projects/sveltejs-kit-template-default-tvrqmc/node_modules/@sveltejs/kit/src/core/prerender/prerender.js:239:3)
[vite-plugin-svelte-kit] Prerendering failed with code 1
error during build:
Error: Prerendering failed with code 1
    at ChildProcess.eval (file:///home/projects/sveltejs-kit-template-default-tvrqmc/node_modules/@sveltejs/kit/src/vite/index.js:445:14)
    at EventEmitter.emit (https://sveltejs-kit-template-default-tvrqmc.w.staticblitz.com/blitz.1aed30d7bfa712aa778f484223078bdc72898352.js:6:155574)
    at ChildProcess._handle.onexit (https://sveltejs-kit-template-default-tvrqmc.w.staticblitz.com/blitz.1aed30d7bfa712aa778f484223078bdc72898352.js:6:956472)
    at https://sveltejs-kit-template-default-tvrqmc.w.staticblitz.com/blitz.1aed30d7bfa712aa778f484223078bdc72898352.js:15:380472
    at _0x35818a (https://sveltejs-kit-template-default-tvrqmc.w.staticblitz.com/blitz.1aed30d7bfa712aa778f484223078bdc72898352.js:15:144412)
    at https://sveltejs-kit-template-default-tvrqmc.w.staticblitz.com/blitz.1aed30d7bfa712aa778f484223078bdc72898352.js:15:144195
```

### System Info

```shell
System:
    OS: Linux 5.19 Pop!_OS 22.04 LTS
    CPU: (8) x64 Intel(R) Core(TM) i7-8550U CPU @ 1.80GHz
    Memory: 5.15 GB / 15.39 GB
    Container: Yes
    Shell: 5.8.1 - /usr/bin/zsh
  Binaries:
    Node: 16.16.0 - ~/.nvm/versions/node/v16.16.0/bin/node
    Yarn: 1.22.19 - ~/.nvm/versions/node/v16.16.0/bin/yarn
    npm: 8.11.0 - ~/.nvm/versions/node/v16.16.0/bin/npm
  Browsers:
    Brave Browser: 101.1.38.111
    Chromium: 104.0.5112.101
    Firefox: 103.0
```

### Severity

blocking an upgrade

**Comment by ericwilhite** [comment]
Same issue.
Just updated to`"@sveltejs/kit": "1.0.0-next.434",` and dev server works but build fails with the same error as OP.
