### ISSUE TITLE
production build tries to load 'service-worker.js' via routes/[name]/

### ISSUE THREAD

**Issue by willidad** [sveltejs/kit#6242]
### Describe the bug

The production build version of my App tries to load a file `service-worker.js` via a `routes/[name]` route when the browser loads the app.  This causes a dynamic import in the routes `+page.server.ts` to report an error. 

The problem does not show up when the app runs on dev-mode, 

I have not sen this problems on routes like `routes/abc/[name]`.

### Reproduction

Reproduction reporitory: [https://github.com/willidad/sveltekit-bug](https://github.com/willidad/sveltekit-bug)

npm install
npm run vite build
npm run vite preview

load localhost:4173 in a browser

### Logs

```shell
> vite preview

  ➜  Local:   http://localhost:4173/
  ➜  Network: use --host to expose
{ name: 'service-worker.js' }
Error: Unknown variable dynamic import: ../../articles/service-worker.js.md
    at file:///F:/bug-report/.svelte-kit/output/server/entries/pages/_name_/_page.server.ts.js:7:92
    at new Promise (<anonymous>)
    at __variableDynamicImportRuntimeHelper (file:///F:/bug-report/.svelte-kit/output/server/entries/pages/_name_/_page.server.ts.js:6:10)
    at load (file:///F:/bug-report/.svelte-kit/output/server/entries/pages/_name_/_page.server.ts.js:12:18)
    at load_server_data (file:///F:/bug-report/.svelte-kit/output/server/index.js:1105:71)
    at file:///F:/bug-report/.svelte-kit/output/server/index.js:1713:24
```

### System Info

```shell
envinfo fails on my system, so here is tne most important data. if you need more, please let me know.

Node: 18.6.0
OS: Windows 10 Pro 21H1
svelte: 3.49.0
sveltekit: 1.0.0-next.435
vite: 3.0.9
adapter-node: 1.0.0-next.87
```

### Severity

annoyance

### Additional Information

Changin the route to `routes/something/[name]` avoids the problem.

**Comment by willidad** [comment]
uhhh, routes/[name] shadows the static public routes, so using this for specific dynamic imports is a bad idea. sorry for this oversight. closing the issue
