### ISSUE TITLE
`+layout.server.ts` not re-running after slug change

### ISSUE THREAD

**Issue by HegarGarcia** [sveltejs/kit#6257]
### Describe the bug

When changing slug in a route, the `+page.server.ts` gets called but the `+layout.server.ts` doesn't event though in depends on the params.

GIven a url structure: `/foo/[baz]`.

When going from `/foo` to `/foo/abc`:
- `foo/[baz]/+layout@.server.ts#load`  doesn't run
- if a `foo/+page.server.ts` exists, then `foo/[slug]/+page.svelte` will receive it's return value

When going from `/foo` to `/foo/abc` to `/foo/xyz`:
- `foo/[baz]/+layout@.server.ts#load`  doesn't get executed
- if a `foo/+page.server.ts` exists, then `foo/[slug]/+page.svelte` will receive the same props no matter how many slug changes are performed

When accessing directly `/foo/abc`
- `foo/[baz]/+layout@.server.ts#load` gets executed

When accessing directly `/foo/abc` then go the `/foo/xyz`
- `foo/[baz]/+layout@.server.ts#load` gets executed on `/foo/abc`
- `foo/[baz]/+layout@.server.ts#load` doesn't get executed when routing to `/foo/xyz`

This happens no matter if you are using `<a>` or the `goto` function.

### Reproduction

[Reproduction](https://stackblitz.com/edit/sveltejs-kit-template-default-84kyg5?file=src/routes/foo/[slug]/+layout@.svelte)

From the landing page, follow the link between the pages and see the output of each page.

### System Info

```shell
System:
  OS: macOS 12.5.1
  CPU: (8) arm64 Apple M1
  Memory: 224.58 MB / 16.00 GB
  Shell: 5.8.1 - /bin/zsh
Binaries:
  Node: 16.16.0 - ~/.nvm/versions/node/v16.16.0/bin/node
  Yarn: 1.22.15 - ~/.nvm/versions/node/v16.16.0/bin/yarn
  npm: 8.11.0 - ~/.nvm/versions/node/v16.16.0/bin/npm
Browsers:
  Chrome: 104.0.5112.101
  Safari: 15.6.1
npmPackages:
  @sveltejs/adapter-auto: next => 1.0.0-next.66 
  @sveltejs/kit: 1.0.0-next.436 => 1.0.0-next.436 
  svelte: ^3.44.0 => 3.49.0 
  vite: ^3.0.8 => 3.0.8
```

### Severity

serious, but I can work around it

**Comment by HegarGarcia** [comment]
Adding the `/foo/[slug]/+page.server.ts` file, completely empty, solves the issue.

> To remove the `isolatedModules` error just add `export {};`

---

You can even create an empty load function and will still work.
> Had to manually add the return type so that `PageData` interface can infer the types correctly.

If any value is returned, it follows normal behavior; gets merge with return value of `/foo/[slug]/+layout.server.ts`.

```ts
import type { PageServerLoad } from './$types';
import type { load as layoutLoad } from './+layout.server';

export const load: PageServerLoad = async (): Promise<ReturnType<typeof layoutLoad>> => {
	return;

	// return { test: 'foo' };
};
```

If you try to `await parent()` inside the function you get the following error:

```
Cannot read properties of null (reading 'data')
TypeError: Cannot read properties of null (reading 'data')
    at parent (file:///node_modules/.pnpm/@sveltejs+kit@1.0.0-next.436_svelte@3.49.0+vite@3.0.8/node_modules/@sveltejs/kit/src/runtime/server/index.js:288:41)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async load (/src/routes/foo/[slug]/+page.server.ts:5:1)
    at async load_server_data (file:///node_modules/.pnpm/@sveltejs+kit@1.0.0-next.436_svelte@3.49.0+vite@3.0.8/node_modules/@sveltejs/kit/src/runtime/server/page/load_data.js:38:17)
    at async Promise.all (index 2)
    at async resolve (file:///node_modules/.pnpm/@sveltejs+kit@1.0.0-next.436_svelte@3.49.0+vite@3.0.8/node_modules/@sveltejs/kit/src/runtime/server/index.js:311:22)
    at async respond (file:///node_modules/.pnpm/@sveltejs+kit@1.0.0-next.436_svelte@3.49.0+vite@3.0.8/node_modules/@sveltejs/kit/src/runtime/server/index.js:216:20)
    at async file:///node_modules/.pnpm/@sveltejs+kit@1.0.0-next.436_svelte@3.49.0+vite@3.0.8/node_modules/@sveltejs/kit/src/vite/dev/index.js:375:22
```
