### ISSUE TITLE
Bug on build with adapter netlify

### ISSUE THREAD

**Issue by squelix** [sveltejs/kit#6345]
### Describe the bug

It doesn't build with the new version of adapter netlify. It's when building with edge functions that made a bug on build, building with classical functions still works

### Reproduction

Use there version
```
"@sveltejs/adapter-netlify": "1.0.0-next.73",
"@sveltejs/kit": "1.0.0-next.445",
```

Add this config to netlify adapter 
```
adapter: adapter({
  edge: true
})
```

And run `yarn build` or `npm run build`.

### Logs

```shell
❯ npm run build

> svelte-portfolio@0.0.1 build
> vite build

vite v3.0.9 building for production...
✓ 196 modules transformed.
.svelte-kit/output/client/vite-manifest.json                                                                                       29.49 KiB
.svelte-kit/output/client/_app/immutable/components/pages/_error.svelte-44b070c7.js                                                1.86 KiB / gzip: 0.96 KiB
.svelte-kit/output/client/_app/immutable/components/pages/_lang_/about/_layout.svelte-77ff4430.js                                  4.95 KiB / gzip: 1.83 KiB
.svelte-kit/output/client/_app/immutable/components/pages/_lang_/about/personal-info/bio/_layout.svelte-2a8e52f4.js                3.25 KiB / gzip: 1.30 KiB
.svelte-kit/output/client/_app/immutable/components/pages/_lang_/about/personal-info/education/_layout.svelte-7dd8b9be.js          0.54 KiB / gzip: 0.36 KiB
.svelte-kit/output/client/_app/immutable/components/pages/_lang_/about/personal-info/bio/_page.svelte-69dd888d.js                  3.38 KiB / gzip: 1.24 KiB
.svelte-kit/output/client/_app/immutable/components/pages/_layout.svelte-06012a31.js                                               13.86 KiB / gzip: 4.92 KiB
.svelte-kit/output/client/_app/immutable/components/pages/_lang_/about/personal-info/bio/looking-for/_page.svelte-95c877f4.js      3.56 KiB / gzip: 1.25 KiB
.svelte-kit/output/client/_app/immutable/start-c1661111.js                                                                         29.98 KiB / gzip: 9.50 KiB
.svelte-kit/output/client/_app/immutable/components/pages/_lang_/_page.svelte-9661c879.js                                          15.18 KiB / gzip: 5.33 KiB
.svelte-kit/output/client/_app/immutable/components/pages/_lang_/about/personal-info/education/projects/_page.svelte-b4bc442d.js   4.83 KiB / gzip: 1.76 KiB
.svelte-kit/output/client/_app/immutable/components/pages/_lang_/about/personal-info/education/schools/_page.svelte-c5792476.js    3.08 KiB / gzip: 1.11 KiB
.svelte-kit/output/client/_app/immutable/modules/pages/_layout.ts-435ae93f.js                                                      0.40 KiB / gzip: 0.20 KiB
.svelte-kit/output/client/_app/immutable/modules/pages/_lang_/about/_layout.ts-32bf949d.js                                         0.29 KiB / gzip: 0.15 KiB
.svelte-kit/output/client/_app/immutable/components/pages/_lang_/contact/_page.svelte-6e6b50d1.js                                  12.66 KiB / gzip: 4.67 KiB
.svelte-kit/output/client/_app/immutable/modules/pages/_lang_/about/personal-info/bio/_layout.ts-80cc856a.js                       0.30 KiB / gzip: 0.13 KiB
.svelte-kit/output/client/_app/immutable/components/pages/_lang_/projects/_page.svelte-c887913f.js                                 17.30 KiB / gzip: 6.05 KiB
.svelte-kit/output/client/_app/immutable/modules/pages/_lang_/about/personal-info/education/_layout.ts-dad93944.js                 0.30 KiB / gzip: 0.13 KiB
.svelte-kit/output/client/_app/immutable/modules/pages/_lang_/about/personal-info/bio/_page.ts-922b4f1b.js                         0.20 KiB / gzip: 0.10 KiB
.svelte-kit/output/client/_app/immutable/modules/pages/_lang_/about/personal-info/bio/looking-for/_page.ts-8e57a580.js             0.21 KiB / gzip: 0.10 KiB
.svelte-kit/output/client/_app/immutable/modules/pages/_lang_/about/personal-info/education/projects/_page.ts-d8932fe7.js          0.24 KiB / gzip: 0.13 KiB
.svelte-kit/output/client/_app/immutable/modules/pages/_lang_/about/personal-info/education/schools/_page.ts-6791bb75.js           0.24 KiB / gzip: 0.13 KiB
.svelte-kit/output/client/_app/immutable/modules/pages/_lang_/contact/_page.ts-d24c7115.js                                         0.29 KiB / gzip: 0.15 KiB
.svelte-kit/output/client/_app/immutable/modules/pages/_lang_/projects/_page.ts-c3478ccb.js                                        0.25 KiB / gzip: 0.14 KiB
.svelte-kit/output/client/_app/immutable/chunks/singletons-e6a5c098.js                                                             1.16 KiB / gzip: 0.69 KiB
.svelte-kit/output/client/_app/immutable/chunks/index-e76970dc.js                                                                  0.80 KiB / gzip: 0.49 KiB
.svelte-kit/output/client/_app/immutable/chunks/preload-helper-aa6bc0ce.js                                                         0.70 KiB / gzip: 0.43 KiB
.svelte-kit/output/client/_app/immutable/chunks/stores-c92b42af.js                                                                 0.61 KiB / gzip: 0.35 KiB
.svelte-kit/output/client/_app/immutable/chunks/routing-6d0bcd94.js                                                                1.09 KiB / gzip: 0.44 KiB
.svelte-kit/output/client/_app/immutable/chunks/env-b36e993f.js                                                                    0.46 KiB / gzip: 0.31 KiB
.svelte-kit/output/client/_app/immutable/chunks/index-236c7eb1.js                                                                  12.29 KiB / gzip: 5.06 KiB
.svelte-kit/output/client/_app/immutable/chunks/profile-21951759.js                                                                2.33 KiB / gzip: 0.66 KiB
.svelte-kit/output/client/_app/immutable/chunks/_commonjsHelpers-094ef602.js                                                       0.13 KiB / gzip: 0.09 KiB
.svelte-kit/output/client/_app/immutable/chunks/SvgIcon-6df7cede.js                                                                1.78 KiB / gzip: 0.99 KiB
.svelte-kit/output/client/_app/immutable/chunks/PageTitle-2984e2c5.js                                                              1.83 KiB / gzip: 0.91 KiB
.svelte-kit/output/client/_app/immutable/chunks/index-f37614db.js                                                                  15.43 KiB / gzip: 4.92 KiB
.svelte-kit/output/client/_app/immutable/chunks/_layout-37a896da.js                                                                9.80 KiB / gzip: 3.96 KiB
.svelte-kit/output/client/_app/immutable/chunks/nav-1b0db161.js                                                                    0.24 KiB / gzip: 0.15 KiB
.svelte-kit/output/client/_app/immutable/chunks/title-d8b87d14.js                                                                  0.25 KiB / gzip: 0.16 KiB
.svelte-kit/output/client/_app/immutable/chunks/_layout-0a42b11c.js                                                                0.25 KiB / gzip: 0.21 KiB
.svelte-kit/output/client/_app/immutable/chunks/_layout-5bf83028.js                                                                0.22 KiB / gzip: 0.19 KiB
.svelte-kit/output/client/_app/immutable/chunks/nav-f0ce3bb5.js                                                                    1.18 KiB / gzip: 0.35 KiB
.svelte-kit/output/client/_app/immutable/chunks/_layout-b91b4caa.js                                                                0.23 KiB / gzip: 0.19 KiB
.svelte-kit/output/client/_app/immutable/chunks/_page-1cd1313d.js                                                                  0.19 KiB / gzip: 0.17 KiB
.svelte-kit/output/client/_app/immutable/chunks/PageNav-b552356b.js                                                                15.12 KiB / gzip: 4.30 KiB
.svelte-kit/output/client/_app/immutable/chunks/_page-da7409c9.js                                                                  0.19 KiB / gzip: 0.17 KiB
.svelte-kit/output/client/_app/immutable/chunks/PageTextContent-ae4fcfdc.js                                                        1.44 KiB / gzip: 0.63 KiB
.svelte-kit/output/client/_app/immutable/chunks/schools-539a17f7.js                                                                0.37 KiB / gzip: 0.21 KiB
.svelte-kit/output/client/_app/immutable/chunks/services-abf57f51.js                                                               1.50 KiB / gzip: 0.75 KiB
.svelte-kit/output/client/_app/immutable/chunks/_page-42554107.js                                                                  0.21 KiB / gzip: 0.19 KiB
.svelte-kit/output/client/_app/immutable/chunks/_page-7a8dc525.js                                                                  0.20 KiB / gzip: 0.18 KiB
.svelte-kit/output/client/_app/immutable/chunks/_page-983cd9c0.js                                                                  0.24 KiB / gzip: 0.20 KiB
.svelte-kit/output/client/_app/immutable/chunks/projects-fd99c3f4.js                                                               0.70 KiB / gzip: 0.36 KiB
.svelte-kit/output/client/_app/immutable/chunks/0-67743cc0.js                                                                      0.50 KiB / gzip: 0.29 KiB
.svelte-kit/output/client/_app/immutable/chunks/1-f75801d5.js                                                                      0.30 KiB / gzip: 0.19 KiB
.svelte-kit/output/client/_app/immutable/chunks/_page-45f965a3.js                                                                  0.31 KiB / gzip: 0.23 KiB
.svelte-kit/output/client/_app/immutable/chunks/2-3cafd050.js                                                                      0.54 KiB / gzip: 0.29 KiB
.svelte-kit/output/client/_app/immutable/chunks/3-cd07e937.js                                                                      0.40 KiB / gzip: 0.24 KiB
.svelte-kit/output/client/_app/immutable/chunks/4-7fb20d50.js                                                                      0.32 KiB / gzip: 0.20 KiB
.svelte-kit/output/client/_app/immutable/chunks/5-55122b42.js                                                                      0.39 KiB / gzip: 0.23 KiB
.svelte-kit/output/client/_app/immutable/chunks/6-700df157.js                                                                      0.50 KiB / gzip: 0.29 KiB
.svelte-kit/output/client/_app/immutable/chunks/7-8bf84303.js                                                                      0.51 KiB / gzip: 0.29 KiB
.svelte-kit/output/client/_app/immutable/chunks/9-002535af.js                                                                      0.45 KiB / gzip: 0.27 KiB
.svelte-kit/output/client/_app/immutable/chunks/10-449b7e61.js                                                                     0.56 KiB / gzip: 0.30 KiB
.svelte-kit/output/client/_app/immutable/chunks/11-bce79bd1.js                                                                     0.62 KiB / gzip: 0.34 KiB
.svelte-kit/output/client/_app/immutable/chunks/8-5be84ce4.js                                                                      0.60 KiB / gzip: 0.33 KiB
.svelte-kit/output/client/_app/immutable/chunks/Project-d79751f1.js                                                                26.02 KiB / gzip: 9.83 KiB
.svelte-kit/output/client/_app/immutable/chunks/common-81155a17.js                                                                 0.24 KiB / gzip: 0.19 KiB
.svelte-kit/output/client/_app/immutable/chunks/error-8cc41f94.js                                                                  0.14 KiB / gzip: 0.13 KiB
.svelte-kit/output/client/_app/immutable/chunks/error-672f97cb.js                                                                  0.15 KiB / gzip: 0.14 KiB
.svelte-kit/output/client/_app/immutable/chunks/common-320eda19.js                                                                 0.21 KiB / gzip: 0.17 KiB
.svelte-kit/output/client/_app/immutable/chunks/home-4099f52f.js                                                                   0.22 KiB / gzip: 0.19 KiB
.svelte-kit/output/client/_app/immutable/chunks/home-aaa51257.js                                                                   0.21 KiB / gzip: 0.18 KiB
.svelte-kit/output/client/_app/immutable/chunks/about-e1e73c83.js                                                                  0.51 KiB / gzip: 0.31 KiB
.svelte-kit/output/client/_app/immutable/chunks/bio-da6b2267.js                                                                    0.10 KiB / gzip: 0.12 KiB
.svelte-kit/output/client/_app/immutable/chunks/bio-363cf2f8.js                                                                    0.10 KiB / gzip: 0.12 KiB
.svelte-kit/output/client/_app/immutable/chunks/about-bf1fc6c5.js                                                                  0.47 KiB / gzip: 0.28 KiB
.svelte-kit/output/client/_app/immutable/chunks/looking-for-d8165684.js                                                            0.11 KiB / gzip: 0.12 KiB
.svelte-kit/output/client/_app/immutable/chunks/looking-for-7a3292b3.js                                                            0.11 KiB / gzip: 0.12 KiB
.svelte-kit/output/client/_app/immutable/chunks/education-projects-829716f5.js                                                     0.12 KiB / gzip: 0.13 KiB
.svelte-kit/output/client/_app/immutable/chunks/schools-2febcddc.js                                                                0.11 KiB / gzip: 0.12 KiB
.svelte-kit/output/client/_app/immutable/chunks/schools-52e9fde1.js                                                                0.11 KiB / gzip: 0.12 KiB
.svelte-kit/output/client/_app/immutable/chunks/education-projects-5a03fb69.js                                                     0.12 KiB / gzip: 0.12 KiB
.svelte-kit/output/client/_app/immutable/chunks/contact-635e55bd.js                                                                0.48 KiB / gzip: 0.33 KiB
.svelte-kit/output/client/_app/immutable/chunks/projects-a316e8b9.js                                                               0.26 KiB / gzip: 0.20 KiB
.svelte-kit/output/client/_app/immutable/chunks/projects-ffb51aaa.js                                                               0.26 KiB / gzip: 0.19 KiB
.svelte-kit/output/client/_app/immutable/assets/+page-e8fdc8b6.css                                                                 0.32 KiB / gzip: 0.20 KiB
.svelte-kit/output/client/_app/immutable/chunks/contact-319b5ffb.js                                                                0.45 KiB / gzip: 0.30 KiB
.svelte-kit/output/client/_app/immutable/assets/PageTextContent-2cac5837.css                                                       0.30 KiB / gzip: 0.22 KiB
.svelte-kit/output/client/_app/immutable/assets/PageTitle-54dd1467.css                                                             0.96 KiB / gzip: 0.36 KiB
.svelte-kit/output/client/_app/immutable/assets/Project-3d1bf694.css                                                               3.39 KiB / gzip: 0.95 KiB
.svelte-kit/output/client/_app/immutable/assets/PageNav-1db09f01.css                                                               4.47 KiB / gzip: 0.94 KiB
.svelte-kit/output/client/_app/immutable/assets/+layout-8420db0e.css                                                               0.31 KiB / gzip: 0.18 KiB
.svelte-kit/output/client/_app/immutable/assets/+page-616ab023.css                                                                 3.10 KiB / gzip: 0.77 KiB
.svelte-kit/output/client/_app/immutable/assets/+layout-686b183d.css                                                               11.23 KiB / gzip: 3.14 KiB
.svelte-kit/output/client/_app/immutable/assets/+page-4c4f69be.css                                                                 6.42 KiB / gzip: 1.28 KiB
.svelte-kit/output/client/_app/immutable/assets/+page-8c5fd10f.css                                                                 3.63 KiB / gzip: 1.00 KiB
vite v3.0.9 building SSR bundle for production...
✓ 196 modules transformed.
.svelte-kit/output/server/vite-manifest.json                                                               17.38 KiB
.svelte-kit/output/server/index.js                                                                         63.55 KiB
.svelte-kit/output/server/entries/endpoints/_server.ts.js                                                  0.37 KiB
.svelte-kit/output/server/entries/endpoints/_lang_/about/_server.ts.js                                     0.34 KiB
.svelte-kit/output/server/entries/endpoints/_lang_/about/personal-info/_server.ts.js                       0.35 KiB
.svelte-kit/output/server/entries/endpoints/_lang_/about/personal-info/education/_server.ts.js             0.37 KiB
.svelte-kit/output/server/entries/pages/_layout.svelte.js                                                  16.36 KiB
.svelte-kit/output/server/entries/pages/_layout.ts.js                                                      0.68 KiB
.svelte-kit/output/server/entries/pages/_layout.server.ts.js                                               1.36 KiB
.svelte-kit/output/server/entries/pages/_error.svelte.js                                                   1.36 KiB
.svelte-kit/output/server/entries/pages/_lang_/about/_layout.svelte.js                                     3.30 KiB
.svelte-kit/output/server/entries/pages/_lang_/about/_layout.ts.js                                         0.37 KiB
.svelte-kit/output/server/entries/pages/_lang_/about/personal-info/bio/_layout.svelte.js                   2.34 KiB
.svelte-kit/output/server/entries/pages/_lang_/about/personal-info/bio/_layout.ts.js                       0.34 KiB
.svelte-kit/output/server/entries/pages/_lang_/about/personal-info/education/_layout.svelte.js             0.24 KiB
.svelte-kit/output/server/entries/pages/_lang_/about/personal-info/education/_layout.ts.js                 0.36 KiB
.svelte-kit/output/server/entries/pages/_lang_/_page.svelte.js                                             14.38 KiB
.svelte-kit/output/server/entries/pages/_lang_/about/personal-info/bio/_page.svelte.js                     3.14 KiB
.svelte-kit/output/server/entries/pages/_lang_/about/personal-info/bio/_page.ts.js                         0.20 KiB
.svelte-kit/output/server/entries/pages/_lang_/about/personal-info/bio/looking-for/_page.svelte.js         3.23 KiB
.svelte-kit/output/server/entries/pages/_lang_/about/personal-info/bio/looking-for/_page.ts.js             0.21 KiB
.svelte-kit/output/server/entries/pages/_lang_/about/personal-info/education/projects/_page.svelte.js      3.58 KiB
.svelte-kit/output/server/entries/pages/_lang_/about/personal-info/education/projects/_page.ts.js          0.28 KiB
.svelte-kit/output/server/entries/pages/_lang_/about/personal-info/education/projects/_page.server.ts.js   1.25 KiB
.svelte-kit/output/server/entries/pages/_lang_/about/personal-info/education/schools/_page.svelte.js       2.27 KiB
.svelte-kit/output/server/entries/pages/_lang_/about/personal-info/education/schools/_page.ts.js           0.25 KiB
.svelte-kit/output/server/entries/pages/_lang_/about/personal-info/education/schools/_page.server.ts.js    0.99 KiB
.svelte-kit/output/server/entries/pages/_lang_/contact/_page.svelte.js                                     11.38 KiB
.svelte-kit/output/server/entries/pages/_lang_/contact/_page.ts.js                                         0.36 KiB
.svelte-kit/output/server/entries/pages/_lang_/projects/_page.svelte.js                                    13.78 KiB
.svelte-kit/output/server/entries/pages/_lang_/projects/_page.ts.js                                        0.42 KiB
.svelte-kit/output/server/entries/pages/_lang_/projects/_page.server.ts.js                                 1.69 KiB
.svelte-kit/output/server/chunks/index.js                                                                  7.89 KiB
.svelte-kit/output/server/chunks/index2.js                                                                 0.93 KiB
.svelte-kit/output/server/chunks/index3.js                                                                 2.27 KiB
.svelte-kit/output/server/chunks/langs.enum.js                                                             0.17 KiB
.svelte-kit/output/server/chunks/routing.js                                                                1.90 KiB
.svelte-kit/output/server/chunks/stores.js                                                                 0.99 KiB
.svelte-kit/output/server/chunks/env.js                                                                    0.76 KiB
.svelte-kit/output/server/chunks/profile.js                                                                4.30 KiB
.svelte-kit/output/server/chunks/index4.js                                                                 4.71 KiB
.svelte-kit/output/server/chunks/SvgIcon.js                                                                2.12 KiB
.svelte-kit/output/server/chunks/graphql.js                                                                0.34 KiB
.svelte-kit/output/server/chunks/PageTitle.js                                                              2.73 KiB
.svelte-kit/output/server/chunks/PageNav.js                                                                12.53 KiB
.svelte-kit/output/server/chunks/nav.js                                                                    0.69 KiB
.svelte-kit/output/server/chunks/title.js                                                                  0.60 KiB
.svelte-kit/output/server/chunks/nav2.js                                                                   1.78 KiB
.svelte-kit/output/server/chunks/PageTextContent.js                                                        1.46 KiB
.svelte-kit/output/server/chunks/Project.js                                                                17.16 KiB
.svelte-kit/output/server/chunks/schools.js                                                                0.72 KiB
.svelte-kit/output/server/chunks/services.js                                                               2.80 KiB
.svelte-kit/output/server/chunks/projects.js                                                               1.47 KiB
.svelte-kit/output/server/chunks/hooks.js                                                                  0.72 KiB
.svelte-kit/output/server/chunks/common.js                                                                 0.31 KiB
.svelte-kit/output/server/chunks/common2.js                                                                0.29 KiB
.svelte-kit/output/server/chunks/error.js                                                                  0.19 KiB
.svelte-kit/output/server/chunks/error2.js                                                                 0.18 KiB
.svelte-kit/output/server/chunks/home.js                                                                   0.29 KiB
.svelte-kit/output/server/chunks/home2.js                                                                  0.27 KiB
.svelte-kit/output/server/chunks/about.js                                                                  0.67 KiB
.svelte-kit/output/server/chunks/about2.js                                                                 0.63 KiB
.svelte-kit/output/server/chunks/bio.js                                                                    0.14 KiB
.svelte-kit/output/server/chunks/bio2.js                                                                   0.14 KiB
.svelte-kit/output/server/chunks/looking-for.js                                                            0.16 KiB
.svelte-kit/output/server/chunks/looking-for2.js                                                           0.16 KiB
.svelte-kit/output/server/chunks/schools2.js                                                               0.15 KiB
.svelte-kit/output/server/chunks/schools3.js                                                               0.15 KiB
.svelte-kit/output/server/chunks/education-projects.js                                                     0.18 KiB
.svelte-kit/output/server/chunks/education-projects2.js                                                    0.18 KiB
.svelte-kit/output/server/chunks/contact.js                                                                0.62 KiB
.svelte-kit/output/server/chunks/contact2.js                                                               0.58 KiB
.svelte-kit/output/server/chunks/projects2.js                                                              0.35 KiB
.svelte-kit/output/server/chunks/projects3.js                                                              0.35 KiB

Run npm run preview to preview your production build locally.

> Using @sveltejs/adapter-netlify
✘ [ERROR] Top-level await is not available in the configured target environment ("es2020")

    .svelte-kit/netlify-tmp/entry.js:7:0:
      7 │ await server.init({
        ╵ ~~~~~

error during build:
Error: Build failed with 1 error:
.svelte-kit/netlify-tmp/entry.js:7:0: ERROR: Top-level await is not available in the configured target environment ("es2020")
    at failureErrorWithLog (/Users/mickael/Workspace/svelte-portfolio/node_modules/esbuild/lib/main.js:1605:15)
    at /Users/mickael/Workspace/svelte-portfolio/node_modules/esbuild/lib/main.js:1251:28
    at runOnEndCallbacks (/Users/mickael/Workspace/svelte-portfolio/node_modules/esbuild/lib/main.js:1164:65)
    at buildResponseToResult (/Users/mickael/Workspace/svelte-portfolio/node_modules/esbuild/lib/main.js:1249:7)
    at /Users/mickael/Workspace/svelte-portfolio/node_modules/esbuild/lib/main.js:1358:14
    at /Users/mickael/Workspace/svelte-portfolio/node_modules/esbuild/lib/main.js:666:9
    at handleIncomingPacket (/Users/mickael/Workspace/svelte-portfolio/node_modules/esbuild/lib/main.js:763:9)
    at Socket.readFromStdout (/Users/mickael/Workspace/svelte-portfolio/node_modules/esbuild/lib/main.js:632:7)
    at Socket.emit (node:events:527:28)
    at addChunk (node:internal/streams/readable:315:12)
```

### System Info

```shell
System:
    OS: macOS 12.5
    CPU: (12) x64 Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz
    Memory: 44.67 MB / 16.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 16.16.0 - ~/.nvm/versions/node/v16.16.0/bin/node
    Yarn: 1.22.19 - ~/.yvm/shim/yarn
    npm: 8.11.0 - ~/.nvm/versions/node/v16.16.0/bin/npm
  Browsers:
    Brave Browser: 101.1.38.109
    Chrome: 104.0.5112.101
    Edge: 104.0.1293.70
    Firefox: 94.0.1
    Safari: 15.6
    Safari Technology Preview: 16.0
  npmPackages:
    @sveltejs/adapter-netlify: 1.0.0-next.73 => 1.0.0-next.73 
    @sveltejs/kit: 1.0.0-next.445 => 1.0.0-next.445 
    svelte: ^3.49.0 => 3.49.0 
    vite: ^3.0.9 => 3.0.9
```

### Severity

serious, but I can work around it

**Comment by squelix** [comment]
Link to this issue I guess => https://github.com/sveltejs/kit/issues/6308

**Comment by squelix** [comment]
Linked to this fix too => https://github.com/sveltejs/kit/pull/6327

**Comment by dummdidumm** [comment]
It says `Top-level await is not available in the configured target environment ("es2020")` - is that what you have set in your `tsconfig.json`? If yes, bump it to `es2022` and try again.

**Comment by squelix** [comment]
Still have the bug with 
```
"module": "es2022",
"target": "es2022",
```
in my `tsconfig.json`

**Comment by flaming-codes** [comment]
The same applies to the Vercel-adapter. https://github.com/sveltejs/kit/pull/6327 fixed the initial regression introduced by https://github.com/sveltejs/kit/pull/6179 but introduced this new one.

**Comment by benmccann** [comment]
@squelix does your project have `node_bundler = "esbuild"` set in the Netlify config? Does it work if you remove that?

I don't think esbuild supports top-level await: https://github.com/evanw/esbuild/issues/253

**Comment by benmccann** [comment]
@tcc-sejohnson I'm not sure we can rely on top-level await to call the server init function in the Vercel adapter
