### ISSUE TITLE
Svelte-kit sync fails on install

### ISSUE THREAD

**Issue by MajesticString** [sveltejs/kit#6418]
### Describe the bug

Currently, when I scaffold a new project with `npm init`, when the postinstall script runs, I get an error which blocks the installation.
```sh
node_modules/.pnpm/@sveltejs+kit@1.0.0-next.452_fhgkwirxvgjw2igda6zmhiisma/node_modules/@sveltejs/kit: Running postinstall script, failed in 585ms
.../node_modules/@sveltejs/kit postinstall$ node svelte-kit.js sync
│ > ENOENT: no such file or directory, open '/workspaces/kamp-schedule/node_modules/.pnpm/@sveltejs+kit@1.0.0-next.452_fhgkwirxvgjw2igda6zmhiisma/node_modules/
│     at Object.openSync (node:fs:585:3)
│     at Object.readFileSync (node:fs:453:35)
│     at read_description (file:///workspaces/kamp-schedule/node_modules/.pnpm/@sveltejs+kit@1.0.0-next.452_fhgkwirxvgjw2igda6zmhiisma/node_modules/@sveltejs/k
│     at template (file:///workspaces/kamp-schedule/node_modules/.pnpm/@sveltejs+kit@1.0.0-next.452_fhgkwirxvgjw2igda6zmhiisma/node_modules/@sveltejs/kit/src/c
│     at write_ambient (file:///workspaces/kamp-schedule/node_modules/.pnpm/@sveltejs+kit@1.0.0-next.452_fhgkwirxvgjw2igda6zmhiisma/node_modules/@sveltejs/kit/
│     at init (file:///workspaces/kamp-schedule/node_modules/.pnpm/@sveltejs+kit@1.0.0-next.452_fhgkwirxvgjw2igda6zmhiisma/node_modules/@sveltejs/kit/src/core/
│     at Module.all (file:///workspaces/kamp-schedule/node_modules/.pnpm/@sveltejs+kit@1.0.0-next.452_fhgkwirxvgjw2igda6zmhiisma/node_modules/@sveltejs/kit/src
│     at file:///workspaces/kamp-schedule/node_modules/.pnpm/@sveltejs+kit@1.0.0-next.452_fhgkwirxvgjw2igda6zmhiisma/node_modules/@sveltejs/kit/src/cli.js:56:1
└─ Failed in 586ms
 ELIFECYCLE  Command failed with exit code 1.
```

### Reproduction

* Create a new project with `npm init`, `pnpm create`, etc.
* Install deps with `npm i`, `pnpm i`, `yarn`, etc.
* See error

### Logs

```shell
.../node_modules/@sveltejs/kit postinstall$ node svelte-kit.js sync
│ > ENOENT: no such file or directory, open '/workspaces/kamp-schedule/node_modules/.pnpm/@sveltejs+kit@1.0.0-next.452_fhgkwirxvgjw2igda6zmhiisma/node_modules/
│     at Object.openSync (node:fs:585:3)
│     at Object.readFileSync (node:fs:453:35)
│     at read_description (file:///workspaces/kamp-schedule/node_modules/.pnpm/@sveltejs+kit@1.0.0-next.452_fhgkwirxvgjw2igda6zmhiisma/node_modules/@sveltejs/k
│     at template (file:///workspaces/kamp-schedule/node_modules/.pnpm/@sveltejs+kit@1.0.0-next.452_fhgkwirxvgjw2igda6zmhiisma/node_modules/@sveltejs/kit/src/c
│     at write_ambient (file:///workspaces/kamp-schedule/node_modules/.pnpm/@sveltejs+kit@1.0.0-next.452_fhgkwirxvgjw2igda6zmhiisma/node_modules/@sveltejs/kit/
│     at init (file:///workspaces/kamp-schedule/node_modules/.pnpm/@sveltejs+kit@1.0.0-next.452_fhgkwirxvgjw2igda6zmhiisma/node_modules/@sveltejs/kit/src/core/
│     at Module.all (file:///workspaces/kamp-schedule/node_modules/.pnpm/@sveltejs+kit@1.0.0-next.452_fhgkwirxvgjw2igda6zmhiisma/node_modules/@sveltejs/kit/src
│     at file:///workspaces/kamp-schedule/node_modules/.pnpm/@sveltejs+kit@1.0.0-next.452_fhgkwirxvgjw2igda6zmhiisma/node_modules/@sveltejs/kit/src/cli.js:56:1
└─ Failed in 586ms
 ELIFECYCLE  Command failed with exit code 1.
```
```


### System Info

```shell
System:
    OS: Linux 5.4 Ubuntu 20.04.4 LTS (Focal Fossa)
    CPU: (4) x64 Intel(R) Xeon(R) Platinum 8370C CPU @ 2.80GHz
    Memory: 4.98 GB / 7.77 GB
    Container: Yes
    Shell: 5.0.17 - /bin/bash
  Binaries:
    Node: 16.14.2 - ~/.nodejs/current/bin/node
    Yarn: 1.22.15 - /opt/yarn/stable/bin/yarn
    npm: 8.5.0 - ~/.nodejs/current/bin/npm
  npmPackages:
    @sveltejs/adapter-auto: next => 1.0.0-next.69 
    @sveltejs/kit: next => 1.0.0-next.452 
    svelte: ^3.44.0 => 3.49.0 
    vite: ^3.1.0-beta.1 => 3.1.0-beta.1
```

### Severity

blocking an upgrade

**Comment by tcc-sejohnson** [comment]
Should be fixed by https://github.com/sveltejs/kit/pull/6416
