### ISSUE TITLE
[vite-plugin-svelte-kit] Error running plugin hook writeBundle for vite-plugin-svelte-kit, expected a function hook.

### ISSUE THREAD

**Issue by HenrijsS** [sveltejs/kit#6487]
### Describe the bug

After updateing to Version 1.0.0-next.458 and migrating to all the new changes, I can't seem to build the page.

Started with Adapter-CloudFlare and then with Adapter-Auto but it seems to make no difference.

Looks like there's a problem with the Vite plugin. I guess it's tie to svelte-kit and not Vite itself.

This also seems to be ocurring to one other user who [reported it on Stackoverflow 18h ago](https://stackoverflow.com/questions/73549633/vitesveltekit-build-failing)

### Reproduction

https://github.com/HenrijsS/LBTU-ITF

### Logs

From Cloudflare: https://pastebin.com/Dmhj1syF

From local (`yarn build`):
```shell
PS C:\_DEV\_Sites\LBTU-ITF> yarn build
yarn run v1.22.19
$ vite build
vite v3.0.9 building for production...
transforming (34) src\routes\+layout.ts
🌼 daisyUI components 2.24.0  https://github.com/saadeghi/daisyui
  ✔︎ Including:  base, components, themes[1], utilities
  
transforming (56) src\lib\components\iframeComp.svelte
🌼 daisyUI components 2.24.0  https://github.com/saadeghi/daisyui
  ✔︎ Including:  base, components, themes[1], utilities
  
✓ 67 modules transformed.
.svelte-kit/output/client/_app/immutable/assets/lv_logo-2624bf41.svg                                    108.20 KiB
.svelte-kit/output/client/_app/immutable/assets/itf_logo-2917a315.svg                                   1.29 KiB
.svelte-kit/output/client/_app/immutable/assets/fira-mono-cyrillic-ext-400-normal-3df7909e.woff2        15.40 KiB
.svelte-kit/output/client/_app/immutable/assets/fira-mono-greek-ext-400-normal-9e2fe623.woff2           7.33 KiB
.svelte-kit/output/client/_app/immutable/assets/fira-mono-cyrillic-400-normal-c7d433fd.woff2            8.89 KiB
.svelte-kit/output/client/_app/immutable/assets/fira-mono-greek-400-normal-a8be01ce.woff2               10.27 KiB
.svelte-kit/output/client/_app/immutable/assets/fira-mono-latin-ext-400-normal-6bfabd30.woff2           11.10 KiB
.svelte-kit/output/client/_app/immutable/assets/fira-mono-latin-400-normal-e43b3538.woff2               15.90 KiB
.svelte-kit/output/client/_app/immutable/assets/fira-mono-all-400-normal-1e3b098c.woff                  75.55 KiB
.svelte-kit/output/client/vite-manifest.json                                                            12.14 KiB
[vite-plugin-svelte-kit] Error running plugin hook writeBundle for vite-plugin-svelte-kit, expected a function hook.
error during build:
Error: Error running plugin hook closeBundle for vite-plugin-svelte-kit, expected a function hook.
    at error (file:///C:/_DEV/_Sites/LBTU-ITF/node_modules/rollup/dist/es/shared/rollup.js:1858:30)
    at throwInvalidHookError (file:///C:/_DEV/_Sites/LBTU-ITF/node_modules/rollup/dist/es/shared/rollup.js:22551:12)
    at file:///C:/_DEV/_Sites/LBTU-ITF/node_modules/rollup/dist/es/shared/rollup.js:22692:24
    at async Promise.all (index 0)
    at async Object.close (file:///C:/_DEV/_Sites/LBTU-ITF/node_modules/rollup/dist/es/shared/rollup.js:23662:13)
    at async Promise.all (index 0)
    at async build (file:///C:/_DEV/_Sites/LBTU-ITF/node_modules/vite/dist/node/chunks/dep-0fc8e132.js:43473:13)
    at async CAC.<anonymous> (file:///C:/_DEV/_Sites/LBTU-ITF/node_modules/vite/dist/node/cli.js:747:9)
error Command failed with exit code 1.
```

### System Info

```shell
System:
    OS: Windows 10 10.0.22000
    CPU: (16) x64 AMD Ryzen 7 5800H with Radeon Graphics
    Memory: 4.19 GB / 15.86 GB
  Binaries:
    Node: 16.15.0 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.19 - C:\Program Files\nodejs\yarn.CMD
    npm: 8.14.0 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Edge: Spartan (44.22000.120.0), Chromium (104.0.1293.70)
    Internet Explorer: 11.0.22000.120
```

### Severity

blocking all usage of SvelteKit

**Comment by HenrijsS** [comment]
I did some version hopping and it seems like it breaks on v450: https://github.com/sveltejs/kit/releases/tag/%40sveltejs%2Fkit%401.0.0-next.450

Didn't seem to notice anywhere to update Vite to 3.1
Is that the solution?

**Comment by claudiorivera** [comment]
Yeah, 450+ has a peer dependency of `vite@^3.1.0-beta.1`.

People who have pinned their dependencies and use automated dependency updates (like with Renovate Bot) may find `@sveltejs/kit` is getting updated to 450+, but `vite` remains at `3.0.9` (latest stable). (ie. `unmet peer vite@^3.1.0-beta.1: found 3.0.9`), which throws the `writeBundle` error during build.

The workaround, like @HenrijsS mentioned, is to update `vite` in your `package.json`.

**Comment by dominikg** [comment]
As mentioned you should get a peer dependency error for vite 3.0.9 when installing a version of kit that required 3.1. Please check those warnings and act on them.
