### ISSUE TITLE
get/set/hasContext doesn't work in production code outside a component

### ISSUE THREAD

**Issue by ciscoheat** [sveltejs/kit#6501]
### Describe the bug

I'm trying to use the context functions in library code. They work when using both `vite dev` and `vite preview`. But when publishing to npm and including the library from there, an exception is thrown (see the logs).

### Reproduction

1. Create a new sveltekit todo app
2. Add this code to +layout.svelte:

```typescript
import { Flash } from "sveltekit-flash-message/client"
import { page } from '$app/stores'

const flash = new Flash(page)
const message = flash.message
```

## Explanation

`new Flash(page)` calls `hasContext` in its constructor, throwing the error since `hasContext` cannot find `current_component` at that point. Code:
https://github.com/ciscoheat/sveltekit-flash-message/blob/c5198a35b724d53e0eab780e16d09c7c5c1499fb/src/lib/client.ts#L61-L66

## Stackblitz reproduction

https://stackblitz.com/edit/sveltejs-kit-template-default-ask2u7?file=src%2Froutes%2F%2Blayout.svelte&terminal=dev

### Logs

```shell
Error: Function called outside component initialization
    at get_current_component (file:///E:/Projects/TEST/svelte-next/node_modules/.pnpm/svelte@3.49.0/node_modules/svelte/internal/index.mjs:953:15)
    at hasContext (file:///E:/Projects/TEST/svelte-next/node_modules/.pnpm/svelte@3.49.0/node_modules/svelte/internal/index.mjs:995:12)
    at debugflash (file:///E:/Projects/TEST/svelte-next/node_modules/.pnpm/sveltekit-flash-message@0.6.6/node_modules/sveltekit-flash-message/client.js:52:7)
    at file:///E:/Projects/TEST/svelte-next/.svelte-kit/output/server/entries/pages/_layout.svelte.js:16:3
    at Object.$$render (file:///E:/Projects/TEST/svelte-next/.svelte-kit/output/server/chunks/index.js:89:18)
    at file:///E:/Projects/TEST/svelte-next/.svelte-kit/output/server/index.js:36:97
    at $$render (file:///E:/Projects/TEST/svelte-next/.svelte-kit/output/server/chunks/index.js:89:18)
    at Object.render (file:///E:/Projects/TEST/svelte-next/.svelte-kit/output/server/chunks/index.js:97:20)
    at render_response (file:///E:/Projects/TEST/svelte-next/.svelte-kit/output/server/index.js:938:29)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
```

### System Info

```shell
System:
    OS: Windows 10 10.0.19043
    CPU: (16) x64 Intel(R) Core(TM) i9-9900K CPU @ 3.60GHz
    Memory: 43.25 GB / 63.93 GB
  Binaries:
    Node: 16.16.0 - C:\Program Files\nodejs\node.EXE
    npm: 8.11.0 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Edge: Spartan (44.19041.1266.0), Chromium (104.0.1293.70)
    Internet Explorer: 11.0.19041.1566
  npmPackages:
    @sveltejs/adapter-auto: next => 1.0.0-next.71
    @sveltejs/kit: next => 1.0.0-next.460
    svelte: ^3.49.0 => 3.49.0
    vite: ^3.1.0-beta.1 => 3.1.0-beta.1
```

### Severity

blocking all usage of SvelteKit

**Comment by dummdidumm** [comment]
This sounds like Vite does somehow create a separate Svelte runtime instance for the library. Your package is using `@sveltejs/package` which rules one source of errors out, which is good. I wonder if it's because your package doesn't contain Svelte components, yet it uses functions from it, so vite-plugin-svelte doesn't detect it's related to Svelte and doesn't handle it specifically or something. cc @dominikg @bluwy

**Comment by ciscoheat** [comment]
If you need more information, or can point me in some direction for testing this in more depth, let me know!

**Comment by bluwy** [comment]
I thought this was already fixed via https://github.com/sveltejs/vite-plugin-svelte/issues/360. A workaround for now is to add this in `vite.config.js`:

```
	ssr: {
		noExternal: ['sveltekit-flash-message']
	}
```

**Comment by ciscoheat** [comment]
Tested right away, confirmed that it works with that addition! Can this be fixed, so I don't have to ask library users to add this to their config, thereby increasing the friction?

**Comment by bluwy** [comment]
It should be added automatically but it's not, which sounds like a bug. I'll transfer this over to `vite-plugin-svelte` to track there onwards.
