### ISSUE TITLE
Unavoidable warning when using kit.paths.base when running vite build.

### ISSUE THREAD

**Issue by talwat** [sveltejs/kit#6563]
### Describe the bug

Vite normally recommends the base path to end with a slash, as denoted by this warning when running `npm run build`: `(!) "base" option should end with a slash.`

However, say we remove this, sveltekit will throw its own error: `Error: config.kit.paths.base option must either be the empty string or a root-relative path that starts but doesn't end with '/'. See https://kit.svelte.dev/docs/configuration#paths`

This means that you are unable to get rid of the vite warning.

### Reproduction

First, you need to use `adapter-static` and add `export const prerender = true` to the root layout.

Then, add the `config.kit.paths.base` option without the `/` at the end.

I have recreated the environment in [this](https://github.com/talwat/kit-base-path-error) repo.

Finally, if you try to build it, I ran `npm run build`, you will receive the warning.

### Logs

```txt
Log with / at the end:

error during build:
Error: config.kit.paths.base option must either be the empty string or a root-relative path that starts but doesn't end with '/'. See https://kit.svelte.dev/docs/configuration#paths
    at file:///Users/tal/Temporary%20Code/kit-base-path-error/node_modules/@sveltejs/kit/src/core/config/options.js:200:13
    at file:///Users/tal/Temporary%20Code/kit-base-path-error/node_modules/@sveltejs/kit/src/core/config/options.js:389:43
    at file:///Users/tal/Temporary%20Code/kit-base-path-error/node_modules/@sveltejs/kit/src/core/config/options.js:375:18
    at file:///Users/tal/Temporary%20Code/kit-base-path-error/node_modules/@sveltejs/kit/src/core/config/options.js:375:18
    at file:///Users/tal/Temporary%20Code/kit-base-path-error/node_modules/@sveltejs/kit/src/core/config/options.js:375:18
    at validate_config (file:///Users/tal/Temporary%20Code/kit-base-path-error/node_modules/@sveltejs/kit/src/core/config/index.js:104:9)
    at process_config (file:///Users/tal/Temporary%20Code/kit-base-path-error/node_modules/@sveltejs/kit/src/core/config/index.js:72:20)
    at load_config (file:///Users/tal/Temporary%20Code/kit-base-path-error/node_modules/@sveltejs/kit/src/core/config/index.js:64:9)
    at async config (file:///Users/tal/Temporary%20Code/kit-base-path-error/node_modules/@sveltejs/kit/src/exports/vite/index.js:200:20)
    at async resolveConfig (file:///Users/tal/Temporary%20Code/kit-base-path-error/node_modules/vite/dist/node/chunks/dep-d66eb979.js:62958:25)

Log without / at the end:

vite v3.1.0-beta.2 building for production...
✓ 32 modules transformed.
(!) "base" option should end with a slash.
vite v3.1.0-beta.2 building SSR bundle for production...
✓ 43 modules transformed.
Generated an empty chunk: "hooks"
.svelte-kit/output/server/vite-manifest.json                   1.23 KiB
.svelte-kit/output/server/index.js                             65.22 KiB
.svelte-kit/output/server/entries/fallbacks/layout.svelte.js   0.23 KiB
.svelte-kit/output/server/entries/pages/_layout.js             0.05 KiB
.svelte-kit/output/server/entries/fallbacks/error.svelte.js    1.50 KiB
.svelte-kit/output/server/entries/pages/_page.svelte.js        0.31 KiB
.svelte-kit/output/server/chunks/index.js                      3.10 KiB
.svelte-kit/output/server/chunks/hooks.js                      0.00 KiB

Run npm run preview to preview your production build locally.
.svelte-kit/output/client/vite-manifest.json                                         2.65 KiB
.svelte-kit/output/client/_app/immutable/components/layout.svelte-2d008a8e.js        0.53 KiB / gzip: 0.35 KiB
.svelte-kit/output/client/_app/immutable/components/pages/_page.svelte-f7466cca.js   0.81 KiB / gzip: 0.47 KiB
.svelte-kit/output/client/_app/immutable/components/error.svelte-3d6f3230.js         2.07 KiB / gzip: 0.95 KiB
.svelte-kit/output/client/_app/immutable/modules/pages/_layout.js-7b9cbfbc.js        0.07 KiB / gzip: 0.08 KiB
.svelte-kit/output/client/_app/immutable/chunks/singletons-f8ed2eeb.js               1.81 KiB / gzip: 0.99 KiB
.svelte-kit/output/client/_app/immutable/chunks/_layout-8d2a742b.js                  0.14 KiB / gzip: 0.14 KiB
.svelte-kit/output/client/_app/immutable/chunks/index-4f5b2732.js                    6.62 KiB / gzip: 2.70 KiB
.svelte-kit/output/client/_app/immutable/chunks/1-bef9a7aa.js                        0.15 KiB / gzip: 0.13 KiB
.svelte-kit/output/client/_app/immutable/chunks/2-2f149db4.js                        0.12 KiB / gzip: 0.12 KiB
.svelte-kit/output/client/_app/immutable/chunks/0-b5431218.js                        0.17 KiB / gzip: 0.14 KiB
.svelte-kit/output/client/_app/immutable/start-3d400377.js                           22.50 KiB / gzip: 8.90 KiB

> Using @sveltejs/adapter-static
  Wrote site to "build"
  ✔ done
```

### System Info

```shell
System:
    OS: macOS 12.5.1
    CPU: (8) arm64 Apple M1
    Memory: 130.48 MB / 16.00 GB
    Shell: 5.8.1 - /bin/zsh
Binaries:
    Node: 16.17.0 - /opt/homebrew/opt/node@16/bin/node
    npm: 8.15.0 - /opt/homebrew/opt/node@16/bin/npm
Browsers:
    Chrome: 104.0.5112.101
    Firefox: 104.0.1
    Safari: 15.6.1
```

### Severity

annoyance

### Additional Information

This prevents sveltekit from fully integrating with vite without warnings. It is not a severe issue but something that should be fixed before the first stable release. The base path feature is significant because it is necessary for use with github-pages.

**Comment by charbelnicolas** [comment]
Yep, I get the same warning when doing `npm run build` with the static adapter
