### ISSUE TITLE
config.kit.files.hooks not working with default path settings in svelte config but works with single file path server or client hooks file

### ISSUE THREAD

**Issue by souravjamwal77** [sveltejs/kit#6989]
### Describe the bug

Hi SvelteKit Team,

I had my hooks file (`hooks.server.js`) placed in the `src/` directory as the documentation suggests and I didn't make any changes to the default config path. With the default file and path settings, SvelteKit couldn't find `hooks.server.js`. So, I added the below lines myself so that Kit can recognize the `hooks.server.js` path following the configuration docs:-
```
kit : {
    ...
      files: {
          hooks: {
             client: 'src/hooks.client',
             server: 'src/hooks.server'
      },
     .....
```

With these settings, Kit gave me the following error 

```
error when starting dev server:
Error: config.kit.files.hooks should be a string, if specified
    at assert_string (file:///home/souravjamwal77/Desktop/projects/sample_test/svelte_sourav.fun/node_modules/@sveltejs/kit/src/core/config/options.js:479:9)
    at file:///home/souravjamwal77/Desktop/projects/sample_test/svelte_sourav.fun/node_modules/@sveltejs/kit/src/core/config/options.js:390:3
    at file:///home/souravjamwal77/Desktop/projects/sample_test/svelte_sourav.fun/node_modules/@sveltejs/kit/src/core/config/options.js:379:43
    at file:///home/souravjamwal77/Desktop/projects/sample_test/svelte_sourav.fun/node_modules/@sveltejs/kit/src/core/config/options.js:365:18
    at file:///home/souravjamwal77/Desktop/projects/sample_test/svelte_sourav.fun/node_modules/@sveltejs/kit/src/core/config/options.js:365:18
    at file:///home/souravjamwal77/Desktop/projects/sample_test/svelte_sourav.fun/node_modules/@sveltejs/kit/src/core/config/options.js:365:18
    at validate_config (file:///home/souravjamwal77/Desktop/projects/sample_test/svelte_sourav.fun/node_modules/@sveltejs/kit/src/core/config/index.js:104:9)
    at process_config (file:///home/souravjamwal77/Desktop/projects/sample_test/svelte_sourav.fun/node_modules/@sveltejs/kit/src/core/config/index.js:72:20)
    at load_config (file:///home/souravjamwal77/Desktop/projects/sample_test/svelte_sourav.fun/node_modules/@sveltejs/kit/src/core/config/index.js:64:9)
    at async config (file:///home/souravjamwal77/Desktop/projects/sample_test/svelte_sourav.fun/node_modules/@sveltejs/kit/src/exports/vite/index.js:197:20)

```

Then, I had to change the path like below for that to work, and then Kit was able to find the `hooks.server.js` file
```
kit : {
    ...
      files: {
      hooks: 'src/hooks.server',
     .....
```
It's accepting only one hooks file and we have to define that in order for it to work properly. But, with this we can't add `hooks.client.js` file as this accepts only a string not the object of client and server hooks path.

### Reproduction

To reproduce the issue, just add the path of the hooks files from the SvelteKit docs page here ([https://kit.svelte.dev/docs/configuration])(https://kit.svelte.dev/docs/configuration)  into your `svelte.config.js` and it will give the error which I have posted in the above section.

With default svelte config settings, the SvelteKit will not be able to access the `hooks.server.js` file or hooks.client.js file.

### Logs

```shell
error when starting dev server:
Error: config.kit.files.hooks should be a string, if specified
    at assert_string (file:///home/souravjamwal77/Desktop/projects/sample_test/svelte_sourav.fun/node_modules/@sveltejs/kit/src/core/config/options.js:479:9)
    at file:///home/souravjamwal77/Desktop/projects/sample_test/svelte_sourav.fun/node_modules/@sveltejs/kit/src/core/config/options.js:390:3
    at file:///home/souravjamwal77/Desktop/projects/sample_test/svelte_sourav.fun/node_modules/@sveltejs/kit/src/core/config/options.js:379:43
    at file:///home/souravjamwal77/Desktop/projects/sample_test/svelte_sourav.fun/node_modules/@sveltejs/kit/src/core/config/options.js:365:18
    at file:///home/souravjamwal77/Desktop/projects/sample_test/svelte_sourav.fun/node_modules/@sveltejs/kit/src/core/config/options.js:365:18
    at file:///home/souravjamwal77/Desktop/projects/sample_test/svelte_sourav.fun/node_modules/@sveltejs/kit/src/core/config/options.js:365:18
    at validate_config (file:///home/souravjamwal77/Desktop/projects/sample_test/svelte_sourav.fun/node_modules/@sveltejs/kit/src/core/config/index.js:104:9)
    at process_config (file:///home/souravjamwal77/Desktop/projects/sample_test/svelte_sourav.fun/node_modules/@sveltejs/kit/src/core/config/index.js:72:20)
    at load_config (file:///home/souravjamwal77/Desktop/projects/sample_test/svelte_sourav.fun/node_modules/@sveltejs/kit/src/core/config/index.js:64:9)
    at async config (file:///home/souravjamwal77/Desktop/projects/sample_test/svelte_sourav.fun/node_modules/@sveltejs/kit/src/exports/vite/index.js:197:20)
```

### System Info

```shell
System:
    OS: Linux 5.15 Ubuntu 20.04.5 LTS (Focal Fossa)
    CPU: (4) x64 Intel(R) Core(TM) i7-5600U CPU @ 2.60GHz
    Memory: 8.41 GB / 15.52 GB
    Container: Yes
    Shell: 5.0.17 - /bin/bash
  Binaries:
    Node: 16.14.2 - ~/.nvm/versions/node/v16.14.2/bin/node
    npm: 8.16.0 - ~/.nvm/versions/node/v16.14.2/bin/npm
  Browsers:
    Chrome: 105.0.5195.125
    Firefox: 104.0
  npmPackages:
    @sveltejs/adapter-auto: next => 1.0.0-next.71 
    @sveltejs/kit: next => 1.0.0-next.472 
    svelte: ^3.44.0 => 3.50.0 
    vite: ^3.1.0 => 3.1.0
```

### Severity

serious, but I can work around it

### Additional Information

I only need `hooks.server.js` so I added the path like a string but if someone requires both client and server hooks files then with this bug they won't be able to use both files.

Plus, if we don't override the path settings in `svelte.config.js` then Kit is unable to find the file and devs will have to add the default path also explicitly because of this path accepts string only issue.

**Comment by dummdidumm** [comment]
You're on an old version of SvelteKit prior to the hooks change. Upgrade to the latest version and it should work as expected.
