### ISSUE TITLE
Getting error 'Not found: /mockServiceWorker.js' after using 'vite dev'

### ISSUE THREAD

**Issue by 1mzino** [sveltejs/kit#7062]
### Describe the bug

When using 'pnpm run dev' to launch new (or cloned from github) app, I am presented with the error:

`Not found: /mockServiceWorker.js
Error: Not found: /mockServiceWorker.js
    at resolve (file:///Users/chowdhuryi/Desktop/vite-project/node_modules/@sveltejs/kit/src/runtime/server/index.js:256:13)
    at resolve (file:///Users/chowdhuryi/Desktop/vite-project/node_modules/@sveltejs/kit/src/runtime/server/index.js:287:5)
    at Object.handle (file:///Users/chowdhuryi/Desktop/vite-project/node_modules/@sveltejs/kit/src/exports/vite/dev/index.js:336:66)
    at respond (file:///Users/chowdhuryi/Desktop/vite-project/node_modules/@sveltejs/kit/src/runtime/server/index.js:284:40)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async file:///Users/chowdhuryi/Desktop/vite-project/node_modules/@sveltejs/kit/src/exports/vite/dev/index.js:406:22`

### Reproduction

Clone: https://github.com/1mzino/my-app 
Run (p)npm install
Run (p)npm run dev

Open page on browser and error appears in server logs.

### Logs

```shell
Not found: /mockServiceWorker.js
Error: Not found: /mockServiceWorker.js
    at resolve (file:///Users/chowdhuryi/Desktop/vite-project/node_modules/@sveltejs/kit/src/runtime/server/index.js:256:13)
    at resolve (file:///Users/chowdhuryi/Desktop/vite-project/node_modules/@sveltejs/kit/src/runtime/server/index.js:287:5)
    at Object.handle (file:///Users/chowdhuryi/Desktop/vite-project/node_modules/@sveltejs/kit/src/exports/vite/dev/index.js:336:66)
    at respond (file:///Users/chowdhuryi/Desktop/vite-project/node_modules/@sveltejs/kit/src/runtime/server/index.js:284:40)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async file:///Users/chowdhuryi/Desktop/vite-project/node_modules/@sveltejs/kit/src/exports/vite/dev/index.js:406:22
```

### System Info

```shell
System:
    OS: macOS 12.5.1
    CPU: (10) arm64 Apple M1 Pro
    Memory: 67.70 MB / 16.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 16.17.1 - ~/.nvm/versions/node/v16.17.1/bin/node
    npm: 8.15.0 - ~/.nvm/versions/node/v16.17.1/bin/npm
  Browsers:
    Chrome: 105.0.5195.125
    Firefox: 103.0.2
    Firefox Developer Edition: 106.0
    Safari: 15.6.1
  npmPackages:
    @sveltejs/adapter-auto: next => 1.0.0-next.80 
    @sveltejs/kit: next => 1.0.0-next.504 
    svelte: ^3.44.0 => 3.50.1 
    vite: ^3.1.0 => 3.1.3
```

### Severity

annoyance

**Comment by 1mzino** [comment]
No Idea about the root of the issue.. fixed by adding "dev": "svelte-kit sync && vite dev"

**Comment by Conduitry** [comment]
Presumably you still have a service worker installed in your browser for this origin from when you were using https://mswjs.io/ in another app. There's nothing in SvelteKit or in your repo that references `mockServiceWorker.js`.

**Comment by pot-code** [comment]
@1mzino Open DevTools, navigate to 'Application' Tab, under 'Service Workers' section, unregister the worker
