### ISSUE TITLE
adapter-node@93 breaks endpoints using devDependencies

### ISSUE THREAD

**Issue by vizath** [sveltejs/kit#7093]
### Describe the bug

After using rollup instead of esbuild in https://github.com/sveltejs/kit/pull/6896, some devDependencies cannot be built when imported in endpoints.

Was this breaking change intended?
I cannot find documentation about which dependencies should be `--dev` or not...
And https://kit.svelte.dev/faq#packages is still talking about esbuild.

### Reproduction

1. `npm create svelte@latest`
2. `yarn add --dev @sveltejs/adapter-node yup`
3. set the sveltekit adapter to `@sveltejs/adapter-node` in `svelte.config.js`
4. add `import yup from "yup";` and `console.log(yup);` in `/src/about/+server.ts`
5. `yarn build` fails
6. move the `yup` dependency from `devDependencies` to `dependencies`
7. `yarn build` passes

for the repro: https://github.com/vizath/svelte-node-93-bug
see https://github.com/vizath/svelte-node-93-bug/commit/fa702c7d415a7d681c4ed5d24624bda788508381 for the commit of steps 2-5

### Logs

```shell
$ vite build
vite v3.1.4 building for production...
✓ 371 modules transformed.
'default' is not exported by node_modules/yup/es/index.js, imported by src/routes/about/+page.ts
file: /folder/src/routes/about/+page.ts:1:7
1: import yup from 'yup';
          ^
2: console.log(yup);
error during build:
Error: 'default' is not exported by node_modules/yup/es/index.js, imported by src/routes/about/+page.ts
    at error (file:///folder/node_modules/vite/node_modules/rollup/dist/es/shared/rollup.js:1858:30)
    at Module.error (file:///folder/node_modules/vite/node_modules/rollup/dist/es/shared/rollup.js:12429:16)
    at Module.traceVariable (file:///folder/node_modules/vite/node_modules/rollup/dist/es/shared/rollup.js:12788:29)
    at ModuleScope.findVariable (file:///folder/node_modules/vite/node_modules/rollup/dist/es/shared/rollup.js:11440:39)
    at Identifier.bind (file:///folder/node_modules/vite/node_modules/rollup/dist/es/shared/rollup.js:7439:40)
    at CallExpression.bind (file:///folder/node_modules/vite/node_modules/rollup/dist/es/shared/rollup.js:5265:73)
    at CallExpression.bind (file:///folder/node_modules/vite/node_modules/rollup/dist/es/shared/rollup.js:8935:15)
    at ExpressionStatement.bind (file:///folder/node_modules/vite/node_modules/rollup/dist/es/shared/rollup.js:5269:23)
    at Program.bind (file:///folder/node_modules/vite/node_modules/rollup/dist/es/shared/rollup.js:5265:73)
    at Module.bindReferences (file:///folder/node_modules/vite/node_modules/rollup/dist/es/shared/rollup.js:12425:18)
error Command failed with exit code 1.
```

### System Info

```shell
Binaries:
    Node: 16.14.0 - ~/.nvm/versions/node/v16.14.0/bin/node
    Yarn: 1.22.18 - /usr/bin/yarn
    npm: 8.3.1 - ~/.nvm/versions/node/v16.14.0/bin/npm
  npmPackages:
    @sveltejs/adapter-auto: next => 1.0.0-next.80
    @sveltejs/adapter-node: 1.0.0-next.96 => 1.0.0-next.96
    @sveltejs/kit: next => 1.0.0-next.505
    svelte: ^3.46.0 => 3.50.1
    vite: ^3.1.0 => 3.1.4
```

### Severity

serious, but I can work around it

**Comment by Conduitry** [comment]
https://unpkg.com/yup@0.32.11/es/index.js The ESM version of `yup` has no default export, so the error you're seeing is expected. I don't know esbuild would have been doing before (perhaps it fell back to the CJS version in the package instead?), but you need to import something that the package exports. If you're expecting an object of all of the exports, you can import `* as yup` instead.
