### ISSUE TITLE
can't build to sites/kit.svelte.dev

### ISSUE THREAD

**Issue by boojongmin** [sveltejs/kit#7138]
### Describe the bug

`pnpm build`  not working in `kit/sites/kit.svelte.dev`

### Reproduction

```
cd kit/sites/kit.svelte.dev
pnpm run build
```

### Logs

![image](https://user-images.githubusercontent.com/9567723/193715976-aa6bb5b5-a5c8-4d41-9fcd-5a984eff6467.png)

```shell
Could not resolve '../../../../../../packages/kit/docs/types.js' from src/lib/docs/server/index.js
[vite-plugin-svelte-kit] Could not resolve '../../../../../../packages/kit/docs/types.js' from src/lib/docs/server/index.js
error during build:
Error: Could not resolve '../../../../../../packages/kit/docs/types.js' from src/lib/docs/server/index.js
    at error (file:///home/spring/github/kit/node_modules/.pnpm/rollup@2.78.1/node_modules/rollup/dist/es/shared/rollup.js:1858:30)
    at ModuleLoader.handleResolveId (file:///home/spring/github/kit/node_modules/.pnpm/rollup@2.78.1/node_modules/rollup/dist/es/shared/rollup.js:22350:24)
    at file:///home/spring/github/kit/node_modules/.pnpm/rollup@2.78.1/node_modules/rollup/dist/es/shared/rollup.js:22313:26
 ELIFECYCLE  Command failed with exit code 1.
```
```


### System Info

```shell
windows 11
wsl ubuntu 20.04.5
```

### Severity

annoyance

**Comment by jasonlyu123** [comment]
You'll need to run this script first
https://github.com/sveltejs/kit/blob/7fbc1a0eabb59753864f901b1b7fe8fd23a0a580/packages/kit/package.json#L69

**Comment by boojongmin** [comment]
@jasonlyu123 

OMZ 

I miss this [CONTRIBUTING.md](https://github.com/sveltejs/kit/blob/master/CONTRIBUTING.md).
thank you.
