### ISSUE TITLE
adapter-static no compiled

### ISSUE THREAD

**Issue by Upsetmania** [sveltejs/kit#7139]
### Describe the bug

hello, I have a problem when I compile with adapter-static, the problem comes from the theme/+server.ts route when I delete it it compiles well how to make the +server.ts route work with POST thank you to you

### Reproduction

  @sveltejs/adapter-static: all routes must be fully prerenderable (unless using the 'fallback' option — see https://github.com/sveltejs/kit/tree/master/packages/adapter-static#spa-mode). Try adding `export const prerender = true` to your root +layout.js/.ts file — see https://kit.svelte.dev/docs/page-options#prerender for more details
    - src\routes/theme

### Logs

```shell
@sveltejs/adapter-static: all routes must be fully prerenderable (unless using the 'fallback' option — see https://github.com/sveltejs/kit/tree/master/packages/adapter-static#spa-mode). Try adding `export const prerender = true` to your root +layout.js/.ts file — see https://kit.svelte.dev/docs/page-options#prerender for more details
    - src\routes/theme
error during build:
Error: Encountered dynamic routes
    at adapt (file:///C:/Users/Upset/Desktop/backendfronend/client-508/node_modules/@sveltejs/adapter-static/index.js:35:12)
    at adapt (file:///C:/Users/Upset/Desktop/backendfronend/client-508/node_modules/@sveltejs/kit/src/core/adapt/index.js:28:8)
    at Object.handler (file:///C:/Users/Upset/Desktop/backendfronend/client-508/node_modules/@sveltejs/kit/src/exports/vite/index.js:488:12)
    at async PluginDriver.hookParallel (file:///C:/Users/Upset/Desktop/backendfronend/client-508/node_modules/rollup/dist/es/shared/rollup.js:22632:17)
    at async Object.close (file:///C:/Users/Upset/Desktop/backendfronend/client-508/node_modules/rollup/dist/es/shared/rollup.js:23709:13)
    at async Promise.all (index 0)
    at async build (file:///C:/Users/Upset/Desktop/backendfronend/client-508/node_modules/vite/dist/node/chunks/dep-6b3a5aff.js:45659:13)
    at async CAC.<anonymous> (file:///C:/Users/Upset/Desktop/backendfronend/client-508/node_modules/vite/dist/node/cli.js:748:9)
```

### System Info

```shell
sveltekit
```

### Severity

annoyance

**Comment by dominikg** [comment]
This is working as intended. How do you expect a static server to handle post requests?

Please follow the documentation. If you need help or have questions, please join https://svelte.dev/chat or start a github discussion.
