### ISSUE TITLE
unable to build skeleton template with `@sveltejs/adapter-static`

### ISSUE THREAD

**Issue by josefaidt** [sveltejs/kit#7237]
### Describe the bug

I'm having an issue building the "Skeleton project" template with the latest versions of SvelteKit and the static adapter (installed using the `next` version defaults in `package.json`). To be clear, this is the default template with no additional changes outside swapping the adapter.

```
> Using @sveltejs/adapter-static
  @sveltejs/adapter-static: cannot have dynamic routes unless using the 'fallback' option. See https://github.com/sveltejs/kit/tree/master/packages/adapter-static#spa-mode for more information
    - src/routes
error during build:
Error: Encountered dynamic routes
    at adapt (file:///Users/josef/Documents/playground/tmp/ts-app/node_modules/.pnpm/@sveltejs+adapter-static@1.0.0-next.40/node_modules/@sveltejs/adapter-static/index.js:35:12)
    at adapt (file:///Users/josef/Documents/playground/tmp/ts-app/node_modules/.pnpm/@sveltejs+kit@1.0.0-next.513_svelte@3.51.0+vite@3.1.7/node_modules/@sveltejs/kit/src/core/adapt/index.js:28:8)
    at Object.handler (file:///Users/josef/Documents/playground/tmp/ts-app/node_modules/.pnpm/@sveltejs+kit@1.0.0-next.513_svelte@3.51.0+vite@3.1.7/node_modules/@sveltejs/kit/src/exports/vite/index.js:488:12)
    at async PluginDriver.hookParallel (file:///Users/josef/Documents/playground/tmp/ts-app/node_modules/.pnpm/rollup@2.78.1/node_modules/rollup/dist/es/shared/rollup.js:22632:17)
    at async Object.close (file:///Users/josef/Documents/playground/tmp/ts-app/node_modules/.pnpm/rollup@2.78.1/node_modules/rollup/dist/es/shared/rollup.js:23709:13)
    at async Promise.all (index 0)
    at async build (file:///Users/josef/Documents/playground/tmp/ts-app/node_modules/.pnpm/vite@3.1.7/node_modules/vite/dist/node/chunks/dep-0ebb5606.js:45667:13)
    at async CAC.<anonymous> (file:///Users/josef/Documents/playground/tmp/ts-app/node_modules/.pnpm/vite@3.1.7/node_modules/vite/dist/node/cli.js:748:9)
 ELIFECYCLE  Command failed with exit code 1.
```

### Reproduction

1. `pnpm create svelte@next` > choose skeleton project
2. `pnpm install`
3. replace `adapter-auto` with `adapter-static`
4. `pnpm build`
5. observe error

### System Info

```shell
System:
    OS: macOS 12.5
    CPU: (10) arm64 Apple M1 Pro
    Memory: 246.80 MB / 32.00 GB
    Shell: 3.5.1 - /opt/homebrew/bin/fish
  Binaries:
    Node: 18.7.0 - ~/Library/Caches/fnm_multishells/86580_1665519265321/bin/node
    Yarn: 1.22.19 - ~/Library/Caches/fnm_multishells/86580_1665519265321/bin/yarn
    npm: 8.15.0 - ~/Library/Caches/fnm_multishells/86580_1665519265321/bin/npm
  Browsers:
    Chrome: 106.0.5249.103
    Firefox: 104.0.2
    Safari: 15.6
  npmPackages:
    @sveltejs/adapter-static: 1.0.0-next.40 => 1.0.0-next.40 
    @sveltejs/kit: 1.0.0-next.513 => 1.0.0-next.513 
    svelte: ^3.44.0 => 3.51.0 
    vite: ^3.1.0 => 3.1.7
```

### Severity

serious, but I can work around it

**Comment by dummdidumm** [comment]
That error message looks out of date, it was updated with one suggestion which will fix the issue for you: You need to tell SvelteKit what routes actually should be prerendered. If it's all of them, place this in your root +layout.js:
```
// src/routes/+layout.js
export const prerender = true;
```
More info: https://kit.svelte.dev/docs/page-options#prerender

Closing as this works as expected; adding the prerender option fixes this for you.

**Comment by josefaidt** [comment]
Hey @dummdidumm I can confirm by adding that line in the root `+layout.ts` file it builds as expected, and I see the updated error message now, though I did create this repro yesterday 🤔 

```
> Using @sveltejs/adapter-static
  @sveltejs/adapter-static: all routes must be fully prerenderable (unless using the 'fallback' option — see https://github.com/sveltejs/kit/tree/master/packages/adapter-static#spa-mode). Try adding `export const prerender = true` to your root +layout.js/.ts file — see https://kit.svelte.dev/docs/page-options#prerender for more details
    - src/routes
error during build:
Error: Encountered dynamic routes
```

This error (`all routes must be fully prerenderable`) is a bit vague to me, but I do see the updated docs https://github.com/sveltejs/kit/tree/master/packages/adapter-static#usage.

**Comment by Sina-Hosseini-GST** [comment]
Did you find any solution @josefaidt ?

**Comment by megastruktur** [comment]
@josefaidt  In `svelte.config.js` you have to set the fallback page like so:
```
kit: {
  adapter: adapter({
	  fallback: 'index.html',
  })
}
```

This one is going to resolve the error.
