### ISSUE TITLE
Build failing on next.83 vercel adapter

### ISSUE THREAD

**Issue by smblee** [sveltejs/kit#7253]
### Describe the bug

Haven't investigated into it yet but renovate build is failing with the newest version. `builder.getAppPath is not a function`.

Creating an issue for now  in case anyone else is running into the same error.

```
> Using @sveltejs/adapter-vercel
--
10:52:04.956 | error during build:
10:52:04.956 | TypeError: builder.getAppPath is not a function
10:52:04.956 | at Object.adapt (file:///vercel/path1/node_modules/@sveltejs/adapter-vercel/index.js:121:23)
10:52:04.956 | at adapt (file:///vercel/path1/node_modules/@sveltejs/adapter-auto/index.js:20:22)
10:52:04.956 | at adapt (file:///vercel/path1/node_modules/@sveltejs/kit/src/core/adapt/index.js:28:8)
10:52:04.956 | at Object.handler (file:///vercel/path1/node_modules/@sveltejs/kit/src/exports/vite/index.js:488:12)
10:52:04.956 | at async PluginDriver.hookParallel (file:///vercel/path1/node_modules/rollup/dist/es/shared/rollup.js:22632:17)
10:52:04.956 | at async Object.close (file:///vercel/path1/node_modules/rollup/dist/es/shared/rollup.js:23709:13)
10:52:04.956 | at async Promise.all (index 0)
10:52:04.957 | at async build (file:///vercel/path1/node_modules/vite/dist/node/chunks/dep-0ebb5606.js:45667:13)
10:52:04.957 | at async CAC.<anonymous> (file:///vercel/path1/node_modules/vite/dist/node/cli.js:748:9)
10:52:05.139 | Error: Command "npm run build" exited with 1
```

### Reproduction

Use latest version of next.83 in vercel 

### System Info

```shell
System:
    OS: macOS 12.6
    CPU: (10) arm64 Apple M1 Pro
    Memory: 208.70 MB / 32.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 16.17.1 - ~/.volta/tools/image/node/16.17.1/bin/node
    npm: 8.19.2 - ~/.volta/tools/image/npm/8.19.2/bin/npm
  Browsers:
    Chrome: 106.0.5249.119
    Firefox: 105.0.2
    Safari: 16.0
  npmPackages:
    @sveltejs/adapter-auto: 1.0.0-next.83 => 1.0.0-next.83
    @sveltejs/kit: 1.0.0-next.511 => 1.0.0-next.511
    svelte: 3.50.1 => 3.50.1
    vite: 3.1.7 => 3.1.7
```

### Severity

annoyance

**Comment by Conduitry** [comment]
This changed in #4448. You also need to make the corresponding upgrade to `@sveltejs/kit` (https://github.com/sveltejs/kit/blob/master/packages/kit/CHANGELOG.md#100-next515) - I see you're still on 511.
