### ISSUE TITLE
When runing a fresh SvelteKit project: `Not found: /service-worker.js`

### ISSUE THREAD

**Issue by smithliam** [sveltejs/kit#7260]
### Describe the bug

I create a fresh SvelteKit project and I get this error:

```
Not found: /service-worker.js
Error: Not found: /service-worker.js
    at resolve (file:///C:/Users/babak/Desktop/new-folder/node_modules/.pnpm/@sveltejs+kit@1.0.0-next.515_svelte@3.51.0+vite@3.1.7/node_modules/@sveltejs/kit/src/runtime/server/index.js:259:13)
    at resolve (file:///C:/Users/babak/Desktop/new-folder/node_modules/.pnpm/@sveltejs+kit@1.0.0-next.515_svelte@3.51.0+vite@3.1.7/node_modules/@sveltejs/kit/src/runtime/server/index.js:290:5)
    at Object.handle (file:///C:/Users/babak/Desktop/new-folder/node_modules/.pnpm/@sveltejs+kit@1.0.0-next.515_svelte@3.51.0+vite@3.1.7/node_modules/@sveltejs/kit/src/exports/vite/dev/index.js:337:66)
    at respond (file:///C:/Users/babak/Desktop/new-folder/node_modules/.pnpm/@sveltejs+kit@1.0.0-next.515_svelte@3.51.0+vite@3.1.7/node_modules/@sveltejs/kit/src/runtime/server/index.js:287:40)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async file:///C:/Users/babak/Desktop/new-folder/node_modules/.pnpm/@sveltejs+kit@1.0.0-next.515_svelte@3.51.0+vite@3.1.7/node_modules/@sveltejs/kit/src/exports/vite/dev/index.js:407:22
```

### Reproduction

1. `pnpm create svelte`
2. `Skeleton project`
3. `Add type checking with TypeScript?` NO
4. x3 NO
5. `pnpm i`
6. `pnpm dev`
7. ERROR

### `package.json` Info

```
"devDependencies": {
    "@sveltejs/adapter-auto": "1.0.0-next.83",
    "@sveltejs/kit": "1.0.0-next.515",
    "autoprefixer": "10.4.12",
    "postcss": "8.4.18",
    "postcss-load-config": "4.0.1",
    "svelte": "3.51.0",
    "svelte-outclick": "^3.1.0",
    "svelte-preprocess": "4.10.7",
    "tailwindcss": "3.1.8",
    "vite": "3.1.7"
  }
```

### Severity

annoyance

**Comment by gtm-nayan** [comment]
Can't reproduce with the steps you mentioned and your package.json looks far from a "fresh SvelteKit project". Please provide a proper reproduction as instructed in the issue template.

> A link to a repository, or a fork of https://node.new/sveltekit, that reproduces the issue. Reproductions must be [short, self-contained and correct](http://sscce.org/) and must not contain files or code that aren't relevant to the issue — please do NOT just paste a link to your project. Explaining how to reproduce is generally not enough. It pushes the burden of creating a reproduction project onto a small set of volunteer maintainers and isn't scalable. If no reproduction is provided, the issue will be closed.

**Comment by Conduitry** [comment]
Go away, @babakfp.

**Comment by vfilatov** [comment]
I was able to reproduce this with
```
pnpm dev --port 8080
```
any other ports work just fine.

I followed (all defaults)
```
npm create svelte@latest my-app
cd my-app
npm install
npm run dev --open --port 8080
```
