### ISSUE TITLE
Builds broken where pre-rendered root route is inside a layout group

### ISSUE THREAD

**Issue by drzax** [sveltejs/kit#7359]
### Describe the bug

The [advanced layouts documentation](https://kit.svelte.dev/docs/advanced-routing#advanced-layouts) says it's possible to put the root route inside a layout group:

> You can also put a +page directly inside a (group), for example if / should be an (app) or a (marketing) page.

However also making the root route pre-rendered appears to break builds (though the dev server still runs fine).

Running `npm run build` fails with the following error:

```
Error: bad base path: ""
    at resolve@file:///home/projects/sveltejs-kit-template-default-rsju1n/node_modules/ (sveltejs/kit/src/utils/url.js:34:9)
    at visit@file:///home/projects/sveltejs-kit-template-default-rsju1n/node_modules/ (sveltejs/kit/src/core/prerender/prerender.js:252:36)
    at <anonymous> (<anonymous>)
[vite-plugin-svelte-kit] Prerendering failed with code 1
error during build:
Error: Prerendering failed with code 1
    at handler/</<@file:///home/projects/sveltejs-kit-template-default-rsju1n/node_modules/ (sveltejs/kit/src/exports/vite/index.js:460:15)
    at EventEmitter.prototype.emit (https://sveltejs-kit-template-default-rsju1n.w-corp.staticblitz.com/blitz.dfae8564d35fe429a0bab219bd7d77341f3ec782.js:6:155574)
    at ChildProcess/this._handle.onexit (https://sveltejs-kit-template-default-rsju1n.w-corp.staticblitz.com/blitz.dfae8564d35fe429a0bab219bd7d77341f3ec782.js:6:956479)
    at _onChildExit/< (https://sveltejs-kit-template-default-rsju1n.w-corp.staticblitz.com/blitz.dfae8564d35fe429a0bab219bd7d77341f3ec782.js:15:381382)
    at _0x3ef8b0 (https://sveltejs-kit-template-default-rsju1n.w-corp.staticblitz.com/blitz.dfae8564d35fe429a0bab219bd7d77341f3ec782.js:15:147569)
    at _0x4fa418/< (https://sveltejs-kit-template-default-rsju1n.w-corp.staticblitz.com/blitz.dfae8564d35fe429a0bab219bd7d77341f3ec782.js:15:147301)
    at <anonymous> (<anonymous>)
```

### Reproduction

https://stackblitz.com/edit/sveltejs-kit-template-default-rsju1n?file=src/routes/(group)/+page.js

Kill the dev server (or open a second console) and run `npm run build`.

### System Info

```Shell
## My dev machine
  System:
    OS: macOS 12.6
    CPU: (16) x64 Intel(R) Core(TM) i9-9880H CPU @ 2.30GHz
    Memory: 364.59 MB / 32.00 GB
    Shell: 5.1.8 - /usr/local/bin/bash
  Binaries:
    Node: 18.8.0 - /usr/local/bin/node
    npm: 8.19.2 - /usr/local/bin/npm
  Browsers:
    Chrome: 108.0.5359.10
    Edge: 106.0.1370.52
    Firefox: 105.0.3
    Firefox Developer Edition: 79.0
    Safari: 16.0
  npmPackages:
    @sveltejs/adapter-auto: next => 1.0.0-next.84
    @sveltejs/kit: next => 1.0.0-next.522
    svelte: ^3.44.0 => 3.52.0
    vite: ^3.1.0 => 3.1.8

## Stackbitz repro system


  System:
    OS: Linux 5.0 undefined
    CPU: (8) x64 Intel(R) Core(TM) i9-9880H CPU @ 2.30GHz
    Memory: 0 Bytes / 0 Bytes
    Shell: 1.0 - /bin/jsh
  Binaries:
    Node: 16.14.2 - /usr/local/bin/node
    Yarn: 1.22.19 - /usr/local/bin/yarn
    npm: 7.17.0 - /usr/local/bin/npm
  npmPackages:
    @sveltejs/adapter-auto: next => 1.0.0-next.84 
    @sveltejs/kit: next => 1.0.0-next.522 
    svelte: ^3.46.0 => 3.52.0 
    vite: ^3.1.0 => 3.1.8
```

### Severity

blocking an upgrade

**Comment by KekOnTheWorld** [comment]
Same issue here

**Comment by vnphanquang** [comment]
Bumping. Issue started from `@sveltejs/kit@1.0.0-next.522`, probably from this change here:

```
https://github.com/sveltejs/kit/pull/7338/files#diff-640bb06029f8b528408cb17e6b0a88cd9d68924246d520db4a616a8a2fe7d4f9L373
```
