### ISSUE TITLE
Service worker not intercepting fetch requests coming from client-side load function or invalidateAll (+page.ts)

### ISSUE THREAD

**Issue by reesericci** [sveltejs/kit#7371]
### Describe the bug

I created a service worker to cache data from my API. Every time somebody loads the page it fetches that data with a load function, and then runs `invalidateAll()` every couple of seconds to re-fetch the data. What happens though is that all the fetch requests coming from invalidate don't get intercepted by the worker, and so when the internet is offline it just throws errors instead of returning the cached content. Also on page load I'd like to fetch cached content, but the initial load function is also not being intercepted by the worker.

### Reproduction

https://git.sr.ht/~reesericci/service-worker-repro

Turn on the "offline" setting in the service worker settings under Application in chrome dev tools, and observe the fetch errors. You can also click "network requests" and see that nothing is being caught.

### Logs

```Shell
start-94d4eeb0.js:1          Uncaught (in promise) TypeError: Failed to fetch
    at window.fetch (start-94d4eeb0.js:1:1702)
    at Object.o [as check] (singletons-94312e44.js:1:1446)
    at je (start-94d4eeb0.js:1:12232)
    at async ae (start-94d4eeb0.js:1:11211)
window.fetch @ start-94d4eeb0.js:1
o @ singletons-94312e44.js:1
je @ start-94d4eeb0.js:1
await in je (async)
invalidateAll @ start-94d4eeb0.js:1
(anonymous) @ _page.svelte-c4299835.js:1
start-94d4eeb0.js:1          GET http://127.0.0.1:4173/api/wow net::ERR_INTERNET_DISCONNECTED
window.fetch @ start-94d4eeb0.js:1
e @ _page-65076d1a.js:1
me @ start-94d4eeb0.js:1
await in me (async)
(anonymous) @ start-94d4eeb0.js:1
Pe @ start-94d4eeb0.js:1
je @ start-94d4eeb0.js:1
ae @ start-94d4eeb0.js:1
await in ae (async)
invalidateAll @ start-94d4eeb0.js:1
(anonymous) @ _page.svelte-c4299835.js:1
start-94d4eeb0.js:1 TypeError: Failed to fetch
    at window.fetch (start-94d4eeb0.js:1:1702)
    at e (_page-65076d1a.js:1:85)
    at me (start-94d4eeb0.js:1:15636)
handleError @ start-94d4eeb0.js:1
te @ start-94d4eeb0.js:1
Pe @ start-94d4eeb0.js:1
await in Pe (async)
je @ start-94d4eeb0.js:1
ae @ start-94d4eeb0.js:1
await in ae (async)
invalidateAll @ start-94d4eeb0.js:1
(anonymous) @ _page.svelte-c4299835.js:1
start-94d4eeb0.js:1          GET http://127.0.0.1:4173/_app/version.json net::ERR_INTERNET_DISCONNECTED
window.fetch @ start-94d4eeb0.js:1
o @ singletons-94312e44.js:1
je @ start-94d4eeb0.js:1
await in je (async)
ae @ start-94d4eeb0.js:1
await in ae (async)
invalidateAll @ start-94d4eeb0.js:1
(anonymous) @ _page.svelte-c4299835.js:1
start-94d4eeb0.js:1          Uncaught (in promise) TypeError: Failed to fetch
    at window.fetch (start-94d4eeb0.js:1:1702)
    at Object.o [as check] (singletons-94312e44.js:1:1446)
    at je (start-94d4eeb0.js:1:12232)
    at async ae (start-94d4eeb0.js:1:11211)
```

### System Info

```Shell
System:
    OS: Linux 5.17 Fedora Linux 35 (Container Image)
    CPU: (8) x64 Intel(R) Core(TM) i5-8265U CPU @ 1.60GHz
    Memory: 409.51 MB / 15.31 GB
    Container: Yes
    Shell: 5.1.8 - /bin/bash
  Binaries:
    Node: 16.13.0 - /usr/bin/node
    npm: 8.1.0 - /usr/bin/npm
  npmPackages:
    @sveltejs/adapter-auto: next => 1.0.0-next.84 
    @sveltejs/kit: next => 1.0.0-next.522 
    svelte: ^3.44.0 => 3.52.0 
    vite: ^3.1.0 => 3.1.8
```

### Severity

serious, but I can work around it

**Comment by reesericci** [comment]
I'm aware - but I can't do anything if I can't intercept the requests

**Comment by benmccann** [comment]
I wonder if https://vite-pwa-org.netlify.app/frameworks/sveltekit.html would work any better for you?

**Comment by dummdidumm** [comment]
The service worker implementation is flawed. It isn't adding anything to the cache on a successful response. This is how the `fetch` implementation could look like instead:

```js
self.addEventListener("fetch", function (event) {
  async function addToCache(request, response) {
    const cache = await caches.open("v" + version);
    await cache.put(request, response);
  }
  async function cacheFallback(request) {
    try {
      const response = await fetch(request);
      addToCache(request, response.clone());
      return response;
    } catch (e) {
      const responseFromCache = await caches.match(request);
      if (responseFromCache) {
        return responseFromCache;
      } else {
        throw e;
      }
    }
  }
  event.respondWith(cacheFallback(event.request));
});
```
