### ISSUE TITLE
Error while creating 'Library skeleton project'

### ISSUE THREAD

**Issue by stuymedova** [sveltejs/kit#7475]
### Describe the bug

I have just started a new project using the `npm create svelte@latest` command. After which I chose the following options:

```
✔ Where should we create your project?
  (leave blank to use current directory) … 
✔ Which Svelte app template? › Library skeleton project
✔ Add type checking with TypeScript? › No
✔ Add ESLint for code linting? … No / Yes
✔ Add Prettier for code formatting? … No / Yes
✔ Add Playwright for browser testing? … No / Yes
```

Then run `npm install`  and upon completion `npm run build`. I received the following error:

```
> Failed to locate tsconfig or jsconfig
    at loadTsconfig (/Users/stuymedova/Documents/github/projects/web-development/_test2/node_modules/svelte2tsx/index.js:7260:15)
    at emitDts (/Users/stuymedova/Documents/github/projects/web-development/_test2/node_modules/svelte2tsx/index.js:7250:36)
    at async emit_dts (file:///Users/stuymedova/Documents/github/projects/web-development/_test2/node_modules/@sveltejs/package/src/typescript.js:23:2)
    at async Module.build (file:///Users/stuymedova/Documents/github/projects/web-development/_test2/node_modules/@sveltejs/package/src/index.js:30:3)
    at async file:///Users/stuymedova/Documents/github/projects/web-development/_test2/node_modules/@sveltejs/package/src/cli.js:27:4
```

### Reproduction

I suppose that instructions above would be sufficient because I've started from scratch.

### System Info

```Shell
System:
    OS: macOS 13.0
    CPU: (4) x64 Intel(R) Core(TM) i3-1000NG4 CPU @ 1.10GHz
    Memory: 28.30 MB / 8.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 16.16.0 - /usr/local/bin/node
    Yarn: 1.22.10 - /usr/local/bin/yarn
    npm: 8.11.0 - /usr/local/bin/npm
  Browsers:
    Chrome: 107.0.5304.87
    Firefox: 98.0
    Safari: 16.1
  npmPackages:
    @sveltejs/adapter-auto: next => 1.0.0-next.86 
    @sveltejs/kit: next => 1.0.0-next.532 
    @sveltejs/package: next => 1.0.0-next.1 
    svelte: ^3.44.0 => 3.52.0 
    vite: ^3.1.0 => 3.2.2
```

### Severity

blocking an upgrade

**Comment by stuymedova** [comment]
Thank you for a quick reply!
