### ISSUE TITLE
Typescript error

### ISSUE THREAD

**Issue by taishi55** [sveltejs/kit#7478]
### Describe the bug

After `npm create svelte@latest my-app` with typescript, I get the following error on the browser. 

```
Uncaught (in promise) TypeError: Cannot convert undefined or null to object
    at Function.keys (<anonymous>)
    at companion-bubble.js:1465:19726
    at Generator.next (<anonymous>)
    at Ln (companion-bubble.js:1465:19144)
```

### Reproduction

`npm create svelte@latest my-app`
```
✔ Which Svelte app template? › Skeleton project
✔ Add type checking with TypeScript? › Yes, using TypeScript syntax
✔ Add ESLint for code linting? …  Yes
✔ Add Prettier for code formatting? … Yes
✔ Add Playwright for browser testing? …  Yes
```

`cd my-app`

`npm install`

`npm run dev -- --open`

open DevTools on your browser and confirm the error.

### System Info

```Shell
System:
    OS: macOS 12.4
    CPU: (8) arm64 Apple M1
    Memory: 98.39 MB / 8.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 16.15.0 - /usr/local/bin/node
    npm: 8.19.2 - /usr/local/bin/npm
  Browsers:
    Brave Browser: 103.1.40.113
    Safari: 15.5
  npmPackages:
    @sveltejs/adapter-auto: next => 1.0.0-next.86 
    @sveltejs/kit: next => 1.0.0-next.532 
    svelte: ^3.44.0 => 3.52.0 
    vite: ^3.1.0 => 3.2.2
```

### Severity

annoyance

**Comment by hughest64** [comment]
I believe this is unrelated to SvelteKit. Do you use the Loom Chrome extension? https://stackoverflow.com/questions/74281137/companion-bubble-js-in-the-console

**Comment by taishi55** [comment]
@hughest64 Yes, the loom extension was installed. After uninstalling, the error disappeared! Thank you.
