### ISSUE TITLE
options.manifest._.nodes[0] is not a function

### ISSUE THREAD

**Issue by zyxd** [sveltejs/kit#7618]
### Describe the bug

If run `npm run preview` with `prerender = true` on all pages, a "options.manifest._.nodes[0] is not a function" error comes up if request a non-existent page.

### Reproduction

1. `npm create svelte@latest my-app && cd my-app && npm install`
2. Select `Skeleton project`
3. `echo "export const prerender = true" > src/routes/+layout.js`
4. `npm run build && npm run preview`
5. Open app in browser and navigate `/123`

### Logs
```Shell
TypeError: options.manifest._.nodes[0] is not a function
    at respond_with_error (file:///Users/zyxd/Developer/zyxd/issue-nodes-not-function/.svelte-kit/output/server/index.js:1771:61)
    at resolve (file:///Users/zyxd/Developer/zyxd/issue-nodes-not-function/.svelte-kit/output/server/index.js:2877:22)
    at resolve (file:///Users/zyxd/Developer/zyxd/issue-nodes-not-function/.svelte-kit/output/server/index.js:2904:34)
    at options.hooks.handle (file:///Users/zyxd/Developer/zyxd/issue-nodes-not-function/.svelte-kit/output/server/index.js:3062:59)
    at respond (file:///Users/zyxd/Developer/zyxd/issue-nodes-not-function/.svelte-kit/output/server/index.js:2902:42)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
```

### System Info

```Shell
System:
    OS: macOS 13.0.1
    CPU: (10) arm64 Apple M1 Pro
    Memory: 1.04 GB / 16.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 18.11.0 - /opt/homebrew/bin/node
    npm: 8.19.2 - /opt/homebrew/bin/npm
  Browsers:
    Chrome: 107.0.5304.110
    Safari: 16.1
  npmPackages:
    @sveltejs/adapter-auto: next => 1.0.0-next.87 
    @sveltejs/kit: next => 1.0.0-next.543 
    svelte: ^3.44.0 => 3.53.1 
    vite: ^3.1.0 => 3.2.3
```

### Severity

serious, but I can work around it

**Comment by dummdidumm** [comment]
Duplicate of #5967

**Comment by zyxd** [comment]
> Duplicate of #5967

Sorry but how is this related to this issue? Is there a temporary solution?

**Comment by dummdidumm** [comment]
Solution: Create a `+layout.svelte` file with `<slot />` in it. It's related because the issue says such a fallback component should be created when the user doesn't provide one.

**Comment by zyxd** [comment]
> Solution: Create a `+layout.svelte` file with `<slot />` in it. It's related because the issue says such a fallback component should be created when the user doesn't provide one.

Created, but problem is still here. Could you please recheck?

**Comment by zyxd** [comment]
> Can't reproduce this given your description

https://stackblitz.com/edit/sveltejs-kit-template-default-l1egkl

1. Abort running command
2. `npm run build && npm run preview`
3. navigate `/123`

**Comment by dummdidumm** [comment]
This may have to do with the recent changes to the manifest where prerendered things are moved out of it. The root layout probably should never be moved out of there.

**Comment by Azarattum** [comment]
I'm getting this error when trying to access the root route (aka `/`). Meaning `http://localhost:4173/index.html` works, but `http://localhost:4173/` does not.
