### ISSUE TITLE
Prerendering (on windows?) fails to serve on preview for the root path '/', but works for the path '/index'

### ISSUE THREAD

**Issue by Tal500** [sveltejs/kit#7633]
### Describe the bug

Prerendering (on windows?) fails to serve on preview for the root path '/', but works for the path '/index'.
When disabling prerendering, the opposite is true - it works for '/' but not for '/index'.

Client side navigation after initial load works as normal.

### Reproduction

For some reason, it doesn't happen on StackBlitz, so maybe it's a Windows only issue?

Clone this repo (it contains only a simple seltekit template, nothing was changed from the default generated one):
https://github.com/Tal500/sveltekit-index-prerendering-repro

Run `pnpm install && pnpm build && pnpm preview`.

Going to 'http://localhost:4173/' in Firefox:
![תמונה](https://user-images.githubusercontent.com/1467072/201518995-5d0c7213-5940-42b7-a352-1df6fe59c01e.png)

Client side navigation works fine.

Going to 'http://localhost:4173/index' in Firefox works fine:
![תמונה](https://user-images.githubusercontent.com/1467072/201519158-1a6bf5de-3cce-499e-8b0c-b7a6cc38306c.png)

Disabling prerendering by adding `prerender: { enabled: false }` to `config.kit` in `svelte.config.js` fixes the issue (as I said earlier).

### Logs

```Shell
C:\Src\sveltekit-index-prerendering-repro>pnpm build && pnpm preview

> sveltekit-index-prerendering-repro@0.0.1 build C:\Src\sveltekit-index-prerendering-repro
> vite build

vite v3.2.3 building for production...
✓ 62 modules transformed.
vite v3.2.3 building SSR bundle for production...
transforming (79) src\routes\styles.css"confetti" is imported from external module "@neoconfetti/svelte" but never used in "src/routes/sverdle/+page.svelte".
✓ 79 modules transformed.
Generated an empty chunk: "hooks"
.svelte-kit/output/server/vite-manifest.json                                  4.33 KiB
.svelte-kit/output/server/index.js                                            93.62 KiB
.svelte-kit/output/server/entries/pages/_layout.svelte.js                     4.51 KiB
.svelte-kit/output/server/entries/fallbacks/error.svelte.js                   0.60 KiB
.svelte-kit/output/server/entries/pages/_page.svelte.js                       7.28 KiB
.svelte-kit/output/server/entries/pages/_page.ts.js                           0.05 KiB
.svelte-kit/output/server/entries/pages/about/_page.svelte.js                 1.06 KiB
.svelte-kit/output/server/entries/pages/about/_page.ts.js                     0.13 KiB
.svelte-kit/output/server/entries/pages/sverdle/_page.svelte.js               7.62 KiB
.svelte-kit/output/server/entries/pages/sverdle/_page.server.ts.js            141.76 KiB
.svelte-kit/output/server/entries/pages/sverdle/how-to-play/_page.svelte.js   2.85 KiB
.svelte-kit/output/server/entries/pages/sverdle/how-to-play/_page.ts.js       0.13 KiB
.svelte-kit/output/server/chunks/index.js                                     4.29 KiB
.svelte-kit/output/server/chunks/index2.js                                    1.06 KiB
.svelte-kit/output/server/chunks/index3.js                                    1.29 KiB
.svelte-kit/output/server/chunks/stores.js                                    1.00 KiB
.svelte-kit/output/server/chunks/environment.js                               0.04 KiB
.svelte-kit/output/server/chunks/hooks.js                                     0.00 KiB

Run npm run preview to preview your production build locally.
.svelte-kit/output/client/_app/immutable/assets/svelte-welcome-c18bcf5a.webp                             112.76 KiB
.svelte-kit/output/client/_app/immutable/assets/svelte-welcome-6c300099.png                              352.35 KiB
.svelte-kit/output/client/_app/immutable/assets/svelte-logo-87df40b8.svg                                 1.85 KiB
.svelte-kit/output/client/_app/immutable/assets/github-1ea8d62e.svg                                      1.71 KiB
.svelte-kit/output/client/_app/immutable/assets/fira-mono-cyrillic-ext-400-normal-3df7909e.woff2         15.40 KiB
.svelte-kit/output/client/_app/immutable/assets/fira-mono-cyrillic-400-normal-c7d433fd.woff2             8.89 KiB
.svelte-kit/output/client/_app/immutable/assets/fira-mono-greek-400-normal-a8be01ce.woff2                10.27 KiB
.svelte-kit/output/client/_app/immutable/assets/fira-mono-greek-ext-400-normal-9e2fe623.woff2            7.33 KiB
.svelte-kit/output/client/_app/immutable/assets/fira-mono-latin-ext-400-normal-6bfabd30.woff2            11.10 KiB
.svelte-kit/output/client/_app/immutable/assets/fira-mono-latin-400-normal-e43b3538.woff2                15.90 KiB
.svelte-kit/output/client/_app/immutable/assets/fira-mono-all-400-normal-1e3b098c.woff                   75.55 KiB
.svelte-kit/output/client/vite-manifest.json                                                             10.27 KiB
.svelte-kit/output/client/_app/immutable/start-cf016e0c.js                                               27.39 KiB / gzip: 10.39 KiB
.svelte-kit/output/client/_app/immutable/components/error.svelte-62533ebb.js                             1.54 KiB / gzip: 0.71 KiB
.svelte-kit/output/client/_app/immutable/components/pages/_layout.svelte-1974f168.js                     5.03 KiB / gzip: 1.91 KiB
.svelte-kit/output/client/_app/immutable/components/pages/about/_page.svelte-71b117d3.js                 2.43 KiB / gzip: 1.10 KiB
.svelte-kit/output/client/_app/immutable/components/pages/_page.svelte-c227a61c.js                       5.55 KiB / gzip: 2.46 KiB
.svelte-kit/output/client/_app/immutable/modules/pages/_page.ts-e9fa0128.js                              0.07 KiB / gzip: 0.08 KiB
.svelte-kit/output/client/_app/immutable/components/pages/sverdle/_page.svelte-686cf2b2.js               14.00 KiB / gzip: 5.70 KiB
.svelte-kit/output/client/_app/immutable/modules/pages/about/_page.ts-ad5472f6.js                        0.14 KiB / gzip: 0.12 KiB
.svelte-kit/output/client/_app/immutable/modules/pages/sverdle/how-to-play/_page.ts-4b4b6744.js          0.14 KiB / gzip: 0.12 KiB
.svelte-kit/output/client/_app/immutable/chunks/singletons-93889f83.js                                   1.63 KiB / gzip: 0.89 KiB
.svelte-kit/output/client/_app/immutable/components/pages/sverdle/how-to-play/_page.svelte-c7ad0e72.js   5.14 KiB / gzip: 1.92 KiB
.svelte-kit/output/client/_app/immutable/chunks/_page-802cc2a3.js                                        0.14 KiB / gzip: 0.14 KiB
.svelte-kit/output/client/_app/immutable/chunks/_page-1b928caf.js                                        0.20 KiB / gzip: 0.18 KiB
.svelte-kit/output/client/_app/immutable/chunks/environment-ea55ba0a.js                                  0.03 KiB / gzip: 0.05 KiB
.svelte-kit/output/client/_app/immutable/chunks/_page-cec1766d.js                                        0.20 KiB / gzip: 0.18 KiB
.svelte-kit/output/client/_app/immutable/chunks/0-95c6b78c.js                                            0.09 KiB / gzip: 0.10 KiB
.svelte-kit/output/client/_app/immutable/chunks/1-bf898d57.js                                            0.09 KiB / gzip: 0.09 KiB
.svelte-kit/output/client/_app/immutable/chunks/2-cf5ba567.js                                            0.14 KiB / gzip: 0.13 KiB
.svelte-kit/output/client/_app/immutable/chunks/3-23ba7b01.js                                            0.15 KiB / gzip: 0.13 KiB
.svelte-kit/output/client/_app/immutable/chunks/index-edeadeeb.js                                        0.43 KiB / gzip: 0.30 KiB
.svelte-kit/output/client/_app/immutable/chunks/4-d1eb158c.js                                            0.12 KiB / gzip: 0.12 KiB
.svelte-kit/output/client/_app/immutable/chunks/5-39b660dc.js                                            0.16 KiB / gzip: 0.14 KiB
.svelte-kit/output/client/_app/immutable/assets/_page-265a38f0.css                                       1.41 KiB / gzip: 0.51 KiB
.svelte-kit/output/client/_app/immutable/assets/_layout-c5c520a0.css                                     4.92 KiB / gzip: 1.56 KiB
.svelte-kit/output/client/_app/immutable/assets/_page-89a9e780.css                                       0.79 KiB / gzip: 0.34 KiB
.svelte-kit/output/client/_app/immutable/assets/_page-2c27b08c.css                                       3.79 KiB / gzip: 1.06 KiB
.svelte-kit/output/client/_app/immutable/chunks/stores-93f7a882.js                                       0.61 KiB / gzip: 0.35 KiB
.svelte-kit/output/client/_app/immutable/chunks/index-d132f6eb.js                                        7.97 KiB / gzip: 3.26 KiB

> Using @sveltejs/adapter-auto
  Could not detect a supported production environment. See https://kit.svelte.dev/docs/adapters to learn how to configure your app to run on the platform of your choosing
  ✔ done

C:\Src\sveltekit-index-prerendering-repro>pnpm preview

> sveltekit-index-prerendering-repro@0.0.1 preview C:\Src\sveltekit-index-prerendering-repro
> vite preview

  ➜  Local:   http://localhost:4173/
  ➜  Network: use --host to expose
Error: Not found: /
    at resolve (file:///C:/Src/sveltekit-index-prerendering-repro/.svelte-kit/output/server/index.js:2796:18)
    at resolve (file:///C:/Src/sveltekit-index-prerendering-repro/.svelte-kit/output/server/index.js:2818:34)
    at options.hooks.handle (file:///C:/Src/sveltekit-index-prerendering-repro/.svelte-kit/output/server/index.js:2976:59)
    at respond (file:///C:/Src/sveltekit-index-prerendering-repro/.svelte-kit/output/server/index.js:2816:42)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
```

### System Info

```Shell
System:
    OS: Windows 10 10.0.19044
    CPU: (4) x64 Intel(R) Core(TM) i7-6500U CPU @ 2.50GHz
    Memory: 1.08 GB / 15.49 GB
  Binaries:
    Node: 18.3.0 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.18 - ~\AppData\Roaming\npm\yarn.CMD
    npm: 8.14.0 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Edge: Spartan (44.19041.1266.0), Chromium (107.0.1418.42)
    Internet Explorer: 11.0.19041.1566
  npmPackages:
    @sveltejs/adapter-auto: next => 1.0.0-next.87
    @sveltejs/kit: next => 1.0.0-next.544
    svelte: ^3.46.0 => 3.53.1
    vite: ^3.1.0 => 3.2.3
```

### Severity

serious, but I can work around it

**Comment by Tal500** [comment]
Using Git Bisect (and verifying manually after), I can tell that the commit that caused the bug is d00542bd00e3f1e2513ae098ecc52e97c77830b8.
