### ISSUE TITLE
Error: Unrecognized option 'cssHash'.

### ISSUE THREAD

**Issue by davidwparker** [sveltejs/kit#765]
**Describe the bug**

When running the app, I get the error `Error: Unrecognized option 'cssHash'`.

Everything compiles fine (`npm run build`), but when I run in `dev` or `start` it throws this error

**Logs**
Please include browser console and server logs around the time this bug occurred.
```
Error: Unrecognized option 'cssHash'
    at /app/node_modules/svelte/compiler.js:28710:20
    at Array.forEach (<anonymous>)
    at validate_options (/app/node_modules/svelte/compiler.js:28704:27)
    at compile (/app/node_modules/svelte/compiler.js:28748:6)
    at compileSvelte (/app/node_modules/@sveltejs/vite-plugin-svelte/dist/index.js:291:48)
    at TransformContext.transform (/app/node_modules/@sveltejs/vite-plugin-svelte/dist/index.js:679:33)
    at Object.transform (/app/node_modules/vite/dist/node/chunks/dep-6e02b235.js:43716:53)
    at transformRequest (/app/node_modules/vite/dist/node/chunks/dep-6e02b235.js:59430:51)
    at async instantiateModule (/app/node_modules/vite/dist/node/chunks/dep-6e02b235.js:68980:10)
```

**To Reproduce**

I'll see if I can create a shareable repo.

**Expected behavior**

The app should work. 

**Stacktraces**

<details>
  <summary>Stack trace</summary>

```
Error: Unrecognized option 'cssHash'
    at /app/node_modules/svelte/compiler.js:28710:20
    at Array.forEach (<anonymous>)
    at validate_options (/app/node_modules/svelte/compiler.js:28704:27)
    at compile (/app/node_modules/svelte/compiler.js:28748:6)
    at compileSvelte (/app/node_modules/@sveltejs/vite-plugin-svelte/dist/index.js:291:48)
    at TransformContext.transform (/app/node_modules/@sveltejs/vite-plugin-svelte/dist/index.js:679:33)
    at Object.transform (/app/node_modules/vite/dist/node/chunks/dep-6e02b235.js:43716:53)
    at transformRequest (/app/node_modules/vite/dist/node/chunks/dep-6e02b235.js:59430:51)
    at async instantiateModule (/app/node_modules/vite/dist/node/chunks/dep-6e02b235.js:68980:10)
```

</details>

**Information about your SvelteKit Installation:**

- The output of `npx envinfo --system --npmPackages svelte,@sveltejs/kit --binaries --browsers`

```
System:
    OS: Linux 4.4 Ubuntu 18.04.3 LTS (Bionic Beaver)
    CPU: (12) x64 Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz
    Memory: 16.71 GB / 31.74 GB
    Container: Yes
    Shell: 4.4.20 - /bin/bash
  Binaries:
    Node: 14.16.0 - /usr/local/bin/node
    Yarn: 1.21.1 - /usr/bin/yarn
    npm: 6.14.11 - /usr/local/bin/npm
  npmPackages:
    @sveltejs/kit: next => 1.0.0-next.64
    svelte: ^3.32.1 => 3.32.1
```

- Your browser

Chrome Version 89.0.4389.90 (Official Build) (64-bit)

- Your adapter (e.g. Node, static, Vercel, Begin, etc...)

Static

**Severity**
How severe an issue is this bug to you? Is this annoying, blocking some users, blocking an upgrade or blocking your usage of SvelteKit entirely?

Very severe. The app won't work at all.

**Additional context**
This is an migrated sapper application with a single page. I have another migrated sapper application that I was able to migrate and works more or less identically just fine. I used the other finished migrated app to migrate this one and this one is getting this error but the other is not.

I also tried adding `cssHash` to the `valid_options` in the compiler around line ~28710 and then it loaded the app okay as well.

**Comment by Conduitry** [comment]
`cssHash` wasn't added to Svelte until version 3.34.0, and envinfo output above indicates that you're on 3.32.1.

**Comment by davidwparker** [comment]
> `cssHash` wasn't added to Svelte until version 3.34.0, and envinfo output above indicates that you're on 3.32.1.

This was it, thanks!
