### ISSUE TITLE
Bug with `adapter-node` on `stackblitz`

### ISSUE THREAD

**Issue by AlexRMU** [sveltejs/kit#7808]
### Describe the bug

When using `adapter-node` with `precompress: true` on `stackblitz`, an error appears when trying to build and an offer to buy a pro pops up.
This makes it difficult to create reproductions to issues.
Maybe this is a `stackblitz` problem, and maybe not.

### Reproduction

https://stackblitz.com/edit/sveltejs-kit-template-default-baug2l?file=svelte.config.js
Run `npm run build`

### Logs

```Shell
> Using @sveltejs/adapter-node
error during build:
TypeError: r.init is not a function
    at BrotliCompress.Brotli (https://sveltejskittemplatedefaultbaug2l-ouy5.w-credentialless.staticblitz.com/blitz.131052885c8f3959137493487241913a4935f1a0.js:6:1726692)
    at new BrotliCompress (https://sveltejskittemplatedefaultbaug2l-ouy5.w-credentialless.staticblitz.com/blitz.131052885c8f3959137493487241913a4935f1a0.js:6:1726867)
    at Object.value [as createBrotliCompress] (https://sveltejskittemplatedefaultbaug2l-ouy5.w-credentialless.staticblitz.com/blitz.131052885c8f3959137493487241913a4935f1a0.js:6:1727090)
    at compress_file (file://file:///home/projects/sveltejs-kit-template-default-baug2l/node_modules/@sveltejs/kit/src/core/adapt/builder.js:214:20)
    at eval (file://file:///home/projects/sveltejs-kit-template-default-baug2l/node_modules/@sveltejs/kit/src/core/adapt/builder.js:195:65)
    at Array.map (<anonymous>)
    at Object.compress (file://file:///home/projects/sveltejs-kit-template-default-baug2l/node_modules/@sveltejs/kit/src/core/adapt/builder.js:195:11)
    at async Promise.all (index 1)
    at async adapt (file://file:///home/projects/sveltejs-kit-template-default-baug2l/node_modules/@sveltejs/adapter-node/index.js:53:5)
    at async adapt (file://file:///home/projects/sveltejs-kit-template-default-baug2l/node_modules/@sveltejs/kit/src/core/adapt/index.js:43:2)
```
```


### System Info

```Shell
https://node.new/sveltekit
```

### Severity

annoyance

**Comment by dummdidumm** [comment]
This is related to Stackblitz only, nothing we can do about that. If it's important to reproduce with a production build and a specific adapter, consider using a github repo for reproduction instead.
