### ISSUE TITLE
SyntaxError: The requested module does not provide an export named 'prerendering'

### ISSUE THREAD

**Issue by romelperez** [sveltejs/kit#7847]
### Describe the bug

Hello! After I updated SvelteKit to version `1.0.0-next.564`, the app got a runtime error with the following message:

```
SyntaxError: The requested module '/node_modules/@sveltejs/kit/src/runtime/app/environment.js?v=f9512d5e' does not provide an export named 'prerendering'
```

I search for all my source code but there is no import for that dependency. I also reviewed the migration documentation in the PR which introduced that breaking change at https://github.com/sveltejs/kit/pull/7762 but still the error was appearing.

When I searched for a possible import in the `.svelte-kit` folder output but I didn't find either the import to that dependency.

The app `svelte.config.js` looks like this:

```js
import adapter from '@sveltejs/adapter-cloudflare';
import preprocess from 'svelte-preprocess';

const config = {
	preprocess: preprocess({
		postcss: true
	}),

	kit: {
		adapter: adapter(),
		alias: {
			$houdini: './$houdini'
		}
	}
};

export default config;
```

The `@sveltejs/adapter-cloudflare` was removed but still the error appeared.

### Reproduction

I don't know what is adding the problem to the app, but in our source code, there is no import to that dependency.

### Logs

```Shell
11:01:59.013 client-manifest.js:23 SyntaxError: The requested module '/node_modules/@sveltejs/kit/src/runtime/app/environment.js?v=f9512d5e' does not provide an export named 'prerendering' (at adapter.js:1:19)
handleError @ client-manifest.js:23
handle_error @ client.js?v=f9512d5e:1633
_hydrate @ client.js?v=f9512d5e:1574
await in _hydrate (async)
start @ start.js:38
(anonymous) @ sign-in:95
11:01:59.014 adapter.js:1 Uncaught (in promise) SyntaxError: The requested module '/node_modules/@sveltejs/kit/src/runtime/app/environment.js?v=f9512d5e' does not provide an export named 'prerendering' (at adapter.js:1:19)
11:01:59.014 adapter.js:1 Uncaught (in promise) SyntaxError: The requested module '/node_modules/@sveltejs/kit/src/runtime/app/environment.js?v=f9512d5e' does not provide an export named 'prerendering' (at adapter.js:1:19)
await (async)
(anonymous) @ sign-in:95
```

### System Info

```Shell
System:
    OS: macOS 11.4
    CPU: (8) arm64 Apple M1
    Memory: 99.22 MB / 16.00 GB
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 16.18.1 - ~/.nvm/versions/node/v16.18.1/bin/node
    npm: 8.19.2 - ~/.nvm/versions/node/v16.18.1/bin/npm
  Browsers:
    Chrome: 107.0.5304.121
    Firefox: 107.0
    Safari: 14.1.1
  npmPackages:
    @sveltejs/adapter-auto: ^1.0.0-next.89 => 1.0.0-next.89 
    @sveltejs/adapter-cloudflare: ^1.0.0-next.40 => 1.0.0-next.40 
    @sveltejs/kit: ^1.0.0-next.564 => 1.0.0-next.564 
    svelte: ^3.53.1 => 3.53.1 
    vite: ^3.2.4 => 3.2.4
```

### Severity

blocking an upgrade

### Additional Information

Thank you!

**Comment by dummdidumm** [comment]
Is there some third party package that maybe does use this? Your config hints that you use houdini - do they use that export?

**Comment by romelperez** [comment]
@dummdidumm, I am going to check it out.
