### ISSUE TITLE
$env+static+private.md missing in 1.0.0-next.566

### ISSUE THREAD

**Issue by AisukoWasTaken** [sveltejs/kit#7856]
### Describe the bug

Hello,

I noticed a missing file when running server using version 1.0.0-next.566. That prevents me from starting the dev server
Error: ENOENT: no such file or directory, open '/home/aisuko/dev/sveltekit-test/node_modules/sites/kit.svelte.dev/scripts/types/special-types/$env+static+private.md'

The link seems wrong to me as it goes straight to the folder sites which does not exist.
Rollback to 1.0.0-next.565 works flawlessly.

### Reproduction

Create a new sveltekit project using 1.0.0-next.566
`npm i`
`npm run dev`

### Logs

```Shell
npm run dev

> sveltekit-test@0.0.1 dev
> vite dev


error when starting dev server:
Error: ENOENT: no such file or directory, open '/home/aisuko/dev/sveltekit-test/node_modules/sites/kit.svelte.dev/scripts/types/special-types/$env+static+private.md'
    at Object.openSync (node:fs:600:3)
    at Object.readFileSync (node:fs:468:35)
    at read_description (file:///home/aisuko/dev/sveltekit-test/node_modules/@sveltejs/kit/src/core/sync/write_ambient.js:17:21)
    at template (file:///home/aisuko/dev/sveltekit-test/node_modules/@sveltejs/kit/src/core/sync/write_ambient.js:33:3)
    at write_ambient (file:///home/aisuko/dev/sveltekit-test/node_modules/@sveltejs/kit/src/core/sync/write_ambient.js:58:3)
    at Module.init (file:///home/aisuko/dev/sveltekit-test/node_modules/@sveltejs/kit/src/core/sync/sync.js:36:2)
    at dev (file:///home/aisuko/dev/sveltekit-test/node_modules/@sveltejs/kit/src/exports/vite/dev/index.js:34:7)
    at configureServer (file:///home/aisuko/dev/sveltekit-test/node_modules/@sveltejs/kit/src/exports/vite/index.js:543:17)
    at createServer (file:///home/aisuko/dev/sveltekit-test/node_modules/vite/dist/node/chunks/dep-67e7f8ab.js:61815:30)
    at async CAC.<anonymous> (file:///home/aisuko/dev/sveltekit-test/node_modules/vite/dist/node/cli.js:707:24)
```

### System Info

```Shell
System:
    OS: Linux 5.15 Ubuntu 22.04.1 LTS 22.04.1 LTS (Jammy Jellyfish)
    CPU: (16) x64 AMD Ryzen 9 6900HS with Radeon Graphics
    Memory: 3.99 GB / 7.38 GB
    Container: Yes
    Shell: 5.8.1 - /usr/bin/zsh
  Binaries:
    Node: 18.12.1 - ~/.nvm/versions/node/v18.12.1/bin/node
    Yarn: 1.22.19 - ~/.nvm/versions/node/v18.12.1/bin/yarn
    npm: 8.19.2 - ~/.nvm/versions/node/v18.12.1/bin/npm
  npmPackages:
    @sveltejs/adapter-auto: next => 1.0.0-next.89 
    @sveltejs/kit: 1.0.0-next.565 => 1.0.0-next.565 
    svelte: ^3.44.0 => 3.53.1 
    vite: ^3.1.0 => 3.2.4
```

### Severity

blocking all usage of SvelteKit

**Comment by knd775** [comment]
Can confirm. Rolling back to `1.0.0-next.563` works fine.

**Comment by csjh** [comment]
Has to do with https://github.com/sveltejs/kit/blob/master/packages/kit/src/core/sync/write_ambient.js#L12

**Comment by kellenmace** [comment]
I'm getting this error when trying to update a SvelteKit app from 528 -> 529 🤷‍♂️

**Comment by indaco** [comment]
till `1.0.0-next.565` works fine to me
