### ISSUE TITLE
Cannot build as a package

### ISSUE THREAD

**Issue by ppusapati** [sveltejs/kit#788]
> Using @sveltejs/adapter-node
> Cannot destructure property 'Readable' of 'Stream__default.default' as it is undefined.
TypeError: Cannot destructure property 'Readable' of 'Stream__default.default' as it is undefined.
    at file:///home/projects/DPH/UI/Form/.svelte/output/server/app.js:271:10
    at file:///home/projects/DPH/UI/Form/.svelte/output/server/app.js:2:419
    at file:///home/projects/DPH/UI/Form/.svelte/output/server/app.js:3:3
    at ModuleJob.run (internal/modules/esm/module_job.js:140:23)
    at async Loader.import (internal/modules/esm/loader.js:165:24)
    at async prerender (file:///home/projects/DPH/UI/Form/node_modules/.pnpm/@sveltejs/kit@1.0.0-next.64_svelte@3.36.0+vite@2.1.4/node_modules/@sveltejs/kit/dist/chunks/index5.js:511:14)
    at async Builder.prerender (file:///home/projects/DPH/UI/Form/node_modules/.pnpm/@sveltejs/kit@1.0.0-next.64_svelte@3.36.0+vite@2.1.4/node_modules/@sveltejs/kit/dist/chunks/index5.js:743:4)
    at async adapt (/home/projects/DPH/UI/Form/node_modules/.pnpm/@sveltejs/adapter-node@1.0.0-next.10/node_modules/@sveltejs/adapter-node/index.js:26:4)
    at async adapt (file:///home/projects/DPH/UI/Form/node_modules/.pnpm/@sveltejs/kit@1.0.0-next.64_svelte@3.36.0+vite@2.1.4/node_modules/@sveltejs/kit/dist/chunks/index5.js:765:2)
    at async file:///home/projects/DPH/UI/Form/node_modules/.pnpm/@sveltejs/kit@1.0.0-next.64_svelte@3.36.0+vite@2.1.4/node_modules/@sveltejs/kit/dist/cli.js:604:5

my Svelte.config.cjs 

`const sveltePreprocess = require('svelte-preprocess');
const node = require('@sveltejs/adapter-node');
const pkg = require('./package.json');
const path = require('path');

/** @type {import('@sveltejs/kit').Config} */
module.exports = {
	// Consult https://github.com/sveltejs/svelte-preprocess
	// for more information about preprocessors
	preprocess: [
		sveltePreprocess(),
		require('svelte-windicss-preprocess').preprocess({
			config: 'tailwind.config.cjs', // tailwind config file path (optional)
			compile: false, // false: interpretation mode; true: compilation mode
			prefix: 'windi-', // set compilation mode style prefix
			globalPreflight: true, // set preflight style is global or scoped
			globalUtility: true // set utility style is global or scoped
		})
	],
	kit: {
		// By default, `npm run build` will create a standard Node app.
		// You can create optimized builds for different platforms by
		// specifying a different adapter
		adapter: node(),
		//target: '#svelte',

		vite: {
			build: {
				lib: { entry: 'DHSForms', name: 'DHSForms' }
			},
			resolve: {
				alias: {
					$components: path.resolve('src/components'),
					$templates: path.resolve('src/templates'),
					$hooks: path.resolve('src/hooks')
				}
			},
			ssr: {
				noExternal: Object.keys(pkg.dependencies || {})
			},
			plugins: [require('vite-plugin-windicss').default()]
		}
	}
};
`
Have tried by deleting app.html which gave another error

> ENOENT: no such file or directory, open '/home/projects/DPH/UI/icon/src/app.html'
Error: ENOENT: no such file or directory, open '/home/projects/DPH/UI/icon/src/app.html'
    at Object.openSync (fs.js:465:3)
    at Object.readFileSync (fs.js:368:35)
    at build_server (file:///home/projects/DPH/UI/icon/node_modules/.pnpm/@sveltejs/kit@1.0.0-next.64_svelte@3.36.0+vite@2.1.5/node_modules/@sveltejs/kit/dist/chunks/index4.js:275:48)
    at build (file:///home/projects/DPH/UI/icon/node_modules/.pnpm/@sveltejs/kit@1.0.0-next.64_svelte@3.36.0+vite@2.1.5/node_modules/@sveltejs/kit/dist/chunks/index4.js:52:8)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async file:///home/projects/DPH/UI/icon/node_modules/.pnpm/@sveltejs/kit@1.0.0-next.64_svelte@3.36.0+vite@2.1.5/node_modules/@sveltejs/kit/dist/cli.js:598:4

**Comment by benmccann** [comment]
There's not enough info here to reproduce this and it's not clear that there's an issue in SvelteKit and not just your own project. Please try Discord first. Also, if you can provide a repository that reproduces this you may be more likely to get a response

**Comment by ppusapati** [comment]
Have created a git repo here is the link.

https://github.com/ppusapati/sveltekit

**Comment by benmccann** [comment]
I'd recommend using https://github.com/svelte-add/tailwindcss to setup Tailwind. You can use the `--jit` flag for fast compilation which is probably much easier to setup and much more official than trying to use WindiCSS

**Comment by ppusapati** [comment]
Have updated my repository neither using tailwind or windiCSS but the problem persists.
