### ISSUE TITLE
@Apply inside <style> tag not recognizing custom classes in index page only

### ISSUE THREAD

**Issue by TophC7** [sveltejs/kit#7903]
### Describe the bug

I'm honestly not sure if this is a Tailwind issue or a Svelte kit issue but the problem is that if I try to use a custom `@layer components` class from tailwind inside the style tag of the home page aka `/` it will not be able to find the class and throw and error BUT if I use the same class inside the style tag of a deeper route e.i. `/about` it'll work the Vs plugin still complains about not being able to find it but till build and work as intended.

### Reproduction

Here's a [repo](https://github.com/TophC7/tailwind-svelte-bug) with an example of this just comment out the style in the first page to see the error then try the same on the about page and you'll see it works there.

### Logs

```
Error while preprocessing O:/Github/tailwind-svelte-bug/src/routes/+page.svelte - O:/Github/tailwind-svelte-bug/src/routes/+page.svelte:4:3: The `test` class does not exist. If `test` is a custom class, make sure it is defined within a `@layer` directive.
CssSyntaxError: Error while preprocessing O:/Github/tailwind-svelte-bug/src/routes/+page.svelte - O:/Github/tailwind-svelte-bug/src/routes/+page.svelte:4:3: The `test` class does not exist. If `test` is a custom class, make sure it is defined within a `@layer` directive.
    at Input.error (O:\Github\tailwind-svelte-bug\node_modules\postcss\lib\input.js:148:16)
    at AtRule.error (O:\Github\tailwind-svelte-bug\node_modules\postcss\lib\node.js:60:32)
    at processApply (O:\Github\tailwind-svelte-bug\node_modules\tailwindcss\lib\lib\expandApplyAtRules.js:376:29)
    at O:\Github\tailwind-svelte-bug\node_modules\tailwindcss\lib\lib\expandApplyAtRules.js:524:9
    at O:\Github\tailwind-svelte-bug\node_modules\tailwindcss\lib\processTailwindFeatures.js:55:50        
    at plugins (O:\Github\tailwind-svelte-bug\node_modules\tailwindcss\lib\index.js:38:63)
    at LazyResult.runOnRoot (O:\Github\tailwind-svelte-bug\node_modules\postcss\lib\lazy-result.js:339:16)
    at LazyResult.runAsync (O:\Github\tailwind-svelte-bug\node_modules\postcss\lib\lazy-result.js:393:26) 
    at LazyResult.async (O:\Github\tailwind-svelte-bug\node_modules\postcss\lib\lazy-result.js:221:30)    
    at LazyResult.then (O:\Github\tailwind-svelte-bug\node_modules\postcss\lib\lazy-result.js:206:17
```

### System Info

```Shell
System:
    OS: Windows 10 10.0.22621
    CPU: (12) x64 AMD Ryzen 5 3600 6-Core Processor
    Memory: 19.32 GB / 31.90 GB
  Binaries:
    Node: 18.9.0 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.19 - ~\scoop\apps\yarn\current\bin\yarn.CMD
    npm: 9.1.2 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Edge: Spartan (44.22621.819.0), Chromium (107.0.1418.62)
    Internet Explorer: 11.0.22621.1
  npmPackages:
    @sveltejs/adapter-auto: next => 1.0.0-next.90 
    @sveltejs/kit: next => 1.0.0-next.570 
    svelte: ^3.53.1 => 3.53.1 
    vite: ^3.2.4 => 3.2.4
```

### Severity

annoyance

### Additional Information

![Imgur](https://i.imgur.com/SiBNGo2.png)

**Comment by babichjacob** [comment]
This isn't a bug, and is [mentioned in Tailwind's docs](https://tailwindcss.com/docs/functions-and-directives#using-apply-with-per-component-css).

I responded in [your Discord thread here](https://discord.com/channels/457912077277855764/1047899734104350740/1047968814849077271).

**Comment by babichjacob** [comment]
(Only reopening because of the mention of different behavior on different routes)

**Comment by dummdidumm** [comment]
Closing, as the question seems to have been answered, as no more activity occured.
