### ISSUE TITLE
Routing conflicts occur when multiple optional parameters

### ISSUE THREAD

**Issue by shuaixr** [sveltejs/kit#7925]
### Describe the bug

Routing conflicts occur when the routes folder structure is as follows:
```
.
├── +page.svelte
└── path_a
    └── [[parameter_b]]
        └── [[parameter_c]]
            ├── +page.svelte
            └── +page.ts

```

### Reproduction

1.Create a sveltekit project

2.Let the routes folder structure look like this:
```
.
├── +page.svelte
└── path_a
    └── [[parameter_b]]
        └── [[parameter_c]]
            ├── +page.svelte
            └── +page.ts

```

3.Run `npm dev`

### Logs

```Shell
error when starting dev server:
Error: The "/path_a/[[parameter_b]]/[[parameter_c]]" and "/path_a/[[parameter_b]]/[[parameter_c]]" routes conflict with each other
    at prevent_conflicts (file:///home/username/svelte_project/node_modules/.pnpm/@sveltejs+kit@1.0.0-next.571_svelte@3.53.1+vite@3.2.4/node_modules/@sveltejs/kit/src/core/sync/create_manifest_data/index.js:504:11)
    at create_routes_and_nodes (file:///home/username/svelte_project/node_modules/.pnpm/@sveltejs+kit@1.0.0-next.571_svelte@3.53.1+vite@3.2.4/node_modules/@sveltejs/kit/src/core/sync/create_manifest_data/index.js:292:2)
    at create_manifest_data (file:///home/username/svelte_project/node_modules/.pnpm/@sveltejs+kit@1.0.0-next.571_svelte@3.53.1+vite@3.2.4/node_modules/@sveltejs/kit/src/core/sync/create_manifest_data/index.js:25:28)
    at Module.create (file:///home/username/svelte_project/node_modules/.pnpm/@sveltejs+kit@1.0.0-next.571_svelte@3.53.1+vite@3.2.4/node_modules/@sveltejs/kit/src/core/sync/sync.js:44:24)
    at update_manifest (file:///home/username/svelte_project/node_modules/.pnpm/@sveltejs+kit@1.0.0-next.571_svelte@3.53.1+vite@3.2.4/node_modules/@sveltejs/kit/src/exports/vite/dev/index.js:57:35)
    at dev (file:///home/username/svelte_project/node_modules/.pnpm/@sveltejs+kit@1.0.0-next.571_svelte@3.53.1+vite@3.2.4/node_modules/@sveltejs/kit/src/exports/vite/dev/index.js:197:8)
    at async configureServer (file:///home/username/svelte_project/node_modules/.pnpm/@sveltejs+kit@1.0.0-next.571_svelte@3.53.1+vite@3.2.4/node_modules/@sveltejs/kit/src/exports/vite/index.js:543:11)
    at async createServer (file:///home/username/svelte_project/node_modules/.pnpm/vite@3.2.4/node_modules/vite/dist/node/chunks/dep-67e7f8ab.js:61815:24)
    at async CAC.<anonymous> (file:///home/username/svelte_project/node_modules/.pnpm/vite@3.2.4/node_modules/vite/dist/node/cli.js:707:24)
 ELIFECYCLE  Command failed with exit code 1.
```

### System Info

```Shell
System:
    OS: Linux 5.10 Debian GNU/Linux 11 (bullseye) 11 (bullseye)
    CPU: (1) x64 AMD EPYC 7601 32-Core Processor
    Memory: 68.17 MB / 1.94 GB
    Container: Yes
    Shell: 5.1.4 - /bin/bash
  Binaries:
    Node: 18.12.1 - /usr/bin/node
    npm: 8.19.2 - /usr/bin/npm
  npmPackages:
    @sveltejs/adapter-auto: next => 1.0.0-next.90 
    @sveltejs/kit: next => 1.0.0-next.571 
    svelte: ^3.53.1 => 3.53.1 
    vite: ^3.2.4 => 3.2.4 

```

### Severity

annoyance

### Additional Information

I think this route is feasible and should not cause conflicts, and the document does not explain that situation will cause conflicts

**Comment by Conduitry** [comment]
What would `/path_a/foo` resolve to? Would `foo` be `parameter_b` or `parameter_c`? This doesn't seem entirely obvious to me. The error message is a little confusing though.

**Comment by shuaixr** [comment]
> What would `/path_a/foo` resolve to? Would `foo` be `parameter_b` or `parameter_c`? This doesn't seem entirely obvious to me. The error message is a little confusing though.

Is parameter_b.
Because the+page file only exists in [[parameter_c]].
