### ISSUE TITLE
Unable to build Sveltekit with adapter-node

### ISSUE THREAD

**Issue by kudadam** [sveltejs/kit#8042]
### Describe the bug

When I try run the app I build using adapter-node,  I see the error below

file:///C:/Projects/kudadam.com/build/server/chunks/server-f55d72c2.js:24606
            require.resolve("../lib/utils.js"),
            ^

ReferenceError: require is not defined in ES module scope, you can use import instead
This file is being treated as an ES module because it has a '.js' file extension and 'C:\Projects\kudadam.com\package.json' contains "type": "module". To treat it as a CommonJS script, rename it to use the '.cjs' file extension.
    at file:///C:/Projects/kudadam.com/build/server/chunks/server-f55d72c2.js:24606:6
    at file:///C:/Projects/kudadam.com/build/server/chunks/server-f55d72c2.js:24713:3
    at ModuleJob.run (node:internal/modules/esm/module_job:193:25)
    at async Promise.all (index 0)
    at async ESMLoader.import (node:internal/modules/esm/loader:530:24)
    at async Server.init (file:///C:/Projects/kudadam.com/build/server/index.js:3175:22)
    at async file:///C:/Projects/kudadam.com/build/handler.js:18758:1

Node.js v18.12.1

### Reproduction

Run any Sveltekit project with adapter-node

### System Info

```Shell
$ pnpx envinfo --system --binaries --browsers --npmPackages "{svelte,@sveltejs/*,vite}"
.../Local/pnpm/store/v3/tmp/dlx-12220    |   +1 +
.../Local/pnpm/store/v3/tmp/dlx-12220    | Progress: resolved 1, reused 0, downloaded 1, added 1, done

  System:
    OS: Windows 10 10.0.19044
    CPU: (4) x64 Intel(R) Core(TM) i5-4300U CPU @ 1.90GHz    
    Memory: 1.75 GB / 7.91 GB
  Binaries:
    Node: 18.12.1 - C:\Program Files\nodejs\node.EXE
    npm: 8.19.2 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Edge: Spartan (44.19041.1266.0), Chromium (108.0.1462.42)
  npmPackages:
    @sveltejs/adapter-node: 1.0.0-next.102 => 1.0.0-next.102 
    @sveltejs/kit: next => 1.0.0-next.577 
    svelte: ^3.54.0 => 3.54.0 
    vite: ^3.2.5 => 3.2.5
```

### Severity

blocking all usage of SvelteKit

**Comment by kudadam** [comment]
@tcc-sejohnson , I just tried running the code on a new repo but the problem is not there.
I cannot create a reproducible repo because I do not know the source of the problem

**Comment by kudadam** [comment]
```
	exports.FILES = [
	    require.resolve("../lib/utils.js"),
	    require.resolve("../lib/ast.js"),
	    require.resolve("../lib/transform.js"),
	    require.resolve("../lib/parse.js"),
	    require.resolve("../lib/scope.js"),
	    require.resolve("../lib/compress.js"),
	    require.resolve("../lib/output.js"),
	    require.resolve("../lib/sourcemap.js"),
	    require.resolve("../lib/mozilla-ast.js"),
	    require.resolve("../lib/propmangle.js"),
	    require.resolve("../lib/minify.js"),
	    require.resolve("./exports.js"),
	];
```

This is the code which is calling the require, I do not know what is responsible for it
