### ISSUE TITLE
Can't run in GraalVM

### ISSUE THREAD

**Issue by dcracken** [sveltejs/kit#8076]
### Describe the bug

Can't run vite dev in GraalVM's Node.js. I can install and update packages in npm.

### Reproduction

Install [GraalVM](https://www.graalvm.org/downloads/) and [Node.js](https://www.graalvm.org/22.1/reference-manual/js/NodeJS/) via [GraalVM Updater](https://www.graalvm.org/22.3/reference-manual/graalvm-updater/)

run
```bash
npm run dev
```

### Logs

```Shell
failed to load config from D:\Projects\sveltekit\freelance\vite.config.js
error when starting dev server:
TypeError: Invalid host defined options
    at eval (eval at <anonymous> (file:///D:/Projects/sveltekit/freelance/node_modules/vite/dist/node/chunks/dep-ed9cb113.js:12218:7), <anonymous>:1:2)
    at loadConfigFromBundledFile (file:///D:/Projects/sveltekit/freelance/node_modules/vite/dist/node/chunks/dep-ed9cb113.js:63072:27)
    at loadConfigFromFile (file:///D:/Projects/sveltekit/freelance/node_modules/vite/dist/node/chunks/dep-ed9cb113.js:62957:34)
    at runMicrotasks (native)
    at process.processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async resolveConfig (file:///D:/Projects/sveltekit/freelance/node_modules/vite/dist/node/chunks/dep-ed9cb113.js:62575:34)
    at async createServer (file:///D:/Projects/sveltekit/freelance/node_modules/vite/dist/node/chunks/dep-ed9cb113.js:61883:26)
    at async CAC.<anonymous> (file:///D:/Projects/sveltekit/freelance/node_modules/vite/dist/node/cli.js:730:30)
```

### System Info

```Shell
Kit version: 1.0.0-next.582
Vite version: 4.0.0
Node.js: 16.17.1
NPM: 8.15.0
```

### Severity

blocking all usage of SvelteKit

### Additional Information

I can run in Node.js 18.12.0(_Normal Node.js/Not GraalVM's_) without a problem. Is this a Node version or a Vite problem?

**Comment by Conduitry** [comment]
Presumably it's neither, presumably it's a GraalVM problem. This is not a supported environment.
