### ISSUE TITLE
Symbolic Link Issue

### ISSUE THREAD

**Issue by sanqi** [sveltejs/kit#8100]
### Describe the bug

While testing the application in dev mode, the symbolic link is functioning properly. However, when building the code, the symbolic link is causing an error.

### Reproduction

Steps to reproduce:

Initialize any demo
Add a symbol link in the routing directory
building the code

### Logs

```
[vite-plugin-sveltekit-setup] Cannot read properties of undefined (reading 'file')
error during build:
TypeError: Cannot read properties of undefined (reading 'file')
    at eval (file://file:///home/projects/sveltejs-kit-template-default-uys2ch/node_modules/@sveltejs/kit/src/exports/vite/build/build_server.js:329:75)
    at Array.forEach (<anonymous>)
    at Module.build_server (file://file:///home/projects/sveltejs-kit-template-default-uys2ch/node_modules/@sveltejs/kit/src/exports/vite/build/build_server.js:289:22)
    at async Object.handler (file://file:///home/projects/sveltejs-kit-template-default-uys2ch/node_modules/@sveltejs/kit/src/exports/vite/index.js:445:20)
    at async PluginDriver.hookParallel (file://file:///home/projects/sveltejs-kit-template-default-uys2ch/node_modules/rollup/dist/es/shared/rollup.js:23346:17)
    at async eval (file://file:///home/projects/sveltejs-kit-template-default-uys2ch/node_modules/rollup/dist/es/shared/rollup.js:24751:13)
    at async catchUnfinishedHookActions (file://file:///home/projects/sveltejs-kit-template-default-uys2ch/node_modules/rollup/dist/es/shared/rollup.js:23785:20)
    at async doBuild (file://file:///home/projects/sveltejs-kit-template-default-uys2ch/node_modules/vite/dist/node/chunks/dep-ed9cb113.js:45638:22)
    at async build (file://file:///home/projects/sveltejs-kit-template-default-uys2ch/node_modules/vite/dist/node/chunks/dep-ed9cb113.js:45466:16)
    at async CAC.eval (file://file:///home/projects/sveltejs-kit-template-default-uys2ch/node_modules/vite/dist/node/cli.js:825:9)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

### System Info

```Shell
System:
    OS: Linux 5.15 Ubuntu 20.04.5 LTS (Focal Fossa)
    CPU: (16) x64 AMD EPYC 7B13
    Memory: 13.81 GB / 62.80 GB
    Container: Yes
    Shell: 5.0.17 - /bin/bash
  Binaries:
    Node: 16.18.1 - ~/.nvm/versions/node/v16.18.1/bin/node
    Yarn: 1.22.19 - ~/.nvm/versions/node/v16.18.1/bin/yarn
    npm: 8.19.2 - ~/.nvm/versions/node/v16.18.1/bin/npm
  npmPackages:
    @sveltejs/adapter-auto: next => 1.0.0-next.90 
    @sveltejs/kit: next => 1.0.0-next.583 
    svelte: ^3.54.0 => 3.54.0 
    vite: ^4.0.0 => 4.0.0
```

### Severity

annoyance

**Comment by Conduitry** [comment]
What's the error message?

**Comment by jdnavarro** [comment]
It seems to be happenning only when symlinking `+page.js` files.

**Comment by yukipastelcat** [comment]
Having same issue, any news on this?
