### ISSUE TITLE
 Unexpected option config.kit.trailingSlash Since Updating SvelteKit

### ISSUE THREAD

**Issue by percybolmer** [sveltejs/kit#8241]
### Describe the bug

I updated SvelteKit and now there is no TrailingSlash option for Kit found

```log

> build
> vite build

error during build:
Error: Unexpected option config.kit.trailingSlash
    at file:///home/percy/private/blog/pp-blog-svelte/node_modules/@sveltejs/kit/src/core/config/options.js:264:12
    at file:///home/percy/private/blog/pp-blog-svelte/node_modules/@sveltejs/kit/src/core/config/options.js:271:18
    at validate_config (file:///home/percy/private/blog/pp-blog-svelte/node_modules/@sveltejs/kit/src/core/config/index.js:99:9)
    at process_config (file:///home/percy/private/blog/pp-blog-svelte/node_modules/@sveltejs/kit/src/core/config/index.js:71:20)
    at load_config (file:///home/percy/private/blog/pp-blog-svelte/node_modules/@sveltejs/kit/src/core/config/index.js:63:9)
    at async sveltekit (file:///home/percy/private/blog/pp-blog-svelte/node_modules/@sveltejs/kit/src/exports/vite/index.js:69:24)
    at async Promise.all (index 0)
    at async asyncFlatten (file:///home/percy/private/blog/pp-blog-svelte/node_modules/vite/dist/node/chunks/dep-6305614c.js:12397:16)
    at async resolveConfig (file:///home/percy/private/blog/pp-blog-svelte/node_modules/vite/dist/node/chunks/dep-6305614c.js:62646:29)
    at async doBuild (file:///home/percy/private/blog/pp-blog-svelte/node_modules/vite/dist/node/chunks/dep-6305614c.js:45474:20)
```

### Reproduction

I migrated an old Sveltekit Project and installed NPM after removed Node_modules folder.

This is the package.json

```json
{
  "private": true,
  "license": "MIT",
  "type": "module",
  "scripts": {
    "dev": "vite dev",
    "build": "vite build",
    "preview": "vite build && vite preview",
    "deploy": "vite build && touch build/.nojekyll && gh-pages -d build -t true"
  },
  "devDependencies": {
    "@popperjs/core": "^2.11.6",
    "@sveltejs/adapter-netlify": "^1.0.0-next.88",
    "@sveltejs/adapter-static": "^1.0.0-next.46",
    "@tailwindcss/typography": "^0.5.7",
    "autoprefixer": "^10.4.12",
    "classnames": "^2.3.2",
    "gh-pages": "^4.0.0",
    "mdsvex": "^0.10.6",
    "postcss": "^8.4.18",
    "remark-abbr": "^1.4.1",
    "remark-github": "^11.2.4",
    "sass": "^1.55.0",
    "tailwindcss": "^3.2.1",
    "vite": "^4.0.0",
    "vite-imagetools": "^4.0.11"
  },
  "dependencies": {
    "@sveltejs/kit": "^1.0.1",
    "lazyframe": "^2.2.7",
    "lite-youtube-embed": "^0.2.0",
    "rehype-autolink-headings": "^6.1.1",
    "rehype-slug": "^5.0.1",
    "rehype-urls": "^1.1.1",
    "scss": "^0.2.4",
    "svelte": "^3.55.0",
    "svelte-preprocess": "^5.0.0",
    "svelte-typewriter": "^3.1.4"
  }
}

```

### System Info

```Shell
System:
    OS: Linux 5.15 Ubuntu 20.04.5 LTS (Focal Fossa)
    CPU: (16) x64 11th Gen Intel(R) Core(TM) i7-11800H @ 2.30GHz
    Memory: 7.88 GB / 15.36 GB
    Container: Yes
    Shell: 5.0.17 - /bin/bash
  Binaries:
    Node: 18.12.1 - ~/.nvm/versions/node/v18.12.1/bin/node
    Yarn: 1.22.19 - ~/.nvm/versions/node/v17.9.1/bin/yarn
    npm: 8.19.2 - ~/.nvm/versions/node/v18.12.1/bin/npm
  Browsers:
    Brave Browser: 107.1.45.127
    Chrome: 107.0.5304.110
    Firefox: 108.0
  npmPackages:
    @sveltejs/adapter-netlify: ^1.0.0-next.88 => 1.0.0-next.88 
    @sveltejs/adapter-static: ^1.0.0-next.46 => 1.0.0-next.46 
    @sveltejs/kit: ^1.0.1 => 1.0.1 
    svelte: ^3.55.0 => 3.55.0 
    vite: ^4.0.0 => 4.0.2
```

### Severity

blocking an upgrade

**Comment by dummdidumm** [comment]
Please first upgrade to the last version that still contains all the migration hints as described [here](https://github.com/sveltejs/kit/discussions/5774) (that version is `1.0.0-next.588`). Then you see that that option has been removed in #7719 (that PR contains more info on how to migrate).
