### ISSUE TITLE
URL path cap-sensitiveity

### ISSUE THREAD

**Issue by Dog2657** [sveltejs/kit#8292]
### Describe the bug

I have notest that when trying to access a page when using a url with no capitalization the server will throw 404 error.

e.g:
 path: src/routes/TestHere/+page.svelte

Invalid URL: /testhere
Valid URL: /TestHere

### Reproduction

https://stackblitz.com/edit/sveltejs-kit-template-default-neokcy?file=src/TestHere/+page.svelte

### Logs

```Shell
Not found: /testHere
Error: Not found: /testHere
    at resolve (file://file:///home/projects/sveltejs-kit-template-default-neokcy/node_modules/@sveltejs/kit/src/runtime/server/index.js:395:13)
    at resolve (file://file:///home/projects/sveltejs-kit-template-default-neokcy/node_modules/@sveltejs/kit/src/runtime/server/index.js:247:5)
    at Object.handle (file://file:///home/projects/sveltejs-kit-template-default-neokcy/node_modules/@sveltejs/kit/src/exports/vite/dev/index.js:397:66)
    at respond (file://file:///home/projects/sveltejs-kit-template-default-neokcy/node_modules/@sveltejs/kit/src/runtime/server/index.js:244:40)
    at async eval (file://file:///home/projects/sveltejs-kit-template-default-neokcy/node_modules/@sveltejs/kit/src/exports/vite/dev/index.js:461:22)
```

### System Info

```Shell
System:
    OS: Windows 10 10.0.22621
    CPU: (12) x64 AMD Ryzen 5 3600 6-Core Processor
    Memory: 23.85 GB / 31.92 GB
  Binaries:
    Node: 18.2.0 - C:\Program Files\nodejs\node.EXE
    npm: 8.10.0 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Edge: Spartan (44.22621.963.0), Chromium (108.0.1462.54)
    Internet Explorer: 11.0.22621.1
  npmPackages:
    @sveltejs/adapter-auto: ^1.0.0 => 1.0.0
    @sveltejs/kit: ^1.0.0 => 1.0.1
    svelte: ^3.54.0 => 3.55.0
    vite: ^4.0.0 => 4.0.3
```

### Severity

annoyance

**Comment by Conduitry** [comment]
This is the intended behavior. Just because you're on Windows, the URLs aren't going to be case insensitive.
