### ISSUE TITLE
Node adapter has reproducibility issues. (node fault?)

### ISSUE THREAD

**Issue by VentGrey** [sveltejs/kit#8339]
### Describe the bug

Trying to deploy a SvelteKit application using the `adapter-node` has some strange reproducibility issues. Mainly in the server when trying to run it.

### Reproduction

Just try deploying on a server. Make a systemd unit service OR run it by yourself:

## On local machine
```
$ node build
Listening on 0.0.0.0:3000
```

## On server (exact same code)
```
node build
/var/www/html/site.com/build/index.js:1
import { handler } from './handler.js';
       ^

SyntaxError: Unexpected token {
    at Module._compile (internal/modules/cjs/loader.js:723:23)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:831:12)
    at startup (internal/bootstrap/node.js:283:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:623:3)

```

### Logs

```Shell
node build
/var/www/html/site.com/build/index.js:1
import { handler } from './handler.js';
       ^

SyntaxError: Unexpected token {
    at Module._compile (internal/modules/cjs/loader.js:723:23)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:831:12)
    at startup (internal/bootstrap/node.js:283:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:623:3)

```
```


### System Info

```Shell
System:
    OS: Linux 6.1 Rocky Linux
    CPU: (1) x64 AMD EPYC 7601 32-Core Processor
    Memory: 126.72 MB / 804.71 MB
    Container: Yes
    Shell: 4.4.20 - /bin/bash
  Binaries:
    Node: 10.24.0 - /usr/bin/node
    npm: 6.14.11 - /usr/bin/npm
```

### Severity

annoyance

### Additional Information

I don't know if this is the adapters failing at some point of if the `node` version packed in rocky linux is incompatible with my builds.

**Comment by Conduitry** [comment]
SvelteKit needs Node 16.14+. Node 10 has been end-of-life since April 2021 and hasn't received security fixes since then and shouldn't be used for anything now anyway.

**Comment by VentGrey** [comment]
I've tried deploying on a different server (This time with node `18.12.1`).

It gives the same error, but with an additional warning:

## In journalctl (as a systemd service)
```
Jan 05 06:01:51 localhost node[13629]: (node:13629) Warning: To load an ES module, set "type": "module" in the package.json or use the >
Jan 05 06:01:51 localhost node[13629]: (Use `node --trace-warnings ...` to show where the warning was created)
Jan 05 06:01:51 localhost node[13629]: /var/www/html/site.com/build/index.js:1
Jan 05 06:01:51 localhost node[13629]: import { handler } from './handler.js';
Jan 05 06:01:51 localhost node[13629]: ^^^^^^
Jan 05 06:01:51 localhost node[13629]: SyntaxError: Cannot use import statement outside a module
Jan 05 06:01:51 localhost node[13629]:     at Object.compileFunction (node:vm:360:18)
Jan 05 06:01:51 localhost node[13629]:     at wrapSafe (node:internal/modules/cjs/loader:1088:15)
Jan 05 06:01:51 localhost node[13629]:     at Module._compile (node:internal/modules/cjs/loader:1123:27)
Jan 05 06:01:51 localhost node[13629]:     at Module._extensions..js (node:internal/modules/cjs/loader:1213:10)
Jan 05 06:01:51 localhost node[13629]:     at Module.load (node:internal/modules/cjs/loader:1037:32)
Jan 05 06:01:51 localhost node[13629]:     at Module._load (node:internal/modules/cjs/loader:878:12)
Jan 05 06:01:51 localhost node[13629]:     at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:81:12)
Jan 05 06:01:51 localhost node[13629]:     at node:internal/main/run_main_module:23:47
Jan 05 06:01:51 localhost node[13629]: Node.js v18.12.1
Jan 05 06:01:51 localhost systemd[1]: SvelteKit.service: Main process exited, code=exited, status=1/FAILURE
```

## Running it manually
```
root@localhost:~# node /var/www/html/site.com/build
(node:13771) Warning: To load an ES module, set "type": "module" in the package.json or use the .mjs extension.
(Use `node --trace-warnings ...` to show where the warning was created)
/var/www/html/site.com/build/index.js:1
import { handler } from './handler.js';
^^^^^^

SyntaxError: Cannot use import statement outside a module
    at Object.compileFunction (node:vm:360:18)
    at wrapSafe (node:internal/modules/cjs/loader:1088:15)
    at Module._compile (node:internal/modules/cjs/loader:1123:27)
    at Module._extensions..js (node:internal/modules/cjs/loader:1213:10)
    at Module.load (node:internal/modules/cjs/loader:1037:32)
    at Module._load (node:internal/modules/cjs/loader:878:12)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:81:12)
    at node:internal/main/run_main_module:23:47

Node.js v18.12.1
```

**Comment by tontonsb** [comment]
@Conduitry this is a real issue. The build does not include any `package.json` so it is only usable while the build directory stays within the project. As soon as it's copied or built somewhere else, it's not working.
