### ISSUE TITLE
Prerendering failed with code 1

### ISSUE THREAD

**Issue by VanDerLars** [sveltejs/kit#8413]
### Describe the bug

I am not able to build my quite simple project.

yarn dev works perfect, but when I do yarn build, it fails.

I disabled prerender on all file using `export const prerender = false;`

I also searched through google and went through the issues-list here, I just cannot solve the problem. It was mentioned before, but the suggested solutions don't apply to my project (at least afasics).

Here's the output of the build command:

```
> yarn build

vite v4.0.4 building SSR bundle for production...
✓ 48 modules transformed.
17:53:40 [vite-plugin-svelte] ssr compile done.
package         files     time     avg
lullab.ai           3   52.1ms  17.4ms
@sveltejs/kit       1   17.4ms  17.4ms
Generated an empty chunk: "hooks".
.svelte-kit/output/server/vite-manifest.json                  1.20 kB
.svelte-kit/output/server/chunks/hooks.js                     0.00 kB
.svelte-kit/output/server/entries/pages/_layout.svelte.js     0.47 kB
.svelte-kit/output/server/entries/fallbacks/error.svelte.js   0.83 kB
.svelte-kit/output/server/entries/pages/_page.server.ts.js    1.99 kB
.svelte-kit/output/server/entries/pages/_page.svelte.js       2.65 kB
.svelte-kit/output/server/chunks/index.js                     3.68 kB
.svelte-kit/output/server/index.js                           82.19 kB
file:///Users/larslehmann/Projects/GithubDesktop/lullab.ai/node_modules/@sveltejs/kit/src/utils/exports.js:17
                                throw new Error(
                                      ^

Error: Invalid export 'lengths' in / (valid exports are load, prerender, csr, ssr, actions, trailingSlash, or anything with a '_' prefix)
    at validate (file:///[private_path]/lullab.ai/node_modules/@sveltejs/kit/src/utils/exports.js:17:11)
    at prerender (file:///[private_path]/lullab.ai/node_modules/@sveltejs/kit/src/core/prerender/prerender.js:390:5)

Node.js v18.12.1
[vite-plugin-sveltekit-compile] Prerendering failed with code 1
error during build:
Error: Prerendering failed with code 1
    at ChildProcess.<anonymous> (file:///[private_path]/lullab.ai/node_modules/@sveltejs/kit/src/exports/vite/index.js:551:15)
    at ChildProcess.emit (node:events:513:28)
    at ChildProcess._handle.onexit (node:internal/child_process:291:12)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

### Reproduction

here's a test application:
https://github.com/VanDerLars/Luallab.ai_2

its fairly simple but I just cannot find the issue

### System Info

```Shell
Brave/Chrome, MacOS Ventura, Sveltekit 1.0.
```

### Severity

blocking all usage of SvelteKit

**Comment by Conduitry** [comment]
As the error explains, there are specific allowable export names in https://github.com/VanDerLars/Luallab.ai_2/blob/main/lullab.ai/src/routes/%2Bpage.server.ts and you are trying to export something else. You need to prefix exports that SvelteKit doesn't know what to do with with a `/`.
