### ISSUE TITLE
Cannot import $service-worker

### ISSUE THREAD

**Issue by mweissen** [sveltejs/kit#857]
**Describe the bug**

This line

> import { build, files, timestamp } from '$service-worker';

gives the following error message:

`
Error: [vite]: Rollup failed to resolve import "$service-worker" from "src\routes\index.svelte".
This is most likely unintended because it can break your application at runtime.
`

**Expected behavior**
No error message.

**Stacktraces**

<details>
 
If you do want to externalize this module explicitly add it to
`build.rollupOptions.external`
    at onRollupWarning (C:\Svelte\edudays2021\node_modules\vite\dist\node\chunks\dep-66eb515d.js:44389:19)
    at Object.onwarn (C:\Svelte\edudays2021\node_modules\vite\dist\node\chunks\dep-66eb515d.js:44239:17)
    at Object.onwarn (C:\Svelte\edudays2021\node_modules\rollup\dist\shared\rollup.js:19784:20)
    at ModuleLoader.handleResolveId (C:\Svelte\edudays2021\node_modules\rollup\dist\shared\rollup.js:18526:26)
    at C:\Svelte\edudays2021\node_modules\rollup\dist\shared\rollup.js:18480:22
    at async Promise.all (index 2)
    at async ModuleLoader.fetchStaticDependencies (C:\Svelte\edudays2021\node_modules\rollup\dist\shared\rollup.js:18478:34)
    at async Promise.all (index 0)
    at async ModuleLoader.fetchModule (C:\Svelte\edudays2021\node_modules\rollup\dist\shared\rollup.js:18454:9)
    at async Promise.all (index 1)

</details>

**Information about your SvelteKit Installation:**

<details>
  
- The output of `npx envinfo --system --npmPackages svelte,@sveltejs/kit,vite --binaries --browsers`
 System:
    OS: Windows 10 10.0.19042
    CPU: (12) x64 Intel(R) Xeon(R) CPU           X5650  @ 2.67GHz
    Memory: 14.81 GB / 31.98 GB
  Binaries:
    Node: 14.15.0 - C:\Program Files\nodejs\node.EXE
    npm: 6.14.8 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Edge: Spartan (44.19041.423.0), Chromium (89.0.774.68)
    Internet Explorer: 11.0.19041.1
  npmPackages:
    @sveltejs/kit: next => 1.0.0-next.70
    svelte: ^3.29.0 => 3.37.0
    vite: ^2.1.0 => 2.1.5

- Your browser
Google Chrome

- Your adapter (e.g. Node, static, Vercel, Begin, etc...)
Node
</details>

**Severity**

It is necessary to use the service-worker.

**Comment by Conduitry** [comment]
`$service-worker` is only available inside your service worker, and it looks like you are trying to import it from a route. https://kit.svelte.dev/docs#modules-service-worker

**Comment by mweissen** [comment]
Ok, thank you.  I obviously didn't read the text carefully enough.

Actually, I just wanted to know what files need to be cached in order to apply an app offline. Maybe you have an answer to that?
