### ISSUE TITLE
As of @sveltejs/kit@1.0.13, getting build errors loading JSON from environmental variables

### ISSUE THREAD

**Issue by nstuyvesant** [sveltejs/kit#8646]
### Describe the bug

After bumping @sveltejs/kit from 1.0.12 to 1.0.13 (with no other code changes), running `rpm run build` started throwing errors toward the end of outputting chunks (see logs below). Reverting to 1.0.12 causes the build to work again.

### Reproduction

The error referenced is the third line here:
```javascript
import { e as env } from "./env-private.js";
const { GOOGLE_RECAPTCHA_SECRET } = env;
const BRAINTREE_DESCRIPTOR = JSON.parse(env.BRAINTREE_DESCRIPTOR || "");
```

This is what that environmental variable looks like:
```
BRAINTREE_DESCRIPTOR={"name": "SH YYYY*Class Workshop", "phone": "212-555-1212", "url": "example.com"}
```

The first line of the code above in the original source is:
```typescript
import { env } from '$env/dynamic/private'
```

### Logs

```Shell
> shy-svelte@3.0.4 build
> vite build


vite v4.0.4 building for production...

✓ 1784 modules transformed.
7:31:48 AM [vite-plugin-svelte] dom compile done.
package   	files	 time	   avg
shy-svelte	   94	1.50s	16.0ms

vite v4.0.4 building SSR bundle for production...
✓ 435 modules transformed.
7:16:32 AM [vite-plugin-svelte] ssr compile done.
package   	files	 time	  avg
shy-svelte	   94	0.29s	3.1ms
.svelte-kit/output/server/vite-manifest.json                                             25.42 kB
.svelte-kit/output/server/chunks/prod-ssr.js                                              0.12 kB │ map:     0.23 kB
.svelte-kit/output/server/entries/pages/auth/reset/_token_/_page.ts.js                    0.14 kB │ map:     0.38 kB
.svelte-kit/output/server/entries/pages/_layout.server.ts.js                              0.15 kB │ map:     0.48 kB
.svelte-kit/output/server/entries/pages/classes/_locationId_/_page.ts.js                  0.15 kB │ map:     0.41 kB
.svelte-kit/output/server/chunks/env-private.js                                           0.16 kB │ map:     0.38 kB
.svelte-kit/output/server/internal.js                                                     0.18 kB │ map:     0.09 kB
.svelte-kit/output/server/entries/endpoints/api/announcement/active.json/_server.ts.js    0.20 kB │ map:     0.47 kB
.svelte-kit/output/server/entries/pages/register/_page.server.ts.js                       0.21 kB │ map:     0.50 kB
.svelte-kit/output/server/entries/endpoints/api/class/_server.ts.js                       0.22 kB │ map:     0.49 kB
.svelte-kit/output/server/entries/endpoints/api/product/_server.ts.js                     0.22 kB │ map:     0.50 kB
.svelte-kit/output/server/entries/endpoints/api/user/_id_/_server.ts.js                   0.22 kB │ map:     0.49 kB
.svelte-kit/output/server/entries/endpoints/api/location/_server.ts.js                    0.23 kB │ map:     0.51 kB
.svelte-kit/output/server/entries/endpoints/api/workshop/_server.ts.js                    0.23 kB │ map:     0.51 kB
.svelte-kit/output/server/entries/endpoints/api/class/_id_/_server.ts.js                  0.23 kB │ map:     0.50 kB
.svelte-kit/output/server/entries/endpoints/api/product/_id_/_server.ts.js                0.23 kB │ map:     0.50 kB
.svelte-kit/output/server/entries/endpoints/api/location/_id_/_server.ts.js               0.23 kB │ map:     0.51 kB
.svelte-kit/output/server/entries/endpoints/api/workshop/_id_/_server.ts.js               0.23 kB │ map:     0.51 kB
.svelte-kit/output/server/entries/endpoints/api/announcement/_server.ts.js                0.23 kB │ map:     0.52 kB
.svelte-kit/output/server/entries/pages/checkout/_page.ts.js                              0.23 kB │ map:     0.53 kB
.svelte-kit/output/server/entries/endpoints/api/payment/order/_server.ts.js               0.24 kB │ map:     0.55 kB
.svelte-kit/output/server/entries/endpoints/api/schedule/_server.ts.js                    0.24 kB │ map:     0.53 kB
.svelte-kit/output/server/entries/endpoints/api/history/_server.ts.js                     0.24 kB │ map:     0.53 kB
.svelte-kit/output/server/entries/endpoints/api/announcement/_id_/_server.ts.js           0.24 kB │ map:     0.53 kB
.svelte-kit/output/server/entries/endpoints/api/product/_id_.json/_server.ts.js           0.24 kB │ map:     0.53 kB
.svelte-kit/output/server/entries/endpoints/api/location/_id_.json/_server.ts.js          0.24 kB │ map:     0.53 kB
.svelte-kit/output/server/entries/endpoints/api/user/_id_.json/_server.ts.js              0.24 kB │ map:     0.53 kB
.svelte-kit/output/server/entries/endpoints/api/workshop/_id_.json/_server.ts.js          0.24 kB │ map:     0.53 kB
.svelte-kit/output/server/entries/endpoints/api/schedule/_id_/_server.ts.js               0.24 kB │ map:     0.52 kB
.svelte-kit/output/server/entries/endpoints/api/class/_id_.json/_server.ts.js             0.25 kB │ map:     0.53 kB
.svelte-kit/output/server/entries/endpoints/api/schedule/_id_.json/_server.ts.js          0.25 kB │ map:     0.54 kB
.svelte-kit/output/server/entries/endpoints/api/announcement/_id_.json/_server.ts.js      0.25 kB │ map:     0.56 kB
.svelte-kit/output/server/entries/pages/reserve/_page.server.ts.js                        0.26 kB │ map:     0.53 kB
.svelte-kit/output/server/entries/endpoints/api/payment/_id_.json/_server.ts.js           0.28 kB │ map:     0.56 kB
.svelte-kit/output/server/entries/pages/_page.ts.js                                       0.33 kB │ map:     0.69 kB
.svelte-kit/output/server/chunks/db.js                                                    0.34 kB │ map:     0.90 kB
.svelte-kit/output/server/entries/pages/profile/_page.server.ts.js                        0.38 kB │ map:     0.78 kB
.svelte-kit/output/server/entries/pages/_layout.ts.js                                     0.39 kB │ map:     0.88 kB
.svelte-kit/output/server/entries/pages/classes/_page.svelte.js                           0.39 kB │ map:     0.10 kB
.svelte-kit/output/server/entries/pages/shynet/_page.ts.js                                0.42 kB │ map:     0.80 kB
.svelte-kit/output/server/entries/pages/admin/_page.ts.js                                 0.44 kB │ map:     0.84 kB
.svelte-kit/output/server/chunks/history.js                                               0.44 kB │ map:     0.72 kB
.svelte-kit/output/server/entries/endpoints/api/teacher/current.json/_server.ts.js        0.47 kB │ map:     0.85 kB
.svelte-kit/output/server/entries/endpoints/api/unsubscribe/_email_/_server.ts.js         0.49 kB │ map:     0.86 kB
.svelte-kit/output/server/entries/endpoints/api/master/admin.json/_server.ts.js           0.50 kB │ map:     0.90 kB
.svelte-kit/output/server/chunks/stores.js                                                0.50 kB │ map:     1.80 kB
.svelte-kit/output/server/entries/pages/_error.svelte.js                                  0.52 kB │ map:     0.33 kB
.svelte-kit/output/server/entries/endpoints/api/user/merge/_server.ts.js                  0.53 kB │ map:     1.01 kB
.svelte-kit/output/server/entries/endpoints/api/master/active.json/_server.ts.js          0.54 kB │ map:     0.89 kB
.svelte-kit/output/server/entries/endpoints/api/subscribe/_server.ts.js                   0.54 kB │ map:     0.92 kB
.svelte-kit/output/server/entries/endpoints/api/payment/search.json/_server.ts.js         0.56 kB │ map:     1.05 kB
.svelte-kit/output/server/entries/endpoints/api/class/search.json/_server.ts.js           0.56 kB │ map:     1.05 kB
.svelte-kit/output/server/entries/endpoints/api/product/search.json/_server.ts.js         0.56 kB │ map:     1.05 kB
.svelte-kit/output/server/entries/endpoints/api/location/search.json/_server.ts.js        0.56 kB │ map:     1.06 kB
.svelte-kit/output/server/entries/endpoints/api/workshop/search.json/_server.ts.js        0.56 kB │ map:     1.06 kB
.svelte-kit/output/server/entries/endpoints/api/announcement/search.json/_server.ts.js    0.56 kB │ map:     1.07 kB
.svelte-kit/output/server/entries/pages/classes/_locationId_/_page.svelte.js              0.56 kB │ map:     0.42 kB
.svelte-kit/output/server/entries/endpoints/api/schedule/search.json/_server.ts.js        0.56 kB │ map:     1.07 kB
.svelte-kit/output/server/entries/endpoints/api/history/_what_-_id_.json/_server.ts.js    0.57 kB │ map:     1.05 kB
.svelte-kit/output/server/entries/endpoints/api/history/_what_-_id_/_server.ts.js         0.57 kB │ map:     1.05 kB
.svelte-kit/output/server/entries/endpoints/api/user/search.json/_server.ts.js            0.58 kB │ map:     1.08 kB
.svelte-kit/output/server/chunks/config.js                                                0.58 kB │ map:     0.61 kB
.svelte-kit/output/server/chunks/hooks.server.js                                          0.61 kB │ map:     1.45 kB
.svelte-kit/output/server/entries/endpoints/api/file/_server.ts.js                        0.62 kB │ map:     1.14 kB
.svelte-kit/output/server/entries/endpoints/api/file/_filenum_/_server.ts.js              0.66 kB │ map:     1.21 kB
.svelte-kit/output/server/chunks/user.js                                                  0.67 kB │ map:     1.22 kB
.svelte-kit/output/server/entries/endpoints/api/history/me.json/_server.ts.js             0.68 kB │ map:     1.26 kB
.svelte-kit/output/server/entries/endpoints/api/history/search.json/_server.ts.js         0.73 kB │ map:     1.34 kB
.svelte-kit/output/server/entries/endpoints/api/message/_server.ts.js                     0.77 kB │ map:     1.39 kB
.svelte-kit/output/server/entries/endpoints/auth/reset/_server.ts.js                      0.82 kB │ map:     1.50 kB
.svelte-kit/output/server/entries/endpoints/auth/forgot/_server.ts.js                     1.11 kB │ map:     2.05 kB
.svelte-kit/output/server/entries/endpoints/api/attendance/search.json/_server.ts.js      1.18 kB │ map:     2.08 kB
.svelte-kit/output/server/chunks/enums.js                                                 1.28 kB │ map:     1.32 kB
.svelte-kit/output/server/chunks/stores2.js                                               1.30 kB │ map:     3.09 kB
.svelte-kit/output/server/chunks/index2.js                                                1.35 kB │ map:     4.32 kB
.svelte-kit/output/server/entries/pages/teachers/_page.svelte.js                          1.39 kB │ map:     1.31 kB
.svelte-kit/output/server/chunks/sendgrid.js                                              1.41 kB │ map:     2.52 kB
.svelte-kit/output/server/chunks/AddToCart.js                                             1.57 kB │ map:     1.56 kB
.svelte-kit/output/server/entries/endpoints/api/user/_server.ts.js                        1.61 kB │ map:     2.90 kB
.svelte-kit/output/server/entries/pages/forgot/_page.svelte.js                            1.64 kB │ map:     2.75 kB
.svelte-kit/output/server/entries/pages/merge/_page.svelte.js                             1.96 kB │ map:     3.01 kB
.svelte-kit/output/server/entries/endpoints/auth/google/_server.ts.js                     1.97 kB │ map:     3.64 kB
.svelte-kit/output/server/entries/endpoints/auth/_operation_/_server.ts.js                1.99 kB │ map:     3.74 kB
.svelte-kit/output/server/chunks/datetime.extensions.js                                   2.05 kB │ map:     4.48 kB
.svelte-kit/output/server/chunks/index.js                                                 2.19 kB │ map:     5.67 kB
.svelte-kit/output/server/entries/pages/auth/reset/_token_/_page.svelte.js                2.34 kB │ map:     3.83 kB
.svelte-kit/output/server/chunks/crud.js                                                  2.45 kB │ map:     4.64 kB
.svelte-kit/output/server/chunks/Paginator.js                                             2.56 kB │ map:     3.15 kB
.svelte-kit/output/server/entries/endpoints/api/history/reservation/_server.ts.js         2.65 kB │ map:     4.72 kB
.svelte-kit/output/server/entries/pages/teachertraining/_page.svelte.js                   2.77 kB │ map:     2.61 kB
.svelte-kit/output/server/entries/pages/history/_page.svelte.js                           2.92 kB │ map:     3.95 kB
.svelte-kit/output/server/entries/pages/login/_page.svelte.js                             3.13 kB │ map:     5.25 kB
.svelte-kit/output/server/chunks/CartEditor.js                                            3.18 kB │ map:    11.40 kB
.svelte-kit/output/server/entries/pages/reserve/_page.svelte.js                           3.19 kB │ map:     5.43 kB
.svelte-kit/output/server/entries/pages/register/_page.svelte.js                          3.58 kB │ map:     6.41 kB
.svelte-kit/output/server/entries/pages/confirmation/_page.svelte.js                      3.61 kB │ map:     4.43 kB
.svelte-kit/output/server/entries/pages/leta/_page.svelte.js                              3.61 kB │ map:     0.13 kB
.svelte-kit/output/server/entries/pages/privacy/_page.svelte.js                           3.69 kB │ map:     0.16 kB
.svelte-kit/output/server/entries/pages/profile/_page.svelte.js                           4.22 kB │ map:     6.35 kB
.svelte-kit/output/server/chunks/AddToCalendar.js                                         5.33 kB │ map:     5.83 kB
.svelte-kit/output/server/entries/pages/shynet/_page.svelte.js                            5.93 kB │ map:     8.52 kB
.svelte-kit/output/server/entries/pages/workshops/_page.svelte.js                         7.28 kB │ map:    10.41 kB
.svelte-kit/output/server/chunks/index3.js                                                8.07 kB │ map:    86.24 kB
.svelte-kit/output/server/entries/pages/terms/_page.svelte.js                             8.98 kB │ map:     0.24 kB
.svelte-kit/output/server/entries/pages/_page.svelte.js                                   9.12 kB │ map:     6.87 kB
.svelte-kit/output/server/entries/pages/checkout/_page.svelte.js                          9.31 kB │ map:    26.50 kB
.svelte-kit/output/server/chunks/payment.js                                              11.37 kB │ map:    18.59 kB
.svelte-kit/output/server/chunks/server-internal.js                                      18.81 kB │ map:    27.44 kB
.svelte-kit/output/server/entries/pages/_layout.svelte.js                                23.21 kB │ map:    28.32 kB
.svelte-kit/output/server/chunks/Users.js                                                29.91 kB │ map:    45.56 kB
.svelte-kit/output/server/chunks/Classes.js                                              37.04 kB │ map:    55.54 kB
.svelte-kit/output/server/index.js                                                       76.12 kB │ map:   174.92 kB
.svelte-kit/output/server/entries/pages/admin/_page.svelte.js                           811.10 kB │ map: 1,628.12 kB
undefined:1


SyntaxError: Unexpected end of JSON input
    at JSON.parse (<anonymous>)
    at file:///Users/nates/dev/shy-svelte/.svelte-kit/output/server/chunks/payment.js:7:35
    at ModuleJob.run (node:internal/modules/esm/module_job:194:25)

Node.js v18.13.0
[vite-plugin-sveltekit-compile] Prerendering failed with code 1
error during build:
Error: Prerendering failed with code 1
    at ChildProcess.<anonymous> (file:///Users/nates/dev/shy-svelte/node_modules/@sveltejs/kit/src/exports/vite/index.js:629:15)
    at ChildProcess.emit (node:events:513:28)
    at ChildProcess._handle.onexit (node:internal/child_process:291:12)
```
```


### System Info

```Shell
System:
    OS: macOS 13.1
    CPU: (10) arm64 Apple M1 Pro
    Memory: 386.08 MB / 32.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 18.13.0 - /opt/homebrew/bin/node
    Yarn: 1.22.19 - /opt/homebrew/bin/yarn
    npm: 9.3.1 - /opt/homebrew/bin/npm
  Browsers:
    Chrome: 109.0.5414.87
    Firefox: 108.0.2
    Safari: 16.2
  npmPackages:
    @sveltejs/adapter-node: ^1.1.4 => 1.1.4 
    @sveltejs/kit: 1.2.2 => 1.2.2 
    svelte: ^3.55.1 => 3.55.1 
    vite: ^4.0.4 => 4.0.4
```

### Severity

blocking an upgrade

**Comment by Conduitry** [comment]
Please provide a complete reproduction.

Also, does this also happen with the latest version of SvelteKit?

**Comment by nstuyvesant** [comment]
Here's a complete repro using the SvelteKit skeleton...
https://github.com/nstuyvesant/issue-8646

It happens with the latest SvelteKit (1.2.2 as of this writing) and any version from 1.0.13 on.

**Comment by nstuyvesant** [comment]
I should also mention that `npm run dev` - no problems.
