### ISSUE TITLE
Not able to generate static site using @sveltejs/adapter-static with bootstrape installed

### ISSUE THREAD

**Issue by alokmahor** [sveltejs/kit#8776]
### Describe the bug

I created [sveltekit][1] app using `npm create svelte@latest my-app`  

Then I installed [bootstrap][2] using `npm install bootstrap` and importing bootstrap `css` and `js` in root layout like 

content of `src/routes/+layout.svelte` 
```
<script>
	import 'bootstrap/dist/css/bootstrap.min.css';
	import 'bootstrap/dist/js/bootstrap.min.js';
	import Header from './Header.svelte';
	import './styles.css';
</script>

<div class="app">
	<Header />

	<main>
		<slot />
	</main>

	<footer>
		<p>visit <a href="https://kit.svelte.dev">kit.svelte.dev</a> to learn SvelteKit</p>
	</footer>
</div>

<style>
</style>
```

Content of `svelte.config.js`
```
import adapter from '@sveltejs/adapter-static';

export default {
	kit: {
		adapter: adapter({
			// default options are shown. On some platforms
			// these options are set automatically — see below
			pages: 'build',
			assets: 'build',
			fallback: null,
			precompress: false,
			strict: true
		})
	}
};
```

`npm run dev` is working fine  

But `npm run build` is givng me error 
```
ReferenceError: document is not defined
    at K (/home/alok/Alok/myapp/node_modules/bootstrap/dist/js/bootstrap.min.js:6:8846)
    at /home/alok/Alok/myapp/node_modules/bootstrap/dist/js/bootstrap.min.js:6:9655
    at /home/alok/Alok/myapp/node_modules/bootstrap/dist/js/bootstrap.min.js:6:84
    at Object.<anonymous> (/home/alok/Alok/myapp/node_modules/bootstrap/dist/js/bootstrap.min.js:6:256)
    at Module._compile (node:internal/modules/cjs/loader:1159:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1213:10)
    at Module.load (node:internal/modules/cjs/loader:1037:32)
    at Module._load (node:internal/modules/cjs/loader:878:12)
    at ModuleWrap.<anonymous> (node:internal/modules/esm/translators:169:29)
    at ModuleJob.run (node:internal/modules/esm/module_job:193:25)

Node.js v18.12.1
[vite-plugin-sveltekit-compile] Failed with code 1
error during build:
Error: Failed with code 1
    at ChildProcess.<anonymous> (file:///home/alok/Alok/myapp/node_modules/@sveltejs/kit/src/utils/fork.js:67:13)
    at ChildProcess.emit (node:events:513:28)
    at ChildProcess._handle.onexit (node:internal/child_process:291:12)
```

Is my way of adding bootstrap wrong?
How can I build this project to generate static site?

  [1]: https://kit.svelte.dev
  [2]: https://getbootstrap.com

### Reproduction

https://github.com/prettylinux/myapp

### System Info

```Shell
System:
    OS: Linux 5.4 Ubuntu 20.04 LTS (Focal Fossa)
    CPU: (4) x64 Intel(R) Core(TM) i3-1005G1 CPU @ 1.20GHz
    Memory: 2.76 GB / 7.47 GB
    Container: Yes
    Shell: 5.0.17 - /bin/bash
  Binaries:
    Node: 18.12.1 - ~/Downloads/node-v18.12.1-linux-x64/bin/node
    Yarn: 1.22.10 - /usr/local/bin/yarn
    npm: 8.19.2 - ~/Downloads/node-v18.12.1-linux-x64/bin/npm
  Browsers:
    Chrome: 108.0.5359.124
    Firefox: 108.0.2
  npmPackages:
    @sveltejs/adapter-auto: ^1.0.0 => 1.0.2 
    @sveltejs/adapter-static: ^1.0.5 => 1.0.5 
    @sveltejs/kit: ^1.0.0 => 1.3.2 
    svelte: ^3.54.0 => 3.55.1 
    vite: ^4.0.0 => 4.0.4
```

### Severity

blocking all usage of SvelteKit

**Comment by Conduitry** [comment]
You need to make sure you're not running code on the server that expects to be run on the browser. `bootstrap/dist/js/bootstrap.min.js` contains code that expects `document` to be defined, which does not exist on the server. See https://kit.svelte.dev/faq#how-do-i-use-a-client-side-only-library-that-depends-on-document-or-window
