### ISSUE TITLE
Trailing slash redirect does not work for prerendered pages

### ISSUE THREAD

**Issue by s3812497** [sveltejs/kit#8839]
### Describe the bug

After building the app, trailing slash redirects do not work, returning a 404 instead.

The `server.respond` trailing slash redirect only works for non-prerendered routes.
This is because it checks the SSR manifest first but prerendered routes were removed from it in https://github.com/sveltejs/kit/pull/7541

### Reproduction

https://stackblitz.com/edit/github-vabxnk-zdpsdn?file=src%2Froutes%2Ftest%2F%2Bpage.svelte,src%2Froutes%2F%2Bpage.svelte

1. Run `pnpm build && pnpm preview`
2. Navigate to `/test/` and refresh the page.

#### Expected
Redirect from `/test/` to `/test`.

#### Actual
404 not found.

### Logs

```Shell
Error: Not found: /test/
    at resolve (file://file:///home/projects/github-vabxnk-zdpsdn/.svelte-kit/output/server/index.js:3232:18)
    at resolve (file://file:///home/projects/github-vabxnk-zdpsdn/.svelte-kit/output/server/index.js:3099:34)
    at #options.hooks.handle (file://file:///home/projects/github-vabxnk-zdpsdn/.svelte-kit/output/server/index.js:3276:59)
    at respond (file://file:///home/projects/github-vabxnk-zdpsdn/.svelte-kit/output/server/index.js:3097:43)
```

### System Info

```Shell
System:
    OS: Linux 5.0 undefined
    CPU: (8) x64 Intel(R) Core(TM) i9-9880H CPU @ 2.30GHz
    Memory: 0 Bytes / 0 Bytes
    Shell: 1.0 - /bin/jsh
  Binaries:
    Node: 16.14.2 - /usr/local/bin/node
    Yarn: 1.22.19 - /usr/local/bin/yarn
    npm: 7.17.0 - /usr/local/bin/npm
  npmPackages:
    @sveltejs/adapter-auto: ^1.0.2 => 1.0.2 
    @sveltejs/kit: ^1.3.8 => 1.3.8 
    svelte: ^3.55.1 => 3.55.1 
    vite: ^4.0.4 => 4.0.4
```

### Severity

serious, but I can work around it

### Additional Information

1. Netlify implements its own trailing slash redirect logic as the adapter has none and we can tell SvelteKit isn't handling it because it omits the `x-sveltekit-normalise` header in the redirect.
https://whimsical-croquembouche-bf1ae0.netlify.app/test/
2. `adapter-cloudflare` should allow sveltekit to handle it instead of the logic I implemented [here](https://github.com/sveltejs/kit/blob/089c405041b0267356281fc8ea5f19ecc331178b/packages/adapter-cloudflare/src/worker.js#L62).
3. `adapter-vercel` is unaffected because it uses static redirects from a vercel config file (`adapter-cloudflare` should do the same to bypass worker runs but that's for another day).
4. `adapter-node` currently never reaches `server.respond` because the handler before it doesn't differentiate between `about.html` and `about/index.html`.
5. Not sure which community adapters are affected by this.

**Comment by matfantinel** [comment]
Funnily, I was not able to reproduce the issue in your Stackblitz link, but I am facing it in one of my projects (in the v4 branch): https://github.com/matfantinel/matfantinel.github.io/tree/v4

In my case I am setting trailingSlash to "always", but I saw the same 404 popping up even if I remove that setting (doesn't go from /page to /page/ nor vice-versa).

It works correctly in dev mode, but not after compiling with adapter-static.

**Comment by Conduitry** [comment]
I can reproduce it with the StackBlitz link. Make sure you're building and running the production version of the app, as listed in the repro steps, and not just running the dev mode one that comes up by default.
