### ISSUE TITLE
got an error after running sveltekit-sync

### ISSUE THREAD

**Issue by Mahaveer2** [sveltejs/kit#8916]
### Describe the bug

TypeError: redirects[builder.config.kit.trailingSlash] is not iterable
00:32:15.474

### Reproduction

error

### Logs

```Shell
> Using @sveltejs/adapter-vercel
error during build:
TypeError: redirects[builder.config.kit.trailingSlash] is not iterable
    at Object.adapt (file:///vercel/path0/node_modules/@sveltejs/adapter-auto/node_modules/@sveltejs/adapter-vercel/index.js:118:17)
    at adapt (file:///vercel/path0/node_modules/@sveltejs/adapter-auto/index.js:20:22)
    at adapt (file:///vercel/path0/node_modules/@sveltejs/kit/src/core/adapt/index.js:28:8)
    at Object.handler (file:///vercel/path0/node_modules/@sveltejs/kit/src/exports/vite/index.js:694:12)
    at async PluginDriver.hookParallel (file:///vercel/path0/node_modules/rollup/dist/es/shared/rollup.js:23688:17)
    at async Object.close (file:///vercel/path0/node_modules/rollup/dist/es/shared/rollup.js:24979:13)
    at async Promise.all (index 0)
    at async build (file:///vercel/path0/node_modules/vite/dist/node/chunks/dep-5e7f419b.js:44352:13)
    at async CAC.<anonymous> (file:///vercel/path0/node_modules/vite/dist/node/cli.js:808:9)
Error: Command "npm run build" exited with 1
```

### System Info

```Shell
Mac 13pro intel, browser chrome
```

### Severity

blocking all usage of SvelteKit

### Additional Information

it works on netlify but not on vercel , it worked previoulsly but not now

**Comment by Rich-Harris** [comment]
'error' is not a reproduction, and 'Mac 13pro intel, browser chrome' is not the output of ` npx envinfo --system --binaries --browsers --npmPackages "{svelte,@sveltejs/*,vite}"`.

**Comment by dummdidumm** [comment]
This sounds like you're using an old version `@sveltejs/adapter-vercel` together with a newer version of `@sveltejs/kit`. I suggest you bump these dependencies from `next` to `^1.0.0`. Check out the [migration guide](https://github.com/sveltejs/kit/discussions/5774) depending on how far behind you are on your project.

Closing as this is not an issue related to SvelteKit. You can open a Q&A entry in the discussions board or on Discord with more details if you need further help.

**Comment by adam21xc** [comment]
I can confirm I had the same exact issue & had to update both packages in order to get the Vercel build to work.
