### ISSUE TITLE
base path + adapter-static 2.0.0 fails to build (error w/ favicon)

### ISSUE THREAD

**Issue by KTibow** [sveltejs/kit#8919]
### Describe the bug

with adapter-static 2.0.0 and a base path, the build errors and fails

### Reproduction

https://github.com/KTibow/svelte-adapter-static-bug
error occurs on `npm run build`
things changed in order to cause the error
- install adapter-static
- enable prerendering
- set a base path

### Logs

```Shell
file:///tmp/sv-test/node_modules/@sveltejs/kit/src/core/postbuild/prerender.js:53
                                        throw new Error(format(details));
                                              ^

Error: 404 /favicon.png does not begin with `base`, which is configured in `paths.base` and can be imported from `$app/paths` - see https://kit.svelte.dev/docs/configuration#paths for more info (linked from /base-path)
    at file:///tmp/sv-test/node_modules/@sveltejs/kit/src/core/postbuild/prerender.js:53:12
    at visit (file:///tmp/sv-test/node_modules/@sveltejs/kit/src/core/postbuild/prerender.js:178:4)
    at Object.fn (file:///tmp/sv-test/node_modules/@sveltejs/kit/src/core/postbuild/prerender.js:168:22)
    at dequeue (file:///tmp/sv-test/node_modules/@sveltejs/kit/src/core/postbuild/queue.js:40:42)
    at file:///tmp/sv-test/node_modules/@sveltejs/kit/src/core/postbuild/queue.js:49:7

Node.js v19.1.0
[vite-plugin-sveltekit-compile] Failed with code 1
error during build:
Error: Failed with code 1
    at ChildProcess.<anonymous> (file:///tmp/sv-test/node_modules/@sveltejs/kit/src/utils/fork.js:68:13)
    at ChildProcess.emit (node:events:513:28)
    at ChildProcess._handle.onexit (node:internal/child_process:293:12)
```

### System Info

```Shell
(this issue happens on another machine so this info is irrelevant but anyway)

  System:
    OS: Linux 6.1 Fedora Linux 37 (Workstation Edition)
    CPU: (8) x64 Intel(R) Core(TM) i5-1035G4 CPU @ 1.10GHz
    Memory: 4.09 GB / 15.22 GB
    Container: Yes
    Shell: 3.5.1 - /usr/bin/fish
  Binaries:
    Node: 19.1.0 - /usr/local/bin/node
    npm: 8.19.3 - /usr/local/bin/npm
  Browsers:
    Firefox: 109.0
  npmPackages:
    @sveltejs/adapter-auto: ^2.0.0 => 2.0.0 
    @sveltejs/adapter-static: ^2.0.0 => 2.0.0 
    @sveltejs/kit: ^1.5.0 => 1.5.0 
    svelte: ^3.54.0 => 3.55.1 
    vite: ^4.0.0 => 4.1.1
```

### Severity

blocking an upgrade

**Comment by jdkula** [comment]
I'm encountering this same issue with a fresh installation of SvelteKit from create-svelte– as soon as I set a base path the build fails. Furthermore, if I remove the favicon line from `app.html`, the build will continue to error with any imported assets (e.g. `.png`s) in the actual app code.

It looks like it's erasing the last path segment (if I set the base path to `/x/y`, then it will complain how `/x/favicon.ico` does not start with the base path).

**Comment by KTibow** [comment]
doing some more research on this is giving some inconsistent results, it might only happen with a combination of packages, i'll update soon

**Comment by jdkula** [comment]
Did a bit more digging, it looks like adding `export const trailingSlash = 'always';` to `routes/+layout.ts` fixes it.

It seems that the core of the issue is, when `trailingSlash = 'never';`, when prerendering `/$base/` (our root), we'll get redirected to `'/$base'`, [`prerender.js:305`](https://github.com/sveltejs/kit/blob/master/packages/kit/src/core/postbuild/prerender.js#L305) (which is invalid, it's before the root). Then, we'll visit `/$base`, which will return our actual HTML. This is a problem though, because all relative links we crawl will be resolved relative to `/$base`, so when we call `resolve` at [`prerender.js:250`](https://github.com/sveltejs/kit/blob/master/packages/kit/src/core/postbuild/prerender.js#L250) we'll end up with a call like `resolve('/$base', './favicon.ico')`, which will ofc resolve to `/favicon.ico` (and not `/$base/favicon.ico`, which is what we want).

**Comment by DougAnderson444** [comment]
```
// layout.js/.ts
export const prerender = true;
export const trailingSlash = 'always';
```

^ Fixes this error message for me too.  

Suggest adding this to the **error message suggestions** for a failed build, much like how it suggests when `prerender` fails to add `prerender = true` or `fallback`, etc.
