### ISSUE TITLE
Throwing a custom error using error() causes a DevalueError: Cannot stringify arbitrary non-POJOs error

### ISSUE THREAD

**Issue by awmcclain** [sveltejs/kit#8934]
### Describe the bug

If I modify the type of `App.Error` to have a custom field, then annotate it with a custom field and rethrow it using `error`, I get a `DevalueError: Cannot stringify arbitrary non-POJOs`. I've repro'd this in a minimal repo using the latest starter project.

```
import { error } from "@sveltejs/kit";

/** @type {import('./$types').PageLoad} */
export async function load() {
  try {
    throw new Error("this is a test error");
  } catch (err) {
    let e = err as App.Error;
    e.userMessage = 'this is a user message';
    throw error(500, e);
  }
}
```

### Reproduction

https://github.com/getsesh/sveltekit-error-repro

### Logs

```Shell
DevalueError: Cannot stringify arbitrary non-POJOs
    at walk (file:///Users/andrew/workspace/error-test-app/node_modules/devalue/src/uneval.js:74:13)
    at Proxy.uneval (file:///Users/andrew/workspace/error-test-app/node_modules/devalue/src/uneval.js:96:2)
    at Module.render_response (/node_modules/@sveltejs/kit/src/runtime/server/page/render.js:217:30)
    at async Module.render_page (/node_modules/@sveltejs/kit/src/runtime/server/page/index.js:262:15)
    at async resolve (/node_modules/@sveltejs/kit/src/runtime/server/respond.js:363:17)
    at async Module.respond (/node_modules/@sveltejs/kit/src/runtime/server/respond.js:234:20)
    at async file:///Users/andrew/workspace/error-test-app/node_modules/@sveltejs/kit/src/exports/vite/dev/index.js:495:22
```
```


### System Info

```Shell
System:
    OS: macOS 10.15.7
    CPU: (8) x64 Intel(R) Core(TM) i5-1038NG7 CPU @ 2.00GHz
    Memory: 276.66 MB / 16.00 GB
    Shell: 5.7.1 - /bin/zsh
  Binaries:
    Node: 19.6.0 - /usr/local/bin/node
    npm: 9.4.0 - /usr/local/bin/npm
  Browsers:
    Chrome: 109.0.5414.119
    Safari: 15.6.1
```

### Severity

blocking an upgrade

**Comment by dummdidumm** [comment]
This works as expected. `error` is for expected errors, and it should be passed a POJO which is serializable. In your case, `error` is passed an `Error` object.
