### ISSUE TITLE
ERROR  realworld.svelte.dev@1.0.1-next.0 build: `svelte-kit build`

### ISSUE THREAD

**Issue by lgs** [sveltejs/kit#895]
**Describe the bug**
`pnpm -r build ` in the root of  **kit**  repo fails.
Then **examples/realworld.svelte.dev** sign up fails with 404 http error in the browser: `Not found: /register` :
```

404
Not found: /register

Error: Not found: /register
    at Renderer._get_navigation_result (http://localhost:3000/.svelte/dev/runtime/internal/start.js:560:11)
    at async Renderer.update (http://localhost:3000/.svelte/dev/runtime/internal/start.js:457:29)
    at async Router._navigate (http://localhost:3000/.svelte/dev/runtime/internal/start.js:248:3)
```

**Logs**
```
...
│ import pkg from 'cookie';
│ const {parse: parse$1} = pkg;
│ file:///home/lsoave/SVELTE/kit/examples/realworld.svelte.dev/.svelte/output/server/app.js:8
│ import {parse as parse$1} from "cookie";
│         ^^^^^
│ SyntaxError: The requested module 'cookie' is expected to be of type CommonJS, which does not support named exports. CommonJS modules can 
│ For example:
│ import pkg from 'cookie';
│ const {parse: parse$1} = pkg;
│     at ModuleJob._instantiate (internal/modules/esm/module_job.js:97:21)
│     at async ModuleJob.run (internal/modules/esm/module_job.js:143:20)
│     at async Loader.import (internal/modules/esm/loader.js:182:24)
│     at async prerender (file:///home/lsoave/SVELTE/kit/packages/kit/dist/chunks/index6.js:513:14)
│     at async AdapterUtils.prerender (file:///home/lsoave/SVELTE/kit/packages/kit/dist/chunks/index6.js:745:4)
│     at async adapt (/home/lsoave/SVELTE/kit/packages/adapter-node/index.cjs:26:4)
│     at async adapt (file:///home/lsoave/SVELTE/kit/packages/kit/dist/chunks/index6.js:767:2)
│     at async file:///home/lsoave/SVELTE/kit/packages/kit/dist/cli.js:633:5
└─ Failed in 12.4s
...
/home/lsoave/SVELTE/kit/examples/realworld.svelte.dev:
 ERROR  realworld.svelte.dev@1.0.1-next.0 build: `svelte-kit build`
Exit status 1
...
```
**To Reproduce**

my shell command history here:

```
 1959  git clone https://github.com/sveltejs/kit.git
 1960  cd kit
 1961  pnpm i
 1962  pnpm -r build
 1963  cd examples/realworld.svelte.dev/
 1967  pnpm dev
```

**Expected behavior**

**Stacktraces**

**Information about your SvelteKit Installation:**

In the root of the repo:

lsoave@basenode:~/SVELTE/kit$ cat package.json 
```
{
	"name": "kit",
	"version": "0.0.1",
	"description": "",
	"main": "index.js",
	"scripts": {
		"build": "pnpm build --filter=\"@sveltejs/*\" --filter=\"create-svelte\"",
		"test": "pnpm -r test --workspace-concurrency=1",
		"check": "pnpm -r check",
		"lint": "pnpm -r lint",
		"format": "pnpm -r format",
		"release": "pnpm publish --tag=next --filter=\"@sveltejs/*\" --filter=\"create-svelte\""
	},
	"repository": {
		"type": "git",
		"url": "git+https://github.com/sveltejs/kit.git"
	},
	"author": "",
	"license": "MIT",
	"bugs": {
		"url": "https://github.com/sveltejs/kit/issues"
	},
	"homepage": "https://github.com/sveltejs/kit#readme",
	"devDependencies": {
		"@changesets/cli": "^2.15.0",
		"@rollup/plugin-commonjs": "^17.1.0",
		"@rollup/plugin-json": "^4.1.0",
		"@rollup/plugin-node-resolve": "^11.2.1",
		"@sveltejs/eslint-config": "github:sveltejs/eslint-config#v5.6.0",
		"@typescript-eslint/eslint-plugin": "^4.21.0",
		"@typescript-eslint/parser": "^4.21.0",
		"eslint": "^7.23.0",
		"eslint-plugin-import": "^2.22.1",
		"eslint-plugin-svelte3": "^3.1.2",
		"playwright-chromium": "^1.10.0",
		"prettier": "2.2.1",
		"rollup": "^2.44.0",
		"typescript": "^4.2.3"
	},
	"type": "module"
}
```
Adapter 
```
@sveltejs/adapter-node
```

In the exaple app:
```
lsoave@basenode:~/SVELTE/kit/examples/realworld.svelte.dev$ cat package.json 
{
	"name": "realworld.svelte.dev",
	"version": "1.0.1-next.0",
	"private": true,
	"type": "module",
	"scripts": {
		"dev": "svelte-kit dev",
		"build": "svelte-kit build",
		"start": "svelte-kit start"
	},
	"devDependencies": {
		"@sveltejs/adapter-node": "workspace:*",
		"@sveltejs/kit": "workspace:*",
		"marked": "^2.0.1",
		"svelte": "^3.37.0"
	},
	"dependencies": {
		"cookie": "^0.4.1",
		"node-fetch": "^2.6.1"
	}
}
```

**Severity**
Medium 

**Additional context**

**Comment by benjaminviaud** [comment]
If load returns nothing, SvelteKit will  to other routes until something responds, or will respond with a generic 404.
https://kit.svelte.dev/docs#loading
