### ISSUE TITLE
Rerouting with `goto()` in browser during load crashes application

### ISSUE THREAD

**Issue by MathiasWP** [sveltejs/kit#9026]
### Describe the bug

The `page` store is not updated when rerouting with `goto()` on in load on the browser.

This bug was originally found because of this error-message caused in our application when using goto() in the browser during load:

<img width="1029" alt="Screenshot 2023-02-13 at 12 36 47" src="https://user-images.githubusercontent.com/48158184/218447839-1bfd61cc-9595-4cda-baf2-5f5b7d39a88e.png">

I've created a minimal repro where you can see that the `page` store does not update even though the url has changed.

### Reproduction

[https://github.com/MathiasWP/sveltekit-load-client-reroute-bug](https://github.com/MathiasWP/sveltekit-load-client-reroute-bug)

### Logs

```Shell
Uncaught (in promise) TypeError: Cannot read properties of null (reading 'insertBefore')
    at insert_hydration (index.mjs:372:16)
    at insert_hydration_dev (index.mjs:2146:5)
    at mount (OverviewEdit.svelte? [sm]:71:1)
    at targetCmp.$$.fragment.m (svelte-hooks.js?v=6c82aa17:291:24)
    at mount_component (index.mjs:1949:26)
    at Object.mount [as m] (http://localhost:5173/src/routes/(v2-routes)/project/[project]/[phase]/overview/edit/+page.svelte?t=1676287060043:51:4)
    at Object.update [as p] (http://localhost:5173/src/routes/(v2-routes)/project/[project]/[phase]/overview/edit/+page.svelte?t=1676287060043:117:15)
    at update (index.mjs:1209:36)
    at flush (index.mjs:1169:17)
```

### System Info

```Shell
System:
    OS: macOS 13.1
    CPU: (8) arm64 Apple M1 Pro
    Memory: 58.00 MB / 16.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 18.9.0 - /usr/local/bin/node
    npm: 9.1.1 - /usr/local/bin/npm
  Browsers:
    Brave Browser: 109.1.47.186
    Chrome: 109.0.5414.119
    Firefox: 107.0.1
    Safari: 16.2
  npmPackages:
    @sveltejs/adapter-auto: ^2.0.0 => 2.0.0 
    @sveltejs/kit: ^1.5.0 => 1.5.6 
    svelte: ^3.54.0 => 3.55.1 
    vite: ^4.0.0 => 4.1.1
```

### Severity

serious, but I can work around it

**Comment by Conduitry** [comment]
You should probably be throwing a `redirect` in `load`, not calling `goto`.
