### ISSUE TITLE
After creating and runing project i get a error

### ISSUE THREAD

**Issue by Gorbulev-Sergey** [sveltejs/kit#9047]
### Describe the bug

Error: Missing "./paths" specifier in "@sveltejs/kit" package
    at e (file:///C:/Users/Gorbulev/Desktop/svelteAuthPhone/node_modules/vite/dist/node/chunks/dep-3007b26d.js:14845:25)
    at n (file:///C:/Users/Gorbulev/Desktop/svelteAuthPhone/node_modules/vite/dist/node/chunks/dep-3007b26d.js:14845:627)
    at o (file:///C:/Users/Gorbulev/Desktop/svelteAuthPhone/node_modules/vite/dist/node/chunks/dep-3007b26d.js:14845:1276)
    at resolveExports (file:///C:/Users/Gorbulev/Desktop/svelteAuthPhone/node_modules/vite/dist/node/chunks/dep-3007b26d.js:22032:20)
    at resolveDeepImport (file:///C:/Users/Gorbulev/Desktop/svelteAuthPhone/node_modules/vite/dist/node/chunks/dep-3007b26d.js:22051:31)
    at tryNodeResolve (file:///C:/Users/Gorbulev/Desktop/svelteAuthPhone/node_modules/vite/dist/node/chunks/dep-3007b26d.js:21736:20)
    at Context.resolveId (file:///C:/Users/Gorbulev/Desktop/svelteAuthPhone/node_modules/vite/dist/node/chunks/dep-3007b26d.js:21487:28)
    at Object.resolveId (file:///C:/Users/Gorbulev/Desktop/svelteAuthPhone/node_modules/vite/dist/node/chunks/dep-3007b26d.js:41587:46)
    at async TransformContext.resolve (file:///C:/Users/Gorbulev/Desktop/svelteAuthPhone/node_modules/vite/dist/node/chunks/dep-3007b26d.js:41334:23)
    at async normalizeUrl (file:///C:/Users/Gorbulev/Desktop/svelteAuthPhone/node_modules/vite/dist/node/chunks/dep-3007b26d.js:39685:34)

### Reproduction

 1

### Logs

```Shell
PS C:\Users\Gorbulev\Desktop\svelteAuthPhone> npm create svelte@latest
npm WARN config global `--global`, `--local` are deprecated. Use `--location=global` instead.

create-svelte version 2.3.4

Welcome to SvelteKit!

√ Where should we create your project?
  (leave blank to use current directory) ... 
√ Which Svelte app template? » Skeleton project
√ Add type checking with TypeScript? » Yes, using JavaScript with JSDoc comments
√ Add ESLint for code linting? ... No / Yes
√ Add Prettier for code formatting? ... No / Yes
√ Add Playwright for browser testing? ... No / Yes
√ Add Vitest for unit testing? ... No / Yes

Your project is ready!
✔ Type-checked JavaScript
  https://www.typescriptlang.org/tsconfig#checkJs
✔ Prettier
  https://prettier.io/docs/en/options.html
  https://github.com/sveltejs/prettier-plugin-svelte#options

Install community-maintained integrations:
  https://github.com/svelte-add/svelte-adders

Next steps:
  1: npm install (or pnpm install, etc)
  2: git init && git add -A && git commit -m "Initial commit" (optional)
  3: npm run dev -- --open

To close the dev server, hit Ctrl-C

Stuck? Visit us at https://svelte.dev/chat
PS C:\Users\Gorbulev\Desktop\svelteAuthPhone> npm i                   
npm WARN config global `--global`, `--local` are deprecated. Use `--location=global` instead.

added 105 packages, and audited 106 packages in 8s

13 packages are looking for funding
  run `npm fund` for details

found 0 vulnerabilities
PS C:\Users\Gorbulev\Desktop\svelteAuthPhone> npm run dev -- --open   
npm WARN config global `--global`, `--local` are deprecated. Use `--location=global` instead.

> svelteauthphone@0.0.1 dev
> vite dev "--open"


Forced re-optimization of dependencies

  VITE v4.1.1  ready in 1046 ms

  ➜  Local:   http://127.0.0.1:5173/
  ➜  Network: use --host to expose
  ➜  press h to show help
Missing "./paths" specifier in "@sveltejs/kit" package
Missing "./paths" specifier in "@sveltejs/kit" package (x2)
Missing "./paths" specifier in "@sveltejs/kit" package (x3)
Missing "./paths" specifier in "@sveltejs/kit" package (x4)
```

### System Info

```Shell
1
```

### Severity

blocking all usage of SvelteKit

**Comment by jstilwell** [comment]
Running into the same issue when I create a new project.

**Comment by VitroidFPV** [comment]
Same here, it happens in an already existing project after updating

**Comment by raythurnevoid** [comment]
Downgrading to `"@sveltejs/kit": "1.5.6"` fixes the issue, it was introduced in 1.5.7.

**Comment by abovethewater** [comment]
Starting a new project after a few months away from SvelteKit, and run into this when creating a new project.

Quickest workaround for now is to drop back a version (1.5.7 seems to be the one installed as of right now):

```
"devDependencies": {
    "@sveltejs/kit": "1.5.6",
```

**Comment by benmccann** [comment]
This should be fixed in `@sveltejs/kit@1.6.0`

**Comment by AlaaElrifaie** [comment]
Same issue with a newly created project using `npm create svelte@latest`.
Downgrading @sveltejs/kit to v1.5.6 fixed it.

**Comment by benmccann** [comment]
We've had multiple people confirm it's working now. Please check that you're running 1.6.0 with `npx envinfo --npmPackages "@sveltejs/kit"` or `head node_modules/@sveltejs/kit/package.json`. If it's still not working, please clarify steps to reproduce. E.g. is it `dev`, `build`, or both?
