### ISSUE TITLE
Sveltekit not loading images in npm run preview

### ISSUE THREAD

**Issue by ethanfox** [sveltejs/kit#9079]
### Describe the bug

SvelteKit doesn't load images in npm run preview but does show them in npm run dev. 

### Reproduction

IDK

### Logs

```Shell
Error: Not found: /eclipse-loader.svg
    at resolve (file:///Users/ethanfox/Code/material-space/.svelte-kit/output/server/index.js:2472:18)
    at resolve (file:///Users/ethanfox/Code/material-space/.svelte-kit/output/server/index.js:2339:34)
    at Object.#options.hooks.handle (file:///Users/ethanfox/Code/material-space/.svelte-kit/output/server/index.js:2516:59)
    at respond (file:///Users/ethanfox/Code/material-space/.svelte-kit/output/server/index.js:2337:43)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
```

### System Info

```Shell
System:
    OS: macOS 13.1
    CPU: (10) arm64 Apple M1 Pro
    Memory: 92.95 MB / 16.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 16.17.0 - /usr/local/bin/node
    npm: 8.15.0 - /usr/local/bin/npm
  Browsers:
    Chrome: 110.0.5481.100
    Safari: 16.2
  npmPackages:
    @sveltejs/adapter-auto: ^2.0.0 => 2.0.0 
    @sveltejs/kit: ^1.5.0 => 1.7.1 
    svelte: ^3.54.0 => 3.55.1 
    vite: ^4.0.0 => 4.1.1
```

### Severity

annoyance

### Additional Information

	<div class="loader">
		<img src="/src/static/img/assets/eclipse-loader.svg" />
	</div>

**Comment by Conduitry** [comment]
The contents of `src` are only served in development, which happens so that you can run an unbundled version of the site.

Also, shockingly, "IDK" is not a valid reproduction.
