### ISSUE TITLE
npm create svelte app: Error [ERR_UNKNOWN_BUILTIN_MODULE]: No such built-in module: node:stream/web

### ISSUE THREAD

**Issue by jornfranke** [sveltejs/kit#9110]
### Describe the bug

I follow the instructions on https://kit.svelte.dev/docs/creating-a-project
No matter which combination I choose (with Typescript, without etc.) - everytime I run 
```
npm install
npm run dev
```
It shows the following error message
```
▲ [WARNING] Cannot find base config file "./.svelte-kit/tsconfig.json" [tsconfig.json]

    tsconfig.json:2:12:
      2 │   "extends": "./.svelte-kit/tsconfig.json",
        ╵              ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

failed to load config from /home/user/sveltedemo/vite.config.ts
error when starting dev server:
Error [ERR_UNKNOWN_BUILTIN_MODULE]: No such built-in module: node:stream/web
    at new NodeError (internal/errors.js:322:7)
    at Loader.builtinStrategy (internal/modules/esm/translators.js:285:11)
    at new ModuleJob (internal/modules/esm/module_job.js:63:26)
    at Loader.getModuleJob (internal/modules/esm/loader.js:258:11)
    at async ModuleWrap.<anonymous> (internal/modules/esm/module_job.js:78:21)
    at async Promise.all (index 0)
    at async link (internal/modules/esm/module_job.js:83:9)
```

This is for Typescript and Javascript.

### Reproduction

npm create svelte@latest my-app
cd my-app
npm install
npm run dev

### System Info

```Shell
Node versions

Node: v18.13.0
NPM: 8.19.3
```
```


### Severity

blocking all usage of SvelteKit

### Additional Information

_No response_

**Comment by Conduitry** [comment]
Are you sure that's the version of Node you're using? Are you using a non-standard build of Node? If you're using the standard build of v18.13.0, I have no idea why this would be happening. If you run the Node REPL and try to evaluate `require('node:stream/web')`, what happens?

**Comment by jornfranke** [comment]
```
Welcome to Node.js v18.13.0.
Type ".help" for more information.
>  require('node:stream/web')
{
  ReadableStream: [class ReadableStream],
  ReadableStreamDefaultReader: [class ReadableStreamDefaultReader],
  ReadableStreamBYOBReader: [class ReadableStreamBYOBReader],
  ReadableStreamBYOBRequest: [class ReadableStreamBYOBRequest],
  ReadableByteStreamController: [class ReadableByteStreamController],
  ReadableStreamDefaultController: [class ReadableStreamDefaultController],
  TransformStream: [class TransformStream],
  TransformStreamDefaultController: [class TransformStreamDefaultController],
  WritableStream: [class WritableStream],
  WritableStreamDefaultWriter: [class WritableStreamDefaultWriter],
  WritableStreamDefaultController: [class WritableStreamDefaultController],
  ByteLengthQueuingStrategy: [class ByteLengthQueuingStrategy],
  CountQueuingStrategy: [class CountQueuingStrategy],
  TextEncoderStream: [class TextEncoderStream],
  TextDecoderStream: [class TextDecoderStream],
  CompressionStream: [class CompressionStream],
  DecompressionStream: [class DecompressionStream]
}
```
However, it could be that there are multiple node versions in the PATH. I will investigate

**Comment by jornfranke** [comment]
Ok, I confirm. There were multiple node versions in the path (amongst others node.js 14). After removing the other node versions from the path and keeping only one 18.x it disappears.
