### ISSUE TITLE
Error during build

### ISSUE THREAD

**Issue by mishrasatyam** [sveltejs/kit#913]
**Describe the bug**
Error during build 

**Logs**
```
[vite]: Rollup failed to resolve import "@sveltejs/kit/ssr" from ".svelte/build/app.js".
This is most likely unintended because it can break your application at runtime.
If you do want to externalize this module explicitly add it to
`build.rollupOptions.external`
> [vite]: Rollup failed to resolve import "@sveltejs/kit/ssr" from ".svelte/build/app.js".
This is most likely unintended because it can break your application at runtime.
If you do want to externalize this module explicitly add it to
`build.rollupOptions.external`
Error: [vite]: Rollup failed to resolve import "@sveltejs/kit/ssr" from ".svelte/build/app.js".
This is most likely unintended because it can break your application at runtime.
If you do want to externalize this module explicitly add it to
`build.rollupOptions.external`
    at onRollupWarning (/home/satyam/hj/node_modules/.pnpm/vite@2.1.5/node_modules/vite/dist/node/chunks/dep-66eb515d.js:44389:19)
    at Object.onwarn (/home/satyam/hj/node_modules/.pnpm/vite@2.1.5/node_modules/vite/dist/node/chunks/dep-66eb515d.js:44239:17)
    at Object.onwarn (/home/satyam/hj/node_modules/.pnpm/rollup@2.44.0/node_modules/rollup/dist/shared/rollup.js:19784:20)
    at ModuleLoader.handleResolveId (/home/satyam/hj/node_modules/.pnpm/rollup@2.44.0/node_modules/rollup/dist/shared/rollup.js:18526:26)
    at /home/satyam/hj/node_modules/.pnpm/rollup@2.44.0/node_modules/rollup/dist/shared/rollup.js:18480:22
    at async Promise.all (index 0)
    at async ModuleLoader.fetchStaticDependencies (/home/satyam/hj/node_modules/.pnpm/rollup@2.44.0/node_modules/rollup/dist/shared/rollup.js:18478:34)
    at async Promise.all (index 0)
    at async ModuleLoader.fetchModule (/home/satyam/hj/node_modules/.pnpm/rollup@2.44.0/node_modules/rollup/dist/shared/rollup.js:18454:9)
    at async Promise.all (index 0)
 ERROR  Command failed with exit code 1.
```

**To Reproduce**
Create new svelte kit project, below were dependency versions:
@sveltejs/adapter-node 1.0.0-next.12
 @sveltejs/kit 1.0.0-next.71
svelte 3.37.0
vite 2.1.5

**Severity**
Unable to build project

**Comment by GrygrFlzr** [comment]
Are you using pnpm 6.0.0? If so, this is a duplicate of #902 and you should update to 6.0.1 or higher. If not, please specify what package manager you were using?

**Comment by mishrasatyam** [comment]
> Are you using pnpm 6.0.0? If so, this is a duplicate of #902 and you should update to 6.0.1 or higher. If not, please specify what package manager you were using?

I updated pnpm to 6.0.1 , deleted node_modules folder and reinstalled packages and it works fine now. Thanks!!

**Comment by AlexRMU** [comment]
I have an image in "./public/images/1.png"
if `import image from "/public/images/1.png";` then in dev
```
files in the public directory are served at the root path.
Instead of /public/images/1.png, use /images/1.png.
```
if `import image from "/images/1.png";` everything is fine in dev but in build
```
[vite]: Rollup failed to resolve import "/images/1.png" from "src/routes/index.svelte".
This is most likely unintended because it can break your application at runtime. If you do want to externalize this module explicitly add it to `build.rollupOptions.external`
```

setup:
```
{
    kit: {
        files: {
            assets: "./public",
        },
        vite: {
            server: {
                fs: {
                    allow: ["./public"]
                }
            },
        },
    },
};
"@sveltejs/adapter-node": "^1.0.0-next.73",
"@sveltejs/kit": "^1.0.0-next.314",
"vite": "^2.9.5",
"vite-plugin-iso-import": "^0.1.3",
"vite-tsconfig-paths": "^3.4.1"
"rollup": "^2.70.2",
```

**Comment by AlexRMU** [comment]
Part of the problem can be solved like this:
`import image from "/static/images/1.png";`
`assets: "./static",`
The file in dev will be available in `/static/images/1.png` and `/images/1.png`, which is strange, and everything is fine in build.
