### ISSUE TITLE
Error: Not found: /favicon.ico when using emoji as favicon

### ISSUE THREAD

**Issue by multivac61** [sveltejs/kit#9289]
### Describe the bug

I get the following error when previewing a production build locally with `prerender = true` set.

```
Error: Not found: /favicon.ico
    at resolve (file:///Users/olafur/dev/hvaderibio/.svelte-kit/output/server/index.js:3187:18)
    at resolve (file:///Users/olafur/dev/hvaderibio/.svelte-kit/output/server/index.js:3054:34)
    at #options.hooks.handle (file:///Users/olafur/dev/hvaderibio/.svelte-kit/output/server/index.js:3231:59)
    at respond (file:///Users/olafur/dev/hvaderibio/.svelte-kit/output/server/index.js:3052:43)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
```

However there is no favicon.ico in my project as this is the code I use instead

```
		<link
			rel="icon"
			href="data:image/svg+xml,<svg xmlns=%22http://www.w3.org/2000/svg%22 viewBox=%220 0 100 100%22><text y=%22.9em%22 font-size=%2290%22>🎞️</text></svg>"
		/>
```

### Reproduction

https://github.com/multivac61/hvaderibio

### Logs

```Shell
pnpm build && pnpm run preview

> hvaderibio@0.0.1 build /Users/olafur/dev/hvaderibio
> vite build


vite v4.1.2 building SSR bundle for production...
✓ 59 modules transformed.
2:39:11 PM [vite-plugin-svelte] ssr compile done.
package   	files	  time	   avg
hvaderibio	    4	41.4ms	10.3ms

vite v4.1.2 building for production...
✓ 44 modules transformed.
2:39:12 PM [vite-plugin-svelte] dom compile done.
package   	files	  time	   avg
hvaderibio	    4	81.8ms	20.5ms
.svelte-kit/output/client/_app/version.json                                            0.03 kB
.svelte-kit/output/client/vite-manifest.json                                           3.32 kB
.svelte-kit/output/client/_app/immutable/assets/_layout-cb0259b3.css                  73.18 kB │ gzip: 10.09 kB
.svelte-kit/output/client/_app/immutable/chunks/1-b8026635.js                          0.09 kB │ gzip:  0.10 kB
.svelte-kit/output/client/_app/immutable/modules/pages/_page.ts-63299924.js            0.09 kB │ gzip:  0.10 kB
.svelte-kit/output/client/_app/immutable/chunks/0-0318290b.js                          0.10 kB │ gzip:  0.10 kB
.svelte-kit/output/client/_app/immutable/chunks/2-578bcf85.js                          0.15 kB │ gzip:  0.13 kB
.svelte-kit/output/client/_app/immutable/chunks/control-e7f5239e.js                    0.26 kB │ gzip:  0.18 kB
.svelte-kit/output/client/_app/immutable/components/pages/_layout.svelte-e014857f.js   0.55 kB │ gzip:  0.36 kB
.svelte-kit/output/client/_app/immutable/components/error.svelte-0c2d9b7a.js           0.98 kB │ gzip:  0.57 kB
.svelte-kit/output/client/_app/immutable/chunks/singletons-21706245.js                 2.56 kB │ gzip:  1.34 kB
.svelte-kit/output/client/_app/immutable/chunks/index-0d79d76e.js                      7.50 kB │ gzip:  3.04 kB
.svelte-kit/output/client/_app/immutable/components/pages/_page.svelte-f2380c35.js    13.53 kB │ gzip:  5.43 kB
.svelte-kit/output/client/_app/immutable/start-81eb9fa6.js                            28.17 kB │ gzip: 10.95 kB
.svelte-kit/output/client/_app/immutable/chunks/_page-d7ce62e5.js                     49.00 kB │ gzip: 12.32 kB
.svelte-kit/output/server/vite-manifest.json                           1.93 kB
.svelte-kit/output/server/_app/immutable/assets/_layout-e9663fe1.css  73.44 kB
.svelte-kit/output/server/internal.js                                  0.19 kB
.svelte-kit/output/server/entries/pages/_layout.svelte.js              0.26 kB
.svelte-kit/output/server/entries/fallbacks/error.svelte.js            0.83 kB
.svelte-kit/output/server/entries/pages/_page.ts.js                    1.18 kB
.svelte-kit/output/server/chunks/index.js                              1.95 kB
.svelte-kit/output/server/chunks/index2.js                             3.68 kB
.svelte-kit/output/server/entries/pages/_page.svelte.js                5.32 kB
.svelte-kit/output/server/chunks/internal.js                           5.33 kB
.svelte-kit/output/server/index.js                                    99.36 kB

Run npm run preview to preview your production build locally.

> Using @sveltejs/adapter-auto
  Could not detect a supported production environment. See https://kit.svelte.dev/docs/adapters to learn how to configure your app to run on the platform of your choosing
  ✔ done

> hvaderibio@0.0.1 preview /Users/olafur/dev/hvaderibio
> vite preview


  ➜  Local:   http://localhost:4173/
  ➜  Network: use --host to expose
Error: Not found: /favicon.ico
    at resolve (file:///Users/olafur/dev/hvaderibio/.svelte-kit/output/server/index.js:3187:18)
    at resolve (file:///Users/olafur/dev/hvaderibio/.svelte-kit/output/server/index.js:3054:34)
    at #options.hooks.handle (file:///Users/olafur/dev/hvaderibio/.svelte-kit/output/server/index.js:3231:59)
    at respond (file:///Users/olafur/dev/hvaderibio/.svelte-kit/output/server/index.js:3052:43)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
^C ELIFECYCLE  Command failed.
```
```


### System Info

```Shell
npx envinfo --system --binaries --browsers --npmPackages "{svelte,@sveltejs/*,vite}"
Need to install the following packages:
  envinfo@7.8.1
Ok to proceed? (y) y

  System:
    OS: macOS 13.2.1
    CPU: (10) arm64 Apple M1 Pro
    Memory: 143.03 MB / 32.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 19.3.0 - ~/.nvm/versions/node/v19.3.0/bin/node
    Yarn: 1.22.19 - /opt/homebrew/bin/yarn
    npm: 9.2.0 - ~/.nvm/versions/node/v19.3.0/bin/npm
  Browsers:
    Chrome: 110.0.5481.100
    Edge: 110.0.1587.57
    Firefox: 110.0
    Safari: 16.3
  npmPackages:
    @sveltejs/adapter-auto: ^2.0.0 => 2.0.0
    @sveltejs/kit: ^1.7.2 => 1.7.2
    svelte: ^3.55.1 => 3.55.1
    vite: ^4.1.2 => 4.1.2
```

### Severity

annoyance

**Comment by Rich-Harris** [comment]
I can't reproduce this. Are you certain that you don't have a tab open to localhost:4173 that's showing a different app (or an older version of the same app) that doesn't include the `<link rel="icon">`?

**Comment by multivac61** [comment]
Oh man, you are right. I was messing around with several apps and must've gotten sidetracked 😅

I'm a C++ developer having a blast learning SvelteKit and by proxy web standards! At the moment I have no idea what I am doing but that's fine. I see myself as the Karate Kid learning to _wax on, wax off_ until all of a sudden I know how to build  real web apps!

**Comment by multivac61** [comment]
Oh man, you are right. I was messing around with several apps and must've gotten sidetracked 😅

I'm a C++ developer having a blast learning SvelteKit and by proxy web standards! At the moment I have no idea what I am doing but that's fine. I see myself as the Karate Kid learning to _wax on, wax off_ until all of a sudden I know how to build  real web apps!

**Comment by OffBy0x01** [comment]
I ran into this same issue. In my case it was caused by the template I used which had `/static/favicon.png`, moving it to `/public/favicon.png` resolved the issue.
