### ISSUE TITLE
Dynamic imports do not understand aliases

### ISSUE THREAD

**Issue by GauBen** [sveltejs/kit#9296]
### Describe the bug

Hey! I ran into an issue while trying to use [Vite's dynamic imports](https://vitejs.dev/guide/features.html#dynamic-import) with [SvelteKit's aliases](https://kit.svelte.dev/docs/configuration#alias).

```ts
export const load = () => ({
	// This does not work:
	file: import(`$aliased/${'a'}.json`),
	// This works:
	// file: import(`../aliased/${'a'}.json`),

	// However, both globs below work:
	files1: import.meta.glob('$aliased/*.json'),
	files2: import.meta.glob('../aliased/*.json')
});
```

svelte.config.js:

```ts
const config = {
	kit: {
		adapter: adapter(),
		alias: {
			$aliased: './src/aliased'
		}
	}
};
```

### Reproduction

https://stackblitz.com/edit/sveltejs-kit-template-default-hpsmjr?file=src/routes/+page.js

### Logs

```Shell
4:37:47 PM [vite] warning: 
/home/projects/sveltejs-kit-template-default-hpsmjr/src/routes/+page.js
5  |  export const load = () => ({
6  |    // This does not work:
7  |    file: import(`$aliased/${'a'}.json`),
   |                ^
8  |    // This works:
9  |    // file: import(`../aliased/${'a'}.json`),
The above dynamic import cannot be analyzed by Vite.
See https://github.com/rollup/plugins/tree/master/packages/dynamic-import-vars#limitations for supported dynamic import formats. If this is intended to be left as-is, you can use the /* @vite-ignore */ comment inside the import() call to suppress this warning.

  Plugin: vite:import-analysis
  File: /home/projects/sveltejs-kit-template-default-hpsmjr/src/routes/+page.js
Error: Cannot find module '$aliased/a.json' imported from '/home/projects/sveltejs-kit-template-default-hpsmjr/src/routes/+page.js'
    at nodeImport (file://file:///home/projects/sveltejs-kit-template-default-hpsmjr/node_modules/vite/dist/node/chunks/dep-ca21228b.js:52499:25)
    at ssrImport (file://file:///home/projects/sveltejs-kit-template-default-hpsmjr/node_modules/vite/dist/node/chunks/dep-ca21228b.js:52422:20)
    at ssrDynamicImport (file://file:///home/projects/sveltejs-kit-template-default-hpsmjr/node_modules/vite/dist/node/chunks/dep-ca21228b.js:52449:16)
    at load (/src/routes/+page.js:7:7)
    at Module.load_data (/node_modules/@sveltejs/kit/src/runtime/server/page/load_data.js:162:43)
    at async eval (/node_modules/@sveltejs/kit/src/runtime/server/page/index.js:194:13)
```

### System Info

```Shell
Vite 4.1.4
SvelteKit 1.9.3
```

### Severity

annoyance

**Comment by Rich-Harris** [comment]
This is a Vite issue that we have no control over — see https://github.com/vitejs/vite/issues/10460. Closing since there's nothing we can do on the SvelteKit side
