### ISSUE TITLE
Fetch is not defined with adapter-static and firebase

### ISSUE THREAD

**Issue by jobcespedes** [sveltejs/kit#940]
**Describe the bug**
We were using adapter-static. After we added firebase functions, there is an error when running `npm run build:static`. The error says: `ReferenceError: fetch is not defined`
**Logs**
```
Running 'npm run build:static':

> kio-web-app@0.0.10 build:static /workspace/source
> ADAPTER=@sveltejs/adapter-static OPTIONS={} npm run build


> kio-web-app@0.0.10 build /workspace/source
> svelte-kit build

vite v2.1.4 building for production...
transforming...

warn - Tailwind is not purging unused styles because no template paths have been provided.
warn - If you have manually configured PurgeCSS outside of Tailwind or are deliberately not removing unused styles, set `purge: false` in your Tailwind config file to silence this warning.
warn - https://tailwindcss.com/docs/controlling-file-size/#removing-unused-css
✓ 39 modules transformed.
rendering chunks...
.svelte/output/client/_app/manifest.json                            0.93kb
.svelte/output/client/_app/assets/start-8802ea92.css                3171.54kb / brotli: skipped (large chunk)
.svelte/output/client/_app/pages/sign-up.svelte-65215b67.js         0.52kb / brotli: 0.31kb
.svelte/output/client/_app/assets/pages/index.svelte-51f6bb49.css   0.75kb / brotli: 0.25kb
.svelte/output/client/_app/chunks/vendor-1abd9cb6.js                5.23kb / brotli: 2.04kb
.svelte/output/client/_app/start-f2c65d4b.js                        15.77kb / brotli: 5.36kb
.svelte/output/client/_app/pages/index.svelte-98bfbc41.js           233.63kb / brotli: 59.28kb
vite v2.1.4 building SSR bundle for production...
transforming...
✓ 37 modules transformed.
rendering chunks...
.svelte/output/server/app.js   15998.12kb

Run npm start to try your app locally.

> Using @sveltejs/adapter-static
> fetch is not defined
ReferenceError: fetch is not defined
    at file:///workspace/source/.svelte/output/server/app.js:4280:31
    at ModuleJob.run (internal/modules/esm/module_job.js:152:23)
    at async Loader.import (internal/modules/esm/loader.js:166:24)
    at async prerender (file:///workspace/source/node_modules/@sveltejs/kit/dist/chunks/index6.js:513:14)
    at async AdapterUtils.prerender (file:///workspace/source/node_modules/@sveltejs/kit/dist/chunks/index6.js:745:4)
    at async adapt (/workspace/source/node_modules/@sveltejs/adapter-static/index.js:10:4)
    at async adapt (file:///workspace/source/node_modules/@sveltejs/kit/dist/chunks/index6.js:767:2)
    at async file:///workspace/source/node_modules/@sveltejs/kit/dist/cli.js:633:5
```
**To Reproduce**
`npm run build:static`

**Expected behavior**
Static files are generated

**Information about your SvelteKit Installation:**

<details>
  <summary>Diagnostics</summary>

- The output of `npx envinfo --system --npmPackages svelte,@sveltejs/kit,vite --binaries --browsers`
npx: installed 1 in 1.831s

  System:
    OS: Linux 5.11 CentOS Stream 8
    CPU: (4) x64 Intel(R) Core(TM) i5-4570 CPU @ 3.20GHz
    Memory: 803.47 MB / 15.63 GB
    Container: Yes
    Shell: 4.4.19 - /bin/bash
  Binaries:
    Node: 14.15.4 - ~/.nvm/versions/node/v14.15.4/bin/node
    npm: 6.14.10 - ~/.nvm/versions/node/v14.15.4/bin/npm
  npmPackages:
    @sveltejs/kit: next => 1.0.0-next.71 
    svelte: ^3.29.0 => 3.36.0 
    vite: ^2.1.0 => 2.1.4
- Your browser
None
- Your adapter (e.g. Node, static, Vercel, Begin, etc...)
static
</details>

**Severity**
Blocking firebase integration

Note: the more honest and specific you are here the more we will take you seriously.

**Additional context**
Some versions:
adapter-static: 1.0.0-next.4
firebase/app: 0.6.18
firebase/functions: 0.6.5

file /workspace/source/.svelte/output/server/app.js has around line 4280:
```js
registerFunctions(firebase$1, fetch.bind(self));
```

**Comment by babichjacob** [comment]
Is this still happening?

**Comment by jobcespedes** [comment]
Different message, still cannot use static-adapter with firebase. I tried with:
@sveltejs/adapter-static: 1.0.0-next.9
@sveltejs/kit: 1.0.0-next.107

`npm run build` (static-adapter):
```
Directory import '/src/node_modules/firebase/app' is not supported resolving ES modules imported from /src/.svelte-kit/output/server/
app.js
Did you mean to import firebase/app/dist/index.cjs.js?
Error [ERR_UNSUPPORTED_DIR_IMPORT]: Directory import '/src/node_modules/firebase/app' is not supported resolving ES modules imported fr
om /src/.svelte-kit/output/server/app.js
Did you mean to import firebase/app/dist/index.cjs.js?
    at finalizeResolution (internal/modules/esm/resolve.js:272:17)
    at moduleResolve (internal/modules/esm/resolve.js:699:10)
    at Loader.defaultResolve [as _resolve] (internal/modules/esm/resolve.js:810:11)
    at Loader.resolve (internal/modules/esm/loader.js:86:40)
    at Loader.getModuleJob (internal/modules/esm/loader.js:230:28)
    at ModuleWrap.<anonymous> (internal/modules/esm/module_job.js:56:40)
    at link (internal/modules/esm/module_job.js:55:36)

```

**Comment by jobcespedes** [comment]
Hi, 

Found a workaround after following some pointers from [here](https://sapper.svelte.dev/docs/#Third-party_libraries_that_depend_on_window ) and [here](https://gist.github.com/dyaa/8f8d1f8964160630f2475fe26a2e6150). It combines `onMount` with dynamic importing

**Comment by fernandolguevara** [comment]
i found other workaround 

first install `whatwg-fetch`.

`npm i --save whatwg-fetch` 

create a file `./define-self.js` with this content 

```js
var global =
  (typeof globalThis !== "undefined" && globalThis) ||
  (typeof self !== "undefined" && self) ||
  (typeof global !== "undefined" && global);

if (!global?.self) {
  global.self = global;
}
```

add this script to your index.svelte or  _layout.svelte

```html
<script context="module">
  import "./define-self";
  import "whatwg-fetch";
</script>
```
