### ISSUE TITLE
errors that disapear after 2 reload

### ISSUE THREAD

**Issue by wighawag** [sveltejs/kit#949]
**Describe the bug**
When doing `svelte-kit dev` first time on my project and loading the page, I get some errors, showing both in the console and on the webpage. After reloading twice the error disapear

**Logs**
First load : 
```
TypeError: Cannot read property 'default' of null
    at eval (C:\dev\project\web\src\routes\$layout.svelte:21:66)
    at Object.$$render (C:\dev\project\node_modules\.pnpm\svelte@3.37.0\node_modules\svelte\internal\index.js:1369:22)
    at eval (/C:\dev\project\web\.svelte\dev/generated/root.svelte:60:62)
    at $$render (C:\dev\project\node_modules\.pnpm\svelte@3.37.0\node_modules\svelte\internal\index.js:1369:22)
    at Object.render (C:\dev\project\node_modules\.pnpm\svelte@3.37.0\node_modules\svelte\internal\index.js:1377:26)
    at respond (file:///C:/dev/project/node_modules/.pnpm/@sveltejs+kit@1.0.0-next.71_svelte@3.37.0+vite@2.1.5/node_modules/@sveltejs/kit/dist/ssr.js:2385:28)
    at async respond (file:///C:/dev/project/node_modules/.pnpm/@sveltejs+kit@1.0.0-next.71_svelte@3.37.0+vite@2.1.5/node_modules/@sveltejs/kit/dist/ssr.js:2389:11)
    at async render_page (file:///C:/dev/project/node_modules/.pnpm/@sveltejs+kit@1.0.0-next.71_svelte@3.37.0+vite@2.1.5/node_modules/@sveltejs/kit/dist/ssr.js:2513:19)
    at async file:///C:/dev/project/node_modules/.pnpm/@sveltejs+kit@1.0.0-next.71_svelte@3.37.0+vite@2.1.5/node_modules/@sveltejs/kit/dist/ssr.js:2709:10
    at async ssr (file:///C:/dev/project/node_modules/.pnpm/@sveltejs+kit@1.0.0-next.71_svelte@3.37.0+vite@2.1.5/node_modules/@sveltejs/kit/dist/ssr.js:2696:10)
TypeError: Cannot read property 'default' of null
    at eval (C:\dev\project\web\src\routes\$layout.svelte:21:66)
    at Object.$$render (C:\dev\project\node_modules\.pnpm\svelte@3.37.0\node_modules\svelte\internal\index.js:1369:22)
    at eval (/C:\dev\project\web\.svelte\dev/generated/root.svelte:60:62)
    at $$render (C:\dev\project\node_modules\.pnpm\svelte@3.37.0\node_modules\svelte\internal\index.js:1369:22)
    at Object.render (C:\dev\project\node_modules\.pnpm\svelte@3.37.0\node_modules\svelte\internal\index.js:1377:26)
    at respond (file:///C:/dev/project/node_modules/.pnpm/@sveltejs+kit@1.0.0-next.71_svelte@3.37.0+vite@2.1.5/node_modules/@sveltejs/kit/dist/ssr.js:2385:28)
    at async respond (file:///C:/dev/project/node_modules/.pnpm/@sveltejs+kit@1.0.0-next.71_svelte@3.37.0+vite@2.1.5/node_modules/@sveltejs/kit/dist/ssr.js:2389:11)
    at async render_page (file:///C:/dev/project/node_modules/.pnpm/@sveltejs+kit@1.0.0-next.71_svelte@3.37.0+vite@2.1.5/node_modules/@sveltejs/kit/dist/ssr.js:2513:19)
    at async file:///C:/dev/project/node_modules/.pnpm/@sveltejs+kit@1.0.0-next.71_svelte@3.37.0+vite@2.1.5/node_modules/@sveltejs/kit/dist/ssr.js:2709:10
    at async ssr (file:///C:/dev/project/node_modules/.pnpm/@sveltejs+kit@1.0.0-next.71_svelte@3.37.0+vite@2.1.5/node_modules/@sveltejs/kit/dist/ssr.js:2696:10)
``` 

Second load :
```
TypeError: Cannot read property 'default' of null
    at eval (C:\dev\project\web\src\routes\$layout.svelte:21:66)
    at Object.$$render (C:\dev\project\node_modules\.pnpm\svelte@3.37.0\node_modules\svelte\internal\index.js:1369:22)
    at root.svelte:42:13
    at $$render (C:\dev\project\node_modules\.pnpm\svelte@3.37.0\node_modules\svelte\internal\index.js:1369:22)
    at Object.render (C:\dev\project\node_modules\.pnpm\svelte@3.37.0\node_modules\svelte\internal\index.js:1377:26)
    at respond (file:///C:/dev/project/node_modules/.pnpm/@sveltejs+kit@1.0.0-next.71_svelte@3.37.0+vite@2.1.5/node_modules/@sveltejs/kit/dist/ssr.js:2385:28)
    at async respond (file:///C:/dev/project/node_modules/.pnpm/@sveltejs+kit@1.0.0-next.71_svelte@3.37.0+vite@2.1.5/node_modules/@sveltejs/kit/dist/ssr.js:2389:11)
    at async render_page (file:///C:/dev/project/node_modules/.pnpm/@sveltejs+kit@1.0.0-next.71_svelte@3.37.0+vite@2.1.5/node_modules/@sveltejs/kit/dist/ssr.js:2513:19)
    at async file:///C:/dev/project/node_modules/.pnpm/@sveltejs+kit@1.0.0-next.71_svelte@3.37.0+vite@2.1.5/node_modules/@sveltejs/kit/dist/ssr.js:2709:10
    at async ssr (file:///C:/dev/project/node_modules/.pnpm/@sveltejs+kit@1.0.0-next.71_svelte@3.37.0+vite@2.1.5/node_modules/@sveltejs/kit/dist/ssr.js:2696:10)
```

After another reload, it works fine

**To Reproduce**
Currently i cannot publish the project in question. 

**Expected behavior**
I expect no errors to happen

**Information about your SvelteKit Installation:**

- The output of `npx envinfo --system --npmPackages svelte,@sveltejs/kit,vite --binaries --browsers`

```
  System:
    OS: Windows 10 10.0.19042
    CPU: (8) x64 Intel(R) Core(TM) i7-7700HQ CPU @ 2.80GHz
    Memory: 3.13 GB / 15.89 GB
  Binaries:
    Node: 14.16.0 - D:\scoop\wighawag\apps\nvm\current\nodejs\nodejs\node.EXE
    Yarn: 1.22.5 - D:\scoop\wighawag\apps\yarn\current\Yarn\bin\yarn.CMD
    npm: 6.14.11 - D:\scoop\wighawag\apps\nvm\current\nodejs\nodejs\npm.CMD
  Browsers:
    Edge: Spartan (44.19041.423.0), Chromium (89.0.774.75)
    Internet Explorer: 11.0.19041.1
  npmPackages:
    svelte: ^3.37.0 => 3.37.0
```

**Severity**
This is currently an annoyance as I need to reload the app twice to get started, but this might also indicate a deeper problem

**Comment by akaufmann** [comment]
I see this error with barrel imports. Do you "export from" a module's default export and import it into $layout.svelte? Something like...
```svelte
// e.g. /foo/index.ts
export { default as Foo } from "mod";

// $layout.svelte
<script>
import { Foo } from "<path/to/foo/index.ts>"
...
</script>
```

**Comment by wighawag** [comment]
Hi @akaufmann 

no, it import

-  some typescript file (which do not have barrel imports
- a css file
- and 3 svelte components

See:

```
<script>
  import '../service-worker-handler';
  import '../global.css';
  import Notifications from '$lib/components/notification/Notifications.svelte';
  import NoInstallPrompt from '$lib/components/NoInstallPrompt.svelte';
  import NewVersionNotification from '$lib/components/NewVersionNotification.svelte';
</script>

<svelte:head>
  <title>A title</title>
</svelte:head>

<NoInstallPrompt />
<NewVersionNotification />

<slot />
<Notifications />
```

**Comment by PythonCreator27** [comment]
It seems to have something to do with what @akaufmann pointed out. @wighawag Can you please post the contents of your `$layout.svelte`, or, at the very least, line 26 of it? That would help in figuring out the problem.

**Comment by wighawag** [comment]
@PythonCreator27 I posted the content of it above. It has not 26 lines, so there are probably some issue with sourcemap too

**Comment by Conduitry** [comment]
Without a reproduction, there's not anything anyone can reasonably do. Comment on this issue or open a new issue when you have a (preferably minimal) reproduction you can share.

**Comment by wighawag** [comment]
I understand, something that could be useful is a more verbose output when such error happen?
