### ISSUE TITLE
Destructuring formData from the request object in Actions results in a 500

### ISSUE THREAD

**Issue by mastorm** [sveltejs/kit#9491]
### Describe the bug

When destructuring formData from an action event and then invoking it, the action results in a 500.

```js
export const actions = {
	broken: async ({ request: { formData } }) => {
		const fd = await formData();
	},
	working: async ({ request }) => {
		const fd = await request.formData();
	}
};
```

### Reproduction

https://stackblitz.com/edit/sveltejs-kit-template-default-ls9xhf?file=src/routes/+page.server.js

### Logs

```Shell
TypeError: Illegal invocation
    at webidl.brandCheck (C:\Projects\Repositories\NetworkBox\Network-Box.E-Learning-Portal\source\elearning-portal\node_modules\undici\lib\fetch\webidl.js:38:11)
    at formData (C:\Projects\Repositories\NetworkBox\Network-Box.E-Learning-Portal\source\elearning-portal\node_modules\undici\lib\fetch\body.js:364:14)
    at createCourse (C:/Projects/Repositories/NetworkBox/Network-Box.E-Learning-Portal/source/elearning-portal/src/routes/[lang]/admin/courses/(index)/+page.server.ts:7:21)
    at call_action (/node_modules/@sveltejs/kit/src/runtime/server/page/actions.js:221:9)
    at Module.handle_action_request (/node_modules/@sveltejs/kit/src/runtime/server/page/actions.js:142:22)
    at Module.render_page (/node_modules/@sveltejs/kit/src/runtime/server/page/index.js:63:25)
    at async resolve (/node_modules/@sveltejs/kit/src/runtime/server/respond.js:369:17)
    at async handleAuth (C:/Projects/Repositories/NetworkBox/Network-Box.E-Learning-Portal/source/elearning-portal/src/auth.server.ts:23:8)
    at async Module.respond (/node_modules/@sveltejs/kit/src/runtime/server/respond.js:240:20)
    at async file:///C:/Projects/Repositories/NetworkBox/Network-Box.E-Learning-Portal/source/elearning-portal/node_modules/@sveltejs/kit/src/exports/vite/dev/index.js:505:22
```

### System Info

```Shell
This happens on both windows an linux.

success Install finished in 1.126s


  System:
    OS: Linux 5.0 undefined
    CPU: (8) x64 Intel(R) Core(TM) i9-9880H CPU @ 2.30GHz
    Memory: 0 Bytes / 0 Bytes
    Shell: 1.0 - /bin/jsh
  Binaries:
    Node: 16.14.2 - /usr/local/bin/node
    Yarn: 1.22.19 - /usr/local/bin/yarn
    npm: 7.17.0 - /usr/local/bin/npm
  npmPackages:
    @sveltejs/adapter-auto: ^2.0.0 => 2.0.0 
    @sveltejs/kit: ^1.5.0 => 1.13.0 
    svelte: ^3.54.0 => 3.57.0 
    vite: ^4.2.0 => 4.2.1
```

### Severity

serious, but I can work around it

### Additional Information

I was lucky to find out what was the cause here. If one wasnt as lucky as me and was running into this bug, this could seriously block them for a long time.

**Comment by dummdidumm** [comment]
There's nothing we can do about that. I suppose that `Request` is a class object, which can't be destructured (the method's context is lost and all sorts of weird stuff happens then). Not sure if we can swoop in an catch this somehow to print a more meaningful error.

**Comment by mastorm** [comment]
Maybe this could be warned about in the docs? But I totally understand that this is out of your control. It just feels like this is a behaviour that sveltekit exposes, even though it's just the api surface of a dependeny thats breaking.
