### ISSUE TITLE
adapter-static build fails if static file has space in the file name

### ISSUE THREAD

**Issue by MadeBaruna** [sveltejs/kit#950]
**Describe the bug**
Static file with space in the file name will fail when building with adapter-static with Error: 404

**Logs**
```
Using @sveltejs/adapter-static
404 /images/test%20image.png
Error: 404 /images/test%20image.png
```

**To Reproduce**
Add a static file with space in the filename, then build with adapter-static
Repo: https://github.com/MadeBaruna/sveltekit-bug-static

**Expected behavior**
Should successfully build the project

**Stacktraces**

<details>
  <summary>Stack trace</summary>

```
> svelte-bug-static@0.0.1 build /home/baruna/svelte-bug-static
> svelte-kit build

vite v2.1.5 building for production...
✓ 18 modules transformed.
.svelte/output/client/_app/manifest.json                            0.67kb
.svelte/output/client/_app/assets/start-d4cd1237.css                0.29kb / brotli: 0.18kb
.svelte/output/client/_app/assets/pages/index.svelte-27172613.css   0.69kb / brotli: 0.26kb
.svelte/output/client/_app/pages/index.svelte-7968be67.js           1.73kb / brotli: 0.76kb
.svelte/output/client/_app/chunks/vendor-b2527fc7.js                5.14kb / brotli: 2.00kb
.svelte/output/client/_app/start-a5f0fa97.js                        15.52kb / brotli: 5.28kb
vite v2.1.5 building SSR bundle for production...
✓ 16 modules transformed.
.svelte/output/server/app.js   70.81kb

Run npm start to try your app locally.

> Using @sveltejs/adapter-static
> 404 /images/test%20image.png
Error: 404 /images/test%20image.png
    at error (file:///home/baruna/svelte-bug-static/node_modules/.pnpm/@sveltejs+kit@1.0.0-next.71_svelte@3.37.0+vite@2.1.5/node_modules/@sveltejs/kit/dist/chunks/index6.js:526:11)
    at visit (file:///home/baruna/svelte-bug-static/node_modules/.pnpm/@sveltejs+kit@1.0.0-next.71_svelte@3.37.0+vite@2.1.5/node_modules/@sveltejs/kit/dist/chunks/index6.js:581:5)
    at async visit (file:///home/baruna/svelte-bug-static/node_modules/.pnpm/@sveltejs+kit@1.0.0-next.71_svelte@3.37.0+vite@2.1.5/node_modules/@sveltejs/kit/dist/chunks/index6.js:651:7)
    at async prerender (file:///home/baruna/svelte-bug-static/node_modules/.pnpm/@sveltejs+kit@1.0.0-next.71_svelte@3.37.0+vite@2.1.5/node_modules/@sveltejs/kit/dist/chunks/index6.js:684:5)
    at async AdapterUtils.prerender (file:///home/baruna/svelte-bug-static/node_modules/.pnpm/@sveltejs+kit@1.0.0-next.71_svelte@3.37.0+vite@2.1.5/node_modules/@sveltejs/kit/dist/chunks/index6.js:745:4)
    at async adapt (/home/baruna/svelte-bug-static/node_modules/.pnpm/@sveltejs+adapter-static@1.0.0-next.4/node_modules/@sveltejs/adapter-static/index.js:10:4)
    at async adapt (file:///home/baruna/svelte-bug-static/node_modules/.pnpm/@sveltejs+kit@1.0.0-next.71_svelte@3.37.0+vite@2.1.5/node_modules/@sveltejs/kit/dist/chunks/index6.js:767:2)
    at async file:///home/baruna/svelte-bug-static/node_modules/.pnpm/@sveltejs+kit@1.0.0-next.71_svelte@3.37.0+vite@2.1.5/node_modules/@sveltejs/kit/dist/cli.js:633:5
 ERROR  Command failed with exit code 1.
```
</details>

**Information about your SvelteKit Installation:**

<details>
  <summary>Diagnostics</summary>

- The output of `npx envinfo --system --npmPackages svelte,@sveltejs/kit,vite --binaries --browsers`
```
  System:
    OS: Linux 4.19 Ubuntu 20.04 LTS (Focal Fossa)
    CPU: (8) x64 Intel(R) Core(TM) i5-8265U CPU @ 1.60GHz
    Memory: 3.34 GB / 4.82 GB
    Container: Yes
    Shell: 5.8 - /usr/bin/zsh
  Binaries:
    Node: 14.16.0 - ~/.nvm/versions/node/v14.16.0/bin/node
    Yarn: 1.22.4 - /usr/bin/yarn
    npm: 6.14.11 - ~/.nvm/versions/node/v14.16.0/bin/npm
  npmPackages:
    @sveltejs/kit: next => 1.0.0-next.71 
    svelte: ^3.29.0 => 3.37.0 
    vite: ^2.1.0 => 2.1.5 
```

- Your browser
Chromium Edge

- Your adapter (e.g. Node, static, Vercel, Begin, etc...)
static
</details>

**Severity**
Blocking me from migrating from sapper, because I use many images with space in the filename

**Additional context**

**Comment by destari** [comment]
Seeing this as well

**Comment by ignatiusmb** [comment]
I can't reproduce this in the latest versions of kit and adapter-static.
