### ISSUE TITLE
Build breaks since 1.15.11 when importing a file asynchronously in onMount (and using a monorepo?)

### ISSUE THREAD

**Issue by flayks** [sveltejs/kit#9843]
### Describe the bug

~~Since the v1.15.11, the build breaks when importing a file asynchronously in `onMount` like so:~~

It appears to be linked to imports, in this case the `defineConfig` and `renderStudio` from Sanity

```svelte
<script lang="ts">
    import { onMount } from 'svelte'
    import { defineConfig, renderStudio } from 'sanity'

    let studioEl: HTMLDivElement

    onMount(async () => {
        const { default: config } = await import('sanity-studio/sanity.config')
        //                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

        if (studioEl) {
            const sanityConfig = defineConfig({
                ...config,
                // Replace options with env variables
                projectId: import.meta.env.VITE_SANITY_ID,
                dataset: import.meta.env.VITE_SANITY_DATASET,
            })

            renderStudio(studioEl, sanityConfig)
        }
    })
</script>
```

Rolling back to 1.15.10 works as expected, it build fine. 1.16.00 also breaks builds.

### Reproduction

My project is quite big and using a monorepo so a repro would be complex but it is definitely linked to importing a file from another Monorepo package, or importing a file using `await import()`

https://github.com/flayks/sk-bug-1.15.11

### Logs

```Shell
[vite-plugin-sveltekit-compile] Could not find file ".svelte-kit/generated/client-optimized/nodes/4.js" in Vite manifest
✓ built in 17.38s
error during build:
Error: Could not find file ".svelte-kit/generated/client-optimized/nodes/4.js" in Vite manifest
    at resolve_symlinks (file:///Users/flayks/sites/project/website/node_modules/.pnpm/@sveltejs+kit@1.15.11_svelte@3.58.0_vite@4.3.4/node_modules/@sveltejs/kit/src/exports/vite/build/utils.js:77:28)
    at find_deps (file:///Users/flayks/sites/project/website/node_modules/.pnpm/@sveltejs+kit@1.15.11_svelte@3.58.0_vite@4.3.4/node_modules/@sveltejs/kit/src/exports/vite/build/utils.js:58:26)
    at file:///Users/flayks/sites/project/website/node_modules/.pnpm/@sveltejs+kit@1.15.11_svelte@3.58.0_vite@4.3.4/node_modules/@sveltejs/kit/src/exports/vite/build/build_server.js:72:18
    at Array.forEach (<anonymous>)
    at build_server_nodes (file:///Users/flayks/sites/project/website/node_modules/.pnpm/@sveltejs+kit@1.15.11_svelte@3.58.0_vite@4.3.4/node_modules/@sveltejs/kit/src/exports/vite/build/build_server.js:33:22)
    at Object.handler (file:///Users/flayks/sites/project/website/node_modules/.pnpm/@sveltejs+kit@1.15.11_svelte@3.58.0_vite@4.3.4/node_modules/@sveltejs/kit/src/exports/vite/index.js:737:5)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async PluginDriver.hookParallel (file:///Users/flayks/sites/project/website/node_modules/.pnpm/rollup@3.21.4/node_modules/rollup/dist/es/shared/node-entry.js:24459:17)
    at async file:///Users/flayks/sites/project/website/node_modules/.pnpm/rollup@3.21.4/node_modules/rollup/dist/es/shared/node-entry.js:25820:13
    at async catchUnfinishedHookActions (file:///Users/flayks/sites/project/website/node_modules/.pnpm/rollup@3.21.4/node_modules/rollup/dist/es/shared/node-entry.js:24900:20)
```

### System Info

```Shell
System:
    OS: macOS 13.3
    CPU: (12) arm64 Apple M2 Max
    Memory: 422.41 MB / 32.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 18.16.0 - ~/Library/pnpm/node
    npm: 9.6.5 - ~/Library/pnpm/npm
  Browsers:
    Brave Browser: 112.1.50.121
    Firefox: 110.0.1
    Safari: 16.4
```

### Severity

blocking an upgrade

**Comment by dummdidumm** [comment]
cc @gtm-nayan , probably related to #9808 - though we still need a reproduction if that snippet isn't enough to reproduce

**Comment by flayks** [comment]
Sure, I'll try to reproduce that with a very basic repro

**Comment by flayks** [comment]
@dummdidumm it might be related to Sanity at this stage? Not very sure, but I tried to reproduce it as minimal as possible using my use case: rendering a Sanity Studio on a route using `onMount`

https://github.com/flayks/sk-bug-1.15.11

As it, the build breaks with a similar error. If you comment the [line #3](https://github.com/flayks/sk-bug-1.15.11/blob/39c8dbd4c408c29d94ec446386ce81679365b0b5/apps/website/src/routes/%2Bpage.svelte#L3), it builds normally 🤷

`import { defineConfig, renderStudio } from 'sanity'`

**Comment by gtm-nayan** [comment]
it was probably #9811 instead, although it seems I forgot to push the changeset for that one.

Some of my assumptions around how the vite manifest works didn't hold true, I thought the nodes would be present as is in the manifest but they get renamed if the bundler decides to put in more stuff into them.

Does anyone know if there is a way in vite/rollup to track which chunk a module ends up in?

**Comment by multiplehats** [comment]
I have the same error:

```
Error: Could not find file ".svelte-kit/generated/client-optimized/nodes/15.js" in Vite manifest
    at resolve_symlink
 ```
 
Also using Sanity Studio.

SanityStudio.svelte
```svelte
<script lang="ts">
	import { renderStudio, defineConfig, type StudioProps } from 'sanity';
	import { onMount } from 'svelte';

	export let config: StudioProps['config'];

	let studioEl: HTMLDivElement;

	onMount(() => {
		if (studioEl) {
			const sanityConfig = defineConfig(config);

			renderStudio(studioEl, sanityConfig);
		}
	});
</script>

<svelte:head>
	<meta name="viewport" content="width=device-width, initial-scale=1, viewport-fit=cover" />
	<meta name="robots" content="noindex" />
	<meta name="referrer" content="same-origin" />
</svelte:head>

<div id="studio">
	<div bind:this={studioEl} />
</div>

<style>
	:global(body) {
		margin: 0;
	}

	#studio {
		height: 100vh;
	}

	#studio > div {
		height: 100%;
	}
</style>
```

```svelte
<script lang="ts">
	import config from '$core/sanity/sanity.config';
	import SanityStudio from '$components/misc/SanityStudio.svelte';
</script>

<SanityStudio {config} />
```

Sanity's config looks like this
```ts
import { defineConfig } from 'sanity';

export default defineConfig({
	basePath: '/studio',
	projectId,
	dataset,
	title: 'landing.gallery',
});
```

**Comment by brandtam** [comment]
Similar error on build here with https://github.com/brandtam/sveltekit-sanity-starter 

If you clone and build now it works. But if you change 
```
"@sveltejs/kit": "1.15.10",
```

to 
```
"@sveltejs/kit": "1.15.10",
```

in package.json to allow a for a newer version of Kit and then build it will break with the `Error: Could not find file ".svelte-kit/generated/client-optimized/nodes/5.js" in Vite manifest` error.

**Comment by gyurielf** [comment]
I don't use sanity, but got the same error.
