### ISSUE TITLE
Build fail on `@sveltejs/adapter-cloudflare`

### ISSUE THREAD

**Issue by GoodGoodJM** [sveltejs/kit#9983]
### Describe the bug

Our project hosted on vercel. We decide move to cloudflare.

We checked docs(https://kit.svelte.dev/docs/adapter-cloudflare, https://developers.cloudflare.com/pages/framework-guides/deploy-a-svelte-site/) and install adapter and try to build(`"build": "CF_PAGES=1 vite build"`)

But build occur error and logs(see attached logs).

In my opinion, the compiler can't compile the ts.
 

### Reproduction

install @sveltejs/adapter-cloudflare and build(`"build": "CF_PAGES=1 vite build"`)

### Logs

```Shell
npm run build

> front@0.0.1 build
> CF_PAGES=1 vite build


vite v4.0.4 building SSR bundle for production...
✓ 1 modules transformed.
[vite-plugin-svelte] /src/routes/+layout.svelte:7:13 Unexpected token
file: /Users/goodgoodman/work/cozy/cozy/front/src/routes/+layout.svelte:7:13
  5 |    import '../app.css';
  6 |    import { userContext } from '$lib/context/user';
  7 |    import type { LayoutData } from './$types';
                     ^
  8 |    import { browser } from '$app/environment';
  9 |    import { goto } from '$app/navigation';
error during build:
ParseError: Unexpected token
    at error (file:///Users/goodgoodman/work/cozy/cozy/front/node_modules/svelte/compiler.mjs:13140:19)
    at Parser$1.error (file:///Users/goodgoodman/work/cozy/cozy/front/node_modules/svelte/compiler.mjs:13218:9)
    at Parser$1.acorn_error (file:///Users/goodgoodman/work/cozy/cozy/front/node_modules/svelte/compiler.mjs:13212:14)
    at Object.read_script [as read] (file:///Users/goodgoodman/work/cozy/cozy/front/node_modules/svelte/compiler.mjs:8999:16)
    at tag (file:///Users/goodgoodman/work/cozy/cozy/front/node_modules/svelte/compiler.mjs:12164:33)
    at new Parser$1 (file:///Users/goodgoodman/work/cozy/cozy/front/node_modules/svelte/compiler.mjs:13177:21)
    at parse$a (file:///Users/goodgoodman/work/cozy/cozy/front/node_modules/svelte/compiler.mjs:13317:20)
    at compile (file:///Users/goodgoodman/work/cozy/cozy/front/node_modules/svelte/compiler.mjs:43782:17)
    at compileSvelte2 (file:///Users/goodgoodman/work/cozy/cozy/front/node_modules/@sveltejs/vite-plugin-svelte/dist/index.js:573:22)
    at async Object.transform (file:///Users/goodgoodman/work/cozy/cozy/front/node_modules/@sveltejs/vite-plugin-svelte/dist/index.js:2373:25)
```

### System Info

```Shell
npx envinfo --system --binaries --browsers --npmPackages "{svelte,@sveltejs/*,vite}"

  System:
    OS: macOS 12.5
    CPU: (8) arm64 Apple M1 Pro
    Memory: 80.52 MB / 16.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 18.7.0 - ~/.asdf/installs/nodejs/18.7.0/bin/node
    npm: 8.15.0 - ~/.asdf/plugins/nodejs/shims/npm
  Browsers:
    Chrome: 113.0.5672.126
    Firefox: 112.0.2
    Safari: 15.6
  npmPackages:
    @sveltejs/adapter-auto: ^1.0.0 => 1.0.2
    @sveltejs/adapter-cloudflare: ^2.2.4 => 2.2.4
    @sveltejs/kit: ^1.16.2 => 1.18.0
    svelte: ^3.58.0 => 3.58.0
    vite: ^4.0.0 => 4.0.4
```

### Severity

blocking all usage of SvelteKit

**Comment by GoodGoodJM** [comment]
I attached relevant part of code to logs.
```svelte
// ./src/routes/+layout.svelte
<script lang="ts">
	import { getAuth, onIdTokenChanged } from 'firebase/auth';
	import { onMount } from 'svelte';
	import '$lib/firebase/client';
	import '../app.css';
	import { userContext } from '$lib/context/user';
	import type { LayoutData } from './$types';
/** ... */
```

**Comment by GoodGoodJM** [comment]
@gtm-nayan Yes, you are right. I accidentally deleted the preprocessor, and since I restored it, it goes a little further.

```bash
> Using @sveltejs/adapter-cloudflare
✘ [ERROR] Could not resolve "@firebase/database-compat/standalone"

    node_modules/firebase-admin/lib/app/firebase-namespace.js:106:41:
      106 │         return Object.assign(fn, require('@firebase/database-compat/standalone'));
          ╵                                          ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

  The path "./standalone" is not currently exported by package "@firebase/database-compat":

    node_modules/@firebase/database-compat/package.json:16:13:
      16 │   "exports": {
         ╵              ^

  None of the conditions provided ("types", "node") match any of the currently active conditions
  ("browser", "default", "require", "worker"):

    node_modules/@firebase/database-compat/package.json:27:20:
      27 │     "./standalone": {
         ╵                     ^

  Consider enabling the "types" condition if this package expects it to be enabled. You can use
  "conditions: ['types']" to do that:

    node_modules/@firebase/database-compat/package.json:28:6:
      28 │       "types": "./dist/database-compat/src/index.standalone.d.ts",
         ╵       ~~~~~~~

  You can mark the path "@firebase/database-compat/standalone" as external to exclude it from the
  bundle, which will remove this error. You can also surround this "require" call with a try/catch
  block to handle this failure at run-time instead of bundle-time.

✘ [ERROR] Could not resolve "fs"
...

```

**Comment by GoodGoodJM** [comment]
https://github.com/firebase/firebase-admin-node/issues/2069

I think it should be solved in firebase-admin, I realized it during the reproduction. Thank you to those who have responded to this issue.
