### ISSUE TITLE
Vercel - Error: Could not load function config

### ISSUE THREAD

**Issue by mikenikles** [sveltejs/kit#9998]
### Describe the bug

I upgraded `@sveltejs/adapter-vercel` from 1.0.6 to the latest `3.0.0` and builds on Vercel now fail with the following build error: `Error: Could not load function config: "/vercel/output/functions/render.func/.vc-config.json"`

### Reproduction

N/A

### Logs

```Shell
Vercel build output:

Run npm run preview to preview your production build locally.

> Using @sveltejs/adapter-vercel
  Warning: The following modules failed to locate dependencies that may (or may not) be required for your app to work:
  ../../node_modules/.pnpm/node-fetch@2.6.7/node_modules/node-fetch/lib/index.js
    - encoding
  ✔ done
✓ built in 13.29s
Build Completed in /vercel/output [41s]
Error: Could not load function config: "/vercel/output/functions/render.func/.vc-config.json"
    at m6 (/var/task/sandbox.js:242:3444)
    at async Fve (/var/task/sandbox.js:247:11233)
    at async k2t (/var/task/sandbox.js:262:1923)
    at async I2t (/var/task/sandbox.js:262:1724)
Deployment completed
: Could not load function config: "/vercel/output/functions/render.func/.vc-config.json"
```

### System Info

```Shell
System:
    OS: Linux 6.1 Ubuntu 22.04.2 LTS 22.04.2 LTS (Jammy Jellyfish)
    CPU: (16) x64 AMD EPYC 7B13
    Memory: 36.42 GB / 62.79 GB
    Container: Yes
    Shell: 5.1.16 - /bin/bash
  Binaries:
    Node: 18.16.0 - ~/.nvm/versions/node/v18.16.0/bin/node
    Yarn: 1.22.19 - ~/.nvm/versions/node/v18.16.0/bin/yarn
    npm: 9.5.1 - ~/.nvm/versions/node/v18.16.0/bin/npm
  npmPackages:
    @sveltejs/adapter-vercel: 3.0.0 => 3.0.0 
    @sveltejs/kit: 1.18.0 => 1.18.0 
    svelte: ^3.59.1 => 3.59.1 
    vite: ^4.3.8 => 4.3.8
```

### Severity

blocking an upgrade

### Additional Information

It looks like this was introduced in `@sveltejs/adapter-vercel` version `2.0.0`.

This works:

```
  npmPackages:
    @sveltejs/adapter-vercel: 1.0.6 => 1.0.6
    @sveltejs/kit: 1.18.0 => 1.18.0 
    svelte: ^3.59.1 => 3.59.1 
    vite: ^4.3.8 => 4.3.8
```

while this doesn't work:

```
  npmPackages:
    @sveltejs/adapter-vercel: 2.0.0 => 2.0.0 
    @sveltejs/kit: 1.18.0 => 1.18.0 
    svelte: ^3.59.1 => 3.59.1 
    vite: ^4.3.8 => 4.3.8
```

**Comment by mikenikles** [comment]
I have the following custom `vercel-build` script:

```
"vercel-build": "prisma migrate deploy && pnpm build && mkdir -p .vercel/output/functions/render.func/@devtomio && cp -r ../../node_modules/.pnpm/@devtomio+sodium-linux-x64-gnu@0.3.0/node_modules/@devtomio/sodium-linux-x64-gnu .vercel/output/functions/render.func/@devtomio"
```

When I inspected the Vercel build output, I noticed `.vercel` changed to `/vercel`. I updated my `vercel-build` script accordingly and now the build fails with the same error as reported, but:

```diff
-.vercel/output/functions/render.func/.vc-config.json
+/vercel/output/functions/render.func/.vc-config.json
```

**Comment by mikenikles** [comment]
This is caused by the following `vercel-build` script:

```
"vercel-build": "prisma migrate deploy && pnpm build && mkdir -p /vercel/output/functions/render.func/@devtomio && cp -r ../../node_modules/.pnpm/@devtomio+sodium-linux-x64-gnu@0.3.0/node_modules/@devtomio/sodium-linux-x64-gnu /vercel/output/functions/render.func/@devtomio && ls -ltra /vercel/output/functions/render.func/"
```

**Comment by mikenikles** [comment]
Figured it out:

```diff
-.vercel/output/functions/render.func/
+.vercel/output/functions/fn.func/
```
